// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Graphic ../../../core/Accessor ../../../core/Collection ../../../core/Error ../../../core/has ../../../core/MapUtils ../../../core/maybe ../../../core/promiseUtils ../../../core/reactiveUtils ../../../core/unitUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../geometry/Extent ../../../geometry/support/scaleUtils ../../../layers/support/floorFilterUtils ../../../renderers/support/clickToleranceUtils ../../../rest/identify ../../../rest/support/IdentifyParameters ../../../support/arcadeOnDemand ../../../symbols/SimpleMarkerSymbol ./popupUtils".split(" "),
function(K,u,t,x,L,M,N,E,O,P,y,F,Q,R,z,da,ea,S,T,U,V,G,W,X,Y,H,I){function J(r,n,l){const c=[],a=b=>{var d=0===b.minScale||n<=b.minScale;const p=0===b.maxScale||n>=b.maxScale;b.visible&&d&&p&&(b.sublayers?b.sublayers.forEach(a):b.popupEnabled&&(d=I.getFetchPopupTemplate(b,{...l,defaultPopupTemplateEnabled:!1}),y.isSome(d)&&c.unshift({sublayer:b,popupTemplate:d})))};(r?.toArray()??[]).reverse().map(a);return c}function Z(r){return r.expressionInfos?.length||Array.isArray(r.content)&&r.content.some(n=>
"expression"===n.type)?Y.loadArcade():Promise.resolve()}function aa(r,n){return B.apply(this,arguments)}function B(){B=t._asyncToGenerator(function*(r,n){if(r.capabilities?.operations?.supportsQuery)return!0;try{return yield Promise.any(n.map(({sublayer:l})=>l.load().then(()=>l.capabilities.operations.supportsQuery)))}catch{return!1}});return B.apply(this,arguments)}function ba(r,n){return C.apply(this,arguments)}function C(){C=t._asyncToGenerator(function*(r,n){const l=r.renderer;l&&"defaultSymbol"in
l&&!l.defaultSymbol&&(n=l.valueExpression?yield Promise.all(n.map(c=>l.getSymbolAsync(c).then(a=>a?c:null))).then(c=>c.filter(a=>null!=a)):n.filter(c=>null!=l.getSymbol(c)));return n});return C.apply(this,arguments)}let D=null;u.MapServiceLayerViewHelper=function(r){function n(c){var a=r.call(this,c)||this;a._featuresResolutions=new WeakMap;a.highlightGraphics=null;a.highlightGraphicUpdated=null;a.updateHighlightedFeatures=F.debounce(function(){var b=t._asyncToGenerator(function*(d){a.destroyed||
a.updatingHandles.addPromise(a._updateHighlightedFeaturesGeometries(d).catch(()=>{}))});return function(d){return b.apply(this,arguments)}}());return a}t._inheritsLoose(n,r);var l=n.prototype;l.initialize=function(){const c=a=>{this.updatingHandles.addPromise(this._updateHighlightedFeaturesSymbols(a).catch(()=>{}));this.updateHighlightedFeatures(this._highlightGeometriesResolution)};this.addHandles([Q.on(()=>this.highlightGraphics,"change",a=>c(a.added),{onListenerAdd:a=>c(a)})])};l.fetchPopupFeatures=
function(){var c=t._asyncToGenerator(function*(a,b){const {layerView:{layer:d,view:{scale:p}}}=this;if(!a)throw new E("fetchPopupFeatures:invalid-area","Nothing to fetch without area",{layer:d});const f=J(d.sublayers,p,b);if(!f.length)return[];const q=yield aa(d,f);if(!((d.capabilities?.operations?.supportsIdentify??!0)&&10.5<=d.version||q))throw new E("fetchPopupFeatures:not-supported","query operation is disabled for this service",{layer:d});return q?this._fetchPopupFeaturesUsingQueries(a,f,b):
this._fetchPopupFeaturesUsingIdentify(a,f,b)});return function(a,b){return c.apply(this,arguments)}}();l.clearHighlights=function(){this.highlightGraphics?.removeAll()};l.highlight=function(c){const a=this.highlightGraphics;if(!a)return{remove(){}};let b=null;c instanceof L?b=[c]:N.isCollection(c)&&0<c.length?b=c.toArray():Array.isArray(c)&&0<c.length&&(b=c);b=b?.filter(y.isSome);if(!b||!b.length)return{remove:()=>{}};for(const d of b)c=d.sourceLayer,null!=c&&"geometryType"in c&&"point"===c.geometryType&&
(d.visible=!1);a.addMany(b);return{remove:()=>{a.removeMany(b??[])}}};l._updateHighlightedFeaturesSymbols=function(){var c=t._asyncToGenerator(function*(a){const {layerView:{view:b},highlightGraphics:d,highlightGraphicUpdated:p}=this;if(d&&p)for(const f of a){const q=f.sourceLayer&&"renderer"in f.sourceLayer&&f.sourceLayer.renderer;f.sourceLayer&&"geometryType"in f.sourceLayer&&"point"===f.sourceLayer.geometryType&&q&&"getSymbolAsync"in q&&q.getSymbolAsync(f).then(function(){var m=t._asyncToGenerator(function*(e){e||
(e=new H);let g=null;const h="visualVariables"in q?q.visualVariables?.find(k=>"size"===k.type):void 0;h&&(D||(D=(yield new Promise((k,v)=>K(["../../../renderers/visualVariables/support/visualVariableUtils"],k,v))).getSize),g=D(h,f,{view:b.type,scale:b.scale,shape:"simple-marker"===e.type?e.style:null}));g||(g="width"in e&&"height"in e&&null!=e.width&&null!=e.height?Math.max(e.width,e.height):"size"in e?e.size:16);d.includes(f)&&(f.symbol=new H({style:"square",size:g,xoffset:"xoffset"in e?e.xoffset:
0,yoffset:"yoffset"in e?e.yoffset:0}),p(f,"symbol"),f.visible=!0)});return function(e){return m.apply(this,arguments)}}())}});return function(a){return c.apply(this,arguments)}}();l._updateHighlightedFeaturesGeometries=function(){var c=t._asyncToGenerator(function*(a){const {layerView:{layer:b,view:d},highlightGraphics:p,highlightGraphicUpdated:f}=this;this._highlightGeometriesResolution=a;if(f&&p?.length&&b.capabilities.operations.supportsQuery){var q=this._getTargetResolution(a);a=new Map;for(var m of p)(!this._featuresResolutions.has(m)||
this._featuresResolutions.get(m)>q)&&P.getOrCreateMapValue(a,m.sourceLayer,()=>new Map).set(m.getObjectId(),m);m=Array.from(a,([e,g])=>{const h=e.createQuery();h.objectIds=[...g.keys()];h.outFields=[e.objectIdField];h.returnGeometry=!0;h.maxAllowableOffset=q;h.outSpatialReference=d.spatialReference;return e.queryFeatures(h)});m=yield Promise.all(m);if(!this.destroyed)for(const {features:e}of m)for(const g of e)(m=a.get(g.sourceLayer).get(g.getObjectId()))&&p.includes(m)&&(m.geometry=g.geometry,f(m,
"geometry"),this._featuresResolutions.set(m,q))}});return function(a){return c.apply(this,arguments)}}();l._getTargetResolution=function(c){const a=c*R.getMetersPerUnitForSR(this.layerView.view.spatialReference),b=a/16;return 10>=b?0:c/a*b};l._fetchPopupFeaturesUsingIdentify=function(){var c=t._asyncToGenerator(function*(a,b,d){a=yield this._createIdentifyParameters(a,b,d);if(y.isNone(a))return[];({results:a}=yield W.identify(this.layerView.layer.parsedUrl,a));return a.map(p=>p.feature)});return function(a,
b,d){return c.apply(this,arguments)}}();l._createIdentifyParameters=function(){var c=t._asyncToGenerator(function*(a,b,d){const {floors:p,layer:f,timeExtent:q,view:{spatialReference:m,scale:e}}=this.layerView,g=y.isSome(d)?d.event:null;if(!b.length)return null;yield Promise.all(b.map(({sublayer:v})=>v.load().catch(()=>{})));b=Math.min(O("mapservice-popup-identify-max-tolerance"),f.allSublayers.reduce((v,w)=>w.renderer?G.calculateTolerance({renderer:w.renderer,event:g}):v,2));var h=this.createFetchPopupFeaturesQueryGeometry(a,
b);const k=U.getResolutionForScale(e,m);d=Math.round(h.width/k);h=new T({xmin:h.center.x-k*d,ymin:h.center.y-k*d,xmax:h.center.x+k*d,ymax:h.center.y+k*d,spatialReference:h.spatialReference});return new X({floors:p,gdbVersion:"gdbVersion"in f?f.gdbVersion:void 0,geometry:a,height:d,layerOption:"popup",mapExtent:h,returnGeometry:!0,spatialReference:m,sublayers:f.sublayers,timeExtent:q,tolerance:b,width:d})});return function(a,b,d){return c.apply(this,arguments)}}();l._fetchPopupFeaturesUsingQueries=
function(){var c=t._asyncToGenerator(function*(a,b,d){var p=this;const {layerView:{floors:f,timeExtent:q}}=this,m=y.isSome(d)?d.event:null;b=b.map(function(){var e=t._asyncToGenerator(function*({sublayer:g,popupTemplate:h}){yield g.load().catch(()=>{});if(g.capabilities&&!g.capabilities.operations.supportsQuery)return[];var k=g.createQuery(),v=G.calculateTolerance({renderer:g.renderer,event:m}),w=p.createFetchPopupFeaturesQueryGeometry(a,v);k.geometry=w;k.outFields=yield I.getRequiredFields(g,h);
k.timeExtent=q;if(f){var A=f.clone();A=V.getLayerFloorFilterClause(A,g);y.isSome(A)&&(k.where=k.where?`(${k.where}) AND (${A})`:A)}v=p._getTargetResolution(w.width/v);w=yield Z(h);h="point"===g.geometryType||w&&w.arcadeUtils.hasGeometryOperations(h);h||(k.maxAllowableOffset=v);({features:k}=yield g.queryFeatures(k));h=h?0:v;k=yield ba(g,k);for(const ca of k)p._featuresResolutions.set(ca,h);return k});return function(g){return e.apply(this,arguments)}}());return(yield F.eachAlways(b)).reverse().reduce((e,
g)=>g.value?[...e,...g.value]:e,[]).filter(e=>null!=e)});return function(a,b,d){return c.apply(this,arguments)}}();return n}(M);x.__decorate([z.property({constructOnly:!0})],u.MapServiceLayerViewHelper.prototype,"createFetchPopupFeaturesQueryGeometry",void 0);x.__decorate([z.property({constructOnly:!0})],u.MapServiceLayerViewHelper.prototype,"layerView",void 0);x.__decorate([z.property({constructOnly:!0})],u.MapServiceLayerViewHelper.prototype,"highlightGraphics",void 0);x.__decorate([z.property({constructOnly:!0})],
u.MapServiceLayerViewHelper.prototype,"highlightGraphicUpdated",void 0);x.__decorate([z.property({constructOnly:!0})],u.MapServiceLayerViewHelper.prototype,"updatingHandles",void 0);u.MapServiceLayerViewHelper=x.__decorate([S.subclass("esri.views.layers.support.MapService")],u.MapServiceLayerViewHelper);u.collectPopupProviders=J;u.isMapServiceLayerView=function(r,n){return"tile"===n.type||"map-image"===n.type};Object.defineProperty(u,Symbol.toStringTag,{value:"Module"})});