// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/Logger ../../../core/promiseUtils ../../../layers/FeatureLayer ./featureUtils".split(" "),function(y,p,q,z,A,B,m){function C(b){return`<ul class="esri-widget__list">${b.map(a=>`<li>${"string"===typeof a?m.applyTextFormattingHTML(m.htmlEntities(a)):a}</li>`).join("")}</ul>`}function D(b){return`<table class="esri-widget__table">${b.keys().map(a=>{var c=b.field(a);c="string"===typeof c?m.applyTextFormattingHTML(m.htmlEntities(c)):
c;return`<tr><th>${a}</th><td>${c}</td></tr>`}).join("")}</table>`}function E({aggregatedFeatures:b,arcadeUtils:a,featureSetVars:c,context:e,viewInfo:k,map:l,graphic:h,interceptor:g}){c.forEach(d=>{d=d.toLowerCase();var f=k.sr;const n={map:l,spatialReference:f,interceptor:g};"$map"===d&&(e.vars[d]=a.convertMapToFeatureSetCollection(n));"$layer"===d&&(e.vars[d]=a.convertFeatureLayerToFeatureSet({layer:h.sourceLayer,spatialReference:f,interceptor:g}));"$datastore"===d&&(e.vars[d]=a.convertServiceUrlToWorkspace({url:h.sourceLayer.url,
spatialReference:f,interceptor:g}));if("$aggregatedfeatures"===d){f=h.layer;const {fields:F,objectIdField:G,geometryType:H,spatialReference:v,displayField:I}=f;f=new B({fields:F,objectIdField:G,geometryType:H,spatialReference:v,displayField:I,...("feature"===f.type?{templates:f.templates,typeIdField:f.typeIdField,types:f.types}:null),source:b});e.vars[d]=a.convertFeatureLayerToFeatureSet({layer:f,spatialReference:v,interceptor:g})}})}function w(){return new Promise((b,a)=>y(["../../../support/arcadeUtils"],
b,a))}function J(b){return r.apply(this,arguments)}function r(){r=q._asyncToGenerator(function*({graphic:b,view:a}){const {isAggregate:c,layer:e}=b;if(!c||!e||"2d"!==a?.type)return[];a=yield a.whenLayerView(e);if(!("createQuery"in a&&"queryFeatures"in a))return[];const k=a.createQuery();b=b.getObjectId();k.aggregateIds=null!=b?[b]:[];({features:b}=yield a.queryFeatures(k));return b});return r.apply(this,arguments)}function x(b){return t.apply(this,arguments)}function t(){t=q._asyncToGenerator(function*({expressionInfo:b,
arcadeUtils:a,interceptor:c,spatialReference:e,map:k,graphic:l,view:h}){if(!b||!b.expression)return null;const g=a.createSyntaxTree(b.expression),d=K.filter(n=>a.hasVariable(g,n));[h]=yield Promise.all([J({graphic:l,view:h}),a.loadScriptDependencies(g,!0,d)]);const f=a.getViewInfo({spatialReference:e});e=a.createExecContext(l,f);e.interceptor=c;e.useAsync=!0;E({aggregatedFeatures:h,arcadeUtils:a,featureSetVars:d,context:e,viewInfo:f,map:k,graphic:l,interceptor:c});c=a.createFunction(g,e);return a.executeAsyncFunction(c,
e).catch(n=>L.error("arcade-execution-error",{error:n,graphic:l,expressionInfo:b}))});return t.apply(this,arguments)}function u(){u=q._asyncToGenerator(function*({expressionInfos:b,spatialReference:a,graphic:c,interceptor:e,map:k,view:l}){if(!b||!b.length)return{};const h=yield w(),g={};for(const d of b)g[`expression/${d.name}`]=x({expressionInfo:d,arcadeUtils:h,interceptor:e,spatialReference:a,map:k,graphic:c,view:l});b=yield A.eachAlways(g);a={};for(const d in b)c=b[d].value,c="string"===typeof c?
m.applyTextFormattingHTML(m.htmlEntities(c)):Array.isArray(c)?C(c):"esri.arcade.Dictionary"===c?.declaredClass?D(c):c,a[d]=c;return a});return u.apply(this,arguments)}const K=["$datastore","$map","$layer","$aggregatedfeatures"],L=z.getLogger("esri.widgets.Feature.support.arcadeFeatureUtils");p.createCompiledExpression=x;p.createCompiledExpressions=function(b){return u.apply(this,arguments)};p.loadArcadeUtils=w;Object.defineProperty(p,Symbol.toStringTag,{value:"Module"})});