// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/colorUtils ../../../../../core/Evented ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../chunks/mat4 ../../../../../chunks/mat4f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../Manipulator3D ../../manipulatorUtils ../../RenderObject ../dragEventPipeline3D ../ManipulatorType ../settings ./config ./Manipulation ./moveUtils ../../../webgl-engine/lib/GeometryUtil ../../../webgl-engine/lib/Material ../../../../interactive/dragEventPipeline ../../../../interactive/interfaces".split(" "),
function(C,D,L,M,N,O,z,P,l,r,Q,w,m,R,E,k,A,B,S,F,G,H,n){B=function(I){function x(a){var b=I.call(this)||this;b._radius=A.DISC_RADIUS;b.events=new M;b._tool=a.tool;b._view=a.view;null!=a.radius&&(b._radius=a.radius);b._createManipulator();b.forEachManipulator(d=>b._tool.manipulators.add(d));return b}D._inheritsLoose(x,I);var t=x.prototype;t.destroy=function(){this.forEachManipulator(a=>{this._tool.manipulators.remove(a);a.destroy()})};t.forEachManipulator=function(a){a(this._manipulator,E.ManipulatorType.TRANSLATE_Z)};
t.createGraphicDragPipeline=function(a,b,d){const e=O.unwrap(b.graphic.geometry).spatialReference;return S.createGraphicMoveDragPipeline(b,d,f=>this.createDragPipeline((p,g,c,u,y)=>{({steps:g,cancel:c}=a(p,g,c,u,y));return f(p,g,c)},e),this._view.state.viewingMode)};t.createDragPipeline=function(a,b){const d=this._view;return H.createManipulatorDragEventPipeline(this._manipulator,(e,f,p,g,c)=>{f=f.next(u=>({...u,manipulatorType:E.ManipulatorType.TRANSLATE_Z})).next(R.screenToZConstrained(d,e.renderLocation,
b)).next(H.addScreenDelta());a(e,f,p,g,c)})};t._updateManipulator=function(){var a=this._radius/A.DISC_RADIUS;const b=k.settings.zManipulator.height*a;var d=k.settings.zManipulator.coneHeight*a;const e=k.settings.zManipulator.coneWidth*a;a*=k.settings.zManipulator.width;var f=[r.fromValues(0,0,0),r.fromValues(0,0,b)];const p=[r.fromValues(0,0,0),r.fromValues(0,0,b+d)],g=(q=>{const h=P.create();z.translate(h,h,[0,0,b]);z.rotateX(h,h,Math.PI/2);q&&(q=1+2*q/e,z.scale(h,h,[q,q,q]));return h})(0);var c=
(q,h)=>{h=L.darken(k.settings.zManipulator.color,h);return[h.r/255,h.g/255,h.b/255,k.settings.zManipulator.color.a*q]};const u=w.createManipulatorMaterial(c(1,.25),G.RenderOccludedFlag.Occlude),y=w.createManipulatorMaterial(c(1,0),G.RenderOccludedFlag.Occlude),J=w.createManipulatorMaterial(c(.7,0),k.settings.zManipulator.renderOccluded);c=w.createManipulatorMaterial(c(.85,0),k.settings.zManipulator.renderOccluded);f=F.createTubeGeometry(u,f,a/2,16,!1);d=F.createConeGeometry(u,d,e/2,16,!1);d.transformation=
g;this._manipulator.renderObjects=[new m.RenderObject(d,n.ManipulatorStateFlags.Unfocused),new m.RenderObject(f,n.ManipulatorStateFlags.Unfocused),new m.RenderObject(d.instantiate({material:y}),n.ManipulatorStateFlags.Focused),new m.RenderObject(f.instantiate({material:y}),n.ManipulatorStateFlags.Focused),new m.RenderObject(d.instantiate({material:J}),n.ManipulatorStateFlags.Unfocused),new m.RenderObject(f.instantiate({material:J}),n.ManipulatorStateFlags.Unfocused),new m.RenderObject(d.instantiate({material:c}),
n.ManipulatorStateFlags.Focused),new m.RenderObject(f.instantiate({material:c}),n.ManipulatorStateFlags.Focused)];this._manipulator.radius=a/2+2;this._manipulator.collisionType={type:"line",paths:[p]}};t._createManipulator=function(){const a=new Q.Manipulator3D({view:this._view,autoScaleRenderObjects:!1,worldSized:!1,selectable:!1,cursor:"ns-resize",elevationInfo:this.elevationInfo,worldOriented:!0,collisionPriority:1.6});a.applyObjectTransform=b=>{var d=this._view.state.camera,e=K;this._view.renderCoordsHelper.toRenderCoords(this._manipulator.elevationAlignedLocation,
e);const f=l.dist(d.eye,e),p=d.computeRenderPixelSizeAtDist(f);var g=l.subtract(v,e,d.eye);l.normalize(g,g);var c=T;this._view.renderCoordsHelper.worldUpAtPosition(K,c);e=Math.abs(l.dot(g,c));g=l.cross(v,g,c);c=l.cross(v,g,c);e=N.clamp(e,.01,1);d=1-Math.sqrt(1-e*e)/e/d.fullWidth;e=this._radius/A.DISC_RADIUS*k.settings.zManipulator.width;l.scale(c,l.normalize(c,c),(1/d-1)*f+p*e);b[12]-=v[0];b[13]-=v[1];b[14]-=v[2]};this._manipulator=a;this._updateManipulator()};D._createClass(x,[{key:"radius",get:function(){return this._radius},
set:function(a){a!==this._radius&&(this._radius=a,this._updateManipulator())}},{key:"test",get:function(){return{manipulator:this._manipulator}}}]);return x}(B.Manipulation);const K=r.create(),v=r.create(),T=r.create();C.MoveZManipulation=B;Object.defineProperty(C,Symbol.toStringTag,{value:"Module"})});