// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports","../core/maybe","../symbols/support/unitConversionUtils"],function(f,c,x){function q(a,b){return c.isNone(b)||!b.mode?(a?l:m).mode:b.mode}function r(a,b){return c.isSome(b)?b:a?l:m}function n(a,b){return q(c.isSome(a)?a.hasZ:!1,b)}function t(a){const b=p(a);return n(a.geometry,b)}function p(a){return a.layer&&"elevationInfo"in a.layer?a.layer.elevationInfo:null}function u(a,b,d,e,g,k,h=null){if(!c.isNone(k)){var v=c.isSome(h)?h.mode:"absolute-height";if("on-the-ground"===v)return 0;
({absoluteZ:k}=w(b,d,e,g,a,k));a:{h=c.isSome(h)&&c.isSome(h.offset)?h.offset:0;switch(v){case "absolute-height":a=k-h;break a;case "relative-to-ground":a=k-(c.unwrapOr(a.elevationProvider.getElevation(b,d,e,g,"ground"),0)+h);break a;case "relative-to-scene":a=k-(c.unwrapOr(a.elevationProvider.getElevation(b,d,e,g,"scene"),0)+h);break a}a=void 0}return a}}function w(a,b,d,e,g,k){const h=c.isSome(k.offset)?k.offset:0;switch(k.mode){case "absolute-height":return{absoluteZ:d+h,elevation:0};case "on-the-ground":return d=
c.unwrapOr(g.elevationProvider.getElevation(a,b,0,e,"ground"),0),{absoluteZ:d,elevation:d};case "relative-to-ground":return a=c.unwrapOr(g.elevationProvider.getElevation(a,b,d,e,"ground"),0),{absoluteZ:d+a+h,elevation:a};case "relative-to-scene":return a=c.unwrapOr(g.elevationProvider.getElevation(a,b,d,e,"scene"),0),{absoluteZ:d+a+h,elevation:a}}}const l={mode:"absolute-height",offset:0},m={mode:"on-the-ground",offset:null};f.absoluteHeightElevationInfo=l;f.elevationContextAffectsAlignment=function(a,
b){if(c.isNone(b))return!1;({mode:b}=b);return c.isSome(b)&&("scene"===a&&"relative-to-scene"===b||"ground"===a&&"absolute-height"!==b)};f.elevationInfoLikeEquals=function(a,b){return a===b||c.isSome(a)&&c.isSome(b)&&a.mode===b.mode&&a.offset===b.offset};f.getConvertedElevation=function(a,b,d,e=null){return u(a,b.x,b.y,b.hasZ?b.z:0,b.spatialReference,d,e)};f.getConvertedElevationFromVector=function(a,b,d,e,g=null){return u(a,b[0],b[1],2<b.length?b[2]:0,d,e,g)};f.getEffectiveElevationInfo=r;f.getEffectiveElevationMode=
q;f.getGeometryEffectiveElevationInfo=function(a,b){return r(c.isSome(a)?!!a.hasZ:!1,b)};f.getGeometryEffectiveElevationMode=n;f.getGraphicEffectiveElevationInfo=function(a){var b=p(a);a=n(a.geometry,b);b=c.isSome(b)&&"on-the-ground"!==a?c.unwrapOr(b.offset,0)*x.getMetersPerUnit(c.unwrapOr(b.unit,"meters")):0;return{mode:a,offset:b}};f.getGraphicEffectiveElevationMode=t;f.getZForElevationMode=function(a,b,d){if(!c.isNone(d)&&d.mode){var e=a.hasZ?a.z:0,g=c.isSome(d.offset)?d.offset:0;switch(d.mode){case "absolute-height":return e-
g;case "on-the-ground":return 0;case "relative-to-ground":return a=c.unwrapOr(b.elevationProvider.getElevation(a.x,a.y,e,a.spatialReference,"ground"),0)+g,e-a;case "relative-to-scene":return a=c.unwrapOr(b.elevationProvider.getElevation(a.x,a.y,e,a.spatialReference,"scene"),0)+g,e-a}}};f.hasGraphicFeatureExpressionInfo=function(a){if("on-the-ground"===t(a))return!1;a=p(a);a=c.isSome(a)&&a.featureExpressionInfo?a.featureExpressionInfo.expression:null;return!(!a||"0"===a)};f.onTheGroundElevationInfo=
m;f.zValueInAbsoluteHeightMode=w;Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});