// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../Map ../TimeExtent ../core/Accessor ../core/asyncUtils ../core/Collection ../core/CollectionFlattener ../core/Error ../core/Evented ../core/HandleOwner ../core/handleUtils ../core/Loadable ../core/Logger ../core/maybe ../core/Promise ../core/promiseUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ../core/support/OwningCollection ../geometry/Extent ../geometry/HeightModelInfo ../geometry/SpatialReference ../geometry/support/spatialReferenceUtils ../support/AnalysesCollection ../support/GraphicsCollection ../time/TimeReference ./BasemapView ./LayerViewManager ./Magnifier ./ToolViewManager ./input/Input ./input/ViewEvents ./navigation/Navigation ./support/DefaultsFromMap".split(" "),
function(l,d,B,C,c,D,m,E,F,G,H,I,t,n,g,J,K,k,e,Y,Z,L,u,M,N,O,P,v,w,x,Q,R,y,S,T,U,z,V){var p;c=p=function(r){function q(b){var a=r.call(this,b)||this;a._userSpatialReference=null;a._cursor=null;a.allLayerViews=new E({getCollections:()=>[a.basemapView?.baseLayerViews,a.groundView?.layerViews,a.layerViews,a.basemapView?.referenceLayerViews],getChildrenFunction:h=>h.layerViews});a.groundView=null;a.basemapView=null;a.fatalError=null;a.graphics=new w.GraphicsCollection;a.analyses=new v.AnalysesCollection;
a.typeSpecificPreconditionsReady=!0;a.layerViews=new m;a.magnifier=new y;a.padding={left:0,top:0,right:0,bottom:0};a.ready=!1;a.spatialReferenceWarningDelay=1E3;a.supportsGround=!0;a.timeExtent=null;a.timeReference=new x;a.type=null;a.scale=null;a.updating=!1;a.initialExtentRequired=!0;a.input=new T;a.navigation=new z;a.layerViewManager=null;a.analysisViewManager=null;a.isHeightModelInfoRequired=!1;a.width=null;a.height=null;a.resizing=!1;a.suspended=!1;a.viewEvents=new U.ViewEvents(l._assertThisInitialized(a));
a.persistableViewModels=new m;a._isValid=!1;a._readyCycleForced=!1;a._currentSpatialReference=null;a.handles.add(k.watch(()=>a.preconditionsReady,h=>{h?(a._currentSpatialReference=a.spatialReference,p.views.add(l._assertThisInitialized(a))):(a._currentSpatialReference=null,p.views.remove(l._assertThisInitialized(a)));a.notifyChange("spatialReference");!h&&a.ready?(a.toolViewManager?.detach(),g.isSome(a.analysisViewManager)&&a.analysisViewManager.detach(),a.layerViewManager?.clear(),a._teardown()):
h&&!a.ready&&(a._startup(),g.isSome(a.analysisViewManager)&&a.analysisViewManager.attach(),a.toolViewManager.attach())},k.sync));return a}l._inheritsLoose(q,r);var f=q.prototype;f.initialize=function(){this.addResolvingPromise(this.validate().then(()=>{this._isValid=!0;return k.whenOnce(()=>this.ready)}));this.basemapView=new Q.BasemapView({view:this});this.layerViewManager=new R({view:this,layerViewImporter:{importLayerView:b=>this.importLayerView(b),hasLayerViewModule:b=>this.hasLayerViewModule(b)},
supportsGround:this.supportsGround});this.toolViewManager=new S({view:this});this._setupSpatialReferenceLogger();this.handles.add([k.watch(()=>this.initialExtentRequired,b=>this.defaultsFromMap.required={...this.defaultsFromMap.required,extent:b},{sync:!0,initial:!0}),k.watch(()=>this.ready,b=>{this.defaultsFromMap&&(this.defaultsFromMap.suspended=b,this.defaultsFromMap.userSpatialReference=b?this.spatialReference:this._userSpatialReference)},{sync:!0}),k.watch(()=>this._userSpatialReference,b=>{this.defaultsFromMap&&
(this.defaultsFromMap.userSpatialReference=b)},{sync:!0,initial:!0})])};f._setupSpatialReferenceLogger=function(){var b=this;let a=null;this.handles.add([k.watch(()=>this.defaultsFromMap?.ready,h=>{const W=0<this.map?.allLayers.length;h&&!this.spatialReference&&W?g.isSome(a)||(h=I.makeHandle(()=>a=g.abortMaybe(a)),a=D.createTask(function(){var X=l._asyncToGenerator(function*(A){try{yield K.after(b.spatialReferenceWarningDelay,null,A)}catch{return}finally{a=null}n.getLogger(b.declaredClass).warn("#spatialReference",
"no spatial reference could be derived from the currently added map layers")});return function(A){return X.apply(this,arguments)}}()),this.handles.add(h,"spatial-reference-logger-task")):this.handles.remove("spatial-reference-logger-task")},{sync:!0})])};f.destroy=function(){if(!this.destroyed){this.viewEvents.destroy();this.allLayerViews.destroy();this.navigation&&(this.navigation.destroy(),this._set("navigation",null));this.graphics=g.destroyMaybe(this.graphics);this.analyses=g.destroyMaybe(this.analyses);
this.handles.remove("defaultsFromMap");this.defaultsFromMap.destroy();this._set("defaultsFromMap",null);g.destroyMaybe(this.analysisViewManager);this.toolViewManager=g.destroyMaybe(this.toolViewManager);this.layerViewManager=g.destroyMaybe(this.layerViewManager);this.basemapView=g.destroyMaybe(this.basemapView);this.invalidate();this._emitter.clear();this.handles.removeAll();var b=this.map;this.map=null;b?.destroy()}};f._startup=function(){this._set("ready",!0)};f._teardown=function(){this._set("ready",
!1)};f.whenReady=function(){return Promise.resolve(this)};f.toMap=function(){n.getLogger(this.declaredClass).error("#toMap()","Not implemented on this instance of View");return null};f._spatialReferenceChanged=function(b){};f.whenLayerView=function(b){return this.layerViewManager.whenLayerView(b)};f.getDefaultSpatialReference=function(){return this.defaultsFromMap?.spatialReference};f.getDefaultHeightModelInfo=function(){return(this.map&&"heightModelInfo"in this.map?this.map.heightModelInfo:void 0)??
this.defaultsFromMap?.heightModelInfo??null};f.importLayerView=function(b){throw new F("importLayerView() not implemented");};f.hasLayerViewModule=function(b){return!1};f.validate=function(){var b=l._asyncToGenerator(function*(){});return function(){return b.apply(this,arguments)}}();f.invalidate=function(){this._isValid=!1};f.getSpatialReferenceSupport=function(){return{constraints:null}};f._validateSpatialReference=function(b){return g.isSome(this.getSpatialReferenceSupport({spatialReference:b}))};
f.when=function(b,a){this.isResolved()&&!this.ready&&n.getLogger(this.declaredClass).warn("#when()","Calling view.when() while the view is no longer ready but was already resolved once will resolve immediately. Use reactiveUtils.whenOnce(() \x3d\x3e view.ready).then(...) instead.");return r.prototype.when.call(this,b,a)};f.forceReadyCycle=function(){this.ready&&(k.when(()=>!1===this.preconditionsReady,()=>this._readyCycleForced=!1,{once:!0}),this._readyCycleForced=!0)};f.addAndActivateTool=function(b){this.toolViewManager.tools.add(b);
this.activeTool=b};f.tryFatalErrorRecovery=function(){this.fatalError=null};l._createClass(q,[{key:"activeTool",get:function(){return this.toolViewManager?.activeTool},set:function(b){this.toolViewManager&&(this.toolViewManager.activeTool=b)}},{key:"animation",get:function(){return this._get("animation")},set:function(b){this._set("animation",b)}},{key:"center",get:function(){return null}},{key:"_defaultsFromMapSettings",get:function(){return{}}},{key:"defaultsFromMap",get:function(){return new V.DefaultsFromMap({required:{tileInfo:!1,
heightModelInfo:!1,extent:!1},map:()=>this.map,getSpatialReferenceSupport:b=>this.getSpatialReferenceSupport(b),...this._defaultsFromMapSettings})}},{key:"extent",get:function(){return this._get("extent")},set:function(b){this._set("extent",b)}},{key:"heightModelInfo",get:function(){return this.getDefaultHeightModelInfo()}},{key:"interacting",get:function(){return this.navigating}},{key:"navigating",get:function(){return!1}},{key:"preconditionsReady",get:function(){return!(this.fatalError||!this._isValid||
this._readyCycleForced||!this.map||t.isLoadable(this.map)&&!this.map.loaded||0===this.width||0===this.height||!this.spatialReference||!this._validateSpatialReference(this.spatialReference)||!this._currentSpatialReference&&!this.defaultsFromMap?.ready||!this.typeSpecificPreconditionsReady)}},{key:"resolution",get:function(){return 0}},{key:"map",set:function(b){const a=this._get("map");b!==a&&(b?.destroyed&&(n.getLogger(this.declaredClass).warn("#map","The provided map is already destroyed",{map:b}),
b=null),t.isLoadable(b)&&b.load().catch(()=>{}),this.constructed&&(this.forceReadyCycle(),this._currentSpatialReference=null),this._set("map",b))}},{key:"spatialReference",get:function(){let b=this._userSpatialReference||this._currentSpatialReference||this.getDefaultSpatialReference()||null;b&&this.defaultsFromMap?.required?.heightModelInfo&&(b=b.clone(),b.vcsWkid=this.defaultsFromMap.vcsWkid,b.latestVcsWkid=this.defaultsFromMap.latestVcsWkid);return b},set:function(b){const a=!P.equals(b,this._get("spatialReference"));
this._set("_userSpatialReference",b);a&&(this._set("spatialReference",b),this._spatialReferenceChanged(b))}},{key:"stationary",get:function(){return!this.animation&&!this.navigating&&!this.resizing}},{key:"tools",get:function(){return this.toolViewManager?.tools}},{key:"initialExtent",get:function(){return this.defaultsFromMap?.extent}},{key:"cursor",get:function(){const b=this.toolViewManager?this.toolViewManager.cursor:null;return g.isSome(b)?b:this._cursor||"default"},set:function(b){this._cursor=
b;this.notifyChange("cursor")}},{key:"size",get:function(){return[this.width,this.height]}}]);return q}(H.HandleOwnerMixin(G.EventedMixin(J.EsriPromiseMixin(c))));c.views=new m;d.__decorate([e.property()],c.prototype,"_userSpatialReference",void 0);d.__decorate([e.property()],c.prototype,"activeTool",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"allLayerViews",void 0);d.__decorate([e.property()],c.prototype,"groundView",void 0);d.__decorate([e.property()],c.prototype,"animation",null);
d.__decorate([e.property()],c.prototype,"basemapView",void 0);d.__decorate([e.property()],c.prototype,"center",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"_defaultsFromMapSettings",null);d.__decorate([e.property()],c.prototype,"defaultsFromMap",null);d.__decorate([e.property()],c.prototype,"fatalError",void 0);d.__decorate([e.property({type:M})],c.prototype,"extent",null);d.__decorate([e.property(u.owningCollectionProperty(w.GraphicsCollection,"graphics"))],c.prototype,"graphics",
void 0);d.__decorate([e.property(u.owningCollectionProperty(v.AnalysesCollection,"analyses"))],c.prototype,"analyses",void 0);d.__decorate([e.property({readOnly:!0,type:N})],c.prototype,"heightModelInfo",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"interacting",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"navigating",null);d.__decorate([e.property({readOnly:!0,dependsOn:"fatalError _isValid _readyCycleForced map map.loaded? width height spatialReference _currentSpatialReference defaultsFromMap.ready typeSpecificPreconditionsReady".split(" ")})],
c.prototype,"preconditionsReady",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"typeSpecificPreconditionsReady",void 0);d.__decorate([e.property({type:m,readOnly:!0})],c.prototype,"layerViews",void 0);d.__decorate([e.property()],c.prototype,"resolution",null);d.__decorate([e.property({type:y})],c.prototype,"magnifier",void 0);d.__decorate([e.property({value:null,type:B})],c.prototype,"map",null);d.__decorate([e.property()],c.prototype,"padding",void 0);d.__decorate([e.property({readOnly:!0})],
c.prototype,"ready",void 0);d.__decorate([e.property({type:O})],c.prototype,"spatialReference",null);d.__decorate([e.property()],c.prototype,"spatialReferenceWarningDelay",void 0);d.__decorate([e.property()],c.prototype,"stationary",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"supportsGround",void 0);d.__decorate([e.property({type:C})],c.prototype,"timeExtent",void 0);d.__decorate([e.property({type:x,nonNullable:!0})],c.prototype,"timeReference",void 0);d.__decorate([e.property()],
c.prototype,"tools",null);d.__decorate([e.property()],c.prototype,"toolViewManager",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"type",void 0);d.__decorate([e.property({type:Number})],c.prototype,"scale",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"updating",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"initialExtentRequired",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"initialExtent",null);d.__decorate([e.property()],c.prototype,
"cursor",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"input",void 0);d.__decorate([e.property({type:z,nonNullable:!0})],c.prototype,"navigation",void 0);d.__decorate([e.property()],c.prototype,"layerViewManager",void 0);d.__decorate([e.property()],c.prototype,"analysisViewManager",void 0);d.__decorate([e.property()],c.prototype,"width",void 0);d.__decorate([e.property()],c.prototype,"height",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"resizing",void 0);d.__decorate([e.property({value:null,
readOnly:!0})],c.prototype,"size",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"suspended",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"viewEvents",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"persistableViewModels",void 0);d.__decorate([e.property()],c.prototype,"_isValid",void 0);d.__decorate([e.property()],c.prototype,"_readyCycleForced",void 0);d.__decorate([e.property()],c.prototype,"_currentSpatialReference",void 0);return c=p=d.__decorate([L.subclass("esri.views.View")],
c)});