// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Graphic ../../../core/Accessor ../../../core/Clonable ../../../core/Collection ../../../core/HandleOwner ../../../core/Identifiable ../../../core/maybe ../../../core/promiseUtils ../../../core/reactiveUtils ../../../core/throttle ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../rest/support/RelationshipQuery ../support/featureUtils".split(" "),
function(g,e,H,d,I,B,J,K,u,v,q,w,f,R,S,L,C,D){d=function(E){function r(c){var a=E.call(this,c)||this;a._queryAbortController=null;a._queryPageAbortController=null;a._queryFeatureCountAbortController=null;a.featuresPerPage=10;a.description=null;a.graphic=null;a.layer=null;a.map=null;a.orderByFields=null;a.featureCount=0;a.relationshipId=null;a.showAllEnabled=!1;a.title=null;a._cancelQuery=()=>{const {_queryAbortController:b}=g._assertThisInitialized(a);b&&b.abort();a._queryAbortController=null};a._cancelQueryFeatureCount=
()=>{const {_queryFeatureCountAbortController:b}=g._assertThisInitialized(a);b&&b.abort();a._queryFeatureCountAbortController=null};a._cancelQueryPage=()=>{const {_queryPageAbortController:b}=g._assertThisInitialized(a);b&&b.abort();a._queryPageAbortController=null};a._queryController=g._asyncToGenerator(function*(){a._cancelQuery();const b=new AbortController;a._queryAbortController=b;yield v.ignoreAbortErrors(a._query());a._queryAbortController===b&&(a._queryAbortController=null)});a._queryFeatureCountController=
g._asyncToGenerator(function*(){a._cancelQueryFeatureCount();const b=new AbortController;a._queryFeatureCountAbortController=b;yield v.ignoreAbortErrors(a._queryFeatureCount());a._queryFeatureCountAbortController===b&&(a._queryFeatureCountAbortController=null)});a._queryPageController=g._asyncToGenerator(function*(){const b=new AbortController;a._queryPageAbortController=b;yield v.ignoreAbortErrors(a._queryPage());a._queryPageAbortController===b&&(a._queryPageAbortController=null)});a._queryThrottled=
w.throttle(a._queryController,100,g._assertThisInitialized(a));a._queryFeatureCountThrottled=w.throttle(a._queryFeatureCountController,100,g._assertThisInitialized(a));a._queryPageThrottled=w.throttle(a._queryPageController,100,g._assertThisInitialized(a));a._query=g._asyncToGenerator(function*(){const {_queryAbortController:b,relatedFeatures:h}=g._assertThisInitialized(a);a._destroyRelatedFeatureViewModels();a.featurePage=1;h.removeAll();h.addMany(a._sliceFeatures(yield a._queryRelatedFeatures({signal:b?.signal})))});
a.handles.add([q.watch(()=>[a.displayCount,a.graphic,a.layer,a.map,a.orderByFieldsFixedCasing,a.relationshipId,a.featuresPerPage,a.showAllEnabled,a.canQuery,a.featureCount],()=>a._queryThrottled(),q.initial),q.watch(()=>[a.featurePage,a.showAllEnabled],()=>a._queryPageThrottled()),q.watch(()=>[a.layer,a.relationshipId,a.objectId,a.canQuery],()=>a._queryFeatureCountThrottled())]);return a}g._inheritsLoose(r,E);var n=r.prototype;n.destroy=function(){this._destroyRelatedFeatureViewModels();this.relatedFeatures.removeAll();
this._cancelQuery();this._cancelQueryFeatureCount();this._cancelQueryPage()};n._destroyRelatedFeatureViewModels=function(){this.relatedFeatureViewModels?.forEach(c=>!c.destroyed&&c.destroy());this.relatedFeatureViewModels.removeAll()};n._queryFeatureCount=function(){var c=g._asyncToGenerator(function*(){const {layer:a,relatedLayer:b,relationshipId:h,objectId:k,_queryFeatureCountAbortController:x,canQuery:t,supportsCacheHint:y}=this;yield a?.load();yield b?.load();if(t&&a&&b){var l=b.createQuery();
l=new C({cacheHint:y,relationshipId:h,returnGeometry:!1,objectIds:[k],where:u.unwrapOrValue(l.where,void 0)});l=yield a.queryRelatedFeaturesCount(l,{signal:x?.signal});this._set("featureCount",l[k]||0)}else this._set("featureCount",0)});return function(){return c.apply(this,arguments)}}();n._sliceFeatures=function(c){const {showAllEnabled:a,displayCount:b}=this;return a?c:b?c.slice(0,b):[]};n._queryPage=function(){var c=g._asyncToGenerator(function*(){const {relatedFeatures:a,featurePage:b,showAllEnabled:h,
_queryPageAbortController:k}=this;!h||2>b||a.addMany(yield this._queryRelatedFeatures({signal:k?.signal}))});return function(){return c.apply(this,arguments)}}();n._queryRelatedFeatures=function(){var c=g._asyncToGenerator(function*(a){const {orderByFieldsFixedCasing:b,showAllEnabled:h,featuresPerPage:k,displayCount:x,layer:t,relationshipId:y,featurePage:l,featureCount:F,relatedLayer:p,supportsCacheHint:M}=this,{canQuery:N,objectId:G}=this;if(!N||!t||!p)return[];var z=h?((l-1)*k+F)%F:0;const O=h?
k:x;var A=p.objectIdField;A=[...b?.map(m=>m.field),A].filter(u.isSome);const P=b?.map(m=>`${m.field} ${m.order}`),Q=p.createQuery();z=new C({orderByFields:P,start:z,num:O,outFields:A,cacheHint:M,relationshipId:y,returnGeometry:!1,objectIds:[G],where:u.unwrapOrValue(Q.where,void 0)});a=(yield t.queryRelatedFeatures(z,{signal:a?.signal}))[G]?.features||[];a.forEach(m=>{m.sourceLayer=p;m.layer=p});return a});return function(a){return c.apply(this,arguments)}}();g._createClass(r,[{key:"featurePage",get:function(){return this._get("featurePage")},
set:function(c){const {featuresPerPage:a,featureCount:b}=this;this._set("featurePage",Math.min(Math.max(c,1),Math.ceil(b/a)||1))}},{key:"orderByFieldsFixedCasing",get:function(){const {orderByFields:c,relatedLayer:a}=this;return c&&a?.loaded?c.map(b=>{const h=b.clone();b=D.getFixedFieldName(b.field,a);h.field=b;return h}):c??[]}},{key:"supportsCacheHint",get:function(){return!!this.layer?.capabilities?.queryRelated?.supportsCacheHint}},{key:"canQuery",get:function(){const c=this.layer?.capabilities?.queryRelated;
return!!this.relatedLayer&&!!this.relationship&&"number"===typeof this.relationshipId&&"number"===typeof this.objectId&&!!c?.supportsCount&&!!c?.supportsPagination}},{key:"itemDescriptionFieldName",get:function(){return this.orderByFieldsFixedCasing?.[0]?.field||null}},{key:"displayCount",get:function(){return this._get("displayCount")},set:function(c){this._set("displayCount",Math.min(Math.max(c,0),10))}},{key:"objectId",get:function(){return(this.objectIdField&&this.graphic?.attributes?.[this.objectIdField])??
null}},{key:"objectIdField",get:function(){return this.layer?.objectIdField||null}},{key:"relatedFeatures",get:function(){return this._get("relatedFeatures")||new B}},{key:"relatedLayer",get:function(){const {layer:c,map:a,relationship:b}=this;return c?.loaded&&a&&b?D.findRelatedLayer(a,c,b)??null:null}},{key:"relationship",get:function(){const {relationshipId:c,layer:a}=this;return"number"===typeof c?a?.relationships?.find(({id:b})=>b===c)??null:null}},{key:"relatedFeatureViewModels",get:function(){return this._get("relatedFeatureViewModels")||
new B}},{key:"state",get:function(){const {_queryAbortController:c,_queryFeatureCountAbortController:a,_queryPageAbortController:b,canQuery:h}=this;return a?"loading":c||b?"querying":h?"ready":"disabled"}}]);return r}(I.ClonableMixin(K.IdentifiableMixin(J.HandleOwnerMixin(d))));e.__decorate([f.property()],d.prototype,"_queryAbortController",void 0);e.__decorate([f.property()],d.prototype,"_queryPageAbortController",void 0);e.__decorate([f.property()],d.prototype,"_queryFeatureCountAbortController",
void 0);e.__decorate([f.property({value:1})],d.prototype,"featurePage",null);e.__decorate([f.property()],d.prototype,"featuresPerPage",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"orderByFieldsFixedCasing",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"supportsCacheHint",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"canQuery",null);e.__decorate([f.property()],d.prototype,"description",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"itemDescriptionFieldName",
null);e.__decorate([f.property({value:3})],d.prototype,"displayCount",null);e.__decorate([f.property({type:H})],d.prototype,"graphic",void 0);e.__decorate([f.property()],d.prototype,"layer",void 0);e.__decorate([f.property()],d.prototype,"map",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"objectId",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"objectIdField",null);e.__decorate([f.property()],d.prototype,"orderByFields",void 0);e.__decorate([f.property({readOnly:!0})],
d.prototype,"relatedFeatures",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"relatedLayer",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"relationship",null);e.__decorate([f.property()],d.prototype,"featureCount",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"relatedFeatureViewModels",null);e.__decorate([f.property()],d.prototype,"relationshipId",void 0);e.__decorate([f.property()],d.prototype,"showAllEnabled",void 0);e.__decorate([f.property()],d.prototype,
"state",null);e.__decorate([f.property()],d.prototype,"title",void 0);return d=e.__decorate([L.subclass("esri.widgets.Feature.FeatureRelationship.FeatureRelationshipViewModel")],d)});