// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Error ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ./LayerView3D ./graphics/elevationAlignPointsInFeatures ./graphics/GraphicsProcessor ./graphics/queryForSymbologySnapping ./support/projectExtentUtils ../webgl-engine/lib/UpdatePolicy ../../layers/LayerView".split(" "),
function(h,f,q,k,r,g,d,C,t,u,v,w,x,y,z,A){d=function(l){function m(){var a=l.apply(this,arguments)||this;a.type="graphics-3d";a.symbologySnappingSupported=!0;a._slicePlaneEnabled=!1;a.fullExtentInLocalViewSpatialReference=null;return a}h._inheritsLoose(m,l);var b=m.prototype;b.initialize=function(){this._set("processor",new w.GraphicsProcessor({owner:this,scaleVisibilityEnabled:!0,frustumVisibilityEnabled:!0}));this.addResolvingPromise(this.processor.initializePromise);this.handles.add(this.layer.on("graphic-update",
a=>this.processor.graphicsCore.graphicUpdateHandler(a)));this.addResolvingPromise(y.toViewIfLocal(this).then(a=>this.fullExtentInLocalViewSpatialReference=a));this.layer.internal?this.notifyChange("updating"):this.handles.add(r.when(()=>this.view?.basemapTerrain?.ready,()=>()=>this.notifyChange("updating"),{once:!0}))};b.destroy=function(){this.handles.removeAll();this.updatingHandles.removeAll();this._set("processor",k.destroyMaybe(this.processor))};b.getSuspendInfo=function(){const a=l.prototype.getSuspendInfo.call(this);
a.outsideScaleRange=this.processor?.scaleVisibilitySuspended??!1;a.outsideOfView=this.processor?.frustumVisibilitySuspended??!1;return a};b.fetchPopupFeatures=function(){var a=h._asyncToGenerator(function*(c,e){return k.unwrap(e)?.clientGraphics??[]});return function(c,e){return a.apply(this,arguments)}}();b.getHit=function(a){return this.processor.getHit(a)};b.whenGraphicBounds=function(a,c){return this.processor.whenGraphicBounds(a,c)};b.computeAttachmentOrigin=function(a,c){return this.processor?.computeAttachmentOrigin(a,
c)};b.getSymbolLayerSize=function(a,c){return this.processor.getSymbolLayerSize(a,c)};b.queryGraphics=function(){return Promise.resolve(this.loadedGraphics)};b.maskOccludee=function(a){return this.processor.maskOccludee(a)};b.highlight=function(a){return this.processor.highlight(a)};b.elevationAlignPointsInFeatures=function(){var a=h._asyncToGenerator(function*(c,e){const {processor:n}=this;if(k.isNone(n)||k.isNone(n.graphics3DGraphics))throw new q("graphicslayerview3d:missing-processor","A Graphics3D processor is needed to resolve graphics elevation.");
const {graphics3DGraphics:B}=n;return v.elevationAlignPointsInFeatures(this.view,this.layer,p=>"number"===typeof p?B.get(p):void 0,c,e)});return function(c,e){return a.apply(this,arguments)}}();b.queryForSymbologySnapping=function(){var a=h._asyncToGenerator(function*(c,e){return x.queryForSymbologySnapping(this.processor,c,e)});return function(c,e){return a.apply(this,arguments)}}();b.canResume=function(){return l.prototype.canResume.call(this)&&!this.processor?.scaleVisibilitySuspended};b.isUpdating=
function(){return!(!this.processor?.updating&&(this.layer.internal||this.view?.basemapTerrain?.ready))};b.getUsedMemory=function(){return this.processor?.graphicsCore?.usedMemory??0};b.getUnloadedMemory=function(){return this.processor?.graphicsCore?.unprocessedMemoryEstimate};b.ignoresMemoryFactor=function(){return!0};h._createClass(m,[{key:"loadedGraphics",get:function(){return this.layer.graphics}},{key:"legendEnabled",get:function(){return this.canResume()&&!this.processor?.frustumVisibilitySuspended}},
{key:"slicePlaneEnabled",get:function(){const a=this.layer.internal;return this._slicePlaneEnabled&&!a},set:function(a){this._slicePlaneEnabled=a}},{key:"updatePolicy",get:function(){return this.processor?.graphicsCore.effectiveUpdatePolicy||z.UpdatePolicy.SYNC}},{key:"performanceInfo",get:function(){return{displayedNumberOfFeatures:this.loadedGraphics.length,maximumNumberOfFeatures:-1,totalNumberOfFeatures:-1,nodes:0,core:null,updating:this.updating,elevationUpdating:this.processor?.elevationAlignment.updating??
!1,visibilityFrustum:!this.processor?.frustumVisibilitySuspended}}}]);return m}(u.LayerView3D(A));f.__decorate([g.property()],d.prototype,"loadedGraphics",null);f.__decorate([g.property({readOnly:!0})],d.prototype,"legendEnabled",null);f.__decorate([g.property()],d.prototype,"layer",void 0);f.__decorate([g.property({readOnly:!0})],d.prototype,"processor",void 0);f.__decorate([g.property()],d.prototype,"_slicePlaneEnabled",void 0);f.__decorate([g.property({type:Boolean})],d.prototype,"slicePlaneEnabled",
null);return d=f.__decorate([t.subclass("esri.views.3d.layers.GraphicsLayerView3D")],d)});