// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Graphic ../../../symbols ../../../core/Accessor ../../../core/Handles ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../core/accessorSupport/diffUtils ../../../chunks/vec3f64 ../../../layers/graphics/dehydratedFeatures ./graphics/Graphics3DCore ./graphics/Graphics3DScaleVisibility ./i3s/I3SGeometryUtil ../support/LimitGraphicsMap ../webgl-engine/lib/UpdatePolicy ../../../symbols/PointSymbol3D".split(" "),
function(v,l,z,e,A,B,n,C,p,M,N,D,E,F,G,H,I,w,J,K,L){e=function(x){function t(a){a=x.call(this,a)||this;a.loadedGraphics=new J.LimitGraphicsMap(5E4);a.slicePlaneEnabled=!1;a._renderingInfo={symbol:new L};a._handles=new B;a._graphicsByNode=new Map;return a}v._inheritsLoose(t,x);var f=t.prototype;f.initialize=function(){const a=this.view.basemapTerrain;this._graphicsCore=new H.Graphics3DCore({owner:this,layer:this.layer,preferredUpdatePolicy:K.UpdatePolicy.ASYNC,elevationFeatureExpressionEnabled:!1,
graphicSymbolSupported:!1,getRenderingInfoWithoutRenderer:!0,hasZ:!0,hasM:!1,componentFactories:{deconflictor:c=>this.view.deconflictor.addGraphicsOwner(c),labeler:(c,b)=>this.view.labeler.addGraphicsOwner(c,b,{emptySymbolLabelSupported:!0,elevationInfoOverride:{mode:"absolute-height",offset:0},disablePlacement:{logEntityDescription:"3D Object Scene Layer features"}}),scaleVisibility:(c,b)=>new I({graphicsCoreOwner:this,layer:this.layer,queryGraphicUIDsInExtent:b,graphicsCore:c,basemapTerrain:a,layerScaleEnabled:!1})}});
this._graphicsCore.initializePromise.then(()=>this._graphicsCore.startCreateGraphics()).catch(()=>{});this._handles.add(C.watch(()=>this.layer.labelingInfo,(c,b)=>{E.diff(c,b)&&this._graphicsCore.updateLabelingInfo()}))};f.destroy=function(){this._handles=n.destroyMaybe(this._handles);this._graphicsCore=n.destroyMaybe(this._graphicsCore);this.loadedGraphics=n.destroyMaybe(this.loadedGraphics);this.view=null};f.addNodeMeta=function(a,c){let b=0;const d=a.filteredIds,k=this.view.spatialReference,g=
a.featureIds.map((m,q)=>{w.boundingBoxTop(q,this.collection,a.objectHandle,r);const y=G.makeDehydratedPoint(0,0,0,k);this.view.renderCoordsHelper.fromRenderCoords(r,y);q=c(q,a);let u=!1;n.isNone(d)?u=!0:b<d.length&&m===d[b]&&(u=!0,b++);return{objectId:m,uid:z.generateUID(),attributes:q,visible:u,geometry:y}});this.loadedGraphics.addMany(g);this._graphicsByNode.set(a.node.index,g)};f.updateLabelPositions=function(a){const c=this._graphicsByNode.get(a.node.index);if(c){var b=0,d=this.view.spatialReference,
k=this.view.renderCoordsHelper;for(let g=0;g<a.featureIds.length;g++){const m=c[b];if(a.featureIds[g]===m.objectId){b++;const q=this._graphicsCore.getGraphics3DGraphicById(m.uid);n.isNone(q)||(w.boundingBoxTop(g,this.collection,a.objectHandle,r),this.view.renderCoordsHelper.fromRenderCoords(r,r,d),q.alignWithAbsoluteElevation(r[2],k,!1),n.isSome(m.geometry)&&"point"===m.geometry.type&&(m.geometry.z=r[2]))}}}};f.setNodeMetaAttributes=function(a,c){const b=this._graphicsByNode.get(a.node.index);if(b){var d=
Array(b.length);for(let k=0;k<b.length;k++){const g=b[k];g.attributes=c(k,a);d[k]=g.uid}this._graphicsCore.updateLabelingInfo(d)}};f.applyFilterChange=function(a){var c=this._graphicsByNode.get(a.node.index);if(c)if(n.isNone(a.filteredIds))for(var b of c)b.visible||(b.visible=!0,h.graphic=b,h.property="visible",h.oldValue=!1,h.newValue=!0,this._graphicsCore.graphicUpdateHandler(h));else{b=0;for(const d of c)c=d.visible,b<a.filteredIds.length&&d.objectId===a.filteredIds[b]?(d.visible=!0,b++):d.visible=
!1,c!==d.visible&&(h.graphic=d,h.property="visible",h.oldValue=c,h.newValue=d.visible,this._graphicsCore.graphicUpdateHandler(h))}};f.removeNodeMeta=function(a){this.loadedGraphics.removeManyByObjectId(a.featureIds)};f.getRenderingInfo=function(){return this._renderingInfo};f.notifyGraphicGeometryChanged=function(){};f.notifyGraphicVisibilityChanged=function(){};v._createClass(t,[{key:"updating",get:function(){return this._graphicsCore?.updating??!1}},{key:"updatePolicy",get:function(){return this._graphicsCore.effectiveUpdatePolicy}},
{key:"usedMemory",get:function(){return this._graphicsCore.usedMemory}},{key:"unloadedMemoryEstimate",get:function(){return this._graphicsCore.unprocessedMemoryEstimate}},{key:"test",get:function(){return{graphicsCore:this._graphicsCore}}}]);return t}(A);l.__decorate([p.property()],e.prototype,"view",void 0);l.__decorate([p.property()],e.prototype,"layer",void 0);l.__decorate([p.property()],e.prototype,"collection",void 0);l.__decorate([p.property()],e.prototype,"loadedGraphics",void 0);l.__decorate([p.property()],
e.prototype,"updating",null);l.__decorate([p.property()],e.prototype,"slicePlaneEnabled",void 0);l.__decorate([p.property()],e.prototype,"_graphicsCore",void 0);e=l.__decorate([D.subclass("esri.views.3d.layers.I3SMeshViewLabeler")],e);const h={graphic:null,property:null,oldValue:null,newValue:null},r=F.create();return e});