// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/Logger ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../layers/support/layerUtils ./LayerView3D ./TiledLayerView3D ../../layers/LayerView ../../layers/RefreshableLayerView".split(" "),function(l,h,r,q,e,t,m,f,A,u,
v,w,x,y,z){f=function(n){function k(){var b=n.apply(this,arguments)||this;b.type="wmts-3d";return b}l._inheritsLoose(k,n);var d=k.prototype;d._getCompatibleTileInfoMatrixSet=function(b,a=!1){const c=v.getTileMaxtrixSetFromActiveLayer(this.layer);if(e.isSome(c)){if(r.isCollection(c))return c.find(g=>{g=b(g);e.isSome(g)&&(a?q.getLogger(this.declaredClass).error("The selected tile matrix set is not compatible with the view",g):this.addResolvingPromise(Promise.reject(g)));return null==g});const p=b(c);
e.isSome(p)&&(a?q.getLogger(this.declaredClass).error("The selected tile matrix set is not compatible with the view",p):this.addResolvingPromise(Promise.reject(p)));return c}return null};d.initialize=function(){this._getCompatibleTileInfoMatrixSet(a=>this._getTileInfoSupportError(a.tileInfo,a.fullExtent));const b=t.whenOnce(()=>this.view?.basemapTerrain?.tilingSchemeLocked).then(()=>{const a=this._getCompatibleTileInfoMatrixSet(c=>this._getTileInfoError(c.tileInfo,c.fullExtent));e.isNone(a)||(null!==
a.id&&this.layer.activeLayer.tileMatrixSetId!==a.id&&(this.layer.activeLayer.tileMatrixSetId=a.id),a.tileInfo&&(this.tileInfo=a.tileInfo),this.layer.fullExtent=a.fullExtent)});this.addResolvingPromise(b);this.when(()=>this._postInitialize())};d.refresh=function(){this.emit("data-changed")};d.canResume=function(){if(!n.prototype.canResume.call(this))return!1;const b=this.layer.activeLayer.tileMatrixSet;return e.isSome(b)&&!this._getTileInfoError(b.tileInfo,b.fullExtent)};d.doRefresh=function(){var b=
l._asyncToGenerator(function*(){this.suspended||this.emit("data-changed")});return function(){return b.apply(this,arguments)}}();d._postInitialize=function(){this.updatingHandles.add(()=>this.layer?.activeLayer?.styleId,()=>this.refresh());this.updatingHandles.add(()=>this.layer?.activeLayer,b=>{const a=this._getCompatibleTileInfoMatrixSet(c=>this._getTileInfoError(c.tileInfo,c.fullExtent),!0);e.isSome(a)&&null!==a.id&&b.tileMatrixSetId!==a.id&&(this.layer.activeLayer.tileMatrixSetId=a.id);this.notifyChange("suspended");
this.canResume()&&this.refresh()})};d._getTileInfoError=function(b,a){return this._getTileInfoSupportError(b,a)||this._getTileInfoCompatibilityError(b,this.view.basemapTerrain.tilingScheme)};l._createClass(k,[{key:"hasMixedImageFormats",get:function(){return!0}}]);return k}(z(x.TiledLayerView3D(w.LayerView3D(y))));h.__decorate([m.property({readOnly:!0})],f.prototype,"hasMixedImageFormats",null);h.__decorate([m.property()],f.prototype,"layer",void 0);h.__decorate([m.property()],f.prototype,"suspended",
void 0);return f=h.__decorate([u.subclass("esri.views.3d.layers.WMTSLayerView3d")],f)});