// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../geometry ../../../core/compilerUtils ../../../core/Evented ../../../core/mathUtils ../../../core/maybe ../../../core/screenUtils ../../../core/accessorSupport/utils ../../../chunks/mat3 ../../../chunks/mat3f64 ../../../chunks/mat4 ../../../chunks/mat4f64 ../../../chunks/vec2 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../geometry/ellipsoidUtils ../../../geometry/projection ../../../geometry/support/aaBoundingRect ../../../geometry/support/lineSegment ../../../geometry/support/plane ../../../geometry/support/ray ../../../geometry/support/vectorStacks ../../../layers/graphics/hydratedFeatures ../support/ElevationProvider ../support/geometryUtils/ray ../webgl-engine/lib/Camera ../webgl-engine/lib/Object3D ../webgl-engine/lib/UpdatePolicy ../webgl-engine/lib/WebGLLayer ../../interactive/interfaces ../../../geometry/Point".split(" "),
function(I,U,J,V,W,K,k,r,X,L,Y,t,y,Z,l,p,aa,z,ba,u,v,ca,A,E,F,G,da,ea,fa,ha,n,B){function M(q){return 0!==q[12]||0!==q[13]||0!==q[14]}J=function(){function q(a){this.metadata=void 0;this._camera=new da.Camera;this._elevation={offset:0,override:null};this.collisionType={type:"point"};this.collisionPriority=0;this._renderObjects=[];this._available=this.autoScaleRenderObjects=!0;this._noDisplayCount=0;this._radius=10;this._worldSized=!1;this.focusMultiplier=2;this.touchMultiplier=2.5;this.worldOriented=
!1;this._modelTransform=y.create();this._worldFrame=null;this._renderLocation=p.create();this._renderLocationDirty=!0;this._location=new B({x:0,y:0,z:0});this._elevationAlignedLocation=new B;this.interactive=this._elevationAlignedLocationDirty=!0;this.selectable=!1;this.grabbable=!0;this.grabCursor=this.cursor=null;this._selected=this._hovering=this.dragging=this._grabbing=!1;this._state=n.ManipulatorStateCustomFlags.None;this._focused=!1;this.events=new W.EventEmitter;this._screenLocation={screenPointArray:r.createScreenPointArray(),
renderScreenPointArray:r.createRenderScreenPointArray3(),pixelSize:0};this._screenLocationDirty=!0;this._attached=this._engineResourcesAddedToStage=!1;this._location.spatialReference=a.view.spatialReference;for(const b in a)this[b]=a[b];(a=this.view.state?.camera)&&this._camera.copyFrom(a)}var h=q.prototype;h.destroy=function(){this._removeResourcesFromStage();this._camera=this.view=this._engineResources=null};h.disableDisplay=function(){this._noDisplayCount++;1===this._noDisplayCount&&this._updateEngineObject();
return{remove:X.once(()=>{this._noDisplayCount--;0===this._noDisplayCount&&this._updateEngineObject()})}};h._notifyLocationChanged=function(){this._elevationAlignedLocationDirty=this._screenLocationDirty=this._renderLocationDirty=!0;this._updateEngineObject();this.events.emit("location-update",{location:this._location})};h._updateElevationAlignedLocation=function(){const a=k.isSome(this._elevation.override)?this._elevation.override:this.location.z||0;this._elevationAlignedLocation.x=this.location.x;
this._elevationAlignedLocation.y=this.location.y;this._elevationAlignedLocation.z=a+this._elevation.offset;this._elevationAlignedLocation.spatialReference=E.hydratedSpatialReference(this.location.spatialReference);this._screenLocationDirty=this._renderLocationDirty=!0;this._elevationAlignedLocationDirty=!1};h.grabbableForEvent=function(){return!0};h.updateStateEnabled=function(a,b){this.state=b?this.state|a:this.state&~a};h._setFocused=function(a){a!==this._focused&&(this._focused=a,this.events.emit("focus-changed",
{action:!0===a?"focus":"unfocus"}))};h._ensureScreenLocation=function(){if(this._screenLocationDirty){this._screenLocation.pixelSize=this._camera.computeScreenPixelSizeAt(this.renderLocation);this._screenLocationDirty=!1;if(M(this._modelTransform)){var a=this._calculateModelTransformOffset(ia);a=l.add(a,a,this.renderLocation)}else a=this.renderLocation;this._camera.projectToRenderScreen(a,this._screenLocation.renderScreenPointArray);this._camera.renderToScreen(this._screenLocation.renderScreenPointArray,
this._screenLocation.screenPointArray)}};h.intersectionDistance=function(a,b){if(!this.available)return null;a=r.screenPointObjectToArray(a,ja);var d=this._getCollisionRadius(b);b=-1*this.collisionPriority;switch(this.collisionType.type){case "point":if(Z.squaredDistance(this.screenLocation.screenPointArray,a)<d*d)return this.screenLocation.renderScreenPointArray[2]+b;break;case "line":var g=this.collisionType.paths,c=this._getWorldToScreenObjectScale();c=this._calculateObjectTransform(c,C);d*=this.screenLocation.pixelSize;
a=G.fromScreen(this._camera,a,H);if(k.isNone(a))break;for(var e of g)if(0!==e.length){g=l.transformMat4(w,e[0],c);for(var f=1;f<e.length;f++){var m=l.transformMat4(N,e[f],c),x=u.closestRayDistance2(u.fromPoints(g,m,O),a);if(null!=x&&x<d*d)return c=l.add(A.sv3d.get(),g,m),l.scale(c,c,.5),a=r.castRenderScreenPointArray(A.sv3d.get()),this._camera.projectToRenderScreen(c,a),a[2]+b;l.copy(g,m)}}break;case "disc":g=this.collisionType.direction;c=this.collisionType.offset??p.ZEROS;e=this._getWorldToScreenObjectScale();
f=this._calculateObjectTransform(e,C);e=d*this.screenLocation.pixelSize;a=G.fromScreen(this._camera,a,H);if(k.isNone(a))break;d=L.fromMat4(P,f);d=l.transformMat3(Q,g,d);c=l.transformMat4(R,c,f);v.fromPositionAndNormal(c,d,D);d=S;if(v.intersectRay(D,a,d)&&l.squaredDistance(d,c)<e*e)return this.screenLocation.renderScreenPointArray[2]+b;break;case "ribbon":const {paths:ka,direction:la}=this.collisionType;e=this._getWorldToScreenObjectScale();e=this._calculateObjectTransform(e,C);d*=this._camera.computeScreenPixelSizeAt(this.renderLocation);
g=G.fromScreen(this._camera,a,H);if(k.isNone(g))break;a=L.fromMat4(P,e);a=l.transformMat3(Q,la,a);f=this._calculateModelTransformPosition(R);v.fromPositionAndNormal(f,a,D);a=S;if(!v.intersectRay(D,g,a))break;for(c of ka)if(0!==c.length)for(g=l.transformMat4(w,c[0],e),f=1;f<c.length;f++){m=l.transformMat4(N,c[f],e);x=u.distance2(u.fromPoints(g,m,O),a);if(null!=x&&x<d*d)return c=l.add(A.sv3d.get(),g,m),l.scale(c,c,.5),a=r.castRenderScreenPointArray(A.sv3d.get()),this._camera.projectToRenderScreen(c,
a),a[2]+b;l.copy(g,m)}break;default:V.neverReached(this.collisionType)}return null};h.attach=function(a={manipulator3D:{}}){const b=this._stage;if(b){a=a.manipulator3D;if(k.isNone(a.engineLayerId)){const d=new ha.WebGLLayer({pickable:!1,updatePolicy:fa.UpdatePolicy.SYNC});b.add(d);a.engineLayerId=d.id;this._engineLayer=d}else b?.getObject&&(this._engineLayer=b.getObject(a.engineLayerId));a.engineLayerReferences=(a.engineLayerReferences||0)+1;this._materialIdReferences=a.materialIdReferences;k.isNone(this._materialIdReferences)&&
(this._materialIdReferences=new Map,a.materialIdReferences=this._materialIdReferences);this._camera.copyFrom(this.view.state.camera);this._attached=!0;this._updateEngineObject();z.canProjectWithoutEngine(this._location.spatialReference,this.view.spatialReference)||(this.location=new B({x:0,y:0,z:0,spatialReference:this.view.spatialReference}))}};h.detach=function(a={manipulator3D:{}}){a=a.manipulator3D;a.engineLayerReferences--;const b=0===a.engineLayerReferences;b&&(a.engineLayerId=null);this._removeResourcesFromStage(b);
this._materialIdReferences=this._engineLayer=this._engineResources=null;this._attached=!1};h.onViewChange=function(){this._camera.copyFrom(this.view.state.camera);this._screenLocationDirty=!0;this._updateEngineObject()};h.onElevationChange=function(a){z.projectPoint(this.location,T,a.spatialReference)&&ba.containsPointObject(a.extent,T)&&this._notifyLocationChanged()};h._evaluateElevationAlignment=function(){if(!k.isNone(this.elevationInfo)){var a=null,b=0,d=k.unwrapOr(this.elevationInfo.offset,0);
switch(this.elevationInfo.mode){case "on-the-ground":a=k.unwrapOr(F.getElevationAtPoint(this.view.elevationProvider,this.location,"ground"),0);break;case "relative-to-ground":b=k.unwrapOr(F.getElevationAtPoint(this.view.elevationProvider,this.location,"ground"),0)+d;break;case "relative-to-scene":b=k.unwrapOr(F.getElevationAtPoint(this.view.elevationProvider,this.location,"scene"),0)+d;break;case "absolute-height":b=d}if(b!==this._elevation.offset||a!==this._elevation.override)this._elevation.offset=
b,this._elevation.override=a}};h._updateEngineObject=function(){if(this._attached)if(this.available){var a=this._getWorldToScreenObjectScale(),b=C;!0===this.autoScaleRenderObjects?(a*=this._getFocusedSize(this._radius,this.focused),this._calculateObjectTransform(a,b)):this._calculateObjectTransform(a,b);var {objectsByState:d}=this._ensureEngineResources();a=(this.focused?n.ManipulatorStateFlags.Focused:n.ManipulatorStateFlags.Unfocused)|(this.selected?n.ManipulatorStateFlags.Selected:n.ManipulatorStateFlags.Unselected);
var g=0<this._noDisplayCount;for(const {stateMask:c,objects:e}of d)if(g)for(const f of e)f.visible=!1;else if(d=(c&n.ManipulatorStateCustomFlags.All)===n.ManipulatorStateCustomFlags.None||(this.state&c)===(c&n.ManipulatorStateCustomFlags.All),(c&n.ManipulatorStateFlags.All)!==n.ManipulatorStateFlags.None&&(a&c)!==(c&n.ManipulatorStateFlags.All)||!d)for(const f of e)f.visible=!1;else for(const f of e)f.visible=!0,f.transformation=b}else this._removeResourcesFromStage()};h._ensureEngineResources=function(){if(k.isNone(this._engineResources)){const a=
k.unwrap(this._engineLayer),b=[],d=new Set;this.renderObjects.forEach(({geometry:{material:e}})=>{d.has(e)||(b.push(e),d.add(e))});const g=new Map;this._renderObjects.forEach(e=>{const f=new ea.Object3D({castShadow:!1,geometries:[e.geometry]}),m=g.get(e.stateMask)||[];m.push(f);g.set(e.stateMask,m)});const c=[];g.forEach((e,f)=>c.push({stateMask:f,objects:e}));this._engineResources={objectsByState:c,layer:a,materials:b}}this._addResourcesToStage();return this._engineResources};h._addResourcesToStage=
function(){const a=this._stage;if(!this._engineResourcesAddedToStage&&!k.isNone(this._engineResources)&&a){var {objectsByState:b,layer:d,materials:g}=this._engineResources;g.forEach(c=>{const e=k.unwrap(this._materialIdReferences),f=e.get(c.id)||0;0===f&&a.add(c);e.set(c.id,f+1)});b.forEach(({objects:c})=>{d.addMany(c);a.addMany(c)});this._engineResourcesAddedToStage=!0}};h._removeResourcesFromStage=function(a=!1){const b=this._stage;if(this._engineResourcesAddedToStage&&!k.isNone(this._engineResources)&&
b){var {objectsByState:d,layer:g,materials:c}=this._engineResources;d.forEach(({objects:e})=>{g.removeMany(e);b.removeMany(e)});c.forEach(e=>{const f=k.unwrap(this._materialIdReferences),m=f.get(e.id);1===m?(b.remove(e),f.delete(e.id)):f.set(e.id,m-1)});a&&b.remove(g);this._engineResourcesAddedToStage=!1}};h._getCollisionRadius=function(a){return this._getFocusedSize(this.radius,!0)*("touch"===a?this.touchMultiplier:1)};h._getFocusedSize=function(a,b){return a*(b?this.focusMultiplier:1)};h._getWorldToScreenObjectScale=
function(){return this._worldSized?1:this.screenLocation.pixelSize};h._calculateModelTransformPosition=function(a){var b=this._getWorldToScreenObjectScale();b=this._calculateObjectTransform(b,ma);return l.set(a,b[12],b[13],b[14])};h._calculateModelTransformOffset=function(a){const b=this._calculateModelTransformPosition(a);return l.subtract(a,b,this.renderLocation)};h._calculateObjectTransform=function(a,b){t.set(b,a,0,0,0,0,a,0,0,0,0,a,0,0,0,0,1);this._worldFrame&&t.multiply(b,b,this._worldFrame);
t.multiply(b,b,this._modelTransform);b[12]+=this.renderLocation[0];b[13]+=this.renderLocation[1];b[14]+=this.renderLocation[2];b[15]=1;k.isSome(this._applyObjectTransform)&&this._applyObjectTransform(b);return b};U._createClass(q,[{key:"_stage",get:function(){return this.view?._stage}},{key:"elevationInfo",get:function(){return this._elevationInfo},set:function(a){this._elevationInfo=a;this._renderLocationDirty=this._elevationAlignedLocationDirty=!0;this._updateEngineObject()}},{key:"renderObjects",
get:function(){return this._renderObjects},set:function(a){this._removeResourcesFromStage();this._engineResources=null;this._renderObjects=a.slice();this._updateEngineObject()}},{key:"available",get:function(){return this._available},set:function(a){a!==this._available&&(this._available=a,this._updateEngineObject())}},{key:"radius",get:function(){return this._radius},set:function(a){a!==this._radius&&(this._radius=a,this._updateEngineObject())}},{key:"worldSized",get:function(){return this._worldSized},
set:function(a){a!==this._worldSized&&(this._worldSized=a,this._updateEngineObject())}},{key:"modelTransform",get:function(){return this._modelTransform},set:function(a){M(a)&&(this._screenLocationDirty=!0);t.copy(this._modelTransform,a);this._updateEngineObject()}},{key:"renderLocation",get:function(){if(this._renderLocationDirty)if(this._renderLocationDirty=!1,this.view.renderCoordsHelper.toRenderCoords(this.elevationAlignedLocation,this._renderLocation),this.worldOriented){this._worldFrame||(this._worldFrame=
y.create());a:{var a=this.view,b=this._renderLocation,d=this._worldFrame;switch(a.viewingMode){case "local":t.identity(d);break a;case "global":a=aa.getReferenceEllipsoid(a.renderCoordsHelper.spatialReference),z.sphericalPCPFtoLonLatElevation(b,0,w,0,a.radius),z.computeENUToSphericalPCPFLocalRotation(K.deg2rad(w[0]),K.deg2rad(w[1]),d)}}}else this._worldFrame&&(this._worldFrame=null);return this._renderLocation},set:function(a){this.view.renderCoordsHelper.fromRenderCoords(a,this._location);this.elevationAlignedLocation=
this._location}},{key:"location",get:function(){return this._location},set:function(a){E.clonePoint(a,this._location);this._notifyLocationChanged()}},{key:"elevationAlignedLocation",get:function(){if(!this._elevationAlignedLocationDirty)return this._elevationAlignedLocation;this._evaluateElevationAlignment();this._updateElevationAlignedLocation();return this._elevationAlignedLocation},set:function(a){E.clonePoint(a,this._location);this._evaluateElevationAlignment();this._location.z-=this._elevation.offset;
this._updateElevationAlignedLocation();this._updateEngineObject();this.events.emit("location-update",{location:this._location})}},{key:"grabbing",get:function(){return this._grabbing},set:function(a){a!==this._grabbing&&(this._grabbing=a,this._setFocused(this._hovering||this._grabbing),this._updateEngineObject())}},{key:"hovering",get:function(){return this._hovering},set:function(a){a!==this._hovering&&(this._hovering=a,this._setFocused(this._hovering||this._grabbing),this._updateEngineObject())}},
{key:"selected",get:function(){return this._selected},set:function(a){a!==this._selected&&(this._selected=a,this._updateEngineObject(),this.events.emit("select-changed",{action:a?"select":"deselect"}))}},{key:"state",get:function(){return this._state},set:function(a){a!==this._state&&(this._state=a,this._updateEngineObject())}},{key:"focused",get:function(){return this._focused}},{key:"screenLocation",get:function(){this._ensureScreenLocation();return this._screenLocation}},{key:"applyObjectTransform",
get:function(){return this._applyObjectTransform},set:function(a){this._applyObjectTransform=a;this._screenLocationDirty=!0;this._updateEngineObject()}},{key:"attached",get:function(){return this._attached}},{key:"test",get:function(){let a=!1;if(k.isSome(this._engineResources))for(const b in this._engineResources.objectsByState){const d=this._engineResources.objectsByState[b];for(const g of d.objects)if(g.visible){a=!0;break}if(a)break}return{areAnyResourcesVisible:a}}}]);return q}();const ja=r.createScreenPointArray(),
O=u.create(),H=ca.create(),P=Y.create(),ma=y.create(),C=y.create(),D=v.create(),w=p.create(),N=p.create(),S=p.create(),Q=p.create(),R=p.create(),ia=p.create(),T=new B({x:0,y:0,z:0,spatialReference:null});I.Manipulator3D=J;Object.defineProperty(I,Symbol.toStringTag,{value:"Module"})});