// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../Color ../../../core/has ../../../core/handleUtils ../../../core/maybe ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../geometry/projection ../../../support/elevationInfoUtils ./visualElements/ExtendedLineVisualElement ./visualElements/ParallelLineVisualElement ./visualElements/PointVisualElement ./visualElements/RightAngleQuadVisualElement ../layers/interfaces ../webgl-engine/lib/Material ../../interactive/snapping/Settings ../../interactive/snapping/SnappingDomain ../../interactive/snapping/SnappingPoint ../../interactive/snapping/snappingUtils ../../interactive/snapping/SnappingVisualizer ../../interactive/snapping/hints/LineSnappingHint ../../interactive/support/viewUtils".split(" "),
function(z,E,m,A,q,u,F,G,H,v,B,I,C,J,w,l,f,K,x,y,L,D,M){function n(r,p,k,a,b,d=G.create()){b?H.projectVectorToVector(r,p,d,a.basemapTerrain.overlayManager.renderer.spatialReference):M.vectorToRender(r,p,k,a,d);return d}A=function(r){function p(){return r.apply(this,arguments)||this}E._inheritsLoose(p,r);var k=p.prototype;k.sortUniqueHints=function(a){return a.sort((b,d)=>(d instanceof D.LineSnappingHint?d.length:0)-(b instanceof D.LineSnappingHint?b.length:0))};k.visualizeIntersectionPoint=function(a,
b){const {spatialReference:d,view:g}=b;return q.destroyHandle(new C.PointVisualElement({view:g,primitive:"circle",geometry:x.snappingPointToDehydratedPoint(a.intersectionPoint,d),elevationInfo:a.isDraped?v.onTheGroundElevationInfo:v.absoluteHeightElevationInfo,size:20,outlineSize:2,color:[0,0,0,0],outlineColor:m.toUnitRGBA(f.defaults.orange),pixelSnappingEnabled:!1}))};k.visualizePoint=function(a,b){const {view:d,spatialReference:g}=b,e=this._alignPoint(a.point,a.domain,b);return q.destroyHandle(new C.PointVisualElement({view:d,
primitive:"circle",geometry:x.snappingPointToDehydratedPoint(e,g),elevationInfo:this._hintElevationInfo(a,b),size:20,outlineSize:2,color:[0,0,0,0],outlineColor:m.toUnitRGBA(f.defaults.orange),pixelSnappingEnabled:!1}))};k.visualizeLine=function(a,b){const {view:d,spatialReference:g}=b,e=this._alignPoint(a.lineStart,a.domain,b),c=this._alignPoint(a.lineEnd,a.domain,b);return q.destroyHandle(this._createLineSegmentHint(a.type,e,c,g,this._hintElevationInfo(a,b),d,a.isDraped,a.fadeLeft,a.fadeRight))};
k.visualizeParallelSign=function(a,b){const {view:d,spatialReference:g}=b;var {isDraped:e}=a,c=this._hintElevationInfo(a,b),h=this._alignPoint(a.lineStart,a.domain,b);a=this._alignPoint(a.lineEnd,a.domain,b);h=n(h,g,c,d,e);c=n(a,g,c,d,e);c=F.lerp(c,h,c,.5);e=new I.ParallelLineVisualElement({view:d,attached:!1,offset:f.defaults.parallelLineHintOffset,length:f.defaults.parallelLineHintLength,width:f.defaults.parallelLineHintWidth,color:m.toUnitRGBA(f.defaults.orange),location:c,renderOccluded:e?l.RenderOccludedFlag.OccludeAndTransparent:
l.RenderOccludedFlag.Opaque,isDraped:e,renderGroup:w.DrapedRenderGroup.SnappingHint});e.setDirectionFromPoints(h,c);e.attached=!0;return q.destroyHandle(e)};k.visualizeRightAngleQuad=function(a,b){const {view:d,spatialReference:g}=b;var e=this._hintElevationInfo(a,b);const {isDraped:c}=a;var h=this._alignPoint(a.previousVertex,a.domain,b),t=this._alignPoint(a.centerVertex,a.domain,b);a=this._alignPoint(a.nextVertex,a.domain,b);h=n(h,g,e,d,c);t=n(t,g,e,d,c);e=n(a,g,e,d,c);return q.destroyHandle(new J.RightAngleQuadVisualElement({view:d,
attached:!0,color:c?m.toUnitRGBA(f.defaults.orangeTransparent):m.toUnitRGBA(f.defaults.orange),renderOccluded:c?l.RenderOccludedFlag.OccludeAndTransparent:l.RenderOccludedFlag.Transparent,outlineRenderOccluded:c?l.RenderOccludedFlag.OccludeAndTransparent:l.RenderOccludedFlag.Opaque,outlineColor:m.toUnitRGBA(f.defaults.orange),outlineSize:f.defaults.rightAngleHintOutlineSize,size:f.defaults.rightAngleHintSize,isDraped:c,geometry:{previous:h,center:t,next:e},renderGroup:w.DrapedRenderGroup.SnappingHint}))};
k._createLineSegmentHint=function(a,b,d,g,e,c,h=!1,t=!0,N=!0){b=n(b,g,e,c,h);d=n(d,g,e,c,h);c=new B.ExtendedLineVisualElement({view:c,extensionType:B.ExtensionType.FADED,start:b,end:d,isDraped:h,color:m.toUnitRGBA(f.defaults.orange),renderOccluded:h?l.RenderOccludedFlag.OccludeAndTransparent:l.RenderOccludedFlag.Opaque,renderGroup:w.DrapedRenderGroup.SnappingHint});switch(a){case y.LineSegmentHintType.TARGET:c.width=f.defaults.lineHintWidthTarget;c.fadedExtensions={start:0,end:f.defaults.lineHintFadedExtensions};
break;case y.LineSegmentHintType.REFERENCE_EXTENSION:c.width=f.defaults.lineHintWidthReference;c.fadedExtensions={start:0,end:0};break;case y.LineSegmentHintType.REFERENCE:c.width=f.defaults.lineHintWidthReference,c.fadedExtensions={start:t?f.defaults.lineHintFadedExtensions:0,end:N?f.defaults.lineHintFadedExtensions:0}}c.attached=!0;return c};k._alignPoint=function(a,b,d){b=this._getSelfSnappingZ(b,d);return u.isNone(b)?a:x.createSnappingPoint(a[0],a[1],b)};k._hintElevationInfo=function(a,b){return u.isSome(this._getSelfSnappingZ(a.domain,
b))?u.unwrap(b.selfSnappingZ).elevationInfo:a.isDraped?v.onTheGroundElevationInfo:v.absoluteHeightElevationInfo};k._getSelfSnappingZ=function(a,{selfSnappingZ:b}){return a===K.SnappingDomain.SELF&&u.isSome(b)?b.value:null};return p}(L.SnappingVisualizer);z.SnappingVisualizer3D=A;Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});