// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Error ../core/JSONSupport ../core/Loadable ../core/uuid ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass".split(" "),function(n,k,d,l,c,r,t,f,w,x,u){c=function(m){function p(a){a=m.call(this,a)||this;a._sessionId=null;a.url=null;a.sourceJSON=null;a.id=null;a.description=null;a.creationDate=null;a.access="private";return a}k._inheritsLoose(p,
m);var g=p.prototype;g.read=function(a,b){this.sourceJSON=a;m.prototype.read.call(this,a,b)};g.load=function(a){this.addResolvingPromise(this._loadFromSource());return Promise.resolve(this)};g.startReading=function(){var a=k._asyncToGenerator(function*(){if(this.url){const {startReading:b}=yield new Promise((e,h)=>n(["../rest/versionManagementService/gdbVersion/startReading"],e,h));this._sessionId||(this._sessionId=`{${t.generateUUID()}}`);return yield b(this.url,this.guid,this._sessionId)}throw new l("gdb-version:missing-url",
"service url is missing");});return function(){return a.apply(this,arguments)}}();g.stopReading=function(){var a=k._asyncToGenerator(function*(){if(this.url){if(!this._sessionId)throw new l("gdb-version:missing-session-id","reading session has not been started");var {stopReading:b}=yield new Promise((e,h)=>n(["../rest/versionManagementService/gdbVersion/stopReading"],e,h));if(b=yield b(this.url,this.guid,this._sessionId))this._sessionId=null;return b}throw new l("gdb-version:missing-url","service url is missing");
});return function(){return a.apply(this,arguments)}}();g.startEditing=function(){var a=k._asyncToGenerator(function*(){if(this.url){if(!this._sessionId)throw new l("gdb-version:missing-session-id","reading session has not been started");const {startEditing:b}=yield new Promise((e,h)=>n(["../rest/versionManagementService/gdbVersion/startEditing"],e,h));return yield b(this.url,this.guid,this._sessionId)}throw new l("gdb-version:missing-url","service url is missing");});return function(){return a.apply(this,
arguments)}}();g.stopEditing=function(){var a=k._asyncToGenerator(function*(b){if(this.url){if(!this._sessionId)throw new l("gdb-version:missing-session-id","reading session has not been started");const {stopEditing:e}=yield new Promise((h,q)=>n(["../rest/versionManagementService/gdbVersion/stopEditing"],h,q));return yield e(this.url,this.guid,this._sessionId,b)}throw new l("gdb-version:missing-url","service url is missing");});return function(b){return a.apply(this,arguments)}}();g.getStatusInfo=
function(){var a=k._asyncToGenerator(function*(){if(this.url)return yield this._loadFromUrl(this.url,this.guid);throw new l("gdb-version:missing-url","service url is missing");});return function(){return a.apply(this,arguments)}}();g._loadFromSource=function(){var a=k._asyncToGenerator(function*(){this.sourceJSON&&this.read(this.sourceJSON);this.url&&this.guid&&(yield this._loadFromUrl(this.url,this.guid))});return function(){return a.apply(this,arguments)}}();g._loadFromUrl=function(){var a=k._asyncToGenerator(function*(b,
e){const {getVersion:h}=yield new Promise((q,v)=>n(["../rest/versionManagementService/getVersion"],q,v));(b=yield h(b,e))&&this.read(b);return b});return function(b,e){return a.apply(this,arguments)}}();return p}(c.JSONSupportMixin(r));d.__decorate([f.property()],c.prototype,"_sessionId",void 0);d.__decorate([f.property()],c.prototype,"url",void 0);d.__decorate([f.property()],c.prototype,"sourceJSON",void 0);d.__decorate([f.property({type:String,json:{name:"versionName",write:!0}})],c.prototype,"name",
void 0);d.__decorate([f.property({type:String,json:{name:"versionGuid",write:!0}})],c.prototype,"guid",void 0);d.__decorate([f.property({type:Number,json:{name:"versionId",write:!0}})],c.prototype,"id",void 0);d.__decorate([f.property({type:String,json:{write:!0}})],c.prototype,"description",void 0);d.__decorate([f.property({type:Date,json:{type:Number,write:{writer:(m,p)=>{p.creationDate=m?m.getTime():null}}}})],c.prototype,"creationDate",void 0);d.__decorate([f.property({type:["private","public",
"protected","hidden"],json:{write:!0}})],c.prototype,"access",void 0);return c=d.__decorate([u.subclass("esri.versionManagementService.GDBVersion")],c)});