// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/arrayUtils ../../../../../core/MapUtils ../../../../../core/maybe ../../../../../core/NestedMap ../../../../../core/PooledArray ../../../../../chunks/mat4 ../../../../../chunks/mat4f64 ../../../support/buffer/glUtil ../../core/shaderLibrary/ShaderOutput ../../lib/AppleAmdDriverHelper ../../lib/GLMaterials ../../lib/Material ../../lib/ModelDirtyTypes ../../lib/Util ../DrawParameters ../WaterMaterial ./BufferRange ./Instance ./PerBufferData ./PerOriginData ./VaoCache".split(" "),
function(L,R,E,S,t,T,U,F,G,V,H,W,X,Y,A,B,Z,aa,I,M,N,ba,ca){function da(n,u){let a;if(!n.some(d=>{if(d.numElements<u)return!1;a=d;return!0}))return null;const b=a.from;a.from+=u;a.from>=a.to&&n.removeUnordered(a);return b}function C(n){J.length<n&&(J=new Float32Array(n));return J}function O(n){n*=4;return 262144>n?262144:Math.max(Math.min(262144*Math.ceil(1.5*n/262144),16777216),n)}let fa=function(){function n(a,b,d){this._rctx=a;this._materialRepository=b;this.material=d;this._dataByOrigin=new Map;
this._appleAmdDriverHelper=null;this._hasOccludees=this._hasHighlights=!1;this._glMaterials=new X.GLMaterials(this.material,this._materialRepository);this._bufferWriter=d.createBufferWriter();this._vaoCache=new ca.VaoCache(a,d.vertexAttributeLocations,V.glLayout(this._bufferWriter.vertexBufferLayout));this._rctx.driverTest.drawArraysRequiresIndicesTypeReset.result&&(this._appleAmdDriverHelper=new W.AppleAmdDriverHelper(this._rctx))}var u=n.prototype;u.dispose=function(){this._glMaterials.destroy();
this._dataByOrigin.forEach(a=>a.dispose());this._dataByOrigin.clear();this._vaoCache.dispose();this._appleAmdDriverHelper?.dispose()};u.forEachGeometry=function(a){this._dataByOrigin.forEach(b=>b.buffers.forEach(d=>d.instances.forEach(c=>a(c.geometry))))};u.modify=function(a){this._updateGeometries(a.updates);this._addAndRemoveGeometries(a.adds,a.removes);this._updateDrawCommands()};u._updateGeometries=function(a){const b=this._bufferWriter,d=b.vertexBufferLayout.stride/4;for(const f of a){a=f.renderGeometry;
const e=this._dataByOrigin.get(a.localOrigin.id)?.findBuffer(a.id);if(t.isNone(e))break;const l=e.instances.get(a.id);if(f.updateType&(A.DirtyState.GEOMETRY|A.DirtyState.TRANSFORMATION)){var c=b.elementCount(l.geometry.geometry)*d;c=C(c);const m=b.vertexBufferLayout.createView(c.buffer);this._writeGeometry(a,m,0);e.vao.vertexBuffers.geometry.setSubData(c,l.from*d,0,l.numElements*d)}f.updateType&(A.DirtyState.HIGHLIGHT|A.DirtyState.OCCLUDEE|A.DirtyState.VISIBILITY)&&(e.drawCommandsDirty=!0)}};u._computeDeltas=
function(a,b){const d=new T.NestedMap;for(var c of a){a=c.localOrigin;if(t.isNone(a))continue;let f=d.get(a.id,null);t.isNone(f)&&(f=new P(a.vec3),d.set(a.id,null,f));f.changes.push(c)}for(const f of b)b=f.localOrigin,t.isNone(b)||(c=this._dataByOrigin.get(b.id)?.findBuffer(f.id),t.isNone(c)||(a=d.get(b.id,c),t.isNone(a)&&(a=new P(b.vec3),d.set(b.id,c,a)),a.changes.push(f)));return d};u._addAndRemoveGeometries=function(a,b){const {_bufferWriter:d,_dataByOrigin:c}=this,f=d.vertexBufferLayout.stride/
4,e=this._computeDeltas(a,b);e.forEach((l,m)=>{const p=l.get(null),g=t.isSome(p)?p.changes:[];e.delete(m,null);let h=c.get(m);l.forEach((q,k)=>{e.delete(m,k);if(t.isNone(k))B.assert(!1,"No VAO for removed geometries");else if(k.instances.size===q.changes.length)this._vaoCache.deleteVao(k.vao),E.removeUnordered(h.buffers,k),0===h.buffers.length&&0===g.length&&c.delete(m);else{var v=k.numElements,w=k.vao.size/4,r=g.reduce((z,K)=>z+d.elementCount(K.geometry),0),y=q.changes.reduce((z,K)=>z+d.elementCount(K.geometry),
0);v=Math.min((v+r-y)*f,4194304);r=v>w;65536<v&&v<w/2?(q.changes.forEach(({id:z})=>k.deleteInstance(z)),k.instances.forEach(({geometry:z})=>g.push(z)),this._vaoCache.deleteVao(k.vao),E.removeUnordered(h.buffers,k)):r?this._applyAndRebuild(k,g,q):this._applyRemoves(k,q)}});if(0<g.length)for(t.isNone(h)&&(h=new ba.PerOriginData(p.origin),c.set(m,h)),h.buffers.forEach(q=>this._applyAdds(q,g));0<g.length;)h.buffers.push(this._applyAndRebuild(new N.PerBufferData,g,null))})};u._updateDrawCommands=function(){this._hasOccludees=
this._hasHighlights=!1;this._dataByOrigin.forEach(a=>{a.buffers.forEach(b=>{b.drawCommandsDirty&&(b.hasHiddenInstances=!1,b.hasHighlights=!1,b.hasOccludees=!1,S.someMap(b.instances,d=>{b.updateDrawState(d);return b.hasHiddenInstances&&b.hasHighlights&&b.hasOccludees}),b.updateDrawCommands(this._bufferWriter.vertexBufferLayout.stride));this._hasHighlights=this._hasHighlights||b.hasHighlights;this._hasOccludees=this._hasOccludees||b.hasOccludees})})};u._applyAndRebuild=function(a,b,d){if(t.isSome(d))for(var c of d.changes)a.deleteInstance(c.id);
const f=this._bufferWriter;d=f.vertexBufferLayout.stride;c=d/4;var e=Math.floor(4194304/c);let l=a.numElements;for(;0<b.length;){const h=b.pop();var m=f.elementCount(h.geometry);if(l+m>e&&0<l){b.push(h);break}l+=m;m=new M.Instance(h,0,0);B.assert(null==a.instances.get(h.id));a.addInstance(h.id,m)}b=l*c;e=C(b);const p=f.vertexBufferLayout.createView(e.buffer);let g=0;a.hasHiddenInstances=!1;a.hasHighlights=!1;a.hasOccludees=!1;a.instances.forEach((h,q)=>{this._writeGeometry(h.geometry,p,g);const k=
g;g+=f.elementCount(h.geometry.geometry);a.updateInstance(q,k,g);a.updateDrawState(h)});this._vaoCache.deleteVao(a.vao);a.vao=this._vaoCache.newVao(O(b));a.vao.vertexBuffers.geometry.setSubData(e,0,0,g*c);a.holes.clear();b=a.holes.pushNew();b.from=g;b.to=Math.floor(a.vao.size/d);a.updateDrawCommands(d);return a};u._applyRemoves=function(a,b){if(0!==b.changes.length){for(var d of b.changes){var c=d.id;if(b=a.instances.get(c)){a.deleteInstance(c);if(c=x.back()){if(c.to===b.from){c.to=b.to;continue}if(c.from===
b.to){c.from=b.from;continue}}c=x.pushNew();c.from=b.from;c.to=b.to}}I.mergeAdjacentRanges(x);var f=this._bufferWriter.vertexBufferLayout.stride/4;d=x.reduce((m,p)=>Math.max(m,p.numElements),0)*f;var e=C(d);e.fill(0,0,d);var l=a.vao.vertexBuffers.geometry;x.forAll(m=>l.setSubData(e,m.from*f,0,m.numElements*f));a.holes.pushArray(x.data,x.length);x.forAll((m,p)=>x.data[p]=null);x.clear();a.drawCommandsDirty=!0}};u._applyAdds=function(a,b){if(0!==b.length)if(N.hasVao(a)){var d=this._bufferWriter,c=d.vertexBufferLayout.stride/
4,f=a.numElements,e=b.reduce((w,r)=>w+d.elementCount(r.geometry),0);f=Math.min((f+e)*c,4194304);e=4*f;if(a.vao.size<O(4128768)&&e>a.vao.size)this._applyAndRebuild(a,b,null);else{I.mergeAdjacentRanges(a.holes);var l=[];for(var m of b)e=d.elementCount(m.geometry),e=da(a.holes,e),l.push(e);var p=a.vao.vertexBuffers.geometry,g=0,h=0,q=0,k=C(f),v=d.vertexBufferLayout.createView(k.buffer);b.forEach((w,r)=>{r=l[r];if(!t.isNone(r)){if(q!==r){var y=q-h;0<y&&p.setSubData(k,h*c,0,y*c);h=r;g=0}y=d.elementCount(w.geometry);
this._writeGeometry(w,v,g);g+=y;q=r+y;r=new M.Instance(w,r,r+y);B.assert(null==a.instances.get(w.id));a.addInstance(w.id,r);a.drawCommandsDirty=!0}});m=q-h;0<m&&p.setSubData(k,h*c,0,m*c);E.filterInPlace(b,(w,r)=>t.isNone(l[r]))}}else this._applyAndRebuild(a,b,null)};u._writeGeometry=function(a,b,d){var c=a.localOrigin.vec3;B.setMatrixTranslation3(Q,-c[0],-c[1],-c[2]);c=F.multiply(ea,Q,a.transformation);F.invert(D,c);F.transpose(D,D);this._bufferWriter.write(c,D,a.geometry,b,d)};u.updateAnimation=
function(a){return this.material.update(a)};u.requiresSlot=function(a,b){return this.material.requiresSlot(a,b)};u.render=function(a,b){if(!this.requiresSlot(b.slot,a))return!1;const d=a===H.ShaderOutput.Highlight||a===H.ShaderOutput.ShadowHighlight;if(d&&!this._hasHighlights)return!1;const c=a===H.ShaderOutput.ShadowExcludeHighlight,f=!(d||c),e=this._rctx;let l;const m=()=>{if(t.isSome(l))return l;const p=this._glMaterials.load(e,b.slot,a);if(t.isNone(p))return null;l=p.beginSlot(b);if(t.isNone(l))return null;
e.bindTechnique(l,this.material.parameters,b);return l};this._appleAmdDriverHelper?.resetIndicesType();for(const p of this._dataByOrigin.values())for(const g of p.buffers){if(d&&!g.hasHighlights)continue;const h=(d?g.drawCommandsHighlight:c&&g.needsMultipleCommands()?g.drawCommandsShadowHighlightRest:g.drawCommandsDefault)||null,q=f&&g.drawCommandsOccludees||null;if(h?.length||q?.length){const k=m();if(t.isNone(k))return!1;k.program.bindDraw(new Z.DrawParameters(p.origin),b,this.material.parameters);
k.ensureAttributeLocations(g.vao);e.bindVAO(g.vao);h?.length&&(k.bindPipelineState(e,b.slot,!1),h.forAll(v=>e.drawArrays(k.primitiveType,v.first,v.count)));q?.length&&(k.bindPipelineState(e,b.slot,!0),q.forAll(v=>e.drawArrays(k.primitiveType,v.first,v.count)))}}return t.isSome(l)};R._createClass(n,[{key:"isEmpty",get:function(){return 0===this._dataByOrigin.size}},{key:"hasHighlights",get:function(){return this._hasHighlights}},{key:"hasOccludees",get:function(){return this._hasOccludees}},{key:"hasWater",
get:function(){return!this.isEmpty&&this.material instanceof aa.WaterMaterial}},{key:"rendersOccluded",get:function(){return!this.isEmpty&&this.material.renderOccluded!==Y.RenderOccludedFlag.Occlude}},{key:"numGeometries",get:function(){let a=0;this._dataByOrigin.forEach(b=>a+=b.buffers.reduce((d,c)=>d+=c.instances.size,0));return a}},{key:"test",get:function(){return{material:this.material,glMaterials:this._glMaterials,dataByOrigin:this._dataByOrigin}}}]);return n}(),P=function(n){this.origin=n;
this.changes=[]};const Q=G.create(),ea=G.create(),D=G.create(),x=new U({allocator:n=>n||new I.BufferRange,deallocator:null});let J=new Float32Array(65536);L.MergedRenderer=fa;Object.defineProperty(L,Symbol.toStringTag,{value:"Module"})});