// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Color ../../core/Accessor ../../core/asyncUtils ../../core/has ../../core/Handles ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/screenUtils ../../core/timeUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../chunks/vec3f64 ../../views/3d/support/earthUtils ../../views/3d/support/sunUtils ../../views/3d/webgl-engine/shaders/ShadowCastVisualizeTechniqueConfiguration ./DiscreteOptions ./DurationMode ./DurationOptions ./ShadowCastState ./ShadowTooltipViewModel ./ShadowVisualizationType ./ThresholdOptions ../support/traversalUtils".split(" "),
function(u,d,w,c,H,T,I,g,A,l,B,r,e,U,V,J,K,L,M,x,C,N,D,y,O,q,E,P){function v(m,n){g.isSome(m)&&g.isSome(n)&&m.setParameters({shadowCastOptions:n})}function z(m){if(m.suspended)return!1;switch(m.type){case "building-scene-3d":case "csv-3d":case "elevation-3d":case "feature-3d":case "geojson-3d":case "graphics-3d":case "integrated-mesh-3d":case "ogc-feature-3d":case "route-3d":case "scene-layer-3d":case "scene-layer-graphics-3d":case "stream-3d":case "wms-3d":return!0;case "base-dynamic-3d":case "dimension-3d":case "imagery-3d":case "imagery-tile-3d":case "line-of-sight-3d":case "map-image-3d":case "point-cloud-3d":case "tile-3d":case "vector-tile-3d":case "voxel-3d":case "wfs-3d":case "wmts-3d":case "media-3d":return!1;
case "group":return m.layerViews.toArray().some(n=>z(n));default:return!1}}const F=[],Q=K.create(),G=[],R=r.convertTime(1,"hours","milliseconds");c=function(m){function n(b){var a=m.call(this,b)||this;a.view=null;a.tooltip=new O.ShadowTooltipViewModel({getDuration:(f,k)=>a.getDuration(f,k)});a.startTimeOfDay=r.convertTime(10,"hours","milliseconds");a.endTimeOfDay=r.convertTime(16,"hours","milliseconds");a.visualizationType=q.ShadowVisualizationType.Threshold;a.thresholdOptions=new E;a.durationOptions=
new D;a.discreteOptions=new C;a._running=!0;a._handles=new I;a._stopPreviewingTask=null;a._forcePreview=!1;a._autoRestoreForcePreviewEnabled=!0;a._utcOffset=null;a.date=new Date;return a}u._inheritsLoose(n,m);var t=n.prototype;t.initialize=function(){var b=this;this._handles.add([l.watch(()=>({view:this.view,tooltipEnabled:this._tooltipEnabled}),({view:a,tooltipEnabled:f})=>{this.tooltip.view=a;this.tooltip.enabled=f},l.syncAndInitial),l.watch(()=>this._forcePreviewDependencies,()=>{g.abortMaybe(this._stopPreviewingTask);
this._forcePreview=!0;this._autoRestoreForcePreviewEnabled&&(this._stopPreviewingTask=H.createTask(function(){var a=u._asyncToGenerator(function*(f){yield A.after(500,f);A.throwIfAborted(f);b._forcePreview=!1});return function(f){return a.apply(this,arguments)}}()))},l.syncAndInitial),l.watch(()=>({renderer:this.renderer,parameters:this._visualizationParameters}),a=>v(a.renderer,a.parameters),l.syncAndInitial),l.watch(()=>({renderer:this.renderer,parameters:{lightDirections:this._lightDirections}}),
a=>v(a.renderer,a.parameters),l.syncAndInitial),l.watch(()=>({renderer:this.renderer,parameters:{enabled:this._running}}),a=>v(a.renderer,a.parameters),l.syncAndInitial),l.watch(()=>({renderer:this.renderer,parameters:{previewing:this._previewing}}),a=>v(a.renderer,a.parameters),l.syncAndInitial)])};t.destroy=function(){this.stop();this._handles=g.destroyMaybe(this._handles);g.destroyMaybe(this.tooltip)};t.start=function(){this._running=!0};t.stop=function(){this._running=!1};t.setRunning=function(b){this._running=
b};t.getDuration=function(){var b=u._asyncToGenerator(function*(a,f){const {view:k,renderer:p}=this;if(g.isNone(k)||g.isNone(p))return 0;a=k.state.camera.screenToRender(B.createScreenPointArray(a.x,a.y),B.createRenderScreenPointArray());a=p.readAccumulatedShadow(a);f=this._sampleCount;return 0===f?0:this._duration/f*f*a});return function(a,f){return b.apply(this,arguments)}}();u._createClass(n,[{key:"state",get:function(){return g.isSome(this.view)&&this.view.ready&&g.isSome(this._referencePosition)?
y.ShadowCastState.Ready:y.ShadowCastState.Disabled}},{key:"date",set:function(b){b=new Date(b);b.setHours(0,0,0,0);this._set("date",b)}},{key:"utcOffset",get:function(){return g.unwrapOr(this._utcOffset,this._utcOffsetAuto)},set:function(b){this._utcOffset=b}},{key:"testData",get:function(){return{setAutoRestoreForcedPreviewEnabled:b=>{this._autoRestoreForcePreviewEnabled=b},setForcedPreview:b=>{this._forcePreview=b},isPreviewing:()=>this._previewing}}},{key:"_previewing",get:function(){const {view:b}=
this;return g.isNone(b)||g.isNone(b.allLayerViews)?!0:this._forcePreview||!b.stationary||b.allLayerViews.some(a=>z(a)&&a.updating)}},{key:"_utcOffsetAuto",get:function(){return g.mapOr(this._referencePosition,0,b=>L.longitudeToTimezone(b[0],!1))}},{key:"_dateUTCOffset",get:function(){let b=this.date;b=r.offsetDateUTC(b,-b.getTimezoneOffset(),"minutes");return b=r.offsetDateUTC(b,-this.utcOffset,"hours")}},{key:"_startDateTimeUTC",get:function(){return r.offsetDateUTC(this._dateUTCOffset,this.startTimeOfDay)}},
{key:"_endDateTimeUTC",get:function(){return r.offsetDateUTC(this._dateUTCOffset,this.endTimeOfDay)}},{key:"_referencePosition",get:function(){return g.applySome(this.view,b=>g.applySome(b.environmentManager,a=>a.referencePositionWGS84Comparable))}},{key:"_interval",get:function(){const b=0<this._duration?Math.floor(this._duration/255):255,a=this.discreteOptions.interval;switch(this.visualizationType){case q.ShadowVisualizationType.Threshold:case q.ShadowVisualizationType.Duration:return b;case q.ShadowVisualizationType.Discrete:return 0<
a?a:b}}},{key:"_sampleCount",get:function(){return this._lightDirections.length}},{key:"_duration",get:function(){return this.endTimeOfDay-this.startTimeOfDay}},{key:"_lightDirections",get:function(){var {view:b}=this;if(g.isNone(b))return F;var a="global"===b.viewingMode?Q:this._referencePosition;if(g.isNone(a))return F;b=M.computeDirectionsOverTime(this._startDateTimeUTC,this._endDateTimeUTC,this._interval,a,b.state.viewingMode);a=b.length;G.length=0;const f=P.breadthFirstBinaryPartitioning(0,a,
G),k=Array(a);for(let p=0;p<a;++p)k[p]=b[f[p]];return k}},{key:"_tooltipEnabled",get:function(){return this.state===y.ShadowCastState.Ready&&this.visualizationType!==q.ShadowVisualizationType.Discrete&&this._running&&!this._previewing}},{key:"_visualizationParameters",get:function(){if(!this._running)return null;switch(this.visualizationType){case q.ShadowVisualizationType.Threshold:return this._thresholdVisualizationParameters;case q.ShadowVisualizationType.Duration:return this._durationVisualizationParameters;
case q.ShadowVisualizationType.Discrete:return this._discreteVisualizationParameters}}},{key:"_thresholdVisualizationParameters",get:function(){const {value:b,color:a}=this.thresholdOptions,f=this._duration;return{visualization:x.ShadowCastVisualization.Threshold,color:w.toUnitRGBA(a),threshold:0<f?b/this._duration:0}}},{key:"_durationVisualizationParameters",get:function(){const {color:b,mode:a}=this.durationOptions;var f=this._duration;f=0<f&&a===N.DurationMode.Hourly?R/f:0;return{color:w.toUnitRGBA(b),
visualization:x.ShadowCastVisualization.Gradient,bandsEnabled:0<f,bandSize:f}}},{key:"_discreteVisualizationParameters",get:function(){return{color:w.toUnitRGBA(this.discreteOptions.color),visualization:x.ShadowCastVisualization.Gradient,bandsEnabled:!1,bandSize:0}}},{key:"_forcePreviewDependencies",get:function(){var {view:b}=this;if(g.isNone(b))return null;const a=b.slicePlane;var f=b.allLayerViews.toArray().filter(z),k=f.map(h=>h.layer).filter(g.isSome);b=f.map(h=>h.visible);const p=k.map(h=>h.visible),
S=k.map(h=>h.opacity);k=k.filter(h=>"definitionExpression"in h).map(h=>h.definitionExpression);f=f.filter(h=>"filter"in h).map(h=>h.filter);return{slicePlane:a,startDateUTC:this._startDateTimeUTC,endDateUTC:this._endDateTimeUTC,layerViewVisibilities:b,layerVisibilities:p,layerOpacities:S,filters:f,definitionExpressions:k}}},{key:"renderer",get:function(){var {view:b}=this;if(g.isNone(b))return null;b=b._stage;return g.isNone(b)?null:b.renderer}}]);return n}(c);d.__decorate([e.property()],c.prototype,
"state",null);d.__decorate([e.property()],c.prototype,"view",void 0);d.__decorate([e.property()],c.prototype,"tooltip",void 0);d.__decorate([e.property({nonNullable:!0})],c.prototype,"date",null);d.__decorate([e.property({nonNullable:!0})],c.prototype,"utcOffset",null);d.__decorate([e.property({nonNullable:!0})],c.prototype,"startTimeOfDay",void 0);d.__decorate([e.property({nonNullable:!0})],c.prototype,"endTimeOfDay",void 0);d.__decorate([e.property({nonNullable:!0})],c.prototype,"visualizationType",
void 0);d.__decorate([e.property({type:E,nonNullable:!0})],c.prototype,"thresholdOptions",void 0);d.__decorate([e.property({type:D,nonNullable:!0})],c.prototype,"durationOptions",void 0);d.__decorate([e.property({type:C,nonNullable:!0})],c.prototype,"discreteOptions",void 0);d.__decorate([e.property()],c.prototype,"_running",void 0);d.__decorate([e.property()],c.prototype,"_handles",void 0);d.__decorate([e.property()],c.prototype,"_stopPreviewingTask",void 0);d.__decorate([e.property()],c.prototype,
"_forcePreview",void 0);d.__decorate([e.property()],c.prototype,"_autoRestoreForcePreviewEnabled",void 0);d.__decorate([e.property()],c.prototype,"_previewing",null);d.__decorate([e.property()],c.prototype,"_utcOffset",void 0);d.__decorate([e.property()],c.prototype,"_utcOffsetAuto",null);d.__decorate([e.property()],c.prototype,"_dateUTCOffset",null);d.__decorate([e.property()],c.prototype,"_startDateTimeUTC",null);d.__decorate([e.property()],c.prototype,"_endDateTimeUTC",null);d.__decorate([e.property()],
c.prototype,"_referencePosition",null);d.__decorate([e.property()],c.prototype,"_interval",null);d.__decorate([e.property()],c.prototype,"_sampleCount",null);d.__decorate([e.property()],c.prototype,"_duration",null);d.__decorate([e.property()],c.prototype,"_lightDirections",null);d.__decorate([e.property()],c.prototype,"_tooltipEnabled",null);d.__decorate([e.property()],c.prototype,"_visualizationParameters",null);d.__decorate([e.property()],c.prototype,"_thresholdVisualizationParameters",null);d.__decorate([e.property()],
c.prototype,"_durationVisualizationParameters",null);d.__decorate([e.property()],c.prototype,"_discreteVisualizationParameters",null);d.__decorate([e.property()],c.prototype,"_forcePreviewDependencies",null);d.__decorate([e.property()],c.prototype,"renderer",null);return c=d.__decorate([J.subclass("esri.widgets.ShadowCast.ShadowCastViewModel")],c)});