// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Error ./definitions ./GeometryUtils ./Rect ./RectangleBinPack ../../../webgl/enums ../../../webgl/Texture".split(" "),function(y,z,n,u,v,w,x,A){function q(m){return m&&"static"===m.type}return function(){function m(a,c,b=0){this._mosaicPages=[];this._pageHeight=this._pageWidth=this._currentPage=this._maxItemSize=0;this._mosaicRects=new Map;this._spriteCopyQueue=[];this.pixelRatio=1;(0>=a||0>=c)&&console.error("Sprites mosaic defaultWidth and defaultHeight must be greater than zero!");
this._pageWidth=a;this._pageHeight=c;0<b&&(this._maxItemSize=b);this.pixelRatio=window.devicePixelRatio||1;this._binPack=new w(this._pageWidth,this._pageHeight);this._mosaicPages.push({mosaicsData:{type:"static",data:new Uint32Array(Math.floor(this._pageWidth)*Math.floor(this._pageHeight))},size:[this._pageWidth,this._pageHeight],dirty:!0,texture:void 0})}var f=m.prototype;f.getWidth=function(a){return a>=this._mosaicPages.length?-1:this._mosaicPages[a].size[0]};f.getHeight=function(a){return a>=
this._mosaicPages.length?-1:this._mosaicPages[a].size[1]};f.getPageTexture=function(a){return a<this._mosaicPages.length?this._mosaicPages[a].texture:null};f.has=function(a){return this._mosaicRects.has(a)};f.getSpriteItem=function(a){return this._mosaicRects.get(a)};f.addSpriteItem=function(a,c,b,d,h,e,k=1){if(this._mosaicRects.has(a))return this._mosaicRects.get(a);let g,l,p;q(b)?[g,l,p]=this._allocateImage(c[0],c[1]):(g=new v(0,0,c[0],c[1]),l=this._mosaicPages.length,this._mosaicPages.push({mosaicsData:b,
size:[c[0]+2*n.SPRITE_PADDING,c[1]+2*n.SPRITE_PADDING],dirty:!0,texture:void 0}));if(0>=g.width||0>=g.height)return null;e={rect:g,width:c[0],height:c[1],sdf:h,simplePattern:e,pixelRatio:k,page:l};this._mosaicRects.set(a,e);q(b)&&this._copy({rect:g,spriteSize:c,spriteData:b.data,page:l,pageSize:p,repeat:d,sdf:h});return e};f.hasItemsToProcess=function(){return 0!==this._spriteCopyQueue.length};f.processNextItem=function(){const a=this._spriteCopyQueue.pop();a&&this._copy(a)};f.getSpriteItems=function(a){const c=
{};for(const b of a)c[b]=this.getSpriteItem(b);return c};f.getMosaicItemPosition=function(a){const c=(a=this.getSpriteItem(a))&&a.rect;if(!c)return null;c.width=a.width;c.height=a.height;const b=n.SPRITE_PADDING,d=this._mosaicPages[a.page];return{size:[a.width,a.height],tl:[(c.x+b)/d[0],(c.y+b)/d[1]],br:[(c.x+b+a.width)/d[0],(c.y+b+a.height)/d[1]],page:a.page}};f.bind=function(a,c,b=0,d=0){b=this._mosaicPages[b];const h=b.mosaicsData;var e=b.texture;e||(e=b.size,e=new A.Texture(a,{pixelFormat:x.PixelFormat.RGBA,
dataType:x.PixelType.UNSIGNED_BYTE,width:e[0],height:e[1]},null),b.texture=e);e.setSamplingMode(c);q(h)?(a.bindTexture(e,d),b.dirty&&(e.setData(new Uint8Array(h.data.buffer)),e.generateMipmap())):(h.data.bindFrame(a,e,d),e.generateMipmap());b.dirty=!1};m._copyBits=function(a,c,b,d,h,e,k,g,l,p,r){let t=d*c+b;k=g*e+k;if(r)for(k-=e,r=-1;r<=p;r++,t=((r+p)%p+d)*c+b,k+=e)for(g=-1;g<=l;g++)h[k+g]=a[t+(g+l)%l];else for(b=0;b<p;b++){for(d=0;d<l;d++)h[k+d]=a[t+d];t+=c;k+=e}};f._copy=function(a){if(!(a.page>=
this._mosaicPages.length)){var c=this._mosaicPages[a.page],b=c.mosaicsData;if(!q(c.mosaicsData))throw new z("mapview-invalid-resource","unsuitable data type!");var d=a.spriteData;(b=b.data)&&d||console.error("Source or target images are uninitialized!");m._copyBits(d,a.spriteSize[0],0,0,b,a.pageSize[0],a.rect.x+n.SPRITE_PADDING,a.rect.y+n.SPRITE_PADDING,a.spriteSize[0],a.spriteSize[1],a.repeat);c.dirty=!0}};f._allocateImage=function(a,c){a+=2*n.SPRITE_PADDING;c+=2*n.SPRITE_PADDING;var b=Math.max(a,
c);if(this._maxItemSize&&this._maxItemSize<b){b=2**Math.ceil(u.log2(a));const d=2**Math.ceil(u.log2(c));a=new v(0,0,a,c);this._mosaicPages.push({mosaicsData:{type:"static",data:new Uint32Array(b*d)},size:[b,d],dirty:!0,texture:void 0});return[a,this._mosaicPages.length-1,[b,d]]}b=this._binPack.allocate(a,c);return 0>=b.width?(b=this._mosaicPages[this._currentPage],!b.dirty&&q(b.mosaicsData)&&(b.mosaicsData.data=null),this._currentPage=this._mosaicPages.length,this._mosaicPages.push({mosaicsData:{type:"static",
data:new Uint32Array(this._pageWidth*this._pageHeight)},size:[this._pageWidth,this._pageHeight],dirty:!0,texture:void 0}),this._binPack=new w(this._pageWidth,this._pageHeight),this._allocateImage(a,c)):[b,this._currentPage,[this._pageWidth,this._pageHeight]]};f.dispose=function(){this._binPack=null;for(const c of this._mosaicPages){var a=c.texture;a&&a.dispose();a=c.mosaicsData;q(a)||a.data.destroy()}this._mosaicPages=null;this._mosaicRects.clear()};y._createClass(m,[{key:"itemCount",get:function(){return this._mosaicRects.size}}]);
return m}()});