// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../config ../../../../request ../../../../core/BidiText ../../../../core/Error ../../../../core/fontUtils ../../../../core/Logger ../../../../core/mathUtils ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../chunks/vec2 ../../../../chunks/vec2f32 ../../../../symbols/cim/Rasterizer ./definitions ./enums ./GlyphMosaic ./GlyphSource ./SDFConverter ./SpriteMosaic ./Utils ./animatedFormats/AnimatableTextureResource ./animatedFormats/utils ./util/Result ./util/symbolUtils ../../../support/QueueProcessor ../../../webgl/enums".split(" "),
function(l,E,F,G,p,H,I,z,x,y,u,A,J,K,m,v,L,M,N,O,h,P,Q,R,S,T,B){function C(n,g){g=Math.round(u.pt2px(g)*window.devicePixelRatio);return Math.min(n,g*(128<=g?2:4))}const D=J.create(),w=I.getLogger("esri.views.2d.engine.webgl.TextureManager");let U=function(){function n(g,f,a){this.mosaicType=g;this.page=f;this.sdf=a}n.fromMosaic=function(g,f){return new n(g,f.page,f.sdf)};return n}();return function(){function n(f,a,c){this._requestRender=f;this.resourceManager=a;this._allowNonPowerOfTwo=c;this._invalidFontsMap=
new Map;this._sdfConverter=new N(126);this._bindingInfos=[];this._hashToBindingIndex=new Map;this._ongoingRasterizations=new Map;this._imageRequestQueue=new T.QueueProcessor({concurrency:10,process:function(){var b=l._asyncToGenerator(function*(d,e){y.throwIfAborted(e);try{return yield F(d,{responseType:"image",signal:e})}catch(k){if(!y.isAbortError(k))throw new p("mapview-invalid-resource",`Could not fetch requested resource at ${d}`,k);throw k;}});return function(d,e){return b.apply(this,arguments)}}()});
this._spriteMosaic=new O(2048,2048,500);this._glyphSource=new M(`${E.fontsUrl}/{fontstack}/{range}.pbf`);this._glyphMosaic=new L(1024,1024,this._glyphSource);this._rasterizer=new K(a)}var g=n.prototype;g.dispose=function(){this._spriteMosaic.dispose();this._glyphMosaic.dispose();this._rasterizer.dispose();this._sdfConverter.dispose();this._sdfConverter=this._glyphMosaic=this._spriteMosaic=null;this._hashToBindingIndex.clear();this._bindingInfos=this._hashToBindingIndex=null;this._ongoingRasterizations.clear();
this._ongoingRasterizations=null;this._imageRequestQueue.clear();this._imageRequestQueue=null};g.rasterizeItem=function(){var f=l._asyncToGenerator(function*(a,c,b,d){if(x.isNone(a))return w.error(new p("mapview-null-resource","Unable to rasterize null resource",void 0)),null;switch(a.type){case "text":case "esriTS":return a=yield this._rasterizeText(a,b,d),a.forEach(e=>this._setTextureBinding(v.MosaicType.GLYPH,e)),{glyphMosaicItems:a};default:if(h.is3D(a))return w.error(new p("mapview-invalid-type",
`MapView does not support symbol type: ${a.type}`,a)),null;a=yield this._rasterizeSpriteSymbol(a,c,d);R.ok(a)&&a&&this._setTextureBinding(v.MosaicType.SPRITE,a);return{spriteMosaicItem:a}}});return function(a,c,b,d){return f.apply(this,arguments)}}();g.bindTextures=function(f,a,c,b=!1){if(0!==c.textureBinding){var d=this._bindingInfos[c.textureBinding-1];c=d.page;b=b?B.TextureSamplingMode.LINEAR_MIPMAP_LINEAR:B.TextureSamplingMode.LINEAR;switch(d.mosaicType){case v.MosaicType.SPRITE:d=this.sprites.getWidth(c);
const e=this.sprites.getHeight(c);d=A.set(D,d,e);this._spriteMosaic.bind(f,b,c,m.TEXTURE_BINDING_SPRITE_ATLAS);a.setUniform1i("u_texture",m.TEXTURE_BINDING_SPRITE_ATLAS);a.setUniform2fv("u_mosaicSize",d);break;case v.MosaicType.GLYPH:d=A.set(D,this.glyphs.width,this.glyphs.height);this._glyphMosaic.bind(f,b,c,m.TEXTURE_BINDING_GLYPH_ATLAS);a.setUniform1i("u_texture",m.TEXTURE_BINDING_GLYPH_ATLAS);a.setUniform2fv("u_mosaicSize",d);break;default:w.error("mapview-texture-manager",`Cannot handle unknown type ${d.mosaicType}`)}}};
g._hashMosaic=function(f,a){return 1|f<<1|(a.sdf?1:0)<<2|a.page<<3};g._setTextureBinding=function(f,a){const c=this._hashMosaic(f,a);this._hashToBindingIndex.has(c)||(f=U.fromMosaic(f,a),this._hashToBindingIndex.set(c,this._bindingInfos.length+1),this._bindingInfos.push(f));a.textureBinding=this._hashToBindingIndex.get(c)};g._rasterizeText=function(){var f=l._asyncToGenerator(function*(a,c,b){let d,e;d="cim"in a?a.fontName:H.getFullyQualifiedFontName(a.font);e=a.text;a=this._invalidFontsMap.has(d);
c=c?c:h.charCodes(G.bidiText(e)[0]);try{return yield this._glyphMosaic.getGlyphItems(a?"arial-unicode-ms-regular":d,c,b)}catch(k){return w.error(new p("mapview-invalid-resource",`Couldn't find font ${d}. Falling back to Arial Unicode MS Regular`,void 0)),this._invalidFontsMap.set(d,!0),this._glyphMosaic.getGlyphItems("arial-unicode-ms-regular",c,b)}});return function(a,c,b){return f.apply(this,arguments)}}();g._rasterizeSpriteSymbol=function(){var f=l._asyncToGenerator(function*(a,c,b){if(!h.isSimple(a)){c=
S.keyFromSymbol(a);if(this._spriteMosaic.has(c))return this._spriteMosaic.getSpriteItem(c);if(h.isSVGResource(a)||h.isImageResource(a)&&!h.isMarkerPlacementInsidePolygon(a))return this._handleAsyncResource(c,a,b);if(b=this._rasterizer.rasterizeJSONResource(a,m.PATTERN_FILL_RASTERIZATION_SCALE)){const {size:d,image:e,sdf:k,simplePattern:q,rasterizationScale:r}=b;return this._addItemToMosaic(c,d,{type:"static",data:e},h.shouldRepeat(a),k,q,r)}return new p("TextureManager","unrecognized or null rasterized image")}});
return function(a,c,b){return f.apply(this,arguments)}}();g._handleAsyncResource=function(){var f=l._asyncToGenerator(function*(a,c,b){if(this._ongoingRasterizations.has(a))return this._ongoingRasterizations.get(a);c=h.isSVGResource(c)?this._handleSVG(c,a,b):this._handleImage(c,a,b);this._ongoingRasterizations.set(a,c);try{yield c,this._ongoingRasterizations.delete(a)}catch{this._ongoingRasterizations.delete(a)}return c});return function(a,c,b){return f.apply(this,arguments)}}();g._handleSVG=function(){var f=
l._asyncToGenerator(function*(a,c,b){a=yield this._sdfConverter.draw(a.path,b);return this._addItemToMosaic(c,[126,126],{type:"static",data:new Uint32Array(a.buffer)},!1,!0,!0)});return function(a,c,b){return f.apply(this,arguments)}}();g._handleGIFOrPNG=function(){var f=l._asyncToGenerator(function*(a,c,b){var d=h.getUrl(a);yield this.resourceManager.fetchResource(d,b);b=this.resourceManager.getResource(d);if(x.isNone(b))return new p("mapview-invalid-resource",`Could not fetch requested resource at ${d}.`);
d=b.width;let e=b.height;if(b instanceof HTMLImageElement){"esriPMS"===a.type&&(d=Math.round(C(b.width,h.getPMSResourceSize(a))),e=Math.round(d/b.width*b.height));const {size:k,sdf:q,image:r}=this._rasterizer.rasterizeImageResource(d,e,b,"cim"in a?a.cim.colorSubstitutions:void 0);return this._addItemToMosaic(c,k,{type:"static",data:r},h.shouldRepeat(a),q,!1)}this._allowNonPowerOfTwo||(d=z.nextPowerOfTwo(b.width+2*m.SPRITE_PADDING)-2*m.SPRITE_PADDING,e=z.nextPowerOfTwo(b.height+2*m.SPRITE_PADDING)-
2*m.SPRITE_PADDING);if(d!==b.width||e!==b.height)b=Q.resize(b,d,e);b=new P.AnimatableTextureResource(b,this._requestRender,a.animatedSymbolProperties||{},a.objectId);return this._addItemToMosaic(c,[b.width,b.height],{type:"animated",data:b},h.shouldRepeat(a),!1,!1)});return function(a,c,b){return f.apply(this,arguments)}}();g._handleImage=function(){var f=l._asyncToGenerator(function*(a,c,b){if(h.isGIF(a)||h.isPNG(a))return this._handleGIFOrPNG(a,c,b);const d=h.getUrl(a);try{let e;const k=this.resourceManager.getResource(d);
if(x.isSome(k)&&k instanceof HTMLImageElement)e=k;else{const {data:t}=yield this._imageRequestQueue.push(d,{...b});e=t}if(h.isSVGImage(d))if("width"in a&&"height"in a)e.width=u.pt2px(a.width),e.height=u.pt2px(a.height);else if("cim"in a){const t=a.cim;e.width=u.pt2px(t.width??t.scaleX*t.size);e.height=u.pt2px(t.size)}if(!e.width||!e.height)return null;let q=e.width,r=e.height;"esriPMS"===a.type&&(q=Math.round(C(e.width,h.getPMSResourceSize(a))),r=Math.round(q/e.width*e.height));const {size:V,sdf:W,
image:X}=this._rasterizer.rasterizeImageResource(q,r,e,"cim"in a?a.cim.colorSubstitutions:void 0);return this._addItemToMosaic(c,V,{type:"static",data:X},h.shouldRepeat(a),W,!1)}catch(e){if(!y.isAbortError(e))return new p("mapview-invalid-resource",`Could not fetch requested resource at ${d}. ${e.message}`)}});return function(a,c,b){return f.apply(this,arguments)}}();g._addItemToMosaic=function(f,a,c,b,d,e,k){return this._spriteMosaic.addSpriteItem(f,a,c,b,d,e,k)};l._createClass(n,[{key:"sprites",
get:function(){return this._spriteMosaic}},{key:"glyphs",get:function(){return this._glyphMosaic}}]);return n}()});