// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Collection ../../../../core/Handles ../../../../core/Logger ../../../../core/maybe ../../../../core/PooledArray ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/support/aaBoundingRect ./FeatureTileDescriptor3D ./FeatureTileMeasurements3D ../../support/extentUtils ../../../support/Scheduler".split(" "),
function(d,t,e,v,w,x,y,h,z,l,f,E,F,A,k,r,B,C,m){d.FeatureTileTree3D=function(u){function n(a){a=u.call(this,a)||this;a.tiles=new w;a.tileSize=512;a._idToTile=new Map;a._handles=new x;a._clients=new Set;a._dirty=!1;a._pendingTiles=null;a._newTiles=new z;return a}t._inheritsLoose(n,u);var g=n.prototype;g.initialize=function(){this._handles.add([l.watch(()=>[this.tilingScheme,this.tileSize],()=>this._reset(),l.sync),l.watch(()=>[this.tileSize,this.cameraOnSurface?.location,this.tilingScheme,this.viewState?.contentCamera,
this.focus?.location],()=>this._setDirty(),l.syncAndInitial)]);this.scheduler&&(this._frameWorker=this.scheduler.registerTask(m.TaskPriority.FEATURE_TILE_TREE,this))};g.destroy=function(){this._frameWorker=h.removeMaybe(this._frameWorker);this._handles=h.destroyMaybe(this._handles)};g.addClient=function(){const a=D++;this._clients.add(a);1===this._clients.size&&this._setDirty();return{remove:()=>this._removeClient(a)}};g._removeClient=function(a){this._clients.delete(a);this._hasClients||this._clear()};
g._setDirty=function(){!this._hasClients||this.suspended||this._dirty||(this._frameWorker?(this._dirty=!0,this.notifyChange("updating")):this.runTask(m.noBudget))};g._clear=function(){this.tiles.removeAll();this._idToTile.clear();this._reset();this._dirty=!1;this.notifyChange("updating")};g.runTask=function(a){this._dirty=!1;this._pendingTiles||(this._startUpdate(),h.isSome(this._frameWorker)&&(this._frameWorker.priority=m.TaskPriority.FEATURE_TILE_TREE_ACTIVE));this._subdivideTilesForView(a);!this._pendingTiles&&
h.isSome(this._frameWorker)&&(this._frameWorker.priority=m.TaskPriority.FEATURE_TILE_TREE);this.notifyChange("updating")};g._startUpdate=function(){this.suspended||(this.tilingScheme?(this._tileMeasurements||(this._tileMeasurements=new B.FeatureTileMeasurements3D({renderCoordsHelper:this.renderCoordsHelper,tilingScheme:this.tilingScheme,tileSize:this.tileSize})),this._tileMeasurements.begin(this.viewState.contentCamera,this.focus.location,this.cameraOnSurface.location.z??0),this._pendingTiles=this._getRootTiles()):
this._clear())};g._reset=function(){this._newTiles.clear();this._pendingTiles=this._tileMeasurements=null;this._setDirty()};g._getRootTiles=function(){const {tilingScheme:a}=this;return this._rootTileIds.map(b=>new r.FeatureTileDescriptor3D(b[0],b[1],b[2],a))};g._purgeHorizonTiles=function(a){a.sort((b,c)=>{b=b.measures.screenRect;c=c.measures.screenRect;return b[1]+b[3]-(c[1]+c[3])});k.empty(p);for(let b=0;b<a.length;b++)if(k.expand(p,a.data[b].measures.screenRect,p),10<k.height(p))return a.data.slice(b,
a.length);return[]};g._subdivideTilesForView=function(a){if(this._pendingTiles){for(var {tilingScheme:b}=this;0<this._pendingTiles.length&&!a.done;){const c=this._pendingTiles.pop();a.madeProgress();if(!this._filterExtentRect||k.intersects(this._filterExtentRect,c.extent))this._tileMeasurements.updateTile(c),c.measures.visibility!==r.Visibility.INVISIBLE&&(c.measures.shouldSplit?(b.ensureMaxLod(c.lij[0]+1),this._pendingTiles.push(...c.getChildren())):this._newTiles.push(c))}0===this._pendingTiles.length&&
(this._updateTiles(this._purgeHorizonTiles(this._newTiles)),this._newTiles.clear(),this._tileMeasurements.end(),this._pendingTiles=null)}};g._updateTiles=function(a){for(var b of this.tiles.items)b.used=!1;a=a.filter(c=>{const q=this._idToTile.get(c.id);q?(q.copyMeasurementsFrom(c),q.used=!0):this._idToTile.set(c.id,c);return!q});b=this.tiles.items.filter(c=>c.used?!1:(this._idToTile.delete(c.id),!0));this.tiles.removeMany(b);this.tiles.addMany(a);this._sortTiles()};g._sortTiles=function(){this.viewState.fixedContentCamera||
this.tiles.sort((a,b)=>a.measures.visibility!==b.measures.visibility?a.measures.visibility===r.Visibility.VISIBLE_ON_SURFACE?-1:1:a.measures.distance-b.measures.distance);this.tiles.forEach((a,b)=>a.loadPriority=b)};t._createClass(n,[{key:"tilingScheme",get:function(){const a=this.tilingSchemeOwner.tilingScheme;return a?a.clone():null}},{key:"filterExtent",set:function(a){if(h.isSome(a)&&!a.spatialReference.equals(this.viewState.spatialReference))y.getLogger(this.declaredClass).error("#extent","extent spatial reference needs to be in the same spatial reference as the view");
else{var b=this._get("filterExtent");b===a||h.isSome(b)&&a&&b.equals(a)||(a=h.isSome(a)?a.clone():null,this._set("filterExtent",a),this._setDirty())}}},{key:"_filterExtentRect",get:function(){if(h.isNone(this.filterExtent))return null;const a=k.create();C.toBoundingRect(this.filterExtent,a,this.tilingScheme.spatialReference);return a}},{key:"_rootTileIds",get:function(){const {tilingScheme:a}=this;return this._filterExtentRect&&a?a.rootTilesInExtent(this._filterExtentRect):[[0,0,0]]}},{key:"suspended",
set:function(a){a!==this._get("suspended")&&(this._set("suspended",a),this._setDirty())}},{key:"updating",get:function(){return this._dirty||!!this._pendingTiles}},{key:"_hasClients",get:function(){return 0<this._clients.size}},{key:"running",get:function(){return this.updating}}]);return n}(v);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"scheduler",void 0);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"renderCoordsHelper",void 0);e.__decorate([f.property({constructOnly:!0})],
d.FeatureTileTree3D.prototype,"tilingSchemeOwner",void 0);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"cameraOnSurface",void 0);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"focus",void 0);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"viewState",void 0);e.__decorate([f.property({constructOnly:!0})],d.FeatureTileTree3D.prototype,"terrain",void 0);e.__decorate([f.property()],d.FeatureTileTree3D.prototype,"tiles",
void 0);e.__decorate([f.property()],d.FeatureTileTree3D.prototype,"tileSize",void 0);e.__decorate([f.property({readOnly:!0})],d.FeatureTileTree3D.prototype,"tilingScheme",null);e.__decorate([f.property()],d.FeatureTileTree3D.prototype,"filterExtent",null);e.__decorate([f.property({readOnly:!0})],d.FeatureTileTree3D.prototype,"_filterExtentRect",null);e.__decorate([f.property({readOnly:!0})],d.FeatureTileTree3D.prototype,"_rootTileIds",null);e.__decorate([f.property({value:!1})],d.FeatureTileTree3D.prototype,
"suspended",null);e.__decorate([f.property({readOnly:!0})],d.FeatureTileTree3D.prototype,"updating",null);d.FeatureTileTree3D=e.__decorate([A.subclass("esri.views.3d.layers.support.FeatureTileTree3D")],d.FeatureTileTree3D);let D=0;const p=k.create();Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});