// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../layers/graphics/dehydratedFeatures ../../../../rest/query/operations/query ../../support/PBFDecoder".split(" "),function(w,l,f,q,r,x,g,C,D,t,y,
z,A){let k=function(a){function c(b){return a.call(this,b)||this}l._inheritsLoose(c,a);var d=c.prototype;d.queryFeatureCount=function(b,e){return this.layer.queryFeatureCount(b,e)};d.destroy=function(){this._decoder=r.destroyMaybe(this._decoder)};d._createRequestOptions=function(b){return{...b,query:{...this.layer.customParameters,token:this.layer.apiKey,...b?.query}}};l._createClass(c,[{key:"queryFeaturesDehydrated",get:function(){var b=this.layer.capabilities;b=b&&b.query;const e=this.layer.parsedUrl;
if(b&&b.supportsFormatPBF){r.isNone(this._decoder)&&(this._decoder=new A.PBFDecoder(this.controller));const h={sourceSpatialReference:this.layer.spatialReference?.toJSON()??null,applyTransform:!0,maxStringAttributeLength:1024};return(v,m)=>z.runQuery(e,v,"pbf",this._createRequestOptions(m)).then(B=>{x.throwIfAborted(m);return r.isSome(this._decoder)?this._decoder.invoke({buffer:B.data,options:h},m.signal):Promise.reject(x.createAbortError())})}return(h,v)=>z.executeQuery(e,h,this.layer.spatialReference,
this._createRequestOptions(v)).then(m=>y.fromFeatureSetJSON(m.data))}}]);return c}(q);f.__decorate([g.property({constructOnly:!0})],k.prototype,"layer",void 0);f.__decorate([g.property({constructOnly:!0})],k.prototype,"controller",void 0);f.__decorate([g.property({readOnly:!0})],k.prototype,"queryFeaturesDehydrated",null);k=f.__decorate([t.subclass("esri.views.3d.layers.support.featureTileQuery3D.FeatureTileServiceQuery3D")],k);let n=function(a){function c(b){return a.call(this,b)||this}l._inheritsLoose(c,
a);var d=c.prototype;d.queryFeaturesDehydrated=function(b,e){return this.layer.queryFeatures(b,e)};d.queryFeatureCount=function(b,e){return this.layer.queryFeatureCount(b,e)};return c}(q);f.__decorate([g.property({constructOnly:!0})],n.prototype,"layer",void 0);f.__decorate([g.property({readOnly:!0})],n.prototype,"queryFeaturesDehydrated",null);n=f.__decorate([t.subclass("esri.views.3d.layers.support.featureTileQuery3D.FeatureTileServiceMeshQuery3D")],n);let u=function(a){function c(d){return a.call(this,
d)||this}l._inheritsLoose(c,a);c.prototype.queryFeaturesDehydrated=function(d,b){return this.layer.queryFeatures(d,b)};return c}(q);f.__decorate([g.property({constructOnly:!0})],u.prototype,"layer",void 0);u=f.__decorate([t.subclass("esri.views.3d.layers.support.featureTileQuery3D.FeatureTileServiceQuery3D")],u);let p=function(a){function c(b){return a.call(this,b)||this}l._inheritsLoose(c,a);var d=c.prototype;d.queryFeaturesDehydrated=function(b,e){return this.source.queryFeaturesJSON(b,e).then(y.fromFeatureSetJSON,
h=>{if(h&&"query-features-json:unsupported"===h.name)return this.layer.queryFeatures(b,e);throw h;})};d.queryFeatureCount=function(b,e){return this.layer.queryFeatureCount(b,e)};return c}(q);f.__decorate([g.property({constructOnly:!0})],p.prototype,"layer",void 0);f.__decorate([g.property({constructOnly:!0})],p.prototype,"source",void 0);p=f.__decorate([t.subclass("esri.views.3d.layers.support.featureTileQuery3D.FeatureTileClientQuery3D")],p);w.createFeatureTileQuery3D=function(a,c){return"feature"===
a.type&&"feature-layer"===a.source.type?r.isSome(a.infoFor3D)?new n({layer:a}):new k({layer:a,controller:c}):"feature"===a.type&&"memory"===a.source.type||"csv"===a.type||"geojson"===a.type||"oriented-imagery"===a.type||"wfs"===a.type?new p({layer:a,source:a.source}):"ogc-feature"===a.type?new u({layer:a}):null};Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});