// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../core/Error ../../layers/support/layerUtils ../../layers/support/lazyLayerLoader ../PortalItem ./layersLoader ./portalItemUtils ../../support/requestPresets".split(" "),function(h,d,F,k,G,B,e,g,f){function l(){l=d._asyncToGenerator(function*(a){!a.portalItem||a.portalItem instanceof B||(a={...a,portalItem:new B(a.portalItem)});const b=yield H(a.portalItem);return new b.constructor({portalItem:a.portalItem,...b.properties})});return l.apply(this,
arguments)}function H(a){return m.apply(this,arguments)}function m(){m=d._asyncToGenerator(function*(a){yield a.load();a=yield C(a);return I(a)});return m.apply(this,arguments)}function C(a){return n.apply(this,arguments)}function n(){n=d._asyncToGenerator(function*(a){switch(a.type){case "Map Service":return J(a);case "Feature Service":return K(a);case "Feature Collection":return L(a);case "Scene Service":return M(a);case "Image Service":return N(a);case "Stream Service":return{className:"StreamLayer"};
case "Vector Tile Service":return{className:"VectorTileLayer"};case "GeoJson":return{className:"GeoJSONLayer"};case "CSV":return{className:"CSVLayer"};case "KML":return{className:"KMLLayer"};case "WFS":return{className:"WFSLayer"};case "WMTS":return{className:"WMTSLayer"};case "WMS":return{className:"WMSLayer"};case "Feed":return{className:"StreamLayer"};default:throw new F("portal:unknown-item-type","Unknown item type '${type}'",{type:a.type});}});return n.apply(this,arguments)}function I(a){return p.apply(this,
arguments)}function p(){p=d._asyncToGenerator(function*(a){return{constructor:yield(0,G.layerLookupMap[a.className])(),properties:a.properties}});return p.apply(this,arguments)}function J(a){return q.apply(this,arguments)}function q(){q=d._asyncToGenerator(function*(a){return(yield O(a))?{className:"TileLayer"}:{className:"MapImageLayer"}});return q.apply(this,arguments)}function K(a){return r.apply(this,arguments)}function r(){r=d._asyncToGenerator(function*(a){if(g.hasTypeKeyword(a,"Oriented Imagery Layer"))return P(a);
a=yield D(a);if("object"===typeof a){const b={};null!=a.id&&(b.layerId=a.id);return{className:a.className||"FeatureLayer",properties:b}}return{className:"GroupLayer"}});return r.apply(this,arguments)}function M(a){return t.apply(this,arguments)}function t(){t=d._asyncToGenerator(function*(a){const b=yield D(a);if("object"===typeof b){const c={};let u=void 0;null!=b.id?(c.layerId=b.id,u=`${a.url}/layers/${b.id}`):u=a.url;if(a.typeKeywords?.length)for(const E of Object.keys(k.sceneServiceLayerTypeToClassName))if(a.typeKeywords.includes(E))return{className:k.sceneServiceLayerTypeToClassName[E]};
a=yield f.fetchArcGISServiceJSON(u);return{className:k.sceneServiceLayerTypeToClassName[a?.layerType]||"SceneLayer",properties:c}}return!1===b&&"Voxel"===(yield f.fetchArcGISServiceJSON(a.url))?.layerType?{className:"VoxelLayer"}:{className:"GroupLayer"}});return t.apply(this,arguments)}function L(a){return v.apply(this,arguments)}function v(){v=d._asyncToGenerator(function*(a){yield a.load();const b=g.hasTypeKeyword(a,"Map Notes"),c=g.hasTypeKeyword(a,"Markup");if(b||c)return{className:"MapNotesLayer"};
if(g.hasTypeKeyword(a,"Route Layer"))return{className:"RouteLayer"};a=yield a.fetchData();return 1===e.getNumLayersAndTables(a)?{className:"FeatureLayer"}:{className:"GroupLayer"}});return v.apply(this,arguments)}function N(a){return w.apply(this,arguments)}function w(){w=d._asyncToGenerator(function*(a){yield a.load();var b=a.typeKeywords?.map(c=>c.toLowerCase())??[];if(b.includes("elevation 3d layer"))return{className:"ElevationLayer"};if(b.includes("tiled imagery"))return{className:"ImageryTileLayer"};
b=(yield a.fetchData())?.layerType;if("ArcGISTiledImageServiceLayer"===b)return{className:"ImageryTileLayer"};if("ArcGISImageServiceLayer"===b)return{className:"ImageryLayer"};b=yield f.fetchArcGISServiceJSON(a.url);a=b.cacheType?.toLowerCase();b=b.capabilities?.toLowerCase().includes("tilesonly");return"map"===a||b?{className:"ImageryTileLayer"}:{className:"ImageryLayer"}});return w.apply(this,arguments)}function P(a){return x.apply(this,arguments)}function x(){x=d._asyncToGenerator(function*(a){yield a.load();
a=yield a.fetchData();return a.coverage?{className:"GroupLayer"}:{className:"OrientedImageryLayer",properties:a}});return x.apply(this,arguments)}function O(a){return y.apply(this,arguments)}function y(){y=d._asyncToGenerator(function*(a){return(yield f.fetchArcGISServiceJSON(a.url)).tileInfo});return y.apply(this,arguments)}function D(a){return z.apply(this,arguments)}function z(){z=d._asyncToGenerator(function*(a){const b=a.url;if(!b||b.match(/\/\d+$/))return{};yield a.load();var c=yield a.fetchData();
if("Feature Service"===a.type)return a=yield e.preprocessFSItemData(c,b),a=A(a),"object"===typeof a&&(c=e.getSubtypeGroupLayerIds(c),a.className=null!=a.id&&c.includes(a.id)?"SubtypeGroupLayer":"FeatureLayer"),a;if(0<e.getNumLayersAndTables(c))return A(c);c=yield f.fetchArcGISServiceJSON(b);return A(c)});return z.apply(this,arguments)}function A(a){return 1===e.getNumLayersAndTables(a)?{id:e.getFirstLayerOrTableId(a)}:!1}h.fromItem=function(a){return l.apply(this,arguments)};h.selectLayerClassPath=
C;Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});