// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Accessor ../../core/Evented ../../core/maybe ../../core/reactiveUtils ../../core/screenUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../chunks/vec2 ../../chunks/vec3 ../../chunks/vec3f64 ../../geometry/projection ../../support/elevationInfoUtils ../../symbols/support/defaults ../../symbols/support/ElevationInfo ./support/utils ../support/drapedUtils".split(" "),
function(c,r,f,y,z,l,t,m,h,K,L,A,u,B,C,q,D,E,F,G,H){c.GraphicManipulator=function(v){function n(a){a=v.call(this,a)||this;a.layer=null;a.interactive=!0;a.selectable=!1;a.grabbable=!0;a.dragging=!1;a.cursor=null;a.events=new z.EventEmitter;a._circleCollisionCache=null;a._graphicSymbolChangedHandle=null;a._originalSymbol=null;return a}r._inheritsLoose(n,v);var k=n.prototype;k.grabbableForEvent=function(){return!0};k.destroy=function(){this.detachSymbolChanged();this._resetGraphicSymbol();this._set("view",
null)};k.intersectionDistance=function(a){const d=this.graphic;if(!1===d.visible)return null;const e=d.geometry;if(l.isNone(e))return null;var b=this._get("focusedSymbol");b=l.isSome(b)?b:d.symbol;return"2d"===this.view.type?this._intersectDistance2D(this.view,a,e,b):this._intersectDistance3D(this.view,a,d)};k.attach=function(){this.attachSymbolChanged();l.isSome(this.layer)&&this.layer.add(this.graphic)};k.detach=function(){this.detachSymbolChanged();this._resetGraphicSymbol();l.isSome(this.layer)&&
this.layer.remove(this.graphic)};k.attachSymbolChanged=function(){this.detachSymbolChanged();this._graphicSymbolChangedHandle=t.watch(()=>this.graphic?.symbol,a=>{l.isSome(a)&&a!==this.focusedSymbol&&a!==this._originalSymbol&&(this._originalSymbol=a,this._focused&&l.isSome(this.focusedSymbol)&&(this.graphic.symbol=this.focusedSymbol))},t.sync)};k.detachSymbolChanged=function(){l.isSome(this._graphicSymbolChangedHandle)&&(this._graphicSymbolChangedHandle.remove(),this._graphicSymbolChangedHandle=null)};
k.onElevationChange=function(){};k.onViewChange=function(){};k._updateGraphicSymbol=function(){this.graphic.symbol=this._focused&&l.isSome(this.focusedSymbol)?this.focusedSymbol:this._originalSymbol};k._resetGraphicSymbol=function(){this.graphic.symbol=this._originalSymbol};k._intersectDistance2D=function(a,d,e,b){b=b||E.getDefaultSymbol2D(e);if(l.isNone(b))return null;var g=this._circleCollisionCache;if("point"===e.type&&"cim"===b.type&&"CIMPointSymbol"===b.data.symbol?.type&&b.data.symbol.symbolLayers){const {offsetX:p,
offsetY:I,size:J}=G.getSymbolInfo(b);b=m.screenPointObjectToArray(d,w);g=J/2;a=a.toScreen(e);return u.squaredDistance(b,[a.x+p,a.y+I])<g*g?1:null}if("point"!==e.type||"simple-marker"!==b.type)return H.intersectsDrapedGeometry(d,e,a)?1:null;if(l.isNone(g)||!g.originalPoint.equals(e)){const p=a.spatialReference;q.canProjectWithoutEngine(e.spatialReference,p)&&(g=q.project(e,p),this._circleCollisionCache=g={originalPoint:e.clone(),mapPoint:g,radiusPx:m.pt2px(b.size)})}if(l.isSome(g)){e=m.screenPointObjectToArray(d,
w);a=a.toScreen?.(g.mapPoint);if(!a)return null;g=g.radiusPx;d=a.x+m.pt2px(b.xoffset);b=a.y-m.pt2px(b.yoffset);return u.squaredDistance(e,[d,b])<g*g?1:null}return null};k._intersectDistance3D=function(a,d,e){return(d=a.toMap(d,{include:[e]}))&&q.projectPointToVector(d,x,a.renderSpatialReference)?B.distance(x,a.state.camera.eye):null};r._createClass(n,[{key:"graphic",set:function(a){this._circleCollisionCache=null;this._originalSymbol=a.symbol;this._set("graphic",a);this.attachSymbolChanged()}},{key:"elevationInfo",
get:function(){var {layer:a}=this.graphic;a=a&&"elevationInfo"in a?a.elevationInfo:null;const d=D.getGraphicEffectiveElevationMode(this.graphic);return new F({mode:d,offset:a?a.offset:0})}},{key:"focusedSymbol",set:function(a){a!==this._get("focusedSymbol")&&(this._set("focusedSymbol",a),this._updateGraphicSymbol(),this._circleCollisionCache=null)}},{key:"grabbing",set:function(a){a!==this._get("grabbing")&&(this._set("grabbing",a),this._updateGraphicSymbol())}},{key:"hovering",set:function(a){a!==
this._get("hovering")&&(this._set("hovering",a),this._updateGraphicSymbol())}},{key:"selected",set:function(a){a!==this._get("selected")&&(this._set("selected",a),this._updateGraphicSymbol(),this.events.emit("select-changed",{action:a?"select":"deselect"}))}},{key:"_focused",get:function(){return this._get("hovering")||this._get("grabbing")}}]);return n}(y);f.__decorate([h.property({constructOnly:!0,nonNullable:!0})],c.GraphicManipulator.prototype,"graphic",null);f.__decorate([h.property()],c.GraphicManipulator.prototype,
"elevationInfo",null);f.__decorate([h.property({constructOnly:!0,nonNullable:!0})],c.GraphicManipulator.prototype,"view",void 0);f.__decorate([h.property({value:null})],c.GraphicManipulator.prototype,"focusedSymbol",null);f.__decorate([h.property({constructOnly:!0})],c.GraphicManipulator.prototype,"layer",void 0);f.__decorate([h.property()],c.GraphicManipulator.prototype,"interactive",void 0);f.__decorate([h.property()],c.GraphicManipulator.prototype,"selectable",void 0);f.__decorate([h.property()],
c.GraphicManipulator.prototype,"grabbable",void 0);f.__decorate([h.property({value:!1})],c.GraphicManipulator.prototype,"grabbing",null);f.__decorate([h.property()],c.GraphicManipulator.prototype,"dragging",void 0);f.__decorate([h.property()],c.GraphicManipulator.prototype,"hovering",null);f.__decorate([h.property({value:!1})],c.GraphicManipulator.prototype,"selected",null);f.__decorate([h.property()],c.GraphicManipulator.prototype,"cursor",void 0);c.GraphicManipulator=f.__decorate([A.subclass("esri.views.interactive.GraphicManipulator")],
c.GraphicManipulator);const x=C.create(),w=m.createScreenPointArray();Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});