// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/maybe ../../../../../chunks/mat3 ../../../../../chunks/mat3f64 ../../../../../chunks/mat4 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ./AllRenderPasses ./RenderPass ../shaderLibrary/ShaderOutput ../util/TwoVectorPosition ../../lib/depthRange ../../lib/RenderSlot".split(" "),function(r,u,v,l,w,x,h,y,k,e,c,z,A,f){let B=function(){function m(a,b){this.rctx=a;this.shaderTechniqueRepository=b;this.canRender=
!0;this._materialPassParameters=new k.MaterialPassParameters;this._shadowPassParameters=new k.ShadowMapPassParameters;this._highlightPassParameters=new k.HighlightPassParameters;this._systems=new Set;this._passes={materialOpaque:new e.RenderPass(a,b),materialTransparent:new e.RenderPass(a,b,e.RenderPassSorting.BackToFront),materialIntegratedMesh:new e.RenderPass(a,b),shadowMap:new e.RenderPass(a,b),highlight:new e.RenderPass(a,b),highlightIntegratedMesh:new e.RenderPass(a,b),highlightShadowMap:new e.RenderPass(a,
b),defaultShadowMap:new e.RenderPass(a,b)}}var d=m.prototype;d.register=function(a){this._systems.add(a)};d.prepareRender=function(a){if(0!==this._systems.size){for(const b of Object.values(this._passes))b.prepareSubmit();this._systems.forEach(b=>b.submit(this._passes,a.bindParameters));for(const b of Object.values(this._passes))b.finishSubmit();this.shaderTechniqueRepository.frameUpdate()}};d.render=function(a){if(0!==this._systems.size)switch(this._configure(a),this._materialPassParameters.output=
a.output,a.bindParameters.slot){case f.RenderSlot.OPAQUE_MATERIAL:switch(a.output){case c.ShaderOutput.Color:return this._passes.materialOpaque.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Depth:return this._passes.materialOpaque.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Normal:return this._passes.materialOpaque.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Highlight:return this._passes.highlight.dispatch(this._highlightPassParameters,
a.bindParameters);case c.ShaderOutput.Shadow:return this._passes.shadowMap.dispatch(this._shadowPassParameters,a.bindParameters);case c.ShaderOutput.ShadowHighlight:return this._passes.highlightShadowMap.dispatch(this._shadowPassParameters,a.bindParameters);case c.ShaderOutput.ShadowExcludeHighlight:return this._passes.defaultShadowMap.dispatch(this._shadowPassParameters,a.bindParameters);case c.ShaderOutput.ObjectAndLayerIdColor:return this._passes.materialOpaque.dispatch(this._materialPassParameters,
a.bindParameters)}break;case f.RenderSlot.TRANSPARENT_MATERIAL:switch(a.output){case c.ShaderOutput.Color:return this._passes.materialTransparent.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Alpha:return this._passes.materialTransparent.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Depth:return this._passes.materialTransparent.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Normal:return this._passes.materialTransparent.dispatch(this._materialPassParameters,
a.bindParameters);case c.ShaderOutput.ObjectAndLayerIdColor:return this._passes.materialTransparent.dispatch(this._materialPassParameters,a.bindParameters)}break;case f.RenderSlot.INTEGRATED_MESH:switch(a.output){case c.ShaderOutput.Color:return this._passes.materialIntegratedMesh.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Depth:return this._passes.materialIntegratedMesh.dispatch(this._materialPassParameters,a.bindParameters);case c.ShaderOutput.Normal:return this._passes.materialIntegratedMesh.dispatch(this._materialPassParameters,
a.bindParameters);case c.ShaderOutput.Highlight:return this._passes.highlightIntegratedMesh.dispatch(this._highlightPassParameters,a.bindParameters);case c.ShaderOutput.ObjectAndLayerIdColor:return this._passes.materialIntegratedMesh.dispatch(this._materialPassParameters,a.bindParameters)}}};d.notifyDirty=function(){this._context.requestRender()};d.slots=function(){return[f.RenderSlot.OPAQUE_MATERIAL,f.RenderSlot.TRANSPARENT_MATERIAL,f.RenderSlot.INTEGRATED_MESH]};d.initializeRenderContext=function(a){this._context=
a};d.uninitializeRenderContext=function(){};d.queryDepthRange=function(a){const b={near:Infinity,far:-Infinity};this._systems.forEach(g=>{g=g.queryShadowCasterDepthRange(a);v.isSome(g)&&A.union(b,g,b)});return b};d._configure=function(a){this._updateParameters(a,a.output===c.ShaderOutput.Shadow||a.output===c.ShaderOutput.ShadowHighlight||a.output===c.ShaderOutput.ShadowExcludeHighlight?this._shadowPassParameters:a.output===c.ShaderOutput.Highlight?this._highlightPassParameters:this._materialPassParameters)};
d._updateParameters=function(a,b){const g=a.bindParameters.camera,n=g.viewInverseTransposeMatrix;h.set(p,n[3],n[7],n[11]);q.set(p);h.copy(b.transformWorldFromViewTH,q.high);h.copy(b.transformWorldFromViewTL,q.low);h.copy(b.slicePlaneLocalOrigin,p);l.fromMat4(b.transformViewFromCameraRelativeRS,g.viewMatrix);x.copy(b.transformProjFromView,g.projectionMatrix);b.identifier===k.RenderPassIdentifier.Material&&(this._materialPassParameters.transparent=a.bindParameters.slot===f.RenderSlot.TRANSPARENT_MATERIAL,
this._materialPassParameters.integratedMesh=a.bindParameters.slot===f.RenderSlot.INTEGRATED_MESH,l.transpose(t,b.transformViewFromCameraRelativeRS),l.invert(b.transformNormalViewFromGlobal,t))};u._createClass(m,[{key:"needsHighlight",get:function(){return 0<this._passes.highlight.count||0<this._passes.highlightIntegratedMesh.count}},{key:"needsTransparentPass",get:function(){return 0<this._passes.materialTransparent.count}}]);return m}();const p=y.create(),t=w.create(),q=new z.TwoVectorPosition;r.RenderPassManager=
B;Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});