// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../Basemap ../Viewpoint ../core/asyncUtils ../core/Collection ../core/collectionUtils ../core/JSONSupport ../core/Logger ../core/maybe ../core/promiseUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/accessorSupport/decorators/subclass ../core/accessorSupport/ensureType ../chunks/vec3 ../chunks/vec3f64 ../layers/Layer ../layers/mixins/OperationalLayer ../support/basemapUtils ../views/3d/support/mathUtils ../views/3d/support/viewpointUtils ../views/support/Scheduler ../webdoc/support/SlideThumbnail ./SunLighting ./VirtualLighting ./support/Description ./support/SlideEnvironment ./support/SlideGround ./support/SlideVisibleLayer ./support/Title".split(" "),
function(r,k,R,S,T,H,U,g,V,q,B,W,n,v,ja,X,C,I,D,Y,Z,J,aa,ba,ca,u,da,ea,y,K,L,M,w){function N(f){if("building-scene"===f.type||"map-image"===f.type)return f.allSublayers.toArray()}function O(f){if(f=N(f))return f.filter(l=>l.visible).map(l=>l.id)}function fa(f,l){f=l-f;43200<f&&(f-=86400);-43200>f&&(f+=86400);return f}let ha=0;const E=H.ofType(M.SlideVisibleLayer);g=function(f){function l(a){a=f.call(this,a)||this;a.id=Date.now().toString(16)+"-slide-"+ha++;a.title=new w;a.description=new y;a.thumbnail=
new u.SlideThumbnail;a.viewpoint=null;a.basemap=null;a.ground=null;a.environment=new K.SlideEnvironment;a.visibleLayers=new E;return a}r._inheritsLoose(l,f);var e=l.prototype;e.destroy=function(){this.visibleLayers.removeAll();this.basemap=null;this.thumbnail=q.destroyMaybe(this.thumbnail);this.thumbnail=this.title=this.description=null};e.castTitle=function(a){return"string"===typeof a?new w({text:a}):C.ensureType(w,a)};e.castDescription=function(a){return"string"===typeof a?new y({text:a}):C.ensureType(y,
a)};e.castThumbnail=function(a){return"string"===typeof a?new u.SlideThumbnail({url:a}):C.ensureType(u.SlideThumbnail,a)};e.castBasemap=function(a){return J.ensureType(a)};e.castVisibleLayers=function(a){return a&&"function"===typeof a.map?a.map(b=>{if("string"===typeof b)return{id:b};if(b instanceof Y){const c=O(b);return{id:b.id,sublayerIds:c}}if(b.id)return{id:b.id,sublayerIds:"sublayerIds"in b?b.sublayerIds:void 0};V.getLogger(this.declaredClass).warn('Invalid visible layer, expected { id }, Layer or "id"');
return b}):null};e.clone=function(){return new this.constructor({id:this.id,title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&this.viewpoint.clone()||null,basemap:this.basemap&&this.basemap.clone()||null,ground:this.ground&&this.ground.clone()||null,visibleLayers:this.visibleLayers.clone(),environment:this.environment&&this.environment.clone()||null})};e._updateVisibleLayersFrom=function(a){const b=[];return B.eachAlways(this._getLayers(a.map).map(c=>
a.whenLayerView(c).then(d=>{if(d.visible){const h=O(c);b.push(new M.SlideVisibleLayer({id:d.layer.id,sublayerIds:h}))}})).toArray()).then(()=>{this.visibleLayers.removeAll();this.visibleLayers.addMany(b)})};e.updateFrom=function(a,b){const c={format:"png",quality:80,width:120,height:75,disableDecorations:!0,...(b&&b.screenshot)};return a.when(()=>{this.viewpoint=a.viewpoint.clone();this.environment.lighting="virtual"===a.environment.lighting.type?ea.prototype.clone.apply(a.environment.lighting):da.prototype.clone.apply(a.environment.lighting);
this.environment.weather=a.environment.weather.clone();this.basemap=a.map.basemap&&a.map.basemap.clone()||null;this.ground=a.map.ground?L.fromGround(a.map.ground):null;return this._updateVisibleLayersFrom(a)}).then(()=>a.takeScreenshot(c)).then(d=>{this.thumbnail=new u.SlideThumbnail({url:d.dataUrl});return this})};e.applyTo=function(){var a=r._asyncToGenerator(function*(b,c){var d=this;q.isSome(this._applyToController)&&this._applyToController.abort();let h=new AbortController;this._applyToController=
h;const F=B.onAbortOrThrow(c,()=>h?.abort()),p=b.resourceController.scheduler.registerTask(ca.TaskPriority.SLIDE);let z=!1;const m={animate:!0,...c,signal:this._applyToController.signal};c=function(){var A=r._asyncToGenerator(function*(){yield Promise.all([p.schedule(()=>z=d._setViewpointOfInterest(b,m)),p.schedule(()=>d._applyBasemap(b,m),m.signal)]);yield Promise.all([p.schedule(()=>d._applyLayerVisibility(b),m.signal),p.schedule(()=>d._applyGround(b),m.signal),p.schedule(()=>d._applyViewpoint(b,
m),m.signal)]);yield p.schedule(()=>b.environment.weather=d.environment.weather.clone())});return function(){return A.apply(this,arguments)}}();c=yield T.result(b.addUpdatingPromise(c()));z&&(b.contentCamera=null);p.remove();this._applyToController===h&&(this._applyToController=null);h=null;F?.remove();if(!1===c.ok)throw c.error;return this});return function(b,c){return a.apply(this,arguments)}}();e._applyBasemap=function(){var a=r._asyncToGenerator(function*(b,c){if(this.basemap){try{yield this.basemap.load(c)}catch(d){if(B.isAbortError(d))throw d;
}b.map.basemap=J.clonePreservingTiledLayers(this.basemap,b.map.basemap)}});return function(b,c){return a.apply(this,arguments)}}();e._applyGround=function(a){this.ground&&(a.map.ground=this.ground.cloneAndApplyTo(a.map.ground))};e._getLayers=function(a){const b=new H;this._collectLayers(a,b);this._collectLayers(a.ground,b);return b};e._collectLayers=function(a,b){a.layers.forEach(c=>{Z.isOperationalLayer(c)&&(b.add(c),"layers"in c&&this._collectLayers(c,b))})};e._applyLayerVisibility=function(a){this.visibleLayers&&
this._getLayers(a.map).forEach(b=>{var c=this.visibleLayers.find(h=>h.id===b.id);b.visible=null!=c;const d=c&&c.sublayerIds;c=N(b);d&&c&&c.forEach(h=>h.visible=d.includes(h.id))})};e._setViewpointOfInterest=function(a,b){if(a.state.fixedContentCamera||!this.viewpoint||b?.ignoreViewpoint||!b?.useDestinationCamera)return!1;b=ba.toCamera(a,this.viewpoint);a.contentCamera=b;return q.isSome(b)};e._applyViewpoint=function(){var a=r._asyncToGenerator(function*(b,c){this._applyCachedCameraTrackingEnabled(b);
if(this.viewpoint&&!c.ignoreViewpoint){q.isSome(this.viewpoint.camera)&&(this.viewpoint.camera.fov=b.camera.fov);if(c.animate&&this.get("environment.lighting.date"))return this._animateToLighting(b,c);c.animate&&(b.environment.applyLighting(this.environment.lighting.clone()),yield b.goTo(this.viewpoint,c));b.viewpoint=this.viewpoint}b.environment.applyLighting(this.environment.lighting.clone())});return function(b,c){return a.apply(this,arguments)}}();e._animateToLighting=function(){var a=r._asyncToGenerator(function*(b,
c){let d=null;"virtual"!==b.environment.lighting.type&&"virtual"!==this.environment.lighting.type&&("global"===b.viewingMode&&(d=this._animateLightingWithCamera(b,b.environment.lighting,this.environment.lighting)),b.environment.cachedCameraTrackingEnabled=b.environment.lighting.cameraTrackingEnabled,b.environment.lighting.cameraTrackingEnabled=!1);b.environment.lighting.directShadowsEnabled=this.environment.lighting.directShadowsEnabled;"virtual"===this.environment.lighting.type||"virtual"===b.environment.lighting.type?
(b.environment.applyLighting(this.environment.lighting.clone()),"virtual"!==b.environment.lighting.type&&(b.environment.cachedCameraTrackingEnabled=b.environment.lighting.cameraTrackingEnabled,b.environment.lighting.cameraTrackingEnabled=!1)):null!=this.environment.lighting.displayUTCOffset&&(b.environment.lighting.displayUTCOffset=this.environment.lighting.displayUTCOffset);return b.goTo(this.viewpoint,c).then(()=>{this._applyCachedCameraTrackingEnabled(b);b.environment.applyLighting(this.environment.lighting.clone())}).catch(h=>
{q.isNone(b.animation)&&this._applyCachedCameraTrackingEnabled(b);throw h;}).finally(()=>{q.removeMaybe(d)})});return function(b,c){return a.apply(this,arguments)}}();e._applyCachedCameraTrackingEnabled=function(a){q.isSome(a.environment.cachedCameraTrackingEnabled)&&(a.environment.lighting.cameraTrackingEnabled=a.environment.cachedCameraTrackingEnabled,a.environment.cachedCameraTrackingEnabled=null)};e._getTime=function(a){const b=a.getTime();a=3600*a.getUTCHours()+60*a.getUTCMinutes()+a.getUTCSeconds();
return[b,a]};e._setTime=function(a,b,c){a.setTime(b);a.setUTCHours(c/3600);a.setUTCMinutes(c%3600/60);a.setUTCSeconds(c%3600%60);return a};e._animateLightingWithCamera=function(a,b,c){const [d,h]=this._getTime(new Date(b.date.toString())),[F,p]=this._getTime(c.date),z=fa(h,p),m=a.renderCoordsHelper,A=D.create();m.toRenderCoords(a.camera.position,A);const P=D.create(),G=D.create();q.isSome(this.viewpoint.camera)&&m.toRenderCoords(this.viewpoint.camera.position,P);const ia=new Date;return W.when(()=>
a.camera,t=>{m.toRenderCoords(t.position,G);var x=I.squaredDistance(A,G);const Q=I.squaredDistance(P,G);t=0;0!==x+Q&&(t=x/(x+Q));x=d+(F-d)*t;t=aa.moduloPositive(h+z*t,86400);b.date=this._setTime(ia,x,t)})};l.createFrom=function(a,b){return(new this).updateFrom(a,b)};r._createClass(l,[{key:"visibleLayers",set:function(a){this._set("visibleLayers",U.referenceSetter(a,this._get("visibleLayers"),E))}}]);return l}(g.JSONSupport);k.__decorate([n.property({type:String,json:{write:{isRequired:!0}}})],g.prototype,
"id",void 0);k.__decorate([n.property({type:w,json:{default:()=>new w({text:""}),write:{isRequired:!0}}})],g.prototype,"title",void 0);k.__decorate([v.cast("title")],g.prototype,"castTitle",null);k.__decorate([n.property({type:y,json:{write:{overridePolicy(f){return{enabled:!(!f||!f.text)}}}}})],g.prototype,"description",void 0);k.__decorate([v.cast("description")],g.prototype,"castDescription",null);k.__decorate([n.property({type:u.SlideThumbnail,json:{default:()=>new u.SlideThumbnail({url:""}),
write:{isRequired:!0}}})],g.prototype,"thumbnail",void 0);k.__decorate([v.cast("thumbnail")],g.prototype,"castThumbnail",null);k.__decorate([n.property({type:S,nonNullable:!0,json:{write:{isRequired:!0}}})],g.prototype,"viewpoint",void 0);k.__decorate([n.property({type:R,json:{read:{source:"baseMap"},write:{target:"baseMap"}}})],g.prototype,"basemap",void 0);k.__decorate([v.cast("basemap")],g.prototype,"castBasemap",null);k.__decorate([n.property({type:L,json:{write:!0}})],g.prototype,"ground",void 0);
k.__decorate([n.property({type:E,json:{write:{isRequired:!0}}})],g.prototype,"visibleLayers",null);k.__decorate([v.cast("visibleLayers")],g.prototype,"castVisibleLayers",null);k.__decorate([n.property({type:K.SlideEnvironment,json:{write:!0}})],g.prototype,"environment",void 0);return g=k.__decorate([X.subclass("esri.webscene.Slide")],g)});