// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/sphere ../../support/mathUtils ./basicInterfaces ./ContentObject ./ContentObjectType ./Object3DStateID ./Util ../materials/renderers/utils".split(" "),function(w,t,n,p,x,e,l,y,z,A,u,G,B,H,q){function C(f,d,c){var a=f.bbMin;f=f.bbMax;if(p.hasIdentityRotation(c))for(c=e.set(I,c[12],c[13],c[14]),e.add(g,
a,c),e.add(k,f,c),a=0;3>a;++a)d.min[a]=Math.min(d.min[a],g[a]),d.max[a]=Math.max(d.max[a],k[a]);else if(e.transformMat4(g,a,c),e.exactEquals(a,f))for(a=0;3>a;++a)d.min[a]=Math.min(d.min[a],g[a]),d.max[a]=Math.max(d.max[a],g[a]);else{e.transformMat4(k,f,c);for(var b=0;3>b;++b)d.min[b]=Math.min(d.min[b],g[b],k[b]),d.max[b]=Math.max(d.max[b],g[b],k[b]);for(b=0;3>b;++b){e.copy(g,a);e.copy(k,f);g[b]=f[b];k[b]=a[b];e.transformMat4(g,g,c);e.transformMat4(k,k,c);for(let h=0;3>h;++h)d.min[h]=Math.min(d.min[h],
g[h],k[h]),d.max[h]=Math.max(d.max[h],g[h],k[h])}}}u=function(f){function d(a={}){var b=f.call(this)||this;b.type=G.ContentObjectType.Object;b._geometries=[];b._transformation=x.create();b._bvObjectSpace=new D;b._bvWorldSpace=new D;b._bvDirty=!0;b._hasVolatileTransformation=!1;b._visible=!0;b.castShadow=null!=a.castShadow?a.castShadow:!0;b.metadata=a.metadata;b.metadata&&b.metadata.isElevationSource&&(b.metadata.lastValidElevationBB=new E);a=a.geometries;n.isSome(a)&&(b._geometries=Array.from(a));
return b}t._inheritsLoose(d,f);var c=d.prototype;c.dispose=function(){this._geometries.length=0};c.addGeometry=function(a){a.visible=this._visible;this._geometries.push(a);this._hasVolatileTransformation=this._hasVolatileTransformation||a.hasVolatileTransformation;this._emit("objectGeometryAdded",{object:this,geometry:a});this._invalidateBoundingVolume()};c.removeGeometry=function(a){if(a=this._geometries.splice(a,1)[0])this._emit("objectGeometryRemoved",{object:this,geometry:a}),this._invalidateBoundingVolume()};
c.removeAllGeometries=function(){for(;0<this._geometries.length;)this.removeGeometry(0)};c.geometryVertexAttrsUpdated=function(a){this._emit("objectGeometryUpdated",{object:this,geometry:a});this._invalidateBoundingVolume()};c.maskOccludee=function(){const a=new B.Object3DStateID(A.Object3DState.MaskOccludee);for(const b of this._geometries)b.occludees=q.addObject3DStateID(b.occludees,a);this._emit("occlusionChanged",this);return a};c.removeOcclude=function(a){for(const b of this._geometries)b.occludees=
q.removeObject3DStateID(b.occludees,a);this._emit("occlusionChanged",this)};c.highlight=function(){const a=new B.Object3DStateID(A.Object3DState.Highlight);for(const b of this._geometries)b.highlights=q.addObject3DStateID(b.highlights,a);this._emit("highlightChanged",this);return a};c.removeHighlight=function(a){for(const b of this._geometries)b.highlights=q.removeObject3DStateID(b.highlights,a);this._emit("highlightChanged",this)};c.getCombinedStaticTransformation=function(a,b){return p.multiply(b,
this.transformation,a.transformation)};c._getCombinedShaderTransformation=function(a){return p.multiply(x.create(),this.transformation,a.shaderTransformation)};c.hasVolativeTransformation=function(){return this._hasVolatileTransformation};c._validateBoundingVolume=function(){if(this._bvDirty||this._hasVolatileTransformation){this._bvObjectSpace.init();this._bvWorldSpace.init();for(var a of this._geometries){var b=a.boundingInfo;n.isSome(b)&&(C(b,this._bvObjectSpace,a.shaderTransformation),C(b,this._bvWorldSpace,
this._getCombinedShaderTransformation(a)))}e.lerp(this._bvObjectSpace.bounds,this._bvObjectSpace.min,this._bvObjectSpace.max,.5);e.lerp(this._bvWorldSpace.bounds,this._bvWorldSpace.min,this._bvWorldSpace.max,.5);a=l.create();b=l.create();var h=z.maxScale(this.transformation);for(const F of this._geometries){var m=F.boundingInfo;if(!n.isNone(m)){var r=F.shaderTransformation,v=z.maxScale(r);e.transformMat4(a,m.center,r);r=e.distance(a,this._bvObjectSpace.bounds);m=m.radius*v;this._bvObjectSpace.bounds[3]=
Math.max(this._bvObjectSpace.bounds[3],r+m);e.transformMat4(b,a,this.transformation);v=e.distance(b,this._bvWorldSpace.bounds);this._bvWorldSpace.bounds[3]=Math.max(this._bvWorldSpace.bounds[3],v+m*h)}}this._bvDirty=!1}};c._invalidateBoundingVolume=function(){this._bvDirty=!0;n.isSome(this._parentLayer)&&this._parentLayer.notifyObjectBBChanged(this,this._bvWorldSpace.bounds)};c._emit=function(a,b){n.isSome(this._parentLayer)&&this._parentLayer.events.emit(a,b)};t._createClass(d,[{key:"geometries",
get:function(){return this._geometries}},{key:"transformation",get:function(){return this._transformation},set:function(a){p.copy(this._transformation,a);this._invalidateBoundingVolume();this._emit("objectTransformation",this)}},{key:"parentLayer",get:function(){return this._parentLayer},set:function(a){H.assert(null==this._parentLayer||null==a,"Object3D can only be added to a single Layer");this._parentLayer=a}},{key:"visible",get:function(){return this._visible},set:function(a){if(this._visible!==
a){this._visible=a;for(const b of this._geometries)b.visible=this._visible;this._emit("visibilityChanged",this)}}},{key:"boundingVolumeWorldSpace",get:function(){this._validateBoundingVolume();return this._bvWorldSpace}},{key:"boundingVolumeObjectSpace",get:function(){this._validateBoundingVolume();return this._bvObjectSpace}},{key:"test",get:function(){const a=this;return{hasGeometry:b=>a._geometries.includes(b),getGeometryIndex:b=>a._geometries.indexOf(b)}}}]);return d}(u.ContentObject);let E=function(){function f(){this.min=
l.fromValues(Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE);this.max=l.fromValues(-Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE)}f.prototype.isEmpty=function(){return this.max[0]<this.min[0]&&this.max[1]<this.min[1]&&this.max[2]<this.min[2]};return f}(),D=function(f){function d(){var c=f.apply(this,arguments)||this;c.bounds=y.create();return c}t._inheritsLoose(d,f);d.prototype.init=function(){e.set(this.min,Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE);e.set(this.max,-Number.MAX_VALUE,
-Number.MAX_VALUE,-Number.MAX_VALUE);y.clear(this.bounds)};return d}(E);const I=l.create(),g=l.create(),k=l.create();w.Object3D=u;Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});