// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Evented ../../../../core/MapUtils ../../../../core/mathUtils ../../../../core/maybe ../../../../core/uid ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec4 ../../../../chunks/vec4f64 ./ContentObjectType ./testUtils ./VertexAttribute ../../../support/Scheduler ../../../webgl/enums ../../../webgl/Texture".split(" "),
function(l,w,t,A,B,x,C,m,D,y,M,N,E,F,G,H,I,q,u,r,J){let K=function(){this.offset={x:0,y:0};this.uvMinMax=G.create()},L=function(h,n){this.textId=h;this.textRenderer=n;this.placement=new K;this.rendered=!1};l.TextTextureAtlas=function(h){function n(a){a=h.call(this,a)||this;a.type=H.ContentObjectType.Texture;a.id=D.generateUID();a.events=new B;a._glTexture=null;a._needsClear=!1;a._elementsToAddOrUpdate=new Map;a._elementsToRemove=new Map;a._elementsToRender=new Map;a._elements=new Map;a._stageObjects=
new Map;a.updating=!1;return a}w._inheritsLoose(n,h);var d=n.prototype;d.initialize=function(){this._stage=this.view._stage;this._canvas=this._create2DCanvas();this._ctx=this._canvas.getContext("2d");this._stage.add(this);const a=this._computeAtlasResolution(this.view.width,this.view.height);this._createAtlasRegion(a);this._update2DCanvasSize();this._resetAtlasCursor()};d.unload=function(){this._glTexture=m.disposeMaybe(this._glTexture);this.updating=!1;this.events.emit("unloaded")};d._createDescriptor=
function(a){return{target:r.TextureType.TEXTURE_2D,pixelFormat:r.PixelFormat.RGBA,dataType:r.PixelType.UNSIGNED_BYTE,wrapMode:r.TextureWrapMode.CLAMP_TO_EDGE,flipped:!0,samplingMode:r.TextureSamplingMode.LINEAR_MIPMAP_LINEAR,hasMipmap:!0,preMultiplyAlpha:!0,maxAnisotropy:a.parameters.maxMaxAnisotropy}};d.load=function(a){if(m.isSome(this._glTexture))return this._glTexture;this._glTexture=new J.Texture(a,this._createDescriptor(a),this._canvas);this._frameWorker=this.view.resourceController.scheduler.registerTask(u.TaskPriority.TEXT_TEXTURE_ATLAS,
this);this.setDirty();return this._glTexture};d.dispose=function(){this._elementsToRender=this._elementsToRemove=this._elementsToAddOrUpdate=this._elements=null;this._frameWorker=m.removeMaybe(this._frameWorker);this._glTexture&&(this._stage.remove(this),this._glTexture=m.disposeMaybe(this._glTexture));this._canvas.width=0;this._canvas.height=0;this._ctx=this._canvas=null};d._create2DCanvas=function(){const a=document.createElement("canvas");a.setAttribute("id","canvas2d");a.setAttribute("style",
"display:none");a.setAttribute("width",(512).toString());a.setAttribute("height",(512).toString());return a};d._update2DCanvasSize=function(){this._canvas.setAttribute("width",this._atlas.size.width.toString());this._canvas.setAttribute("height",this._atlas.size.height.toString())};d._createAtlasRegion=function(a=512){this._atlas={size:{width:a,height:a},cursor:{x:0,y:0},lineHeight:0}};d._computeAtlasResolution=function(a,c){a=Math.max(a,c);a=C.nextHighestPowerOfTwo(a+256);return a=Math.min(a,4096)};
d._resizeAtlas=function(a,c){c=c||a;const b=this._atlas;b.size.width=a;b.size.height=c;m.isSome(this._glTexture)&&this._glTexture.resize(a,c);this._update2DCanvasSize()};d._resetAtlasCursor=function(){const a=this._atlas;a.cursor.x=2;a.cursor.y=4;a.lineHeight=0;this._needsClear=!0};d._getAtlasUsage=function(){const a=this._atlas;return(a.cursor.x+a.cursor.y*a.size.width)/(a.size.width*a.size.height)};d._getExpectedAtlasUsage=function(){const a=this._elementsToRemove.size,c=this._elementsToAddOrUpdate.size,
b=this._elements.size;return this._getAtlasUsage()/b*(b+c-a)};d._addAtlasElement=function(a,c,b,f){const e=this._atlas,{renderedWidth:g,renderedHeight:k}=a.textRenderer;a.placement.offset.x=e.cursor.x;a.placement.offset.y=e.cursor.y;F.set(a.placement.uvMinMax,a.placement.offset.x/e.size.width,1-(a.placement.offset.y+k)/e.size.height,(a.placement.offset.x+g)/e.size.width,1-a.placement.offset.y/e.size.height);e.cursor.x+=b;e.lineHeight=Math.max(e.lineHeight,f);this._elements.set(c,a)};d._removeAtlasElement=
function(a){if(a&&this._elements.has(a.textId)){const c=a.placement.offset;this._ctx.clearRect(c.x,c.y,a.textRenderer.renderedWidth,a.textRenderer.renderedHeight);this._elements.delete(a.textId)}};d._ensureStageObjects=function(a){var c=this._stageObjects.get(a);if(c)return c;c=new Set;this._stageObjects.set(a,c);return c};d._addStageObject=function(a,c){this._ensureStageObjects(a).add(c)};d._removeStageObject=function(a,c){(a=this._stageObjects.get(a))&&a.delete(c)&&(c.geometries[0].vertexAttributes.get(q.VertexAttribute.SIZE).data=
[0,0],c.geometryVertexAttrsUpdated(c.geometries[0]))};d._processAddition=function(a,c){const b=this._atlas;var f=a.textId;const e=a.textRenderer.renderedWidth+2,g=a.textRenderer.renderedHeight+2+2;if(b.cursor.x+e<b.size.width&&b.cursor.y+g<b.size.height)this._addAtlasElement(a,f,e,g),this._elementsToRender.set(f,a),this._elementsToAddOrUpdate.delete(f);else if(b.cursor.y+g+b.lineHeight<b.size.height)b.cursor.x=2,b.cursor.y+=b.lineHeight,b.lineHeight=0,this._addAtlasElement(a,f,e,g),this._elementsToRender.set(f,
a),this._elementsToAddOrUpdate.delete(f);else{a=this._getExpectedAtlasUsage();(f=.85<a&&4096>b.size.width)&&this._resizeAtlas(2*b.size.width,2*b.size.height);if(!c||!f&&.95<a&&4096===b.size.width)return this._processRemovals(),p.OK;this._repack();return p.REPACK}return p.OK};d._processRemovals=function(){this._elementsToRemove.forEach((a,c)=>{const b=this._stageObjects.get(c);b&&0!==b.size||this._removeAtlasElement(a);b&&0===b.size&&this._stageObjects.delete(c)});this._elementsToRemove.clear()};d._repack=
function(){this._processRemovals();this._elements.forEach((a,c)=>{a.rendered=!1;this._elementsToAddOrUpdate.set(c,a)});this._elements.clear();this._resetAtlasCursor();this._elementsToRender.clear()};d._processRenderingRequest=function(a){this._ctx.clearRect(a.placement.offset.x,a.placement.offset.y,a.textRenderer.renderedWidth,a.textRenderer.renderedHeight);a.textRenderer.render(this._ctx,a.placement.offset.x,a.placement.offset.y);const c=this._stageObjects.get(a.textId);c&&c.forEach(b=>{b.geometries[0].vertexAttributes.get(q.VertexAttribute.UV0).data=
new Float32Array(a.placement.uvMinMax);b.geometries[0].vertexAttributes.get(q.VertexAttribute.SIZE).data=[a.textRenderer.displayWidth,a.textRenderer.displayHeight];b.geometryVertexAttrsUpdated(b.geometries[0])});a.rendered=!0};d.runTask=function(a,c=!0){if(m.isNone(this._glTexture))return u.Task.YIELD;let b=!1;x.someMap(this._elementsToAddOrUpdate,(e,g)=>(e=this._elements.get(g))&&e.rendered?((e=this._stageObjects.get(g))&&e.forEach(k=>{const z=k.geometries[0].vertexAttributes,v=this._elements.get(g);
z.get(q.VertexAttribute.UV0).data=v.placement.uvMinMax;z.get(q.VertexAttribute.SIZE).data=[v.textRenderer.displayWidth,v.textRenderer.displayHeight];k.geometryVertexAttrsUpdated(k.geometries[0])}),this._elementsToAddOrUpdate.delete(g),a.madeProgress(),!1):this._processAddition(this._elementsToAddOrUpdate.get(g),c)===p.REPACK?b=!0:!1);if(b)this.runTask(u.noBudget,!1),a.madeProgress();else{var f=!1;0<this._elementsToRender.size&&this._needsClear&&(this._ctx.clearRect(0,0,this._canvas.width,this._canvas.height),
this._needsClear=!1);x.someMap(this._elementsToRender,(e,g)=>{this._processRenderingRequest(e);this._elementsToRender.delete(g);f=!0;a.madeProgress();return a.done});f&&this._glTexture.setData(this._canvas);this.updating=0<this._elementsToRender.size;!this.updating&&I.textTextureAtlas.orderedRepackingEnabled&&(this.repackOrdered(),a.madeProgress())}};d.addTextTexture=function(a,c){const b=a.key;this._elementsToAddOrUpdate.has(b)||this._elementsToAddOrUpdate.set(b,new L(b,a));this._addStageObject(b,
c);this._elementsToRemove.delete(b);this.setDirty()};d.removeTextTexture=function(a,c){a=a.key;this._elementsToRemove.set(a,this._elements.get(a));this._removeStageObject(a,c)};d.setDirty=function(){this._glTexture&&(this.updating=!0)};d.repackOrdered=function(){if(0!==this._elements.size){var a=[];this._elements.forEach((b,f)=>a.push({element:b,key:f}));var c=!0;for(let b=0;b<a.length-1;b++)if(0<a[b].key.localeCompare(a[b+1].key)){c=!1;break}if(!c||this._elementsToRemove.size){a.sort((b,f)=>b.key.localeCompare(f.key));
this._elements.clear();for(const {element:b,key:f}of a)this._elements.set(f,b);this._repack();this.setDirty()}}};w._createClass(n,[{key:"width",get:function(){return this._atlas.size.width}},{key:"height",get:function(){return this._atlas.size.height}},{key:"requiresFrameUpdates",get:function(){return!1}},{key:"glTexture",get:function(){return this._glTexture}},{key:"running",get:function(){return this.updating}},{key:"test",get:function(){const {_elements:a,_stageObjects:c,_elementsToRemove:b,_atlas:f}=
this,e=this;return{elements:a,stageObjects:c,elementsToRemove:b,atlas:f,resizeAtlas:(g,k)=>e._resizeAtlas(g,k),run:(g,k)=>e.runTask(g,k)}}}]);return n}(A);t.__decorate([y.property({constructOnly:!0})],l.TextTextureAtlas.prototype,"view",void 0);t.__decorate([y.property({type:Boolean})],l.TextTextureAtlas.prototype,"updating",void 0);l.TextTextureAtlas=t.__decorate([E.subclass("esri.views.3d.webgl-engine.lib.TextTextureAtlas")],l.TextTextureAtlas);var p;(function(h){h[h.OK=0]="OK";h[h.REPACK=1]="REPACK"})(p||
(p={}));Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});