// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Evented ../../../../core/Handles ../../../../core/maybe ../../../../core/PooledArray ./ContentObject ./ContentObjectType ./DirtyEvents ./Octree ./UpdatePolicy".split(" "),function(h,l,q,r,e,m,k,n,t,u,p){k=function(f){function g(a,b=""){var c=f.call(this)||this;c.apiLayerUid=b;c.type=n.ContentObjectType.Layer;c.events=new q;c.sliceable=!1;c._objects=new m;c._objectsAdded=new m;c._stageHandles=new r;c.apiLayerUid=b;c.visible=
a?.visible??!0;c.pickable=a?.pickable??!0;c.updatePolicy=a?.updatePolicy??p.UpdatePolicy.ASYNC;c._disableOctree=a?.disableOctree??!1;return c}l._inheritsLoose(g,f);var d=g.prototype;d.destroy=function(){this.detachStage();this._stage=null};d.attachStage=function(a){this.detachStage();this._stage=a;for(const b of t.DirtyEventNames)this._stageHandles.add(this.events.on(b,c=>a.handleEvent(b,c)))};d.detachStage=function(){this._stageHandles.removeAll();this.invalidateSpatialQueryAccelerator()};d.add=
function(a){this._objects.push(a);a.parentLayer=this;this.events.emit("layerObjectAdded",{layer:this,object:a});e.isSome(this._octree)&&this._objectsAdded.push(a)};d.remove=function(a){this._objects.removeUnordered(a)&&(a.parentLayer=null,this.events.emit("layerObjectRemoved",{layer:this,object:a}),e.isSome(this._octree)&&(this._objectsAdded.removeUnordered(a)||this._octree.remove([a])))};d.addMany=function(a){this._objects.pushArray(a);for(const b of a)b.parentLayer=this;this.events.emit("layerObjectsAdded",
{layer:this,objects:a});e.isSome(this._octree)&&this._objectsAdded.pushArray(a)};d.removeMany=function(a){const b=[];this._objects.removeUnorderedMany(a,a.length,b);if(0!==b.length){for(const c of b)c.parentLayer=null;this.events.emit("layerObjectsRemoved",{layer:this,objects:b});if(e.isSome(this._octree)){for(a=0;a<b.length;)this._objectsAdded.removeUnordered(b[a])?(b[a]=b[b.length-1],--b.length):++a;this._octree.remove(b)}}};d.sync=function(){e.isSome(this._stage)&&this.updatePolicy!==p.UpdatePolicy.SYNC&&
this._stage.syncLayer(this.id)};d.notifyObjectBBChanged=function(a,b){e.isSome(this._octree)&&!this._objectsAdded.includes(a)&&this._octree.update(a,b)};d.getSpatialQueryAccelerator=function(){e.isNone(this._octree)&&50<this._objects.length&&!this._disableOctree?(this._octree=new u(a=>a.boundingVolumeWorldSpace.bounds),this._octree.add(this._objects.data,this._objects.length)):e.isSome(this._octree)&&0<this._objectsAdded.length&&(this._octree.add(this._objectsAdded.data,this._objectsAdded.length),
this._objectsAdded.clear());return this._octree};d.shaderTransformationChanged=function(){this.invalidateSpatialQueryAccelerator();this.events.emit("shaderTransformationChanged",this)};d.invalidateSpatialQueryAccelerator=function(){this._octree=e.destroyMaybe(this._octree);this._objectsAdded.clear()};l._createClass(g,[{key:"objects",get:function(){return this._objects}}]);return g}(k.ContentObject);h.WebGLLayer=k;h.isWebGLLayer=function(f){return e.isSome(f)&&f.type===n.ContentObjectType.Layer};Object.defineProperty(h,
Symbol.toStringTag,{value:"Module"})});