// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/Evented ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/reactiveUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../isSupportedGraphicUtils ./isSupportedGraphic ./ReshapeOperation ../../../../interactive/InteractiveToolBase ../../../../interactive/sketch/SketchLabelOptions ../../../../interactive/sketch/SketchTooltipOptions".split(" "),
function(c,l,d,r,t,g,h,e,y,z,u,v,m,w,x,n,p){c.GraphicReshapeTool=function(q){function k(a){a=q.call(this,a)||this;a._handles=new t;a._internalGeometryUpdate=!1;a.enableZShape=!0;a.enableZVertex=!0;a.enableMoveGraphic=!0;a.enableMidpoints=!0;a.enableEdgeOffset=!1;a.type="reshape-3d";a.labelOptions=new n;a.tooltipOptions=new p;a.snappingManager=null;a.automaticManipulatorSelection=!1;return a}l._inheritsLoose(k,q);var f=k.prototype;f.initialize=function(){const a=this._reshapeOperation=new w.ReshapeOperation({tool:this});
this.addHandles([a.on("reshape",b=>{"reshape"===b.type&&this._onReshapeGeometryChanged();this.emit("reshape",b)}),a.on("move",b=>{"move"===b.type&&this._onReshapeGeometryChanged();this.emit("move",b)}),a.on("vertex-add",b=>{this._onReshapeGeometryChanged();this.emit("vertex-add",b)}),a.on("vertex-remove",b=>{this._onReshapeGeometryChanged();this.emit("vertex-remove",b)}),a.on("immediate-click",b=>this.emit("immediate-click",b)),this.view.on("pointer-down",["Shift"],b=>b.stopPropagation()),h.watch(()=>
this.graphic,()=>this._updateGraphic(),h.syncAndInitial)]);this.finishToolCreation()};f.destroy=function(){this._handles=g.destroyMaybe(this._handles);this._reshapeOperation=g.destroyMaybe(this._reshapeOperation)};f._updateGeometry=function(){const a=m.geometryOfSupportedGraphic(this.graphic);this._reshapeOperation.inputGeometry=g.isSome(a)?a.clone():null};f._updateGraphic=function(){this._handles.remove("onGraphicGeometryChange");this._updateGeometry();if(m.isSupportedGraphic(this.graphic)===v.SupportedGraphicResult.SUPPORTED){var a=
h.watch(()=>this.graphic?.geometry,()=>{!1===this._internalGeometryUpdate&&this._updateGeometry()},h.sync);this._handles.add(a,"onGraphicGeometryChange")}};f.onManipulatorSelectionChanged=function(){if(this._reshapeOperation)this._reshapeOperation.onManipulatorSelectionChanged()};f._updateGeometryInternally=function(a){this._internalGeometryUpdate=!0;this.graphic.geometry=a;this._internalGeometryUpdate=!1};f._onReshapeGeometryChanged=function(){const {outputGeometry:a}=this._reshapeOperation;!g.isNone(this.graphic)&&
a&&this._updateGeometryInternally(a.clone())};f.undo=function(){g.isSome(this.snappingManager)&&this.snappingManager.doneSnapping();const a=this._reshapeOperation.undo(),{outputGeometry:b}=this._reshapeOperation;a&&b&&this._updateGeometryInternally(b.clone())};f.redo=function(){g.isSome(this.snappingManager)&&this.snappingManager.doneSnapping();const a=this._reshapeOperation.redo(),{outputGeometry:b}=this._reshapeOperation;a&&b&&this._updateGeometryInternally(b.clone())};f.onInputEvent=function(a){"key-down"!==
a.type||"Delete"!==a.key&&"Backspace"!==a.key||this._reshapeOperation.removeSelectedVertices()};f.reset=function(){};l._createClass(k,[{key:"updating",get:function(){return this._reshapeOperation?.updating??!1}},{key:"canUndo",get:function(){return this._reshapeOperation.canUndo??!1}},{key:"canRedo",get:function(){return this._reshapeOperation.canRedo??!1}},{key:"test",get:function(){return{snappingManager:this.snappingManager,reshapeOperation:this._reshapeOperation}}}]);return k}(r.EventedMixin(x.InteractiveToolBase));
d.__decorate([e.property()],c.GraphicReshapeTool.prototype,"_reshapeOperation",void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"view",void 0);d.__decorate([e.property({constructOnly:!0})],c.GraphicReshapeTool.prototype,"graphic",void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"enableZShape",void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"enableZVertex",
void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"enableMoveGraphic",void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"enableMidpoints",void 0);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.GraphicReshapeTool.prototype,"enableEdgeOffset",void 0);d.__decorate([e.property()],c.GraphicReshapeTool.prototype,"type",void 0);d.__decorate([e.property({constructOnly:!0,type:n})],c.GraphicReshapeTool.prototype,
"labelOptions",void 0);d.__decorate([e.property({constructOnly:!0,type:p})],c.GraphicReshapeTool.prototype,"tooltipOptions",void 0);d.__decorate([e.property({constructOnly:!0})],c.GraphicReshapeTool.prototype,"snappingManager",void 0);d.__decorate([e.property()],c.GraphicReshapeTool.prototype,"updating",null);d.__decorate([e.property()],c.GraphicReshapeTool.prototype,"automaticManipulatorSelection",void 0);c.GraphicReshapeTool=d.__decorate([u.subclass("esri.views.3d.interactive.editingTools.graphicReshape3D.GraphicReshapeTool")],
c.GraphicReshapeTool);Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});