// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Graphic ../../intl ../../core/Evented ../../core/HandleOwner ../../core/Logger ../../core/maybe ../../core/Promise ../../core/reactiveUtils ../../core/string ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../form/FormTemplate ../../layers/support/ContingentValue ../../layers/support/editableLayers ../../layers/support/LayerContingentValuesCache ./featureFormUtils ./FormExpressionArcadeExecutor ./FormExpressionsManager ./InputField ./InputFieldGroup ../../intl/locale ../../intl/messages".split(" "),
function(z,q,n,Y,I,J,A,p,K,B,E,t,Z,aa,L,M,F,N,O,w,P,Q,G,R,S,T){const C=new n({attributes:{}}),U=["editableExpression","requiredExpression","valueExpression","visibilityExpression"],V=["visibilityExpression"];n=function(y){function v(a){a=y.call(this,a)||this;a._expressionExecutorLookup=new Map;a._expressionLookup=new Map;a._expressionsManager=null;a._contingentValuesCache=null;a._featureClone=C.clone();a._initialFeature=C.clone();a.arcadeEditType="NA";a.contingencyConstraintViolations=new Map;a.inputFields=
[];a.messages=null;a.strict=!1;a._isSupportedElement=a._isSupportedElement.bind(z._assertThisInitialized(a));return a}z._inheritsLoose(v,y);var m=v.prototype;m.initialize=function(){var a=this;const b=function(){var e=z._asyncToGenerator(function*(){const g=yield T.fetchMessageBundle("esri/widgets/FeatureForm/t9n/FeatureForm");a.messages=g;for(const h of a.allInputFields)h.messages=g});return function(){return e.apply(this,arguments)}}();b();const d=B.watch(()=>[this.layer,this.layer?.loaded,this.formTemplate],
([e,g])=>{p.isSome(e)&&(g?this._updateInputFields():e.load().catch(()=>A.getLogger(this.declaredClass).error("Failed to load layer",e.loadError)))},{equals:([e,g,h],[k,l,r])=>e===k&&g===l&&h===r,initial:!0}),c=B.watch(()=>this._arcadeContextInfo,e=>{p.isSome(this._expressionsManager)&&(this._expressionsManager.arcadeContextInfo=e)}),f=B.watch(()=>this.layer,e=>{(e="subtype-sublayer"===e?.type?e.parent:"feature"===e?.type?e:null)&&this.addResolvingPromise(O.createLoadedLayerContingentValuesCache(e).then(g=>
{this._contingentValuesCache=g;this.notifyChange("fieldsWithContingentValues")}))},{initial:!0});this.handles.add([S.onLocaleChange(b),d,c,f])};m.destroy=function(){this.layer=this.feature=null;this._contingentValuesCache=p.destroyMaybe(this._contingentValuesCache)};m.findField=function(a){return this.allInputFields.find(b=>b.name===a)};m.getValue=function(a){const {_featureClone:b,layer:d}=this,c=!!d?.getField(a);return b.getAttribute(a)??(c?null:void 0)};m.setValue=function(a,b){const {_featureClone:d,
strict:c}=this,f=this.findField(a);b=""===b?null:b;f&&d.getAttribute(a)!==b&&(f.value=b,!c||f.valid)&&(this._afterValueChange(f),p.isSome(this._expressionsManager)&&this.updatingHandles.addPromise(this._expressionsManager.evaluateInvalidated([f.name]).finally(()=>this._afterExpressionsEvaluated())))};m.getValues=function(){return{...this._featureClone.attributes}};m.submit=function(){var a=this.allInputFields;const b=new Set(a.filter(c=>c.valid).map(({name:c})=>c));a=a.filter(c=>!c.valid).map(({name:c})=>
c);const d=this.getValues();if(0<this.validateContingencyConstraints(d,{includeIncompleteViolations:!0}).length)for(const [c,f]of this.contingencyConstraintViolations.entries())"error"===f.type&&(b.delete(c),a.push(c));this.emit("submit",{valid:[...b],invalid:a,values:d})};m.validateContingencyConstraints=function(a,b){const {_contingentValuesCache:d}=this,c=new Map;this.contingencyConstraintViolations=c;if(p.isNone(d))return[];const {invalid:f,incomplete:e}=d.validateContingencyConstraints(a);a=
[...f,...(b?.includeIncompleteViolations?e:[])];for(const g of a)for(const h of g.fieldGroup.fields)c.set(h,g);return a};m.notifyFeatureGeometryChanged=function(){const {_expressionsManager:a,feature:b,_featureClone:d}=this;d.geometry=b.geometry;p.isSome(a)&&this.updatingHandles.addPromise(a.evaluateInvalidatedByGeometry().finally(()=>this._afterExpressionsEvaluated()))};m._emitChangeEvent=function({name:a,valid:b,value:d}){this.emit("value-change",{layer:this.layer,feature:this.feature,fieldName:a,
value:d,valid:b})};m._updateInputFields=function(){const {_featureClone:a,_initialFeature:b,arcadeEditType:d,formTemplate:c,inputFields:f,messages:e,layer:g}=this,h={arcadeEditType:d,feature:a,initialFeature:b,layer:g,messages:e},k=f.slice();this.inputFields=p.isSome(c)&&0<c.elements.length?this._updateInputFieldsFromElements(k,c.elements,h):this._updateInputFieldsFromLayerFields(k,g?.fields,h)};m._updateInputFieldsFromElements=function(a,b,d){const c=new Map;for(const e of a)if(w.isGroupField(e)){D(c,
e.groupElement,e);for(const g of e.inputFields)D(c,g.fieldElement,g)}else D(c,e.fieldElement,e);a=new Map;const f=this._updateInputFieldsRecursive({existingInputFieldsByElement:c,updatedElements:b.filter(this._isSupportedElement),sharedInitializationProperties:d,group:null,newExpressionExecutorPromises:a});this.updatingHandles.addPromise(Promise.all(Array.from(a.values())).then(()=>{const e=Array.from(this._expressionExecutorLookup.values()),g=H(f);this._createExpressionsManager(e,g);return p.unwrap(this._expressionsManager).evaluateAll().finally(()=>
this._afterExpressionsEvaluated())}));for(const [e,g]of c.entries())c.delete(e),g.destroy();return f};m._updateInputFieldsRecursive=function(a){const {existingInputFieldsByElement:b,updatedElements:d,sharedInitializationProperties:c,group:f,newExpressionExecutorPromises:e}=a;a=[];for(const h of d){var g=b.has(h);const k=g?b.get(h):"group"===h.type?this._makeInputFieldGroupFromGroupElement(h,c):this._makeInputFieldFromFieldElement(h,c,f);a.push(k);g?(b.delete(h),w.isGroupField(k)?({feature:g}=c,k.set({feature:g})):
k.set(c)):this._assignExpressionExecutors(k,h,e);"group"===h.type&&(g=h.elements.filter(l=>this._isSupportedElement(l)),k.inputFields=this._updateInputFieldsRecursive({existingInputFieldsByElement:b,updatedElements:g,sharedInitializationProperties:c,group:k,newExpressionExecutorPromises:e}))}return a};m._updateInputFieldsFromLayerFields=function(a,b,d){if(!Array.isArray(b))return A.getLogger(this.declaredClass).warn(this.declaredClass,"No attribute fields found."),[];const c=new Map;for(const l of a)if(w.isGroupField(l)){for(const r of l.inputFields)r.destroy();
l.inputFields.length=0;l.destroy()}else p.isSome(l.fieldElement)?l.destroy():c.set(l.field,l);a=[];const {arcadeEditType:f,feature:e,initialFeature:g,layer:h,messages:k}=d;for(const l of b)b=c.get(l)??new G({arcadeEditType:f,field:l,feature:e,initialFeature:g,layer:h,messages:k,value:e.getAttribute(l.name)??null}),a.push(b),c.delete(l);for(const [l,r]of c.entries())c.delete(l),r.destroy();return a};m._resetInputFieldValues=function(a){for(const b of this.allInputFields)b.value=a.getAttribute(b.name)};
m._makeInputFieldFromFieldElement=function(a,b,d=null){const {arcadeEditType:c,feature:f,initialFeature:e,layer:g,messages:h}=b;return new G({arcadeEditType:c,fieldElement:a,field:this._layerFieldsByName.get(a.fieldName),value:f.getAttribute(a.fieldName)??null,feature:f,initialFeature:e,layer:g,group:d,messages:h})};m._makeInputFieldGroupFromGroupElement=function(a,b){const {feature:d,initialFeature:c}=b;return new R({groupElement:a,inputFields:[],feature:d,initialFeature:c})};m._assignExpressionExecutors=
function(a,b,d){var c="group"===b.type?V:U;for(const f of c){c=b[f];const {_expressionExecutorLookup:e}=this;if(p.isSome(c)&&""!==c){const g=`${f}Executor`,h=this._expressionLookup.get(c)??this._addToExpressionLookup(c);e.has(h)?a[g]=e.get(h):d.has(h)?(c=d.get(h).then(k=>a[g]=k),d.set(h,c)):(c=P.createFormExpressionArcadeExecutor(h,this.layer).then(k=>{a[g]=k;e.set(h,k);return k}),d.set(h,c))}}return[]};m._createExpressionsManager=function(a,b){const {_arcadeContextInfo:d,_featureClone:c}=this;this._expressionsManager=
new Q.FormExpressionsManager({executors:a,feature:c,arcadeContextInfo:d,inputFields:b})};m._afterValueChange=function(a){const {name:b,value:d}=a,{_featureClone:c,formTemplate:f,layer:e}=this;if(e){var g=c.getAttribute(b);c.setAttribute(b,d);var {typeFieldName:h,types:k}=w.getNormalizedFeatureTypeInfo(e);if(b===h&&d!==g){"subtype-sublayer"===e.type&&(g=e.parent?.findSublayerForFeature(c),c.sourceLayer=this.feature.sourceLayer=g);g=new Set;for(var l of k)if(l.domains&&"object"===typeof l.domains)for(const r of Object.keys(l.domains))g.add(r);
for(const r of g)(l=this.findField(r))&&l.notifyChange("domain")}if(p.isSome(f)){const {description:r,title:u}=f;u&&E.templateHasKey(u,b)&&this.notifyChange("formTitle");r&&E.templateHasKey(r,b)&&this.notifyChange("formDescription")}this._emitChangeEvent(a)}};m._afterExpressionsEvaluated=function(){const {_featureClone:a}=this;for(const b of this.allInputFields)b.value!==a.getAttribute(b.name)&&this._afterValueChange(b)};m._addToExpressionLookup=function(a){const {_expressionLookup:b,formTemplate:d}=
this,c=(p.isSome(d)&&p.isSome(d.expressionInfos)?Object.values(d.expressionInfos).find(f=>f.name===a):null)?.expression??a;b.set(a,c);a!==c&&b.set(c,c);return c};m._isSupportedElement=function(a){if("field"===a.type||"group"===a.type)return!0;A.getLogger(this.declaredClass).warn("form-info::unsupported-element-type","Only element types 'field' and 'group' are supported",`Element ${a.label} has unsupported type '${a.type}'`);return!1};m._joinContingentValues=function(){var a=this._contingentValuesCache;
if(p.isNone(a))return[];var {typeFieldName:b}=w.getNormalizedFeatureTypeInfo(this.layer);b=b?this.getValue(b):null;const d=[];for(var c of a.fieldGroups){const {contingencies:h,fields:k,name:l}=c;a=[];for(var f of h)f.isRetired||p.isSome(f.subtype)&&f.subtype.code!==b||a.push({values:f.values});0<a.length&&d.push({name:l,fields:k,contingencies:a})}const [e,g]=this._generateJoinPlan(d);c=e.flatMap(h=>this._joinFieldGroupContingencies(h));f=g.flatMap(h=>h.contingencies);return[...c,...f]};m._generateJoinPlan=
function(a){var b=new Map,d=[],c=new Set;for(var f of a)for(const k of f.fields)if(b.has(k)){const l=b.get(k),r=f,u=[l.name,r.name].sort().join("|");c.has(u)||(d.push([l,r]),c.add(u),b.set(k,r))}else b.set(k,f);b=new Set(d.flat());a=new Set(a);for(var e of b)a.delete(e);e=new Map;b=new Map;for(var g of new Set(d.flat()))c=Symbol(g.name),e.set(c,new Set([g])),b.set(g,c);for(const [k,l]of d)if(d=b.get(k),g=b.get(l),d!==g){c=e.get(d);f=e.get(g);for(var h of f)c.add(h),b.set(h,d);e.delete(g)}h=[...e.values()].map(k=>
[...k]);d=[...a];return[h,d]};m._joinFieldGroupContingencies=function(a){const b=a.slice();var d=b.shift(),c=b.shift();a=this._generateJoinKey(d.fields,c.fields);let f=new Set([...d.fields,...c.fields]),e=new Map;for(var g of d.contingencies)[d]=this._hashContingency(g,a.codedValueFields,!0),e.has(d)?e.get(d).push(g):e.set(d,[g]);for(;0<b.length;){g=new Map;d=b.shift();const l=this._generateJoinKey(f,d.fields);for(var h of c.contingencies){const [r,u]=this._hashContingency(h,a.codedValueFields);c=
u?this._findMatchingContingenciesWithAnyHashMask(e,r):e.get(r);e.has("#JSAPI_CONTINGENT_VALUE_ANY_HASH")&&c.push(...this._findMatchingContingenciesContainingAny(h,e.get("#JSAPI_CONTINGENT_VALUE_ANY_HASH"),a.codedValueFields));if(!p.isNone(c))for(var k of c){c=0<a.rangeFields.length?this._joinContingenciesWithRangeDomains(k,h,a.rangeFields):this._joinContingencies(k,h);if(p.isNone(c))break;const [x]=this._hashContingency(c,l.codedValueFields,!0);g.has(x)?g.get(x).push(c):g.set(x,[c])}}e=g;c=d;a=l;
f=new Set([...f,...c.fields])}h=[];for(const l of c.contingencies){const [r,u]=this._hashContingency(l,a.codedValueFields);k=u?this._findMatchingContingenciesWithAnyHashMask(e,r):e.get(r);e.has("#JSAPI_CONTINGENT_VALUE_ANY_HASH")&&k.push(...this._findMatchingContingenciesContainingAny(l,e.get("#JSAPI_CONTINGENT_VALUE_ANY_HASH"),a.codedValueFields));if(!p.isNone(k))for(const x of k)k=0<a.rangeFields.length?this._joinContingenciesWithRangeDomains(x,l,a.rangeFields):this._joinContingencies(x,l),p.isSome(k)&&
h.push(k)}return h};m._joinContingencies=function(a,b){b={values:{...a.values,...b.values}};for(const [d,c]of Object.entries(b.values))"any"===c.objectType&&p.isSome(a.values[d])&&(b.values[d]=a.values[d]);return b};m._joinContingenciesWithRangeDomains=function(a,b,d){const c=this._joinContingencies(a,b);for(const e of d){var f=a.values[e];const g=b.values[e],{leftIsNull:h,rightIsNull:k,bothAreNull:l,leftIsAny:r,rightIsAny:u,bothAreAny:x,leftIsRange:W,rightIsRange:X}=this._compareObjectTypes(f.objectType,
g.objectType);if(!l&&!x)if(h&&u||k&&r)c.values[e]=new F({objectType:"null"});else{if(h&&X||k&&W)return null;r?(f.minValue=-Infinity,f.maxValue=Infinity):u&&(g.minValue=-Infinity,g.maxValue=Infinity);d=Math.max(f.minValue,g.minValue);f=Math.min(f.maxValue,g.maxValue);if(d>f)return null;c.values[e]=new F({objectType:"range",minValue:d,maxValue:f})}}return c};m._findMatchingContingenciesContainingAny=function(a,b,d){return b.filter(c=>d.every(f=>{const e=c.values[f];f=a.values[f];return"any"===e.objectType||
"any"===f.objectType||e.codedValue?.code===f.codedValue?.code}))};m._findMatchingContingenciesWithAnyHashMask=function(a,b){b=RegExp(`${b}$`);const d=[];for(const [c,f]of a){if("#JSAPI_CONTINGENT_VALUE_ANY_HASH"===c)break;b.test(c)&&d.push(...f)}return d};m._generateJoinKey=function(a,b){a=Array.isArray(a)?new Set(a):a;var d=Array.isArray(b)?new Set(b):b;b=a.size<d.size?a:d;a=b===a?d:a;d=new Set;const c=new Set;for(const f of b)if(a.has(f)&&(b=this.layer.getFieldDomain(f,{feature:this.feature}),!p.isNone(b)))switch(b.type){case "coded-value":d.add(f);
break;case "range":c.add(f)}return{codedValueFields:[...d],rangeFields:[...c]}};m._hashContingency=function(a,b,d=!1){if(1>b.length)return["#JSAPI_CONTINGENT_VALUE_EMPTY_HASH",!1];const c=[];let f=!1;for(const e of b)if(b=a.values[e],"any"===b.objectType){if(d)return["#JSAPI_CONTINGENT_VALUE_ANY_HASH",!0];f=!0;c.push(`${e}:.*`)}else"null"===b.objectType?c.push(`${e}:${"#JSAPI_CONTINGENT_VALUE_NULL_HASH"}`):c.push(`${e}:${b.codedValue?.code}`);return[c.sort().join("\x26"),f]};m._compareObjectTypes=
function(a,b){return{leftIsNull:"null"===a,rightIsNull:"null"===b,bothAreNull:"null"===a&&"null"===b,leftIsAny:"any"===a,rightIsAny:"any"===b,bothAreAny:"any"===a&&"any"===b,leftIsRange:"range"===a,rightIsRange:"range"===b}};z._createClass(v,[{key:"_arcadeContextInfo",get:function(){const {_initialFeature:a,arcadeEditType:b,layer:d,spatialReference:c,view:f}=this;return{layer:N.isEditableLayer(d)?d:null,originalFeature:a,editType:b,spatialReference:c,map:f?.map}}},{key:"updating",get:function(){return this.updatingHandles.updating}},
{key:"allInputFields",get:function(){return H(this.inputFields)}},{key:"_layerFieldsByName",get:function(){return new Map(this.layer.fields.map(a=>[a.name,a]))}},{key:"feature",get:function(){return this._get("feature")},set:function(a){this._featureClone=a?a.clone():C.clone();this._initialFeature=this._featureClone.clone();this._resetInputFieldValues(this._featureClone);this.contingencyConstraintViolations.clear();p.isSome(this._expressionsManager)&&(this._expressionsManager.resetExecutors(),this._expressionsManager.feature=
this._featureClone,this.updatingHandles.addPromise(this._expressionsManager.evaluateAll().finally(()=>this._afterExpressionsEvaluated())));this._set("feature",a)}},{key:"fieldsWithContingentValues",get:function(){if(p.isNone(this._contingentValuesCache))return new Set;const a=this._contingentValuesCache.fieldGroups.flatMap(b=>b.fields);return new Set(a)}},{key:"formTemplate",get:function(){return this.layer&&"formTemplate"in this.layer?this.layer.formTemplate:null},set:function(a){void 0===a?this._clearOverride("formTemplate"):
this._override("formTemplate",a)}},{key:"formDescription",get:function(){const {formTemplate:a,layer:b}=this;return!p.isNone(a)&&a.description&&b?w.parseFormTemplateString(a.description,this.getValues(),b.fieldsIndex):null}},{key:"formTitle",get:function(){const {formTemplate:a,layer:b}=this;return!p.isNone(a)&&a.title&&b?w.parseFormTemplateString(a.title,this.getValues(),b.fieldsIndex):null}},{key:"joinedContingentValues",get:function(){return this._joinContingentValues()}},{key:"layer",get:function(){return this.feature?.sourceLayer&&
"applyEdits"in this.feature.sourceLayer?this.feature.sourceLayer:null},set:function(a){this._override("layer",a)}},{key:"spatialReference",get:function(){return this.layer?.spatialReference??null},set:function(a){this._override("spatialReference",a)}},{key:"state",get:function(){return this.messages&&this.get("layer.loaded")?"ready":"disabled"}},{key:"submittable",get:function(){return this.valid?!0:this.allInputFields.filter(a=>!a.valid).every(({submittable:a})=>a)}},{key:"valid",get:function(){const a=
this.allInputFields;return 0<a.length&&a.every(({valid:b})=>b)}}]);return v}(J.HandleOwnerMixin(K.EsriPromiseMixin(I.EventedAccessor)));q.__decorate([t.property()],n.prototype,"_featureClone",void 0);q.__decorate([t.property()],n.prototype,"_arcadeContextInfo",null);q.__decorate([t.property()],n.prototype,"updating",null);q.__decorate([t.property({readOnly:!0})],n.prototype,"allInputFields",null);q.__decorate([t.property()],n.prototype,"_layerFieldsByName",null);q.__decorate([t.property()],n.prototype,
"arcadeEditType",void 0);q.__decorate([t.property()],n.prototype,"contingencyConstraintViolations",void 0);q.__decorate([t.property()],n.prototype,"feature",null);q.__decorate([t.property()],n.prototype,"fieldsWithContingentValues",null);q.__decorate([t.property({type:M})],n.prototype,"formTemplate",null);q.__decorate([t.property()],n.prototype,"formDescription",null);q.__decorate([t.property()],n.prototype,"formTitle",null);q.__decorate([t.property()],n.prototype,"inputFields",void 0);q.__decorate([t.property()],
n.prototype,"joinedContingentValues",null);q.__decorate([t.property()],n.prototype,"layer",null);q.__decorate([t.property()],n.prototype,"messages",void 0);q.__decorate([t.property()],n.prototype,"spatialReference",null);q.__decorate([t.property()],n.prototype,"state",null);q.__decorate([t.property()],n.prototype,"strict",void 0);q.__decorate([t.property()],n.prototype,"submittable",null);q.__decorate([t.property()],n.prototype,"valid",null);q.__decorate([t.property()],n.prototype,"view",void 0);
q.__decorate([t.property()],n.prototype,"getValues",null);q.__decorate([t.property()],n.prototype,"submit",null);n=q.__decorate([L.subclass("esri.widgets.FeatureForm.FeatureFormViewModel")],n);const H=y=>y.reduce((v,m)=>w.isGroupField(m)?[...v,...m.inputFields]:[...v,m],[]),D=(y,v,m)=>{p.isSome(v)&&y.set(v,m)};return n});