// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Accessor ../../core/MapUtils ../../core/maybe ../../core/promiseUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass".split(" "),function(l,u,q,B,w,x,y,v,E,F,C){l.FormExpressionsManager=function(e){function m(b){var a=e.call(this,b)||this;a._fieldReferencesLookup=new Map;a._fieldsAffectedLookup=new Map;a._latestFieldValues=
{...b.feature.attributes};return a}u._inheritsLoose(m,e);var f=m.prototype;f.initialize=function(){this._dependencyGraph=this._buildDependencyGraph()};f.evaluateAll=function(){return this._evaluate(this.executors)};f.evaluateExpressions=function(b){return this._evaluate(b)};f.evaluateInvalidated=function(b){const {_fieldReferencesLookup:a,_latestFieldValues:h,feature:g}=this,k=new Set;for(const c of b)if(h[c]=g.getAttribute(c),a.has(c))for(const r of a.get(c))k.add(r);return this._evaluate([...k])};
f.evaluateInvalidatedByGeometry=function(){var b=u._asyncToGenerator(function*(){if(this._fieldReferencesLookup.has("#JSAPI_FORM_EXPRESSIONS_MANAGER_GEOMETRY"))return this._evaluate([...this._fieldReferencesLookup.get("#JSAPI_FORM_EXPRESSIONS_MANAGER_GEOMETRY")])});return function(){return b.apply(this,arguments)}}();f.resetExecutors=function(){for(const b of this.executors)b.reset()};f._buildDependencyGraph=function(){const {_fieldReferencesLookup:b,_fieldsAffectedLookup:a,executors:h}=this,g=new Map(this.inputFields.map(c=>
[c.name,c])),k=new Map(h.map(c=>[c,[]]));for(const c of h){for(const r of c.fieldsUsed){w.getOrCreateMapValue(b,r,()=>new Set).add(c);const d=g.get(r),{valueExpressionExecutor:p,editableExpressionExecutor:t}=d;x.isSome(p)&&p!==c&&(k.get(p).push(c),w.getOrCreateMapValue(a,p,()=>new Set).add(d));x.isSome(t)&&t!==c&&(k.get(t).push(c),w.getOrCreateMapValue(a,t,()=>new Set).add(d))}c.geometryUsed&&w.getOrCreateMapValue(b,"#JSAPI_FORM_EXPRESSIONS_MANAGER_GEOMETRY",()=>new Set).add(c)}return k};f._evaluate=
function(){var b=u._asyncToGenerator(function*(a){var h=this;const g=new Map,{_dependencyGraph:k,_fieldsAffectedLookup:c,_latestFieldValues:r}=this;for(const d of a)z(d,g,k);for(const [d,{resolver:p,dependencyPromises:t}]of g)Promise.all(t).then(u._asyncToGenerator(function*(){const [n,D]=h._makeContext(r);return d.executeAsync(n,D)})).then(()=>{if(c.has(d))for(const n of c.get(d))this._latestFieldValues[n.name]=n.value;p.resolve()},n=>{!n||y.isAbortError(n)||A(n)||d.markStale();p.reject(n)});a=(yield Promise.allSettled(Array.from(g.values(),
({resolver:d})=>d.promise))).filter(d=>"rejected"===d.status&&!(y.isAbortError(d.reason)||A(d.reason)));if(0<a.length)throw new AggregateError(a,"One or more expression executions failed");});return function(a){return b.apply(this,arguments)}}();f._makeContext=function(b){const [a,h]=this._baseContext,g=this.feature.clone();g.attributes=b;return[{...a,$feature:g},h]};u._createClass(m,[{key:"_baseContext",get:function(){const {editType:b,layer:a,map:h,originalFeature:g,spatialReference:k}=this.arcadeContextInfo,
c="feature"===a?.type?a:"scene"===a?.type&&x.isSome(a.associatedLayer)?a.associatedLayer:void 0;return[{$originalfeature:g,$editcontext:{editType:b},$layer:c,$featureset:c,$datastore:a?.url,$map:h},{spatialReference:k}]}},{key:"feature",set:function(b){this._latestFieldValues={...b?.attributes};this._set("feature",b)}}]);return m}(B);q.__decorate([v.property()],l.FormExpressionsManager.prototype,"_baseContext",null);q.__decorate([v.property()],l.FormExpressionsManager.prototype,"feature",null);q.__decorate([v.property()],
l.FormExpressionsManager.prototype,"executors",void 0);q.__decorate([v.property()],l.FormExpressionsManager.prototype,"inputFields",void 0);q.__decorate([v.property()],l.FormExpressionsManager.prototype,"arcadeContextInfo",void 0);l.FormExpressionsManager=q.__decorate([C.subclass("esri.widgets.FeatureForm.FormExpressionsManager")],l.FormExpressionsManager);const z=(e,m,f)=>{if(!m.has(e)){var b=y.createResolver();m.set(e,{resolver:b,dependencyPromises:[]});e.abort();e=f.get(e);for(const a of e)z(a,
m,f),m.get(a).dependencyPromises.push(b.promise)}},A=e=>e&&"object"===typeof e&&"message"in e&&"Cancelled"===e.message;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});