// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Evented ../../../../core/has ../../../../core/Logger ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/scheduling ../../../../core/time ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../collections/Component/ComponentObjectCollection ../core/shaderTechnique/ShaderTechniqueRepository ../lib/basicInterfaces ../lib/CompositingHelper ../lib/depthRangeUtils ../lib/GLMaterialRepository ../lib/MagnifierHelper ../lib/Material ../lib/ObjectAndLayerIdRenderHelper ../lib/Renderer ../lib/RenderingContext ../lib/TextureRepository ../materials/StippleTextureRepository ../materials/internal/WaterTextureRepository ./contextCache ./requireUtils ./ScreenshotManager ./testUtils ../../../support/RenderState ../../../webgl/context-util".split(" "),
function(f,t,g,E,F,u,w,n,x,G,y,k,Y,Z,H,I,J,p,K,L,M,N,O,P,Q,z,R,S,T,U,V,A,W,B,X){f.RenderView=function(C){function q(b){var a=C.call(this,{})||this;a.events=new F;a.waterTextureRepository=new T.WaterTextureRepository;a._magnifierHelper=new N.MagnifierHelper;a.objectAndLayerIdRenderHelper=u("enable-feature:objectAndLayerId-rendering")?new P.ObjectAndLayerIdRenderHelper:null;a._needsUpdate=!0;a._needsRender=!0;a._idleSuspend=!0;a._needsWaterReflectionUpdate=!1;a._lastAnimationUpdate=0;a._container=b.container;
a._viewingMode=b.viewingMode;a._initializeContext(b);x.watch(()=>a.waterTextureRepository?.updating,()=>a.requestRender(),x.initial);a._magnifierHelper.events.on("request-render",()=>a.requestRender());a._stippleTextureRepository=new S.StippleTextureRepository(a._rctx);a._shaderTechniqueRepository=new J.ShaderTechniqueRepository({rctx:a._rctx,viewingMode:b.viewingMode,stippleTextureRepository:a._stippleTextureRepository,waterTextureRepository:a.waterTextureRepository});a._textureRepository=new R.TextureRepository(b,
a._shaderTechniqueRepository,a._rctx);a._textureRepository.events.on("changed",d=>a.requestRender(d));a._materialRepository=new M.GLMaterialRepository(a._textureRepository,a._shaderTechniqueRepository,()=>a.requestRender(),()=>a.requestRender());a._compositingHelper=new K(a._rctx,a._shaderTechniqueRepository);a.renderer=new Q.Renderer(b,a._materialRepository,a._textureRepository,a._shaderTechniqueRepository,a._rctx,a._compositingHelper,a._magnifierHelper,d=>a.requestRender(d));a._screenshotManager=
new A.ScreenshotManager(a._rctx,{renderScene:(d,e,c,h,l)=>a.renderer.render(d,e,{camera:c,contentCamera:c,mode:B.RenderState.IDLE},h,l),requestRenderScene:d=>a.requestRender(d),prepareOverlay:()=>b.options.screenshot.prepareOverlay(),renderOverlay:(d,e)=>b.options.screenshot.renderOverlay(d,e)},d=>a.events.emit("force-camera-for-screenshot",d),()=>a.renderer.disposeOffscreenBuffers());a._registerFrameTask(b);return a}t._inheritsLoose(q,C);var m=q.prototype;m.normalizeCtorArgs=function(){return{}};
m.destroy=function(){this._container.contains(this._canvas)&&this._container.removeChild(this._canvas);this._frameTask=n.removeMaybe(this._frameTask);this._shaderTechniqueRepository=n.destroyMaybe(this._shaderTechniqueRepository)};m.requestRender=function(b=p.RenderRequestType.UPDATE){this._needsRender=!0;b===p.RenderRequestType.UPDATE&&(this._needsUpdate=!0)};m.setIdleSuspend=function(b){this._idleSuspend!==b&&(this._idleSuspend=b,this.requestRender())};m.takeScreenshot=function(b){return this._screenshotManager.takeScreenshot(b).then(a=>
a[0])};m.takeScreenshotWithOID=function(b){b.objectAndLayerIdColor=!0;return this._screenshotManager.takeScreenshot(b)};m.getAlpha=function(){return!!this._rctx.contextAttributes.alpha};m.getMinimalDepthForArea=function(b,a,d,e,c,h=c){h=e.constrainWindowSize(a,d,c*e.pixelRatio,h*e.pixelRatio);const l=this._ensureDepthBuffer(h);this.renderer.readDepthPixels(e,h,l);c=Number.MAX_VALUE;for(let v=0;v<h[2]*h[3];v++){const r=L.textureToDepth(4*v,l,e.nearFar);c>r&&r!==e.nearFar[0]&&r!==e.nearFar[1]&&(c=r)}n.isSome(b)&&
(b=b.pickDepth(a*e.pixelRatio,d*e.pixelRatio,e),n.isSome(b)&&c>b&&b!==e.nearFar[0]&&b!==e.nearFar[1]&&(c=b));return c===Number.MAX_VALUE?void 0:c};m._ensureDepthBuffer=function(b){b=4*b[2]*b[3];if(n.isNone(this._tmpDepthBuffer)||this._tmpDepthBuffer.byteLength<b)this._tmpDepthBuffer=new Uint8Array(b);return this._tmpDepthBuffer};m.reloadShaders=function(){var b=t._asyncToGenerator(function*(){V.removeLoadedShaderModules();yield this._shaderTechniqueRepository.reloadAll();this.requestRender()});return function(){return b.apply(this,
arguments)}}();m._registerFrameTask=function(b){const a=b.view.state;let d=!1,e=p.RenderRequestType.BACKGROUND,c=!1;this._frameTask=G.addFrameTask({preRender:({time:h})=>{d=this.updating;e=this._needsUpdate?p.RenderRequestType.UPDATE:p.RenderRequestType.BACKGROUND;b.commitSyncLayers();var l=y.Milliseconds(h-this._lastAnimationUpdate);if(l>this.renderer.animationTimestep||n.isSome(a.forcedAnimationTime)||d||this._needsRender)l=y.Milliseconds(l/this.renderer.animationTimeDilation),l=new O.UpdateParameters(a.camera,
l,a.forcedAnimationTime),this.renderer.updateAnimation(l)&&this.requestRender(p.RenderRequestType.BACKGROUND),this._lastAnimationUpdate=h},render:({time:h})=>{if((this._needsRender||!this._idleSuspend||!this.renderer.isCameraFinal||this._needsWaterReflectionUpdate)&&0<a.camera.fullWidth&&0<a.camera.fullHeight){const l=this._needsUpdate&&this._idleSuspend&&this.renderer.isCameraFinal;this._needsWaterReflectionUpdate=this._needsUpdate=this._needsRender=!1;this.renderer.render(null,null,a,p.Decorations.ON,
h);c=!0;l&&this.renderer.hasWaterReflection&&(this.requestRender(p.RenderRequestType.BACKGROUND),this._needsWaterReflectionUpdate=!0)}},update:({time:h})=>{const l=new A.ScreenshotContext(a.camera,this.renderer.hasSlicePlane||this._magnifierHelper.enabled);this._textureRepository.update();this._screenshotManager.update(l,h)},finish:()=>{c&&(this.renderer.finish(a.mode===B.RenderState.IDLE?e:p.RenderRequestType.UPDATE),c=!1)}})};m._initializeContext=function(b){const a=b.options;this._canvas=a.canvas;
this._canvas||(this._canvas=document.createElement("canvas"));this._canvas.setAttribute("style","width: 100%; height:100%; display:block;");const d=X.createContextOrErrorHTML("3d",this._canvas,{alpha:a.alpha||!1,premultipliedAlpha:!0,antialias:!1,depth:!0,stencil:null==a.stencil?!0:a.stencil,powerPreference:"high-performance",preserveDrawingBuffer:a.preserveDrawingBuffer??!1});n.isNone(d)?(b=u("esri-force-webgl"),w.getLogger(this.declaredClass).error("A WebGL context with the requested version ("+
b?b:"automatic) could not be created.")):(this._rctx=this._newRenderingContext(d,b),this._loadShaderOnlyExtensions(),!a.alpha&&this._rctx.contextAttributes.alpha&&w.getLogger(this.declaredClass).error("WebGL context has alpha channel even though no alpha channel was requested"),!this._rctx.contextAttributes.alpha&&11<=u("safari")&&(this._container.style.backgroundColor="black"),this._container.appendChild(this._canvas))};m._newRenderingContext=function(b,a){const d={disabledExtensions:a.options.deactivatedWebGLExtensions||
{},debugWebGLExtensions:a.options.debugWebGLExtensions||{},maxAnisotropy:8},e=(c,h)=>a.view.resourceController.memoryController.newCache(c,h);if(W.contextCache.enabled){let c=D.get(b);if(c)return c.configure(d),c.newCache=e,c.ref(),c;c=new z.RenderingContext(b,d,e);D.set(b,c);c.ref();return c}return new z.RenderingContext(b,d,e)};m._loadShaderOnlyExtensions=function(){this._rctx.capabilities.enable("standardDerivatives");this._rctx.capabilities.enable("shaderTextureLOD");this._rctx.capabilities.enable("textureFloat")};
m.getObjectAndLayerIdColor=function(b){return n.isSome(this.objectAndLayerIdRenderHelper)?this.objectAndLayerIdRenderHelper.getObjectAndLayerIdColor(b):null};t._createClass(q,[{key:"performanceInfo",get:function(){const b=this._rctx.gl;return{renderer:this.renderer.performanceInfo,textureMemory:void 0!==b.getUsedTextureMemory?b.getUsedTextureMemory():void 0,renderbufferMemory:void 0!==b.getUsedRenderbufferMemory?b.getUsedRenderbufferMemory():void 0,VBOMemory:void 0!==b.getUsedVBOMemory?b.getUsedVBOMemory():
void 0}}},{key:"updating",get:function(){return this._needsUpdate||this._needsWaterReflectionUpdate||this.renderer.updating||this._textureRepository.updating||this.waterTextureRepository.updating||this._magnifierHelper.updating}},{key:"textureRepository",get:function(){return this._textureRepository}},{key:"compositingHelper",get:function(){return this._compositingHelper}},{key:"magnifier",set:function(b){this._magnifierHelper.magnifier=b}},{key:"renderingContext",get:function(){return this._rctx}},
{key:"capabilities",get:function(){return this._rctx.capabilities}},{key:"canvas",get:function(){return this._canvas}},{key:"componentObjectCollection",get:function(){n.isNone(this._componentObjectCollection)&&(this._componentObjectCollection=new I.ComponentObjectCollection(this.renderer.renderPassManager,this._viewingMode));return this._componentObjectCollection},set:function(b){this._componentObjectCollection=b}}]);return q}(E);g.__decorate([k.property({type:Boolean,readOnly:!0})],f.RenderView.prototype,
"updating",null);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_rctx",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_container",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_canvas",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_stippleTextureRepository",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"waterTextureRepository",void 0);g.__decorate([k.property({autoDestroy:!0})],
f.RenderView.prototype,"_magnifierHelper",void 0);g.__decorate([k.property({readOnly:!0})],f.RenderView.prototype,"objectAndLayerIdRenderHelper",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_textureRepository",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_compositingHelper",void 0);g.__decorate([k.property({autoDestroy:!0,readOnly:!0})],f.RenderView.prototype,"renderer",void 0);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,
"_screenshotManager",void 0);g.__decorate([k.property()],f.RenderView.prototype,"componentObjectCollection",null);g.__decorate([k.property({autoDestroy:!0})],f.RenderView.prototype,"_componentObjectCollection",void 0);g.__decorate([k.property()],f.RenderView.prototype,"_needsUpdate",void 0);g.__decorate([k.property()],f.RenderView.prototype,"_needsWaterReflectionUpdate",void 0);f.RenderView=g.__decorate([H.subclass("esri.views.3d.webgl-engine.parts.RenderView")],f.RenderView);const D=U.getContextCache();
Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});