// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../core/promiseUtils ../../../../chunks/vec4f64 ../lib/basicInterfaces ../../../support/screenshotUtils ../../../webgl/enums ../../../webgl/FramebufferObject ../../../../core/imageUtils".split(" "),function(r,x,v,y,z,t,A,m,w,u){let B=function(){function q(b,a,d,c){this._rctx=b;this._renderFunctions=a;this._forceCameraHook=d;this._disposeOffscreenBuffers=c;this.supersample=!0;this._screenshotQueue=[]}var h=
q.prototype;h.destroy=function(){this._rctx=null};h.takeScreenshot=function(){var b=x._asyncToGenerator(function*(a){yield this._renderFunctions.prepareOverlay();this._renderFunctions.requestRenderScene(t.RenderRequestType.BACKGROUND);const d=y.createResolver();this._screenshotQueue.push({settings:a,resolver:d});return d.promise});return function(a){return b.apply(this,arguments)}}();h.update=function(b,a){for(const d of this._screenshotQueue){if(null==this._rctx){d.resolver.reject();continue}const c=
this._renderScreenshot(b,{...d.settings,pixelRatio:d.settings.pixelRatio*b.viewCamera.pixelRatio},a);d.resolver(c)}this._screenshotQueue.length=0};h._renderScreenshotOverlay=function(b,a,d){b.width=a.width;b.height=a.height;const c=b.getContext("2d"),g=d.pixelRatio;c.save();c.translate(0,a.height);c.scale(1,-1);d.region&&c.translate(-d.region.x,-d.region.y);c.scale(g,g);a=this._renderFunctions.renderOverlay(b,a);c.restore();return a};h._readbackScreenshot=function(b,a){return b.resample?this._readbackScreenshotResampled({...b,
resample:b.resample},a):this._readbackScreenshotImmediate(b,a)};h._readbackScreenshotResampled=function(b,a){const {framebufferWidth:d,framebufferHeight:c,region:g,resample:f}=b,p=this._ensureScreenshotEncodeCanvas();let n=u.createEmptyImageData(d,c,p);this._rctx.gl.readPixels(0,0,d,c,m.PixelFormat.RGBA,m.DataType.UNSIGNED_BYTE,new Uint8Array(n.data.buffer));a();n=this._renderScreenshotOverlay(p,n,{...b,region:void 0});b=u.createEmptyImageData(g.width,g.height,p);return A.resampleHermite(n,b,!0,f.region.x,
c-(f.region.y+f.region.height),f.region.width,f.region.height)};h._readbackScreenshotImmediate=function(b,a){const {framebufferHeight:d,region:c}=b,g=this._ensureScreenshotEncodeCanvas(),f=u.createEmptyImageData(c.width,c.height,g);this._rctx.gl.readPixels(c.x,d-(c.y+c.height),c.width,c.height,m.PixelFormat.RGBA,m.DataType.UNSIGNED_BYTE,new Uint8Array(f.data.buffer));a();return this._renderScreenshotOverlay(g,f,b)};h._renderScreenshot=function(b,a,d){let c=null,g=null;const f=b.viewCamera,{framebufferWidth:p,
framebufferHeight:n}=a;var l=!1;b=a.disableDecorations&&b.frameHasDecorations;var e=a.ignorePadding&&f.pixelRatio!==a.pixelRatio;b=p!==f.fullWidth||n!==f.fullHeight||b||e||a.objectAndLayerIdColor;a.objectAndLayerIdColor&&(g=new w.FramebufferObject(this._rctx,{width:p,height:n,colorTarget:m.TargetType.TEXTURE,depthStencilTarget:m.DepthStencilTargetType.DEPTH_STENCIL_RENDER_BUFFER}));if(b){e=f.clone();if(a.ignorePadding){l=z.clone(e.padding);for(var k=0;4>k;k++)l[k]=Math.round(l[k]/e.pixelRatio*a.pixelRatio);
e.padding=l}e.fullWidth=p;e.fullHeight=n;e.pixelRatio=a.pixelRatio;l=f.fovX-e.fovX;k=f.fovY-e.fovY;0>l&&l<k?e.fovX=f.fovX:0>k&&k<l&&(e.fovY=f.fovY);this._forceCameraHook(e);l=!0;c=new w.FramebufferObject(this._rctx,{width:e.fullWidth,height:e.fullHeight,colorTarget:m.TargetType.TEXTURE,depthStencilTarget:m.DepthStencilTargetType.DEPTH_STENCIL_RENDER_BUFFER});this._renderFunctions.renderScene(c,g,e,a.disableDecorations?t.Decorations.OFF:t.Decorations.ON,d);this._disposeOffscreenBuffers()}e=()=>{this._rctx.bindFramebuffer(null);
v.disposeMaybe(c)};d=this._readbackScreenshot(a,e);e();e=null;a.objectAndLayerIdColor&&(k=()=>{this._rctx.bindFramebuffer(null);v.disposeMaybe(g)},this._rctx.bindFramebuffer(g),e=this._readbackScreenshot(a,k),this._rctx.bindFramebuffer(null),k());if(b&&!this._rctx.contextAttributes.alpha)for(a=3;a<d.data.length;a+=4)d.data[a]=255;if(e&&!this._rctx.contextAttributes.alpha)for(a=3;a<e.data.length;a+=4)e.data[a]=255;l&&this._forceCameraHook(f);return[d,e]};h._ensureScreenshotEncodeCanvas=function(){this._screenshotEncodeCanvas||
(this._screenshotEncodeCanvas=document.createElement("canvas"));return this._screenshotEncodeCanvas};return q}();r.ScreenshotContext=function(q,h){this.viewCamera=q;this.frameHasDecorations=h};r.ScreenshotManager=B;Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});