// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/handleUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ../widgets/Widget ../widgets/support/widget ../widgets/support/jsxFactory ../widgets/support/decorators/messageBundle".split(" "),function(Y,E,pa,qa,F,U,Z,ra,y,sa,z,ta){function aa(r,d){var b=Object.keys(r);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(r);
d&&(a=a.filter(function(e){return Object.getOwnPropertyDescriptor(r,e).enumerable}));b.push.apply(b,a)}return b}function ba(r){for(var d=1;d<arguments.length;d++){var b=null!=arguments[d]?arguments[d]:{};d%2?aa(Object(b),!0).forEach(function(a){var e=b[a];a:if("object"===typeof a&&null!==a){var h=a[Symbol.toPrimitive];if(void 0!==h){a=h.call(a,"string");if("object"!==typeof a)break a;throw new TypeError("@@toPrimitive must return a primitive value.");}a=String(a)}a="symbol"===typeof a?a:String(a);
a in r?Object.defineProperty(r,a,{value:e,enumerable:!0,configurable:!0,writable:!0}):r[a]=e}):Object.getOwnPropertyDescriptors?Object.defineProperties(r,Object.getOwnPropertyDescriptors(b)):aa(Object(b)).forEach(function(a){Object.defineProperty(r,a,Object.getOwnPropertyDescriptor(b,a))})}return r}U='input select textarea a[href] button [tabindex]:not(slot) audio[controls] video[controls] [contenteditable]:not([contenteditable\x3d"false"]) details\x3esummary:first-of-type details'.split(" ");var N=
U.join(","),C=(Z="undefined"===typeof Element)?function(){}:Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,O=!Z&&Element.prototype.getRootNode?function(r){return r.getRootNode()}:function(r){return r.ownerDocument},ca=function(r,d,b){var a=Array.prototype.slice.apply(r.querySelectorAll(N));d&&C.call(r,N)&&a.unshift(r);return a=a.filter(b)},da=function e(d,b,a){for(var h=[],g=Array.from(d);g.length;){var k=g.shift();if("SLOT"===k.tagName){var l=
k.assignedElements();l=e(l.length?l:k.children,!0,a);a.flatten?h.push.apply(h,l):h.push({scopeParent:k,candidates:l})}else{C.call(k,N)&&a.filter(k)&&(b||!d.includes(k))&&h.push(k);l=k.shadowRoot||"function"===typeof a.getShadowRoot&&a.getShadowRoot(k);var q=!a.shadowRootFilter||a.shadowRootFilter(k);l&&q?(l=e(!0===l?k.children:l.children,!0,a),a.flatten?h.push.apply(h,l):h.push({scopeParent:k,candidates:l})):g.unshift.apply(g,k.children)}}return h},ea=function(d,b){return 0>d.tabIndex&&(b||/^(AUDIO|VIDEO|DETAILS)$/.test(d.tagName)||
d.isContentEditable)&&isNaN(parseInt(d.getAttribute("tabindex"),10))?0:d.tabIndex},ua=function(d,b){return d.tabIndex===b.tabIndex?d.documentOrder-b.documentOrder:d.tabIndex-b.tabIndex},va=function(d){return"DETAILS"===d.tagName&&Array.prototype.slice.apply(d.children).some(function(b){return"SUMMARY"===b.tagName})},wa=function(d,b){for(var a=0;a<d.length;a++)if(d[a].checked&&d[a].form===b)return d[a]},xa=function(d){if(!d.name)return!0;var b=d.form||O(d),a=function(h){return b.querySelectorAll('input[type\x3d"radio"][name\x3d"'+
h+'"]')};if("undefined"!==typeof window&&"undefined"!==typeof window.CSS&&"function"===typeof window.CSS.escape)var e=a(window.CSS.escape(d.name));else try{e=a(d.name)}catch(h){return console.error("Looks like you have a radio button with a name attribute containing invalid CSS selector characters and need the CSS.escape polyfill: %s",h.message),!1}a=wa(e,d.form);return!a||a===d},fa=function(d){d=d.getBoundingClientRect();var b=d.height;return 0===d.width&&0===b},ya=function(d,b){var a=b.displayCheck;
b=b.getShadowRoot;if("hidden"===getComputedStyle(d).visibility)return!0;var e=C.call(d,"details\x3esummary:first-of-type")?d.parentElement:d;if(C.call(e,"details:not([open]) *"))return!0;if(!a||"full"===a||"legacy-full"===a){if("function"===typeof b){for(e=d;d;){var h=d.parentElement,g=O(d);if(h&&!h.shadowRoot&&!0===b(h))return fa(d);d=d.assignedSlot?d.assignedSlot:h||g===d.ownerDocument?h:g.host}d=e}b=d;var k;e=O(b).host;for(h=!!(null!==(k=e)&&void 0!==k&&k.ownerDocument.contains(e)||b.ownerDocument.contains(b));!h&&
e;){var l;e=O(e).host;h=!(null===(l=e)||void 0===l||!l.ownerDocument.contains(e))}if(h)return!d.getClientRects().length;if("legacy-full"!==a)return!0}else if("non-zero-area"===a)return fa(d);return!1},P=function(d,b){var a;(a=b.disabled)||(a="INPUT"===b.tagName&&"hidden"===b.type);if(!(d=a||ya(b,d)||va(b)))a:{if(/^(INPUT|BUTTON|SELECT|TEXTAREA)$/.test(b.tagName))for(d=b.parentElement;d;){if("FIELDSET"===d.tagName&&d.disabled){for(a=0;a<d.children.length;a++){var e=d.children.item(a);if("LEGEND"===
e.tagName){d=C.call(d,"fieldset[disabled] *")?!0:!e.contains(b);break a}}d=!0;break a}d=d.parentElement}d=!1}return d?!1:!0},V=function(d,b){return"INPUT"===b.tagName&&"radio"===b.type&&!xa(b)||0>ea(b)||!P(d,b)?!1:!0},za=function(d){d=parseInt(d.getAttribute("tabindex"),10);return isNaN(d)||0<=d?!0:!1},Aa=function a(b){var e=[],h=[];b.forEach(function(g,k){var l=!!g.scopeParent,q=l?g.scopeParent:g,t=ea(q,l),A=l?a(g.candidates):q;0===t?l?e.push.apply(e,A):e.push(q):h.push({documentOrder:k,tabIndex:t,
item:g,isScope:l,content:A})});return h.sort(ua).reduce(function(g,k){k.isScope?g.push.apply(g,k.content):g.push(k.content);return g},[]).concat(e)},Ba=function(b,a){a=a||{};b=a.getShadowRoot?da([b],a.includeContainer,{filter:V.bind(null,a),flatten:!1,getShadowRoot:a.getShadowRoot,shadowRootFilter:za}):ca(b,a.includeContainer,V.bind(null,a));return Aa(b)},Ca=function(b,a){a=a||{};return a.getShadowRoot?da([b],a.includeContainer,{filter:P.bind(null,a),flatten:!0,getShadowRoot:a.getShadowRoot}):ca(b,
a.includeContainer,P.bind(null,a))},Q=function(b,a){a=a||{};if(!b)throw Error("No node provided");return!1===C.call(b,N)?!1:V(a,b)},Da=U.concat("iframe").join(","),W=function(b,a){a=a||{};if(!b)throw Error("No node provided");return!1===C.call(b,Da)?!1:P(a,b)},ha={activateTrap:function(b,a){if(0<b.length){var e=b[b.length-1];e!==a&&e.pause()}e=b.indexOf(a);-1!==e&&b.splice(e,1);b.push(a)},deactivateTrap:function(b,a){a=b.indexOf(a);-1!==a&&b.splice(a,1);0<b.length&&b[b.length-1].unpause()}},G=function(b){return"Tab"===
b.key||9===b.keyCode},Ea=function(b){return G(b)&&!b.shiftKey},Fa=function(b){return G(b)&&b.shiftKey},ia=function(b,a){var e=-1;b.every(function(h,g){return a(h)?(e=g,!1):!0});return e},H=function(b){for(var a=arguments.length,e=Array(1<a?a-1:0),h=1;h<a;h++)e[h-1]=arguments[h];return"function"===typeof b?b.apply(void 0,e):b},R=function(b){return b.target.shadowRoot&&"function"===typeof b.composedPath?b.composedPath()[0]:b.target},Ga=[],Ia=function(b,a){var e=(null===a||void 0===a?void 0:a.document)||
document,h=(null===a||void 0===a?void 0:a.trapStack)||Ga,g=ba({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0,isKeyForward:Ea,isKeyBackward:Fa},a),k=[],l=[],q=[],t=null,A=null,u=!1,x=!1,I=void 0,D=function(n,c,f){return n&&void 0!==n[c]?n[c]:g[f||c]},J=function(n){return l.findIndex(function(c){var f=c.tabbableNodes;return c.container.contains(n)||f.find(function(m){return m===n})})},K=function(n){var c=g[n];if("function"===typeof c){for(var f=arguments.length,m=Array(1<f?f-
1:0),p=1;p<f;p++)m[p-1]=arguments[p];c=c.apply(void 0,m)}!0===c&&(c=void 0);if(!c){if(void 0===c||!1===c)return c;throw Error("`".concat(n,"` was specified but was not a node, or did not return a node"));}f=c;if("string"===typeof c&&(f=e.querySelector(c),!f))throw Error("`".concat(n,"` as selector refers to no known node"));return f},S=function(){var n=K("initialFocus");if(!1===n)return!1;void 0===n&&(n=0<=J(e.activeElement)?e.activeElement:(n=q[0])&&n.firstTabbableNode||K("fallbackFocus"));if(!n)throw Error("Your focus-trap needs to have at least one focusable element");
return n},L=function(){l=k.map(function(n){var c=Ba(n,g.tabbableOptions),f=Ca(n,g.tabbableOptions);return{container:n,tabbableNodes:c,focusableNodes:f,firstTabbableNode:0<c.length?c[0]:null,lastTabbableNode:0<c.length?c[c.length-1]:null,nextTabbableNode:function(m){var p=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,w=f.findIndex(function(v){return v===m});if(!(0>w))return p?f.slice(w+1).find(function(v){return Q(v,g.tabbableOptions)}):f.slice(0,w).reverse().find(function(v){return Q(v,
g.tabbableOptions)})}}});q=l.filter(function(n){return 0<n.tabbableNodes.length});if(0>=q.length&&!K("fallbackFocus"))throw Error("Your focus-trap must have at least one container with at least one tabbable node in it at all times");},M=function f(c){!1!==c&&c!==e.activeElement&&(c&&c.focus?(c.focus({preventScroll:!!g.preventScroll}),A=c,c.tagName&&"input"===c.tagName.toLowerCase()&&"function"===typeof c.select&&c.select()):f(S()))},ja=function(c){var f=K("setReturnFocus",c);return f?f:!1===f?!1:
c},T=function(c){var f=R(c);0<=J(f)||(H(g.clickOutsideDeactivates,c)?B.deactivate({returnFocus:g.returnFocusOnDeactivate&&!W(f,g.tabbableOptions)}):H(g.allowOutsideClick,c)||c.preventDefault())},ka=function(c){var f=R(c),m=0<=J(f);m||f instanceof Document?m&&(A=f):(c.stopImmediatePropagation(),M(A||S()))},Ha=function(c){var f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,m=R(c);L();var p=null;if(0<q.length){var w=J(m),v=0<=w?l[w]:void 0;0>w?p=f?q[q.length-1].lastTabbableNode:q[0].firstTabbableNode:
f?(f=ia(q,function(X){return m===X.firstTabbableNode}),0>f&&(v.container===m||W(m,g.tabbableOptions)&&!Q(m,g.tabbableOptions)&&!v.nextTabbableNode(m,!1))&&(f=w),0<=f?p=q[0===f?q.length-1:f-1].lastTabbableNode:G(c)||(p=v.nextTabbableNode(m,!1))):(f=ia(q,function(X){return m===X.lastTabbableNode}),0>f&&(v.container===m||W(m,g.tabbableOptions)&&!Q(m,g.tabbableOptions)&&!v.nextTabbableNode(m))&&(f=w),0<=f?p=q[f===q.length-1?0:f+1].firstTabbableNode:G(c)||(p=v.nextTabbableNode(m)))}else p=K("fallbackFocus");
p&&(G(c)&&c.preventDefault(),M(p))},la=function(c){"Escape"!==c.key&&"Esc"!==c.key&&27!==c.keyCode||!1===H(g.escapeDeactivates,c)?(g.isKeyForward(c)||g.isKeyBackward(c))&&Ha(c,g.isKeyBackward(c)):(c.preventDefault(),B.deactivate())},ma=function(c){var f=R(c);0<=J(f)||H(g.clickOutsideDeactivates,c)||H(g.allowOutsideClick,c)||(c.preventDefault(),c.stopImmediatePropagation())},na=function(){if(u)return ha.activateTrap(h,B),I=g.delayInitialFocus?setTimeout(function(){M(S())},0):M(S()),e.addEventListener("focusin",
ka,!0),e.addEventListener("mousedown",T,{capture:!0,passive:!1}),e.addEventListener("touchstart",T,{capture:!0,passive:!1}),e.addEventListener("click",ma,{capture:!0,passive:!1}),e.addEventListener("keydown",la,{capture:!0,passive:!1}),B},oa=function(){if(u)return e.removeEventListener("focusin",ka,!0),e.removeEventListener("mousedown",T,!0),e.removeEventListener("touchstart",T,!0),e.removeEventListener("click",ma,!0),e.removeEventListener("keydown",la,!0),B};var B={get active(){return u},get paused(){return x},
activate:function(c){if(u)return this;var f=D(c,"onActivate"),m=D(c,"onPostActivate"),p=D(c,"checkCanFocusTrap");p||L();u=!0;x=!1;t=e.activeElement;f&&f();c=function(){p&&L();na();m&&m()};if(p)return p(k.concat()).then(c,c),this;c();return this},deactivate:function(c){if(!u)return this;var f=ba({onDeactivate:g.onDeactivate,onPostDeactivate:g.onPostDeactivate,checkCanReturnFocus:g.checkCanReturnFocus},c);clearTimeout(I);I=void 0;oa();x=u=!1;ha.deactivateTrap(h,B);var m=D(f,"onDeactivate"),p=D(f,"onPostDeactivate");
c=D(f,"checkCanReturnFocus");var w=D(f,"returnFocus","returnFocusOnDeactivate");m&&m();f=function(){setTimeout(function(){w&&M(ja(t));p&&p()},0)};if(w&&c)return c(ja(t)).then(f,f),this;f();return this},pause:function(){if(x||!u)return this;x=!0;oa();return this},unpause:function(){if(!x||!u)return this;x=!1;L();na();return this},updateContainerElements:function(c){k=[].concat(c).filter(Boolean).map(function(f){return"string"===typeof f?e.querySelector(f):f});u&&L();return this}};B.updateContainerElements(b);
return B};y=function(b){function a(h,g){var k=b.call(this,h,g)||this;k.container=document.createElement("div");k.content=null;k.open=!1;k._focusTrap=null;k._close=()=>{k.open=!1};document.body.appendChild(k.container);k.addHandles(qa.watch(()=>k.open,()=>k._toggleFocusTrap()));return k}Y._inheritsLoose(a,b);var e=a.prototype;e.destroy=function(){this._destroyFocusTrap()};e.render=function(){var h=this.id;const {open:g,content:k,title:l,messages:q}=this;var t=g&&!!k;const A={["esri-identity-modal--open"]:t,
["esri-identity-modal--closed"]:!t},u=z.tsx("button",{class:"esri-identity-modal__close-button","aria-label":q.close,title:q.close,bind:this,onclick:this._close,type:"button"},z.tsx("span",{"aria-hidden":"true",class:"esri-icon-close"})),x=`${h}_title`;h=`${h}_content`;const I=l?z.tsx("h1",{id:x,class:"esri-identity-modal__title"},l):null;t=t?z.tsx("div",{bind:this,class:"esri-identity-modal__dialog",role:"dialog","aria-labelledby":x,"aria-describedby":h,afterCreate:this._createFocusTrap},u,I,this._renderContent(h)):
null;return z.tsx("div",{tabIndex:-1,class:this.classes("esri-identity-modal",A)},t)};e._destroyFocusTrap=function(){this._focusTrap?.deactivate({onDeactivate:()=>{}});this._focusTrap=null};e._toggleFocusTrap=function(){const {_focusTrap:h,open:g}=this;h&&(g?h.activate():h.deactivate())};e._createFocusTrap=function(h){this._destroyFocusTrap();const g=requestAnimationFrame(()=>{this._focusTrap=Ia(h,{initialFocus:"input",onDeactivate:this._close});this._toggleFocusTrap()});this.addHandles(pa.makeHandle(()=>
cancelAnimationFrame(g)))};e._renderContent=function(h){const g=this.content;return"string"===typeof g?z.tsx("div",{class:"esri-identity-modal__content",id:h,innerHTML:g}):sa.isWidget(g)?z.tsx("div",{class:"esri-identity-modal__content",id:h},g.render()):g instanceof HTMLElement?z.tsx("div",{class:"esri-identity-modal__content",id:h,bind:g,afterCreate:this._attachToNode}):null};e._attachToNode=function(h){h.appendChild(this)};Y._createClass(a,[{key:"title",get:function(){return this.messages?.auth.signIn}}]);
return a}(y);E.__decorate([F.property({readOnly:!0})],y.prototype,"container",void 0);E.__decorate([F.property()],y.prototype,"content",void 0);E.__decorate([F.property()],y.prototype,"open",void 0);E.__decorate([F.property(),ta.messageBundle("esri/t9n/common")],y.prototype,"messages",void 0);E.__decorate([F.property()],y.prototype,"title",null);return y=E.__decorate([ra.subclass("esri.identity.IdentityModal")],y)});