// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../chunks/_rollupPluginBabelHelpers ../geometry ../kernel ../request ../core/Error ../core/Logger ./knowledgeGraph/GraphQueryResult ./knowledgeGraph/GraphQueryStreamingResult ./knowledgeGraph/KnowledgeGraph ./knowledgeGraph/ServiceDefinition ./knowledgeGraph/wasmInterface/knowledgeWasmAccess ./knowledgeGraph/wasmInterface/queryToWasmEncodedFactories ./knowledgeGraph/wasmInterface/updateToWasmEncodedFactories ./knowledgeGraph/wasmInterface/wasmToDataModelFactories ./knowledgeGraph/wasmInterface/wasmToQueryResponseObjFactories ./knowledgeGraph/wasmInterface/wasmToUpdateResponseFactories ../geometry/Geometry".split(" "),
function(l,k,ia,U,r,f,V,P,Q,W,X,n,q,t,Y,Z,aa,ba){function w(){w=k._asyncToGenerator(function*(a,c,b){if(a.serviceDefinition.dataEditingNotSupported)throw new f("knowledge-graph:data-editing-not-supported","The Knowledge Graph Service definition indicated that data editing is not supported");const d=`${a.url}/graph/applyEdits`;yield x(a);b=yield y(d,b);b.data.body=yield ca(c,a);a=yield fetch(b.data.url,b.data);return da(a)});return w.apply(this,arguments)}function z(){z=k._asyncToGenerator(function*(a,
c,b){b=yield r(`${a.url}/graph/query`,{responseType:"array-buffer",query:{f:"pbf",openCypherQuery:c.openCypherQuery,...b?.query},signal:b?.signal,timeout:b?.timeout});const d=b.getHeader?.("content-type");c=b.data;if(d?.includes("application/x-protobuf")){b=new ((yield n.getWasmInterface()).GraphQueryDecoder);b.deleteLater();if(a.dataModel)return new P({resultRows:A(b,c,a.dataModel)});throw new f("knowledge-graph:undefined-data-model","The KnowledgeGraph supplied did not have a data model");}throw new f("knowledge-graph:unexpected-server-response",
"server returned an unexpected response",{responseType:d,data:b.data});});return z.apply(this,arguments)}function B(){B=k._asyncToGenerator(function*(a,c,b){const d=`${a.url}/graph/query`;yield x(a);b=yield y(d,b);b.data.body=yield ea(c,a);c=yield fetch(b.data.url,b.data);if(a.dataModel)return new Q({resultRowsStream:yield R(c,a.dataModel)});throw new f("knowledge-graph:undefined-data-model","The KnowledgeGraph supplied did not have a data model");});return B.apply(this,arguments)}function C(){C=
k._asyncToGenerator(function*(a,c,b){b=yield r(`${a.url}/graph/search`,{responseType:"array-buffer",query:{f:"pbf",searchQuery:`"${c.searchQuery}"`,typeCategoryFilter:c.typeCategoryFilter,...b?.query},signal:b?.signal,timeout:b?.timeout});const d=b.getHeader?.("content-type");c=b.data;if(d?.includes("application/x-protobuf")){b=new ((yield n.getWasmInterface()).GraphQueryDecoder);b.deleteLater();if(a.dataModel)return new P({resultRows:A(b,c,a.dataModel)});throw new f("knowledge-graph:undefined-data-model",
"The KnowledgeGraph supplied did not have a data model");}throw new f("knowledge-graph:unexpected-server-response","server returned an unexpected response",{responseType:d,data:b.data});});return C.apply(this,arguments)}function D(){D=k._asyncToGenerator(function*(a,c,b){const d=`${a.url}/graph/search`;yield x(a);b=yield y(d,b);b.data.body=yield fa(c);c=yield fetch(b.data.url,b.data);if(a.dataModel)return new Q({resultRowsStream:yield R(c,a.dataModel)});throw new f("knowledge-graph:undefined-data-model",
"The KnowledgeGraph supplied did not have a data model");});return D.apply(this,arguments)}function E(){E=k._asyncToGenerator(function*(a){a=new W({url:a});const c=[];c.push(u(a));c.push(S(a));yield Promise.all(c);return a});return E.apply(this,arguments)}function u(a){return F.apply(this,arguments)}function F(){F=k._asyncToGenerator(function*(a){a.dataModel=yield T(a)});return F.apply(this,arguments)}function S(a){return G.apply(this,arguments)}function G(){G=k._asyncToGenerator(function*(a){const c=
(yield r(a.url,{query:{f:"json"}})).data;c.capabilities=c?.capabilities?.split(",");c.supportedQueryFormats=c?.supportedQueryFormats?.split(",");a.serviceDefinition=new X(c);return a.serviceDefinition});return G.apply(this,arguments)}function x(a){return H.apply(this,arguments)}function H(){H=k._asyncToGenerator(function*(a){U.id?.findCredential(a.url)||(a.dataModel?yield T(a):yield u(a))});return H.apply(this,arguments)}function v(a,c,b){if(0!==a.error_code)throw new f(c,b,{errorCode:a.error_code,
errorMessage:a.error_message});}function ca(a,c){return I.apply(this,arguments)}function I(){I=k._asyncToGenerator(function*(a,c){c.dataModel||(yield u(c));if(!c.dataModel)throw new f("knowledge-graph:data-model-undefined","Encoding could not proceed because a data model was not provided and it could not be determined from the service");const b=yield n.getWasmInterface();c=a.options?.cascadeDelete?!0:!1;const d=new b.GraphApplyEditsEncoder(b.SpatialReferenceUtil.WGS84(),a.options?.inputQuantizationParameters?
t.inputQuantizationParemetersToWasmFormat(a.options?.inputQuantizationParameters):b.InputQuantizationUtil.WGS84_lossless());d.deleteLater();d.cascade_delete=c;try{let g;a.entityAdds?.forEach(e=>{g=d.add_entity(t.namedObjectToWasm(e,b));v(g,"knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits - an entity failed to be added to the encoder")});a.relationshipAdds?.forEach(e=>{if(!e.originId||!e.destinationId)throw new f("knowledge-graph:relationship-origin-destination-missing",
"When adding a new relationship, you must provide both an origin and destination id on the appropriate class property");g=d.add_relationship(t.namedObjectToWasm(e,b));v(g,"knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits - a relationship failed to be added to the encoder")});a.entityUpdates?.forEach(e=>{if(!e.id)throw new f("knowledge-graph:entity-id-missing","When updating an entity or relationship, you must specify the id on the class level property");g=d.update_entity(t.namedObjectToWasm(e,
b));v(g,"knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits - an entity failed to be added to the encoder")});a.relationshipUpdates?.forEach(e=>{if(!e.id)throw new f("knowledge-graph:relationship-id-missing","When updating an entity or relationship, you must specify the id on the class level property");g=d.update_relationship(t.namedObjectToWasm(e,b));v(g,"knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits - a relationship failed to be added to the encoder")});
a.entityDeletes?.forEach(e=>{if(!e.typeName)throw new f("knowledge-graph:no-type-name","You must indicate the entity/relationship named object type to apply edits - delete");const h=d.make_delete_helper(e.typeName,!0);h.deleteLater();e.ids?.forEach(m=>{h.delete_by_id(m)})});a.relationshipDeletes?.forEach(e=>{if(!e.typeName)throw new f("knowledge-graph:no-type-name","You must indicate the entity/relationship named object type to apply edits - delete");const h=d.make_delete_helper(e.typeName,!1);e.ids?.forEach(m=>
{h.delete_by_id(m)})});d.encode()}catch(g){throw new f("knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits failed",{error:g});}a=d.get_encoding_result();v(a.error,"knowledge-graph:applyEdits-encoding-failed","Attempting to encode the applyEdits failed");return a.get_byte_buffer()});return I.apply(this,arguments)}function ea(a,c){return J.apply(this,arguments)}function J(){J=k._asyncToGenerator(function*(a,c){const b=yield n.getWasmInterface(),d=new b.GraphQueryRequestEncoder;
d.deleteLater();d.output_spatial_reference=b.SpatialReferenceUtil.WGS84();d.open_cypher_query=a.openCypherQuery;if(a.bindParameters)for(const [p,ha]of Object.entries(a.bindParameters)){var g=p,e=ha,h=d,m=b;null===e||void 0===e?h.set_param_key_value(g,""):"object"!==typeof e?h.set_param_key_value(g,e):e instanceof Date?h.set_param_key_value(g,e):e instanceof ba?h.set_param_key_value(g,q.geometryToWasm(e,m)):e instanceof Array?h.set_param_key_value(g,q.bindParamArrayToWasm(e,m)):h.set_param_key_value(g,
q.bindParamObjectToWasm(e,m))}if(a.bindGeometryQuantizationParameters)q.setInputQuantizationParametersOnEncoder(a.bindGeometryQuantizationParameters,d);else if(c.dataModel||(yield u(c)),4326===c.dataModel?.spatialReference?.wkid)d.input_quantization_parameters=b.InputQuantizationUtil.WGS84_lossless();else throw new f("knowledge-graph:SR-quantization-mismatch","If the DataModel indicates a coordinate system other than WGS84, inputQuantizationParameters must be provided to the query encoder");a.outputQuantizationParameters&&
q.setOutputQuantizationParametersOnEncoder(a.outputQuantizationParameters,d,b);try{d.encode()}catch(p){throw new f("knowledge-graph:query-encoding-failed","Attempting to encode the query failed",{error:p});}a=d.get_encoding_result();if(0!==a.error.error_code)throw new f("knowledge-graph:query-encoding-failed","Attempting to encode the query failed",{errorCode:a.error.error_code,errorMessage:a.error.error_message});return a.get_byte_buffer()});return J.apply(this,arguments)}function fa(a){return K.apply(this,
arguments)}function K(){K=k._asyncToGenerator(function*(a){const c=yield n.getWasmInterface(),b=new c.GraphSearchRequestEncoder;b.deleteLater();b.search_query=a.searchQuery;b.type_category_filter=c.esriNamedTypeCategory[a.typeCategoryFilter.toString()];!0===a.returnSearchContext&&(b.return_search_context=a.returnSearchContext);void 0!==a.start&&0<a.start&&(b.start_index=a.start);void 0!==a.num&&(b.max_num_results=a.num);if(void 0!==a.idsFilter&&Array.isArray(a.idsFilter)&&0<a.idsFilter.length)try{b.set_ids_filter(q.bindParamArrayToWasm(a.idsFilter,
c))}catch(d){throw new f("knowledge-graph:ids-format-error","Attempting to set ids filter failed.  This is usually caused by an incorrectly formatted UUID string",{error:d});}a.namedTypesFilter?.forEach(d=>{b.add_named_type_filter(d)});try{b.encode()}catch(d){throw new f("knowledge-graph:search-encoding-failed","Attempting to encode the search failed",{error:d});}a=b.get_encoding_result();if(0!==a.error.error_code)throw new f("knowledge-graph:search-encoding-failed","Attempting to encode the search failed",
{errorCode:a.error.error_code,errorMessage:a.error.error_message});return a.get_byte_buffer()});return K.apply(this,arguments)}function y(a,c){return L.apply(this,arguments)}function L(){L=k._asyncToGenerator(function*(a,c){return r(a,{responseType:"native-request-init",method:"post",query:{f:"pbf",...c?.query},body:"x",headers:{"Content-Type":"application/octet-stream"},signal:c?.signal,timeout:c?.timeout})});return L.apply(this,arguments)}function da(a){return M.apply(this,arguments)}function M(){M=
k._asyncToGenerator(function*(a){var c=a.headers.get("content-type");if(c?.includes("application/x-protobuf"))return a=yield a.arrayBuffer(),c=new ((yield n.getWasmInterface()).GraphApplyEditsDecoder),c.deleteLater(),c.decode(new Uint8Array(a)),aa.decoderToApplyEditsResponse(c);throw new f("knowledge-graph:unexpected-server-response","server returned an unexpected response",{responseType:c,data:a.text()});});return M.apply(this,arguments)}function A(a,c,b){a.push_buffer(new Uint8Array(c));c=[];for(b=
0;a.next_row();){b||(b=a.get_header_keys().size());const d=Array(b);for(let g=0;g<b;g++){const e=a.get_value(g);d[g]=Z.decodedWasmObjToQueryResponseObj(e)}c.push(d)}if(a.has_error())throw new f("knowledge-graph:stream-decoding-error","One or more result rows were not successfully decoded",{errorCode:a.error.error_code,errorMessage:a.error.error_message});return c}function R(a,c){return N.apply(this,arguments)}function N(){N=k._asyncToGenerator(function*(a,c){c=a.headers.get("content-type");a.headers.get("content-length")&&
V.getLogger("esri.rest.knowledgeGraph.knowledgeGraphService").warnOnce("Found `Content-Length` header when expecting a streaming HTTP response! Please investigate whether all intermediate HTTP proxies and/or load balancers are configured such that they don't forcefully buffer the entire response before returning it to the client. A valid HTTP streaming response should use Chunked Transfer Encoding and not have a Content Length defined.");if(c?.includes("application/x-protobuf")){const b=a.body?.getReader(),
d=new ((yield n.getWasmInterface()).GraphQueryDecoder);d.deleteLater();return new ReadableStream({start(g){return k._asyncToGenerator(function*(){function e(){return b?.read().then(({done:h,value:m})=>{if(h){let p;d.has_error()&&(p=new f("knowledge-graph:stream-decoding-error","One or more result rows were not successfully decoded",{errorCode:d.error.error_code,errorMessage:d.error.error_message}));b.releaseLock();if(p)throw g.error(p),p;g.close()}else return h=A(d,m),0<h.length&&g.enqueue(h),e()})}
try{return e()}catch(h){b?.releaseLock(),g.error(new f("knowledge-graph:stream-decoding-error","The server returned a valid response, but there was an error decoding the response stream",{error:h})),g.close()}})()}})}throw new f("knowledge-graph:unexpected-server-response","server returned an unexpected response",{responseType:c,data:a.text()});});return N.apply(this,arguments)}function T(a){return O.apply(this,arguments)}function O(){O=k._asyncToGenerator(function*(a){a=yield r(`${a.url}/dataModel/queryDataModel`,
{responseType:"array-buffer",query:{f:"pbf"}});const c=a.getHeader?.("content-type"),b=a.data;if(c?.includes("application/x-protobuf")){a=(yield n.getWasmInterface()).decode_data_model_from_protocol_buffer(new Uint8Array(b));if(!a)throw new f("knowledge-graph:data-model-decode-failure","The server responded to the data model query, but the response failed to be decoded.  This typically occurs when the Knowledge JS API (4.26 or later) is used with an unsupported backend (11.0 or earlier)");return Y.wasmToDataModel(a)}throw new f("knowledge-graph:unexpected-server-response",
"server returned an unexpected response",{responseType:c,data:a.data});});return O.apply(this,arguments)}l.executeApplyEdits=function(a,c,b){return w.apply(this,arguments)};l.executeQuery=function(a,c,b){return z.apply(this,arguments)};l.executeQueryStreaming=function(a,c,b){return B.apply(this,arguments)};l.executeSearch=function(a,c,b){return C.apply(this,arguments)};l.executeSearchStreaming=function(a,c,b){return D.apply(this,arguments)};l.fetchKnowledgeGraph=function(a){return E.apply(this,arguments)};
l.refreshDataModel=u;l.refreshServiceDefinition=S;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});