// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/mathUtils ../../../../core/maybe ../../../../geometry/support/aaBoundingBox ../../support/buffer/InterleavedLayout ../core/shaderLibrary/ShaderOutput ../core/shaderLibrary/shading/Normals.glsl ../lib/GLMaterial ../lib/Material ../lib/PathGeometry ../lib/RenderSlot ../lib/VertexAttribute ./DefaultBufferWriter ./PathTechnique ./internal/MaterialUtil".split(" "),function(q,r,x,y,E,F,d,t,G,u,H,v,n,I,p,J){u=function(g){function f(a){a=
g.call(this,a,new z)||this;a.supportsEdges=!0;a._vertexAttributeLocations=p.vertexAttributeLocations;a._configuration=new p.PathTechniqueConfiguration;a._vertexBufferLayout=f.getVertexBufferLayout();return a}r._inheritsLoose(f,g);var b=f.prototype;b.getConfiguration=function(a,e){this._configuration.output=a;this._configuration.vvSize=this.parameters.vvSizeEnabled;this._configuration.vvColor=this.parameters.vvColorEnabled;this._configuration.vvOpacity=this.parameters.vvOpacityEnabled;this._configuration.hasSlicePlane=
this.parameters.hasSlicePlane;this._configuration.transparent=this.parameters.transparent;this._configuration.hasOccludees=this.parameters.hasOccludees;if(a===d.ShaderOutput.Color||a===d.ShaderOutput.Alpha)this._configuration.doubleSidedMode=this.parameters.doubleSided&&"normal"===this.parameters.doubleSidedType?t.NormalsDoubleSidedMode.View:this.parameters.doubleSided&&"winding-order"===this.parameters.doubleSidedType?t.NormalsDoubleSidedMode.WindingOrder:t.NormalsDoubleSidedMode.None,this._configuration.receiveShadows=
this.parameters.receiveShadows,this._configuration.receiveAmbientOcclusion=e.ssaoHelper.active?this.parameters.receiveSSAO:!1;this._configuration.transparencyPassType=e.transparencyPassType;this._configuration.hasMultipassTerrain=e.multipassTerrain.enabled;this._configuration.cullAboveGround=e.multipassTerrain.cullAboveGround;return this._configuration};b.isVisibleForOutput=function(a){return a===d.ShaderOutput.Shadow||a===d.ShaderOutput.ShadowExcludeHighlight||a===d.ShaderOutput.ShadowHighlight?
this.parameters.castShadows:!0};b.isVisible=function(){return g.prototype.isVisible.call(this)&&0<this.parameters.opacity};b.intersect=function(a,e,w,h,l,A){if(H.isPathGeometry(a)){e=a.path;var k=[this.parameters.size[0],this.parameters.size[1]];if(this.parameters.vvSizeEnabled){var c=this.parameters.vvSizeOffset,m=this.parameters.vvSizeFactor;const B=this.parameters.vvSizeMinSize,C=this.parameters.vvSizeMaxSize,D=e.sizeAttributeValue;k[0]*=x.clamp(c[0]+D*m[0],B[0],C[0]);k[1]*=x.clamp(c[2]+D*m[2],
B[2],C[2])}c=Math.max(k[0],k[1]);a=a.boundingInfo;y.isNone(a)?this._intersectTriangles(e,k,h,l,A):(a=E.fromValues(a.bbMin[0]-c,a.bbMin[1]-c,a.bbMin[2]-c,a.bbMax[0]+c,a.bbMax[1]+c,a.bbMax[2]+c),c=[l[0]-h[0],l[1]-h[1],l[2]-h[2]],m=Math.sqrt(c[0]*c[0]+c[1]*c[1]+c[2]*c[2]),J.intersectAabbInvDir(a,h,[m/c[0],m/c[1],m/c[2]],w.tolerance)&&this._intersectTriangles(e,k,h,l,A))}};b._intersectTriangles=function(a,e,w,h,l){a.baked.size&&a.baked.size[0]===e[0]&&a.baked.size[1]===e[1]||a.baked.bake(e);a.baked.intersect(w,
h,l)};b.createBufferWriter=function(){return new I.DefaultBufferWriter(this._vertexBufferLayout)};b.requiresSlot=function(a,e){switch(e){case d.ShaderOutput.Shadow:case d.ShaderOutput.ShadowHighlight:case d.ShaderOutput.ShadowExcludeHighlight:if(!this.parameters.castShadows)return!1;case d.ShaderOutput.Color:case d.ShaderOutput.Alpha:case d.ShaderOutput.Depth:case d.ShaderOutput.Normal:case d.ShaderOutput.Highlight:case d.ShaderOutput.ObjectAndLayerIdColor:return a===(this.parameters.transparent?
v.RenderSlot.TRANSPARENT_MATERIAL:v.RenderSlot.OPAQUE_MATERIAL)||a===v.RenderSlot.DRAPED_MATERIAL;default:return!1}};b.createGLMaterial=function(a){return new K(a)};f.getVertexBufferLayout=function(){return F.newLayout().vec3f(n.VertexAttribute.POSITION).vec4f(n.VertexAttribute.PROFILERIGHT).vec4f(n.VertexAttribute.PROFILEUP).vec4f(n.VertexAttribute.PROFILEVERTEXANDNORMAL).vec4f(n.VertexAttribute.FEATUREVALUE)};return f}(u.Material);let K=function(g){function f(){return g.apply(this,arguments)||this}
r._inheritsLoose(f,g);var b=f.prototype;b._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.hasOccludees&&this._material.setParameters({hasOccludees:a.hasOccludees})};b._updateShadowState=function(a){(y.isNone(this.technique)||a.shadowMap.enabled!==this.technique.configuration.receiveShadows)&&this._material.setParameters({receiveShadows:a.shadowMap.enabled})};b.beginSlot=function(a){if(this._output===d.ShaderOutput.Color||this._output===d.ShaderOutput.Alpha)this._updateShadowState(a),
this._updateOccludeeState(a);return this.ensureTechnique(p.PathTechnique,a)};return f}(G),z=function(g){function f(){var b=g.apply(this,arguments)||this;b.doubleSided=!1;b.doubleSidedType="normal";b.receiveSSAO=!0;b.receiveShadows=!1;b.castShadows=!0;b.hasSlicePlane=!1;b.transparent=!1;b.hasOccludees=!1;return b}r._inheritsLoose(f,g);return f}(p.PathPassParameters);q.PathMaterial=u;q.PathMaterialParameters=z;Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});