// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/vec4f64 ../../../../geometry/support/buffer/BufferView ../../support/buffer/InterleavedLayout ../core/shaderLibrary/ShaderOutput ../lib/basicInterfaces ../lib/GLMaterial ../lib/Material ../lib/OrderIndependentTransparency ../lib/RenderSlot ../lib/Util ../lib/VertexAttribute ./DefaultBufferWriter ./PatternStyle ./TriangleMaterial ./internal/bufferWriterUtils ../shaders/PatternTechnique".split(" "),function(w,q,E,r,F,p,
G,H,I,J,t,u,n,K,L,x,y,z){x=function(h){function e(a){a=h.call(this,a,new D)||this;a.supportsEdges=!0;a._vertexAttributeLocations=z.vertexAttributeLocations;a._configuration=new z.PatternTechniqueConfiguration;return a}q._inheritsLoose(e,h);var c=e.prototype;c.getConfiguration=function(a,b){this._configuration.output=a;this._configuration.cullFace=this.parameters.cullFace;this._configuration.hasVertexColors=this.parameters.hasVertexColors;this._configuration.hasSlicePlane=this.parameters.hasSlicePlane;
this._configuration.polygonOffset=this.parameters.polygonOffset;this._configuration.writeDepth=this.parameters.writeDepth;this._configuration.style=this.parameters.style;this._configuration.patternSpacing=this.parameters.patternSpacing;this._configuration.lineWidth=this.parameters.lineWidth;this._configuration.draped=this.parameters.draped;this._configuration.transparencyPassType=b.transparencyPassType;this._configuration.enableOffset=b.camera.relativeElevation<J.OITPolygonOffsetLimit;this._configuration.hasMultipassTerrain=
b.multipassTerrain.enabled;this._configuration.cullAboveGround=b.multipassTerrain.cullAboveGround;return this._configuration};c.requiresSlot=function(a,b){return b===p.ShaderOutput.Color||b===p.ShaderOutput.Alpha||b===p.ShaderOutput.Highlight||b===p.ShaderOutput.Depth&&this.parameters.writeLinearDepth?a===t.RenderSlot.DRAPED_MATERIAL?!0:b===p.ShaderOutput.Highlight?a===t.RenderSlot.OPAQUE_MATERIAL:a===(this.parameters.writeDepth?t.RenderSlot.TRANSPARENT_MATERIAL:t.RenderSlot.TRANSPARENT_DEPTH_WRITE_DISABLED_MATERIAL):
!1};c.createGLMaterial=function(a){return new M(a)};c.createBufferWriter=function(){const a=F.newLayout().vec3f(n.VertexAttribute.POSITION).vec4u8(n.VertexAttribute.COLOR).vec4f(n.VertexAttribute.UVMAPSPACE);this.parameters.draped||a.mat3f(n.VertexAttribute.BOUNDINGRECT);return new N(a)};return e}(x.TriangleMaterial);let M=function(h){function e(){return h.apply(this,arguments)||this}q._inheritsLoose(e,h);var c=e.prototype;c._updateParameters=function(a){return this.ensureTechnique(z.PatternTechnique,
a)};c._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.hasOccludees&&this._material.setParameters({hasOccludees:a.hasOccludees})};c.beginSlot=function(a){this._output!==p.ShaderOutput.Color&&this._output!==p.ShaderOutput.Alpha||this._updateOccludeeState(a);return this._updateParameters(a)};return e}(H),N=function(h){function e(){return h.apply(this,arguments)||this}q._inheritsLoose(e,h);var c=e.prototype;c.write=function(a,b,d,l,k){for(const m of this.vertexBufferLayout.fieldNames){b=
d.vertexAttributes.get(m);const f=d.indices.get(m);if(b&&f)switch(m){case n.VertexAttribute.POSITION:u.assert(3===b.size);var g=l.getField(m,r.BufferViewVec3f);g&&y.writePosition(f,b.data,a,g,k);break;case n.VertexAttribute.COLOR:u.assert(3===b.size||4===b.size);(g=l.getField(m,r.BufferViewVec4u8))&&y.writeColor(f,b.data,b.size,g,k);break;case n.VertexAttribute.UVMAPSPACE:u.assert(4===b.size);(g=l.getField(m,r.BufferViewVec4f))&&y.writeBufferVec4(f,b.data,g,k);break;case n.VertexAttribute.BOUNDINGRECT:u.assert(9===
b.size),(g=l.getField(m,r.BufferViewMat3f))&&this.writeBoundingRect(f,b.data,a,g,k)}}};c.writeBoundingRect=function(a,b,d,l,k){const g=l.typedBuffer;l=l.typedBufferStride;const m=a.length;k*=l;for(let A=0;A<m;++A){const v=9*a[A];var f=b[v];const B=b[v+1],C=b[v+2];g[k]=d[0]*f+d[4]*B+d[8]*C+d[12];g[k+1]=d[1]*f+d[5]*B+d[9]*C+d[13];g[k+2]=d[2]*f+d[6]*B+d[10]*C+d[14];for(f=3;9>f;++f)g[k+f]=b[v+f];k+=l}};return e}(K.DefaultBufferWriter),D=function(h){function e(){var c=h.apply(this,arguments)||this;c.color=
E.fromValues(1,1,1,1);c.writeDepth=!0;c.writeLinearDepth=!1;c.hasVertexColors=!1;c.polygonOffset=!1;c.hasSlicePlane=!1;c.cullFace=G.CullFaceOptions.None;c.hasOccludees=!1;c.style=L.Style.Cross;c.patternSpacing=10;c.lineWidth=1;c.draped=!0;return c}q._inheritsLoose(e,h);return e}(I.MaterialParameters);w.Parameters=D;w.PatternMaterial=x;Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});