// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/time ../../../../chunks/vec2f64 ../../../../chunks/vec4f64 ../core/shaderLibrary/ShaderOutput ../lib/AnimationTimer ../lib/Material ../lib/OrderIndependentTransparency ../lib/RenderSlot ./DefaultBufferWriter ./DefaultLayouts ./TriangleMaterial ./WaterGLMaterial ./WaterTechnique".split(" "),function(h,l,n,p,q,g,r,t,u,d,v,w,k,x,y){k=function(f){function e(b){b=f.call(this,b,new m)||this;b._configuration=new y.WaterTechniqueConfiguration;
b.animation=new r.AnimationTimer;return b}l._inheritsLoose(e,f);var a=e.prototype;a.getConfiguration=function(b,c){this._configuration.output=b;this._configuration.writeDepth=this.parameters.writeDepth;this._configuration.receiveShadows=this.parameters.receiveShadows;this._configuration.hasSlicePlane=this.parameters.hasSlicePlane;this._configuration.transparent=this.parameters.transparent;this._configuration.hasScreenSpaceReflections=this.parameters.hasScreenSpaceReflections;this._configuration.hasCloudsReflections=
this.parameters.hasCloudsReflections;this._configuration.isDraped=this.parameters.isDraped;this._configuration.transparencyPassType=c.transparencyPassType;this._configuration.enableOffset=c.camera.relativeElevation<u.OITPolygonOffsetLimit;this._configuration.hasMultipassTerrain=c.multipassTerrain.enabled;this._configuration.cullAboveGround=c.multipassTerrain.cullAboveGround;return this._configuration};a.update=function(b){this.animation.enabled=35E3>Math.sqrt(this.parameters.waveTextureRepeat/this.parameters.waveStrength)*
Math.min(b.camera.relativeElevation,b.camera.distance);b=this.animation.advance(b);this.setParameters({timeElapsed:n.secondsFromMilliseconds(this.animation.time)*this.parameters.animationSpeed},!1);return this.animation.enabled&&b};a.requiresSlot=function(b,c){switch(c){case g.ShaderOutput.Normal:return b===d.RenderSlot.DRAPED_WATER;case g.ShaderOutput.Color:if(this.parameters.isDraped)return b===d.RenderSlot.DRAPED_MATERIAL;break;case g.ShaderOutput.Alpha:break;case g.ShaderOutput.Highlight:return b===
d.RenderSlot.OPAQUE_MATERIAL||b===d.RenderSlot.DRAPED_MATERIAL;default:return!1}c=d.RenderSlot.OPAQUE_MATERIAL;this.parameters.transparent&&(c=this.parameters.writeDepth?d.RenderSlot.TRANSPARENT_MATERIAL:d.RenderSlot.TRANSPARENT_DEPTH_WRITE_DISABLED_MATERIAL);return b===c};a.createGLMaterial=function(b){return new x.WaterGLMaterial(b)};a.createBufferWriter=function(){return new v.DefaultBufferWriter(w.PositionUVLayout)};return e}(k.TriangleMaterial);let m=function(f){function e(){var a=f.apply(this,
arguments)||this;a.waveStrength=.06;a.waveTextureRepeat=32;a.waveDirection=p.fromValues(1,0);a.waveVelocity=.05;a.flowStrength=.015;a.flowOffset=-.5;a.animationSpeed=.35;a.timeElapsed=0;a.color=q.fromValues(0,0,0,0);a.transparent=!0;a.writeDepth=!0;a.hasSlicePlane=!1;a.isDraped=!1;a.receiveShadows=!0;a.hasScreenSpaceReflections=!1;a.hasCloudsReflections=!1;return a}l._inheritsLoose(e,f);return e}(t.MaterialParameters);h.WaterMaterial=k;h.WaterMaterialParameters=m;Object.defineProperty(h,Symbol.toStringTag,
{value:"Module"})});