// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/mathUtils ../../../../core/maybe ../../../../core/PooledArray ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4 ../../../../chunks/vec4f64 ../../../../geometry/ellipsoidUtils ../../../../geometry/support/aaBoundingRect ../../../../chunks/boundedPlane ../../../../geometry/support/ray ../../../../chunks/sphere ./deconflictorDebug ./enums ../../support/debugFlags ../../webgl-engine/lib/Camera ../../webgl-engine/lib/screenSizePerspectiveUtils ../../webgl-engine/lib/VertexAttribute ../../webgl-engine/materials/HUDMaterial ../../webgl-engine/materials/ScaleInfo".split(" "),
function(l,A,B,N,G,w,H,I,ka,la,O,P,Q,R,u,r,x,J,S,p,C,T,z,D,t,U,V,W,K,X,Y){function*L(g){if(Map.prototype.entries){g=g.entries();for(let k=g.next();!k.done;k=g.next())yield k.value[1]}else yield*g.values()}function*Z(g,k,h){k.clear();g.forEach((c,b)=>{const d=k.pushNew();d.id=b;d.visible=c.graphics3DGraphic.hasVisibilityFlag(t.VisibilityFlag.DECONFLICTION,h);d.prio=c.info?c.info[h].distance:Number.MAX_VALUE});yield;const a=k.iterableSort((c,b)=>c.visible!==b.visible?c.visible?-1:1:c.prio!==b.prio?
c.prio-b.prio:c.id-b.id);for(let c=a.next();!c.done;c=a.next())yield;k.forAll(c=>{const b=g.get(c.id);b&&(g.delete(c.id),g.set(c.id,b))});k.clear()}const n=r.create(),v=J.create(),y=J.create(),E=r.create(),aa=Q.create(),ba=z.create(),F=T.create(),ca=r.create(),da=p.create();let ea=function(){this.aabr=p.create();this.distance=0;this.visible=this.culled=!1};l.State=void 0;(function(g){g[g.Idle=0]="Idle";g[g.Process=1]="Process";g[g.Sort=2]="Sort";g[g.Deconflict=3]="Deconflict";g[g.NumStates=4]="NumStates"})(l.State||
(l.State={}));let M=function(){function g(){this.camera=new V.Camera;this.slicePlane=C.create();this.slicePlaneEnabled=!1}g.prototype.copyFrom=function(k){this.camera.copyFrom(k.camera);C.copy(k.slicePlane,this.slicePlane);this.slicePlaneEnabled=k.slicePlaneEnabled};return g}();l.Deconflictor=function(g){function k(a){a=g.call(this,a)||this;a._dirty=!1;a._runningViewState=new M;a._state=l.State.Idle;a._active=new Map;a._visible=new Map;a._iterators=new fa;a._accBinsNumX=15;a._accBinsNumY=20;a._accBinsSizeX=
0;a._accBinsSizeY=0;a._accBins=null;a.accNumTests=0;return a}A._inheritsLoose(k,g);var h=k.prototype;h.destroy=function(){this._active.clear();this._visible.clear();this._iterators=null};h.setDirty=function(){!this._dirty&&0<this._active.size&&(this._dirty=!0,this.notifyChange("updating"))};h.runTask=function(a){switch(this._state){case l.State.Idle:this._startUpdate(),a.madeProgress();case l.State.Process:if(this._state=l.State.Process,!this._processActiveGraphics(a))break;case l.State.Sort:if(this._state=
l.State.Sort,!this._sortVisibleGraphics(a))break;case l.State.Deconflict:if(this._state=l.State.Deconflict,!this._deconflictVisibleGraphics(a))break;default:D.drawAccelerationStruct(this,this._visible),this._state=l.State.Idle,this.notifyChange("updating")}};h.modifyGraphics=function(a,c){c?a.forEach(b=>this.addToActiveGraphics(b)):a.forEach(b=>this.removeFromActiveGraphics(b));this.setDirty()};h.layerSupportsDeconfliction=function(a){if(w.isNone(a)||"object3d"!==a.type)return!1;a=a.stageObject;return 1===
(a?a.geometries.length:0)&&a?.geometries[0]?.material instanceof X.HUDMaterial?!0:!1};h._startUpdate=function(){D.prepare(this.view);this._dirty=!1;this._runningViewState.copyFrom(this.viewState);const {fullWidth:a,fullHeight:c}=this._runningViewState.camera;this._initBins(a,c);this._resetIterators()};h.addToActiveGraphics=function(a){a.info[this.visibilityGroup]=new ea;this._active.set(a.graphics3DGraphic.graphic.uid,a);this.setDirty()};h.removeFromActiveGraphics=function(a){this._visible.delete(a.graphics3DGraphic.graphic.uid);
const c=a.graphics3DGraphic;c.destroyed||c.clearVisibilityFlag(t.VisibilityFlag.DECONFLICTION,this.visibilityGroup);delete a.info[this.visibilityGroup];this._active.delete(a.graphics3DGraphic.graphic.uid);this.setDirty()};h._processActiveGraphics=function(a){const c=this._ensureActiveGraphicsIterator(),b=P.invertOrIdentity(aa,this._runningViewState.camera.projectionMatrix),d="global"===this.view.viewingMode&&1===this.view.map.ground.opacity&&0<this._runningViewState.camera.relativeElevation?ba:null;
let f=0;w.isSome(d)&&(u.transformMat4(d,r.ZEROS,this._runningViewState.camera.viewMatrix),d[3]=S.getReferenceEllipsoid(this.view.spatialReference).radius,f=z.distanceToSilhouette(d,r.ZEROS));for(;!a.done;){a.madeProgress();var e=c.next();if(!0===e.done)return this._resetActiveGraphicsIterator(),!0;const m=(e=e.value)&&e.info[this.visibilityGroup];m&&(this._collectGraphics3DGraphics(e,b,d,f),m.culled?this._visible.delete(e.graphics3DGraphic.graphic.uid):this._visible.set(e.graphics3DGraphic.graphic.uid,
e))}return!1};h._sortVisibleGraphics=function(a){const c=this._ensureSortGraphicsIterator();for(;!a.done;){const b=c.next();a.madeProgress();if(!0===b.done)return this._resetSortGraphicsIterator(),!0}return!1};h._deconflictVisibleGraphics=function(a){const c=this._ensureVisibleGraphicsIterator(),b=this.visibilityGroup===t.VisibilityGroup.LABEL;for(;!a.done;){a.madeProgress();var d=c.next();if(!0===d.done)return this._resetVisibleGraphicsIterator(),!0;d=d.value;const e=d.info[this.visibilityGroup];
if(e&&!e.culled){var f=d.graphics3DGraphic;(f=(!b||f.isVisible())&&!this._isConflicted(d))&&this._addToBins(d);e.visible=f;this._setGraphicVisibility(d,f);D.drawPoly(e,f)}}return!1};h._resetIterators=function(){this._iterators.active=null;this._iterators.visible=null;this._iterators.sort=null};h._ensureActiveGraphicsIterator=function(){this._iterators.active||(this._iterators.active=L(this._active));return this._iterators.active};h._resetActiveGraphicsIterator=function(){this._iterators.active=null};
h._ensureVisibleGraphicsIterator=function(){this._iterators.visible||(this._iterators.visible=L(this._visible));return this._iterators.visible};h._resetVisibleGraphicsIterator=function(){this._iterators.visible=null};h._ensureSortGraphicsIterator=function(){this._iterators.sort||(this._iterators.sort=Z(this._visible,this._iterators.sortArray,this.visibilityGroup));return this._iterators.sort};h._resetSortGraphicsIterator=function(){this._iterators.sort=null};h._collectGraphics3DGraphics=function(a,
c,b,d){var f=a.graphics3DGraphic;if(!f.destroyed){var e=a.info[this.visibilityGroup];if(f.isVisible(t.VisibilityGroup.GRAPHIC,t.VisibilityFlag.DECONFLICTION)){var m=this.getGraphicsLayers(f);p.empty(e.aabr);f=null;for(const q of m)if(this.layerSupportsDeconfliction(q)){m=q.stageObject.geometries[0].material;if(w.isNone(f)){f=ha;this._getProjectionInfo(q,c,f);if(f.isOutsideScreen||this._isCulledBySlice(a,n)||w.isSome(b)&&this._isCulledByHorizon(f,b,d)){e.culled=!0;return}!U.TESTS_DISABLE_OPTIMIZATIONS&&
e.visible&&(f.distance*=.7)}this._expandBoundingRect(e,q,m,f)}w.isNone(f)?e.culled=!0:(e.distance=f.distance,e.culled=!1)}else e.culled=!0}};h._getProjectionInfo=function(a,c,b){const d=this._runningViewState.camera;a=a.stageObject;var f=a.geometries[0];const e=f.material;var m=z.getCenter(a.boundingVolumeWorldSpace.bounds);u.transformMat4(n,m,d.viewMatrix);m=f.vertexAttributes;f=m.get(K.VertexAttribute.NORMAL).data;m=m.get(K.VertexAttribute.AUXPOS1).data;e.applyShaderOffsetsView(n,f,a.transformation,
m,d,b.scaleInfo,n);x.set(v,n[0],n[1],n[2],1);x.transformMat4(y,v,d.projectionMatrix);u.scale(b.positionNDC,y,1/y[3]);e.applyShaderOffsetsNDC(b.positionNDC,m,d,b.positionNDC,E);b.distanceWithoutPolygonOffset=d.depthNDCToWorld(E[2]);b.distance=E[2]===b.positionNDC[2]?b.distanceWithoutPolygonOffset:d.depthNDCToWorld(b.positionNDC[2]);x.set(y,b.positionNDC[0],b.positionNDC[1],b.positionNDC[2],1);x.transformMat4(v,y,c);x.scale(v,v,1/v[3]);u.set(b.positionView,n[0],n[1],n[2])};h._isCulledByHorizon=function(a,
c,b){u.copy(F.direction,a.positionView);u.set(F.origin,0,0,0);return z.intersectRay(c,F,ca)?a.distanceWithoutPolygonOffset>b:!1};h._isCulledBySlice=function(a,c){return a.slicePlaneEnabled&&this._runningViewState.slicePlaneEnabled&&C.extrusionContainsPoint(this._runningViewState.slicePlane,c)};h._expandBoundingRect=function(a,c,b,{positionNDC:d,scaleInfo:f}){const e=this._runningViewState.camera;c=c.getScreenSize(ia);W.applyPrecomputedScaleFactor(c,f.factor,c);c[0]*=e.pixelRatio;c[1]*=e.pixelRatio;
b=p.offset(b.calculateRelativeScreenBounds(c,f.factorAlignment.scale,da),G.lerp(0,e.fullWidth,.5+.5*d[0]),G.lerp(0,e.fullHeight,.5+.5*d[1]));d=this.iconMarginFactor;0!==d&&(d*=Math.min(p.width(b),p.height(b)),b[0]-=d,b[1]-=d,b[2]+=d,b[3]+=d);p.expand(a.aabr,b,a.aabr)};h._isConflicted=function(a){const c=a.graphics3DGraphic.graphic.uid;a=a.info[this.visibilityGroup];for(let b=Math.floor(a.aabr[0]/this._accBinsSizeX);b<=Math.floor(a.aabr[2]/this._accBinsSizeX);b++)if(!(0>b||b>=this._accBinsNumX))for(let d=
Math.floor(a.aabr[1]/this._accBinsSizeY);d<=Math.floor(a.aabr[3]/this._accBinsSizeY);d++){if(0>d||d>=this._accBinsNumY)continue;const f=this._accBins[b][d];for(let e=0;e<f.length;e++){const m=f.data[e],q=m.info[this.visibilityGroup];if(q&&q.visible&&m.graphics3DGraphic.graphic.uid!==c&&(this.accNumTests++,p.intersects(q.aabr,a.aabr)))return!0}}return!1};h._initBins=function(a,c){if(null==this._accBins){this._accBins=[];for(var b=0;b<this._accBinsNumX;b++){this._accBins.push([]);var d=this._accBins[this._accBins.length-
1];for(let f=0;f<this._accBinsNumY;f++)d.push(new H)}}else for(b=0;b<this._accBinsNumX;b++)for(d=0;d<this._accBinsNumY;d++)this._accBins[b][d].clear();this._accBinsSizeX=a/this._accBinsNumX;this._accBinsSizeY=c/this._accBinsNumY;this.accNumTests=0};h._addToBins=function(a){var c=a.info[this.visibilityGroup],b=Math.floor(c.aabr[0]/this._accBinsSizeX);const d=Math.floor(c.aabr[2]/this._accBinsSizeX),f=Math.floor(c.aabr[1]/this._accBinsSizeY);for(c=Math.floor(c.aabr[3]/this._accBinsSizeY);b<=d;b++)if(!(0>
b||b>=this._accBinsNumX))for(let e=f;e<=c;e++)0>e||e>=this._accBinsNumY||this._accBins[b][e].push(a)};h._setGraphicVisibility=function(a,c){a=a.graphics3DGraphic;a.destroyed||(a.setVisibilityFlag(t.VisibilityFlag.DECONFLICTION,c,this.visibilityGroup),this.visibilityGroup===t.VisibilityGroup.LABEL&&this.view.labeler.setLabelGraphicVisibility(a,c))};A._createClass(k,[{key:"dirty",get:function(){return this._dirty}},{key:"state",get:function(){return this._state}},{key:"updating",get:function(){return this._state!==
l.State.Idle||this._dirty}},{key:"updatingProgress",get:function(){if(!this.updating)return 1;const a=this._state/l.State.NumStates;return this._dirty?.5*a:a}},{key:"running",get:function(){return this.view.ready&&null!=this.view.state&&this.updating}}]);return k}(N);B.__decorate([I.property({constructOnly:!0})],l.Deconflictor.prototype,"view",void 0);B.__decorate([I.property({type:Boolean,readOnly:!0})],l.Deconflictor.prototype,"updating",null);l.Deconflictor=B.__decorate([O.subclass("esri.views.3d.layers.graphics.Deconflictor")],
l.Deconflictor);let ja=function(){},fa=function(g=null,k=null,h=null){this.active=g;this.visible=k;this.sort=h;this.sortArray=new H({allocator:a=>a||new ja})};const ia=R.create(),ha=new (function(){function g(){this.positionView=r.create();this.positionNDC=r.create();this.distanceWithoutPolygonOffset=this.distance=0;this.scaleInfo=new Y.ScaleInfo}A._createClass(g,[{key:"isOutsideScreen",get:function(){const k=this.positionNDC;return-1>k[0]||-1>k[1]||-1>k[2]||1<=k[0]||1<=k[1]}}]);return g}());l.DeconflictorGraphic=
function(g,k){this.graphics3DGraphic=g;this.slicePlaneEnabled=k;this.info={}};l.DeconflictorViewState=M;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});