// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../core/asyncUtils ../../../../core/byteSizeEstimations ../../../../core/maybe ../../../../core/ObjectPool ../../../../chunks/vec2 ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/Polygon ../../../../geometry/projection ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/spatialReferenceUtils ../../../../layers/graphics/dehydratedFeatures ../../../../layers/graphics/featureConversionUtils ./enums ./featureExpressionInfoUtils".split(" "),
function(q,w,x,l,y,z,A,B,C,D,E,m,r,F,u,G,n,H){const v=new y(Array,p=>m.set(p,m.ZERO),null,10,5),I=r.create();return function(){function p(a,b,c,f,h){this.graphic=a;this.graphics3DSymbol=b;this.layers=c;this._labelLayers=[];this._auxiliaryLayers=[];var e=n.VisibilityFlag._COUNT;const k=Array(n.VisibilityGroup._COUNT);for(let g=0;g<k.length;g++)k[g]=Array(e);this._visibilityFlags=k;this._featureExpressionFeature=null;this._optimizedGeometry={geometry:null,hasZ:!1,hasM:!1};this._extent=null;this.isElevationSource=
!1;++b.referenced;this._featureExpressionFeature=h?H.createFeature(h,a,f):null;for(const g of c)l.isSome(g)&&(this.isElevationSource=this.isElevationSource||g.isElevationSource)}var d=p.prototype;d.initialize=function(a,b){this._layer=b;this._stage=a;this._forEachSymbolLayerGraphic(c=>{c.initialize(a,b);c.setVisibility(this.isVisible())})};d.destroy=function(){this._forEachSymbolLayerGraphic(a=>a.destroy());this._auxiliaryLayers=this.layers=null;--this.graphics3DSymbol.referenced;this.graphics3DSymbol=
null};d.clearLabelGraphics=function(){this._forEachLabelGraphic(a=>a.destroy());this._labelLayers.length=0};d.addLabelGraphic=function(a,b,c){this._labelLayers.push(a);a.initialize(b,c);a.setVisibility(this.isVisible(n.VisibilityGroup.LABEL))};d.addAuxiliaryGraphic=function(a){this._auxiliaryLayers.push(a);this._layer&&(a.initialize(this._stage,this._layer),a.setVisibility(this.isVisible()))};d.isVisible=function(a=n.VisibilityGroup.GRAPHIC,b){for(let c=0;c<=a;c++){const f=this._visibilityFlags[c];
for(let h=0;h<f.length;++h)if(!1===f[h]&&h!==b)return!1}return!0};d.hasVisibilityFlag=function(a,b){return null!=this._visibilityFlags[b][a]};d.setVisibilityFlag=function(a,b,c){const f=this.isVisible(c);this._visibilityFlags[c][a]=b;const h=this.isVisible(c);if(f===h)return!1;if(c===n.VisibilityGroup.LABEL)this._forEachLabelGraphic(e=>e.setVisibility(h));else{this._forEachSymbolLayerGraphic(k=>k.setVisibility(h));const e=this.isVisible(n.VisibilityGroup.LABEL);this._forEachLabelGraphic(k=>k.setVisibility(e))}return!0};
d.clearVisibilityFlag=function(a,b=n.VisibilityGroup.GRAPHIC){return this.setVisibilityFlag(a,void 0,b)};d.computeExtent=function(a){if(!this._extent){var b=this.graphic.geometry;if(l.isNone(b))return!1;this._extent=r.create();u.computeAABR(b,this._extent);b=b.spatialReference;if(!F.equals(b,a)&&!E.projectBoundingRect(this._extent,b,this._extent,a))return this._extent=null,!1}return!0};d.getAsOptimizedGeometry=function(a,b){if(l.isSome(this._optimizedGeometry.geometry)&&this._optimizedGeometry.hasZ===
a&&this._optimizedGeometry.hasM===b)return this._optimizedGeometry.geometry;this._optimizedGeometry.geometry=this._convertGraphicToOptimizedGeometry(this.graphic,a,b);this._optimizedGeometry.hasZ=a;this._optimizedGeometry.hasM=b;return this._optimizedGeometry.geometry};d._convertGraphicToOptimizedGeometry=function(a,b,c){a=a.geometry;if("mesh"===a.type||"extent"===a.type)a=D.fromExtent("mesh"===a.type?a.extent:a);return G.convertFromGeometry(a,b,c)};d.computeAttachmentOrigin=function(){const a={render:{origin:C.create(),
num:0},draped:{origin:A.create(),num:0}};for(const b of this.layers)l.isNone(b)||b.computeAttachmentOrigin(a);1<a.render.num&&B.scale(a.render.origin,a.render.origin,1/a.render.num);1<a.draped.num&&z.scale(a.draped.origin,a.draped.origin,1/a.draped.num);return a};d.getProjectedBoundingBox=function(){var a=q._asyncToGenerator(function*(b,c,f,h,e){e||(e={boundingBox:null,requiresDrapedElevation:!1,screenSpaceObjects:[]});e.boundingBox?m.empty(e.boundingBox):e.boundingBox=m.empty();e.requiresDrapedElevation=
!1;yield w.forEach(this.layers,function(){var k=q._asyncToGenerator(function*(g){if(!l.isNone(g)){var J="draped"===g.type?c:b,t=v.acquire();g=yield g.getProjectedBoundingBox(J,f,e.screenSpaceObjects,h,t);isFinite(g[2])&&isFinite(g[5])||(e.requiresDrapedElevation=!0);g&&m.expandWithAABB(e.boundingBox,t);v.release(t)}});return function(g){return k.apply(this,arguments)}}());return m.allFinite(e.boundingBox)||r.allFinite(m.toRect(e.boundingBox,I))?e:null});return function(b,c,f,h,e){return a.apply(this,
arguments)}}();d.needsElevationUpdates=function(){for(const a of this.layers)if(l.isSome(a)&&("object3d"===a.type||"lod-instance"===a.type)&&a.needsElevationUpdates)return!0;for(const a of this._labelLayers)if(a&&a.needsElevationUpdates)return!0;return!1};d.alignWithElevation=function(a,b,c){this._forEachRenderedGraphic(f=>{"object3d"!==f.type&&"lod-instance"!==f.type||f.alignWithElevation(a,b,this._featureExpressionFeature,c)})};d.alignWithAbsoluteElevation=function(a,b,c){this._forEachRenderedGraphic(f=>
{"object3d"===f.type&&f.alignWithAbsoluteElevation(a,b,c)})};d.addObjectStateSet=function(a,b){this._forEachSymbolLayerGraphic(c=>c.addObjectState(a,b))};d.removeObjectState=function(a){this._forEachSymbolLayerGraphic(b=>b.removeObjectState(a))};d._forEachGraphicList=function(a,b){a.forEach(c=>c&&b(c))};d._forEachSymbolLayerGraphic=function(a){this._forEachGraphicList(this.layers,a);this._forEachGraphicList(this._auxiliaryLayers,a)};d._forEachLabelGraphic=function(a){this._forEachGraphicList(this._labelLayers,
a)};d._forEachRenderedGraphic=function(a){this._forEachSymbolLayerGraphic(a);this._forEachLabelGraphic(a)};q._createClass(p,[{key:"labelLayers",get:function(){return this._labelLayers}},{key:"extent",get:function(){return this._extent}},{key:"destroyed",get:function(){return null==this.layers}},{key:"isDraped",get:function(){let a=!1;this._forEachSymbolLayerGraphic(b=>{"draped"===b.type&&(a=!0)});return a}},{key:"usedMemory",get:function(){let a=x.estimateAttributesObjectSize(this.graphic.attributes);
this._forEachSymbolLayerGraphic(b=>{const c=b.graphics3DSymbolLayer.complexity;l.isNone(c)||(b="draped"===b.type?c.memory.draped:c.memory,a+=b.bytesPerFeature,b.bytesPerCoordinate&&(a+=u.numVertices(this.graphic.geometry)*b.bytesPerCoordinate))});return a}}]);return p}()});