// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/earcut ../../../../chunks/vec4 ../../../../geometry/support/aaBoundingBox ./elevationAlignmentUtils ./ElevationContext ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ./lineUtils ./polygonUtils ../support/patternUtils ../support/uvUtils ../../support/engineContent/line ../../support/renderInfoUtils/polygon ../../webgl-engine/lib/DoubleArray ../../webgl-engine/lib/FloatArray ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/lib/VertexAttribute ../../webgl-engine/materials/lineStippleUtils ../../webgl-engine/materials/PatternMaterial ../../webgl-engine/materials/RibbonLineMaterial".split(" "),
function(x,t,F,f,G,y,z,h,n,H,I,J,u,K,L,r,A,B,C,D,w,v,M,E,N,O,P,Q){const R=["polyline","polygon","extent"];u=function(l){function m(a,b,c,g){a=l.call(this,a,b,c,g)||this;a._needsUV=!1;a._hasOutline=!1;return a}t._inheritsLoose(m,l);var d=m.prototype;d.doLoad=function(){var a=t._asyncToGenerator(function*(){});return function(){return a.apply(this,arguments)}}();d._ensureMaterials=function(){this._ensureFillMaterial();this._ensureOutlineMaterial()};d._ensureFillMaterial=function(){if(!f.isSome(this._material)){var a=
f.get(this.symbolLayer,"material","color");a=this._getCombinedOpacityAndColor(a);this._material=A.createMaterial(this.symbolLayer,{color:a,transparent:1>a[3]||this.needsDrivenTransparentPass,polygonOffset:!1,hasVertexColors:!0,writeLinearDepth:!0,hasSlicePlane:this._context.slicePlaneEnabled},{isDraped:this.draped});this._needsUV=this._material instanceof P.PatternMaterial;this._context.stage.add(this._material)}};d._ensureOutlineMaterial=function(){const a=this.symbolLayer.outline;!f.isSome(this._outlineMaterial)&&
this._isValidOutline(a)&&(this._hasOutline=!0,this._outlineMaterial=(b=>{const c=O.getStipplePatternForLinePattern(a.pattern);return new Q.RibbonLineMaterial({width:b,color:this._getOutlineColor(),hasPolygonOffset:!0,hasSlicePlane:this._context.slicePlaneEnabled,isClosed:!0,stipplePattern:c,stippleScaleWithLineWidth:!0,cap:L.parseCapType(a.patternCap||"butt")})})(G.pt2px(a.size)),this._context.stage.add(this._outlineMaterial))};d._isValidOutline=function(a){return f.isSome(a)&&null!=a.size&&0<a.size&&
f.isSome(a.color)&&(f.isNone(a.pattern)||"style"!==a.pattern.type||"none"!==a.pattern.style)};d.destroy=function(){l.prototype.destroy.call(this);this._context.stage.remove(this._material);this._material=null;this._context.stage.remove(this._outlineMaterial);this._outlineMaterial=null};d.createGraphics3DGraphic=function(a){const b=a.graphic;if(!this._validateGeometry(b.geometry,R,this.symbolLayer.type))return null;a=this._getVertexOpacityAndColor(a.renderingInfo,255);const c=this.setGraphicElevationContext(b,
new H.ElevationContext);this.ensureDrapedStatus("on-the-ground"===c.mode);this._ensureMaterials();return this.draped?this._createAsOverlay(b,a):this._createAs3DShape(b,a,c)};d.layerOpacityChanged=function(){if(f.isSome(this._material)){var a=this._material.parameters.color,b=f.get(this.symbolLayer,"material","color");b=this._getCombinedOpacity(b);this._material.setParameters({color:[a[0],a[1],a[2],b],transparent:1>b||this.needsDrivenTransparentPass})}f.isSome(this._outlineMaterial)&&(a=this._outlineMaterial.parameters.color,
this._outlineMaterial.setParameters({color:[a[0],a[1],a[2],this._getOutlineOpacity()]}))};d.layerElevationInfoChanged=function(a,b,c){const g=this._elevationContext.mode;c=n.elevationModeChangeUpdateType(m.elevationModeChangeTypes,c,g);if(c!==n.SymbolUpdateType.UPDATE)return c;const e=n.needsElevationUpdates2D(g);return this.updateGraphics3DGraphicElevationInfo(a,b,()=>e)};d.slicePlaneEnabledChanged=function(){f.isSome(this._material)&&this._material.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});
f.isSome(this._outlineMaterial)&&this._outlineMaterial.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});return!0};d.physicalBasedRenderingChanged=function(){return!0};d.pixelRatioChanged=function(){return!0};d.skipHighSymbolLodsChanged=function(){return!0};d._createAs3DShape=function(a,b,c){const g=r.geometryAsPolygon(a.geometry);if(f.isNone(g))return null;var e=D.geometryToRenderInfo(g,this._context.elevationProvider,this._context.renderCoordsHelper,c);b=new S(e,b,this._context.layer.uid,
a.uid);e=b.renderData.position.length/3;this._needsUV&&(b.uvMapSpace=v.newFloatArray(4*e,!0),b.boundingRect=w.newDoubleArray(9*e,!0),B.createMapSpaceUVCoords(b.uvMapSpace,b.boundingRect,b.renderData.position,this._context.renderCoordsHelper));b.objectAndLayerIdColor=this._context.stage.renderView?.getObjectAndLayerIdColor(b);this._createAs3DShapeFill(b);this._hasOutline&&this._createAs3DShapeOutline(b);this._logGeometryCreationWarnings(b.renderData,g.rings,"rings","FillSymbol3DLayer");if(0===b.outGeometries.length)return null;
a=new M.Object3D({geometries:b.outGeometries,castShadow:!1,metadata:{layerUid:this._context.layer.uid,graphicUid:a.uid}});a=new J.Graphics3DObject3DGraphicLayer(this,a,b.outGeometries,null,null,A.uvElevationAligner,c);a.alignedSampledElevation=b.renderData.sampledElevation;a.needsElevationUpdates=n.needsElevationUpdates2D(c.mode);return a};d._createAs3DShapeFill=function(a){var b=a.renderData.polygons;for(const {position:c,mapPositions:g,holeIndices:e,index:p,count:q}of b){if(f.isSome(this._context.clippingExtent)&&
(h.empty(k),h.expandWithBuffer(k,g),!h.intersectsClippingArea(k,this._context.clippingExtent)))continue;b=y.earcut(g,e,3);0!==b.length&&(b=r.createColorGeometry({material:f.unwrap(this._material),indices:b,mapPositions:g,attributeData:{position:c,color:a.color,uvMapSpace:this._needsUV?v.floatSubArray(a.uvMapSpace,4*p,4*q):null,boundingRect:this._needsUV?w.doubleSubArray(a.boundingRect,9*p,9*q):null,objectAndLayerIdColor:a.objectAndLayerIdColor}}),a.outGeometries.push(b))}};d._createAs3DShapeOutline=
function(a){if(this._hasOutline){var b=a.renderData.outlines;for(let c=0;c<b.length;++c){const {mapPositions:g,position:e}=b[c];if(f.isSome(this._context.clippingExtent)&&(h.empty(k),h.expandWithBuffer(k,g),!h.intersectsClippingArea(k,this._context.clippingExtent)))continue;const p=C.createGeometry(f.unwrap(this._outlineMaterial),{overlayInfo:null,removeDuplicateStartEnd:!0,mapPositions:g,attributeData:{position:e}},a.objectAndLayerIdColor),q=p.vertexAttributes.get(N.VertexAttribute.POSITION);q.data===
e&&(q.data=w.doubleArrayFrom(e));a.outGeometries.push(p)}}};d._createAsOverlay=function(a,b){const c=r.geometryAsPolygon(a.geometry);if(f.isNone(c))return null;f.unwrap(this._material).renderPriority=this._renderPriority+this._renderPriorityStep/2;f.isSome(this._outlineMaterial)&&(this._outlineMaterial.renderPriority=this._renderPriority);const g=D.geometryToRenderInfoDraped(c,this._context.overlaySR);a=new T(g,b,this._context.layer.uid,a.uid);b=a.renderData.position.length/3;this._needsUV&&(a.uvMapSpace=
v.newFloatArray(4*b,!0),B.createMapSpaceUVCoordsDraped(a.uvMapSpace,a.renderData.position,this._context.overlaySR,this._context.graphicsCoreOwner.view.state.viewingMode));a.outBoundingBox=h.empty();a.objectAndLayerIdColor=this._context.stage.renderView?.getObjectAndLayerIdColor(a);this._createAsOverlayFill(a);this._hasOutline&&this._createAsOverlayOutline(a);this._logGeometryCreationWarnings(a.renderData,c.rings,"rings","FillSymbol3DLayer");return 0===a.outGeometries.length?null:new I(this,a.outGeometries,
a.outBoundingBox,this._context.drapeSourceRenderer)};d._createAsOverlayFill=function(a){var b=a.renderData.polygons;for(const {position:g,holeIndices:e,index:p,count:q}of b)if(b=h.empty(k),h.expandWithBuffer(b,g),h.intersectsClippingArea(b,this._context.clippingExtent)){var c=y.earcut(g,e,3);0!==c.length&&(h.expandWithAABB(a.outBoundingBox,b),c=r.createColorGeometry({material:f.unwrap(this._material),indices:c,attributeData:{position:g,color:a.color,uvMapSpace:this._needsUV?v.floatSubArray(a.uvMapSpace,
4*p,4*q):null,objectAndLayerIdColor:a.objectAndLayerIdColor}}),c=new E.RenderGeometry(c,a),z.set(c.boundingSphere,.5*(b[0]+b[3]),.5*(b[1]+b[4]),0,.5*Math.sqrt((b[3]-b[0])*(b[3]-b[0])+(b[4]-b[1])*(b[4]-b[1]))),a.outGeometries.push(c))}};d._createAsOverlayOutline=function(a){if(this._hasOutline){var b=a.renderData.outlines;for(let g=0;g<b.length;++g){var {position:c}=b[g];h.empty(k);h.expandWithBuffer(k,c);if(!h.intersectsClippingArea(k,this._context.clippingExtent))continue;h.expandWithAABB(a.outBoundingBox,
k);c=C.createGeometry(f.unwrap(this._outlineMaterial),{overlayInfo:{spatialReference:this._context.overlaySR,renderCoordsHelper:this._context.renderCoordsHelper},removeDuplicateStartEnd:!0,attributeData:{position:c}},a.objectAndLayerIdColor);c=new E.RenderGeometry(c,a);const e=k;z.set(c.boundingSphere,.5*(e[0]+e[3]),.5*(e[1]+e[4]),0,.5*Math.sqrt((e[3]-e[0])*(e[3]-e[0])+(e[4]-e[1])*(e[4]-e[1])));a.outGeometries.push(c)}}};d._getOutlineOpacity=function(){const a=f.get(this.symbolLayer,"outline","color");
return(this.draped?1:this._getLayerOpacity())*(f.isSome(a)?a.a:0)};d._getOutlineColor=function(){const a=f.get(this.symbolLayer,"outline","color"),b=this._getOutlineOpacity();return K.mixinColorAndOpacity(f.isSome(a)?F.toUnitRGB(a):null,b)};d.test=function(){return{...l.prototype.test.call(this),createAsOverlay:(a,b)=>this._createAsOverlay(a,b),createAs3DShape:(a,b,c)=>this._createAs3DShape(a,b,c)}};return m}(u.Graphics3DSymbolLayer);u.elevationModeChangeTypes={definedChanged:n.SymbolUpdateType.RECREATE,
staysOnTheGround:n.SymbolUpdateType.NONE,onTheGroundChanged:n.SymbolUpdateType.RECREATE};const k=h.create();let S=function(l){function m(d,a,b,c){d=l.call(this,d,b,c)||this;d.color=a;return d}t._inheritsLoose(m,l);return m}(r.PolygonCreationDataBase),T=function(l){function m(d,a,b,c){d=l.call(this,d,b,c)||this;d.color=a;return d}t._inheritsLoose(m,l);return m}(r.PolygonCreationDataBase);x.Graphics3DPolygonFillSymbolLayer=u;Object.defineProperty(x,Symbol.toStringTag,{value:"Module"})});