// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../core/has ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4f64 ../../../../geometry/projection ../../../../geometry/support/aaBoundingBox ../../../../symbols/support/ObjectSymbol3DLayerResource ../../../../symbols/support/symbolLayerUtils3D ./ElevationAligners ./elevationAlignmentUtils ./ElevationContext ./Graphics3DLodInstanceGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ./interfaces ./Loadable ./lodResourceUtils ./objectResourceUtils ./pointUtils ./primitiveObjectSymbolUtils ./symbolComplexity ../support/FastSymbolUpdates ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/VertexAttribute ../../webgl-engine/lib/lodRendering/LodRenderer ../../webgl-engine/lib/lodRendering/LodResources ../../webgl-engine/materials/DefaultMaterial".split(" "),
function(V,z,R,W,h,da,X,I,Y,v,n,A,Z,w,ea,J,fa,K,ha,ia,S,G,L,ja,ka,la,M,aa,ma,B,N,na,oa,y,pa){let ba=function(C,D,k,b,a,c,d,e,f,g,m,l){this.lodResources=C;this.lodRenderer=D;this.stageResources=k;this.originalMaterialParameters=b;this.resourceSize=a;this.isEsriSymbolResource=c;this.isWosr=d;this.resourceBoundingBox=e;this.symbolSize=f;this.extentPadding=g;this.physicalBasedRenderingEnabled=m;this.pivotOffset=l};S=function(C){function D(b,a,c,d){b=C.call(this,b,a,c,d)||this;b._resources=null;b._optionalFields=
[];b._instanceIndexToGraphicUid=new Map;b._hasLoadedPBRTextures=!1;b._disposeResourceHandles=[];b.ensureDrapedStatus(!1);b._hasLoadedPBRTextures=c.physicalBasedRenderingEnabled;return b}z._inheritsLoose(D,C);var k=D.prototype;k.getCachedSize=function(){const [b,a,c]=h.isSome(this._resources)?this._resources.symbolSize:[1,1,1];return{width:b,depth:a,height:c}};k.doLoad=function(){var b=z._asyncToGenerator(function*(a){if(!this._drivenProperties.size&&G.validateSymbolLayerSize(this.symbolLayer))throw Error();
const c=this.symbolLayer;this._resources=this._isPrimitive?yield this._createResourcesForPrimitive(c.resource?c.resource.primitive:ea.defaultPrimitive,a):yield this._createResourcesForUrl(c.resource.href,a);this.layerOpacityChanged();this.slicePlaneEnabledChanged();this.physicalBasedRenderingChanged();this.complexity=this.computeComplexity()});return function(a){return b.apply(this,arguments)}}();k._setMaterialTransparencyParams=function(b,a=h.get(this.symbolLayer,"material","color")){a=this._getCombinedOpacity(a);
const c=1>a||this.needsDrivenTransparentPass;b.transparent=c;b.opacity=a;b.cullFace=c?N.CullFaceOptions.None:N.CullFaceOptions.Back;return b};k._createResourcesForPrimitive=function(){var b=z._asyncToGenerator(function*(a,c){if(!aa.isValidPrimitive(a))throw Error(`Unknown object symbol primitive: ${a}`);var d=this.symbolLayer;const e=w.create(J.objectSymbolLayerPrimitiveBoundingBox(a)),f=n.fromArray(w.size(e)),g=n.fromArray(J.objectSymbolLayerSizeWithResourceSize(f,d)),m=v.length(g);var l={usePBR:this._context.physicalBasedRenderingEnabled,
isSchematic:!0,ambient:n.ONES,diffuse:n.ONES,hasSlicePlane:this._context.slicePlaneEnabled,hasSliceHighlight:!1,castShadows:this.symbolLayer.castShadows,offsetTransparentBackfaces:!this.symbolLayer.isPrimitive};const p=!!l.usePBR;this._setMaterialTransparencyParams(l);const q=this.symbol;if("point-3d"===q.type&&q.verticalOffset){const {screenLength:x,minWorldLength:t,maxWorldLength:u}=q.verticalOffset;l.verticalOffset={screenLength:X.pt2px(x),minWorldLength:t||0,maxWorldLength:h.isSome(u)?u:Infinity};
l.castShadows=!1}this._context.screenSizePerspectiveEnabled&&(l.screenSizePerspective=this._context.sharedResources.screenSizePerspectiveSettings);this._drivenProperties.color?l.externalColor=A.ONES:(d=h.isSome(d.material)?d.material.color:null,d=h.isSome(d)?R.toUnitRGBA(d):A.ONES,l.externalColor=d);this._fastUpdates=B.initFastSymbolUpdatesState(this._context.renderer,this._fastVisualVariableConvertOptions(e,g,f,h.none));l.instanced=["transformation"];this._fastUpdates.enabled?(Object.assign(l,this._fastUpdates.materialParameters),
l.instanced.push("featureAttribute"),this._optionalFields.push("featureAttribute")):this._hasPerInstanceColor()&&(l.instanced.push("color"),this._optionalFields.push("color"));W("enable-feature:objectAndLayerId-rendering")&&(l.instanced.push("objectAndLayerIdColor"),this._optionalFields.push("objectAndLayerIdColor"));l=new pa.DefaultMaterial(l);l=aa.primitiveLodResources(a,l);if(!l)throw Error(`Unknown object symbol primitive: ${a}`);a=y.materialsFromLodResources(l).map(x=>({opacity:1,transparent:x.parameters.transparent}));
d=yield this._createStageResources(l,p,c);c=yield this._createLodRenderer(l,c);return new ba(l,c,d,a,f,!1,!1,e,g,m,p,h.none)});return function(a,c){return b.apply(this,arguments)}}();k._createResourcesForUrl=function(){var b=z._asyncToGenerator(function*(a,c){var d=["transformation"],e={materialParamsMixin:{instanced:d,hasSlicePlane:this._context.slicePlaneEnabled,castShadows:this.symbolLayer.castShadows},streamDataRequester:this._context.streamDataRequester,cache:this._context.sharedResources.objectResourceCache};
this._fastUpdates=B.initFastSymbolUpdatesState(this._context.renderer,this._fastVisualVariableConvertOptions(h.none,h.none,h.none,h.none));this._fastUpdates.enabled?(Object.assign(e.materialParamsMixin,this._fastUpdates.materialParameters),d.push("featureAttribute"),this._optionalFields.push("featureAttribute")):this._hasPerInstanceColor()&&(d.push("color"),this._optionalFields.push("color"));W("enable-feature:objectAndLayerId-rendering")&&(d.push("objectAndLayerIdColor"),this._optionalFields.push("objectAndLayerIdColor"));
d=this.symbol;if("point-3d"===d.type&&d.verticalOffset){const {screenLength:r,minWorldLength:E,maxWorldLength:H}=d.verticalOffset;e.materialParamsMixin.verticalOffset={screenLength:X.pt2px(r),minWorldLength:E||0,maxWorldLength:h.isSome(H)?H:Infinity};e.materialParamsMixin.castShadows=!1}e.signal=c;e.usePBR=this._context.physicalBasedRenderingEnabled;e.skipHighLods=this._context.skipHighSymbolLods;d=e.usePBR;var f=yield la.fetch(a,e);a=f.isEsriSymbolResource;e=f.isWosr;const g=ka.makeLodResources(f.lods);
g.levels.sort((r,E)=>r.minScreenSpaceRadius-E.minScreenSpaceRadius);const m=this._context,l=this._getExternalColorParameters(this.symbolLayer.material);var p=h.get(this.symbolLayer,"material","color");const q=this._getCombinedOpacity(p,{hasIntrinsicColor:!0}),x=this.needsDrivenTransparentPass;var t=y.materialsFromLodResources(g);p=y.materialsFromLodResources(g).map(r=>({opacity:r.parameters.opacity||1,transparent:r.parameters.transparent}));t.forEach(r=>{const E=r.parameters;r.setParameters(l);const H=
E.opacity*q;r.setParameters({opacity:H,transparent:1>H||x||E.transparent});m.screenSizePerspectiveEnabled&&r.setParameters({screenSizePerspective:m.sharedResources.screenSizePerspectiveSettings})});f=f.referenceBoundingBox;const u=n.fromArray(w.size(f)),O=n.fromArray(g.levels[0].pivotOffset),T=n.fromArray(J.objectSymbolLayerSizeWithResourceSize(u,this.symbolLayer)),qa=v.length(T);B.updateFastSymbolUpdatesState(this._fastUpdates,this._context.renderer,this._fastVisualVariableConvertOptions(f,T,u,O))&&
t.forEach(r=>r.setParameters(this._fastUpdates.materialParameters));t=yield this._createStageResources(g,d,c);c=yield this._createLodRenderer(g,c);return new ba(g,c,t,p,u,a,e,f,T,qa,d,O)});return function(a,c){return b.apply(this,arguments)}}();k._addDisposeResource=function(b){this._disposeResourceHandles.push(b)};k._createStageResources=function(){var b=z._asyncToGenerator(function*(a,c,d){const e=this._context.stage,f=y.materialsFromLodResources(a);c!==this._context.physicalBasedRenderingEnabled&&
this.physicalBasedRenderingChanged();e.addMany(f);this._addDisposeResource(()=>e.removeMany(f));const g=y.texturesFromLodResources(a);e.addMany(g);this._addDisposeResource(()=>e.removeMany(g));yield e.load(g,d);da.throwIfAborted(d);const m=y.geometriesFromLodResources(a);e.addMany(m);this._addDisposeResource(()=>e.removeMany(m));return{materials:f,textures:g,geometries:m}});return function(a,c,d){return b.apply(this,arguments)}}();k._createLodRenderer=function(){var b=z._asyncToGenerator(function*(a,
c){const d=this._context.stage,e=new oa.LodRenderer({symbol:a,optionalFields:this._optionalFields,metadata:{layerUid:this._context.layer.uid,graphicUid:f=>this._instanceIndexToGraphicUid.get(f),notifyGraphicGeometryChanged:f=>this._context.notifyGraphicGeometryChanged(this._instanceIndexToGraphicUid.get(f)),notifyGraphicVisibilityChanged:f=>this._context.notifyGraphicVisibilityChanged(this._instanceIndexToGraphicUid.get(f))},shaderTransformation:this._fastUpdates.enabled?{applyTransform:(f,g,m)=>
{f.getFeatureAttribute(g,P);I.copy(m,B.evaluateModelTransform(this._fastUpdates.materialParameters,P,m))},scaleFactor:(f,g,m)=>{g.getFeatureAttribute(m,P);return B.evaluateModelTransformScale(f,this._fastUpdates.materialParameters,P)}}:null},this._context.scheduler);e.slicePlaneEnabled=this._context.slicePlaneEnabled;this._addDisposeResource(()=>{d.removeRenderPlugin(e);e.destroy()});yield d.addRenderPlugin(e.slots,e,c);return e});return function(a,c){return b.apply(this,arguments)}}();k._getExternalColorParameters=
function(b){const a={};this._drivenProperties.color?a.externalColor=A.ONES:h.isSome(b)&&h.isSome(b.color)?a.externalColor=R.toUnitRGBA(b.color):(a.externalColor=A.ONES,a.colorMixMode="ignore");return a};k.destroy=function(){C.prototype.destroy.call(this);this._cleanupResources()};k._cleanupResources=function(){this._disposeResourceHandles.forEach(b=>b());this._disposeResourceHandles.length=0;this._resources=null};k.createGraphics3DGraphic=function(b){const a=b.graphic;if(!this._validateGeometry(a.geometry))return null;
const c=M.placePointOnGeometry(a.geometry);if(h.isNone(c))return this.logger.warn(`unsupported geometry type for icon symbol: ${a.geometry.type}`),null;const d=this.setGraphicElevationContext(a,new ha.ElevationContext);return this._createAs3DShape(a,c,b.renderingInfo,d,a.uid,b.layer.uid)};k.notifyDestroyGraphicLayer=function(b){this._instanceIndexToGraphicUid.delete(b.instanceIndex)};k.graphicLayerToGraphicId=function(){return 0};k.layerOpacityChanged=function(){if(!h.isNone(this._resources)){var b=
this._drivenProperties.opacity,a=!this._isPrimitive,c=this._resources.stageResources.materials,d=this._resources.originalMaterialParameters;for(let g=0;g<c.length;g++){const m=c[g];var e=h.get(this.symbolLayer,"material","color"),f=d[g];e=this._getCombinedOpacity(e,{hasIntrinsicColor:a})*f.opacity;f=1>e||b||f.transparent;m.setParameters({opacity:e,transparent:f});this._isPrimitive&&m.setParameters({cullFace:f?N.CullFaceOptions.None:N.CullFaceOptions.Back})}}};k.layerElevationInfoChanged=function(b,
a){return this.updateGraphics3DGraphicElevationInfo(b,a,K.needsElevationUpdates3D)};k.slicePlaneEnabledChanged=function(){if(h.isNone(this._resources))return!0;this._resources.lodRenderer.slicePlaneEnabled=this._context.slicePlaneEnabled;for(const b of this._resources.stageResources.materials)b.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});return!0};k.physicalBasedRenderingChanged=function(){if(h.isNone(this._resources))return!0;const {stageResources:b,isWosr:a}=this._resources;for(const c of b.materials)this._isPrimitive?
c.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0}):a||c.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!1});return!1===this._hasLoadedPBRTextures&&!0===this._context.physicalBasedRenderingEnabled?(this._hasLoadedPBRTextures=!0,!1):!0};k.pixelRatioChanged=function(){return!0};k.skipHighSymbolLodsChanged=function(){return!1};k.applyRendererDiff=function(b,a){if(h.isNone(this._resources))return L.ApplyRendererDiffResult.Recreate_Symbol;
const {stageResources:{materials:c},lodRenderer:d,resourceBoundingBox:e,symbolSize:f,resourceSize:g,pivotOffset:m}=this._resources;for(const l in b.diff)switch(l){case "visualVariables":if(B.updateFastSymbolUpdatesState(this._fastUpdates,a,this._fastVisualVariableConvertOptions(e,f,g,m))){for(const p of c)p.setParameters(this._fastUpdates.materialParameters);d.notifyShaderTransformationChanged()}else return L.ApplyRendererDiffResult.Recreate_Symbol;break;default:return L.ApplyRendererDiffResult.Recreate_Symbol}return L.ApplyRendererDiffResult.Fast_Update};
k.computeComplexity=function(){if(h.isNone(this._resources))return C.prototype.computeComplexity.call(this);var b=this._resources.lodResources;const a=y.geometriesFromLodLevelResources(b.levels[0]).reduce((e,f)=>e+f.indices.get(na.VertexAttribute.POSITION).length,0)/3,c=e=>Array.from(e.vertexAttributes.values()).reduce((f,g)=>f+(g.data.buffer?.byteLength??0),0)+Array.from(e.indices.values()).reduce((f,g)=>f+(Array.isArray(g)?12*g.length:g.buffer.byteLength),0);var d=y.texturesFromLodResources(b).reduce((e,
f)=>e+(f.params.encoding&&"image/ktx2"===f.params.encoding?f.estimatedTexMemRequired:f.estimatedTexMemRequired/4),0);b=y.geometriesFromLodResources(b).reduce((e,f)=>e+c(f),0);d+=b;d={...ma.defaultSymbolLayerMemoryComplexity(this.symbol,this.symbolLayer),resourceBytes:d};return{primitivesPerFeature:a,primitivesPerCoordinate:0,drawCallsPerFeature:0,estimated:!1,memory:d}};k._hasLodRenderer=function(){return h.isSome(this._resources)};k._createAs3DShape=function(b,a,c,d,e,f){if(!this._hasLodRenderer()||
h.isNone(this._resources))return null;b=this.getFastUpdateAttrValues(b);const g=!this._fastUpdates.enabled&&this._hasPerInstanceColor()?G.mixinColorAndOpacity(c.color,c.opacity):null;var m=this._context.clippingExtent;Z.projectPointToVector(a,F,this._context.elevationProvider.spatialReference);if(h.isSome(m)&&!w.containsPoint(m,F))return null;m=this._requiresTerrainElevation(d);const l=this._computeGlobalTransform(a,d,U,Q);c=this._computeLocalTransform(this._resources,this.symbolLayer,c,ca);const p=
this._resources.lodRenderer.instanceData,q=p.addInstance();this._instanceIndexToGraphicUid.set(q,e);p.setLocalTransform(q,c,!1);p.setGlobalTransform(q,l);b&&p.setFeatureAttribute(q,b);g&&p.setColor(q,g);h.isSome(this._context.stage.renderView.objectAndLayerIdRenderHelper)&&p.setObjectAndLayerIdColor(q,this._context.stage.renderView.objectAndLayerIdRenderHelper.getObjectAndLayerIdColor({graphicUid:e,layerUid:f}));e=new ia(this,q,fa.perLodInstanceElevationAligner,d);m&&(e.alignedSampledElevation=Q.sampledElevation);
e.needsElevationUpdates=K.needsElevationUpdates3D(d.mode);M.extendPointGraphicElevationContext(e,a,this._context.elevationProvider);return e};k._computeGlobalTransform=function(b,a,c,d){K.evaluateElevationInfoAtPoint(b,this._context.elevationProvider,a,this._context.renderCoordsHelper,d);F[0]=b.x;F[1]=b.y;F[2]=d.z;Z.computeTranslationToOriginAndRotation(b.spatialReference,F,c,this._context.renderCoordsHelper.spatialReference);return c};k._computeLocalTransform=function(b,a,c,d){I.identity(d);this._applyObjectRotation(c,
!1,d);this._applyObjectRotation(a,!0,d);this._applyObjectScale(b,c,d);this._applyAnchor(b,a,d);return d};k._applyObjectScale=function(b,a,c){this._fastUpdates.enabled&&this._fastUpdates.requiresShaderTransformation||(b=G.computeObjectScale(this._drivenProperties.size&&a.size?a.size:b.symbolSize,b.symbolSize,b.resourceSize,this._context.renderCoordsHelper.unitInMeters),1===b[0]&&1===b[1]&&1===b[2]||I.scale(c,c,b))};k.prepareSymbolLayerPatch=function(b){if("partial"===b.diff.type){var a=b.diff.diff;
this._preparePatchTransform(b,a);this._preparePatchColor(b,a)}};k.updateGeometry=function(b,a){if(h.isNone(this._resources))return!0;const c=a&&M.placePointOnGeometry(a);if(h.isNone(c))return!1;a=this.getGeometryElevationMode(a);if(b.elevationContext.mode!==a)return!1;this._computeGlobalTransform(c,b.elevationContext,U,Q);this._requiresTerrainElevation(b.elevationContext)&&(b.alignedSampledElevation=Q.sampledElevation);this._resources.lodRenderer.instanceData.setGlobalTransform(b.instanceIndex,U,
!0);M.extendPointGraphicElevationContext(b,c,this._context.elevationProvider);return!0};k._preparePatchTransform=function(b,a){if((a.heading||a.tilt||a.roll||a.width||a.height||a.depth||a.anchor||a.anchorPosition)&&!h.isNone(this._resources)){var c=(t,u,O)=>h.unwrapOr(null!=t&&"complete"===t.type?t.newValue:u,O),d=c(a.heading,this.symbolLayer.heading,0),e=c(a.tilt,this.symbolLayer.tilt,0),f=c(a.roll,this.symbolLayer.roll,0),g=c(a.width,this.symbolLayer.width,void 0),m=c(a.height,this.symbolLayer.height,
void 0),l=c(a.depth,this.symbolLayer.depth,void 0),p=c(a.anchor,this.symbolLayer.anchor,void 0);c=c(a.anchorPosition,this.symbolLayer.anchorPosition,void 0);delete a.heading;delete a.tilt;delete a.roll;delete a.width;delete a.height;delete a.depth;delete a.anchor;delete a.anchorPosition;var q={heading:d,tilt:e,roll:f,anchor:p,anchorPosition:c},x=this._resources;this.loadStatus===ja.LoadStatus.LOADED&&b.symbolLayerStatePatches.push(()=>{x.symbolSize=n.fromArray(J.objectSymbolLayerSizeWithResourceSize(x.resourceSize,
{width:g,height:m,depth:l,isPrimitive:this.symbolLayer.isPrimitive}))});b.graphics3DGraphicPatches.push((t,u)=>{u=this._computeLocalTransform(x,q,u,ca);x.lodRenderer.instanceData.setLocalTransform(t.instanceIndex,u,!0)})}};k._preparePatchColor=function(b,a){if(a.material&&"partial"===a.material.type&&(a=a.material.diff,a.color&&"complete"===a.color.type&&null!=a.color.newValue&&null!=a.color.oldValue)){var c=a.color.newValue,d=h.isSome(c)?R.toUnitRGBA(c):A.ONES;delete a.color;var e=this._resources;
h.isNone(e)||b.graphics3DGraphicPatches.push(f=>{this._hasPerInstanceColor()?(e.lodRenderer.instanceData.setColor(f.instanceIndex,d),f=this._setMaterialTransparencyParams({},c)):f=this._setMaterialTransparencyParams({externalColor:d},c);for(const g of e.stageResources.materials)g.setParameters(f)})}};k._requiresTerrainElevation=function(b){return"absolute-height"!==b.mode};k._applyObjectRotation=function(b,a,c){if(!(this._fastUpdates.enabled&&this._fastUpdates.requiresShaderTransformation&&a))return G.computeObjectRotation(b.heading,
b.tilt,b.roll,c)};k._computeAnchor=function(b,a,c){const d=n.create();switch(c.anchor){case "center":v.copy(d,w.center(b));v.negate(d,d);break;case "top":a=w.center(b);v.set(d,-a[0],-a[1],-b[5]);break;case "bottom":a=w.center(b);v.set(d,-a[0],-a[1],-b[2]);break;case "relative":a=w.center(b);b=w.size(b);c=(c=c.anchorPosition)?n.fromValues(c.x,c.y,c.z):n.ZEROS;v.multiply(d,b,c);v.add(d,d,a);v.negate(d,d);break;default:h.isSome(a)?v.negate(d,a):v.copy(d,n.ZEROS)}return d};k._applyAnchor=function(b,a,
c){this._fastUpdates.enabled&&this._fastUpdates.requiresShaderTransformation||(b=this._computeAnchor(b.resourceBoundingBox,b.pivotOffset,a))&&I.translate(c,c,b)};k._hasPerInstanceColor=function(){return this._drivenProperties.color||this._drivenProperties.opacity};k._fastVisualVariableConvertOptions=function(b,a,c,d){const e=h.isSome(b)?n.fromArray(w.size(b)):n.ONES;b=h.isSome(b)?this._computeAnchor(b,d,this.symbolLayer):n.ZEROS;d=this._context.renderCoordsHelper.unitInMeters;c=G.computeObjectScale(h.isSome(a)?
a:void 0,a,c,d);const f=n.fromValues(this.symbolLayer.tilt||0,this.symbolLayer.roll||0,this.symbolLayer.heading||0);return{modelSize:e,symbolSize:h.isSome(a)?a:n.ONES,unitInMeters:d,transformation:{anchor:b,scale:c,rotation:f}}};z._createClass(D,[{key:"extentPadding",get:function(){return h.isSome(this._resources)?this._resources.extentPadding:0}},{key:"_isPrimitive",get:function(){return!(this.symbolLayer.resource&&this.symbolLayer.resource.href)}},{key:"lodRenderer",get:function(){return h.isSome(this._resources)?
this._resources.lodRenderer:null}}]);return D}(S.Graphics3DSymbolLayer);const F=n.create(),ca=Y.create(),U=Y.create(),P=A.create(),Q=new K.SampleElevationInfo;V.Graphics3DObjectSymbolLayer=S;Object.defineProperty(V,Symbol.toStringTag,{value:"Module"})});