// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/has ../../../../core/Error ../../../../core/lang ../../../../core/maybe ../../../../core/unitUtils ../../../../chunks/earcut ../../../../chunks/mat3 ../../../../chunks/mat3f64 ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/buffer/BufferView ../../../../chunks/vec32 ../../../../layers/graphics/data/SnappingCandidate ../../../../renderers/support/renderingInfoUtils ../../../ViewingMode ./elevationAlignmentUtils ./ElevationContext ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ./interfaces ./polygonUtils ../support/edgeUtils ../../support/debugFlags ../../support/ElevationProvider ../../support/renderInfoUtils/polygon ../../webgl-engine/lib/Attribute ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/ContentObjectType ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryWithMapPositions ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/VertexAttribute ../../webgl-engine/materials/DefaultMaterial".split(" "),
function(da,U,ea,va,V,H,wa,xa,ya,za,fa,W,A,D,Aa,P,ha,ia,X,Ba,Ca,Y,Da,Ea,Fa,ja,ka,Ga,Ha,Ia,Ja,Ka,Q,Z,La,Ma,Na,Oa,G,la){function ma(g,k,f,c,a,b){const d=Array(k.length).fill(0);a=[[G.VertexAttribute.POSITION,new Q.Attribute(c.positions,3,!0)],[G.VertexAttribute.NORMAL,new Q.Attribute(c.normals,3,!0)],[G.VertexAttribute.COLOR,new Q.Attribute(a,4,!0)],[G.VertexAttribute.SIZE,new Q.Attribute(c.heights,1,!0)]];return new Ma.Geometry(g,a,[[G.VertexAttribute.POSITION,k],[G.VertexAttribute.NORMAL,k],[G.VertexAttribute.COLOR,
d]],c.elevation,La.ContentObjectType.Mesh,b,f)}function Pa(g,k,f,c,a,b,d,p,h,m,n,l,q){let y=0;var e=2*c.count,r=c.index,t=c.count,E=f.length/3,u=e;A.copy(w,l);const v=0<n?1:-1;e=3*r;let x=0;r=3*x;let F=t;l=3*F;for(let z=0;z<t;++z)q&&(w[0]=g[e+0],w[1]=g[e+1],w[2]=g[e+2],A.normalize(w,w)),a[r+0]=g[e+0],a[r+1]=g[e+1],a[r+2]=g[e+2],b[r+0]=k[e+0],b[r+1]=k[e+1],b[r+2]=k[e+2],d[r+0]=-v*w[0],d[r+1]=-v*w[1],d[r+2]=-v*w[2],p[x]=0,a[l+0]=g[e+0]+n*w[0],a[l+1]=g[e+1]+n*w[1],a[l+2]=g[e+2]+n*w[2],b[l+0]=k[e+0],
b[l+1]=k[e+1],b[l+2]=k[e+2],d[l+0]=v*w[0],d[l+1]=v*w[1],d[l+2]=v*w[2],p[F]=n,r+=3,l+=3,e+=3,x+=1,F+=1;r=e=0;l=3*u;g=0>n?na:oa;k=0>n?oa:na;for(q=0;q<E;++q)m[r+0]=f[e+g[0]],m[r+1]=f[e+g[1]],m[r+2]=f[e+g[2]],h[l+0]=f[e+k[0]]+t,h[l+1]=f[e+k[1]]+t,h[l+2]=f[e+k[2]]+t,r+=3,l+=3,e+=3;f=2*c.count;e=0;pa(a,b,p,d,y,c.pathLengths[0],c.count,f,h,e,n);f+=4*c.pathLengths[0];e+=2*c.pathLengths[0];y+=c.pathLengths[0];for(m=1;m<c.pathLengths.length;++m)pa(a,b,p,d,y,c.pathLengths[m],c.count,f,h,e,n),f+=4*c.pathLengths[m],
e+=2*c.pathLengths[m],y+=c.pathLengths[m]}function R(g,k,f,c,a,b,d){c[b]=c[d];d*=3;b*=3;g[b+0]=g[d+0];g[b+1]=g[d+1];g[b+2]=g[d+2];k[b+0]=k[d+0];k[b+1]=k[d+1];k[b+2]=k[d+2];f[b+0]=a[0];f[b+1]=a[1];f[b+2]=a[2]}function pa(g,k,f,c,a,b,d,p,h,m,n){let l=a,q=a+1,y=a+d,e=a+d+1,r=p,t=p+1,E=p+2*b;p=p+2*b+1;0>n&&(l=a+d+1,e=a);m*=3;for(let B=0;B<b;++B){B===b-1&&(0<n?(q=a,e=a+d):(q=a,l=a+d));var u=g,v=l,x=q,F=y,z=N;v*=3;x*=3;F*=3;A.set(aa,u[v++],u[v++],u[v++]);A.set(qa,u[x++],u[x++],u[x++]);A.set(ra,u[F++],u[F++],
u[F++]);A.subtract(sa,qa,aa);A.subtract(ta,ra,aa);A.cross(z,ta,sa);A.normalize(z,z);R(g,k,c,f,N,r,l);R(g,k,c,f,N,t,q);R(g,k,c,f,N,E,y);R(g,k,c,f,N,p,e);h[m++]=r;h[m++]=E;h[m++]=p;h[m++]=r;h[m++]=p;h[m++]=t;l++;q++;y++;e++;r+=2;t+=2;E+=2;p+=2}}function Qa(g,k,f,c,a){g=g.stageObject;const b=g.geometries,d=b.length;k="absolute-height"!==k.mode;let p=0;const h=g.transformation,m=fa.invertOrIdentity(W.create(),h);for(let n=0;n<d;n+=2){const l=b[n];if(!Na.isGeometryWithMapPositions(l))continue;const q=
l.getMutableAttribute(G.VertexAttribute.POSITION).data,y=l.vertexAttributes.get(G.VertexAttribute.SIZE).data,e=new Ja.SamplePosition(l.mapPositions),r=q.length/3;let t=0,E=!1,u=0;for(let v=0;v<r;v++){L[0]=q[t];L[1]=q[t+1];L[2]=q[t+2];c(e,S);k&&(u+=S.sampledElevation);Ia.TESTS_DISABLE_OPTIMIZATIONS?(A.set(C,e.array[e.offset+0],e.array[e.offset+1],S.z+y[t/3]),H.isSome(f)&&a.toRenderCoords(C,f,C)):(A.set(C,q[t+0],q[t+1],q[t+2]),A.transformMat4(C,C,h),a.setAltitude(C,S.z+y[t/3]));A.transformMat4(C,C,
m);q[t]=C[0];q[t+1]=C[1];q[t+2]=C[2];const x=.01/a.unitInMeters;if(Math.abs(L[0]-q[t])>=x||Math.abs(L[1]-q[t+1])>=x||Math.abs(L[2]-q[t+2])>=x)E=!0;e.offset+=3;t+=3}E&&(l.invalidateBoundingInfo(),g.geometryVertexAttrsUpdated(b[n]),b[n+1].invalidateBoundingInfo(),g.geometryVertexAttrsUpdated(b[n+1]));p+=u/r}return p/d}const Ra=["polygon","extent"];ea=function(g){function k(c,a,b,d){c=g.call(this,c,a,b,d)||this;c.ensureDrapedStatus(!1);return c}U._inheritsLoose(k,g);var f=k.prototype;f.doLoad=function(){var c=
U._asyncToGenerator(function*(){if(!this._drivenProperties.size){var a=ja.validateSymbolLayerSize(this._getSymbolSize());if(a)throw new va("graphics3dextrudesymbollayer:invalid-size",a);}a=H.get(this.symbolLayer,"material","color");var b=this._getCombinedOpacityAndColor(a);a=D.fromArray(b);b=b[3];const d=1>b||this.needsDrivenTransparentPass;a={usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0,diffuse:a,ambient:a,opacity:b,transparent:d,cullFace:d?Z.CullFaceOptions.None:Z.CullFaceOptions.Back,
hasVertexColors:!0,hasSlicePlane:this._context.slicePlaneEnabled,castShadows:this.symbolLayer.castShadows,offsetTransparentBackfaces:!0};this._material=new la.DefaultMaterial(a);this._bottomMaterial=new la.DefaultMaterial({...a,cullFace:Z.CullFaceOptions.Back});this._context.stage.add(this._material);this._context.stage.add(this._bottomMaterial)});return function(){return c.apply(this,arguments)}}();f.destroy=function(){g.prototype.destroy.call(this);this._material&&(this._context.stage.remove(this._material),
this._context.stage.remove(this._bottomMaterial))};f.createGraphics3DGraphic=function(c){const a=c.graphic;if(!this._validateGeometry(a.geometry,Ra,this.symbolLayer.type))return null;const b=this._getVertexOpacityAndColor(c.renderingInfo,255),d=this.setGraphicElevationContext(a,new Da.ElevationContext);return this._createAs3DShape(a,c.renderingInfo,b,d,a.uid)};f.layerOpacityChanged=function(c,a){var b=H.get(this.symbolLayer,"material","color");b=this._getCombinedOpacity(b);const d=1>b||this.needsDrivenTransparentPass;
this._material.setParameters({opacity:b,transparent:d});this._bottomMaterial.setParameters({opacity:b,transparent:d});const p=this._getLayerOpacity();c.forEach(h=>{h=a(h);H.isSome(h)&&h.layerOpacityChanged(p,this._context.isAsync)})};f.layerElevationInfoChanged=function(c,a){return this.updateGraphics3DGraphicElevationInfo(c,a,Y.needsElevationUpdates3D)};f.slicePlaneEnabledChanged=function(c,a){this._material.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});this._bottomMaterial.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});
c.forEach(b=>{b=a(b);H.isSome(b)&&b.slicePlaneEnabledChanged(this._context.slicePlaneEnabled,this._context.isAsync)});return!0};f.physicalBasedRenderingChanged=function(){this._material.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0});this._bottomMaterial.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0});return!0};f.pixelRatioChanged=function(){return!0};f.skipHighSymbolLodsChanged=function(){return!0};f._getExtrusionSize=function(c){c=
c.size&&this._drivenProperties.size?Ba.getDriverAxisSizeValue(c.size,2)??0:this._getSymbolSize();return c/=this._context.renderCoordsHelper.unitInMeters};f.applyRendererDiff=function(c,a){return this._drivenPropertiesChanged(a)?ka.ApplyRendererDiffResult.Recreate_Symbol:ka.ApplyRendererDiffResult.Recreate_Graphics};f.queryForSnapping=function(){var c=U._asyncToGenerator(function*(a,b,d,p){b=this._getExtrusionSize(d)*this._context.renderCoordsHelper.unitInMeters/wa.getMetersPerVerticalUnitForSR(b);
const {objectId:h,target:m}=a;d=V.clone(m);d.z=(d.z??0)+b;switch(a.type){case "edge":const {start:n,end:l}=a;a=V.clone(n);p=V.clone(l);a.z=(a.z??0)+b;p.z=(p.z??0)+b;return[X.makeEdgeCandidate(h,d,Infinity,a,p)];case "vertex":return[X.makeVertexCandidate(h,d,Infinity),X.makeEdgeCandidate(h,m,Infinity,m,d)];default:return[]}});return function(a,b,d,p){return c.apply(this,arguments)}}();f._getSymbolSize=function(){return this.symbolLayer.size??1};f._createAs3DShape=function(c,a,b,d,p){var h=Ga.geometryAsPolygon(c.geometry);
if(H.isNone(h))return null;if(0===h.rings.length||!h.rings.some(O=>0<O.length))return this._logGeometryValidationWarnings(h.rings,"rings","ExtrudeSymbol3DLayer"),null;c=Ka.geometryToRenderInfo(h,this._context.elevationProvider,this._context.renderCoordsHelper,d);this._logGeometryCreationWarnings(c,h.rings,"rings","ExtrudeSymbol3DLayer");var m=ja.computeCentroid(h);if(H.isNone(m))return null;var n=[];const l=P.create(),q=W.create(),y=D.create(),e=this._context.renderCoordsHelper.viewingMode===Ca.ViewingMode.Global;
e||this._context.renderCoordsHelper.worldUpAtPosition(null,y);Aa.computeTranslationToOriginAndRotation(h.spatialReference,[m.x,m.y,0],q,this._context.renderCoordsHelper.spatialReference);h=W.create();fa.invert(h,q);m=za.create();ya.normalFromMat4(m,h);const {polygons:r,mapPositions:t,position:E}=c;var u=E.length/3;const v=new Float64Array(18*u),x=new Float64Array(18*u),F=new Float64Array(18*u);u=new Float64Array(6*u);let z=0;for(let O=0;O<r.length;++O){var B=r[O],M=B.count;if(this._context.clippingExtent&&
(P.empty(l),P.expandWithBuffer(l,B.mapPositions),!P.intersectsClippingArea(l,this._context.clippingExtent)))continue;const T=xa.earcut(B.mapPositions,B.holeIndices,3);if(0===T.length)continue;const ba=Array(6*M+T.length),ca=Array(T.length);var K=6*M,I=3*v.BYTES_PER_ELEMENT;I=new ha.BufferViewVec3f64(v.buffer,z*I,I,(z+K)*I);var J=3*x.BYTES_PER_ELEMENT;J=new ha.BufferViewVec3f64(x.buffer,z*J,J,(z+K)*J);const ua=new Float64Array(F.buffer,3*z*F.BYTES_PER_ELEMENT,3*K);K=new Float64Array(u.buffer,1*z*u.BYTES_PER_ELEMENT,
1*K);const Sa=this._getExtrusionSize(a);Pa(E,t,T,B,I.typedBuffer,ua,J.typedBuffer,K,ba,ca,Sa,y,e);ia.transformMat4(I,I,h);ia.transformMat3(J,J,m);z+=6*M;B=this._context.stage.renderView.getObjectAndLayerIdColor({graphicUid:p,layerUid:this._context.layer.uid});M=new Ta(I.typedBuffer,ua,J.typedBuffer,K);n.push(ma(this._material,ba,ba.length-ca.length,M,b,B));n.push(ma(this._bottomMaterial,ca,0,M,b,B))}if(0===n.length)return null;a=new Oa.Object3D({geometries:n,metadata:{layerUid:this._context.layer.uid,
graphicUid:p,isElevationSource:!0}});a.transformation=q;b=Ha.createMaterial(this.symbolLayer,{opacity:this._getLayerOpacity()});b=H.isSome(b)?{baseMaterial:this._material,edgeMaterials:[b],properties:{mergeGeometries:!0,hasSlicePlane:this._context.slicePlaneEnabled}}:null;n=new Ea.Graphics3DObject3DGraphicLayer(this,a,n,null,null,Qa,d,b);n.alignedSampledElevation=c.sampledElevation;n.needsElevationUpdates=Y.needsElevationUpdates3D(d.mode);return n};return k}(Fa.Graphics3DSymbolLayer);const N=D.create(),
aa=D.create(),qa=D.create(),ra=D.create(),sa=D.create(),ta=D.create(),L=D.create(),C=D.create(),w=D.create(),S=new Y.SampleElevationInfo,oa=[0,2,1],na=[0,1,2];let Ta=function(g,k,f,c){this.positions=g;this.elevation=k;this.normals=f;this.heights=c};da.Graphics3DExtrudeSymbolLayer=ea;Object.defineProperty(da,Symbol.toStringTag,{value:"Module"})});