// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/vec2f64 ../../../../chunks/vec3f64 ../../../../chunks/vec4f64 ../../../../symbols/callouts/calloutUtils ./ElevationAligners ./elevationAlignmentUtils ./ElevationContext ./Graphics3DGraphicCreationContext ./Graphics3DObject3DGraphicLayer ./Graphics3DObjectMetadata ./Graphics3DSymbolLayer ./graphicUtils ./pointUtils ./symbolComplexity ../../webgl-engine/lib/Attribute ../../webgl-engine/lib/ContentObjectType ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/VertexAttribute ../../webgl-engine/materials/LineCalloutMaterial".split(" "),
function(r,t,x,g,y,z,B,C,D,E,m,F,v,G,H,u,I,A,J,p,K,L,n,q){u=function(l){function k(a,b){a=l.call(this,a,null,b,M)||this;a._elevationOptions={supportsOffsetAdjustment:!0,supportsOnTheGround:!1};a.ensureDrapedStatus(!1);return a}t._inheritsLoose(k,l);var e=k.prototype;e.doLoad=function(){var a=t._asyncToGenerator(function*(){this._material=new q.LineCalloutMaterial(this._materialParameters);this._context.stage.add(this._material)});return function(){return a.apply(this,arguments)}}();e.destroy=function(){l.prototype.destroy.call(this);
this._context.stage.remove(this._material);this._material=null};e._perInstanceMaterialParameters=function(a){const b=this._materialParameters;b.screenOffset=a.screenOffset||z.ZEROS;b.centerOffsetUnits=a.centerOffsetUnits||"world";return b};e._defaultElevationInfoNoZ=function(){return N};e.createGraphics3DGraphic=function(a){const b=a.renderingInfo;a=a.graphic;const c=this.setGraphicElevationContext(a,new F.ElevationContext,b.elevationOffset||0);var d=b.symbol;const h="on-the-ground"===this._elevationContext.mode&&
("cim"===d.type||!d.symbolLayers.some(f=>"object"===f.type||"text"===f.type));if("label-3d"!==d.type&&h||"point-3d"===d.type&&d.symbolLayers.every(f=>"text"===f.type&&!D.textSymbolLayerSupportsVerticalOffset(f)))return null;d=I.computeCentroid(a.geometry);return g.isNone(d)?null:this._createAs3DShape(d,c,b,a.uid)};e.layerOpacityChanged=function(){g.isSome(this._material)&&this._material.setParameters(this._materialParameters)};e.layerElevationInfoChanged=function(a,b,c){c=m.elevationModeChangeUpdateType(k.elevationModeChangeTypes,
c,this._elevationContext.mode);if(c!==m.SymbolUpdateType.UPDATE)return c;a.forEach(d=>{const h=b(d);g.isSome(h)&&this.updateGraphicElevationContext(d.graphic,h)});return c};e.slicePlaneEnabledChanged=function(){if(g.isNone(this._material))return!0;this._material.setParameters({hasSlicePlane:this._context.slicePlaneEnabled});return!0};e.physicalBasedRenderingChanged=function(){return!0};e.pixelRatioChanged=function(){return!0};e.skipHighSymbolLodsChanged=function(){return!0};e.setGraphicElevationContext=
function(a,b,c=0){a=l.prototype.setGraphicElevationContext.call(this,a,b);a.addOffsetRenderUnits(c);return a};e.updateGraphicElevationContext=function(a,b){this.setGraphicElevationContext(a,b.elevationContext,g.isSome(b.metadata)?b.metadata.elevationOffset:0);b.needsElevationUpdates=m.needsElevationUpdates2D(b.elevationContext.mode)};e.computeComplexity=function(){return{primitivesPerFeature:2,primitivesPerCoordinate:0,drawCallsPerFeature:0,estimated:!1,memory:J.emptySymbolComplexity.memory}};e._createVertexData=
function(a){const {translation:b,centerOffset:c}=a;a=b?new p.Attribute([b[0],b[1],b[2]],3,!0):new p.Attribute([0,0,0],3,!0);const d=c?new p.Attribute([c[0],c[1],c[2],c[3]],4,!0):new p.Attribute([0,0,0,1],4,!0);return[[n.VertexAttribute.POSITION,a],[n.VertexAttribute.NORMAL,new p.Attribute([0,0,1],3,!0)],[n.VertexAttribute.AUXPOS1,d]]};e._getOrCreateMaterial=function(a){const b=this._perInstanceMaterialParameters(a),c=q.LineCalloutMaterial.uniqueMaterialIdentifier(b);if(g.isSome(this._material)&&c===
this._material.uniqueMaterialIdentifier)return{material:this._material,isUnique:!1};if(g.isSome(a.materialCollection)){let d=a.materialCollection.get(c);g.isNone(d)&&(d=new q.LineCalloutMaterial(b),a.materialCollection.add(c,d));return{material:d,isUnique:!1}}return{material:new q.LineCalloutMaterial(b),isUnique:!0}};e._createAs3DShape=function(a,b,c,d){var h=this._context.stage.renderView.getObjectAndLayerIdColor({graphicUid:d,layerUid:this._context.layer.uid}),f=this._getOrCreateMaterial(c);h=new L.Geometry(f.material,
this._createVertexData(c),O,null,K.ContentObjectType.Point,h);d=A.createStageObject(this._context,a,h,b,d);if(g.isNone(d))return null;f=new G.Graphics3DObject3DGraphicLayer(this,d.object,[h],f.isUnique?[f.material]:null,null,E.perObjectElevationAligner,b);f.metadata=new H.Graphics3DObjectMetadata(c.elevationOffset);f.alignedSampledElevation=d.sampledElevation;f.needsElevationUpdates=m.needsElevationUpdates2D(b.mode);A.extendPointGraphicElevationContext(f,a,this._context.elevationProvider);return f};
t._createClass(k,[{key:"_materialParameters",get:function(){const a=new q.Parameters;var b=this.symbol,c=b.callout;a.color=g.isSome(c.color)?x.toUnitRGBA(c.color):[0,0,0,0];a.color[3]*=this._getLayerOpacity();a.size=y.pt2px(c.size||0);if(b.verticalOffset){const {screenLength:d,minWorldLength:h,maxWorldLength:f}=b.verticalOffset;a.verticalOffset={screenLength:y.pt2px(d),minWorldLength:h||0,maxWorldLength:g.isSome(f)?f:Infinity}}a.borderColor=g.isSome(c.border)&&g.isSome(c.border.color)?x.toUnitRGBA(c.border.color):
null;c="object"===b.symbolLayers.getItemAt(0).type;b="label-3d"===b.type;a.occlusionTest=!c;a.shaderPolygonOffset=c?0:void 0;a.depthHUDAlignStart=b;a.hasSlicePlane=this._context.slicePlaneEnabled;a.screenSizePerspective=this._context.screenSizePerspectiveEnabled?this._context.sharedResources.screenSizePerspectiveSettings:null;return a}}]);return k}(u.Graphics3DSymbolLayer);u.elevationModeChangeTypes={definedChanged:m.SymbolUpdateType.UPDATE,staysOnTheGround:m.SymbolUpdateType.UPDATE,onTheGroundChanged:m.SymbolUpdateType.RECREATE};
const w=[0],O=[[n.VertexAttribute.POSITION,w],[n.VertexAttribute.NORMAL,w],[n.VertexAttribute.AUXPOS1,w]],N={mode:"relative-to-ground",offset:0},M={ignoreDrivers:!0,renderPriority:0,renderPriorityStep:1};v=function(l){function k(){return l.apply(this,arguments)||this}t._inheritsLoose(k,l);return k}(v);r.Graphics3DLineCalloutSymbolLayer=u;r.LineCalloutCreationContext=v;r.LineCalloutSymbolLayerRenderingInfo=function(l,k,e=B.create(),a=C.create(),b=z.create(),c="world",d=0,h=null){this.renderer=l;this.symbol=
k;this.translation=e;this.centerOffset=a;this.screenOffset=b;this.centerOffsetUnits=c;this.elevationOffset=d;this.materialCollection=h};Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});