// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/support/aaBoundingBox ./elevationAlignmentUtils ./featureExpressionInfoUtils ./graphicUtils ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/Object3DStateID".split(" "),function(x,y,z,q,t,m,A,B,C,D,E){let G=function(){function u(a,b,c,l){this.graphics3DSymbolLayer=a;this.instanceIndex=b;this.elevationAligner=c;this.elevationContext=
l;this.type="lod-instance";this._highlights=new Set;this.alignedSampledElevation=0;this.needsElevationUpdates=this.isElevationSource=!1}var f=u.prototype;f.initialize=function(){};f.setVisibility=function(a){const b=this._lodRenderer.instanceData;a!==b.getVisible(this.instanceIndex)&&b.setVisible(this.instanceIndex,a)};f.destroy=function(){null!=this.instanceIndex&&(this._lodRenderer.instanceData.removeInstance(this.instanceIndex),this.graphics3DSymbolLayer.notifyDestroyGraphicLayer(this))};f.alignWithElevation=
function(a,b,c){this.elevationAligner&&(B.setContextFeature(this.elevationContext.featureExpressionInfoContext,c),c=this.elevationAligner(this,this.elevationContext,a.spatialReference,(l,r)=>A.evaluateElevationInfoAtPoint(l,a,this.elevationContext,b,r),b),y.isSome(c)&&(this.alignedSampledElevation=c))};f.getCenterObjectSpace=function(a=t.create()){this._lodRenderer.instanceData.getCombinedLocalTransform(this.instanceIndex,h);return q.transformMat4(a,this._lodRenderer.baseBoundingSphere.center,h)};
f.getBoundingBoxObjectSpace=function(a=m.create()){this._lodRenderer.instanceData.getCombinedLocalTransform(this.instanceIndex,h);const b=this._lodRenderer.baseBoundingBox;m.empty(a);for(let c=0;8>c;++c)q.set(g,0===(c&1)?b[0]:b[3],0===(c&2)?b[1]:b[4],0===(c&4)?b[2]:b[5]),q.transformMat4(g,g,h),m.expandWithVec3(a,g);return a};f.computeAttachmentOrigin=function(a){this._lodRenderer.instanceData.getGlobalTransform(this.instanceIndex,h);a.render.origin[0]+=h[12];a.render.origin[1]+=h[13];a.render.origin[2]+=
h[14];a.render.num++};f.getProjectedBoundingBox=function(){var a=x._asyncToGenerator(function*(b,c,l,r,d){d=this.getBoundingBoxObjectSpace(d);var k=F;const v=m.isPoint(d)?1:k.length;this._lodRenderer.instanceData.getGlobalTransform(this.instanceIndex,h);for(var e=0;e<v;e++){const n=k[e];g[0]=d[n[0]];g[1]=d[n[1]];g[2]=d[n[2]];q.transformMat4(g,g,h);p[3*e]=g[0];p[3*e+1]=g[1];p[3*e+2]=g[2]}if(!b(p,0,v))return null;m.empty(d);b=null;this.calculateRelativeScreenBounds&&(b=this.calculateRelativeScreenBounds());
for(k=0;k<3*v;k+=3){for(e=0;3>e;e++)d[e]=Math.min(d[e],p[k+e]),d[e+3]=Math.max(d[e+3],p[k+e]);b&&l.push({location:p.slice(k,k+3),screenSpaceBoundingRect:b})}if(c&&(m.center(d,w),"absolute-height"!==this.elevationContext.mode)){let n;l=C.demResolutionForBoundingBox(d,c.service.spatialReference,c);try{n=yield c.service.queryElevation(w[0],w[1],r,l,"ground")}catch(H){}y.isSome(n)&&m.offset(d,0,0,-this.alignedSampledElevation+n)}return d});return function(b,c,l,r,d){return a.apply(this,arguments)}}();
f.addObjectState=function(a,b){a===D.Object3DState.Highlight&&(a=new E.Object3DStateID(a),this._addHighlightId(a),b.addExternal(c=>{this._removeHighlightId(c)},a))};f.removeObjectState=function(a){this._highlights.forEach(b=>a.remove(b))};f._addHighlightId=function(a){this._highlights.add(a);this._lodRenderer.instanceData.setHighlight(this.instanceIndex,!0)};f._removeHighlightId=function(a){this._highlights.delete(a);this._lodRenderer.instanceData.setHighlight(this.instanceIndex,0<this._highlights.size)};
x._createClass(u,[{key:"_lodRenderer",get:function(){return this.graphics3DSymbolLayer.lodRenderer}}]);return u}();const p=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],g=t.create(),w=t.create(),F=[[0,1,2],[3,1,2],[0,4,2],[3,4,2],[0,1,5],[3,1,5],[0,4,5],[3,4,5]],h=z.create();return G});