// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../intl/date ../../intl/number ../../layers/support/CodedValueDomain ../../layers/support/editableLayers ../../layers/support/fieldUtils ../../layers/support/layerUtils ../FeatureForm/InputField ./Grid/EditorColumn ../support/DatePicker ../support/TimePicker ../support/widgetUtils".split(" "),
function(r,k,y,E,l,h,T,F,v,A,G,H,u,I,J,K,L,M,B){const N=v.convertDateFormatToIntlOptions("short-date-short-time"),O=v.convertDateFormatToIntlOptions("short-date"),P={useGrouping:!0,maximumFractionDigits:20};h=function(C){function w(b){var a=C.call(this,b)||this;a._inputField=null;a.cellValueFormatFunction=({rowData:c,value:d})=>{if(a.formatFunction){const {config:e,field:m}=r._assertThisInitialized(a);return a.formatFunction({config:e,field:m,value:B.renderingSanitizer.sanitize(d)})}if(null===d)return"\x26nbsp;";
const {config:f,field:g}=r._assertThisInitialized(a);({item:{feature:c}}=c);if(c=a._getDomainForFeature(c))return a._getComputedDomain(d,c);if("date"===g.type){c=a._getDateFormatOptions();const e="feature"===a.layer?.type&&a.layer.datesInUnknownTimezone?{timeZone:"UTC"}:null;return d?v.formatDate(d,{...c,...e}):null}return u.isNumericField(g)?(c=f?.format?A.convertNumberFormatToIntlOptions(f.format):P,A.formatNumber(parseFloat(d),c)):B.renderingSanitizer.sanitize(d)};a.cellValueValidatorFunction=
({oldValue:c,value:d})=>a._inputField&&!a._inputField.valid||a.required&&(!y.isSome(d)||""===d)?!1:c!==d;a.config=null;a.editingEnabled=!1;a.expressionInfos=null;a.field=null;a.formatFunction=null;a.headerRenderFunction=c=>{const {root:d}=c,{editable:f,editingEnabled:g,headerMenuEnabled:e,sortable:m}=r._assertThisInitialized(a);a.removeCellContent(d);d.classList.add("esri-field-column__header-content");g&&!f&&d.appendChild(a.createLockedElement());if(m)a.headerSorterRenderFunction(c);else{const n=
document.createElement("div");n.classList.add("esri-field-column__header-label");n.textContent=a.label;d.appendChild(n)}e&&a.headerMenuRenderFunction(c)};a.inputRenderFunction=({root:c,column:d,rowData:f})=>{if(!a.activeEditInfo?.updating&&a.editable){var g=a.getCellValue(d,f),e=a.createInputElement({root:c,column:d,rowData:f,value:g});a._set("activeEditInfo",{column:d,input:e,root:c,rowData:f,updating:!0,oldValue:g});"date"===a.field.type?a._renderDateEditors(g,c,e):(d=a.createInputContainer(),d.appendChild(e),
a.removeCellContent(c),c.appendChild(d),e.focus(),e instanceof HTMLInputElement&&e.select(),a.grid?.notifyResize())}};a.layer=null;a.parseInputValueFunction=({input:c})=>{c=c.value;const {required:d,type:f}=a._inputField;return d||""!==c?"number"===f||"date"===f?parseFloat(c):"text"===f?c.trim():c:null};a.store=null;a.template=null;a.updateRowItemFunction=({rowData:c,column:d,value:f})=>{c.item.feature.attributes[d.path]=f};a.updateStoreItemFunction=function(){var c=r._asyncToGenerator(function*({rowData:d,
column:f,value:g}){d&&a.store&&(d=a.store.getObjectIdIndex(d.item.objectId)??d.index,yield a.store.updateItem({index:d,name:f.path,value:g}))});return function(d){return c.apply(this,arguments)}}();return a}r._inheritsLoose(w,C);var p=w.prototype;p.createInputElement=function({rowData:b,value:a}){({item:b}=b);if(!b||!b.feature)return null;this._inputField=this._setUpInputField(b.feature,a);const {field:c,maxLength:d,minLength:f,required:g}=this;({domain:b}=this._inputField);let e=null;"coded-value"===
b?.type?(e=this._createSelectElement(a,b.codedValues.map(({code:t,name:z})=>({value:t,name:z})),this._inputField),e.onchange=()=>{e.onblur=null;n()}):(e=document.createElement("input"),e.type=u.isNumericField(c)?"number":"text",-1<d&&(e.maxLength=d),0<f&&(e.minLength=f));e.classList.add("esri-field-column__cell-input");e.value=a;e.required=g;let m=!1;e.onkeydown=t=>{m="Escape"===t.key};e.onblur=()=>{e.onblur=null;n()};const n=()=>{m?this.cancel():this.submit();this._inputField=null};return e};p.createInputContainer=
function(){const b=document.createElement("div");b.classList.add("esri-field-column__cell__input-container");return b};p.createLockedElement=function(){const b=document.createElement("div");b.classList.add("esri-icon-locked");return b};p.getCellValue=function({path:b},{item:a}){return a?.feature?.attributes?.[b]??null};p._renderDateEditors=function(b,a,c){const {config:d,messagesCommon:f,template:g}=this;var e=b?new Date(b):new Date(Date.now());const m=new L({dateInputEnabled:!0,value:e}),n=new M({value:e});
c.value=e.getTime().toString();let t=!b;const z=()=>{t=!0;const Q=this._getCombinedDateTime(m.value,n.value);c.value=Q.getTime().toString()},R=()=>{t?this.submit():this.cancel()},S=()=>{c.value=null;this.submit()};E.watch(()=>[m.value,n.value],()=>z());var q=document.createElement("div");const D=document.createElement("div");m.container=q;n.container=D;b=document.createElement("button");b.classList.add("esri-field-column__button","esri-icon-save");b.onclick=()=>R();b.title=f?.save;e=document.createElement("button");
e.classList.add("esri-field-column__button","esri-icon-trash");e.onclick=()=>S();e.title=f?.clear;const x=document.createElement("div");x.classList.add("esri-field-column__cell__date-input-wrapper");x.appendChild(q);(g&&g.input&&"datetime-picker"===g.input.type&&!1!==g.input.includeTime||d&&!1!==d.includeTime)&&x.appendChild(D);q=document.createElement("div");q.classList.add("esri-field-column__cell__date-input-container");q.appendChild(x);q.appendChild(b);q.appendChild(e);m.when(()=>this.grid?.notifyResize());
n.when(()=>this.grid?.notifyResize());this.removeCellContent(a);a.appendChild(q);this.grid?.notifyResize()};p._createSelectElement=function(b,a,c){let d=!1;a=a.map(g=>{g.value===b&&(d=!0);const e=document.createElement("option");e.text=g.name;e.value=g.value;return e});if(null!=b&&""!==b&&!d){const g=document.createElement("option");g.text=b;g.value=b;a.unshift(g)}c.required||null!=c.value||(c=document.createElement("option"),c.value="",a.unshift(c));const f=document.createElement("select");a.forEach(g=>
f.add(g));f.value=b;return f};p._setUpInputField=function(b,a){const {config:c,field:d,layer:f}=this;b=new J({config:c,feature:b,initialFeature:b.clone(),field:d,layer:f,group:null,messages:null});b.set("value",a);return b};p._isDomainCompatible=function(b){const {field:a}=this;if(b&&"coded-value"===b.type){const c=typeof b.codedValues[0].code;if("string"===c&&u.isStringField(a)||"number"===c&&u.isNumericField(a))return!0}return b&&"range"===b.type&&u.isNumericField(a)?!0:!1};p._getDomainForFeature=
function(b){const {config:a,layer:c,name:d,template:f}=this;if("wfs"===c.type||"geojson"===c.type||"csv"===c.type)return null;if(f?.domain&&this._isDomainCompatible(f.domain))return f.domain;var {typeIdField:g}=c;const e=this.field.domain;if(g===d&&!e)return new G({name:"__internal-type-based-coded-value-domain__",codedValues:c.types.map(({id:m,name:n})=>({code:m,name:n}))});b=g&&c.getFieldDomain(d,{feature:b})||e;g=a?.domain;return this._isDomainCompatible(g)?g:b};p._getComputedDomain=function(b,
a){return a?"range"===a.type?b:"coded-value"===a.type?(a=a.codedValues.filter(c=>c.hasOwnProperty("code")&&c.code===b))&&a.length?a[0].name:b:null:null};p._getCombinedDateTime=function(b,a){return new Date(b.getFullYear(),b.getMonth(),b.getDate(),a.getHours(),a.getMinutes(),a.getSeconds())};p._getDateFormatOptions=function(){const {config:b,template:a}=this,c=a?.format?.dateFormat||b?.format?.dateFormat;return c?v.convertDateFormatToIntlOptions(c):a&&a.input&&!1==="includeTime"in a.input||!1===b?.includeTime?
O:N};r._createClass(w,[{key:"alias",get:function(){return this.field?.alias}},{key:"defaultValue",get:function(){return this.field?.defaultValue}},{key:"description",get:function(){return this.template?.description??this.config?.description??this.field?.description??null}},{key:"editable",get:function(){const {config:b,editingEnabled:a,field:c,layer:d,template:f}=this;if(y.isNone(c)||y.isNone(d))return!1;const g=H.isEditableLayer(d),e=I.getEffectiveLayerCapabilities(d);return c.editable&&g&&e?.operations.supportsUpdate?
a?!(!1===f?.editable||!1===b?.editable):!(!f?.editable&&!b?.editable):!1}},{key:"header",get:function(){return this.template?.label||this.config?.label||this.alias||this.path||null}},{key:"hidden",get:function(){const {config:b}=this;return!1===b?.visible||this._get("hidden")||!1},set:function(b){this._set("hidden",b)}},{key:"loadingMessage",get:function(){return this.messages?.loading||"..."}},{key:"maxLength",get:function(){const {field:b,config:a,template:c}=this,d=b?.length,f=c?.input&&"maxLength"in
c.input?c.input.maxLength:a?.maxLength;return!isNaN(f)&&-1<=f&&(-1===d||f<=d)?f:d}},{key:"minLength",get:function(){const {config:b,template:a,maxLength:c}=this,d=a?.input&&"minLength"in a.input?a.input.minLength:b?.minLength||null;return c&&d<=c?d:null}},{key:"name",get:function(){return this.field?.name}},{key:"nullable",get:function(){return this.field?.nullable??!1}},{key:"path",get:function(){return this.field?.name}},{key:"required",get:function(){const {config:b,field:a,template:c}=this;return this.editable&&
(!a?.nullable||!0===b?.required||!0===c?.required)}},{key:"sortable",get:function(){return this.template?!1!==this.template?.sortable:!1!==this.config?.sortable}}]);return w}(K);k.__decorate([l.property({readOnly:!0})],h.prototype,"alias",null);k.__decorate([l.property()],h.prototype,"cellValueFormatFunction",void 0);k.__decorate([l.property()],h.prototype,"cellValueValidatorFunction",void 0);k.__decorate([l.property()],h.prototype,"config",void 0);k.__decorate([l.property({readOnly:!0})],h.prototype,
"defaultValue",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"description",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"editable",null);k.__decorate([l.property()],h.prototype,"editingEnabled",void 0);k.__decorate([l.property()],h.prototype,"expressionInfos",void 0);k.__decorate([l.property()],h.prototype,"field",void 0);k.__decorate([l.property()],h.prototype,"formatFunction",void 0);k.__decorate([l.property({readOnly:!0})],h.prototype,"header",null);k.__decorate([l.property()],
h.prototype,"hidden",null);k.__decorate([l.property()],h.prototype,"headerRenderFunction",void 0);k.__decorate([l.property()],h.prototype,"inputRenderFunction",void 0);k.__decorate([l.property()],h.prototype,"layer",void 0);k.__decorate([l.property({readOnly:!0})],h.prototype,"loadingMessage",null);k.__decorate([l.property()],h.prototype,"maxLength",null);k.__decorate([l.property()],h.prototype,"minLength",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"name",null);k.__decorate([l.property({readOnly:!0})],
h.prototype,"nullable",null);k.__decorate([l.property()],h.prototype,"parseInputValueFunction",void 0);k.__decorate([l.property({readOnly:!0})],h.prototype,"path",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"required",null);k.__decorate([l.property()],h.prototype,"sortable",null);k.__decorate([l.property()],h.prototype,"store",void 0);k.__decorate([l.property()],h.prototype,"template",void 0);k.__decorate([l.property()],h.prototype,"updateRowItemFunction",void 0);k.__decorate([l.property()],
h.prototype,"updateStoreItemFunction",void 0);return h=k.__decorate([F.subclass("esri.widgets.FeatureTable.FieldColumn")],h)});