// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ./ControlPointsTransformTool ./TransformTool".split(" "),function(d,m,f,x,n,q,g,D,E,y,u,z){const k={redo:"r",undo:"z"};d.MediaTransformToolsWrapper=function(v){function r(a){a=
v.call(this,a)||this;a._transformTool=null;a._controlPointsTransformTool=null;a._advancedModeTransformTool=null;a._activeTool=null;a._sharedUndoStack=[];a._sharedRedoStack=[];a._originalOpacity=null;a.activeHandle=0;return a}m._inheritsLoose(r,v);var e=r.prototype;e.initialize=function(){var a=this;const {view:c,mediaElement:p,preserveAspectRatio:A,snapRotation:B,advancedMode:h}=this;this._originalOpacity=p.opacity;this._transformTool=new z.TransformTool({target:p,view:c,preserveAspectRatio:A,snapRotation:B});
this._controlPointsTransformTool=new u.ControlPointsTransformTool({mediaElement:p,view:c});this._advancedModeTransformTool=new u.ControlPointsTransformTool({mediaElement:h.mediaElement,view:h.view});this._transformTool.setSharedUndoStack(this._sharedUndoStack);this._transformTool.setSharedRedoStack(this._sharedRedoStack);this._controlPointsTransformTool.setSharedUndoStack(this._sharedUndoStack);this._controlPointsTransformTool.setSharedRedoStack(this._sharedRedoStack);this._advancedModeTransformTool.setSharedUndoStack(this._sharedUndoStack);
this._advancedModeTransformTool.setSharedRedoStack(this._sharedRedoStack);const t=n.unwrap(p.georeference),w=n.unwrap(h.mediaElement.georeference);h.view.tools.addMany([this._advancedModeTransformTool]);"controlPoints"in w&&"controlPoints"in t&&this.addHandles([h.view.on("key-down",b=>{b.key===k.undo&&this.canUndo()&&(this.undo(),b.stopPropagation());b.key===k.redo&&this.canRedo()&&(this.redo(),b.stopPropagation())}),h.view.on("focus",function(){var b=m._asyncToGenerator(function*(l){a._controlPointsTransformTool.removeHighlightActiveHandle();
a._advancedModeTransformTool.highlightActiveHandle()});return function(l){return b.apply(this,arguments)}}()),q.watch(()=>w.controlPoints,b=>{t.controlPoints=n.unwrap(b).map(({sourcePoint:l},C)=>({sourcePoint:l,mapPoint:n.unwrap(t.controlPoints)[C].mapPoint}));this._activeTool?.refresh()}),q.watch(()=>this._controlPointsTransformTool.activeHandle,b=>{this._advancedModeTransformTool.updateActiveHandle(b);this.activeHandle=b}),q.watch(()=>this._advancedModeTransformTool.activeHandle,b=>{this._controlPointsTransformTool.updateActiveHandle(b);
this.activeHandle=b})]);this.addHandles([c.on("key-down",b=>{b.key===k.undo&&this.canUndo()&&(this.undo(),b.stopPropagation());b.key===k.redo&&this.canRedo()&&(this.redo(),b.stopPropagation())}),c.on("focus",function(){var b=m._asyncToGenerator(function*(l){a._advancedModeTransformTool.removeHighlightActiveHandle();a._controlPointsTransformTool.highlightActiveHandle()});return function(l){return b.apply(this,arguments)}}())]);c.tools.addMany([this._transformTool,this._controlPointsTransformTool]);
this._activeTool=c.activeTool=this._transformTool;c.focus()};e.destroy=function(){this._transformTool?.destroy();this._controlPointsTransformTool?.destroy();this._sharedRedoStack=this._sharedUndoStack=this._activeTool=this._advancedModeTransformTool=this._controlPointsTransformTool=this._transformTool=null};e.canUndo=function(){return 0<this._sharedUndoStack.length};e.canRedo=function(){return 0<this._sharedRedoStack.length};e.undo=function(){if(0<this._sharedUndoStack.length){const {tool:a,operation:c}=
this._sharedUndoStack.pop();a!==this._activeTool&&a.refresh();c.undo();a.updateGraphics();this._sharedRedoStack.push({tool:a,operation:c});this._activeTool!==a&&this._activeTool?.refresh()}};e.redo=function(){if(0<this._sharedRedoStack.length){const {tool:a,operation:c}=this._sharedRedoStack.pop();a!==this._activeTool&&a.refresh();c.apply();a.updateGraphics();this._sharedUndoStack.push({tool:a,operation:c});this._activeTool!==a&&this._activeTool?.refresh()}};e.refresh=function(){this._activeTool.refresh()};
e.reset=function(){this._activeTool.reset();this._advancedModeTransformTool.reset()};e.enableAdvancedMode=function(){var a=m._asyncToGenerator(function*(){this._activeTool=this.view.activeTool=this._controlPointsTransformTool;this._activeTool.refresh();yield this.advancedMode.view.when();this.advancedMode.view.activeTool=this._advancedModeTransformTool;this._originalOpacity=this._controlPointsTransformTool.mediaElement.opacity;this._controlPointsTransformTool.mediaElement.opacity=.25*this._originalOpacity});
return function(){return a.apply(this,arguments)}}();e.disableAdvancedMode=function(){this._activeTool=this.view.activeTool=this._transformTool;this._activeTool.refresh();this.advancedMode.view.activeTool=null;this._controlPointsTransformTool.mediaElement.opacity=this._originalOpacity};return r}(x);f.__decorate([g.property()],d.MediaTransformToolsWrapper.prototype,"activeHandle",void 0);f.__decorate([g.property({constructOnly:!0})],d.MediaTransformToolsWrapper.prototype,"advancedMode",void 0);f.__decorate([g.property()],
d.MediaTransformToolsWrapper.prototype,"preserveAspectRatio",void 0);f.__decorate([g.property()],d.MediaTransformToolsWrapper.prototype,"snapRotation",void 0);f.__decorate([g.property({constructOnly:!0,nonNullable:!0})],d.MediaTransformToolsWrapper.prototype,"mediaElement",void 0);f.__decorate([g.property({constructOnly:!0})],d.MediaTransformToolsWrapper.prototype,"view",void 0);d.MediaTransformToolsWrapper=f.__decorate([y.subclass("esri.views.2d.interactive.editingTools.MediaTransformToolsWrapper")],
d.MediaTransformToolsWrapper);d.KEYS=k;Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});