// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../geometry ../../../../Graphic ../../../../symbols ../../../../core/analysisThemeUtils ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/unitUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec2 ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../chunks/boundedPlane ../../../../geometry/support/spatialReferenceUtils ../../../../layers/GraphicsLayer ../../../ViewingMode ./manipulations/DragManipulation ./manipulations/RotateManipulation ./manipulations/ScaleManipulation ./manipulations/utils ../../../input/keys ../../../interactive/InteractiveToolBase ../../../interactive/editGeometry/EditGeometry ../../../interactive/editGeometry/EditGeometryOperations ../../../interactive/editGeometry/interfaces ../../../interactive/editGeometry/operations/UpdateVertices ../../../interactive/editGeometry/support/editPlaneUtils ../../../support/hitTestSelectUtils ../../../support/screenUtils ../../../../geometry/Polygon ../../../../geometry/Point ../../../../symbols/SimpleFillSymbol ../../../../symbols/SimpleMarkerSymbol".split(" "),
function(l,x,p,fa,z,ha,y,m,N,D,t,ia,ja,O,E,F,h,q,B,C,P,Q,G,R,S,T,H,U,V,W,X,I,Y,Z,aa,ba,ca,r,da,J){const n={up:"ArrowUp",down:"ArrowDown",left:"ArrowLeft",right:"ArrowRight",plus:"+",minus:"-",toggleOpacity:"t",shift:"Shift",primaryKey:U.primaryKey},ea=[[1,1],[1,-1],[-1,-1],[-1,1],[1,0],[0,-1],[-1,0],[0,1]];l.TransformTool=function(K){function A(a){a=K.call(this,a)||this;a._initialControlPoints=null;a._initialGeometry=null;a._graphic=null;a._planeCache=C.create();a._displayPlaneCache=C.create();a._mainAxisCache=
F.create();a._rotationHandleCache=q.create();a._cornerA=q.create();a._cornerB=q.create();a._cornerC=q.create();a._cornerD=q.create();a._avgAB=q.create();a._avgBC=q.create();a._avgCD=q.create();a._avgDA=q.create();a._preserveAspectRatio=new H.PreserveAspectRatio;a._snapRotation=new H.SnapRotation;a._graphicsLayer=new Q({internal:!0,listMode:"hide",visible:!1});a._sharedUndoStack=[];a._sharedRedoStack=[];a._isOpacityToggled=!1;a._isModifierActive=!1;a._factor=1;a.preserveAspectRatio=null;a.snapRotation=
null;return a}x._inheritsLoose(A,K);var f=A.prototype;f.initialize=function(){this._initialize()};f.destroy=function(){const {map:a}=this.view;this._dragManipulation.destroy();this._rotateManipulation.destroy();this._scaleManipulations.forEach(b=>b.destroy());this._editGeometryOperations.destroy();a.removeMany([this._graphicsLayer]);this._graphicsLayer.removeAll();this._graphicsLayer=m.destroyMaybe(this._graphicsLayer);this._sharedRedoStack=this._sharedUndoStack=this._avgDA=this._avgCD=this._avgBC=
this._avgAB=this._cornerD=this._cornerC=this._cornerB=this._cornerA=this._mainAxisCache=this._rotationHandleCache=this._displayPlaneCache=this._planeCache=this._snapRotation=this._preserveAspectRatio=this._graphic=this._initialGeometry=this._initialControlPoints=null};f.onActivate=function(){this.visible=!0};f.onDeactivate=function(){this.visible=!1};f.onShow=function(){this._graphicsLayer.visible=!0};f.onHide=function(){this._graphicsLayer.visible=!1};f.canUndo=function(){return this._editGeometryOperations.canUndo};
f.canRedo=function(){return this._editGeometryOperations.canRedo};f.undo=function(){this._editGeometryOperations.undo();this.updateGraphics()};f.redo=function(){this._editGeometryOperations.redo();this.updateGraphics()};f.refresh=function(){const {view:a,target:b}=this,d="georeference"in b?m.unwrap(m.unwrap(b.georeference).coords):b.geometry,e=this._editGeometryOperations,k=e.data.components[0].vertices,c=W.EditGeometry.fromGeometry(B.project(d,a.spatialReference),G.ViewingMode.Local).components[0].vertices;
k.forEach((g,u)=>{e.setVertexPosition(g,c[u].pos)});this.updateGraphics()};f.reset=function(){var {target:a}=this;"georeference"in a?(a=m.unwrap(a.georeference),"control-points"===a.type&&(a.controlPoints=this._initialControlPoints)):a.geometry=this._initialGeometry;this.refresh();this._sharedUndoStack.length=0;this._sharedRedoStack.length=0};f.updateGraphics=function(){const a=this._editGeometryOperations.data.geometry;"georeference"in this.target&&(m.unwrap(this.target.georeference).coords=a);this._graphic.geometry=
a;this._backgroundGraphic.geometry=this._backgroundGraphicGeometry;this._rotateGraphic.geometry=this._rotateGraphicGeometry;this._scaleGraphicGeometries.forEach((b,d)=>{this._scaleGraphics[d].geometry=b})};f.setSharedUndoStack=function(a){this._sharedUndoStack=a};f.setSharedRedoStack=function(a){this._sharedRedoStack=a};f._initialize=function(){var a=x._asyncToGenerator(function*(){var b=this;const {view:d,target:e}=this;if("georeference"in e){const c=m.unwrap(e.georeference);this._graphic=new z({geometry:m.unwrap(c.coords)});
this._initialControlPoints="control-points"===c.type?c.controlPoints:null}else this._graphic=e,this._initialGeometry=m.unwrap(e.geometry);d.map.addMany([this._graphicsLayer]);d.focus();this.visible=!1;this.finishToolCreation();yield this._loadProjectionEngine();this._editGeometryOperations=X.EditGeometryOperations.fromGeometry(B.project(this._graphic.geometry,d.spatialReference),G.ViewingMode.Local);this._backgroundGraphic=new z({symbol:new da({color:"transparent",outline:{type:"simple-line",color:y.getAccentColor(),
width:2}}),geometry:this._backgroundGraphicGeometry});this._rotateGraphic=new z({symbol:new J({color:y.getContrastColor(),outline:{type:"simple-line",color:y.getAccentColor(),width:1}}),geometry:this._rotateGraphicGeometry});this._scaleGraphics=this._scaleGraphicGeometries.map(c=>new z({symbol:new J({size:6,style:"square",color:y.getContrastColor(),outline:{type:"simple-line",color:y.getAccentColor(),width:1}}),geometry:c}));this._graphicsLayer.graphics.addMany([this._backgroundGraphic,this._rotateGraphic,
...this._scaleGraphics]);this._dragManipulation=new R.DragManipulation({tool:this,view:d,graphic:this._graphic});this._rotateManipulation=new S.RotateManipulation({tool:this,view:d,graphic:this._rotateGraphic,snapRotation:this._snapRotation});this._scaleManipulations=this._scaleGraphics.map((c,g)=>new T.ScaleManipulation({tool:this,view:d,graphic:c,direction:ea[g],preserveAspectRatio:this._preserveAspectRatio}));this.addHandles([this._dragManipulation.createDragPipeline(this._getInfo.bind(this),this._updateGraphics.bind(this)),
this._rotateManipulation.createDragPipeline(this._getInfo.bind(this),this._updateGraphics.bind(this)),...this._scaleManipulations.map(c=>c.createDragPipeline(this._getInfo.bind(this),this._updateGraphics.bind(this))),N.watch(()=>this.view.scale,()=>this.active?this.updateGraphics():null),d.on("click",function(){var c=x._asyncToGenerator(function*(g){if(null==d.activeTool||d.activeTool===b){g=ba.createScreenPointFromEvent(g);var u=[];d.map.allLayers.forEach(w=>{"vector-tile"!==w.type&&"imagery"!==
w.type||u.push(w)});g=yield b.view.hitTest(g,{exclude:u});var v=g.results;if(0===v.length)d.activeTool=null;else{g=aa.findFirstGraphicHit(g.results);const w="georeference"in e;v=v.map(L=>"media"===L.type?L.element:null).filter(Boolean);const M=[...b._graphicsLayer.graphics,w?null:e].filter(Boolean);(w?v.includes(e)||m.isSome(g)&&M.includes(g.graphic):m.isSome(g)&&M.includes(g.graphic))?null==d.activeTool&&(d.activeTool=b):d.activeTool=null}}});return function(g){return c.apply(this,arguments)}}())]);
const k=c=>{this.addHandles(c.events.on("grab-changed",g=>{"georeference"in e&&("start"===g.action?e.opacity*=.5:"end"===g.action&&(e.opacity*=2))}))};this._dragManipulation.forEachManipulator(k);this._rotateManipulation.forEachManipulator(k);this._scaleManipulations.forEach(c=>c.forEachManipulator(k));this.addHandles([d.on("key-down",c=>{d.activeTool===this&&(c.key!==n.shift||c.repeat||(null==this.preserveAspectRatio&&(this._preserveAspectRatio.enabled=!this._preserveAspectRatio.enabled),null==this.snapRotation&&
(this._snapRotation.enabled=!this._snapRotation.enabled),this._isModifierActive=!0,c.stopPropagation()),c.key!==n.toggleOpacity||c.repeat||("georeference"in e&&(e.opacity*=this._isOpacityToggled?2:.5,this._isOpacityToggled=!this._isOpacityToggled),c.stopPropagation()),c.key!==n.primaryKey||c.repeat||(this._factor=10,c.stopPropagation()),this._isModifierActive&&(c.key===n.plus&&(this._scale(this._factor),c.stopPropagation()),c.key===n.minus&&(this._scale(-this._factor),c.stopPropagation()),c.key===
n.up&&(this._move(0,this._factor),c.stopPropagation()),c.key===n.down&&(this._move(0,-this._factor),c.stopPropagation()),c.key===n.left&&(this._move(-this._factor,0),c.stopPropagation()),c.key===n.right&&(this._move(this._factor,0),c.stopPropagation())))}),d.on("key-up",c=>{d.activeTool===this&&(c.key===n.shift&&(null==this.preserveAspectRatio&&(this._preserveAspectRatio.enabled=!this._preserveAspectRatio.enabled),null==this.snapRotation&&(this._snapRotation.enabled=!this._snapRotation.enabled),this._isModifierActive=
!1,c.stopPropagation()),c.key===n.primaryKey&&(this._factor=1,c.stopPropagation()))})])});return function(){return a.apply(this,arguments)}}();f._loadProjectionEngine=function(){var a=x._asyncToGenerator(function*(){const b=m.unwrap(this._graphic.geometry);return B.initializeProjection(b.spatialReference,this.view.spatialReference)});return function(){return a.apply(this,arguments)}}();f._updateDisplayPlaneConrers=function(a){const {basis1:b,basis2:d,origin:e}=a;a=this._cornerA;h.add(a,e,b);h.add(a,
a,d);a=this._cornerB;h.add(a,e,b);h.subtract(a,a,d);a=this._cornerC;h.subtract(a,e,b);h.subtract(a,a,d);a=this._cornerD;h.subtract(a,e,b);h.add(a,a,d)};f._getInfo=function(){return{editGeometryOperations:this._editGeometryOperations,plane:this._plane,displayPlane:this._displayPlane}};f._updateGraphics=function(a,b){"start"===a.action&&(this._sharedUndoStack.push({tool:this,operation:b}),this._sharedRedoStack.length=0);this.updateGraphics()};f._scale=function(a){var b=this._editGeometryOperations;
const d=[];for(var e of b.data.components)d.push(...e.vertices);e=b.data.geometry.extent?.width;a=(e+a*this.view.resolution)/e;b=b.scaleVertices(d,this._plane.origin,F.UNIT_X,a,a,I.AccumulationBehaviour.NEW_STEP,Y.AccumulationType.REPLACE);this._sharedUndoStack.push({tool:this,operation:b});this._sharedRedoStack.length=0;this.updateGraphics()};f._move=function(a,b){const d=this._editGeometryOperations,e=[];for(const k of d.data.components)e.push(...k.vertices);a=d.moveVertices(e,a*this.view.resolution,
b*this.view.resolution,0,I.AccumulationBehaviour.NEW_STEP);this._sharedUndoStack.push({tool:this,operation:a});this._sharedRedoStack.length=0;this.updateGraphics()};x._createClass(A,[{key:"_plane",get:function(){const a=this._graphic.geometry;if(!m.isSome(a))return null;const b=this._editGeometryOperations.data;var d=b.components[0].edges[0];d=E.subtract(this._mainAxisCache,d.leftVertex.pos,d.rightVertex.pos);E.normalize(d,d);let e=80*this.view.resolution;const k=this.view.spatialReference;P.equals(k,
a.spatialReference)&&(e*=D.getMetersPerUnitForSR(k)/D.getMetersPerUnitForSR(a.spatialReference));return Z.calculateOrientedBounds(d,b,e,this._planeCache)}},{key:"_displayPlane",get:function(){var a=this._plane;if(!a)return null;const b=this._displayPlaneCache;C.copy(a,b);a=10*this.view.resolution;h.scale(b.basis1,b.basis1,1+a/h.length(b.basis1));h.scale(b.basis2,b.basis2,1+a/h.length(b.basis2));return b}},{key:"_backgroundGraphicGeometry",get:function(){const a=this._displayPlane;if(!a)return null;
const b=this.view.spatialReference;this._updateDisplayPlaneConrers(a);return new ca({spatialReference:b,rings:[[this._cornerA,this._cornerB,this._cornerC,this._cornerD,this._cornerA]]})}},{key:"_rotateGraphicGeometry",get:function(){const a=this._plane;if(!a)return null;const b=this._rotationHandleCache;h.normalize(b,a.basis1);h.scale(b,b,30*this.view.resolution);h.add(b,b,a.origin);h.add(b,b,a.basis1);return new r({x:b[0],y:b[1],spatialReference:this.view.spatialReference})}},{key:"_scaleGraphicGeometries",
get:function(){var a=this._displayPlane;if(!a)return[];const b=this.view.spatialReference;this._updateDisplayPlaneConrers(a);const {_cornerA:d,_cornerB:e,_cornerC:k,_cornerD:c}=this;a=h.lerp(this._avgAB,d,e,.5);const g=h.lerp(this._avgBC,e,k,.5),u=h.lerp(this._avgCD,k,c,.5),v=h.lerp(this._avgDA,c,d,.5);return[new r({x:d[0],y:d[1],spatialReference:b}),new r({x:e[0],y:e[1],spatialReference:b}),new r({x:k[0],y:k[1],spatialReference:b}),new r({x:c[0],y:c[1],spatialReference:b}),new r({x:a[0],y:a[1],spatialReference:b}),
new r({x:g[0],y:g[1],spatialReference:b}),new r({x:u[0],y:u[1],spatialReference:b}),new r({x:v[0],y:v[1],spatialReference:b})]}}]);return A}(V.InteractiveToolBase);p.__decorate([t.property()],l.TransformTool.prototype,"_plane",null);p.__decorate([t.property()],l.TransformTool.prototype,"_backgroundGraphicGeometry",null);p.__decorate([t.property()],l.TransformTool.prototype,"_rotateGraphicGeometry",null);p.__decorate([t.property()],l.TransformTool.prototype,"_scaleGraphicGeometries",null);p.__decorate([t.property()],
l.TransformTool.prototype,"preserveAspectRatio",void 0);p.__decorate([t.property()],l.TransformTool.prototype,"snapRotation",void 0);p.__decorate([t.property({constructOnly:!0,nonNullable:!0})],l.TransformTool.prototype,"target",void 0);p.__decorate([t.property({constructOnly:!0})],l.TransformTool.prototype,"view",void 0);l.TransformTool=p.__decorate([O.subclass("esri.views.2d.interactive.editingTools.TransformTool")],l.TransformTool);l.KEYS=n;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});