// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../PixelBlock","../rasterFormats/pixelRangeUtils"],function(z,E,F,S){function G(a){return E.isSome(a)&&"esri.layers.support.PixelBlock"===a.declaredClass&&a.pixels&&0<a.pixels.length}function Q(a,b,c,d,f){const e=a.length;f=F.createEmptyBand(f,e);if(b)for(let h=0;h<e;h++)b[h]&&(f[h]=c[a[h]-d]);else for(b=0;b<e;b++)f[b]=c[a[b]-d];return f}function T(a,b,c,d){const f=null!=c&&2<=c.length?new Set(c):null;c=1===c?.length?c[0]:null;const e=!!b?.length;for(let h=
0;h<a.length;h++)if(d[h]){const l=a[h];if(e){let g=!1;for(let p=0;p<b.length;p+=2)if(l>=b[p]&&l<=b[p+1]){g=!0;break}g||(d[h]=0)}d[h]&&(l===c||f?.has(l))&&(d[h]=0)}}function U(a,b){const c=a[0].length;for(let d=0;d<c;d++)if(b[d]){let f=!1;for(let e=0;e<a.length;e++)if(a[e][d]){f=!0;break}f||(b[d]=0)}}function V(a,b){const c=a[0].length;for(let d=0;d<c;d++)if(b[d]){let f=!1;for(let e=0;e<a.length;e++)if(0===a[e][d]){f=!0;break}f&&(b[d]=0)}}function W(a,b,c,d,f,e,h,l){return{xmin:f<=c*a?0:f<c*a+a?f-
c*a:a,ymin:e<=d*b?0:e<d*b+b?e-d*b:b,xmax:f+h<=c*a?0:f+h<c*a+a?f+h-c*a:a,ymax:e+l<=d*b?0:e+l<d*b+b?e+l-d*b:b}}function M(a,b,c,d,f,e){const {width:h,height:l}=c.block,{x:g,y:p}=c.offset,{width:n,height:q}=c.mosaic;c=W(h,l,d,f,g,p,n,q);let k=0;var m=0;if(e){var r=e.hasGCSSShiftTransform?360:e.halfWorldWidth??0,t=h*e.resolutionX;const u=e.startX+d*t;u<r&&u+t>r?m=e.rightPadding:u>=r&&(k=e.leftMargin-e.rightPadding,m=0)}c.xmax-=m;if("number"===typeof b)for(e=c.ymin;e<c.ymax;e++)for(m=(f*l+e-p)*n+(d*h-
g)+k,r=c.xmin;r<c.xmax;r++)a[m+r]=b;else for(e=c.ymin;e<c.ymax;e++)for(m=(f*l+e-p)*n+(d*h-g)+k,r=e*h,t=c.xmin;t<c.xmax;t++)a[m+t]=b[r+t]}function X(a,b,c={}){const {clipOffset:d,clipSize:f,alignmentInfo:e,blockWidths:h}=c;if(h)return ca(a,b,{blockWidths:h});var l=a.find(w=>G(w));if(E.isNone(l))return null;c=f?f.width:b.width;const g=f?f.height:b.height;var p=l.width,n=l.height;const q=b.width/p,k=b.height/n;b={offset:d||{x:0,y:0},mosaic:f||b,block:{width:p,height:n}};p=l.pixelType;n=F.getPixelArrayConstructor(p);
var m=l.pixels.length;l=[];for(var r=0;r<m;r++){var t=new n(c*g);for(let w=0;w<k;w++)for(let x=0;x<q;x++){var u=a[w*q+x];G(u)&&(u=u.pixels[r],M(t,u,b,x,w,e))}l.push(t)}let v;if(a.some(w=>E.isNone(w)||E.isSome(w.mask)&&0<w.mask.length))for(v=new Uint8Array(c*g),n=0;n<k;n++)for(m=0;m<q;m++)t=a[n*q+m],r=E.isSome(t)?t.mask:null,E.isSome(r)?M(v,r,b,m,n,e):t?M(v,1,b,m,n,e):M(v,0,b,m,n,e);a=new F({width:c,height:g,pixels:l,pixelType:p,mask:v});a.updateStatistics();return a}function ca(a,b,c){const d=a.find(m=>
E.isSome(m));if(E.isNone(d))return null;var f=a.some(m=>E.isSome(m)?!!m.mask:!0);const {width:e,height:h}=b;b=f?new Uint8Array(e*h):null;({blockWidths:c}=c);const l=[],g=d.getPlaneCount(),p=F.getPixelArrayConstructor(d.pixelType);if(f)for(let m=0,r=0;m<a.length;r+=c[m],m++)if(f=a[m],G(f)){var n=E.unwrap(f.mask);for(var q=0;q<h;q++)for(var k=0;k<c[m];k++)b[q*e+k+r]=null==n?255:n[q*f.width+k]}for(f=0;f<g;f++){n=new p(e*h);for(let m=0,r=0;m<a.length;r+=c[m],m++)if(q=a[m],G(q)&&(k=q.pixels[f],null!=k))for(let t=
0;t<h;t++)for(let u=0;u<c[m];u++)n[t*e+u+r]=k[t*q.width+u];l.push(n)}a=new F({width:e,height:h,mask:b,pixels:l,pixelType:d.pixelType});a.updateStatistics();return a}function Y(a){if(!G(a))return null;const b=a.clone(),{width:c,height:d,pixels:f}=a;var e=f[0];const h=b.pixels[0];a=E.unwrap(a.mask);for(let p=2;p<d-1;p++){const n=new Map;for(var l=p-2;l<p+2;l++)for(var g=0;4>g;g++){const q=l*c+g;L(n,e[q],a?a[q]:1)}h[p*c]=Z(n);h[p*c+1]=h[p*c+2]=h[p*c];for(l=3;l<c-1;l++)g=(p-2)*c+l+1,L(n,e[g],a?a[g]:1),
g=(p-1)*c+l+1,L(n,e[g],a?a[g]:1),g=p*c+l+1,L(n,e[g],a?a[g]:1),g=(p+1)*c+l+1,L(n,e[g],a?a[g]:1),g=(p-2)*c+l-3,N(n,e[g],a?a[g]:1),g=(p-1)*c+l-3,N(n,e[g],a?a[g]:1),g=p*c+l-3,N(n,e[g],a?a[g]:1),g=(p+1)*c+l-3,N(n,e[g],a?a[g]:1),h[p*c+l]=Z(n);h[p*c+l+1]=h[p*c+l]}for(e=0;e<c;e++)h[e]=h[c+e]=h[2*c+e],h[(d-1)*c+e]=h[(d-2)*c+e];b.updateStatistics();return b}function Z(a){if(0===a.size)return 0;let b=0,c=-1,d=0;const f=a.keys();let e=f.next();for(;!e.done;)d=a.get(e.value),d>b&&(c=e.value,b=d),e=f.next();return c}
function N(a,b,c){0!==c&&(c=a.get(b),1===c?a.delete(b):a.set(b,c-1))}function L(a,b,c){0!==c&&a.set(b,a.has(b)?a.get(b)+1:1)}function aa(a,b,c){let {x:d,y:f}=b;const {width:e,height:h}=c;if(0===d&&0===f&&h===a.height&&e===a.width)return a;const {width:l,height:g}=a;b=Math.max(0,f);const p=Math.max(0,d),n=Math.min(d+e,l),q=Math.min(f+h,g);if(0>n||0>q||!G(a))return null;d=Math.max(0,-d);f=Math.max(0,-f);var {pixels:k}=a,m=e*h,r=k.length;const t=[];for(var u=0;u<r;u++){var v=k[u],w=F.createEmptyBand(a.pixelType,
m);for(let x=b;x<q;x++){const y=x*l;let A=(x+f-b)*e+d;for(let D=p;D<n;D++)w[A++]=v[y+D]}t.push(w)}k=new Uint8Array(m);m=E.unwrap(a.mask);for(r=b;r<q;r++)for(u=r*l,v=(r+f-b)*e+d,w=p;w<n;w++)k[v++]=m?m[u+w]:1;a=new F({width:c.width,height:c.height,pixelType:a.pixelType,pixels:t,mask:k});a.updateStatistics();return a}function da(a,b=!0){if(!G(a))return null;const {pixels:c,width:d,height:f,mask:e,pixelType:h}=a;a=[];const l=Math.round(d/2),g=Math.round(f/2),p=f-1,n=d-1;for(var q=0;q<c.length;q++){var k=
c[q],m=F.createEmptyBand(h,l*g),r=0;for(var t=0;t<f;t+=2)for(var u=0;u<d;u+=2){var v=k[t*d+u];if(b){var w=u===n?v:k[t*d+u+1];const x=t===p?v:k[t*d+u+d],y=u===n?x:t===p?w:k[t*d+u+d+1];m[r++]=(v+w+x+y)/4}else m[r++]=v}a.push(m)}q=null;if(E.isSome(e))for(q=new Uint8Array(l*g),k=0,m=0;m<f;m+=2)for(r=0;r<d;r+=2)t=e[m*d+r],b?(u=r===n?t:e[m*d+r+1],v=m===p?t:e[m*d+r+d],w=r===n?v:m===p?u:e[m*d+r+d+1],q[k++]=t*u*v*w?1:0):q[k++]=t;return new F({width:l,height:g,pixelType:h,pixels:a,mask:q})}function R(a,b,c,
d,f=0){const {width:e,height:h}=a,{width:l,height:g}=b;a=d.cols;d=d.rows;b=Math.ceil(l/a-.1/a);const p=Math.ceil(g/d-.1/d);let n,q,k,m,r;const t=b*a;var u=t*p*d;const v=new Float32Array(u),w=new Float32Array(u),x=new Uint32Array(u),y=new Uint32Array(u);let A=0,D,K;for(let I=0;I<p;I++)for(let J=0;J<b;J++){var B=12*(I*b+J);u=c[B];n=c[B+1];q=c[B+2];k=c[B+3];m=c[B+4];r=c[B+5];for(var C=0;C<d;C++){A=(I*d+C)*t+J*a;K=(C+.5)/d;for(let H=0;H<C;H++)D=(H+.5)/a,v[A+H]=(u*D+n*K+q)*e+f,w[A+H]=(k*D+m*K+r)*h+f,x[A+
H]=Math.floor(v[A+H]),y[A+H]=Math.floor(w[A+H])}B+=6;u=c[B];n=c[B+1];q=c[B+2];k=c[B+3];m=c[B+4];r=c[B+5];for(B=0;B<d;B++)for(A=(I*d+B)*t+J*a,K=(B+.5)/d,C=B;C<a;C++)D=(C+.5)/a,v[A+C]=(u*D+n*K+q)*e+f,w[A+C]=(k*D+m*K+r)*h+f,x[A+C]=Math.floor(v[A+C]),y[A+C]=Math.floor(w[A+C])}return{offsets_x:v,offsets_y:w,offsets_xi:x,offsets_yi:y,gridWidth:t}}z.NoDataInterpretation=void 0;(function(a){a[a.matchAny=0]="matchAny";a[a.matchAll=1]="matchAll"})(z.NoDataInterpretation||(z.NoDataInterpretation={}));z.MissingBandAction=
void 0;(function(a){a[a.bestMatch=0]="bestMatch";a[a.fail=1]="fail"})(z.MissingBandAction||(z.MissingBandAction={}));z.MAX_MAP_SIZE_GPU=6;z.approximateTransform=function(a,b,c,d,f="nearest"){if(!G(a))return null;"majority"===f&&(a=Y(a));const {pixels:e,mask:h,pixelType:l}=a,g=a.width;var p=a.height;const n=F.getPixelArrayConstructor(l),q=e.length,{width:k,height:m}=b;a=!1;for(let y=0;y<c.length;y+=3)-1===c[y]&&-1===c[y+1]&&-1===c[y+2]&&(a=!0);const {offsets_x:r,offsets_y:t,offsets_xi:u,offsets_yi:v,
gridWidth:w}=R({width:g,height:p},b,c,d,"majority"===f?.5:0);let x;b=(y,A,D)=>{const K=y instanceof Float32Array||y instanceof Float64Array?0:.5;for(let B=0;B<m;B++){x=B*w;for(let C=0;C<k;C++){if(0>r[x]||0>t[x])y[B*k+C]=0;else if(D)y[B*k+C]=A[u[x]+v[x]*g];else{const I=Math.floor(r[x]),J=Math.floor(t[x]),H=Math.ceil(r[x]),O=Math.ceil(t[x]),P=r[x]-I,ba=t[x]-J;y[B*k+C]=!h||h[I+J*g]&&h[I+J*g]&&h[I+O*g]&&h[H+O*g]?(1-ba)*((1-P)*A[I+J*g]+P*A[H+J*g])+ba*((1-P)*A[I+O*g]+P*A[H+O*g])+K:A[u[x]+v[x]*g]}x++}}};
c=[];for(p=0;p<q;p++)d=new n(k*m),b(d,e[p],"nearest"===f||"majority"===f),c.push(d);f=new F({width:k,height:m,pixelType:l,pixels:c});if(E.isSome(h))f.mask=new Uint8Array(k*m),b(f.mask,h,!0);else if(a)for(f.mask=new Uint8Array(k*m),a=0;a<k*m;a++)f.mask[a]=0>r[a]||0>t[a]?0:1;f.updateStatistics();return f};z.clip=aa;z.colorize=function(a,b){if(!G(a)||!b||!b.indexedColormap&&!b.indexed2DColormap)return a;const c=a.clone();var d=c.pixels;let f=c.mask;const e=c.width*c.height;if(1!==d.length)return a;const {indexedColormap:h,
indexed2DColormap:l,offset:g,alphaSpecified:p}=b;a=0;d=d[0];b=new Uint8Array(d.length);const n=new Uint8Array(d.length),q=new Uint8Array(d.length);var k=0;if(h){const m=h.length-1;if(E.isSome(f))for(a=0;a<e;a++)f[a]&&(k=4*(d[a]-g),k<g||k>m?f[a]=0:(b[a]=h[k],n[a]=h[k+1],q[a]=h[k+2],f[a]=h[k+3]));else{f=new Uint8Array(e);for(a=0;a<e;a++)k=4*(d[a]-g),k<g||k>m?f[a]=0:(b[a]=h[k],n[a]=h[k+1],q[a]=h[k+2],f[a]=h[k+3]);c.mask=f}}else if(l)if(E.isSome(f))for(a=0;a<e;a++)f[a]&&(k=l[d[a]],b[a]=k[0],n[a]=k[1],
q[a]=k[2],f[a]=k[3]);else{f=new Uint8Array(e);for(a=0;a<e;a++)k=l[d[a]],b[a]=k[0],n[a]=k[1],q[a]=k[2],f[a]=k[3];c.mask=f}c.pixels=[b,n,q];c.statistics=null;c.pixelType="u8";c.maskIsAlpha=p;return c};z.compositeBands=function(a){if(!a?.length||a.some(g=>!G(g)))return null;if(1===a.length)return E.isSome(a[0])?a[0].clone():null;const {width:b,height:c,pixelType:d}=a[0];if(a.some(g=>g.width!==b||g.height!==c))return null;const f=a.map(({mask:g})=>g).filter(g=>null!=g);let e=null;f.length&&(e=new Uint8Array(b*
c),e.set(f[0]),1<f.length&&V(f.slice(1),e));const h=[];a.forEach(({pixels:g})=>h.push(...g));const l=[];a.map(({statistics:g})=>g).filter(g=>g?.length).forEach(g=>l.push(...g));return new F({pixelType:d,width:b,height:c,mask:e,pixels:h,statistics:l.length?l:null})};z.createColormapLUT=function(a){if(a){var b=a.colormap;if(b&&0!==b.length){b=b.sort((p,n)=>p[0]-n[0]);var c=0;0>b[0][0]&&(c=b[0][0]);var d=Math.max(256,b[b.length-1][0]-c+1),f=new Uint8Array(4*d),e=[],h=0,l=0,g=5===b[0].length;if(65536<
d)return b.forEach(p=>{e[p[0]-c]=g?p.slice(1):p.slice(1).concat([255])}),{indexed2DColormap:e,offset:c,alphaSpecified:g};if(a.fillUnspecified)for(a=b[l],h=a[0]-c;h<d;h++)f[4*h]=a[1],f[4*h+1]=a[2],f[4*h+2]=a[3],f[4*h+3]=g?a[4]:255,h===a[0]-c&&(a=l===b.length-1?a:b[++l]);else for(h=0;h<b.length;h++)a=b[h],l=4*(a[0]-c),f[l]=a[1],f[l+1]=a[2],f[l+2]=a[3],f[l+3]=g?a[4]:255;return{indexedColormap:f,offset:c,alphaSpecified:g}}}};z.createMaskLUT=function(a,b,c){if("u8"!==a&&"s8"!==a&&"u16"!==a&&"s16"!==a)return null;
var d=a.includes("16")?65536:256;a=a.includes("s")?-d/2:0;d=new Uint8Array(d);if(b)for(let e=0;e<b.length;e++){var f=Math.ceil(b[2*e]-a);const h=Math.floor(b[2*e+1]-a);for(;f<=h;f++)d[f]=255}else d.fill(255);if(c)for(b=0;b<c.length;b++)d[c[b]-a]=0;return{lut:d,offset:a}};z.createRemapLUT=function(a){const {srcPixelType:b,inputRanges:c,outputValues:d,allowUnmatched:f,noDataRanges:e,isLastInputRangeInclusive:h,outputPixelType:l}=a;if("u8"!==b&&"s8"!==b&&"u16"!==b&&"s16"!==b)return null;var g=b.includes("16")?
65536:256;a=b.includes("s")?-g/2:0;const p=F.createEmptyBand(l,g);g=new Uint8Array(g);f&&g.fill(255);const [n,q]=S.getPixelValueRange(l);if(c?.length&&d?.length){var k=c.map(u=>u-1E-6);k[0]=c[0];h&&(k[k.length-1]=c[c.length-1]);for(var m=0;m<k.length;m++){var r=d[m]>q?q:d[m]<n?n:d[m],t=Math.ceil(k[2*m]-a);const u=Math.floor(k[2*m+1]-a);for(;t<=u;t++)p[t]=r,g[t]=255}}if(e?.length)for(k=0;k<e.length;k++)for(r=Math.ceil(e[2*k]-a),m=Math.floor(e[2*k+1]-a);r<=m;r++)g[r]=0;return{lut:p,offset:a,mask:g}};
z.extractBands=function(a,b){if(!b?.length||!G(a))return a;const c=a.pixels.length;return b&&b.some(d=>d>=c)||1===c&&1===b.length&&0===b[0]||c===b.length&&!b.some((d,f)=>d!==f)?a:new F({pixelType:a.pixelType,width:a.width,height:a.height,mask:a.mask,validPixelCount:a.validPixelCount,maskIsAlpha:a.maskIsAlpha,pixels:b.map(d=>a.pixels[d]),statistics:a.statistics&&b.map(d=>a.statistics[d])})};z.getClipBounds=W;z.getLocalArithmeticNorthRotations=function(a,b){const {coefficients:c,spacing:d}=b,{offsets_x:f,
offsets_y:e,gridWidth:h}=R(a,a,c,{rows:d[0],cols:d[1]}),{width:l,height:g}=a;a=new Float32Array(l*g);b=180/Math.PI;for(let q=0;q<g;q++)for(let k=0;k<l;k++){var p=q*h+k,n=0===q?p:p-h;const m=q===g-1?p:p+h;p=f[n]-f[m];n=e[m]-e[n];isNaN(p)||isNaN(n)?a[q*l+k]=90:(n=Math.atan2(n,p)*b,n=(360+n)%360,a[q*l+k]=n)}return a};z.interpolateOffsets=R;z.isValidPixelBlock=G;z.lookupBandValues=Q;z.lookupPixels=function(a,b){if(!G(a))return null;const {pixels:c,mask:d}=a,f=c.length;let e=b.lut;const {offset:h}=b;e&&
1===e[0].length&&(e=c.map(()=>e));const l=[];b=b.outputPixelType||"u8";for(let g=0;g<f;g++){const p=Q(c[g],d,e[g],h||0,b);l.push(p)}a=new F({width:a.width,height:a.height,pixels:l,mask:d,pixelType:b});a.updateStatistics();return a};z.mask=function(a,b){if(!G(a))return null;const {width:c,height:d,pixels:f}=a;var e=c*d;const h=new Uint8Array(e);a.mask?h.set(a.mask):h.fill(255);a=f.length;const {includedRanges:l,noDataValues:g,outputPixelType:p,matchAll:n,lookups:q}=b;if(q){e=[];for(b=0;b<a;b++){var k=
q[b];k=Q(f[b],h,k.lut,k.offset||0,"u8");e.push(k)}1===e.length?h.set(e[0]):n?U(e,h):V(e,h)}else if(n){b=[];for(k=0;k<a;k++){const m=new Uint8Array(e);m.set(h);T(f[k],l?.slice(2*k,2*k+2),g?.[k],m);b.push(m)}1===b.length?h.set(b[0]):U(b,h)}else for(e=0;e<a;e++)T(f[e],l?.slice(2*e,2*e+2),g?.[e],h);return new F({width:c,height:d,pixelType:p,pixels:f,mask:h})};z.mosaic=X;z.mosaicPixelData=function(a,b){if(!a||0===a.length)return null;var c=a.find(q=>q.pixelBlock);if(!c||E.isNone(c.pixelBlock))return null;
var d=(c.extent.xmax-c.extent.xmin)/c.pixelBlock.width;const f=(c.extent.ymax-c.extent.ymin)/c.pixelBlock.height,e=.01*Math.min(d,f),h=a.sort((q,k)=>Math.abs(q.extent.ymax-k.extent.ymax)>e?k.extent.ymax-q.extent.ymax:Math.abs(q.extent.xmin-k.extent.xmin)>e?q.extent.xmin-k.extent.xmin:0);var l=Math.min.apply(null,h.map(q=>q.extent.xmin));const g=Math.min.apply(null,h.map(q=>q.extent.ymin)),p=Math.max.apply(null,h.map(q=>q.extent.xmax)),n=Math.max.apply(null,h.map(q=>q.extent.ymax));a={x:Math.round((b.xmin-
l)/d),y:Math.round((n-b.ymax)/f)};l={width:Math.round((p-l)/d),height:Math.round((n-g)/f)};d={width:Math.round((b.xmax-b.xmin)/d),height:Math.round((b.ymax-b.ymin)/f)};if(Math.round(l.width/c.pixelBlock.width)*Math.round(l.height/c.pixelBlock.height)!==h.length||0>a.x||0>a.y||l.width<d.width||l.height<d.height)return null;c=h.map(q=>q.pixelBlock);c=X(c,l,{clipOffset:a,clipSize:d});return{extent:b,pixelBlock:c}};z.remap=function(a,b){if(!G(a))return null;const {width:c,height:d}=a,{inputRanges:f,outputValues:e,
outputPixelType:h,noDataRanges:l,allowUnmatched:g,isLastInputRangeInclusive:p}=b;b=a.pixels[0];const n=F.createEmptyBand(h,b.length),q=a.mask,k=new Uint8Array(c*d);q?k.set(q):k.fill(255);const m=a.pixelType.startsWith("f")?1E-6:0;var r=f.map(A=>A-m);r[0]=f[0];r[r.length-1]=f[f.length-1]+(p?1E-6:0);a=f.length/2;const [t,u]=S.getPixelValueRange(h);for(var v=0;v<d;v++)for(var w=0;w<c;w++){var x=v*c+w;if(k[x]){var y=b[x];let A=!1;for(let D=a-1;0<=D;D--)if(y===r[2*D]||y>r[2*D]&&y<r[2*D+1]){n[x]=e[D];A=
!0;break}A||(g?n[x]=y>u?u:y<t?t:y:k[x]=0)}}if(l?.length)for(r=0;r<d;r++)for(v=0;v<c;v++)if(w=r*c+v,!q||q[w])for(x=b[w],y=0;y<a;y+=2)if(x>=l[y]&&x<=l[y+1]){n[w]=0;k[w]=0;break}return new F({width:c,height:d,pixelType:h,pixels:[n],mask:k})};z.remapColor=function(a,b){if(!G(a))return null;a=a.clone();var {pixels:c}=a;const d=a.width*a.height,f=b.length,e=Math.floor(f/2),h=b[Math.floor(e)];c=c[0];let l,g,p,n,q,k,m=!1;const r=new Uint8Array(d),t=new Uint8Array(d),u=new Uint8Array(d);let v=a.mask;const w=
4===b[0].mappedColor.length;v||(v=new Uint8Array(d),v.fill(w?255:1),a.mask=v);for(q=0;q<d;q++)if(v[q]){l=c[q];m=!1;k=e;g=h;p=0;for(n=f-1;1<n-p;){if(l===g.value){m=!0;break}l>g.value?p=k:n=k;k=Math.floor((p+n)/2);g=b[Math.floor(k)]}m||(l===b[p].value?(g=b[p],m=!0):l===b[n].value?(g=b[n],m=!0):l<b[p].value?(m=!1,g=null):l>b[p].value&&(l<b[n].value?(g=b[p],m=!0):n===f-1?(m=!1,g=null):(g=b[n],m=!0)));m?(r[q]=g.mappedColor[0],t[q]=g.mappedColor[1],u[q]=g.mappedColor[2],v[q]=g.mappedColor[3]):r[q]=t[q]=
u[q]=v[q]=0}a.pixels=[r,t,u];a.mask=v;a.pixelType="u8";a.maskIsAlpha=w;return a};z.resampleByMajority=Y;z.setValidBoundary=function(a,b,c){if(!G(a))return null;const {width:d,height:f}=a,e=b.x;b=b.y;const h=c.width+e;c=c.height+b;if(0>e||0>b||h>d||c>f||0===e&&0===b&&h===d&&c===f)return a;a.mask||(a.mask=new Uint8Array(d*f));const l=a.mask;for(let g=0;g<f;g++){const p=g*d;for(let n=0;n<d;n++)l[p+n]=g<b||g>=c||n<e||n>=h?0:1}a.updateStatistics();return a};z.split=function(a,b,c){if(!G(a))return null;
const {width:d,height:f}=b;let {width:e,height:h}=a;const l=new Map,g={x:0,y:0};c=null==c?1:1+c;for(let p=0;p<c;p++){const n=Math.ceil(e/d),q=Math.ceil(h/f);for(let k=0;k<q;k++){g.y=k*f;for(let m=0;m<n;m++){g.x=m*d;const r=aa(a,g,b);l.set(`${p}/${k}/${m}`,r)}}p<c-1&&(a=da(a));e=Math.round(e/2);h=Math.round(h/2)}return l};Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});