// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/mathUtils ../../../core/maybe ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../rasterFormats/pixelRangeUtils ./BaseRasterFunction ./pixelUtils ./RemapFunctionArguments".split(" "),function(y,q,t,u,r,n,D,z,A,B,k,C){n=function(x){function v(){var a=x.apply(this,arguments)||this;a.functionName=
"Remap";a.functionArguments=null;a.rasterArgumentNames=["raster"];a.lookup=null;return a}y._inheritsLoose(v,x);var w=v.prototype;w._bindSourceRasters=function(){const a=this.sourceRasterInfos[0].clone(),{pixelType:e}=a;this.outputPixelType=this._getOutputPixelType(e);a.pixelType=this.outputPixelType;a.colormap=null;a.histograms=null;a.bandCount=1;a.attributeTable=null;const {statistics:g}=a,{allowUnmatched:l,outputValues:c,inputRanges:f,noDataRanges:h,isLastInputRangeInclusive:m}=this.functionArguments;
if(u.isSome(g)&&g.length&&c?.length)if(l){var d=Math.min.apply(null,[...c,g[0].min]),b=Math.max.apply(null,[...c,g[0].max]);a.statistics=[{...g[0],min:d,max:b}]}else{b=d=c[0];for(let p=0;p<c.length;p++)d=d>c[p]?c[p]:d,b=b>c[p]?b:c[p];a.statistics=[{...g[0],min:d,max:b}]}this.rasterInfo=a;this.lookup=l?null:k.createRemapLUT({srcPixelType:e,inputRanges:f,outputValues:c,noDataRanges:h,allowUnmatched:l,isLastInputRangeInclusive:m,outputPixelType:this.outputPixelType});return{success:!0,supportsGPU:(!c||
c.length<=k.MAX_MAP_SIZE_GPU)&&(!h||h.length<=k.MAX_MAP_SIZE_GPU)}};w._processPixels=function(a){a=a.pixelBlocks?.[0];if(u.isNone(a))return null;const {lookup:e,outputPixelType:g}=this;if(e){const d=k.lookupPixels(a,{lut:[e.lut],offset:e.offset,outputPixelType:g});u.isSome(d)&&e.mask&&(d.mask=k.lookupBandValues(a.pixels[0],a.mask,e.mask,e.offset,"u8"));return d}const {inputRanges:l,outputValues:c,noDataRanges:f,allowUnmatched:h,isLastInputRangeInclusive:m}=this.functionArguments;return k.remap(a,
{inputRanges:l,outputValues:c,noDataRanges:f,outputPixelType:g,allowUnmatched:h,isLastInputRangeInclusive:m})};w._getWebGLParameters=function(){const {allowUnmatched:a,inputRanges:e,outputValues:g,noDataRanges:l,isLastInputRangeInclusive:c}=this.functionArguments,f=new Float32Array(3*k.MAX_MAP_SIZE_GPU);var h=g.length;if(e?.length){var m=0;let d=0;for(let b=0;b<f.length;b+=3)if(f[b]=e[m++]??t.NUMBER_MAX_FLOAT32-1,f[b+1]=e[m++]??t.NUMBER_MAX_FLOAT32,f[b+2]=g[d++]??0,d<=h&&(0<b&&(f[b]-=1E-5),d<h||!c))f[b+
1]-=1E-5}h=new Float32Array(2*k.MAX_MAP_SIZE_GPU);h.fill(t.NUMBER_MAX_FLOAT32);l?.length&&h.set(l);m=A.getPixelValueRange(this.outputPixelType);return{allowUnmatched:a,rangeMaps:f,noDataRanges:h,clampRange:m}};return v}(B);q.__decorate([r.property({json:{write:!0,name:"rasterFunction"}})],n.prototype,"functionName",void 0);q.__decorate([r.property({type:C,json:{write:!0,name:"rasterFunctionArguments"}})],n.prototype,"functionArguments",void 0);q.__decorate([r.property()],n.prototype,"rasterArgumentNames",
void 0);q.__decorate([r.property({json:{write:!0}})],n.prototype,"lookup",void 0);return n=q.__decorate([z.subclass("esri.layers.support.rasterFunctions.RemapFunction")],n)});