// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../PixelBlock","../rasterFormats/pixelRangeUtils","../../../renderers/support/stretchRendererUtils"],function(z,A,D,I,J){function E(e,d=256){d=Math.min(d,256);const {size:l,counts:g}=e;e=new Uint8Array(l);var m=g.reduce((b,k)=>b+k/d,0);let p=0;var c=0;let h=0,f=m;for(let b=0;b<l;b++)if(h+=g[b],!(b<l-1&&h+g[b+1]<f)){for(;p<d-1&&f<h;)p++,f+=m;for(;c<=b;c++)e[c]=p;c=b+1}for(m=c;m<l;m++)e[m]=d-1;return e}function F(e,d){e=Math.min(Math.max(e,-100),100);d=Math.min(Math.max(d??
0,-100),100);let l=0,g=0;const m=new Uint8Array(256);for(l=0;256>l;l++)0<e&&100>e?g=(200*l-25500+510*d)/(2*(100-e))+128:0>=e&&-100<e?g=(200*l-25500+510*d)*(100+e)/2E4+128:100===e?(g=200*l-25500+256*(100-e)+510*d,g=0<g?255:0):-100===e&&(g=128),m[l]=255<g?255:0>g?0:g;return m}function G(e){if(A.isNone(e)||!e.pixels?.length)return null;const {pixels:d,mask:l,pixelType:g}=e,m=e.width*e.height,p=d.length;let c,h;let f;var b;const k=[],w=[];for(f=0;f<p;f++){var q=new Uint32Array(256);var r=d[f];if("u8"===
g)if(c=-.5,h=255.5,l)for(b=0;b<m;b++)l[b]&&q[r[b]]++;else for(b=0;b<m;b++)q[r[b]]++;else{b=!1;e.statistics||(e.updateStatistics(),b=!0);var a=e.statistics;c=a[f].minValue;h=a[f].maxValue;var n=(h-c)/256;if(0===n)for(!a||e.validPixelCount||b||e.updateStatistics(),n=(e.validPixelCount||e.width*e.height)/256,b=0;256>b;b++)q[b]=Math.round(n*(b+1))-Math.round(n*b);else{a=new Uint32Array(257);for(b=0;b<m;b++)l&&!l[b]||a[Math.floor((r[b]-c)/n)]++;for(b=0;255>b;b++)q[b]=a[b];q[255]=a[255]+a[256]}}k.push({min:c,
max:h,size:256,counts:q});for(b=a=r=n=0;256>b;b++)n+=q[b],r+=b*q[b];r/=n;for(b=0;256>b;b++)a+=q[b]*(b-r)**2;b=Math.sqrt(a/(n-1));n=(h-c)/256;q=(r+.5)*n+c;n*=b;w.push({min:c,max:h,avg:q,stddev:n})}return{statistics:w,histograms:k}}function K(e,d){if(null==d||0===d.length)return e;const l=Math.max.apply(null,d),{minCutOff:g,maxCutOff:m,outMin:p,outMax:c,histogramLut:h}=e;return g.length===d.length||g.length<=l?e:{minCutOff:d.map(f=>g[f]),maxCutOff:d.map(f=>m[f]),histogramLut:h?d.map(f=>h[f]):null,outMin:p,
outMax:c}}function C(e,d){const l=new Float32Array(e);for(let g=0;g<e;g++)l[g]=1<d[g]?2<d[g]?6.5+(d[g]-2)**2.5:6.5+100*(2-d[g])**4:1;return l}const L=[.299,.587,.114];z.computeGammaCorrection=C;z.computeGammaValues=function(e,d,l){const g=[];for(let f=0;f<d.length;f++){var m=0,p=0,c=0;"min"in d[f]?{min:m,max:p,avg:c}=d[f]:[m,p,c]=d[f];c=c??0;"u8"!==e&&(c=255*(c-m)/(p-m));l&&(c*=L[f]);m=g;p=m.push;if(0>=c||255<=c)c=1;else{var h=0;150!==c&&(h=150>=c?45*Math.cos(.01047*c):17*Math.sin(.021*c));h=Math.log((c+
h)/255);0===h?c=1:(c=Math.log(c/255)/h,c=isNaN(c)?1:Math.min(9.9,Math.max(.01,c)))}p.call(m,c)}return g};z.createContrastBrightnessLUT=F;z.createHistogramEqualizationLUT=E;z.createStretchLUT=function(e){const {minCutOff:d,maxCutOff:l,gamma:g,pixelType:m,rounding:p}=e,c=e.outMin||0,h=e.outMax||255;if(!["u8","u16","s8","s16"].includes(m))return null;const f=d.length;let b,k,w=0;"s8"===m?w=-127:"s16"===m&&(w=-32767);let q=256;["u16","s16"].includes(m)&&(q=65536);var r=[],a=[];const n=h-c;for(b=0;b<f;b++)a[b]=
l[b]-d[b],r[b]=0===a[b]?0:n/a[b];let B;const x=[];let u,v;if(g&&g.length>=f)for(r=C(f,g),b=0;b<f;b++){v=[];for(k=0;k<q;k++)if(0===a[b])v[k]=c;else{var t=k+w;B=(t-d[b])/a[b];u=1;1<g[b]&&(u-=(1/n)**(B*r[b]));t<l[b]&&t>d[b]?(t=u*n*B**(1/g[b])+c,v[k]="floor"===p?Math.floor(t):"round"===p?Math.round(t):t):v[k]=t>=l[b]?h:c}x[b]=v}else for(b=0;b<f;b++){v=[];for(k=0;k<q;k++)t=k+w,t<=d[b]?v[k]=c:t>=l[b]?v[k]=h:(a=(t-d[b])*r[b]+c,v[k]="floor"===p?Math.floor(a):"round"===p?Math.round(a):a);x[b]=v}if(null!=e.contrastOffset)for(e=
F(e.contrastOffset,e.brightnessOffset),b=0;b<f;b++)for(v=x[b],k=0;k<q;k++)v[k]=e[v[k]];return{lut:x,offset:w}};z.estimateStatisticsFromHistograms=function(e){const d=[];for(let p=0;p<e.length;p++){const {min:c,max:h,size:f,counts:b}=e[p];let k=0;var l=0;for(var g=0;g<f;g++)k+=b[g],l+=g*b[g];l/=k;g=0;for(var m=0;m<f;m++)g+=b[m]*(m-l)**2;m=(h-c)/f;d.push({min:c,max:h,avg:(l+.5)*m+c,stddev:Math.sqrt(g/(k-1))*m})}return d};z.estimateStatisticsHistograms=G;z.getStretchCutoff=function(e,d){const {pixelBlock:l,
bandIds:g,returnHistogramLut:m,rasterInfo:p}=d;var c=null;d=null;var h=e.stretchType;"number"===typeof h&&(h=J.stretchTypeFunctionEnum[h]);e.dra?"minMax"===h&&A.isSome(l)&&l.statistics?c=l.statistics.map(t=>[t.minValue,t.maxValue,0,0]):(d=G(l),c=A.isSome(d)?d.statistics:null,d=A.isSome(d)?d.histograms:null):(c=0<e.statistics?.length?e.statistics:A.unwrap(p.statistics),d=e.histograms||A.unwrap(p.histograms));"percentClip"!==h&&"histogramEqualization"!==h||d?.length||(h="minMax");var f=c?.length||d?.length||
p.bandCount;const b=[],k=[];let w;let q,r,a,n;c&&!Array.isArray(c[0])&&(c=c.map(t=>[t.min,t.max,t.avg,t.stddev]));const [B,x]=I.getPixelValueRange(p.pixelType);if(!c?.length){c=[];for(a=0;a<f;a++)c.push([B,x,1,1]);"standardDeviation"===h&&(h="minMax")}switch(h){case "none":for(a=0;a<f;a++)b[a]=B,k[a]=x;break;case "minMax":for(a=0;a<f;a++)b[a]=c[a][0],k[a]=c[a][1];break;case "standardDeviation":for(a=0;a<f;a++)b[a]=c[a][2]-e.numberOfStandardDeviations*c[a][3],k[a]=c[a][2]+e.numberOfStandardDeviations*
c[a][3],b[a]<c[a][0]&&(b[a]=c[a][0]),k[a]>c[a][1]&&(k[a]=c[a][1]);break;case "histogramEqualization":A.assertIsSome(d);for(a=0;a<f;a++)b[a]=d[a].min,k[a]=d[a].max;break;case "percentClip":A.assertIsSome(d);for(a=0;a<d.length;a++){c=d[a];q=new Uint32Array(c.size);var u=[...c.counts];20<=u.length&&(u[0]=u[1]=u[2]=u[u.length-1]=u[u.length-2]=0);w=0;f=(c.max-c.min)/c.size;r=-.5===c.min&&1===f?.5:0;for(n=0;n<c.size;n++)w+=u[n],q[n]=w;u=(e.minPercent||0)*w/100;b[a]=c.min+r;for(n=0;n<c.size;n++)if(q[n]>
u){b[a]=c.min+f*(n+r);break}u=(1-(e.maxPercent||0)/100)*w;k[a]=c.max+r;for(n=c.size-2;0<=n;n--)if(q[n]<u){k[a]=c.min+f*(n+2-r);break}k[a]<b[a]&&(c=b[a],b[a]=k[a],k[a]=c)}break;default:for(a=0;a<f;a++)b[a]=c[a][0],k[a]=c[a][1]}let v;"histogramEqualization"===h?(A.assertIsSome(d),h=d[0].size||256,e=0,m&&(v=d.map(t=>E(t)))):(h=e.max||255,e=e.min||0);return K({minCutOff:b,maxCutOff:k,outMax:h,outMin:e,histogramLut:v},g)};z.stretch=function(e,d){if(A.isNone(e)||!e.pixels?.length)return e;const {mask:l,
width:g,height:m,pixels:p}=e,{minCutOff:c,maxCutOff:h,gamma:f}=d;var b=d.outMin||0;const k=d.outMax||255,w=g*m,q=d.outputPixelType||"u8";e=e.pixels.map(()=>D.createEmptyBand(q,w));const r=e.length;let a;let n,B;var x=k-b,u=[];const v=[];for(a=0;a<r;a++)v[a]=h[a]-c[a],u[a]=0===v[a]?0:x/v[a];const t=q.startsWith("u")||q.startsWith("s"),H=!!d.isRenderer;if(f&&f.length>=r)for(u=C(r,f),d=0;d<w;d++){if(null==l||l[d])for(a=0;a<r;a++)if(0===v[a])e[a][d]=b;else{var y=p[a][d];B=(y-c[a])/v[a];n=1;1<f[a]&&(n-=
(1/x)**(B*u[a]));y<h[a]&&y>c[a]?(y=n*x*B**(1/f[a])+b,e[a][d]=H?Math.floor(y):t?Math.round(y):y):e[a][d]=y>=h[a]?k:b}}else for(d=0;d<w;d++)if(null==l||l[d])for(a=0;a<r;a++)y=p[a][d],y<h[a]&&y>c[a]?(x=(y-c[a])*u[a]+b,e[a][d]=H?Math.floor(x):t?Math.round(x):x):e[a][d]=y>=h[a]?k:b;b=new D({width:g,height:m,mask:l,pixels:e,pixelType:q});b.updateStatistics();return b};Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});