// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../geometry ../../../../core/HandleOwner ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/Point ../../../../layers/support/PixelBlock ../../../../layers/support/TileInfo ../../../../layers/support/rasterDatasets/RawBlockCache ../../../../layers/support/rasterFunctions/pixelUtils ../../../../layers/support/rasterFunctions/rasterProjectionHelper ../../tiling/PagedTileQueue ../../tiling/TileInfoView ../../tiling/TileKey ../../tiling/TileQueue ../../tiling/TileStrategy ../../engine/webgl/definitions ../../../webgl/capabilities ../../../../geometry/Extent".split(" "),
function(h,m,k,P,E,A,u,t,l,Q,R,F,G,H,y,p,I,B,S,J,T,K,C,v,L,M){const N=[0,0];h.BaseImageryTileSubView2D=function(D){function w(){var a=D.apply(this,arguments)||this;a._emptyTilePixelBlock=null;a._tileStrategy=null;a._tileInfoView=null;a._fetchQueue=null;a._blockCacheRegistryUrl=null;a._blockCacheRegistryId=null;a._srcResolutions=[];a.previousLOD=null;a._needBlockCacheUpdate=!1;a._globalSymbolizerParams=null;a._symbolizerParams=null;a._abortController=null;a._isCustomTilingScheme=!1;a._rasterFunctionState=
"na";a._globalUpdateRequested=!1;a.attached=!1;a.timeExtent=null;a.redrawOrRefetch=t.debounce(m._asyncToGenerator(function*(b={}){if(a.previousLOD&&!a.layerView.suspended){var c=a._rasterFunctionState;b.reprocess&&(yield a.updatingHandles.addPromise(a.layer.updateRasterFunction()),a.updateRasterFunctionParameters());var d=a._rasterFunctionState,{type:e}=m._assertThisInitialized(a);return b.refetch||"raster"!==e&&b.reprocess||"cpu"===d||"cpu"===c?a.updatingHandles.addPromise(a.doRefresh()):a.updatingHandles.addPromise(a._redrawImage(b.signal))}}));
return a}m._inheritsLoose(w,D);var f=w.prototype;f.update=function(a){this._fetchQueue.pause();this._fetchQueue.state=a.state;this._tileStrategy.update(a);this._fetchQueue.resume();const {extent:b,resolution:c,scale:d}=a.state;a=this._tileInfoView.getClosestInfoForScale(d);if(this.layer.raster){if(!this.useProgressiveUpdate||this._needBlockCacheUpdate){const e=this._srcResolutions[a.level],g=b.toJSON?b:M.fromJSON(b);p.update(this._blockCacheRegistryUrl,this._blockCacheRegistryId,g,c,e,this.layer.raster.ioConfig.sampling)}this._needBlockCacheUpdate=
!1;this.previousLOD?.level!==a.level&&(this.previousLOD=a,null==this._symbolizerParams||this.layerView.hasTilingEffects||this._updateSymbolizerParams(),this._tileStrategy.updateCacheSize(0))}};f.moveEnd=function(){if(this.layerView.hasTilingEffects||!this.useProgressiveUpdate)this._abortController&&this._abortController.abort(),this._abortController=new AbortController,0===this._fetchQueue.length&&this._redrawImage(this._abortController.signal).then(()=>{this._globalUpdateRequested=!1;this.layerView.requestUpdate()});
const a=this._getCacheSize(this.useProgressiveUpdate);this._tileStrategy.updateCacheSize(a);this.layerView.requestUpdate()};f.attach=function(){L.getWebGLCapabilities("2d").supportsTextureFloat||(this.useWebGLForProcessing=!1);this._initializeTileInfo();this._tileInfoView=new J(this.layerView.tileInfo,this.layerView.fullExtent);var a=this._computeFetchConcurrency();this._fetchQueue=new K({tileInfoView:this._tileInfoView,concurrency:a,process:(b,c)=>this._fetchTile1(b,c)});a=this._getCacheSize(this.useProgressiveUpdate);
this._tileStrategy=new C({cachePolicy:"purge",acquireTile:b=>this.acquireTile(b),releaseTile:b=>this.releaseTile(b),cacheSize:a,tileInfoView:this._tileInfoView});this._updateBlockCacheRegistry()};f.detach=function(){this._tileStrategy.destroy();this._fetchQueue.clear();this.container.removeAllChildren();this._fetchQueue=this._tileStrategy=this._tileInfoView=null;p.unregister(this._blockCacheRegistryUrl,this._blockCacheRegistryId);this._blockCacheRegistryUrl=this._blockCacheRegistryId=null};f.acquireTile=
function(a){a=this.container.createTile(a);this._enqueueTileFetch(a);this.layerView.requestUpdate();this._needBlockCacheUpdate=!0;this._globalUpdateRequested=this.layerView.hasTilingEffects||!this.useProgressiveUpdate;return a};f.releaseTile=function(a){this._fetchQueue.abort(a.key.id);this.container.removeChild(a);a.once("detach",()=>{a.destroy();this.layerView.requestUpdate()});this.layerView.requestUpdate()};f.createEmptyTilePixelBlock=function(a=null){const b=null==a||a.join(",")===this._tileInfoView.tileInfo.size.join(",");
if(b&&u.isSome(this._emptyTilePixelBlock))return this._emptyTilePixelBlock;a=a||this._tileInfoView.tileInfo.size;const [c,d]=a;a=new H({width:c,height:d,pixels:[new Uint8Array(c*d)],mask:new Uint8Array(c*d),pixelType:"u8"});b&&(this._emptyTilePixelBlock=a);return a};f._getBandIds=function(){if(!("rasterFunctionChain"in this.container&&this.container.rasterFunctionChain))return this.layer.bandIds;const {bandIds:a,raster:b}=this.layer,c="rasterFunction"in b?b.rasterFunction.rawInputBandIds:null;return a?.length&&
c?.length&&1!==b.rasterInfo.bandCount?a.map(d=>c[Math.min(d,c.length-1)]):a||c};f.updateRasterFunctionParameters=function(){};f._fetchTile1=function(a,b){b=u.isSome(b)?b.signal:null;const c=this.canUseWebGLForProcessing(),{layerView:d}=this,{tileInfo:e}=d,g=!e.isWrappable&&u.isSome(B.getWorldWidth(d.view.spatialReference));b={allowPartialFill:!0,datumTransformation:d.datumTransformation,interpolation:c?"nearest":this.layer.interpolation,registryId:this._blockCacheRegistryId,requestRawData:c&&this.layer.raster.hasUniqueSourceStorageInfo,
skipRasterFunction:"raster"===this.type&&null!=this.container.rasterFunctionChain,signal:u.unwrap(b),srcResolution:this._srcResolutions[a.level],timeExtent:d.timeExtent,tileInfo:e,disableWrapAround:g};return this.fetchTile(a,b)};f._getCacheSize=function(a){return a?40:0};f._initializeTileInfo=function(){const {layerView:a}=this;var b=a.view.spatialReference;const c=new G({x:a.fullExtent.xmin,y:a.fullExtent.ymax,spatialReference:b});if(this._canUseLayerLODs()){const {lods:q}=this.layer.tileInfo,x=
q.map(({scale:r})=>r),n=y.create({spatialReference:b,size:v.TILE_SIZE,scales:x});this._isCustomTilingScheme=Math.abs(n.origin.x-c.x)>(b.isGeographic?.01*1E-5:.01);if(0===n.origin.x||n.origin.x>c.x)n.origin=c;if(!this._isCustomTilingScheme){const r=y.create({spatialReference:b,size:v.TILE_SIZE}).lods.map(({scale:z})=>z);this._isCustomTilingScheme=x.some(z=>!r.some(O=>.001>Math.abs(O-z)))}a.set("tileInfo",n);this._srcResolutions=q.map(({resolution:r})=>({x:r,y:r}))}else{var {scales:d,srcResolutions:e,
isCustomTilingScheme:g}=B.computeProjectedScales(this.layer.rasterInfo,b,v.TILE_SIZE);b=y.create({spatialReference:b,size:v.TILE_SIZE,scales:d});if(0===b.origin.x||b.origin.x>c.x)b.origin=c;this._isCustomTilingScheme=g;a.set("tileInfo",b);this._srcResolutions=e??[]}};f._canUseLayerLODs=function(){const {layer:a,layerView:b}=this;if("Map"!==a.raster.tileType)return!1;const {lods:c}=a.tileInfo;var d=b.view.constraints?.effectiveLODs;if(d?.length!==c.length||!d.every(({scale:e},g)=>.001>Math.abs(e-c[g].scale)))return!1;
d=[];for(let e=0;e<c.length-1;e++)d.push(Math.round(10*c[e].resolution/c[e+1].resolution)/10);return d.some(e=>e!==e[0])};f._computeFetchConcurrency=function(){var {blockBoundary:a}=this.layer.rasterInfo.storageInfo;a=a[a.length-1];return 64<(a.maxCol-a.minCol+1)*(a.maxRow-a.minRow+1)?2:10};f._enqueueTileFetch=function(){var a=m._asyncToGenerator(function*(b,c){this.updatingHandles.addPromise(this._enqueueTileFetch1(b,c))});return function(b,c){return a.apply(this,arguments)}}();f._enqueueTileFetch1=
function(){var a=m._asyncToGenerator(function*(b,c){if(!this._fetchQueue.has(b.key.id)){try{const d=yield this._fetchQueue.push(b.key),e=this._getBandIds();let g=!this.useProgressiveUpdate||this.layerView.hasTilingEffects&&!this._globalSymbolizerParams;if(this._globalUpdateRequested&&!this.layerView.moving&&0===this._fetchQueue.length){g=!1;try{yield this._redrawImage(this._abortController?.signal)}catch(n){t.isAbortError(n)&&A.getLogger(this.declaredClass).error(n)}this._globalUpdateRequested=!1}!this.canUseWebGLForProcessing()&&
"rasterVF"!==this.type||this.layerView.hasTilingEffects||null!=this._symbolizerParams||this._updateSymbolizerParams();const q=this._tileInfoView.getTileCoords(N,b.key),x=this._tileInfoView.getTileResolution(b.key);yield this.updateTileSource(b,{source:d,symbolizerParams:this._symbolizerParams,globalSymbolizerParams:this._globalSymbolizerParams,suspended:g,bandIds:e,coords:q,resolution:x});b.once("attach",()=>this.layerView.requestUpdate());this.container.addChild(b)}catch(d){t.isAbortError(d)||A.getLogger(this.declaredClass).error(d)}this.layerView.requestUpdate()}});
return function(b,c){return a.apply(this,arguments)}}();f._redrawImage=function(){var a=m._asyncToGenerator(function*(b){var c=this;0!==this.container.children.length&&(yield this.layer.updateRenderer(),this.layerView.hasTilingEffects?yield this._updateGlobalSymbolizerParams(b):(this._updateSymbolizerParams(),this._globalSymbolizerParams=null),b=this.container.children.map(function(){var d=m._asyncToGenerator(function*(e){return c.updateTileSymbolizerParameters(e,{local:c._symbolizerParams,global:c._globalSymbolizerParams})});
return function(e){return d.apply(this,arguments)}}()),yield t.eachAlways(b),this.container.requestRender())});return function(b){return a.apply(this,arguments)}}();f._updateGlobalSymbolizerParams=function(){var a=m._asyncToGenerator(function*(b){if((b=yield this.layer.fetchPixels(this.layerView.view.extent,this.layerView.view.width,this.layerView.view.height,{srcResolution:this._srcResolutions[this.previousLOD.level],registryId:this._blockCacheRegistryId,signal:b}))&&b.pixelBlock){var {resolution:c}=
this.previousLOD,d=this._getBandIds();b=this.layer.symbolizer.generateWebGLParameters({pixelBlock:I.extractBands(b.pixelBlock,d),isGCS:this.layerView.view.spatialReference.isGeographic,resolution:{x:c,y:c},bandIds:d});!this.canUseWebGLForProcessing()&&b&&"stretch"===b.type&&this.layer.renderer&&"raster-stretch"===this.layer.renderer.type&&(b.factor=b.factor.map(e=>255*e),b.outMin=Math.round(255*b.outMin),b.outMax=Math.round(255*b.outMax));this._globalSymbolizerParams=b}});return function(b){return a.apply(this,
arguments)}}();f._updateSymbolizerParams=function(){const {resolution:a}=this.previousLOD,b=this._getBandIds();this._symbolizerParams=this.layer.symbolizer.generateWebGLParameters({pixelBlock:null,isGCS:this.layerView.view.spatialReference.isGeographic,resolution:{x:a,y:a},bandIds:b})};f._updateBlockCacheRegistry=function(a=!1){const {layer:b,layerView:c}=this,{url:d,raster:e}=b;var {multidimensionalDefinition:g}=b.normalizeRasterFetchOptions({multidimensionalDefinition:b.multidimensionalDefinition,
timeExtent:c.timeExtent});g=e.rasterInfo.multidimensionalInfo?e.getSliceIndex(g):null;g=p.getRasterId(d,g);if(g!==this._blockCacheRegistryUrl){null!=this._blockCacheRegistryUrl&&p.unregister(this._blockCacheRegistryUrl,this._blockCacheRegistryId);this._blockCacheRegistryId=p.register(g,e.rasterInfo);if(a){({view:a}=c);const q=this._tileInfoView.getClosestInfoForScale(a.scale);p.update(g,this._blockCacheRegistryId,a.extent,a.resolution,this._srcResolutions[q.level],e.ioConfig.sampling)}this._blockCacheRegistryUrl=
g}};f.doRefresh=function(){var a=m._asyncToGenerator(function*(){if(this.attached){yield this.layer.updateRenderer();this.layerView.hasTilingEffects||this._updateSymbolizerParams();this._updateBlockCacheRegistry(!0);this._fetchQueue.reset();var b=[];this._globalUpdateRequested=this.layerView.hasTilingEffects||!this.useProgressiveUpdate;this._tileStrategy.tiles.forEach(c=>b.push(this._enqueueTileFetch(c)));yield t.eachAlways(b)}});return function(){return a.apply(this,arguments)}}();m._createClass(w,
[{key:"useWebGLForProcessing",get:function(){return this._get("useWebGLForProcessing")??!0},set:function(a){this._set("useWebGLForProcessing",a)}},{key:"useProgressiveUpdate",get:function(){return null==this._get("useProgressiveUpdate")?!0:this._get("useProgressiveUpdate")},set:function(a){if(this._tileStrategy&&this.useProgressiveUpdate!==a){this._tileStrategy.destroy();this.container.removeAllChildren();const b=this._getCacheSize(a);this._tileStrategy=new C({cachePolicy:"purge",acquireTile:c=>this.acquireTile(c),
releaseTile:c=>this.releaseTile(c),cacheSize:b,tileInfoView:this._tileInfoView});this._set("useProgressiveUpdate",a);this.layerView.requestUpdate()}}},{key:"updating",get:function(){return this._fetchQueue?.updating||this._globalUpdateRequested||!(!this.updatingHandles||!this.updatingHandles.updating)}}]);return w}(E.HandleOwner);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"_fetchQueue",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"_globalUpdateRequested",
void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"attached",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"container",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"layer",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"layerView",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"type",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"useWebGLForProcessing",
null);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"useProgressiveUpdate",null);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"timeExtent",void 0);k.__decorate([l.property()],h.BaseImageryTileSubView2D.prototype,"updating",null);h.BaseImageryTileSubView2D=k.__decorate([F.subclass("esri.views.2d.layers.imagery.BaseImageryTileSubView2D")],h.BaseImageryTileSubView2D);Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});