// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../request ../../../../core/HandleOwner ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/Extent ../../../../layers/support/rasterFunctions/rasterProjectionHelper ../../../../layers/support/rasterFunctions/vectorFieldUtils ../../engine/imagery/RasterVFContainer ./ImageryVFStrategy".split(" "),
function(m,h,x,y,d,n,r,l,G,H,z,A,B,t,C,D){d=function(u){function p(){var a=u.apply(this,arguments)||this;a.attached=!1;a.container=new C.RasterVFContainer;a.type="imageryVF";a._dataParameters={exportParametersVersion:0,bbox:"",symbolTileSize:0,time:""};a._fetchpixels=function(){var f=m._asyncToGenerator(function*(c,b,v,e){const q=yield a._projectFullExtentPromise,{symbolTileSize:w}=a.layer.renderer,{extent:k,width:E,height:F}=t.snapImageToSymbolTile(c,b,v,w,q);if(n.isSome(q)&&!q.intersects(c))return{extent:k,
pixelBlock:null};c={bbox:`${k.xmin}, ${k.ymin}, ${k.xmax}, ${k.ymax}`,exportParametersVersion:a.layer.exportImageServiceParameters.version,symbolTileSize:w,time:JSON.stringify(a.timeExtent||"")};if(a._canReuseVectorFieldData(c)&&(b=a.getPixelData(),n.isSome(b)&&`${b.extent.xmin}, ${b.extent.ymin}, ${b.extent.xmax}, ${b.extent.ymax}`===c.bbox))return b;({pixelData:e}=yield a.layer.fetchImage(k,E,F,{timeExtent:a.timeExtent,requestAsImageElement:!1,signal:e}));a._dataParameters=c;e=e?.pixelBlock;if(n.isNone(e))return{extent:k,
pixelBlock:null};e="vector-uv"===a.layer.rasterInfo.dataType?n.unwrap(t.convertVectorFieldData(e,"vector-uv")):e;return{extent:k,pixelBlock:e}});return function(c,b,v,e){return f.apply(this,arguments)}}();return a}m._inheritsLoose(p,u);var g=p.prototype;g.attach=function(){this._projectFullExtentPromise=this._getProjectedFullExtent(this.view.spatialReference);this._strategy=new D({container:this.container,fetchPixels:this._fetchpixels});this.handles.add(r.watch(()=>this.layer.renderer,a=>this._updateSymbolizerParams(a),
r.syncAndInitial),"attach")};g.detach=function(){this._strategy.destroy();this.container.children.forEach(a=>a.destroy());this.container.removeAllChildren();this.handles.remove("attach");this._strategy=this.container=this._projectFullExtentPromise=null};g.getPixelData=function(){const a=this.container.children[0]?.rawPixelData;if(this.updating||!a)return null;const {extent:f,pixelBlock:c}=a;return{extent:f,pixelBlock:c}};g.hitTest=function(a){return new x({attributes:{},geometry:a.clone(),layer:this.layer})};
g.update=function(a){this._strategy.update(a,this._symbolizerParams)};g.redraw=function(){const {renderer:a}=this.layer;a&&(this._updateSymbolizerParams(a),this._strategy.redraw(this._symbolizerParams))};g._canReuseVectorFieldData=function(a){const f=this._dataParameters.time===a.time,c=this._dataParameters.symbolTileSize===a.symbolTileSize,b=this._dataParameters.bbox===a.bbox;return this._dataParameters.exportParametersVersion===a.exportParametersVersion&&f&&c&&b};g._getProjectedFullExtent=function(){var a=
m._asyncToGenerator(function*(f){try{return yield B.projectExtent(this.layer.fullExtent,f)}catch(c){try{const b=(yield y(this.layer.url,{query:{option:"footprints",outSR:f.wkid||JSON.stringify(f.toJSON()),f:"json"}})).data.featureCollection.layers[0].layerDefinition.extent;return b?A.fromJSON(b):null}catch{return null}}});return function(f){return a.apply(this,arguments)}}();g._updateSymbolizerParams=function(a){"vector-field"===a.type&&(this._symbolizerParams=this.layer.symbolizer.generateWebGLParameters({pixelBlock:null}))};
m._createClass(p,[{key:"updating",get:function(){return!this.attached||this._strategy.updating}}]);return p}(d.HandleOwner);h.__decorate([l.property()],d.prototype,"attached",void 0);h.__decorate([l.property()],d.prototype,"container",void 0);h.__decorate([l.property()],d.prototype,"layer",void 0);h.__decorate([l.property()],d.prototype,"timeExtent",void 0);h.__decorate([l.property()],d.prototype,"type",void 0);h.__decorate([l.property()],d.prototype,"view",void 0);h.__decorate([l.property()],d.prototype,
"updating",null);return d=h.__decorate([z.subclass("esri.views.2d.layers.imagery.VectorFieldView2D")],d)});