// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Error ../../../../core/Handles ../../../../core/maybe ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/Extent ../../../../layers/LayerConstants ../../../../layers/graphics/data/QueryEngine ../../../../rest/support/FeatureSet ../../../../rest/support/Query".split(" "),
function(d,g,f,r,p,t,m,h,B,C,u,v,w,x,y,z){const A=x.QueryEngine;d.I3SQueryEngine=function(q){function l(c){c=q.call(this,c)||this;c._handles=new t;return c}g._inheritsLoose(l,q);var e=l.prototype;e.initialize=function(){this._handles.add(this.layerView.on("visible-geometry-changed",()=>this.spatialIndex.events.emit("changed")))};e.destroy=function(){this._dataQueryEngineInstance=m.destroyMaybe(this._dataQueryEngineInstance);this._handles=m.destroyMaybe(this._handles);this._set("layerView",null)};
e.executeQueryForCount=function(){var c=g._asyncToGenerator(function*(a,b){return this._dataQueryEngine.executeQueryForCount(this._ensureQueryJSON(a),b)});return function(a,b){return c.apply(this,arguments)}}();e.executeQueryForExtent=function(){var c=g._asyncToGenerator(function*(a,b){const {count:k,extent:n}=yield this._dataQueryEngine.executeQueryForExtent(this._ensureQueryJSON(a),b);a=v.fromJSON(n);return{count:k,extent:a}});return function(a,b){return c.apply(this,arguments)}}();e.executeQueryForIds=
function(){var c=g._asyncToGenerator(function*(a,b){return this._dataQueryEngine.executeQueryForIds(this._ensureQueryJSON(a),b)});return function(a,b){return c.apply(this,arguments)}}();e.executeQuery=function(){var c=g._asyncToGenerator(function*(a,b){a=this._ensureQueryJSON(a);if(a.returnGeometry)throw new p("feature-store:unsupported-query","returnGeometry is not yet supported for mesh scene layer queries");if(a.returnCentroid)throw new p("feature-store:unsupported-query","returnCentroid is not yet supported for mesh scene layer queries");
b=yield this._dataQueryEngine.executeQuery(a,b);b=y.fromJSON(b);b.features.forEach(k=>{k.geometry=null});return b});return function(a,b){return c.apply(this,arguments)}}();e._ensureQueryJSON=function(c){return m.isNone(c)?this.defaultQueryJSON:c.toJSON()};e._ensureDataQueryEngine=function(){if(this._dataQueryEngineInstance)return this._dataQueryEngineInstance;const c=this.layer.objectIdField||w.fallbackObjectIDAttribute,a=this.layer.fields?.map(n=>n.toJSON())??[],b=this.layerView.view.resourceController.scheduler,
k=this.spatialReference.toJSON();return this._dataQueryEngineInstance=new A({hasZ:!0,hasM:!1,geometryType:"esriGeometryPolygon",fields:a,timeInfo:null,spatialReference:k,objectIdField:c,featureStore:this.spatialIndex,scheduler:b,priority:this.priority})};g._createClass(l,[{key:"spatialReference",get:function(){return this.layerView.view.spatialReference}},{key:"layer",get:function(){return this.layerView.i3slayer}},{key:"defaultQueryJSON",get:function(){return(new z({outSpatialReference:this.spatialReference})).toJSON()}},
{key:"_dataQueryEngine",get:function(){return this._ensureDataQueryEngine()}}]);return l}(r);f.__decorate([h.property({constructOnly:!0})],d.I3SQueryEngine.prototype,"layerView",void 0);f.__decorate([h.property({constructOnly:!0})],d.I3SQueryEngine.prototype,"priority",void 0);f.__decorate([h.property({constructOnly:!0})],d.I3SQueryEngine.prototype,"spatialIndex",void 0);f.__decorate([h.property()],d.I3SQueryEngine.prototype,"spatialReference",null);f.__decorate([h.property()],d.I3SQueryEngine.prototype,
"layer",null);f.__decorate([h.property()],d.I3SQueryEngine.prototype,"defaultQueryJSON",null);d.I3SQueryEngine=f.__decorate([u.subclass("esri.views.3d.layers.i3s.I3SQueryEngine")],d.I3SQueryEngine);Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});