// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/maybe ../../../../renderers/PointCloudClassBreaksRenderer ../../../../renderers/PointCloudStretchRenderer ../../../../renderers/PointCloudUniqueValueRenderer ./I3SBinaryReader ./LEPCC".split(" "),function(q,v,A,B,C,w,D){function y(a,b){const h=new Float64Array(b);for(let l=0;l<b;l++)h[l]=a[3*l+2];return h}function x(a){return null==a||"none"===a?null:"low-four-bit"===a?b=>b&15:"high-four-bit"===a?b=>(b&240)>>4:"absolute-value"===a?b=>Math.abs(b):"modulo-ten"===a?b=>
b%10:null}function z(a){let b=0;for(const h of a?a:[])b|=1<<h;return b}q.elevationFromPositions=y;q.evaluateRenderer=function(a,b,h,l){const {rendererJSON:m,isRGBRenderer:n}=a;var f=a=null;if(b&&n)a=b;else if(b&&"pointCloudUniqueValueRenderer"===m?.type){f=C.fromJSON(m);var c=f.colorUniqueValueInfos;a=new Uint8Array(3*l);var g=x(f.fieldTransformType);for(var e=0;e<l;e++){var k=(g?g(b[e]):b[e])+"";for(var d=0;d<c.length;d++)if(c[d].values.includes(k)){a[3*e]=c[d].color.r;a[3*e+1]=c[d].color.g;a[3*
e+2]=c[d].color.b;break}}}else if(b&&"pointCloudStretchRenderer"===m?.type)for(f=B.fromJSON(m),c=f.stops,a=new Uint8Array(3*l),g=x(f.fieldTransformType),e=0;e<l;e++)if(k=g?g(b[e]):b[e],d=c.length-1,k<c[0].value)a[3*e]=c[0].color.r,a[3*e+1]=c[0].color.g,a[3*e+2]=c[0].color.b;else if(k>=c[d].value)a[3*e]=c[d].color.r,a[3*e+1]=c[d].color.g,a[3*e+2]=c[d].color.b;else for(d=1;d<c.length;d++){if(k<c[d].value){k=(k-c[d-1].value)/(c[d].value-c[d-1].value);a[3*e]=c[d].color.r*k+c[d-1].color.r*(1-k);a[3*e+
1]=c[d].color.g*k+c[d-1].color.g*(1-k);a[3*e+2]=c[d].color.b*k+c[d-1].color.b*(1-k);break}}else if(b&&"pointCloudClassBreaksRenderer"===m?.type)for(f=A.fromJSON(m),c=f.colorClassBreakInfos,a=new Uint8Array(3*l),g=x(f.fieldTransformType),e=0;e<l;e++)for(k=g?g(b[e]):b[e],d=0;d<c.length;d++){if(k>=c[d].minValue&&k<=c[d].maxValue){a[3*e]=c[d].color.r;a[3*e+1]=c[d].color.g;a[3*e+2]=c[d].color.b;break}}else for(a=new Uint8Array(3*l),b=0;b<a.length;b++)a[b]=255;if(h&&f&&f.colorModulation)for(b=f.colorModulation.minValue,
f=f.colorModulation.maxValue,c=0;c<l;c++)g=h[c],g=g>=f?1:g<=b?.3:.3+.7*(g-b)/(f-b),a[3*c]*=g,a[3*c+1]*=g,a[3*c+2]*=g;return a};q.filterInPlace=function(a,b,h,l,m){const n=a.length/3;let f=0;for(let p=0;p<n;p++){let r=!0;for(let t=0;t<l.length&&r;t++){var {filterJSON:c}=l[t],g=m[t].values[p];switch(c.type){case "pointCloudValueFilter":var e="exclude"===c.mode;c.values.includes(g)===e&&(r=!1);break;case "pointCloudBitfieldFilter":e=z(c.requiredSetBits);c=z(c.requiredClearBits);if((g&e)!==e||0!==(g&
c))r=!1;break;case "pointCloudReturnFilter":var k=g&15,d=g>>>4&15;g=1<d;e=1===k;k=k===d;d=!1;for(const u of c.includedReturns)if("last"===u&&k||"firstOfMany"===u&&e&&g||"lastOfMany"===u&&k&&g||"single"===u&&!g){d=!0;break}d||(r=!1)}}r&&(h[f]=p,a[3*f]=a[3*p],a[3*f+1]=a[3*p+1],a[3*f+2]=a[3*p+2],b[3*f]=b[3*p],b[3*f+1]=b[3*p+1],b[3*f+2]=b[3*p+2],f++)}return f};q.getAttributeValues=function(a,b,h){return v.isSome(a)&&a.attributeInfo.useElevation?b?y(b,h):null:v.isSome(a)&&a.attributeInfo.storageInfo?w.readBinaryAttribute(a.attributeInfo.storageInfo,
a.buffer,h):null};q.readGeometry=function(a,b){if(null==a.encoding||""===a.encoding){a=w.createGeometryIndexFromSchema(b,a);if(v.isNone(a.vertexAttributes.position))return;b=w.createTypedView(b,a.vertexAttributes.position);var h=a.header.fields;a=[h.offsetX,h.offsetY,h.offsetZ];h=[h.scaleX,h.scaleY,h.scaleZ];const l=b.length/3,m=new Float64Array(3*l);for(let n=0;n<l;n++)m[3*n]=b[3*n]*h[0]+a[0],m[3*n+1]=b[3*n+1]*h[1]+a[1],m[3*n+2]=b[3*n+2]*h[2]+a[2];return m}if("lepcc-xyz"===a.encoding)return D.decodeXYZ(b).result};
Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});