// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../kernel ../../core/Error ../../core/jsonMap ../../core/maybe ../../core/sql ./layerUtils ../../rest/support/AttachmentQuery ../../rest/support/Query ../../rest/support/RelationshipQuery".split(" "),function(L,f,h,m,g,p,H,M,N,O,n,I){function q(){q=h._asyncToGenerator(function*(a,b,d,c){const e=yield l(a);yield r(a,b,c);if(!e.addAttachment)throw new g(c,"Layer source does not support addAttachment capability");return e.addAttachment(b,
d)});return q.apply(this,arguments)}function r(a,b,d){const {attributes:c}=b,{objectIdField:e}=a;return a.get("capabilities.data.supportsAttachment")?b?c?e&&c[e]?Promise.resolve():Promise.reject(new g(d,`feature is missing the identifying attribute ${e}`)):Promise.reject(new g(d,"'attributes' are required on a feature to query attachments")):Promise.reject(new g(d,"A feature is required to add/delete/update attachments")):Promise.reject(new g(d,"this layer doesn't support attachments"))}function t(){t=
h._asyncToGenerator(function*(a,b,d,c,e){const k=yield l(a);yield r(a,b,e);if(!k.updateAttachment)throw new g(e,"Layer source does not support updateAttachment capability");return k.updateAttachment(b,d,c)});return t.apply(this,arguments)}function u(){u=h._asyncToGenerator(function*(a,b,d){const c=yield new Promise((e,k)=>L(["../graphics/editingSupport"],e,k));a=yield a.load();return c.applyEdits(a,a.source,b,d)});return u.apply(this,arguments)}function v(){v=h._asyncToGenerator(function*(a,b,d,c){const e=
yield l(a);yield r(a,b,c);if(!e.deleteAttachments)throw new g(c,"Layer source does not support deleteAttachments capability");return e.deleteAttachments(b,d)});return v.apply(this,arguments)}function w(){w=h._asyncToGenerator(function*(a,b,d){a=(yield a.load({signal:b?.signal})).source;if(!a.fetchRecomputedExtents)throw new g(d,"Layer source does not support fetchUpdates capability");return a.fetchRecomputedExtents(b)});return w.apply(this,arguments)}function x(){x=h._asyncToGenerator(function*(a,
b,d,c){b=O.from(b);yield a.load();d=a.source;a=a.capabilities;if(!a?.data?.supportsAttachment)throw new g(c,"this layer doesn't support attachments");const {attachmentTypes:e,objectIds:k,globalIds:J,num:P,size:Q,start:R,where:K}=b;if(!a?.operations?.supportsQueryAttachments&&(0<e?.length||0<J?.length||0<Q?.length||P||R||K))throw new g(c,"when 'capabilities.operations.supportsQueryAttachments' is false, only objectIds is supported",b);if(!(k?.length||J?.length||K))throw new g(c,"'objectIds', 'globalIds', or 'where' are required to perform attachment query",
b);if(!d.queryAttachments)throw new g(c,"Layer source does not support queryAttachments capability",b);return d.queryAttachments(b)});return x.apply(this,arguments)}function y(){y=h._asyncToGenerator(function*(a,b,d,c){const e=yield l(a);if(!e.queryObjectIds)throw new g(c,"Layer source does not support queryObjectIds capability");return e.queryObjectIds(n.from(b)??a.createQuery(),d)});return y.apply(this,arguments)}function z(){z=h._asyncToGenerator(function*(a,b,d,c){const e=yield l(a);if(!e.queryFeatureCount)throw new g(c,
"Layer source does not support queryFeatureCount capability");return e.queryFeatureCount(n.from(b)??a.createQuery(),d)});return z.apply(this,arguments)}function A(){A=h._asyncToGenerator(function*(a,b,d,c){const e=yield l(a);if(!e.queryExtent)throw new g(c,"Layer source does not support queryExtent capability");return e.queryExtent(n.from(b)??a.createQuery(),d)});return A.apply(this,arguments)}function B(){B=h._asyncToGenerator(function*(a,b,d,c){a=yield l(a);if(!a.queryRelatedFeatures)throw new g(c,
"Layer source does not support queryRelatedFeatures capability");return a.queryRelatedFeatures(I.from(b),d)});return B.apply(this,arguments)}function C(){C=h._asyncToGenerator(function*(a,b,d,c){a=yield l(a);if(!a.queryRelatedFeaturesCount)throw new g(c,"Layer source does not support queryRelatedFeaturesCount capability");return a.queryRelatedFeaturesCount(I.from(b),d)});return C.apply(this,arguments)}function D(){D=h._asyncToGenerator(function*(a){const b=a.source;if(b?.refresh)try{const {dataChanged:d,
updates:c}=yield b.refresh();H.isSome(c)&&(a.sourceJSON={...a.sourceJSON,...c},a.read(c,{origin:"service",url:a.parsedUrl}));if(d)return!0}catch{}if(a.definitionExpression)try{return(yield M.parseWhereClause(a.definitionExpression,a.fieldsIndex)).hasDateFunctions}catch{}return!1});return D.apply(this,arguments)}function l(a){return E.apply(this,arguments)}function E(){E=h._asyncToGenerator(function*(a){return(yield a.load()).source});return E.apply(this,arguments)}function S(a,b){return F.apply(this,
arguments)}function F(){F=h._asyncToGenerator(function*(a,b){if(m.id&&!m.id.findCredential(a)){var d;try{const c=yield N.getOwningPortalUrl(a,b);c&&(d=yield m.id.checkSignInStatus(`${c}/sharing`))}catch(c){}if(d)try{const c=H.isSome(b)?b.signal:null;yield m.id.getCredential(a,{signal:c})}catch(c){}}});return F.apply(this,arguments)}function G(){G=h._asyncToGenerator(function*(a,b){const d=a.parsedUrl?.path;if(d){var c=a.editFieldsInfo;if(a.userHasUpdateItemPrivileges||a.userHasFullEditingPrivileges&&
a.capabilities.operations.supportsEditing||c?.creatorField||c?.editorField)yield S(d,b)}});return G.apply(this,arguments)}p=new p.JSONMap({esriGeometryPoint:"point",esriGeometryMultipoint:"multipoint",esriGeometryPolyline:"polyline",esriGeometryPolygon:"polygon",esriGeometryMultiPatch:"multipatch"});f.addAttachment=function(a,b,d,c){return q.apply(this,arguments)};f.applyEdits=function(a,b,d){return u.apply(this,arguments)};f.computeEffectiveEditingEnabled=function(a){return a.sourceJSON?.isMultiServicesView?
!1:a.userHasUpdateItemPrivileges||a.editingEnabled};f.createQuery=function(a){const b=new n,d=a.get("capabilities.data"),c=a.get("capabilities.query");b.historicMoment=a.historicMoment;b.gdbVersion=a.gdbVersion;b.returnGeometry=!0;c&&(b.compactGeometryEnabled=c.supportsCompactGeometry,b.defaultSpatialReferenceEnabled=c.supportsDefaultSpatialReference);d&&(d.supportsZ&&null!=a.returnZ&&(b.returnZ=a.returnZ),d.supportsM&&null!=a.returnM&&(b.returnM=a.returnM));b.outFields=["*"];const {timeOffset:e,
timeExtent:k}=a;b.timeExtent=null!=e&&null!=k?k.offset(-e.value,e.unit):k||null;b.multipatchOption="multipatch"===a.geometryType?"xyFootprint":null;return b};f.deleteAttachments=function(a,b,d,c){return v.apply(this,arguments)};f.ensureLayerCredential=function(a,b){return G.apply(this,arguments)};f.fetchRecomputedExtents=function(a,b,d){return w.apply(this,arguments)};f.geometryTypeKebabDict=p;f.hasDataChanged=function(a){return D.apply(this,arguments)};f.queryAttachments=function(a,b,d,c){return x.apply(this,
arguments)};f.queryExtent=function(a,b,d,c){return A.apply(this,arguments)};f.queryFeatureCount=function(a,b,d,c){return z.apply(this,arguments)};f.queryObjectIds=function(a,b,d,c){return y.apply(this,arguments)};f.queryRelatedFeatures=function(a,b,d,c){return B.apply(this,arguments)};f.queryRelatedFeaturesCount=function(a,b,d,c){return C.apply(this,arguments)};f.readGlobalIdField=function(a){const {globalIdField:b,fields:d}=a;if(b)return b;if(d)for(const c of d)if("esriFieldTypeGlobalID"===c.type)return c.name};
f.readObjectIdField=function(a){const {objectIdField:b,fields:d}=a;if(b)return b;if(d)for(const c of d)if("esriFieldTypeOID"===c.type)return c.name};f.readVersion=function(a){return a.currentVersion?a.currentVersion:a.hasOwnProperty("capabilities")||a.hasOwnProperty("drawingInfo")||a.hasOwnProperty("hasAttachments")||a.hasOwnProperty("htmlPopupType")||a.hasOwnProperty("relationships")||a.hasOwnProperty("timeInfo")||a.hasOwnProperty("typeIdField")||a.hasOwnProperty("types")?10:9.3};f.updateAttachment=
function(a,b,d,c,e){return t.apply(this,arguments)};Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});