// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../core/lang ../../core/maybe ./RasterFunction ./rasterFunctionUtils ./rasterFormats/pixelRangeUtils ../../renderers/support/colorRampUtils ../../renderers/support/stretchRendererUtils ../../renderers/visualVariables/SizeVariable".split(" "),function(w,B,C,k,H,I,v,J,K){function D(a,b){for(const c in a)"raster"===c.toLowerCase()&&("RasterFunctionVariable"===a[c].type?(a[c]=b.rasterFunctionDefinition,a[c].type="RasterFunctionTemplate"):"RasterFunctionTemplate"===a[c].type&&D(a[c].arguments,
b))}function r(a){const b=B.clone(H.schema[a.functionName+"Function"]);a=a.functionArguments;for(const c in a)"raster"===c.toLowerCase()?(b.arguments[c]=r(a[c]),b.arguments[c].type="RasterFunctionTemplate"):"colormap"===c.toLowerCase()?(b.arguments[c].value=L(a[c]),b.arguments.ColorSchemeType.value=0):b.arguments[c].value=a[c];return b}function E(a){const b=a?.Raster;return b&&"esri.layers.support.RasterFunction"===b.declaredClass?E(b.functionArguments):a}function M(a,b){const c=new k;c.functionName=
"VectorFieldRenderer";const {dataType:g,bandProperties:e}=b,d="vector-uv"===g?!0:!1;let l,n;e&&2===e.length&&(l=e.map(h=>h.BandName.toLowerCase()).indexOf("magnitude"),n=e.map(h=>h.BandName.toLowerCase()).indexOf("direction"));if(-1===l||null===l)l=0,n=1;const p="arithmetic"===a.rotationType?1:2,t="flow-from"===a.flowRepresentation?0:1,q=a.visualVariables?a.visualVariables.find(h=>"Magnitude"===h.field):new K;a={magnitudeBandID:l,directionBandID:n,isUVComponents:d,referenceSystem:p,massFlowAngleRepresentation:t,
symbolTileSize:50,symbolTileSizeUnits:100,calculationMethod:"Vector Average",symbologyName:N[a.style.toLowerCase().replace("-","_")],minimumMagnitude:q.minDataValue,maximumMagnitude:q.maxDataValue,minimumSymbolSize:q.minSize,maximumSymbolSize:q.maxSize};c.functionArguments=a;return b.convertToRFT?new k({rasterFunctionDefinition:r(c)}):c}function O(a,b){const c=b.convertToRFT,g=new k;g.functionName="Stretch";var e=x[J.stretchTypeJSONDict.toJSON(a.stretchType)],d=P(a.statistics??[]);d={StretchType:e,
Statistics:d,DRA:a.dynamicRangeAdjustment,UseGamma:a.useGamma,Gamma:a.gamma,ComputeGamma:a.computeGamma};null!=a.outputMin&&(d.Min=a.outputMin);null!=a.outputMax&&(d.Max=a.outputMax);e===x.standardDeviation?(d.NumberOfStandardDeviations=a.numberOfStandardDeviations,g.outputPixelType="u8"):e===x.percentClip?(d.MinPercent=a.minPercent,d.MaxPercent=a.maxPercent,g.outputPixelType="u8"):e===x.minMax?g.outputPixelType="u8":e===x.sigmoid&&(d.SigmoidStrengthLevel=a.sigmoidStrengthLevel);g.functionArguments=
d;g.variableName="Raster";if(a.colorRamp){d=a.colorRamp;e=new k;if(c)e.functionArguments={ColorRamp:v.getRFxArgColorRampValue(d)};else{const l=v.getColorRampName(d);l?e.functionArguments={colorRamp:l}:!b.convertColorRampToColormap||"algorithmic"!==d.type&&"multipart"!==d.type?(a=a.colorRamp.toJSON(),"algorithmic"===a.type?a.algorithm=a.algorithm||"esriCIELabAlgorithm":"multipart"===a.type&&a.colorRamps?.length&&a.colorRamps.forEach(n=>n.algorithm=n.algorithm||"esriCIELabAlgorithm"),e.functionArguments=
{colorRamp:a}):e.functionArguments={Colormap:v.convertColorRampToColormap(d)}}e.variableName="Raster";e.functionName="Colormap";e.functionArguments.Raster=g;return c?new k({rasterFunctionDefinition:r(e)}):e}return c?new k({rasterFunctionDefinition:r(g)}):g}function Q(a,b){const c=[],g=[],e=[],d=[],{pixelType:l,rasterAttributeTable:n}=b,p=C.isNone(n)?null:n.features,t=F(n);if(t&&p&&Array.isArray(p)&&a.classBreakInfos){a.classBreakInfos.forEach((f,y)=>{const u=f.symbol?.color;let z;u?.a&&null!=f.minValue&&
null!=f.maxValue&&p.forEach(G=>{null!=f.minValue&&null!=f.maxValue&&(z=G.attributes[a.field],(z>=f.minValue&&z<f.maxValue||y===a.classBreakInfos.length-1&&z>=f.minValue)&&d.push([G.attributes[t],u.r,u.g,u.b]))})});var q=l?A(d,l):d,h=new k;h.functionName="Colormap";h.functionArguments={};h.functionArguments.Colormap=q;h.variableName="Raster";return b.convertToRFT?new k({rasterFunctionDefinition:r(h)}):h}a.classBreakInfos.forEach((f,y)=>{if(null!=f.minValue&&null!=f.maxValue){var u=f.symbol&&f.symbol.color;
u?.a?(0===y?c.push(f.minValue,f.maxValue+1E-6):c.push(f.minValue+1E-6,f.maxValue+1E-6),g.push(y),d.push([y,u.r,u.g,u.b])):e.push(f.minValue,f.maxValue)}});q=l?A(d,l):d;h=new k;h.functionName="Remap";h.functionArguments={InputRanges:c,OutputValues:g,NoDataRanges:e};h.variableName="Raster";const m=new k;m.functionName="Colormap";m.functionArguments={Colormap:q,Raster:h};return b.convertToRFT?new k({rasterFunctionDefinition:r(m)}):m}function A(a,b){(b=R.has(b)?I.getPixelValueRange(b):null)&&a.push([Math.floor(b[0]-
1),0,0,0],[Math.ceil(b[1]+1),0,0,0]);return a}function F(a){if(!C.isNone(a))return{fields:a}=a,(a=a&&a.find(b=>b&&b.name&&"value"===b.name.toLowerCase()))&&a.name}function S(a,b){const c=[],{pixelType:g,rasterAttributeTable:e}=b;var d=C.isNone(e)?null:e.features;const l=F(e),n=a.defaultSymbol?.color?.toRgb();var p=a.uniqueValueInfos;if(p)if(!d)for(a=0;a<p.length;a++){var t=p[a];d=t.symbol?.color;t=+t.value;if(d?.a){if(isNaN(t))return null;c.push([t,d.r,d.g,d.b])}}else if(l){const q=new Map;p.forEach(m=>
{const f=m.value;m=m.symbol?.color;null!=f&&m&&m.a&&q.set(String(f),m.toRgb())});const h=a.field;d.forEach(({attributes:m})=>{const f=m[l];(m=q.get(String(m[h])))?c.push([f,...m]):n&&c.push([f,...n])})}p=g&&0<c.length?A(c,g):c;a=new k;a.functionName="Colormap";a.functionArguments={};a.functionArguments.Colormap=p;a.variableName="Raster";return b.convertToRFT?new k({rasterFunctionDefinition:r(a)}):a}function P(a){const b=[];a?.forEach(c=>{Array.isArray(c)?b.push(c):null!=c.min&&null!=c.max&&b.push([c.min,
c.max,c.avg||0,c.stddev||0])});return b}function L(a){const b=[],c=[];a.forEach(g=>{b.push(g[0]);c.push(v.rgbaConvertTo32Bit([...g.slice(1),255]))});return{type:"RasterColormap",values:b,colors:c}}const R=new Set("u1 u2 u4 u8 s8 u16 s16".split(" ")),N={simple_scalar:"Simple Scalar",wind_barb:"Wind Barb",single_arrow:"Single Arrow",beaufort_kn:"Beaufort Wind (Knots)",beaufort_m:"Beaufort Wind (MetersPerSecond)",ocean_current_m:"Ocean Current (MetersPerSecond)",ocean_current_kn:"Ocean Current (Knots)"},
T=new Set("raster-stretch unique-value class-breaks raster-shaded-relief vector-field raster-colormap".split(" ")),x={none:0,standardDeviation:3,histogramEqualization:4,minMax:5,percentClip:6,sigmoid:9};w.combineRenderingRules=function(a,b){if(!a||!b)return B.clone(a||b);a=B.clone(a);if(a.rasterFunctionDefinition&&b.rasterFunctionDefinition){const c=b.rasterFunctionDefinition;if(c.thumbnail||c.thumbnailEx)c.thumbnail=c.thumbnailEx=void 0;D(a.rasterFunctionDefinition.arguments,b)}else"none"!==b.functionName?.toLowerCase()&&
(E(a.functionArguments).Raster=b);return a};w.convertRendererToRenderingRule=function(a,b){b=b||{};switch(a.type){case "raster-stretch":return O(a,b);case "class-breaks":return Q(a,b);case "unique-value":return S(a,b);case "raster-colormap":var c=b;(b=a.extractColormap())&&0!==b.length?({pixelType:a}=c,a=a?A(b,a):b,b=new k,b.functionName="Colormap",b.functionArguments={},b.functionArguments.Colormap=a,a=c.convertToRFT?new k({rasterFunctionDefinition:r(b)}):b):a=null;return a;case "vector-field":return M(a,
b);case "raster-shaded-relief":c=b.convertToRFT;if("elevation"!==b.dataType&&("generic"!==b.dataType||1!==b.bandCount||"s16"!==b.pixelType&&"s32"!==b.pixelType&&"f32"!==b.pixelType&&"f64"!==b.pixelType))a=new k;else{b=new k;b.functionName="Hillshade";var g="traditional"===a.hillshadeType?0:1,e="none"===a.scalingType?1:3,d={HillshadeType:g,SlopeType:e,ZFactor:a.zFactor};0===g&&(d.Azimuth=a.azimuth,d.Altitude=a.altitude);3===e&&(d.PSPower=a.pixelSizePower,d.PSZFactor=a.pixelSizeFactor);b.functionArguments=
d;b.variableName="Raster";a.colorRamp&&(b.functionName="ShadedRelief",c?d.ColorRamp=v.getRFxArgColorRampValue(a.colorRamp):d.Colormap=v.convertColorRampToColormap(a.colorRamp));a=c?new k({rasterFunctionDefinition:r(b)}):b}return a;case "flow":throw Error("Unsupported rendering rule.");}};w.convertRenderingRuleToRFT=r;w.isSupportedRendererType=function(a){return T.has(a.type)};Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});