// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports","../../core/has","../../core/maybe","./arcgisLayerUrl"],function(q,t,u,r){function b(a,d,c){return!(a&&a.hasOwnProperty(d)?!a[d]:!c)}function p(a,d,c){return a&&a.hasOwnProperty(d)?a[d]:c}function v(a){a=a?.supportedSpatialAggregationStatistics?.map(d=>d.toLowerCase());return{envelope:!!a?.includes("envelopeaggregate"),centroid:!!a?.includes("centroidaggregate"),convexHull:!!a?.includes("convexhullaggregate")}}function n(a,d){return!!a?.supportedOperationsWithCacheHint?.map(c=>c.toLowerCase())?.includes(d.toLowerCase())}
function w(a){const d=a.attachmentProperties,c={supportsName:!1,supportsSize:!1,supportsContentType:!1,supportsKeywords:!1,supportsExifInfo:!1,supportsCacheHint:n(a.advancedQueryCapabilities,"queryAttachments"),supportsResize:b(a,"supportsAttachmentsResizing",!1)};d&&Array.isArray(d)&&d.forEach(e=>{const f=x[e.name];f&&(c[f]=!!e.isEnabled)});return c}function y(a,d,c){a=a?a.toLowerCase().split(",").map(m=>m.trim()):[];c=c?r.parse(c):null;c=a.includes(u.isSome(c)&&"MapServer"===c.serverType?"data":
"query");const e=a.includes("editing")&&!d.datesInUnknownTimezone;let f=e&&a.includes("create"),g=e&&a.includes("delete"),l=e&&a.includes("update");const h=a.includes("changetracking"),k=d.advancedQueryCapabilities;!e||f||g||l||(f=g=l=!0);return{supportsCalculate:b(d,"supportsCalculate",!1),supportsTruncate:b(d,"supportsTruncate",!1),supportsValidateSql:b(d,"supportsValidateSql",!1),supportsAdd:f,supportsDelete:g,supportsEditing:e,supportsChangeTracking:h,supportsQuery:c,supportsQueryAnalytics:b(k,
"supportsQueryAnalytic",!1),supportsQueryAttachments:b(k,"supportsQueryAttachments",!1),supportsQueryTopFeatures:b(k,"supportsTopFeaturesQuery",!1),supportsResizeAttachments:b(d,"supportsAttachmentsResizing",!1),supportsSync:a.includes("sync"),supportsUpdate:l,supportsExceedsLimitStatistics:b(d,"supportsExceedsLimitStatistics",!1)}}function z(a,d){const c=a.advancedQueryCapabilities,e=a.ownershipBasedAccessControlForFeatures,f=a.archivingInfo;var g=a.currentVersion;g=!d?.includes("MapServer")||g>=
t("mapserver-pbf-version-support");d=r.isHostedAgolService(d);const l=new Set((a.supportedQueryFormats??"").split(",").map(h=>h.toLowerCase().trim()));return{supportsStatistics:b(c,"supportsStatistics",a.supportsStatistics),supportsPercentileStatistics:b(c,"supportsPercentileStatistics",!1),supportsSpatialAggregationStatistics:b(c,"supportsSpatialAggregationStatistics",!1),supportedSpatialAggregationStatistics:v(c),supportsCentroid:b(c,"supportsReturningGeometryCentroid",!1),supportsDistance:b(c,
"supportsQueryWithDistance",!1),supportsDistinct:b(c,"supportsDistinct",a.supportsAdvancedQueries),supportsExtent:b(c,"supportsReturningQueryExtent",!1),supportsGeometryProperties:b(c,"supportsReturningGeometryProperties",!1),supportsHavingClause:b(c,"supportsHavingClause",!1),supportsOrderBy:b(c,"supportsOrderBy",a.supportsAdvancedQueries),supportsPagination:b(c,"supportsPagination",!1),supportsQuantization:b(a,"supportsCoordinatesQuantization",!1),supportsQuantizationEditMode:b(a,"supportsQuantizationEditMode",
!1),supportsQueryGeometry:b(a,"supportsReturningQueryGeometry",!1),supportsResultType:b(c,"supportsQueryWithResultType",!1),supportsMaxRecordCountFactor:b(c,"supportsMaxRecordCountFactor",!1),supportsSqlExpression:b(c,"supportsSqlExpression",!1),supportsStandardizedQueriesOnly:b(a,"useStandardizedQueries",!1),supportsTopFeaturesQuery:b(c,"supportsTopFeaturesQuery",!1),supportsQueryByOthers:b(e,"allowOthersToQuery",!0),supportsHistoricMoment:b(f,"supportsQueryWithHistoricMoment",!1),supportsFormatPBF:g&&
l.has("pbf"),supportsDisjointSpatialRelationship:b(c,"supportsDisjointSpatialRel",!1),supportsCacheHint:b(c,"supportsQueryWithCacheHint",!1)||n(c,"query"),supportsDefaultSpatialReference:b(c,"supportsDefaultSR",!1),supportsCompactGeometry:d,supportsFullTextSearch:b(c,"supportsFullTextSearch",!1),maxRecordCountFactor:p(a,"maxRecordCountFactor",void 0),maxRecordCount:p(a,"maxRecordCount",void 0),standardMaxRecordCount:p(a,"standardMaxRecordCount",void 0),tileMaxRecordCount:p(a,"tileMaxRecordCount",
void 0)}}const x={name:"supportsName",size:"supportsSize",contentType:"supportsContentType",keywords:"supportsKeywords",exifInfo:"supportsExifInfo"};q.getFeatureLayerCapabilities=function(a,d){var c={supportsCacheHint:n(a.advancedQueryCapabilities,"queryAnalytics")},e=w(a);var f={isVersioned:b(a,"isDataVersioned",!1),supportsAttachment:b(a,"hasAttachments",!1),supportsM:b(a,"hasM",!1),supportsZ:b(a,"hasZ",!1)};var g={supportsAdvancedFieldProperties:b(a,"supportsFieldDescriptionProperty",!1)},l=y(a.capabilities,
a,d);d=z(a,d);var h=a.advancedQueryCapabilities;var k=b(h,"supportsAdvancedQueryRelated",!1);h={supportsPagination:b(h,"supportsQueryRelatedPagination",!1),supportsCount:k,supportsOrderBy:k,supportsCacheHint:n(h,"queryRelated")};k={supportsCacheHint:n(a.advancedQueryCapabilities,"queryTopFilter")};const m=a.ownershipBasedAccessControlForFeatures;a={supportsGeometryUpdate:b(a,"allowGeometryUpdates",!0),supportsGlobalId:b(a,"supportsApplyEditsWithGlobalIds",!1),supportsReturnServiceEditsInSourceSpatialReference:b(a,
"supportsReturnServiceEditsInSourceSR",!1),supportsRollbackOnFailure:b(a,"supportsRollbackOnFailureParameter",!1),supportsUpdateWithoutM:b(a,"allowUpdateWithoutMValues",!1),supportsUploadWithItemId:b(a,"supportsAttachmentsByUploadId",!1),supportsDeleteByAnonymous:b(m,"allowAnonymousToDelete",!0),supportsDeleteByOthers:b(m,"allowOthersToDelete",!0),supportsUpdateByAnonymous:b(m,"allowAnonymousToUpdate",!0),supportsUpdateByOthers:b(m,"allowOthersToUpdate",!0)};return{analytics:c,attachment:e,data:f,
metadata:g,operations:l,query:d,queryRelated:h,queryTopFeatures:k,editing:a}};Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});