// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec3f64 ../../../../../core/workers/WorkerHandle ../../../../../chunks/sphere ../../SnappingPoint ../../candidates/EdgeSnappingCandidate ../../candidates/VertexSnappingCandidate".split(" "),
function(f,h,m,w,p,F,G,x,u,y,z,A,B,C){f.SceneLayerSnappingSourceWorkerHandle=function(n){function l(b){b=n.call(this,b)||this;b.availability=0;b._ids=new Set;return b}h._inheritsLoose(l,n);var d=l.prototype;d.destroy=function(){this._workerHandle.destroy();this._workerHandle=null};d.initialize=function(){this._workerHandle=new D(this.schedule,{fetchAllEdgeLocations:(b,a)=>this._fetchAllEdgeLocations(b,a)})};d.fetchCandidates=function(){var b=h._asyncToGenerator(function*(a,c){const q=a.coordinateHelper;
var {point:g}=a;const k=E;this.renderCoordsHelper.toRenderCoords(g,q.spatialReference,k);g=a.distance;a=yield this._workerHandle.invoke({bounds:z.fromValues(k[0],k[1],k[2],"number"===typeof g?g:g.distance),types:a.types},c);a.candidates.sort((e,t)=>e.distance-t.distance);return a.candidates.map(e=>this._convertCandidate(q,e))});return function(a,c){return b.apply(this,arguments)}}();d.add=function(){var b=h._asyncToGenerator(function*(a,c){this._ids.add(a.id);yield this._workerHandle.invokeMethod("add",
a,c)});return function(a,c){return b.apply(this,arguments)}}();d.remove=function(){var b=h._asyncToGenerator(function*(a,c){this._ids.delete(a.id);yield this._workerHandle.invokeMethod("remove",a,c)});return function(a,c){return b.apply(this,arguments)}}();d._convertCandidate=function(b,a){switch(a.type){case "edge":return new B.EdgeSnappingCandidate({objectId:a.objectId,targetPoint:this._convertRenderCoordinate(b,a.target),edgeStart:this._convertRenderCoordinate(b,a.start),edgeEnd:this._convertRenderCoordinate(b,
a.end),isDraped:!1});case "vertex":return new C.VertexSnappingCandidate({objectId:a.objectId,targetPoint:this._convertRenderCoordinate(b,a.target),isDraped:!1})}};d._convertRenderCoordinate=function({spatialReference:b},a){const c=u.create();this.renderCoordsHelper.fromRenderCoords(a,c,b);return A.asSnappingPoint(c)};d._fetchAllEdgeLocations=function(){var b=h._asyncToGenerator(function*(a,c){var q=this;const g=[],k=[];for(const {id:e,uid:t}of a.components)this._ids.has(e)&&g.push(h._asyncToGenerator(function*(){const r=
yield q.fetchEdgeLocations(e,c.signal),v=r.locations.buffer;k.push(v);return{id:e,uid:t,objectIds:r.objectIds,locations:v,origin:r.origin,type:r.type}})());return{result:{components:(yield Promise.all(g)).filter(({id:e})=>this._ids.has(e))},transferList:k}});return function(a,c){return b.apply(this,arguments)}}();return l}(w.HandleOwner);m.__decorate([p.property({constructOnly:!0})],f.SceneLayerSnappingSourceWorkerHandle.prototype,"renderCoordsHelper",void 0);m.__decorate([p.property({constructOnly:!0})],
f.SceneLayerSnappingSourceWorkerHandle.prototype,"fetchEdgeLocations",void 0);m.__decorate([p.property({constructOnly:!0})],f.SceneLayerSnappingSourceWorkerHandle.prototype,"schedule",void 0);m.__decorate([p.property({readOnly:!0})],f.SceneLayerSnappingSourceWorkerHandle.prototype,"availability",void 0);f.SceneLayerSnappingSourceWorkerHandle=m.__decorate([x.subclass("esri.views.interactive.snapping.featureSources.sceneLayerSource.SceneLayerSnappingSourceWorker")],f.SceneLayerSnappingSourceWorkerHandle);
let D=function(n){function l(d,b){return n.call(this,"SceneLayerSnappingSourceWorker","fetchCandidates",{},d,{strategy:"dedicated",client:b})||this}h._inheritsLoose(l,n);return l}(y.WorkerHandle);const E=u.create();Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});