// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/has ../../../core/mathUtils ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../geometry/ellipsoidUtils ../../../geometry/support/spatialReferenceUtils ../../ViewingMode ./AtmosphereType ./ChapmanAtmosphere ./CloudsComposition ./CloudsCompositionParameters ./CloudsData ./CloudsGenerator ./CloudsPresets ./Fog ./PanoramicAtmosphere ./Precipitation ./SimpleAtmosphere ./SimpleHaze ./Stars ./weather ./weatherUtils ../webgl-engine/core/shaderLibrary/ShaderOutput ../webgl-engine/lib/RenderFeature ../webgl-engine/lib/RenderSlot ../webgl-engine/lib/Update".split(" "),
function(e,y,f,J,Z,n,b,g,h,aa,ba,K,q,z,A,B,L,k,x,M,C,D,N,O,E,P,Q,R,F,S,T,G,U,V,v,W){var t;const X=[v.RenderSlot.POSTPROCESSING_ENVIRONMENT_OPAQUE,v.RenderSlot.POSTPROCESSING_ENVIRONMENT_TRANSPARENT];e.EnvironmentRenderer=t=function(u){function p(a){a=u.call(this,a)||this;a._context=null;a._atmosphere=null;a._hqAtmosphere=null;a._oldWeatherParameters=new w;a._newWeatherParameters=new w;a._fadedWeatherParameters=new w;a._weatherParameters=a._newWeatherParameters;return a}y._inheritsLoose(p,u);var d=
p.prototype;d.initialize=function(){this.view._stage.addRenderPlugin(X,this)};d.destroy=function(){this.removeHandles();null!=this.view?._stage&&this.view._stage.removeRenderPlugin(this);this._set("view",null)};d.updateAnimation=function(a){return b.isSome(this._precipitation)?this._precipitation.update(a):!1};d.initializeRenderContext=function(a=null){this._context=a;a=()=>this._setNeedsRender();this.addHandles([g.when(()=>this.view?.basemapTerrain,()=>this._updateBasemapTerrain(),g.syncAndInitial),
g.watch(()=>({viewingMode:this.view.state.viewingMode,enabled:this.view.environment.atmosphereEnabled,quality:this.view.environment.atmosphere.quality}),c=>this._updateAtmosphere(c),g.syncAndInitial),g.watch(()=>this._stars,a),g.watch(()=>this._precipitation,a),g.watch(()=>this._clouds,()=>this._updateWeather(),g.initial),g.watch(()=>this._fog,()=>this._updateFogHaze(),g.initial),g.watch(()=>this._simpleHaze,()=>this._updateFogHaze(),g.initial),g.watch(()=>this.view.state.mode,()=>{this._setNeedsRender()},
g.sync),g.watch(()=>this._atmosphereType,()=>this._updateBasemapTerrain(),g.syncAndInitial),g.watch(()=>this._weatherUpdateParameters,()=>{this._updateWeather();this._updateFogHaze()},g.syncAndInitial)])};d.uninitializeRenderContext=function(){this._context=null;this._atmosphere=b.destroyMaybe(this._atmosphere);this._hqAtmosphere=b.destroyMaybe(this._hqAtmosphere);this._set("_stars",b.destroyMaybe(this._stars));this._set("_precipitation",b.destroyMaybe(this._precipitation));this._set("_clouds",b.destroyMaybe(this._clouds));
this._set("_cloudsComposition",b.destroyMaybe(this._cloudsComposition));this._set("_fog",b.destroyMaybe(this._fog));this._set("_simpleHaze",b.destroyMaybe(this._simpleHaze))};d.prepareRender=function(a){a.bindParameters.cloudsFade.data=D.isReadyCloudsData(this._clouds)?this._clouds:null;"local"!==this.view.viewingMode&&(G.updateWeatherFading(a.bindParameters.cloudsFade,a.bindParameters.camera,this.view.state.mode,a.time,this.view.qualitySettings.fadeDuration),this._updateWeatherFading(a.bindParameters),
a.bindParameters.cloudsFade.renderingStage===D.CloudsRenderingStages.FINISHED&&b.isSome(this._clouds)&&0===this._clouds.coverage&&!1===this._clouds.running&&(this._clouds.destroyFrameBufferCube(),a.bindParameters.cloudsFade.data=null))};d.render=function(a){if(a.output===U.ShaderOutput.Color)switch(a.bindParameters.slot){case v.RenderSlot.POSTPROCESSING_ENVIRONMENT_OPAQUE:b.isSome(this._stars)&&this._stars.render(a);b.isSome(this.atmosphere)&&(this.atmosphere.render(a),b.isSome(this._cloudsComposition)&&
b.isSome(a.bindParameters.cloudsFade.data)&&(this.weatherVisible&&b.isSome(this._clouds)&&this._clouds.updateWeatherTile(),this._cloudsComposition.render(a)),G.weatherFadingNeedsRender(a.bindParameters.cloudsFade)&&b.isSome(this._context)&&this._context.requestRender());break;case v.RenderSlot.POSTPROCESSING_ENVIRONMENT_TRANSPARENT:if(b.isSome(this.atmosphere)&&(this.atmosphere.renderHaze(a,this._weatherParameters.haze.amount),0<this._weatherParameters.haze.amount&&this._atmosphereType!==k.AtmosphereType.Realistic&&
b.isSome(this._simpleHaze)&&this._simpleHaze.render(a,this._weatherParameters.haze),0<this._weatherParameters.fog.amount&&b.isSome(this._fog)&&this._fog.render(a,this._weatherParameters.fog),b.isSome(this._precipitation))){const c=this.view.environment.weather;"rainy"!==c.type&&"snowy"!==c.type||this._precipitation.render(a,c.precipitation,c.type)}}};d.updateLightSources=function(a,c,l,r){if(b.isSome(this._context)){const m=this._context.renderContext;m.bindParameters.oldLighting.copyFrom(m.bindParameters.lighting);
m.bindParameters.newLighting.noonFactor=c;m.bindParameters.newLighting.globalFactor=l;m.bindParameters.newLighting.set(a);r===W.Update.Faded||m.bindParameters.weatherFading?m.bindParameters.fadeLighting(0):m.bindParameters.fadeLighting(1);this._context.requestRender()}};d._updateWeatherFading=function(a){if(a.weatherFading){var c=a.cloudsFade;c.fadeIn.stage===C.FadeInStages.FADE_IN?(a.fadeLighting(c.fadeIn.factor),this._fadeWeather(c.fadeIn.factor)):c.fadeInOut.stage===C.FadeInOutStages.FADE_IN?(a.fadeLighting(c.fadeInOut.factor),
this._fadeWeather(c.fadeInOut.factor)):c.crossFade.enabled?(a.fadeLighting(c.crossFade.factor),this._fadeWeather(c.crossFade.factor)):(a.fadeLighting(0),this._fadeWeather(0))}};d._fadeWeather=function(a){const {_newWeatherParameters:c,_oldWeatherParameters:l}=this;1<=a?this._weatherParameters=c:(this._fadedWeatherParameters.lerp(l,c,a),this._weatherParameters=this._fadedWeatherParameters)};d._updateWeather=function(){const a=this._weatherUpdateParameters;b.isNone(a)||b.isNone(this._clouds)||(this._clouds.applyPreset(O.cloudPresets[a.type],
a.weatherAdjustment),this._setNeedsRender())};d._setNeedsRender=function(){b.isSome(this._context)&&this._context.requestRender()};d._updateFogHaze=function(){const a=this._weatherUpdateParameters;if(!(b.isNone(this._fog)||b.isNone(this._simpleHaze)||b.isNone(a)||b.isNone(this._context))){var c=this._context.renderContext.bindParameters;this._oldWeatherParameters.copyFrom(this._weatherParameters);switch(a.type){case "foggy":this._newWeatherParameters.fog.strength=n.lerp(3E-5,.005,a.weatherAdjustment**
3);q.copy(this._newWeatherParameters.fog.color,H);this._newWeatherParameters.fog.amount=1;this._newWeatherParameters.haze.strength=0;this._newWeatherParameters.haze.amount=this._atmosphereType===k.AtmosphereType.Realistic?1:0;this._setNeedsRender();break;case "rainy":this._newWeatherParameters.fog.strength=n.lerp(4E-6,2E-4,(a.effect??0)**3);q.copy(this._newWeatherParameters.fog.color,Y);this._newWeatherParameters.fog.amount=1;this._newWeatherParameters.haze.strength=0;this._newWeatherParameters.haze.amount=
0;this._setNeedsRender();break;case "snowy":this._newWeatherParameters.fog.strength=n.lerp(4E-6,2E-4,(a.effect??0)**3);q.copy(this._newWeatherParameters.fog.color,H);this._newWeatherParameters.fog.amount=1;this._newWeatherParameters.haze.strength=0;this._newWeatherParameters.haze.amount=this._atmosphereType===k.AtmosphereType.Realistic?1:0;this._setNeedsRender();break;default:this._newWeatherParameters.fog.strength=0,this._newWeatherParameters.fog.amount=0,this._newWeatherParameters.haze.strength=
4E-6,this._newWeatherParameters.haze.amount=1,this._setNeedsRender()}c.weatherFading?this._fadeWeather(0):this._fadeWeather(1)}};d._updateAtmosphere=function(a){a=this._selectAtmosphereType(a);if(b.isSome(this._atmosphere)?this._atmosphere.type!==a:a!==k.AtmosphereType.None){this._atmosphere=b.destroyMaybe(this._atmosphere);this._hqAtmosphere=b.destroyMaybe(this._hqAtmosphere);var c=this._getAtmosphereClass(a);c&&b.isSome(this._context)&&(this._atmosphere=new c(this.view,this._context),a===k.AtmosphereType.Simple&&
(this._hqAtmosphere=new x.ChapmanAtmosphere(this.view,this._context)));this._setNeedsRender();this._updateBasemapTerrain()}};d._getAtmosphereClass=function(a){switch(a){case k.AtmosphereType.Realistic:return x.ChapmanAtmosphere;case k.AtmosphereType.Panoramic:return P.PanoramicAtmosphere;case k.AtmosphereType.Simple:return R;default:case k.AtmosphereType.None:return null}};d._selectAtmosphereType=function(a){const {enabled:c,quality:l,viewingMode:r}=a;return!c||B.isMoon(this.view.spatialReference)?
k.AtmosphereType.None:r===L.ViewingMode.Local?k.AtmosphereType.Panoramic:b.isSome(this._context)&&"high"===l&&x.ChapmanAtmosphere.isSupported(this._context)&&B.isEarth(this.view.spatialReference)?k.AtmosphereType.Realistic:k.AtmosphereType.Simple};d._updateBasemapTerrain=function(){this.view.basemapTerrain&&(this.view.basemapTerrain.velvetOverground=this._atmosphereType===k.AtmosphereType.Simple)};y._createClass(p,[{key:"atmosphere",get:function(){return b.isSome(this._hqAtmosphere)&&this.view._stage.renderer.isFeatureEnabled(V.RenderFeature.RealisticAtmosphere)?
this._hqAtmosphere:this._atmosphere}},{key:"_atmosphereType",get:function(){return b.isSome(this.atmosphere)?this.atmosphere.type:k.AtmosphereType.None}},{key:"canRender",get:function(){return!!this.view.basemapTerrain?.renderer.canRender||"global"!==this.view.viewingMode}},{key:"needsLinearDepth",get:function(){return this._atmosphereType===k.AtmosphereType.Realistic}},{key:"updating",get:function(){return b.isSome(this._stars)&&this._stars.updating||b.isSome(this._clouds)&&this._clouds.running}},
{key:"weatherVisible",get:function(){return q.length(this.view.state.camera.eye)-A.getReferenceEllipsoid(this.view.spatialReference).radius<=T.weatherHeightLimit}},{key:"_stars",get:function(){const a=this.view,c=a.environment?.starsEnabled??!1,l=this._get("_stars");return!c||b.isNone(this._context)?(b.destroyMaybe(l),null):b.isSome(l)?l:new S.Stars({view:a,requestRender:()=>this._setNeedsRender()})}},{key:"_precipitation",get:function(){const a=this._get("_precipitation");if(!this._precipitationEnabled||
b.isNone(this._context))return b.destroyMaybe(a),null;const c=this.view,l=this._context;if(b.isSome(a)&&a.context===l)return a;b.destroyMaybe(a);return new Q.Precipitation({context:l,view:c})}},{key:"_clouds",get:function(){const a=this._get("_clouds");if(!this.weatherEnabled||b.isNone(this._context))return b.destroyMaybe(a),null;if(b.isSome(a))return a;const c=this.view,l=this._context;b.destroyMaybe(a);return new N.CloudsGenerator({context:l,view:c,requestRender:()=>this._setNeedsRender()})}},{key:"_cloudsComposition",
get:function(){const a=this._get("_cloudsComposition");if(!this.weatherEnabled||b.isNone(this._context))return b.destroyMaybe(a),null;const c=this.view.state.viewingMode,l=this._context.renderContext.rctx,r=A.getReferenceEllipsoid(this.view.spatialReference).radius;if(b.isSome(a)&&a.viewingMode===c&&a.planetRadius===r)return a;b.destroyMaybe(a);return new M.CloudsComposition({rctx:l,viewingMode:c,planetRadius:r,requestRender:()=>this._setNeedsRender()})}},{key:"_fog",get:function(){const a=this._get("_fog");
return!this.weatherEnabled||b.isNone(this._context)?(b.destroyMaybe(a),null):b.isSome(a)?a:new E.Fog({context:this._context,view:this.view})}},{key:"_simpleHaze",get:function(){const a=this._get("_simpleHaze");return!this.weatherEnabled||b.isNone(this._context)?(b.destroyMaybe(a),null):b.isSome(a)?a:new F.SimpleHaze({context:this._context,view:this.view})}},{key:"weatherEnabled",get:function(){return!!this.view?.environmentManager?.weatherEnabled}},{key:"_precipitationEnabled",get:function(){return this.weatherEnabled&&
("rainy"===this.view.environment.weather.type||"snowy"===this.view.environment.weather.type)}},{key:"_weatherUpdateParameters",get:function(){const a=this.weatherEnabled?this.view.environment.weather:null;return b.isNone(a)?null:"rainy"===a.type||"snowy"===a.type?{type:a.type,weatherAdjustment:a.cloudCover,effect:a.precipitation}:{type:a.type,weatherAdjustment:"foggy"===a.type?a.fogStrength:a.cloudCover}}},{key:"test",get:function(){return{atmosphere:this._atmosphere,clouds:this._clouds,selectAtmosphereType:()=>
this._selectAtmosphereType({viewingMode:this.view.state.viewingMode,enabled:this.view.environment.atmosphereEnabled,quality:this.view.environment.atmosphere.quality}),stubGetAtmosphereClass:a=>{I=t.prototype._getAtmosphereClass;t.prototype._getAtmosphereClass=a},restoreGetAtmosphereClass:()=>{t.prototype._getAtmosphereClass=I}}}}]);return p}(J);f.__decorate([h.property({constructOnly:!0})],e.EnvironmentRenderer.prototype,"view",void 0);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,
"atmosphere",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_atmosphereType",null);f.__decorate([h.property({type:Boolean,readOnly:!0})],e.EnvironmentRenderer.prototype,"updating",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"weatherVisible",null);f.__decorate([h.property()],e.EnvironmentRenderer.prototype,"_context",void 0);f.__decorate([h.property()],e.EnvironmentRenderer.prototype,"_atmosphere",void 0);f.__decorate([h.property()],
e.EnvironmentRenderer.prototype,"_hqAtmosphere",void 0);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_stars",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_precipitation",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_clouds",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_cloudsComposition",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,
"_fog",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_simpleHaze",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"weatherEnabled",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_precipitationEnabled",null);f.__decorate([h.property({readOnly:!0})],e.EnvironmentRenderer.prototype,"_weatherUpdateParameters",null);e.EnvironmentRenderer=t=f.__decorate([K.subclass("esri.views.3d.environment.EnvironmentRenderer")],
e.EnvironmentRenderer);let w=function(){function u(){this.fog=new E.FogParameters;this.haze=new F.HazeParameters}var p=u.prototype;p.copyFrom=function(d){this.fog.amount=d.fog.amount;this.haze.amount=d.haze.amount;this.fog.strength=d.fog.strength;this.haze.strength=d.haze.strength;q.copy(this.fog.color,d.fog.color)};p.lerp=function(d,a,c){this.fog.amount=n.lerp(d.fog.amount,a.fog.amount,c);this.haze.amount=n.lerp(d.haze.amount,a.haze.amount,c);this.fog.strength=n.lerp(d.fog.strength,a.fog.strength,
c);this.haze.strength=n.lerp(d.haze.strength,a.haze.strength,c);q.lerp(this.fog.color,d.fog.color,a.fog.color,c)};return u}();const Y=z.fromValues(.5,.5,.5),H=z.fromValues(1.5,1.5,1.5);let I;e.WeatherParameters=w;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});