// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["require","exports","./index","./dom","./debounce"],function(Ja,E,Ka,ja,Y){function I(a){return a.split("-")[0]}function J(a){return a.split("-")[1]}function M(a){return["top","bottom"].includes(I(a))?"x":"y"}function Z(a){return"y"===a?"height":"width"}function ka(a,b,c){let {reference:d,floating:e}=a;var f=d.x+d.width/2-e.width/2;const g=d.y+d.height/2-e.height/2;a=M(b);var k=Z(a);k=d[k]/2-e[k]/2;const h=I(b),l="x"===a;switch(h){case "top":f={x:f,y:d.y-e.height};break;case "bottom":f={x:f,
y:d.y+d.height};break;case "right":f={x:d.x+d.width,y:g};break;case "left":f={x:d.x-e.width,y:g};break;default:f={x:d.x,y:d.y}}switch(J(b)){case "start":f[a]-=k*(c&&l?-1:1);break;case "end":f[a]+=k*(c&&l?-1:1)}return f}function la(a){return"number"!==typeof a?{top:0,right:0,bottom:0,left:0,...a}:{top:a,right:a,bottom:a,left:a}}function N(a){return{...a,top:a.y,left:a.x,right:a.x+a.width,bottom:a.y+a.height}}async function O(a,b){var c;void 0===b&&(b={});const {x:d,y:e,platform:f,rects:g,elements:k,
strategy:h}=a,{boundary:l="clippingAncestors",rootBoundary:m="viewport",elementContext:p="floating",altBoundary:r=!1,padding:t=0}=b;a=la(t);var n=k[r?"floating"===p?"reference":"floating":p];b=N(await f.getClippingRect({element:(null!=(c=await (null==f.isElement?void 0:f.isElement(n)))?c:1)?n:n.contextElement||await (null==f.getDocumentElement?void 0:f.getDocumentElement(k.floating)),boundary:l,rootBoundary:m,strategy:h}));n="floating"===p?{...g.floating,x:d,y:e}:g.reference;const q=await (null==
f.getOffsetParent?void 0:f.getOffsetParent(k.floating));c=await (null==f.isElement?void 0:f.isElement(q))?await (null==f.getScale?void 0:f.getScale(q))||{x:1,y:1}:{x:1,y:1};n=N(f.convertOffsetParentRelativeRectToViewportRelativeRect?await f.convertOffsetParentRelativeRectToViewportRelativeRect({rect:n,offsetParent:q,strategy:h}):n);return{top:(b.top-n.top+a.top)/c.y,bottom:(n.bottom-b.bottom+a.bottom)/c.y,left:(b.left-n.left+a.left)/c.x,right:(n.right-b.right+a.right)/c.x}}function S(a){return a.replace(/left|right|bottom|top/g,
b=>La[b])}function ma(a,b,c){void 0===c&&(c=!1);const d=J(a),e=M(a);a=Z(e);c="x"===e?d===(c?"end":"start")?"right":"left":"start"===d?"bottom":"top";b.reference[a]>b.floating[a]&&(c=S(c));return{main:c,cross:S(c)}}function aa(a){return a.replace(/start|end/g,b=>Ma[b])}function Na(a,b,c){return(a?[...c.filter(d=>J(d)===a),...c.filter(d=>J(d)!==a)]:c.filter(d=>I(d)===d)).filter(d=>a?J(d)===a||(b?aa(d)!==d:!1):!0)}function Oa(a){const b=S(a);return[aa(a),b,aa(b)]}function na(a,b){return{top:a.top-b.height,
right:a.right-b.width,bottom:a.bottom-b.height,left:a.left-b.width}}function oa(a){return pa.some(b=>0<=a[b])}async function Pa(a,b){const {placement:c,platform:d,elements:e}=a;var f=await (null==d.isRTL?void 0:d.isRTL(e.floating)),g=I(c);const k=J(c),h="x"===M(c);g=["left","top"].includes(g)?-1:1;f=f&&h?-1:1;a="function"===typeof b?b(a):b;let {mainAxis:l,crossAxis:m,alignmentAxis:p}="number"===typeof a?{mainAxis:a,crossAxis:0,alignmentAxis:null}:{mainAxis:0,crossAxis:0,alignmentAxis:null,...a};k&&
"number"===typeof p&&(m="end"===k?-1*p:p);return h?{x:m*f,y:l*g}:{x:l*g,y:m*f}}function z(a){var b;return(null==(b=a.ownerDocument)?void 0:b.defaultView)||window}function D(a){return z(a).getComputedStyle(a)}function G(a){return a instanceof z(a).Node?(a.nodeName||"").toLowerCase():""}function qa(){if(ba)return ba;const a=navigator.userAgentData;return a&&Array.isArray(a.brands)?ba=a.brands.map(b=>b.brand+"/"+b.version).join(" "):navigator.userAgent}function F(a){return a instanceof z(a).HTMLElement}
function B(a){return a instanceof z(a).Element}function ra(a){if("undefined"===typeof ShadowRoot)return!1;const b=z(a).ShadowRoot;return a instanceof b||a instanceof ShadowRoot}function T(a){const {overflow:b,overflowX:c,overflowY:d,display:e}=D(a);return/auto|scroll|overlay|hidden|clip/.test(b+d+c)&&!["inline","contents"].includes(e)}function ca(a){const b=/firefox/i.test(qa()),c=D(a);a=c.backdropFilter||c.WebkitBackdropFilter;return"none"!==c.transform||"none"!==c.perspective||(a?"none"!==a:!1)||
b&&"filter"===c.willChange||b&&(c.filter?"none"!==c.filter:!1)||["transform","perspective"].some(d=>c.willChange.includes(d))||["paint","layout","strict","content"].some(d=>{const e=c.contain;return null!=e?e.includes(d):!1})}function sa(){return!/^((?!chrome|android).)*safari/i.test(qa())}function da(a){return["html","body","#document"].includes(G(a))}function ta(a){var b=D(a);let c=parseFloat(b.width);b=parseFloat(b.height);const d=a.offsetWidth;a=a.offsetHeight;const e=U(c)!==d||U(b)!==a;e&&(c=
d,b=a);return{width:c,height:b,fallback:e}}function ua(a){return B(a)?a:a.contextElement}function L(a){var b=ua(a);if(!F(b))return va;a=b.getBoundingClientRect();const {width:c,height:d,fallback:e}=ta(b);b=(e?U(a.width):a.width)/c;a=(e?U(a.height):a.height)/d;b&&Number.isFinite(b)||(b=1);a&&Number.isFinite(a)||(a=1);return{x:b,y:a}}function K(a,b,c,d){var e,f;void 0===b&&(b=!1);void 0===c&&(c=!1);var g=a.getBoundingClientRect(),k=ua(a),h=va;b&&(d?B(d)&&(h=L(d)):h=L(a));a=k?z(k):window;b=!sa()&&c;
c=(g.left+(b?(null==(e=a.visualViewport)?void 0:e.offsetLeft)||0:0))/h.x;e=(g.top+(b?(null==(f=a.visualViewport)?void 0:f.offsetTop)||0:0))/h.y;f=g.width/h.x;g=g.height/h.y;if(k)for(k=z(k),h=d&&B(d)?z(d):d,a=k.frameElement;a&&d&&h!==k;){b=L(a);const l=a.getBoundingClientRect(),m=getComputedStyle(a);l.x+=(a.clientLeft+parseFloat(m.paddingLeft))*b.x;l.y+=(a.clientTop+parseFloat(m.paddingTop))*b.y;c*=b.x;e*=b.y;f*=b.x;g*=b.y;c+=l.x;e+=l.y;a=z(a).frameElement}return{width:f,height:g,top:e,right:c+f,bottom:e+
g,left:c,x:c,y:e}}function H(a){return((a instanceof z(a).Node?a.ownerDocument:a.document)||window.document).documentElement}function V(a){return B(a)?{scrollLeft:a.scrollLeft,scrollTop:a.scrollTop}:{scrollLeft:a.pageXOffset,scrollTop:a.pageYOffset}}function wa(a){return K(H(a)).left+V(a).scrollLeft}function P(a){if("html"===G(a))return a;a=a.assignedSlot||a.parentNode||(ra(a)?a.host:null)||H(a);return ra(a)?a.host:a}function xa(a){return F(a)&&"fixed"!==D(a).position?a.offsetParent:null}function ya(a){const b=
z(a);for(var c=xa(a);c&&["table","td","th"].includes(G(c))&&"static"===D(c).position;)c=xa(c);if(c&&("html"===G(c)||"body"===G(c)&&"static"===D(c).position&&!ca(c)))return b;if(!c)a:{for(a=P(a);F(a)&&!da(a);)if(ca(a)){c=a;break a}else a=P(a);c=null}return c||b}function za(a){const b=P(a);return da(b)?a.ownerDocument.body:F(b)&&T(b)?b:za(b)}function Q(a,b){var c;void 0===b&&(b=[]);const d=za(a);a=d===(null==(c=a.ownerDocument)?void 0:c.body);c=z(d);return a?b.concat(c,c.visualViewport||[],T(d)?d:[]):
b.concat(d,Q(d))}function Aa(a,b,c){if("viewport"===b){b=z(a);a=H(a);b=b.visualViewport;var d=a.clientWidth;a=a.clientHeight;var e=0,f=0;if(b){d=b.width;a=b.height;const g=sa();if(g||!g&&"fixed"===c)e=b.offsetLeft,f=b.offsetTop}return N({width:d,height:a,x:e,y:f})}if(B(b))return d=K(b,!0,"fixed"===c),c=d.top+b.clientTop,e=d.left+b.clientLeft,a=F(b)?L(b):{x:1,y:1},d=b.clientWidth*a.x,b=b.clientHeight*a.y,e*=a.x,c*=a.y,{top:c,left:e,right:e+d,bottom:c+b,x:e,y:c,width:d,height:b};f=H(a);c=H(f);a=V(f);
b=null==(d=f.ownerDocument)?void 0:d.body;d=R(c.scrollWidth,c.clientWidth,b?b.scrollWidth:0,b?b.clientWidth:0);e=R(c.scrollHeight,c.clientHeight,b?b.scrollHeight:0,b?b.clientHeight:0);f=-a.scrollLeft+wa(f);a=-a.scrollTop;"rtl"===D(b||c).direction&&(f+=R(c.clientWidth,b?b.clientWidth:0)-d);return N({width:d,height:e,x:f,y:a})}function Qa(a,b){var c=b.get(a);if(c)return c;c=Q(a).filter(g=>B(g)&&"body"!==G(g));let d=null;const e="fixed"===D(a).position;let f=e?P(a):a;for(;B(f)&&!da(f);){const g=D(f),
k=ca(f);(e?k||d:k||"static"!==g.position||!d||!["absolute","fixed"].includes(d.position))?d=g:c=c.filter(h=>h!==f);f=P(f)}b.set(a,c);return c}function Ra(a,b,c,d){function e(){const n=K(a);!t||n.x===t.x&&n.y===t.y&&n.width===t.width&&n.height===t.height||c();t=n;r=requestAnimationFrame(e)}void 0===d&&(d={});const {ancestorScroll:f=!0,ancestorResize:g=!0,elementResize:k=!0,animationFrame:h=!1}=d,l=f&&!h,m=l||g?[...(B(a)?Q(a):a.contextElement?Q(a.contextElement):[]),...Q(b)]:[];m.forEach(n=>{l&&n.addEventListener("scroll",
c,{passive:!0});g&&n.addEventListener("resize",c)});let p=null;if(k){let n=!0;p=new ResizeObserver(()=>{n||c();n=!1});B(a)&&!h&&p.observe(a);B(a)||!a.contextElement||h||p.observe(a.contextElement);p.observe(b)}let r,t=h?K(a):null;h&&e();c();return()=>{var n;m.forEach(q=>{l&&q.removeEventListener("scroll",c);g&&q.removeEventListener("resize",c)});null==(n=p)?void 0:n.disconnect();p=null;h&&cancelAnimationFrame(r)}}function Sa({placement:a,flipDisabled:b,flipPlacements:c,offsetDistance:d,offsetSkidding:e,
arrowEl:f,type:g}){const k=[Ta(),Ua()];return"menu"===g?[...k,Ba({fallbackPlacements:c||"top-start top top-end bottom-start bottom bottom-end".split(" ")})]:"popover"===g||"tooltip"===g?(d=[...k,Va({mainAxis:"number"===typeof d?d:0,crossAxis:"number"===typeof e?e:0})],"auto"===a||"auto-start"===a||"auto-end"===a?d.push(Wa({alignment:"auto-start"===a?"start":"auto-end"===a?"end":null})):b||d.push(Ba(c?{fallbackPlacements:c}:{})),f&&d.push(Xa({element:f})),d):[]}async function Ca({referenceEl:a,floatingEl:b,
overlayPositioning:c="absolute",placement:d,flipDisabled:e,flipPlacements:f,offsetDistance:g,offsetSkidding:k,includeArrow:h=!1,arrowEl:l,type:m}){if(!a||!b||h&&!l)return null;await Ya;"auto"===d||"auto-start"===d||"auto-end"===d?h=void 0:(h=["left","right"],"rtl"===ja.getElementDir(b)&&h.reverse(),h=d.replace(/leading/gi,h[0]).replace(/trailing/gi,h[1]));d={strategy:c,placement:h,middleware:Sa({placement:d,flipDisabled:e,flipPlacements:f,offsetDistance:g,offsetSkidding:k,arrowEl:l,type:m})};c=new Map;
d={platform:W,...d};a=Za(a,b,{...d,platform:{...d.platform,_c:c}});const {x:p,y:r,placement:t,strategy:n,middlewareData:q}=await a;if(q?.arrow){const {x:w,y:u}=q.arrow;Object.assign(l.style,{left:null!=w?`${w}px`:"",top:null!=u?`${u}px`:""})}a=(l=q?.hide?.referenceHidden?"hidden":null)?"none":null;b.setAttribute("data-placement",t);Object.assign(b.style,{visibility:l,pointerEvents:a,position:n,top:"0",left:"0",transform:`translate(${Math.round(p)}px,${Math.round(r)}px)`})}function Da(a,b,c){c&&b&&
((c.shadowRoot||c).removeEventListener("transitionend",ea),(b=fa.get(a))&&b(),fa.delete(a))}function ea(a){const b=a.target;"opacity"===a.propertyName&&b.classList.contains(Ea.animation)&&(a=ja.closestElementCrossShadowBoundary(b,"[data-placement]"),Fa(a),(a.shadowRoot||a).removeEventListener("transitionend",ea))}function Fa(a){a.style.transform="";a.style.top="0";a.style.left="0"}const Za=async(a,b,c)=>{const {placement:d="bottom",strategy:e="absolute",middleware:f=[],platform:g}=c;c=f.filter(Boolean);
const k=await (null==g.isRTL?void 0:g.isRTL(b));let h=await g.getElementRects({reference:a,floating:b,strategy:e}),{x:l,y:m}=ka(h,d,k),p=d,r={},t=0;for(let n=0;n<c.length;n++){const {name:q,fn:w}=c[n],{x:u,y:x,data:v,reset:A}=await w({x:l,y:m,initialPlacement:d,placement:p,strategy:e,middlewareData:r,rects:h,platform:g,elements:{reference:a,floating:b}});l=null!=u?u:l;m=null!=x?x:m;r={...r,[q]:{...r[q],...v}};A&&50>=t&&(t++,"object"===typeof A&&(A.placement&&(p=A.placement),A.rects&&(h=!0===A.rects?
await g.getElementRects({reference:a,floating:b,strategy:e}):A.rects),{x:l,y:m}=ka(h,p,k)),n=-1)}return{x:l,y:m,placement:p,strategy:e,middlewareData:r}},ha=Math.min,ia=Math.max,Xa=a=>({name:"arrow",options:a,async fn(b){const {element:c,padding:d=0}=null!=a?a:{},{x:e,y:f,placement:g,rects:k,platform:h}=b;if(null==c)return{};var l=la(d);b={x:e,y:f};const m=M(g),p=Z(m),r=await h.getDimensions(c),t="y"===m?"top":"left",n="y"===m?"bottom":"right";var q=k.reference[p]+k.reference[m]-b[m]-k.floating[p],
w=b[m]-k.reference[m],u=await (null==h.getOffsetParent?void 0:h.getOffsetParent(c));let x=u?"y"===m?u.clientHeight||0:u.clientWidth||0:0;0===x&&(x=k.floating[p]);u=l[t];const v=x-r[p]-l[n];q=x/2-r[p]/2+(q/2-w/2);w=ia(u,ha(q,v));l=null!=J(g)&&q!=w&&0>k.reference[p]/2-(q<u?l[t]:l[n])-r[p]/2;return{[m]:b[m]-(l?q<u?u-q:v-q:0),data:{[m]:w,centerOffset:q-w}}}}),La={left:"right",right:"left",bottom:"top",top:"bottom"},Ma={start:"end",end:"start"},pa=["top","right","bottom","left"],Ga=pa.reduce((a,b)=>a.concat(b,
b+"-start",b+"-end"),[]),Wa=function(a){void 0===a&&(a={});return{name:"autoPlacement",options:a,async fn(b){var c,d,e,f,g;const {x:k,y:h,rects:l,middlewareData:m,placement:p,platform:r,elements:t}=b,{alignment:n,allowedPlacements:q=Ga,autoAlignment:w=!0,...u}=a,x=void 0!==n||q===Ga?Na(n||null,w,q):q;var v=await O(b,u);b=null!=(c=null==(d=m.autoPlacement)?void 0:d.index)?c:0;d=x[b];if(null==d)return{};const {main:A,cross:X}=ma(d,l,await (null==r.isRTL?void 0:r.isRTL(t.floating)));if(p!==d)return{x:k,
y:h,reset:{placement:x[0]}};v=[v[I(d)],v[A],v[X]];c=[...(null!=(e=null==(f=m.autoPlacement)?void 0:f.overflows)?e:[]),{placement:d,overflows:v}];if(e=x[b+1])return{data:{index:b+1,overflows:c},reset:{placement:e}};e=c.slice().sort((y,C)=>y.overflows[0]-C.overflows[0]);f=null==(g=e.find(y=>{({overflows:y}=y);return y.every(C=>0>=C)}))?void 0:g.placement;g=null!=f?f:e[0].placement;return g!==p?{data:{index:b+1,overflows:c},reset:{placement:g}}:{}}}},Ba=function(a){void 0===a&&(a={});return{name:"flip",
options:a,async fn(b){var c;const {placement:d,middlewareData:e,rects:f,initialPlacement:g,platform:k,elements:h}=b,{mainAxis:l=!0,crossAxis:m=!0,fallbackPlacements:p,fallbackStrategy:r="bestFit",flipAlignment:t=!0,...n}=a,q=I(d);var w=p||(q!==g&&t?Oa(g):[S(g)]);w=[g,...w];const u=await O(b,n),x=[];b=(null==(c=e.flip)?void 0:c.overflows)||[];l&&x.push(u[q]);if(m){const {main:y,cross:C}=ma(d,f,await (null==k.isRTL?void 0:k.isRTL(h.floating)));x.push(u[y],u[C])}b=[...b,{placement:d,overflows:x}];if(!x.every(y=>
0>=y)){var v,A;c=(null!=(v=null==(A=e.flip)?void 0:A.index)?v:0)+1;if(v=w[c])return{data:{index:c,overflows:b},reset:{placement:v}};v="bottom";switch(r){case "bestFit":var X;(b=null==(X=b.map(y=>[y,y.overflows.filter(C=>0<C).reduce((C,$a)=>C+$a,0)]).sort((y,C)=>y[1]-C[1])[0])?void 0:X[0].placement)&&(v=b);break;case "initialPlacement":v=g}if(d!==v)return{reset:{placement:v}}}return{}}}},Ua=function(a){void 0===a&&(a={});return{name:"hide",options:a,async fn(b){const {strategy:c="referenceHidden",
...d}=a;var {rects:e}=b;switch(c){case "referenceHidden":return b=await O(b,{...d,elementContext:"reference"}),e=na(b,e.reference),{data:{referenceHiddenOffsets:e,referenceHidden:oa(e)}};case "escaped":return b=await O(b,{...d,altBoundary:!0}),e=na(b,e.floating),{data:{escapedOffsets:e,escaped:oa(e)}};default:return{}}}}},Va=function(a){void 0===a&&(a=0);return{name:"offset",options:a,async fn(b){const {x:c,y:d}=b;b=await Pa(b,a);return{x:c+b.x,y:d+b.y,data:b}}}},Ta=function(a){void 0===a&&(a={});
return{name:"shift",options:a,async fn(b){const {x:c,y:d,placement:e}=b,{mainAxis:f=!0,crossAxis:g=!1,limiter:k={fn:n=>{let {x:q,y:w}=n;return{x:q,y:w}}},...h}=a;var l={x:c,y:d};const m=await O(b,h),p=M(I(e)),r="x"===p?"y":"x";let t=l[p];l=l[r];f&&(t=ia(t+m["y"===p?"top":"left"],ha(t,t-m["y"===p?"bottom":"right"])));g&&(l=ia(l+m["y"===r?"top":"left"],ha(l,l-m["y"===r?"bottom":"right"])));b=k.fn({...b,[p]:t,[r]:l});return{...b,data:{x:b.x-c,y:b.y-d}}}}};let ba;const Ha=Math.min,R=Math.max,U=Math.round,
va={x:1,y:1},W={getClippingRect:function(a){let {element:b,boundary:c,rootBoundary:d,strategy:e}=a;a=[...("clippingAncestors"===c?Qa(b,this._c):[].concat(c)),d];a=a.reduce((f,g)=>{g=Aa(b,g,e);f.top=R(g.top,f.top);f.right=Ha(g.right,f.right);f.bottom=Ha(g.bottom,f.bottom);f.left=R(g.left,f.left);return f},Aa(b,a[0],e));return{width:a.right-a.left,height:a.bottom-a.top,x:a.left,y:a.top}},convertOffsetParentRelativeRectToViewportRelativeRect:function(a){let {rect:b,offsetParent:c,strategy:d}=a;var e=
F(c);const f=H(c);if(c===f)return b;a={scrollLeft:0,scrollTop:0};let g={x:1,y:1};var k=0,h=0;if(e||!e&&"fixed"!==d){if("body"!==G(c)||T(f))a=V(c);F(c)&&(e=K(c),g=L(c),k=e.x+c.clientLeft,h=e.y+c.clientTop)}return{width:b.width*g.x,height:b.height*g.y,x:b.x*g.x-a.scrollLeft*g.x+k,y:b.y*g.y-a.scrollTop*g.y+h}},isElement:B,getDimensions:function(a){return ta(a)},getOffsetParent:ya,getDocumentElement:H,getScale:L,async getElementRects(a){let {reference:b,floating:c,strategy:d}=a;a=this.getDimensions;var e=
await (this.getOffsetParent||ya)(c),f=F(e);const g=H(e),k=K(b,!0,"fixed"===d,e);let h={scrollLeft:0,scrollTop:0};var l=0,m=0;if(f||!f&&"fixed"!==d){if("body"!==G(e)||T(g))h=V(e);F(e)?(f=K(e,!0),l=f.x+e.clientLeft,m=f.y+e.clientTop):g&&(l=wa(g))}return{reference:{x:k.left+h.scrollLeft-l,y:k.top+h.scrollTop-m,width:k.width,height:k.height},floating:{x:0,y:0,...(await a(c))}}},getClientRects:a=>Array.from(a.getClientRects()),isRTL:a=>"rtl"===D(a).direction},ab={floatingUINonChromiumPositioningFix:!0,
...globalThis.calciteComponentsConfig},Ya=async function(){function a(){const b=navigator.userAgentData;return b?.brands?b.brands.map(c=>`${c.brand}/${c.version}`).join(" "):navigator.userAgent}if(Ka.Build.isBrowser&&ab.floatingUINonChromiumPositioningFix&&/firefox|safari/i.test(a())){const {getClippingRect:b,getElementRects:c,getOffsetParent:d}=await new Promise((e,f)=>Ja(["./nonChromiumPlatformUtils"],e,f));W.getClippingRect=b;W.getOffsetParent=d;W.getElementRects=c}}(),Ia="top bottom right left top-start top-end bottom-start bottom-end right-start right-end left-start left-end".split(" "),
Ea={animation:"calcite-floating-ui-anim",animationActive:"calcite-floating-ui-anim--active"},bb=Y.debounce(Ca,100,{leading:!0,maxWait:100}),fa=new WeakMap;Y=Math.ceil(Math.hypot(4,4));E.FloatingCSS=Ea;E.connectFloatingUI=function(a,b,c){if(c&&b){Da(a,b,c);var d=a.overlayPositioning;Object.assign(c.style,{visibility:"hidden",pointerEvents:"none",position:d});"absolute"===d&&Fa(c);fa.set(a,Ra(b,c,()=>a.reposition()))}};E.defaultMenuPlacement="bottom-start";E.defaultOffsetDistance=Y;E.disconnectFloatingUI=
Da;E.filterComputedPlacements=function(a,b){const c=a.filter(d=>Ia.includes(d));c.length!==a.length&&console.warn(`${b.tagName}: Invalid value found in: flipPlacements. Try any of these: ${Ia.map(d=>`"${d}"`).join(", ").trim()}`,{el:b});return c};E.rectToClientRect=N;E.reposition=async function(a,b,c=!1){if(a.open)return c?bb(b):Ca(b)};E.updateAfterClose=function(a){a&&"absolute"===a.style.position&&(a.shadowRoot||a).addEventListener("transitionend",ea)}});