// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports"],function(D){D.webglDebugExports={};(function(E){(function(u){u=u();void 0!==u&&(E.exports=u)})(function(){function u(a){if(null==y){y={};F={};for(var e in a)"number"==typeof a[e]&&(y[a[e]]=e,F[e]=a[e])}}function K(){if(null==y)throw"WebGLDebugUtils.init(ctx) not called";}function A(a){K();var e=y[a];return void 0!==e?"gl."+e:"/*UNKNOWN WebGL ENUM*/ 0x"+a.toString(16)}function G(a,e,g,d){a=O[a];if(void 0!==a&&(a=a[e],void 0!==a&&a[g])){if("object"===typeof a[g]&&void 0!==a[g].enumBitwiseOr){e=
a[g].enumBitwiseOr;g=0;a=[];for(var p=0;p<e.length;++p){var q=F[e[p]];0!==(d&q)&&(g|=q,a.push(A(q)))}return g===d?a.join(" | "):A(d)}return A(d)}return null===d?"null":void 0===d?"undefined":d.toString()}function L(a,e,g){a.__defineGetter__(g,function(){return e[g]});a.__defineSetter__(g,function(d){e[g]=d})}function M(a,e,g,d){function p(n,f){return function(){g&&g(f,arguments);var v=n[f].apply(n,arguments),k=d.getError();0!=k&&(q[k]=!0,e(k,f,arguments));return v}}d=d||a;u(a);e=e||function(n,f,v){for(var k=
"",z=v.length,t=0;t<z;++t)k+=(0==t?"":", ")+G(f,z,t,v[t]);n="WebGL error "+A(n)+" in "+f+"("+k+")";window.console&&window.console.error?window.console.error(n):window.console&&window.console.log&&window.console.log(n)};var q={},w={},h;for(h in a)if("function"==typeof a[h])if("getExtension"!=h)w[h]=p(a,h);else{var C=p(a,h);w[h]=function(){var n=C.apply(a,arguments);return M(n,e,g,d)}}else L(w,a,h);w.getError=function(){for(var n in q)if(q.hasOwnProperty(n)&&q[n])return q[n]=!1,n;return a.NO_ERROR};
return w}function N(a){var e=a.getParameter(a.MAX_VERTEX_ATTRIBS),g=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,g);for(var d=0;d<e;++d)a.disableVertexAttribArray(d),a.vertexAttribPointer(d,4,a.FLOAT,!1,0,0),a.vertexAttrib1f(d,0);a.deleteBuffer(g);e=a.getParameter(a.MAX_TEXTURE_IMAGE_UNITS);for(d=0;d<e;++d)a.activeTexture(a.TEXTURE0+d),a.bindTexture(a.TEXTURE_CUBE_MAP,null),a.bindTexture(a.TEXTURE_2D,null);a.activeTexture(a.TEXTURE0);a.useProgram(null);a.bindBuffer(a.ARRAY_BUFFER,null);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,
null);a.bindFramebuffer(a.FRAMEBUFFER,null);a.bindRenderbuffer(a.RENDERBUFFER,null);a.disable(a.BLEND);a.disable(a.CULL_FACE);a.disable(a.DEPTH_TEST);a.disable(a.DITHER);a.disable(a.SCISSOR_TEST);a.blendColor(0,0,0,0);a.blendEquation(a.FUNC_ADD);a.blendFunc(a.ONE,a.ZERO);a.clearColor(0,0,0,0);a.clearDepth(1);a.clearStencil(-1);a.colorMask(!0,!0,!0,!0);a.cullFace(a.BACK);a.depthFunc(a.LESS);a.depthMask(!0);a.depthRange(0,1);a.frontFace(a.CCW);a.hint(a.GENERATE_MIPMAP_HINT,a.DONT_CARE);a.lineWidth(1);
a.pixelStorei(a.PACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);a.UNPACK_COLORSPACE_CONVERSION_WEBGL&&a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,a.BROWSER_DEFAULT_WEBGL);a.polygonOffset(0,0);a.sampleCoverage(1,!1);a.scissor(0,0,a.canvas.width,a.canvas.height);a.stencilFunc(a.ALWAYS,0,4294967295);a.stencilMask(4294967295);a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.viewport(0,0,a.canvas.width,a.canvas.height);
for(a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT|a.STENCIL_BUFFER_BIT);a.getError(););}var O={enable:{1:{0:!0}},disable:{1:{0:!0}},getParameter:{1:{0:!0}},drawArrays:{3:{0:!0}},drawElements:{4:{0:!0,2:!0}},createShader:{1:{0:!0}},getShaderParameter:{2:{1:!0}},getProgramParameter:{2:{1:!0}},getShaderPrecisionFormat:{2:{0:!0,1:!0}},getVertexAttrib:{2:{1:!0}},vertexAttribPointer:{6:{2:!0}},bindTexture:{2:{0:!0}},activeTexture:{1:{0:!0}},getTexParameter:{2:{0:!0,1:!0}},texParameterf:{3:{0:!0,1:!0}},
texParameteri:{3:{0:!0,1:!0,2:!0}},texImage2D:{9:{0:!0,2:!0,6:!0,7:!0},6:{0:!0,2:!0,3:!0,4:!0}},texSubImage2D:{9:{0:!0,6:!0,7:!0},7:{0:!0,4:!0,5:!0}},copyTexImage2D:{8:{0:!0,2:!0}},copyTexSubImage2D:{8:{0:!0}},generateMipmap:{1:{0:!0}},compressedTexImage2D:{7:{0:!0,2:!0}},compressedTexSubImage2D:{8:{0:!0,6:!0}},bindBuffer:{2:{0:!0}},bufferData:{3:{0:!0,2:!0}},bufferSubData:{3:{0:!0}},getBufferParameter:{2:{0:!0,1:!0}},pixelStorei:{2:{0:!0,1:!0}},readPixels:{7:{4:!0,5:!0}},bindRenderbuffer:{2:{0:!0}},
bindFramebuffer:{2:{0:!0}},checkFramebufferStatus:{1:{0:!0}},framebufferRenderbuffer:{4:{0:!0,1:!0,2:!0}},framebufferTexture2D:{5:{0:!0,1:!0,2:!0}},getFramebufferAttachmentParameter:{3:{0:!0,1:!0,2:!0}},getRenderbufferParameter:{2:{0:!0,1:!0}},renderbufferStorage:{4:{0:!0,1:!0}},clear:{1:{0:{enumBitwiseOr:["COLOR_BUFFER_BIT","DEPTH_BUFFER_BIT","STENCIL_BUFFER_BIT"]}}},depthFunc:{1:{0:!0}},blendFunc:{2:{0:!0,1:!0}},blendFuncSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},blendEquation:{1:{0:!0}},blendEquationSeparate:{2:{0:!0,
1:!0}},stencilFunc:{3:{0:!0}},stencilFuncSeparate:{4:{0:!0,1:!0}},stencilMaskSeparate:{2:{0:!0}},stencilOp:{3:{0:!0,1:!0,2:!0}},stencilOpSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},cullFace:{1:{0:!0}},frontFace:{1:{0:!0}},drawArraysInstancedANGLE:{4:{0:!0}},drawElementsInstancedANGLE:{5:{0:!0,2:!0}},blendEquationEXT:{1:{0:!0}}},y=null,F=null;return{init:u,mightBeEnum:function(a){K();return void 0!==y[a]},glEnumToString:A,glFunctionArgToString:G,glFunctionArgsToString:function(a,e){for(var g="",d=e.length,
p=0;p<d;++p)g+=(0==p?"":", ")+G(a,d,p,e[p]);return g},makeDebugContext:M,makeLostContextSimulatingCanvas:function(a){function e(c){return"function"==typeof c?c:function(b){c.handleEvent(b)}}function g(){for(var c=Object.keys(x),b=0;b<c.length;++b)delete x[c]}function d(){++B;k||t==B&&a.loseContext()}function p(c,b){var l=c[b];return function(){d();if(!k)return l.apply(c,arguments)}}function q(c){return{statusMessage:c,preventDefault:function(){H=!0}}}function w(c){for(var b in c)"function"==typeof c[b]?
f[b]=p(c,b):L(f,c,b);f.getError=function(){d();if(!k)for(var m;m=h.getError();)x[m]=!0;for(m in x)if(x[m])return delete x[m],m;return f.NO_ERROR};var l="createBuffer createFramebuffer createProgram createRenderbuffer createShader createTexture".split(" ");for(b=0;b<l.length;++b){var r=l[b];f[r]=function(m){return function(){d();if(k)return null;var I=m.apply(c,arguments);I.__webglDebugContextLostId__=v;z.push(I);return I}}(c[r])}l="getActiveAttrib getActiveUniform getBufferParameter getContextAttributes getAttachedShaders getFramebufferAttachmentParameter getParameter getProgramParameter getProgramInfoLog getRenderbufferParameter getShaderParameter getShaderInfoLog getShaderSource getTexParameter getUniform getUniformLocation getVertexAttrib".split(" ");
for(b=0;b<l.length;++b)r=l[b],f[r]=function(m){return function(){d();return k?null:m.apply(c,arguments)}}(f[r]);l="isBuffer isEnabled isFramebuffer isProgram isRenderbuffer isShader isTexture".split(" ");for(b=0;b<l.length;++b)r=l[b],f[r]=function(m){return function(){d();return k?!1:m.apply(c,arguments)}}(f[r]);f.checkFramebufferStatus=function(m){return function(){d();return k?f.FRAMEBUFFER_UNSUPPORTED:m.apply(c,arguments)}}(f.checkFramebufferStatus);f.getAttribLocation=function(m){return function(){d();
return k?-1:m.apply(c,arguments)}}(f.getAttribLocation);f.getVertexAttribOffset=function(m){return function(){d();return k?0:m.apply(c,arguments)}}(f.getVertexAttribOffset);f.isContextLost=function(){return k};return f}var h,C=[],n=[];var f={};var v=1,k=!1,z=[],t=0,B=0,H=!1,J=0,x={};a.getContext=function(c){return function(){var b=c.apply(a,arguments);if(b instanceof WebGLRenderingContext){if(b!=h){if(h)throw"got different context";h=b;f=w(h)}return f}return b}}(a.getContext);(function(c){var b=c.addEventListener;
c.addEventListener=function(l,r,m){switch(l){case "webglcontextlost":C.push(e(r));break;case "webglcontextrestored":n.push(e(r));break;default:b.apply(c,arguments)}}})(a);a.loseContext=function(){if(!k){k=!0;t=0;for(++v;h.getError(););g();x[h.CONTEXT_LOST_WEBGL]=!0;var c=q("context lost"),b=C.slice();setTimeout(function(){for(var l=0;l<b.length;++l)b[l](c);0<=J&&setTimeout(function(){a.restoreContext()},J)},0)}};a.restoreContext=function(){k&&n.length&&setTimeout(function(){if(!H)throw"can not restore. webglcontestlost listener did not call event.preventDefault";
for(var c=0;c<z.length;++c){var b=z[c];b instanceof WebGLBuffer?h.deleteBuffer(b):b instanceof WebGLFramebuffer?h.deleteFramebuffer(b):b instanceof WebGLProgram?h.deleteProgram(b):b instanceof WebGLRenderbuffer?h.deleteRenderbuffer(b):b instanceof WebGLShader?h.deleteShader(b):b instanceof WebGLTexture&&h.deleteTexture(b)}N(h);k=!1;B=0;H=!1;c=n.slice();b=q("context restored");for(var l=0;l<c.length;++l)c[l](b)},0)};a.loseContextInNCalls=function(c){if(k)throw"You can not ask a lost contet to be lost";
t=B+c};a.getNumCalls=function(){return B};a.setRestoreTimeout=function(c){J=c};return a},resetToInitialState:N}})})({get exports(){return D.webglDebugExports},set exports(E){D.webglDebugExports=E}})});