// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/maybe ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/rbush ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/OptimizedGeometry ../../../../../layers/graphics/data/StreamFeatureManager ../../../../../layers/graphics/sources/connections/createConnection ./DataTileSource ../support/FeatureSetReaderJSON ../support/UpdateToken".split(" "),
function(l,m,q,T,r,v,U,V,z,A,t,x,B,C,D,E,F){function G(e,d){const c=e.weakClone();if(r.isSome(e.geometry)){const a=t.quantizeX(d,e.geometry.coords[0]);e=t.quantizeY(d,e.geometry.coords[1]);c.geometry=new x([],[a,e])}return c}function H(e){switch(e){case "esriGeometryPoint":return G;default:return(d,c)=>{const a=d.weakClone(),b=new x;d=t.quantizeOptimizedGeometry(b,d.geometry,!1,!1,e,c,!1,!1);a.geometry=d;return a}}}function I(e){switch(e){case "esriGeometryPoint":return d=>r.isSome(d.geometry)?{minX:d.geometry.coords[0],
minY:d.geometry.coords[1],maxX:d.geometry.coords[0],maxY:d.geometry.coords[1]}:{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity};default:return d=>{let c=Infinity,a=Infinity,b=-Infinity,g=-Infinity;r.isSome(d.geometry)&&d.geometry.forEachVertex((k,f)=>{c=Math.min(c,k);a=Math.min(a,f);b=Math.max(b,k);g=Math.max(g,f)});return{minX:c,minY:a,maxX:b,maxY:g}}}}let J=function(){function e(c,a){this.onUpdate=c;this._geometryType=a;this._objectIdToFeature=new Map;this._index=null}var d=e.prototype;
d.add=function(c){this._objectIdToFeature.set(c.objectId,c);this._index=null};d.get=function(c){return this._objectIdToFeature.has(c)?this._objectIdToFeature.get(c):null};d.forEach=function(c){this._objectIdToFeature.forEach(c)};d.search=function(c){if(!this._index){var a=this._features;const b=A.rbush(9,I(this._geometryType));b.load(a);this._index=b}return this._index.search({minX:c.bounds[0],minY:c.bounds[1],maxX:c.bounds[2],maxY:c.bounds[3]})};d.clear=function(){this._index=null;this._objectIdToFeature.clear()};
d.removeById=function(c){const a=this._objectIdToFeature.get(c);return a?(this._objectIdToFeature.delete(c),this._index=null,a):null};d.update=function(c,a){this.onUpdate(c,a)};m._createClass(e,[{key:"_features",get:function(){const c=[];this._objectIdToFeature.forEach(a=>c.push(a));return c}},{key:"size",get:function(){return this._objectIdToFeature.size}}]);return e}();l.StreamSource=function(e){function d(a){var b=e.call(this,a)||this;b.type="stream";b._updateIntervalId=0;b._level=0;b._updateInfo=
{websocket:0,client:0};b._isPaused=!1;b._inUpdate=!1;var {outSR:g}=a;const {geometryType:k,objectIdField:f,timeInfo:h,purgeOptions:w,source:K,spatialReference:L,serviceFilter:M,maxReconnectionAttempts:N,maxReconnectionInterval:O,updateInterval:P,customParameters:Q,enabledEventTypes:R}=a.serviceInfo,y=new J(b._onUpdate.bind(m._assertThisInitialized(b)),k),S=new B.StreamFeatureManager(y,f,h,w);g=C.createConnection(K,L,g,k,M,N,O,Q??{});b._store=y;b._manager=S;b._connection=g;b._quantize=H(k);b._enabledEventTypes=
new Set(R);b._handles=[b._connection.on("data-received",n=>b._onFeature(n)),b._connection.on("message-received",n=>b._onWebSocketMessage(n))];b._initUpdateInterval=()=>{let n=performance.now();b._updateIntervalId=setInterval(()=>{var u=performance.now(),p=u-n;2500<p&&(n=u,u=Math.round(b._updateInfo.client/(p/1E3)),p=Math.round(b._updateInfo.websocket/(p/1E3)),b._updateInfo.client=0,b._updateInfo.websocket=0,b.events.emit("updateRate",{client:u,websocket:p}));a.canAcceptRequest()&&!b._inUpdate&&b._manager.checkForUpdates()},
P)};b._initUpdateInterval();return b}m._inheritsLoose(d,e);var c=d.prototype;c.destroy=function(){e.prototype.destroy.call(this);this._clearUpdateInterval();this._handles.forEach(a=>a.remove());this._connection.destroy()};c._fetchDataTile=function(){};c.updateCustomParameters=function(a){this._connection.updateCustomParameters(a)};c.pauseStream=function(){this._isPaused||(this._isPaused=!0,this._clearUpdateInterval())};c.resumeStream=function(){this._isPaused&&(this._isPaused=!1,this._initUpdateInterval())};
c.sendMessageToSocket=function(a){this._connection.sendMessageToSocket(a)};c.sendMessageToClient=function(a){this._connection.sendMessageToClient(a)};c.enableEvent=function(a,b){b?this._enabledEventTypes.add(a):this._enabledEventTypes.delete(a)};c.subscribe=function(a,b){e.prototype.subscribe.call(this,a,b);b=this._subscriptions.get(a.id);this._level=a.level;const g=this._getTileFeatures(a);this._onMessage({type:"append",id:a.key.id,addOrUpdate:g,end:!0});b.didSend=!0};c.unsubscribe=function(a){e.prototype.unsubscribe.call(this,
a)};c.readers=function*(a){a=this._subscriptions.get(a);({tile:a}=a);yield this._getTileFeatures(a)};c.createTileQuery=function(a){throw Error("Service does not support tile  queries");};c.resend=function(){var a=m._asyncToGenerator(function*(){this._subscriptions.forEach(b=>{({tile:b}=b);b={type:"append",id:b.id,addOrUpdate:this._getTileFeatures(b),end:!0};this._onMessage(b)})});return function(){return a.apply(this,arguments)}}();c._getTileFeatures=function(a){const b=this._store.search(a).map(g=>
this._quantize(g,a.transform));return E.FeatureSetReaderJSON.fromOptimizedFeatures(b,this._serviceInfo,a.transform)};c._onWebSocketMessage=function(a){this._enabledEventTypes.has("message-received")&&this.events.emit("message-received",a);if("type"in a)switch(a.type){case "delete":if(a.objectIds)for(const b of a.objectIds)this._manager.removeById(b);if(a.trackIds)for(const b of a.trackIds)this._manager.removeByTrackId(b);break;case "clear":this._store.forEach(b=>this._manager.removeById(b.objectId))}};
c._onFeature=function(a){this._updateInfo.websocket++;try{this._enabledEventTypes.has("data-received")&&this.events.emit("data-received",a);const b=t.convertFromFeature(a,this._serviceInfo.geometryType,!1,!1,this._serviceInfo.objectIdField);this._manager.add(b)}catch(b){}};c._clearUpdateInterval=function(){clearInterval(this._updateIntervalId);this._updateIntervalId=0};c._onUpdate=function(){var a=m._asyncToGenerator(function*(b,g){this._inUpdate=!0;try{r.isSome(b)&&(this._updateInfo.client+=b.length);
this._subscriptions.forEach((f,h)=>{f.didSend&&f.tile.level===this._level&&this._onMessage({type:"append",id:h,addOrUpdate:null,clear:!0,end:!1})});const k=[];this._subscriptions.forEach((f,h)=>{if(f.didSend&&f.tile.level===this._level){var w=this._getTileFeatures(f.tile);h={type:"append",id:h,addOrUpdate:w,remove:[],end:!1,status:F.UpdateToken.empty()};f.requests.stream.enqueue(h);k.push(this._onMessage(h))}});yield Promise.all(k);this._subscriptions.forEach((f,h)=>{f.didSend&&f.tile.level===this._level&&
this._onMessage({type:"append",id:h,addOrUpdate:null,end:!0})})}catch{}this._inUpdate=!1});return function(b,g){return a.apply(this,arguments)}}();m._createClass(d,[{key:"connectionStatus",get:function(){return this._isPaused?"paused":this._connection?.connectionStatus}},{key:"errorString",get:function(){return this._connection?.errorString}},{key:"updating",get:function(){return!1}}]);return d}(D.DataTileSource);q.__decorate([v.property()],l.StreamSource.prototype,"_isPaused",void 0);q.__decorate([v.property()],
l.StreamSource.prototype,"connectionStatus",null);q.__decorate([v.property()],l.StreamSource.prototype,"errorString",null);l.StreamSource=q.__decorate([z.subclass("esri.views.2d.layers.features.sources")],l.StreamSource);Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});