// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../config ../../kernel ../../request ../../core/asyncUtils ../../core/Error ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/urlUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/reader ../../core/accessorSupport/decorators/subclass ../../core/accessorSupport/decorators/writer ../support/layerUtils ../../portal/Portal ../../portal/PortalItem ../../portal/PortalUser ../../portal/support/portalItemUtils".split(" "),
function(D,x,h,k,E,v,F,G,H,I,q,l,r,p,O,P,J,K,L,M,y,w,N,z){var A=null,B=null;x.PortalLayer=f=>{f=function(t){function u(){var d=t.apply(this,arguments)||this;d.resourceReferences={portalItem:null,paths:[]};d.userHasEditingPrivileges=!0;d.userHasFullEditingPrivileges=!1;d.userHasUpdateItemPrivileges=!1;return d}h._inheritsLoose(u,t);var e=u.prototype;e.destroy=function(){this.portalItem=q.destroyMaybe(this.portalItem)};e.readPortalItem=function(d,a,b){if(a.itemId)return new w({id:a.itemId,portal:b&&
b.portal})};e.writePortalItem=function(d,a){d&&d.id&&(a.itemId=d.id)};e.loadFromPortal=function(){var d=h._asyncToGenerator(function*(a,b){if(this.portalItem&&this.portalItem.id)try{const c=yield new Promise((m,g)=>D(["../../portal/support/layersLoader"],m,g));l.throwIfAborted(b);return yield c.load({instance:this,supportedTypes:a.supportedTypes,validateItem:a.validateItem,supportsData:a.supportsData,layerModuleTypeMap:a.layerModuleTypeMap},b)}catch(c){throw l.isAbortError(c)||I.getLogger(this.declaredClass).warn(`Failed to load layer (${this.title}, ${this.id}) portal item (${this.portalItem.id})\n  ${c}`),
c;}});return function(a,b){return d.apply(this,arguments)}}();e.finishLoadEditablePortalLayer=function(){var d=h._asyncToGenerator(function*(a){this._set("userHasEditingPrivileges",yield this._fetchUserHasEditingPrivileges(a).catch(b=>{l.throwIfAbortError(b);return!0}))});return function(a){return d.apply(this,arguments)}}();e._setUserPrivileges=function(){var d=h._asyncToGenerator(function*(a,b){if(!E.userPrivilegesApplied)return this.finishLoadEditablePortalLayer(b);if(this.url)try{const {features:{edit:c,
fullEdit:m},content:{updateItem:g}}=yield this._fetchUserPrivileges(a,b);this._set("userHasEditingPrivileges",c);this._set("userHasFullEditingPrivileges",m);this._set("userHasUpdateItemPrivileges",g)}catch(c){l.throwIfAbortError(c)}});return function(a,b){return d.apply(this,arguments)}}();e._fetchUserPrivileges=function(){var d=h._asyncToGenerator(function*(a,b){let c=this.portalItem;if(!a||!c||!c.loaded||c.sourceUrl)return this._fetchFallbackUserPrivileges(b);const m=a===c.id;if(m&&c.portal.user)return z.getUserPrivileges(c);
let g;if(m)g=c.portal.url;else try{g=yield M.getOwningPortalUrl(this.url,b)}catch(n){l.throwIfAbortError(n)}if(!g||!r.hasSameCanonicalPortal(g,c.portal.url))return this._fetchFallbackUserPrivileges(b);let C;try{const n=q.isSome(b)?b.signal:null;C=yield v.id?.getCredential(`${g}/sharing`,{prompt:!1,signal:n})}catch(n){l.throwIfAbortError(n)}if(!C)return{features:{edit:!0,fullEdit:!1},content:{updateItem:!1}};try{if(m?yield c.reload():(c=new w({id:a,portal:{url:g}}),yield c.load(b)),c.portal.user)return z.getUserPrivileges(c)}catch(n){l.throwIfAbortError(n)}return{features:{edit:!0,
fullEdit:!1},content:{updateItem:!1}}});return function(a,b){return d.apply(this,arguments)}}();e._fetchFallbackUserPrivileges=function(){var d=h._asyncToGenerator(function*(a){let b=!0;try{b=yield this._fetchUserHasEditingPrivileges(a)}catch(c){l.throwIfAbortError(c)}return{features:{edit:b,fullEdit:!1},content:{updateItem:!1}}});return function(a){return d.apply(this,arguments)}}();e._fetchUserHasEditingPrivileges=function(){var d=h._asyncToGenerator(function*(a){const b=this.url?v.id?.findCredential(this.url):
null;if(!b)return!0;a=A===b?B:yield this._fetchEditingUser(a);A=b;B=a;return q.isNone(a)||null==a.privileges||a.privileges.includes("features:user:edit")});return function(a){return d.apply(this,arguments)}}();e._fetchEditingUser=function(){var d=h._asyncToGenerator(function*(a){var b=this.portalItem?.portal?.user;if(b)return b;b=v.id.findServerInfo(this.url??"");if(!b?.owningSystemUrl)return null;b=`${b.owningSystemUrl}/sharing/rest`;const c=y.getDefault();if(c&&c.loaded&&r.normalize(c.restUrl)===
r.normalize(b))return c.user;b=`${b}/community/self`;a=q.isSome(a)?a.signal:null;a=yield G.result(F(b,{authMode:"no-prompt",query:{f:"json"},signal:a}));return a.ok?N.fromJSON(a.value.data):null});return function(a){return d.apply(this,arguments)}}();e.read=function(d,a){a&&(a.layer=this);t.prototype.read.call(this,d,a)};e.write=function(d,a){const b=a&&a.portal,c=this.portalItem&&this.portalItem.id&&(this.portalItem.portal||y.getDefault());return b&&c&&!r.hasSamePortal(c.restUrl,b.restUrl)?(a.messages&&
a.messages.push(new H("layer:cross-portal",`The layer '${this.title} (${this.id})' cannot be persisted because it refers to an item on a different portal than the one being saved to. To save, set layer.portalItem to null or save to the same portal as the item associated with the layer`,{layer:this})),null):t.prototype.write.call(this,d,{...a,layer:this})};h._createClass(u,[{key:"portalItem",set:function(d){d!==this._get("portalItem")&&(this.removeOrigin("portal-item"),this._set("portalItem",d))}}]);
return u}(f);k.__decorate([p.property({type:w})],f.prototype,"portalItem",null);k.__decorate([J.reader("web-document","portalItem",["itemId"])],f.prototype,"readPortalItem",null);k.__decorate([L.writer("web-document","portalItem",{itemId:{type:String}})],f.prototype,"writePortalItem",null);k.__decorate([p.property({clonable:!1})],f.prototype,"resourceReferences",void 0);k.__decorate([p.property({type:Boolean,readOnly:!0})],f.prototype,"userHasEditingPrivileges",void 0);k.__decorate([p.property({type:Boolean,
readOnly:!0})],f.prototype,"userHasFullEditingPrivileges",void 0);k.__decorate([p.property({type:Boolean,readOnly:!0})],f.prototype,"userHasUpdateItemPrivileges",void 0);return f=k.__decorate([K.subclass("esri.layers.mixins.PortalLayer")],f)};Object.defineProperty(x,Symbol.toStringTag,{value:"Module"})});