// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/HandleOwner ../../core/maybe ../../core/reactiveUtils ../../core/scheduling ../../core/timeUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../views/SceneView ../../views/3d/environment/SunLighting ../../views/3d/environment/VirtualLighting ../../views/3d/support/earthUtils ./support/daylightUtils ./support/SliderWithDropdownViewModel ../support/DatePickerViewModel ../support/timeWidgetUtils".split(" "),
function(t,d,c,f,l,y,p,e,F,G,z,A,u,B,C,m,v,w,r){c=function(x){function q(a){a=x.call(this,a)||this;a.view=null;a.datePickerViewModel=new w;a.timeSliderViewModel=new v.SliderWithDropdownViewModel({min:0,max:1439,values:[0],labelFormatFunction:r.formatSliderLabel,inputFormatFunction:r.formatSliderLabel});a.lightingUpdateInterval=200;a._oldLighting=null;a.playSpeedMultiplier=1;a._lastTime=null;a._sunrise=null;a._sunset=null;a._cachedLightingDateUTC=new Date(0);a._cachedDisplayUTCOffset=0;a._firstInteraction=
!0;a._lastLightingUpdate=0;a._nextLightingUpdate=null;return a}t._inheritsLoose(q,x);var k=q.prototype;k.initialize=function(){this.handles.add([l.when(()=>this.view,a=>a.when(()=>this._updateLighting(null)),l.initial),l.watch(()=>f.applySome(this._lighting,a=>"virtual"!==a.type?a.date:null),a=>this._scheduleUpdateLighting(a)),l.on(()=>this._lighting,"timezone-will-change",a=>this._timezoneWillChange(a),{onListenerAdd:()=>this._timezoneWillChange(null)}),l.watch(()=>!0===f.applySome(this.view,a=>
a.stationary),()=>{(this.dayPlaying||this.yearPlaying)&&this._updateSunriseAndSunset()},l.initial),l.watch(()=>{const a=this.timeSliderViewModel;return{vm:a,state:a.state,sliderPosition:this.timeSliderPosition}},({vm:a,state:b,sliderPosition:g})=>{"ready"===b&&a.setValue(0,g)}),l.watch(()=>this.timeSliderViewModel.currentItem?.utcOffset,a=>this.utcOffset=a),l.watch(()=>this.timeSliderViewModel.isDropdownOpen,()=>this.stopPlaying()),l.watch(()=>this.timeSliderViewModel.values,a=>this.timeSliderPosition=
a?.[0]??0),l.watch(()=>this.datePickerViewModel.value,a=>{this.dayPlaying=!1;this.localDate=a}),l.watch(()=>this.localDate,a=>{this.datePickerViewModel.value.valueOf()!==a.getTime()&&this.datePickerViewModel.set("value",a)})])};k.destroy=function(){this._nextLightingUpdate&&(clearTimeout(this._nextLightingUpdate),this._nextLightingUpdate=null);this.view=null};k._timezoneFromCamera=function(a,b){if(f.isNone(b)||!a.cameraTrackingEnabled)return 0;a=C.positionToTimezoneInfo([b.longitude,b.latitude]);
return f.isNone(a)?0:Math.round(a.hours+a.minutes/60+a.seconds/3600)};k.stopPlaying=function(){this.playingState="none"};k.toggleDayPlaying=function(){this.dayPlaying=!this.dayPlaying};k.toggleYearPlaying=function(){this.yearPlaying=!this.yearPlaying};k.toggleSunLightingEnabled=function(){this.stopPlaying();this.sunLightingEnabled=!this.sunLightingEnabled};k.toggleDirectShadowsEnabled=function(){this.stopPlaying();this.directShadowsEnabled=!this.directShadowsEnabled};k._enableDirectShadowsIfFirstInteraction=
function(){this._firstInteraction&&(this._firstInteraction=!1,this.directShadowsEnabled=!0)};k._updateLighting=function(a){this._lastLightingUpdate=Date.now();var {view:b}=this;const g=this._lighting;if(!f.isNone(b)&&!f.isNone(g)&&"virtual"!==g.type){a=a||g.date;var h=g.displayUTCOffset;b=null!==h?h:this._timezoneFromCamera(g,b.camera?.position);this._cachedLightingDateUTC.getTime()!==a.getTime()&&(this._cachedLightingDateUTC=new Date(a.getTime()));this._cachedDisplayUTCOffset!==b&&(this._cachedDisplayUTCOffset=
b)}};k._timezoneWillChange=function(a){const b=this._lighting;if(!f.isNone(b)&&"virtual"!==b.type&&b.cameraTrackingEnabled){if(a)a=a.timezoneOffset;else{if(null!=b.displayUTCOffset)return;a=u.calculateTimezoneOffset(b.positionTimezoneInfo)}b.displayUTCOffset=a;this._scheduleUpdateLighting(null)}};k._scheduleUpdateLighting=function(a){if(!this._nextLightingUpdate&&!f.isNone(a)){var b=Date.now()-this._lastLightingUpdate;b=this.lightingUpdateInterval-b;0>=b?y.schedule(()=>this._updateLighting(a)):this._nextLightingUpdate=
setTimeout(()=>{this._updateLighting(null);this._nextLightingUpdate=null},b)}};k._play=function(){const a=this._lighting;if(!f.isNone(a)&&this.sunLightingEnabled&&"virtual"!==a.type&&(this.dayPlaying||this.yearPlaying)){var b=Date.now()-(this._lastTime??0);if(this.dayPlaying){if(this._lastTime=Date.now(),b*=m.calculatePlaySpeed(this._sunrise,this._sunset,a.date)*this.playSpeedMultiplier/100,0<b){var g=new Date(a.date.getTime()+b),h=a.displayUTCOffset??0;const n=((g.getUTCHours()+h)%24+24)%24;h=((a.date.getUTCHours()+
h)%24+24)%24;n<h&&(g=new Date(a.date.getTime()+b-864E5));a.date=g}}else 1E3<b&&(this._lastTime=Date.now(),b=(a.date.getUTCMonth()+1)%12,g=new Date(a.date.getTime()),g.setUTCMonth(b),a.date=g);requestAnimationFrame(()=>this._play())}};k._updateSunriseAndSunset=function(){var a=this._lighting;if(!f.isNone(a)&&"virtual"!==a.type&&this.sunLightingEnabled){var b=f.applySome(this.view,D=>D.camera?.position);if(!f.isNone(b)){var {latitude:g,longitude:h}=b,{date:n,displayUTCOffset:E}=a;if(a=r.getSunriseAndSunsetTimes(n,
g,h,E))this._sunrise=new Date(a.sunrise),this._sunset=new Date(a.sunset)}}};t._createClass(q,[{key:"isSupported",get:function(){return f.isNone(this.view)||"3d"===this.view.type}},{key:"utcOffset",get:function(){return this._cachedDisplayUTCOffset},set:function(a){a!==this.utcOffset&&f.isSome(this._lighting)&&"virtual"!==this._lighting.type&&(this._lighting.displayUTCOffset=a,this._updateLighting(null))}},{key:"localDate",get:function(){return p.truncateLocalTime(this._lightingDateDisplay)},set:function(a){a.getTime()!==
this.localDate.getTime()&&(this._lightingDateDisplay=p.resetUTCDate(this._lightingDateDisplay,a))}},{key:"timeSliderPosition",get:function(){return m.dateTimeToSliderPos(this._lightingDateDisplay)},set:function(a){Math.abs(a-this.timeSliderPosition)>1/60&&(this._lightingDateDisplay=m.sliderPosToDateTime(this._lightingDateDisplay,a),this.stopPlaying(),this._enableDirectShadowsIfFirstInteraction())}},{key:"directShadowsEnabled",get:function(){const a=f.applySome(this._lighting,b=>b.directShadowsEnabled);
return f.unwrapOr(a,!1)},set:function(a){f.applySome(this._lighting,b=>{b.directShadowsEnabled=a})}},{key:"sunLightingEnabled",get:function(){return"sun"===this._lightingType},set:function(a){const b=this._environment;if(a!==this._get("sunLightingEnabled")&&!f.isNone(b)){var g=b.lighting,h=this._oldLighting;this._oldLighting=g;g={directShadowsEnabled:g.directShadowsEnabled,ambientOcclusionEnabled:g.ambientOcclusionEnabled,waterReflectionEnabled:g.waterReflectionEnabled,cameraTrackingEnabled:g.cameraTrackingEnabled};
var n=a?"sun":"virtual";h=f.isSome(h)&&h.type===n?h:a?new u:new B;h.set(g);b.lighting=h;a||(this.timeSliderViewModel.isDropdownOpen=!1)}}},{key:"playingState",set:function(a){this.playingState!==a&&this.sunLightingEnabled&&(this._set("playingState",a),"none"!==a&&(this._updateSunriseAndSunset(),this._lastTime=Date.now(),this._play(),this._enableDirectShadowsIfFirstInteraction()))}},{key:"dayPlaying",get:function(){return"day"===this.playingState},set:function(a){a?this.playingState="day":this.dayPlaying&&
(this.playingState="none")}},{key:"yearPlaying",get:function(){return"year"===this.playingState},set:function(a){a?this.playingState="year":this.yearPlaying&&(this.playingState="none")}},{key:"currentSeason",get:function(){return m.getSeasonFromDate(this.localDate,this._currentHemisphere)},set:function(a){this.stopPlaying();a=m.getNorthernHemisphereSeason(a,this._currentHemisphere);this.localDate=m.getSeasonDate(this.localDate,a,m.Hemisphere.NORTHERN)}},{key:"_currentHemisphere",get:function(){const a=
f.applySome(this.view,b=>b.camera?.position?.latitude);return f.isNone(a)||0<=a?m.Hemisphere.NORTHERN:m.Hemisphere.SOUTHERN}},{key:"_environment",get:function(){return f.applySome(this.view,a=>a.environment)}},{key:"_lighting",get:function(){return f.applySome(this._environment,a=>a.lighting)}},{key:"_lightingType",get:function(){return f.applySome(this._lighting,a=>a.type)}},{key:"_lightingDateDisplay",get:function(){return p.offsetDate(this._cachedLightingDateUTC,this._cachedDisplayUTCOffset,"hours")},
set:function(a){const b=this._lighting;!f.isNone(b)&&this.sunLightingEnabled&&"virtual"!==b.type&&(a=p.offsetDate(a,-this._cachedDisplayUTCOffset,"hours"),a.getTime()!==b.date.getTime()&&(b.date=a,this._updateLighting(null)))}}]);return q}(c.HandleOwner);d.__decorate([e.property({type:A})],c.prototype,"view",void 0);d.__decorate([e.property({type:w,nonNullable:!0})],c.prototype,"datePickerViewModel",void 0);d.__decorate([e.property({type:v.SliderWithDropdownViewModel,nonNullable:!0})],c.prototype,
"timeSliderViewModel",void 0);d.__decorate([e.property()],c.prototype,"isSupported",null);d.__decorate([e.property()],c.prototype,"lightingUpdateInterval",void 0);d.__decorate([e.property()],c.prototype,"utcOffset",null);d.__decorate([e.property()],c.prototype,"localDate",null);d.__decorate([e.property()],c.prototype,"timeSliderPosition",null);d.__decorate([e.property()],c.prototype,"directShadowsEnabled",null);d.__decorate([e.property()],c.prototype,"sunLightingEnabled",null);d.__decorate([e.property({type:["none",
"day","year"],value:"none"})],c.prototype,"playingState",null);d.__decorate([e.property()],c.prototype,"dayPlaying",null);d.__decorate([e.property()],c.prototype,"yearPlaying",null);d.__decorate([e.property()],c.prototype,"playSpeedMultiplier",void 0);d.__decorate([e.property()],c.prototype,"currentSeason",null);d.__decorate([e.property()],c.prototype,"_lastTime",void 0);d.__decorate([e.property()],c.prototype,"_sunrise",void 0);d.__decorate([e.property()],c.prototype,"_sunset",void 0);d.__decorate([e.property()],
c.prototype,"_cachedLightingDateUTC",void 0);d.__decorate([e.property()],c.prototype,"_cachedDisplayUTCOffset",void 0);d.__decorate([e.property()],c.prototype,"_firstInteraction",void 0);d.__decorate([e.property()],c.prototype,"_currentHemisphere",null);d.__decorate([e.property()],c.prototype,"_environment",null);d.__decorate([e.property()],c.prototype,"_lighting",null);d.__decorate([e.property()],c.prototype,"_lightingType",null);d.__decorate([e.property()],c.prototype,"_lightingDateDisplay",null);
return c=d.__decorate([z.subclass("esri.widgets.Daylight.DaylightViewModel")],c)});