// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../geometry ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/memoize ../../../../../core/reactiveUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../../../../../core/support/WatchUpdatingTracking ../../../../../layers/graphics/hydratedFeatures ../../../analysis/support/measurementUtils ../../SnappingVisualizer3D ../../editingTools/dragEventPipeline3D ./DirectLineMeasurement3DView ../../../support/ElevationProvider ../../../../interactive/AnalysisToolBase ../../../../interactive/coordinateHelper ../../../../interactive/dragEventPipeline ../../../../interactive/editGeometry/EditGeometry ../../../../interactive/editGeometry/EditGeometryOperations ../../../../interactive/snapping/SceneSnappingManagerPool ../../../../interactive/snapping/SnappingContext ../../../../interactive/snapping/SnappingDragPipelineStep ../../../../interactive/snapping/snappingUtils ../../../../support/screenUtils ../../../../../geometry/Point".split(" "),
function(D,d,c,K,e,L,E,f,ia,ja,M,N,O,P,Q,z,R,S,T,U,F,V,W,X,Y,Z,aa,G,ba){function A(q,r,g){q.events.emit("drag",{action:"start",pointerType:r,start:g,screenPoint:g});return{update:a=>q.events.emit("drag",{action:"update",start:a,screenPoint:a}),end:a=>q.events.emit("drag",{action:"end",start:a,screenPoint:a}),cancel:()=>q.events.emit("drag",{action:"cancel"})}}c=function(q){function r(a){var b=q.call(this,a)||this;b._handles=new K;b._updatingHandles=new N.WatchUpdatingTracking;b._emulatedDrag=null;
b.lineState="initial";b.startPointSurfaceLocation=null;b.endPointSurfaceLocation=null;b.cursorPointSurfaceLocation=null;b.startManipulator=null;b.endManipulator=null;b.cursorManipulator=null;b._getSnappingContext=L.memoize(m=>new Y.SnappingContext({elevationInfo:{mode:"absolute-height",offset:0},pointer:m,editGeometryOperations:new W.EditGeometryOperations(new V.EditGeometry("point",U.createCoordinateHelper(!0,!1,b.view.spatialReference))),visualizer:new Q.SnappingVisualizer3D}));return b}D._inheritsLoose(r,
q);var g=r.prototype;g.initialize=function(){const {view:a,analysis:b,analysisViewData:m,visible:t}=this;this.measurementView=new R.DirectLineMeasurement3DView({toolState:this,view:a,analysis:b,analysisViewData:m,visible:t});var k=X.acquire(a);this._snappingManagerResult=k;this._handles.add(k);const {start:n,end:l,cursor:p}=this.measurementView.createManipulators();k=(u,x,B)=>F.createManipulatorDragEventPipeline(u,(C,v,y,H)=>{const I=z.hideManipulatorWhileDragging(C),ca=this._snappingManager,da=this._getSnappingContext(H),
ea=this._updatingHandles,{lineState:fa}=this;y=y.next(I).next(F.resetProperties(this,[B,x])).next(h=>{C.location=e.unwrap(this.analysis[x]);return h});const ha=z.screenToMap3D(this.view);v=v.next(I).next(h=>{h=ha(h);h||"drawing"!==this.lineState&&"initial"!==this.lineState||(this[x]=null,this[B]=null);return h});if("touch"!==H||"editing"===fa){const {snappingStep:h,cancelSnapping:w}=Z.createSnapDragEventPipelineStep({snappingManager:ca,snappingContext:da,updatingHandles:ea});y=y.next(w);v=v.next(...h)}v.next(h=>
"start"!==h.action?h:null).next(h=>{const w=O.clonePoint(h.mapEnd,new ba);this[x]=w;C.location=w;this[B]=this._surfaceLocation(w,h.surfaceType)})});const J=u=>u.events.on("grab-changed",()=>{this.lineState=n.grabbing||l.grabbing?"editing":"measured"});this._handles.add([k(n,"startPoint","startPointSurfaceLocation"),k(l,"endPoint","endPointSurfaceLocation"),k(p,"cursorPoint","cursorPointSurfaceLocation"),J(n),J(l)]);this.manipulators.add(n);this.manipulators.add(l);this.manipulators.add(p);this.startManipulator=
n;this.endManipulator=l;this.cursorManipulator=p;this._handles.add(E.watch(()=>this.state,u=>{"measured"===u&&this.finishToolCreation()},E.syncAndInitial));aa.setupSnappingToggleHandles(this)};g.destroy=function(){this._handles=e.destroyMaybe(this._handles);this._updatingHandles=e.destroyMaybe(this._updatingHandles);this.measurementView=e.destroyMaybe(this.measurementView)};g.onShow=function(){this.measurementView.show();this._updateManipulatorAvailability()};g.onHide=function(){this.measurementView.hide()};
g.onDeactivate=function(){this._emulatedDrag?.cancel();this._emulatedDrag=null};g.onInputEvent=function(a){switch(a.type){case "immediate-click":this._handleImmediateClick(a);break;case "pointer-move":this._handlePointerMove(a)}this._updateManipulatorAvailability()};g._handlePointerMove=function(a){if(this.active&&!this.view.navigating){var {pointerType:b}=a;if("mouse"===b){var m=G.createScreenPointFromEvent(a),{lineState:t,cursorManipulator:k,endManipulator:n}=this,l=!1;e.isNone(this.cursorPoint)&&
(this._emulatedDrag?.cancel(),this._emulatedDrag=A(k,b,m),l=!0);"initial"===t&&(this._emulatedDrag?.update(m),l=!0);"drawing"===t&&(n.events.emit("drag",{action:"update",start:m,screenPoint:m}),l=!0);l&&a.stopPropagation()}}};g._handleImmediateClick=function(a){if(this.active&&P.isPrimaryPointerAction(a)){var b=G.createScreenPointFromEvent(a),{pointerType:m}=a,{cursorManipulator:t,startManipulator:k,endManipulator:n,lineState:l}=this,p=!1;e.isNone(this.cursorPoint)&&(this._emulatedDrag?.cancel(),
this._emulatedDrag=A(t,m,b));switch(l){case "initial":this._emulatedDrag?.update(b);e.isSome(this.cursorPoint)&&(this._emulatedDrag?.end(b),this._emulatedDrag=null,{cursorPoint:p}=this,this.startPoint=p,this.startPointSurfaceLocation=this.cursorPointSurfaceLocation,k.location=p,k.interactive=!1,n.interactive=!1,this.lineState="drawing",this._emulatedDrag=A(n,m,b),p=!0);break;case "drawing":this._emulatedDrag?.update(b),e.isSome(this.endPoint)&&(this._emulatedDrag?.end(b),this._emulatedDrag=null,k.interactive=
!0,n.interactive=!0,this.lineState="measured",p=!0)}p&&a.stopPropagation()}};g._surfaceLocation=function(a,b){return b===z.SurfaceType.GROUND?"on-the-surface":(a.z??0)>=this._getElevation(a)?"above-the-surface":"below-the-surface"};g._updateManipulatorAvailability=function(){this.startManipulator.available=e.isSome(this.analysis.startPoint);this.endManipulator.available=e.isSome(this.analysis.endPoint)};g._getElevation=function(a){return this.view.basemapTerrain.ready?e.unwrapOr(S.getElevationAtPoint(this.view.elevationProvider,
a),0):0};D._createClass(r,[{key:"_snappingManager",get:function(){return this._snappingManagerResult.snappingManager}},{key:"state",get:function(){var {analysis:a}=this;if(e.isNone(a.startPoint)&&e.isNone(a.endPoint))return"ready";({lineState:a}=this);return this.validMeasurement&&"editing"!==a&&"drawing"!==a?"measured":"measuring"}},{key:"cursor",get:function(){const {lineState:a}=this;return"initial"===a||"drawing"===a?"crosshair":null}},{key:"startPoint",get:function(){return this.analysis.startPoint},
set:function(a){this.analysis.startPoint=a}},{key:"endPoint",get:function(){return this.analysis.endPoint},set:function(a){this.analysis.endPoint=a}},{key:"cursorPoint",get:function(){return this.measurementView.cursorPoint},set:function(a){this.measurementView.cursorPoint=a}},{key:"snappingOptions",get:function(){return this._snappingManager.options}},{key:"validMeasurement",get:function(){return e.isSome(this.analysis.startPoint)&&e.isSome(this.analysis.endPoint)}},{key:"updating",get:function(){return this._updatingHandles.updating||
this._snappingManager.updating}},{key:"test",get:function(){return{snappingManager:this._snappingManager}}}]);return r}(T.AnalysisToolBase);d.__decorate([f.property({readOnly:!0})],c.prototype,"state",null);d.__decorate([f.property()],c.prototype,"lineState",void 0);d.__decorate([f.property({readOnly:!0})],c.prototype,"cursor",null);d.__decorate([f.property()],c.prototype,"startPoint",null);d.__decorate([f.property()],c.prototype,"endPoint",null);d.__decorate([f.property()],c.prototype,"cursorPoint",
null);d.__decorate([f.property({constructOnly:!0})],c.prototype,"analysis",void 0);d.__decorate([f.property({constructOnly:!0})],c.prototype,"analysisViewData",void 0);d.__decorate([f.property()],c.prototype,"measurementView",void 0);d.__decorate([f.property({constructOnly:!0})],c.prototype,"view",void 0);d.__decorate([f.property({readOnly:!0})],c.prototype,"validMeasurement",null);d.__decorate([f.property({value:null})],c.prototype,"startPointSurfaceLocation",void 0);d.__decorate([f.property({value:null})],
c.prototype,"endPointSurfaceLocation",void 0);d.__decorate([f.property({value:null})],c.prototype,"cursorPointSurfaceLocation",void 0);d.__decorate([f.property()],c.prototype,"updating",null);return c=d.__decorate([M.subclass("esri.views.3d.interactive.measurementTools.directLineMeasurement3D.DirectLineMeasurement3DTool")],c)});