// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../layers/support/layerUtils ../../views/draw/support/helpMessageUtils ./CreateWorkflowData ./Edits ./Workflow ./workflowUtils".split(" "),function(c,t,A,D,v,l,K,E,B,F,G,H,I,e){var x;l=x=function(C){function u(b){b=C.call(this,b)||this;
b.type="create";return b}c._inheritsLoose(u,C);u.create=function(b,m,a){b=new x({data:new G({edits:new H.Edits,viewModel:b}),onCommit:function(){var k=c._asyncToGenerator(function*(g){yield a(g.creationInfo.layer,{addFeatures:[g.edits.feature]})});return function(g){return k.apply(this,arguments)}}()});b._set("steps",this._createWorkflowSteps(b,m));return b};u._createWorkflowSteps=function(b,m="awaiting-feature-creation-info"){const {data:a,handles:k}=b,g=new Map;b=e.createWorkflowSteps(["awaiting-feature-creation-info",
"awaiting-feature-to-create","editing-new-feature","adding-attachment","editing-attachment"],m,{"awaiting-feature-creation-info":()=>({id:"awaiting-feature-creation-info",setUp(){var f=this;return c._asyncToGenerator(function*(){a.creationInfo=null;a.edits.feature=null;a.viewModel.featureTemplatesViewModel.select(null);k.add(a.viewModel.featureTemplatesViewModel.on("select",({item:d})=>{d&&(a.creationInfo=d,a.viewModel.activeWorkflow?.next())}),f.id)})()},tearDown(){var f=this;return c._asyncToGenerator(function*(){k.remove(f.id)})()}}),
"awaiting-feature-to-create":()=>({id:"awaiting-feature-to-create",setUp(){var f=this;return c._asyncToGenerator(function*(){k.add(yield e.setUpFeatureAdd(a.viewModel.sketchViewModel,a.creationInfo,d=>{a.edits.feature=d;a.viewModel.activeWorkflow?.next()},g),f.id)})()},tearDown(){var f=this;return c._asyncToGenerator(function*(){k.remove(f.id)})()}}),"editing-new-feature":()=>({id:"editing-new-feature",setUp(){var f=this;return c._asyncToGenerator(function*(){const d=a.edits.feature,y=d.sourceLayer,
n=a.viewModel,r=n.sketchViewModel;var z=e.findLayerInfo(n.layerInfos,y);const {spatialReference:J}=n.view;n.featureFormViewModel.set({arcadeEditType:"INSERT",feature:d,formTemplate:z?.formTemplate,spatialReference:J});r.allowDeleteKey=!1;e.prepareAttachmentsForCreateWorkflow(n.attachmentsViewModel);const p=e.getVisualVariableAttributes(d);yield e.startUpdatingFeature(r,d,y,p,g);z=r.on("update",function(){var w=c._asyncToGenerator(function*(q){var h=q.graphics[0];if("complete"===q.state)return e.startUpdatingFeature(r,
h,y,p,g);yield e.visualVariableInteractiveUpdate(r.view,h,q,p,g);q=h.attributes;A.isSome(p.rotation)&&({field:h}=p.rotation,n.featureFormViewModel.setValue(h,q[h]));A.isSome(p.size)&&({field:h}=p.size,n.featureFormViewModel.setValue(h,q[h]))});return function(q){return w.apply(this,arguments)}}());k.add([a.viewModel.featureFormViewModel.on("value-change",c._asyncToGenerator(function*(){a.edits.updateAttributes(a.viewModel.featureFormViewModel.getValues());d.attributes=a.edits.feature.attributes;"3d"===
r.view.type&&(yield e.updateGraphicSymbolWhenRequired(d,g))})),z,D.watch(()=>a.viewModel.attachmentsViewModel.mode,w=>{"add"===w&&a.viewModel.activeWorkflow.go("adding-attachment");"edit"===w&&a.viewModel.activeWorkflow.go("editing-attachment")})],f.id)})()},tearDown(f){var d=this;return c._asyncToGenerator(function*(){f.cancelled&&a.viewModel.sketchViewModel.layer.removeAll();k.remove(d.id)})()}}),"adding-attachment":()=>({id:"adding-attachment",parent:"editing-new-feature",setUp(){return c._asyncToGenerator(function*(){})()},
tearDown(){return c._asyncToGenerator(function*(){a.viewModel.attachmentsViewModel.mode="view"})()}}),"editing-attachment":()=>({id:"editing-attachment",parent:"editing-new-feature",setUp(){return c._asyncToGenerator(function*(){})()},tearDown(){return c._asyncToGenerator(function*(){a.viewModel.attachmentsViewModel.mode="view"})()}})});return e.avoidFeatureTemplateSelectionWithOnlyOneItem(a,b)};c._createClass(u,[{key:"shouldShowAttachments",get:function(){return this.data&&this.data.creationInfo&&
this.data.viewModel?e.shouldShowAttachmentsForCreateWorkflow(this.data):!1}},{key:"shouldAllowAttachmentEditing",get:function(){return this.shouldShowAttachments}},{key:"helpMessage",get:function(){if("editing-new-feature"===this.stepId){var {creationInfo:b,viewModel:m}=this.data;return F.getDrawHelpMessage(b.layer.geometryType,m.sketchViewModel.createGraphic?.geometry)}}},{key:"reliesOnOwnerAdminPrivileges",get:function(){const {layer:b}=this.data.creationInfo,m=b.capabilities?.operations.supportsAdd,
a=B.getEffectiveLayerCapabilities(b)?.operations.supportsAdd;return B.getEffectiveEditingEnabled(b)&&!b.editingEnabled||!!a&&!m}}]);return u}(I);t.__decorate([v.property()],l.prototype,"shouldShowAttachments",null);t.__decorate([v.property()],l.prototype,"shouldAllowAttachmentEditing",null);t.__decorate([v.property()],l.prototype,"helpMessage",null);t.__decorate([v.property()],l.prototype,"reliesOnOwnerAdminPrivileges",null);return l=x=t.__decorate([E.subclass("esri.widgets.Editor.CreateWorkflow")],
l)});