// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/asyncUtils ../../core/Collection ../../core/deprecate ../../core/Error ../../core/Evented ../../core/HandleOwner ../../core/Logger ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../layers/GraphicsLayer ../../layers/support/layerUtils ../../portal/support/urlUtils ../Attachments/AttachmentsViewModel ./CreateFeaturesWorkflow ./CreateWorkflow ./deprecationUtils ./UpdateWorkflow ./workflowUtils ../FeatureForm/FeatureFormViewModel ../FeatureTemplates/FeatureTemplatesViewModel ../Sketch/SketchViewModel ../Spinner/SpinnerViewModel".split(" "),
function(m,g,G,D,H,A,f,I,J,B,n,k,Y,Z,K,L,z,M,N,O,P,C,Q,R,S,T,U,V){function t(w,v,h){x.error(new A(w,v,h))}function W(w,v){return w?w.find(h=>h.layer===v):void 0}const x=J.getLogger("esri.widgets.Editor.EditorViewModel"),E=["create","create-features","update"];f=function(w){function v(b){var a=w.call(this,b)||this;a._sketchGraphicsLayer=new L({listMode:"hide",internal:!0});a._updateEditableItemsTask=null;a.activeWorkflow=null;a._activityQueue=[];a.editableItems=new D;a.failures=[];a.attachmentsViewModel=
new N({abilities:{editing:!0}});a.featureFormViewModel=new S;a.featureTemplatesViewModel=new T;a.sketchViewModel=new U({layer:a._sketchGraphicsLayer});a.spinnerViewModel=new V;a.pageStack=[];a.showDiscardPrompt=()=>Promise.resolve();a._candidateCommitted=!1;a.back=m._asyncToGenerator(function*(){const c=a.activeWorkflow;if(c&&a.canGoBack){if(a.hasPendingEdits)try{yield a.showDiscardPrompt()}catch(d){return}c.hasPreviousStep?yield c.previous({cancelCurrentStep:!0}):yield a.cancelWorkflow({force:!0})}});
a.save=()=>{const {featureFormViewModel:c}=m._assertThisInitialized(a);c.submit();!c.submittable||0<c.validateContingencyConstraints(c.getValues(),{includeIncompleteViolations:!0}).length||a.activeWorkflow?.commit()};a.selectFeature=(c,d=!1)=>{const e=a.activeWorkflow;a._candidateCommitted||"update"!==e?.type||(e.data.edits.feature=c,d&&(e.next(),a._candidateCommitted=!0))};return a}m._inheritsLoose(v,w);var h=v.prototype;h.initialize=function(){this.handles.add([n.watch(()=>{const b=this.view?.map?.editableLayers.filter(({parent:c,
visible:d})=>c&&"visible"in c?d&&c.visible:d),a=this.view?.allLayerViews?.filter(c=>!!b?.includes(c.layer)&&!c.suspended);return[b,a,this.layerInfos,this.allowedWorkflows]},()=>this._updateEditableItems(),n.initial),n.on(()=>this.activeWorkflow,"cancel",()=>this.emit("workflow-cancel")),n.on(()=>this.activeWorkflow,"commit",()=>this.emit("workflow-commit")),n.when(()=>this.view?.map,b=>{b.add(this._sketchGraphicsLayer)},n.initial),n.watch(()=>this.editableItems.toArray(),()=>{const {activeWorkflow:b}=
this;this.refreshCreationTemplates();if(b){var {stepId:a}=b;"create"===b.type?"awaiting-feature-creation-info"!==a||this.canCreate||this._cancelWorkflow():"update"===b.type&&("awaiting-feature-to-update"===a&&!this.canUpdate||"awaiting-update-feature-candidate"===a&&!b.data.candidates.some(c=>{const d=this.editableItems.find(e=>e.layer===c.layer);return d&&d.supports.includes("update")}))&&this._cancelWorkflow()}}),n.watch(()=>this.page,(b,a)=>{const c=this.pageStack.slice();b=c.indexOf(b);-1===b&&
a?c.push(a):c.splice(b);this.pageStack=c}),n.when(()=>"awaiting-update-feature-candidate"===this.state,()=>this._candidateCommitted=!1)])};h.destroy=function(){this._cancelWorkflow().then(()=>{this.view?.map&&this.view.map.remove(this._sketchGraphicsLayer);this.view=null});this._updateEditableItemsTask=B.abortMaybe(this._updateEditableItemsTask)};h.startCreateWorkflowAtFeatureTypeSelection=function(){var b=m._asyncToGenerator(function*(){C.workflowDeprecation(x,"startCreateWorkflowAtFeatureTypeSelection",
"startCreateFeaturesWorkflowAtFeatureTypeSelection");yield n.whenOnce(()=>!this.updating);if(this.canCreate){yield this._cancelWorkflow();var a=this._createCreateWorkflow();yield a.start();this._set("activeWorkflow",a)}else t("editing:unsupported-workflow","Create workflow is unsupported or disabled.")});return function(){return b.apply(this,arguments)}}();h.startCreateFeaturesWorkflowAtFeatureTypeSelection=function(){var b=m._asyncToGenerator(function*(){return this.startCreateFeaturesWorkflow()});
return function(){return b.apply(this,arguments)}}();h.startCreateWorkflowAtFeatureCreation=function(){var b=m._asyncToGenerator(function*(a){C.workflowDeprecation(x,"startCreateWorkflowAtFeatureCreation","startCreateFeaturesWorkflowAtFeatureCreation");yield n.whenOnce(()=>!this.updating);if(this.canCreate){yield this._cancelWorkflow();var c=this._createCreateWorkflow("awaiting-feature-to-create");c.data.creationInfo=a;yield c.start();this._set("activeWorkflow",c)}else t("editing:unsupported-workflow",
"Create workflow is unsupported or disabled.")});return function(a){return b.apply(this,arguments)}}();h.startCreateFeaturesWorkflowAtFeatureCreation=function(){var b=m._asyncToGenerator(function*(a){return this.startCreateFeaturesWorkflow(a,"creating-features")});return function(a){return b.apply(this,arguments)}}();h.startCreateFeaturesWorkflow=function(){var b=m._asyncToGenerator(function*(a,c="awaiting-feature-creation-info"){yield n.whenOnce(()=>!this.updating);if(!this.canCreate)throw new A("editing:unsupported-workflow",
"Creating features is unsupported or disabled.");yield this._cancelWorkflow();a=this._createCreateFeaturesWorkflow(a,c);yield a.start();this._set("activeWorkflow",a)});return function(a){return b.apply(this,arguments)}}();h.startCreateWorkflowAtFeatureEdit=function(){var b=m._asyncToGenerator(function*(a){C.workflowDeprecation(x,"startCreateWorkflowAtFeatureEdit");yield n.whenOnce(()=>!this.updating);if(this.canCreate){yield this._cancelWorkflow();var c=this._createCreateWorkflow("editing-new-feature");
c.data.edits.feature=a;yield c.start();this._set("activeWorkflow",c)}else t("editing:unsupported-workflow","Create workflow is unsupported or disabled.")});return function(a){return b.apply(this,arguments)}}();h.startUpdateWorkflowAtFeatureSelection=function(){var b=m._asyncToGenerator(function*(){yield n.whenOnce(()=>!this.updating);if(this.canUpdate){yield this._cancelWorkflow();var a=this._createUpdateWorkflow();yield a.start();this._set("activeWorkflow",a)}else t("editing:unsupported-workflow",
"Update workflow is unsupported or disabled.")});return function(){return b.apply(this,arguments)}}();h.startUpdateWorkflowAtMultipleFeatureSelection=function(){var b=m._asyncToGenerator(function*(a){yield n.whenOnce(()=>!this.updating);if(this.canUpdate){yield this._cancelWorkflow();var c=this._createUpdateWorkflow("awaiting-update-feature-candidate");c.data.candidates=a;yield c.start();this._set("activeWorkflow",c)}else t("editing:unsupported-workflow","Update workflow is unsupported or disabled.")});
return function(a){return b.apply(this,arguments)}}();h.startUpdateWorkflowAtFeatureEdit=function(){var b=m._asyncToGenerator(function*(a){yield n.whenOnce(()=>!this.updating);if(this.canUpdate){yield this._cancelWorkflow();var c=this._createUpdateWorkflow("editing-existing-feature");c.data.edits.feature=a;yield c.start();this._set("activeWorkflow",c)}else t("editing:unsupported-workflow","Update workflow is unsupported or disabled.")});return function(a){return b.apply(this,arguments)}}();h.deleteFeatureFromWorkflow=
function(){var b=m._asyncToGenerator(function*(){const {activeWorkflow:a}=this;a&&"update"===a.type?(yield this._delete(a.data.edits.feature),yield a.reset()):t("editing:unsupported-workflow","Deleting requires an active update workflow.")});return function(){return b.apply(this,arguments)}}();h.cancelWorkflow=function(){var b=m._asyncToGenerator(function*(a){return this._cancelWorkflow({warn:!0,...a})});return function(a){return b.apply(this,arguments)}}();h.findEditableItemForLayer=function(b){const a=
"subtype-sublayer"===b.type?b.parent:b;return this.editableItems.find(c=>c.layer===a)};h.refreshCreationTemplates=function(){const b=[];for(const {layer:a,supports:c}of this.editableItems)a.loaded&&c.includes("create")&&b.push(a);this.featureTemplatesViewModel.layers=b};h._updateEditableItems=function(){var b=m._asyncToGenerator(function*(){var a=this;B.abortMaybe(this._updateEditableItemsTask);const c=G.createTask(function(){var d=m._asyncToGenerator(function*(e){var l=a.view?.allLayerViews,q=a.view?.map?.editableLayers;
if(l&&q){var p=new Set(q);q=q?.filter(r=>{const u=z.getEffectiveLayerCapabilities(r)?.operations;return!(!r.visible||!u?.supportsAdd||u?.supportsQuery)});var y=l.filter(r=>p.has(r.layer));l=[];for(const r of y.reverse()){const {layer:u,suspended:F}=r;"subtype-group"===u.type?(yield u.loadAll(),l.push(...u.sublayers.slice().reverse().map(X=>a._makeEditableItemForLayer(X,F)))):l.push(a._makeEditableItemForLayer(u,F))}for(const r of q.reverse())"subtype-group"===r.type?(yield r.loadAll(),l.push(...r.sublayers.map(u=>
a._makeEditableItemForLayer(u,!1)))):l.push(a._makeEditableItemForLayer(r,!1));e.aborted||(e=a.editableItems,a.editableItems=new D(l),e.destroy())}});return function(e){return d.apply(this,arguments)}}());this.updatingHandles.addPromise(c.promise);this._updateEditableItemsTask=c});return function(){return b.apply(this,arguments)}}();h._cancelWorkflow=function(){var b=m._asyncToGenerator(function*(a){const c=this.activeWorkflow;c?a&&!1===a.force?(yield c.cancel(a),this._set("activeWorkflow",null)):
(this.emit("workflow-cancel"),this._set("activeWorkflow",null),yield c.cancel(a)):a&&a.warn&&t("editing:no-active-workflow","There is no active workflow to cancel.")});return function(a){return b.apply(this,arguments)}}();h._createCreateFeaturesWorkflow=function(b,a){return O.create(this,b,a,(c,d,e)=>this._applyEdits(c,d,e),(c,d)=>this._addAttachments(c,d))};h._createCreateWorkflow=function(b){return P.create(this,b,(a,c,d)=>this._applyEdits(a,c,d))};h._createUpdateWorkflow=function(b){return Q.create(this,
b,(a,c)=>this._applyEdits(a,c))};h._delete=function(){var b=m._asyncToGenerator(function*(a){const c=a?.sourceLayer;c&&"applyEdits"in c&&(yield this._applyEdits(c,{deleteFeatures:[a]}))});return function(a){return b.apply(this,arguments)}}();h._addAttachments=function(b,a){const c=[];a?.forEach(d=>c.push(this._addAttachment(b,d.feature,d.attachment)));return Promise.all(c)};h._addAttachment=function(){var b=m._asyncToGenerator(function*(a,c,d){let e=null;if("geojson"===a.type||"scene"===a.type||"oriented-imagery"===
a.type)throw new A("editor:attachments-not-supported","Adding attachments is not supported for this layer type");yield this._queueOperation(m._asyncToGenerator(function*(){return e=(yield a.addAttachment?.(c,d).catch(l=>{throw l?.error||l;}))??null}));return e});return function(a,c,d){return b.apply(this,arguments)}}();h._applyEdits=function(){var b=m._asyncToGenerator(function*(a,c,d){var e=this;let l=null;const q=a.url?yield z.getOwningPortalUrl(a.url):null,p={returnServiceEditsOption:q&&M.parseKnownArcGISOnlineDomain(q)||
RegExp("/hosted/","i").test(a.url)?void 0:"original-and-current-features",...d};yield this._queueOperation(m._asyncToGenerator(function*(){if(z.getEffectiveLayerCapabilities(a)?.operations.supportsQuery){const y=yield R.whenEditorLayerView(e.view,a);l=yield a.applyEdits(c,p);yield n.whenOnce(()=>!y.updating);return l}return l=yield a.applyEdits(c,p)}));return l});return function(a,c,d){return b.apply(this,arguments)}}();h._queueOperation=function(b){this._activityQueue.push(b);this.notifyChange("syncing");
const a=(c,d)=>{c=d.indexOf(c);-1<c&&d.splice(c,1)};return b().then(c=>{if("error"in c&&c.error)throw c.error;if("addFeatureResults"in c){const {addFeatureResults:d,deleteFeatureResults:e,updateFeatureResults:l}=c,q=d.find(p=>!!p.error)||l.find(p=>!!p.error)||e.find(p=>!!p.error);if(q)throw q.error;}return c}).catch(c=>{t("editing:operation-error","An error occurred.",{error:c});const d={error:c,retry:()=>{a(d,this.failures);return this._queueOperation(b)},cancel:()=>{a(d,this.failures)}};this._set("failures",
[...this.failures,d])}).then(()=>{a(b,this._activityQueue);this.notifyChange("syncing")})};h._makeEditableItemForLayer=function(b,a=!0){const c=z.getEffectiveLayerCapabilities(b);var d=c?.operations;const e=W(this.layerInfos,b);var l=this.allowedWorkflows;const q=l.includes("create")||l.includes("create-features");var p=l.includes("update");const y=q&&!!d?.supportsAdd&&(!e||!1!==e.enabled&&!1!==e.addEnabled);l=p&&!!d?.supportsUpdate&&(!e||!1!==e.enabled&&!1!==e.updateEnabled);p=p&&!!d?.supportsDelete&&
(!e||!1!==e.enabled&&!1!==e.deleteEnabled);d=[];a||(y&&d.push("create"),l&&d.push("update"),p&&d.push("delete"));a=!!c?.data?.supportsAttachment&&(!e||!1!==e.allowAttachments);return{layer:b,supports:d,attributeUpdatesEnabled:l&&(!e||!1!==e.attributeUpdatesEnabled),geometryUpdatesEnabled:l&&!!c?.editing?.supportsGeometryUpdate&&(!e||!1!==e.geometryUpdatesEnabled),hasAttachments:a,attachmentsOnCreateEnabled:a&&q&&(!e||!1!==e.attachmentsOnCreateEnabled),attachmentsOnUpdateEnabled:a&&(!e||!1!==e.attachmentsOnUpdateEnabled)}};
m._createClass(v,[{key:"allowedWorkflows",get:function(){return this._get("allowedWorkflows")},set:function(b){b&&0!==b.length||(b=[...E]);this._set("allowedWorkflows",b)}},{key:"canCreate",get:function(){return this.editableItems.some(b=>b.supports.includes("create"))}},{key:"canUpdate",get:function(){return this.editableItems.some(b=>b.supports.includes("update")||b.supports.includes("delete")||b.attachmentsOnUpdateEnabled)}},{key:"labelOptions",get:function(){return this.sketchViewModel.labelOptions},
set:function(b){this.sketchViewModel.labelOptions=b}},{key:"layerInfos",set:function(b){b?.some(a=>{"allowAttachments"in a&&H.deprecated(x,"Property: layerInfo.allowAttachments",{replacement:"layerInfo.attachmentsOnCreateEnabled or layerInfo.attachmentsOnUpdateEnabled",version:"4.26"});return!0});this._set("layerInfos",b)}},{key:"snappingOptions",get:function(){return this.sketchViewModel.snappingOptions},set:function(b){this.sketchViewModel.snappingOptions=b}},{key:"state",get:function(){if(!this.get("view.ready")||
0===this.editableItems.length)return"disabled";var b=this.attachmentsViewModel.mode;if("add"===b)return"adding-attachment";if("edit"===b)return"editing-attachment";({activeWorkflow:b}=this);return b?b.stepId:"ready"}},{key:"syncing",get:function(){return 0<this._activityQueue.length}},{key:"updating",get:function(){return this.updatingHandles.updating}},{key:"tooltipOptions",get:function(){return this.sketchViewModel.tooltipOptions},set:function(b){this.sketchViewModel.tooltipOptions=b}},{key:"view",
set:function(b){this.sketchViewModel.view=b;this.spinnerViewModel.view=b;this._set("view",b)}},{key:"page",get:function(){const {activeWorkflow:b,state:a}=this;return"awaiting-feature-to-update"===a||"awaiting-feature-to-create"===a||"create-features"===b?.type&&0===b.pendingFeatures.length?"ready":a??"disabled"}},{key:"selectedTemplateItem",get:function(){var {activeWorkflow:b}=this;if("create-features"===b?.type&&0===b.pendingFeatures.length){({template:b}=b.data.creationInfo);for(const a of this.featureTemplatesViewModel.items)if("findByTemplate"in
a){const c=a.findByTemplate(b);if(c)return c}else if(a.template===b)return a}}},{key:"featureFormDisabled",get:function(){const {activeWorkflow:b}=this;return"update"===b?.type&&!1===b?.data.editableItem?.attributeUpdatesEnabled}},{key:"canGoBack",get:function(){return B.isSome(this.activeWorkflow)&&!this.syncing}},{key:"shouldShowDeleteButton",get:function(){const {activeWorkflow:b}=this;return!!b&&"update"===b.type&&b.data.editableItem.supports.includes("delete")}},{key:"hasPendingEdits",get:function(){const {activeWorkflow:b}=
this;return b?"create"===b.type||"create-features"===b.type&&0<b.numPendingFeatures||"editing-existing-feature"===b.stepId&&b.data.edits.modified:!1}}]);return v}(I.HandleOwnerMixin(f.EventedAccessor));g.__decorate([k.property({readOnly:!0})],f.prototype,"activeWorkflow",void 0);g.__decorate([k.property({readOnly:!0})],f.prototype,"_activityQueue",void 0);g.__decorate([k.property({value:[...E]})],f.prototype,"allowedWorkflows",null);g.__decorate([k.property({readOnly:!0})],f.prototype,"canCreate",
null);g.__decorate([k.property({readOnly:!0})],f.prototype,"canUpdate",null);g.__decorate([k.property()],f.prototype,"editableItems",void 0);g.__decorate([k.property({readOnly:!0})],f.prototype,"failures",void 0);g.__decorate([k.property()],f.prototype,"attachmentsViewModel",void 0);g.__decorate([k.property()],f.prototype,"featureFormViewModel",void 0);g.__decorate([k.property()],f.prototype,"featureTemplatesViewModel",void 0);g.__decorate([k.property()],f.prototype,"labelOptions",null);g.__decorate([k.property()],
f.prototype,"layerInfos",null);g.__decorate([k.property()],f.prototype,"sketchViewModel",void 0);g.__decorate([k.property()],f.prototype,"snappingOptions",null);g.__decorate([k.property()],f.prototype,"spinnerViewModel",void 0);g.__decorate([k.property()],f.prototype,"state",null);g.__decorate([k.property({readOnly:!0})],f.prototype,"syncing",null);g.__decorate([k.property()],f.prototype,"updating",null);g.__decorate([k.property()],f.prototype,"tooltipOptions",null);g.__decorate([k.property()],f.prototype,
"view",null);g.__decorate([k.property()],f.prototype,"pageStack",void 0);g.__decorate([k.property()],f.prototype,"showDiscardPrompt",void 0);g.__decorate([k.property()],f.prototype,"_candidateCommitted",void 0);g.__decorate([k.property()],f.prototype,"page",null);g.__decorate([k.property()],f.prototype,"selectedTemplateItem",null);g.__decorate([k.property()],f.prototype,"featureFormDisabled",null);g.__decorate([k.property()],f.prototype,"canGoBack",null);g.__decorate([k.property()],f.prototype,"shouldShowDeleteButton",
null);g.__decorate([k.property()],f.prototype,"hasPendingEdits",null);return f=g.__decorate([K.subclass("esri.widgets.Editor.EditorViewModel")],f)});