// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/handleUtils ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../../layers/support/layerUtils ../../views/support/layerViewUtils ./Edits ./UpdateWorkflowData ./Workflow ./workflowUtils".split(" "),function(h,y,K,F,D,L,E,u,X,S,M,T,U,V,W,r){var G;u=G=function(N){function v(b){b=
N.call(this,b)||this;b.type="update";return b}h._inheritsLoose(v,N);v.create=function(b,l,a){b=new G({data:new V({edits:new U.Edits,viewModel:b}),onCommit:function(){var g=h._asyncToGenerator(function*(w){const c=w.edits.feature;if(c){var d=c.sourceLayer,e=c.clone();if(!w.edits.attributesModified){const f=d.objectIdField;e.attributes={[f]:c.getAttribute(f)}}w.edits.geometryModified||(e.geometry=null);yield a(d,{updateFeatures:[e]})}});return function(w){return g.apply(this,arguments)}}()});b._set("steps",
this._createWorkflowSteps(b,l));return b};var O=v.prototype;O.highlight=function(b){var l=this.data.viewModel.view;l&&b&&(l=b&&l.allLayerViews.items.find(({layer:a})=>a===b.layer||"subtype-sublayer"===b.layer.type&&b.layer.parent===a),T.highlightsSupported(l)&&this.handles.add(l.highlight(b),"candidate-highlight"))};O.unhighlight=function(){this.handles.remove("candidate-highlight")};v._createWorkflowSteps=function(b,l="awaiting-feature-to-update"){const {data:a,handles:g}=b,w=new Map;return r.createWorkflowSteps(["awaiting-feature-to-update",
"awaiting-update-feature-candidate","editing-existing-feature","adding-attachment","editing-attachment"],l,{"awaiting-feature-to-update":()=>({id:"awaiting-feature-to-update",setUp(){var c=this;return h._asyncToGenerator(function*(){const {spinnerViewModel:d}=a.viewModel,e=a.viewModel.view;let f=null;g.add({remove(){f&&(f.abort(),f=null)}},c.id);a.edits.feature=null;const I=e.on("immediate-click",n=>{d.location=n.mapPoint;d.visible=!0;f?.abort();const {editableItems:H}=a.viewModel;f=new AbortController;
(new Promise((p,t)=>{D.onAbort(f?.signal,()=>t(D.createAbortError()));p(r.fetchCandidates(H,e,n,f?.signal))})).then(p=>{D.throwIfAborted(f);a.candidates=p.reduce((t,m)=>m.error?t:[...t,...m.value],[]);a.viewModel.spinnerViewModel.visible=1===a.candidates.length;0!==a.candidates.length&&(p=a.viewModel.activeWorkflow,1===a.candidates.length?(a.edits.feature=a.candidates[0],p.go("editing-existing-feature").catch(()=>{}).then(()=>a.viewModel.spinnerViewModel.visible=!1)):p.next())})});e.focus();g.add(I,
c.id)})()},tearDown(){var c=this;return h._asyncToGenerator(function*(){g.remove(c.id)})()}}),"awaiting-update-feature-candidate":()=>({id:"awaiting-update-feature-candidate",setUp(){var c=this;return h._asyncToGenerator(function*(){const {edits:d}=a;d.feature=null;g.add(L.watch(()=>d.feature,e=>{b.unhighlight();b.highlight(e)}),c.id)})()},tearDown(){var c=this;return h._asyncToGenerator(function*(){b.unhighlight();g.remove(c.id)})()}}),"editing-existing-feature":()=>({id:"editing-existing-feature",
setUp(){var c=this;return h._asyncToGenerator(function*(){if(!g.has("editing-existing-feature")){var d=a.edits.feature,e=a.viewModel.view,{attachmentsViewModel:f,editableItems:I,featureFormViewModel:n,layerInfos:H,sketchViewModel:p}=a.viewModel;a.editableItem=I.find(k=>k.layer===d.layer);var t=new AbortController;g.add({remove:()=>t.abort()},c.id);var m=r.whenEditorLayerView(e,d.layer),z=r.fetchFullFeature(d,e,t.signal);m=yield m;var q=yield z;if(!D.isAborted(t)){a.edits.updateGeometry(q.geometry);
a.edits.updateAttributes(q.attributes);a.edits.trackChanges();var x=a.editableItem.supports;z=x.includes("create");x=x.includes("update");f.set({abilities:{editing:!0,operations:{add:z||x,update:x,delete:x}},graphic:q,filesEnabled:!1,mode:"view"});z=r.findLayerInfo(H,q.sourceLayer);n.set({arcadeEditType:"UPDATE",feature:q,formTemplate:z?.formTemplate,spatialReference:e.spatialReference,view:e});var A="createInteractiveEditSession"in m?m.createInteractiveEditSession(d):null;m=[n.on("value-change",
k=>{a.edits.updateAttributes(n.getValues());q.attributes=a.edits.feature.attributes;A&&A.setAttribute(k.fieldName,k.value)}),L.watch(()=>f.mode,k=>{"add"===k&&a.viewModel.activeWorkflow.go("adding-attachment");"edit"===k&&a.viewModel.activeWorkflow.go("editing-attachment")})];A&&(m.push(K.makeHandle(()=>A.rollback())),g.add(K.makeHandle(()=>A.commit()),b._handleKeys.afterCommit));if(a.editableItem.geometryUpdatesEnabled){p.allowDeleteKey=!1;const k=r.getVisualVariableAttributes(q),{interactive:P,
visual:Q}=yield r.setUpGeometryUpdate(q,k,p,e,({geometry:R,attributes:J},B)=>{if(F.isSome(k.rotation)){var {field:C}=k.rotation;n.setValue(C,J[C])}F.isSome(k.size)&&({field:C}=k.size,n.setValue(C,J[C]));a.edits.updateAttributes(J);a.edits.updateGeometry(R);n.feature.geometry=R;("undo"===B.type||"redo"===B.type||"update"===B.type&&F.isSome(B.toolEventInfo)&&r.isTerminalUpdateEventType(B.toolEventInfo.type))&&n.notifyFeatureGeometryChanged()},w);m.push(P,Q);g.add(P,b._handleKeys.beforeCommit);g.add(Q,
b._handleKeys.afterCommit)}else b.highlight(q);g.add(m,c.id)}}})()},tearDown({cancelled:c}){var d=this;return h._asyncToGenerator(function*(){c&&(b.unhighlight(),g.remove(d.id))})()}}),"adding-attachment":()=>({id:"adding-attachment",parent:"editing-existing-feature",setUp(){return h._asyncToGenerator(function*(){})()},tearDown(){return h._asyncToGenerator(function*(){a.viewModel.attachmentsViewModel.mode="view"})()}}),"editing-attachment":()=>({id:"editing-attachment",parent:"editing-existing-feature",
setUp(){return h._asyncToGenerator(function*(){})()},tearDown(){return h._asyncToGenerator(function*(){a.viewModel.attachmentsViewModel.mode="view"})()}})})};h._createClass(v,[{key:"shouldShowAttachments",get:function(){return!!this.data?.editableItem.attachmentsOnUpdateEnabled}},{key:"shouldAllowAttachmentEditing",get:function(){return!!this.data?.editableItem.supports.includes("update")}},{key:"helpMessage",get:function(){return"awaiting-feature-to-update"===this.stepId?"select":void 0}},{key:"reliesOnOwnerAdminPrivileges",
get:function(){const {layer:b}=this.data.editableItem,l=b.capabilities?.operations.supportsUpdate,a=M.getEffectiveLayerCapabilities(b)?.operations.supportsUpdate;return M.getEffectiveEditingEnabled(b)&&!b.editingEnabled||!!a&&!l}}]);return v}(W);y.__decorate([E.property()],u.prototype,"shouldShowAttachments",null);y.__decorate([E.property()],u.prototype,"shouldAllowAttachmentEditing",null);y.__decorate([E.property()],u.prototype,"helpMessage",null);y.__decorate([E.property()],u.prototype,"reliesOnOwnerAdminPrivileges",
null);return u=G=y.__decorate([S.subclass("esri.widgets.Editor.UpdateWorkflow")],u)});