// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/time ../../../../../core/Logger ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/Error ../../../../../core/has ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../geometry/ellipsoidUtils ../../../../../chunks/sphere ../../../camera/constraintUtils ../../../camera/constraintUtils/ConstraintTypes ../../../camera/constraintUtils/InteractionType ../../../camera/constraintUtils/surfaceCollision ../../../camera/constraintUtils/TiltMode ../PointToPointAnimationController ../../utils/navigationUtils ../../../support/geometryUtils/ray ../../../support/geometryUtils/sphere ../../../webgl-engine/lib/Camera ../../../webgl-engine/lib/Intersector ../../../../animation/easing".split(" "),
function(l,w,x,y,z,A,P,Q,R,S,T,B,c,h,C,D,E,F,G,H,I,J,k,K,L,t,M,N){l.ZoomStepController=function(u){function q(){var a=u.apply(this,arguments)||this;a._zoomLocation=h.create();a._tmpCamera=new t.Camera;a._tmpViewDir=h.create();a._tmpRayDir={origin:h.create(),direction:h.create()};a._targetOnSphere=h.create();a._tmpCenter=h.create();a._constraintOptions={selection:F.ConstraintTypes.ALL_EXCEPT_COLLISION,interactionType:G.InteractionType.ZOOM,interactionFactor:null,interactionStartCamera:new t.Camera,
interactionDirection:null,tiltMode:I.TiltMode.TUMBLE};a._sphere=D.create();return a}w._inheritsLoose(q,u);var m=q.prototype;m.initialize=function(){this._intersector=M.newIntersector(this.view.state.viewingMode)};m.zoomStep=function(a,e){if(this.active){var f=this.view.state,{interactionStartCamera:b}=this._constraintOptions;b&&(this.animation.finished?b.copyFrom(f.camera):this.animation.cameraAt(1,b));var d=b=!1;this.intersectionHelper.intersectScreen(e,this._zoomLocation,0===this.view.map.ground.opacity?
k.contentIntersectorOptions:{})&&(b=0<a?!0:!1,d=!0);this._tmpCamera.copyFrom(f.camera);b?this.intersectionHelper.intersectRay(this._tmpCamera.ray,this._intersector,this._tmpCenter)&&(this._tmpCamera.center=this._tmpCenter):this.intersectionHelper.intersectRay(this._tmpCamera.ray,this._intersector,this._zoomLocation)?this._tmpCamera.center=this._zoomLocation:c.copy(this._zoomLocation,this._tmpCamera.center);this._updateCamera(this._tmpCamera,a,this._zoomLocation,e,d);this.begin(this._tmpCamera)}};
m.animationSettings=function(){return{duration:A.Milliseconds(600),easing:N.outExpo}};m._updateCamera=function(a,e,f,b,d){var g=C.getReferenceEllipsoid(this.view.spatialReference);g=k.decideNavigationMode(a,b,g);var r=Math.abs(this.view.camera.position.z);c.normalize(n,a.eye);c.scale(n,n,-1);K.fromScreenAtEye(a,b,this._tmpRayDir);c.normalize(this._tmpRayDir.direction,this._tmpRayDir.direction);const v=y.clamp(Math.min(k.ZOOM_DISTANCE_MODIFIER,1/Math.abs(c.dot(n,this._tmpRayDir.direction)))*r,k.ZOOM_MIN_DISTANCE_MODIFIER,
k.ZOOM_MAX_DISTANCE_MODIFIER);if(g===k.NavigationMode.Horizontal){e=.6**e;this._sphere[3]=c.length(f);c.subtract(this._tmpViewDir,a.center,a.eye);d=Math.min(c.length(this._tmpViewDir),v);g=d*e;1>=e&&4>g&&(g=4,e=g/d);if(1E-6>Math.abs(d-g))return;d=c.length(a.center);this._sphere[3]!==d&&(a.center=c.scale(p,a.center,(this._sphere[3]+e*(d-this._sphere[3]))/d));c.scale(this._tmpViewDir,this._tmpViewDir,-e);a.eye=c.add(p,a.center,this._tmpViewDir);E.applyAll(this.view,a,this._constraintOptions);1E-12<
c.squaredDistance(f,a.center)&&L.intersectScreen(this._sphere,a,b,this._targetOnSphere)&&k.panToPosition(this._sphere,a,f,this._targetOnSphere,this.view.camera.heading,this.view.camera.tilt,!0)}else{g=.6**Math.abs(e);r=0<e?1:-1;c.subtract(this._tmpViewDir,f,a.eye);const O=c.length(this._tmpViewDir);b=this.view._stage.renderView.getMinimalDepthForArea(null,b[0],b[1],this.view.state.camera,60);b=z.isSome(b)?b:v;b=d&&0<e?Math.min(b,O):b;c.scale(this._tmpRayDir.direction,this._tmpRayDir.direction,b);
c.add(f,this._tmpRayDir.origin,this._tmpRayDir.direction);f=b*g;d=Math.max(4,1.01*a.nearFar[0]);0<e&&f<d&&(f=d,g=f/b);if(1E-6>Math.abs(b-f))return;c.scale(this._tmpRayDir.direction,this._tmpRayDir.direction,r*(1-g));a.eye=c.add(p,a.eye,this._tmpRayDir.direction);a.center=c.add(p,a.center,this._tmpRayDir.direction)}H.applySurfaceCollisionConstraint(this.view,a)};return q}(J.PointToPointAnimationController);l.ZoomStepController=x.__decorate([B.subclass("esri.views.3d.state.controllers.global.ZoomStepController")],
l.ZoomStepController);const p=h.create(),n=h.create();Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});