// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/has ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/spatialReferenceUtils ../../../../layers/support/TileInfo ../../viewStateUtils ../../engine/Bitmap ../../tiling/TileInfoView ../../tiling/TileKey".split(" "),
function(r,k,g,M,n,m,N,O,G,C,H,I,E,J,K,L){const q=C.create(),p=[0,0],z=new L(0,0,0,0);g=function(F){function A(l){var a=F.call(this,l)||this;a._imagePromise=null;a.bitmaps=[];a.hidpi=!1;a.imageMaxWidth=2048;a.imageMaxHeight=2048;a.imageRotationSupported=!1;a.imageNormalizationSupported=!1;a.update=n.debounce(function(){var h=r._asyncToGenerator(function*(e,c){n.throwIfAborted(c);if(e.stationary&&!a.destroyed){var b=e.state,f=H.getInfo(b.spatialReference);e=a.hidpi?e.pixelRatio:1;var d=a.imageNormalizationSupported&&
b.worldScreenWidth&&b.worldScreenWidth<b.size[0],u=a.imageMaxWidth??0,v=a.imageMaxHeight??0;d?(p[0]=b.worldScreenWidth,p[1]=b.size[1]):a.imageRotationSupported?(p[0]=b.size[0],p[1]=b.size[1]):E.getOuterSize(p,b);f=f&&(b.extent.xmin<f.valid[0]||b.extent.xmax>f.valid[1]);var w=!a.imageNormalizationSupported&&f,D=!(Math.floor(p[0]*e)>u||Math.floor(p[1]*e)>v)&&!w,x=a.imageRotationSupported?b.rotation:0;f=a.container.children.slice();D?(d=d?b.paddedViewState.center:b.center,a._imagePromise&&console.error("Image promise was not defined!"),
a._imagePromise=a._singleExport(b,p,d,b.resolution,x,e,c)):(d=Math.min(u,v),w&&(d=Math.min(b.worldScreenWidth,d)),a._imagePromise=a._tiledExport(b,d,e,c));try{const y=(yield a._imagePromise)??[];n.throwIfAborted(c);c=[];a._imagePromise=null;if(!a.destroyed){a.bitmaps=y;for(const t of f)y.includes(t)||c.push(t.fadeOut().then(()=>{t.remove();t.destroy()}));for(const t of y)c.push(t.fadeIn());yield Promise.all(c)}}catch(y){a._imagePromise=null,n.throwIfAbortError(y)}}});return function(e,c){return h.apply(this,
arguments)}}(),5E3);a.updateExports=n.debounce(function(){var h=r._asyncToGenerator(function*(e){const c=[];for(const b of a.container.children){if(!b.visible||!b.stage)return;c.push(e(b).then(()=>{b.invalidateTexture();b.requestRender()}))}a._imagePromise=n.eachAlways(c).then(()=>a._imagePromise=null);yield a._imagePromise});return function(e){return h.apply(this,arguments)}}());return a}r._inheritsLoose(A,F);var B=A.prototype;B.destroy=function(){this.bitmaps.forEach(l=>l.destroy());this.bitmaps=
[]};B._export=function(){var l=r._asyncToGenerator(function*(a,h,e,c,b,f){e=yield this.fetchSource(a,Math.floor(h*b),Math.floor(e*b),{rotation:c,pixelRatio:b,signal:f});n.throwIfAborted(f);const d=new J.Bitmap(null,{immutable:!0,requestRenderOnSourceChangedEnabled:!0});d.x=a.xmin;d.y=a.ymax;d.resolution=a.width/h;d.rotation=c;d.pixelRatio=b;d.opacity=0;this.container.addChild(d);yield d.setSourceAsync(e,f);n.throwIfAborted(f);return d});return function(a,h,e,c,b,f){return l.apply(this,arguments)}}();
B._singleExport=function(){var l=r._asyncToGenerator(function*(a,h,e,c,b,f,d){E.getBBox(q,e,c,h);a=C.toExtent(q,a.spatialReference);return[yield this._export(a,h[0],h[1],b,f,d)]});return function(a,h,e,c,b,f,d){return l.apply(this,arguments)}}();B._tiledExport=function(l,a,h,e){var c=I.create({size:a,spatialReference:l.spatialReference,scales:[l.scale]});const b=new K(c);c=b.getTileCoverage(l);if(!c)return null;const f=[];c.forEach((d,u,v,w)=>{z.set(d,u,v,0);b.getTileBounds(q,z);const D=C.toExtent(q,
l.spatialReference);f.push(this._export(D,a,a,0,h,e).then(x=>{0!==w&&(z.set(d,u,v,w),b.getTileBounds(q,z),x.x=q[0],x.y=q[3]);return x}))});return Promise.all(f)};r._createClass(A,[{key:"updating",get:function(){return!this.destroyed&&null!==this._imagePromise}}]);return A}(g);k.__decorate([m.property()],g.prototype,"_imagePromise",void 0);k.__decorate([m.property()],g.prototype,"bitmaps",void 0);k.__decorate([m.property()],g.prototype,"container",void 0);k.__decorate([m.property()],g.prototype,"fetchSource",
void 0);k.__decorate([m.property()],g.prototype,"hidpi",void 0);k.__decorate([m.property()],g.prototype,"imageMaxWidth",void 0);k.__decorate([m.property()],g.prototype,"imageMaxHeight",void 0);k.__decorate([m.property()],g.prototype,"imageRotationSupported",void 0);k.__decorate([m.property()],g.prototype,"imageNormalizationSupported",void 0);k.__decorate([m.property()],g.prototype,"requestUpdate",void 0);k.__decorate([m.property()],g.prototype,"updating",null);return g=k.__decorate([G.subclass("esri.views.2d.layers.support.ExportStrategy")],
g)});