// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/3d/support/buffer/workerHelper":function(){define(["exports","../../../../geometry/support/buffer/BufferView","./InterleavedLayout"],function(l,k,x){function r(c){const d=[];c.fields.forEach((g,n)=>{var w=g.constructor;d.push([n,{...g,constructor:`${w.ElementType}_${w.ElementCount}`}])});return{stride:c.stride,fields:d,fieldNames:c.fieldNames}}function q(c){const d=x.newLayout();d.stride=c.stride;d.fieldNames=c.fieldNames;c.fields.forEach(g=>d.fields.set(g[0],{...g[1],
constructor:h.get(g[1].constructor)}));return d}k=[k.BufferViewFloat,k.BufferViewVec2f,k.BufferViewVec3f,k.BufferViewVec4f,k.BufferViewMat3f,k.BufferViewMat4f,k.BufferViewFloat64,k.BufferViewVec2f64,k.BufferViewVec3f64,k.BufferViewVec4f64,k.BufferViewMat3f64,k.BufferViewMat4f64,k.BufferViewUint8,k.BufferViewVec2u8,k.BufferViewVec3u8,k.BufferViewVec4u8,k.BufferViewUint16,k.BufferViewVec2u16,k.BufferViewVec3u16,k.BufferViewVec4u16,k.BufferViewUint32,k.BufferViewVec2u32,k.BufferViewVec3u32,k.BufferViewVec4u32,
k.BufferViewInt8,k.BufferViewVec2i8,k.BufferViewVec3i8,k.BufferViewVec4i8,k.BufferViewInt16,k.BufferViewVec2i16,k.BufferViewVec3i16,k.BufferViewVec4i16,k.BufferViewInt32,k.BufferViewVec2i32,k.BufferViewVec3i32,k.BufferViewVec4i32];const h=new Map;k.forEach(c=>h.set(`${c.ElementType}_${c.ElementCount}`,c));l.packInterleavedBuffer=function(c,d){d.push(c.buffer);return{buffer:c.buffer,layout:r(c.layout)}};l.packLayout=r;l.unpackInterleavedBuffer=function(c){return q(c.layout).createView(c.buffer)};l.unpackLayout=
q;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/buffer/BufferView":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ./internals/Mat3 ./internals/Mat4 ./internals/Scalar ./internals/Vec2 ./internals/Vec3 ./internals/Vec4".split(" "),function(l,k,x,r,q,h,c,d){let g=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.fromTypedArray=function(a,f){return new b(a.buffer,
a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);g.ElementType="f32";let n=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);n.ElementType="f32";let w=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,
a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);w.ElementType="f32";let t=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,
f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);t.ElementType="f32";let u=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(x.BufferViewMat3Impl);u.ElementType="f32";x=function(e){function b(a,f=0,z,C){a=
e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(x.BufferViewMat3Impl);x.ElementType="f64";let E=function(e){function b(a,f=0,z,C){a=e.call(this,Float32Array,a,f,z,C)||this;a.elementType="f32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=
function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewMat4Impl);E.ElementType="f32";r=function(e){function b(a,f=0,z,C){a=e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewMat4Impl);r.ElementType="f64";let y=function(e){function b(a,
f=0,z,C){a=e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);y.ElementType="f64";let p=function(e){function b(a,f=0,z,C){a=e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,
a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);p.ElementType="f64";let v=function(e){function b(a,f=0,z,C){a=e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);v.ElementType="f64";let A=
function(e){function b(a,f=0,z,C){a=e.call(this,Float64Array,a,f,z,C)||this;a.elementType="f64";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);A.ElementType="f64";let D=function(e){function b(a,f=0,z,C){a=e.call(this,Uint8Array,a,f,z,C)||this;a.elementType="u8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,
a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);D.ElementType="u8";let F=function(e){function b(a,f=0,z,C){a=e.call(this,Uint8Array,a,f,z,C)||this;a.elementType="u8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);F.ElementType="u8";let B=
function(e){function b(a,f=0,z,C){a=e.call(this,Uint8Array,a,f,z,C)||this;a.elementType="u8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);B.ElementType="u8";let G=function(e){function b(a,f=0,z,C){a=e.call(this,Uint8Array,a,f,z,C)||this;a.elementType="u8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,
a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);G.ElementType="u8";let H=function(e){function b(a,f=0,z,C){a=e.call(this,Uint16Array,a,f,z,C)||this;a.elementType="u16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);H.ElementType="u16";let I=
function(e){function b(a,f=0,z,C){a=e.call(this,Uint16Array,a,f,z,C)||this;a.elementType="u16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);I.ElementType="u16";let J=function(e){function b(a,f=0,z,C){a=e.call(this,Uint16Array,a,f,z,C)||this;a.elementType="u16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,
a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);J.ElementType="u16";let K=function(e){function b(a,f=0,z,C){a=e.call(this,Uint16Array,a,f,z,C)||this;a.elementType="u16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);K.ElementType="u16";let L=
function(e){function b(a,f=0,z,C){a=e.call(this,Uint32Array,a,f,z,C)||this;a.elementType="u32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);L.ElementType="u32";let M=function(e){function b(a,f=0,z,C){a=e.call(this,Uint32Array,a,f,z,C)||this;a.elementType="u32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,
f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);M.ElementType="u32";let P=function(e){function b(a,f=0,z,C){a=e.call(this,Uint32Array,a,f,z,C)||this;a.elementType="u32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);
P.ElementType="u32";let O=function(e){function b(a,f=0,z,C){a=e.call(this,Uint32Array,a,f,z,C)||this;a.elementType="u32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);O.ElementType="u32";let R=function(e){function b(a,f=0,z,C){a=e.call(this,Int8Array,a,f,z,C)||this;a.elementType="i8";return a}k._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);R.ElementType="i8";let S=function(e){function b(a,f=0,z,C){a=e.call(this,Int8Array,a,f,z,C)||this;a.elementType="i8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);
S.ElementType="i8";let T=function(e){function b(a,f=0,z,C){a=e.call(this,Int8Array,a,f,z,C)||this;a.elementType="i8";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);T.ElementType="i8";let Q=function(e){function b(a,f=0,z,C){a=e.call(this,Int8Array,a,f,z,C)||this;a.elementType="i8";return a}k._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);Q.ElementType="i8";let U=function(e){function b(a,f=0,z,C){a=e.call(this,Int16Array,a,f,z,C)||this;a.elementType="i16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);
U.ElementType="i16";let V=function(e){function b(a,f=0,z,C){a=e.call(this,Int16Array,a,f,z,C)||this;a.elementType="i16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);V.ElementType="i16";let N=function(e){function b(a,f=0,z,C){a=e.call(this,Int16Array,a,f,z,C)||this;a.elementType="i16";return a}k._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);N.ElementType="i16";let m=function(e){function b(a,f=0,z,C){a=e.call(this,Int16Array,a,f,z,C)||this;a.elementType="i16";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);
m.ElementType="i16";q=function(e){function b(a,f=0,z,C){a=e.call(this,Int32Array,a,f,z,C)||this;a.elementType="i32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(q.BufferViewScalarImpl);q.ElementType="i32";h=function(e){function b(a,f=0,z,C){a=e.call(this,Int32Array,a,f,z,C)||this;a.elementType="i32";return a}k._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);h.ElementType="i32";c=function(e){function b(a,f=0,z,C){a=e.call(this,Int32Array,a,f,z,C)||this;a.elementType="i32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);
c.ElementType="i32";d=function(e){function b(a,f=0,z,C){a=e.call(this,Int32Array,a,f,z,C)||this;a.elementType="i32";return a}k._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);d.ElementType="i32";l.BufferViewFloat=g;l.BufferViewFloat64=y;l.BufferViewInt16=U;l.BufferViewInt32=q;l.BufferViewInt8=R;l.BufferViewMat3f=u;l.BufferViewMat3f64=x;
l.BufferViewMat4f=E;l.BufferViewMat4f64=r;l.BufferViewUint16=H;l.BufferViewUint32=L;l.BufferViewUint8=D;l.BufferViewVec2f=n;l.BufferViewVec2f64=p;l.BufferViewVec2i16=V;l.BufferViewVec2i32=h;l.BufferViewVec2i8=S;l.BufferViewVec2u16=I;l.BufferViewVec2u32=M;l.BufferViewVec2u8=F;l.BufferViewVec3f=w;l.BufferViewVec3f64=v;l.BufferViewVec3i16=N;l.BufferViewVec3i32=c;l.BufferViewVec3i8=T;l.BufferViewVec3u16=J;l.BufferViewVec3u32=P;l.BufferViewVec3u8=B;l.BufferViewVec4f=t;l.BufferViewVec4f64=A;l.BufferViewVec4i16=
m;l.BufferViewVec4i32=d;l.BufferViewVec4i8=Q;l.BufferViewVec4u16=K;l.BufferViewVec4u32=O;l.BufferViewVec4u8=G;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/buffer/internals/Mat3":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,k){let x=function(){function r(h,c,d=0,g,n){this.TypedArrayConstructor=h;this.elementCount=9;h=this.TypedArrayConstructor;void 0===g&&(g=9*h.BYTES_PER_ELEMENT);const w=0===c.byteLength?0:d;this.typedBuffer=
null==n?new h(c,w):new h(c,w,(n-d)/h.BYTES_PER_ELEMENT);this.typedBufferStride=g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var q=r.prototype;q.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};q.getMat=function(h,c){h*=this.typedBufferStride;for(let d=0;9>d;d++)c[d]=this.typedBuffer[h++];
return c};q.setMat=function(h,c){h*=this.typedBufferStride;for(let d=0;9>d;d++)this.typedBuffer[h++]=c[d]};q.get=function(h,c){return this.typedBuffer[h*this.typedBufferStride+c]};q.set=function(h,c,d){this.typedBuffer[h*this.typedBufferStride+c]=d};q.copyFrom=function(h,c,d){const g=this.typedBuffer,n=c.typedBuffer;h*=this.typedBufferStride;c=d*c.typedBufferStride;for(d=0;9>d;++d)g[h++]=n[c++]};k._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return r}();x.ElementCount=
9;l.BufferViewMat3Impl=x;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/buffer/internals/Mat4":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,k){let x=function(){function r(h,c,d=0,g,n){this.TypedArrayConstructor=h;this.elementCount=16;h=this.TypedArrayConstructor;void 0===g&&(g=16*h.BYTES_PER_ELEMENT);const w=0===c.byteLength?0:d;this.typedBuffer=null==n?new h(c,w):new h(c,w,(n-d)/h.BYTES_PER_ELEMENT);this.typedBufferStride=
g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var q=r.prototype;q.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};q.getMat=function(h,c){h*=this.typedBufferStride;for(let d=0;16>d;d++)c[d]=this.typedBuffer[h++];return c};q.setMat=function(h,c){h*=this.typedBufferStride;for(let d=0;16>
d;d++)this.typedBuffer[h++]=c[d]};q.get=function(h,c){return this.typedBuffer[h*this.typedBufferStride+c]};q.set=function(h,c,d){this.typedBuffer[h*this.typedBufferStride+c]=d};q.copyFrom=function(h,c,d){const g=this.typedBuffer,n=c.typedBuffer;h*=this.typedBufferStride;c=d*c.typedBufferStride;for(d=0;16>d;++d)g[h++]=n[c++]};k._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return r}();x.ElementCount=16;l.BufferViewMat4Impl=x;Object.defineProperty(l,Symbol.toStringTag,
{value:"Module"})})},"esri/geometry/support/buffer/internals/Scalar":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,k){let x=function(){function r(h,c,d=0,g,n){this.TypedArrayConstructor=h;this.elementCount=1;h=this.TypedArrayConstructor;void 0===g&&(g=h.BYTES_PER_ELEMENT);const w=0===c.byteLength?0:d;this.typedBuffer=null==n?new h(c,w):new h(c,w,(n-d)/h.BYTES_PER_ELEMENT);this.stride=g;this.typedBufferStride=g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/
this.typedBufferStride)}var q=r.prototype;q.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};q.get=function(h){return this.typedBuffer[h*this.typedBufferStride]};q.set=function(h,c){this.typedBuffer[h*this.typedBufferStride]=c};k._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return r}();x.ElementCount=1;l.BufferViewScalarImpl=x;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},
"esri/geometry/support/buffer/internals/Vec2":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec2"],function(l,k,x){let r=function(){function q(c,d,g=0,n,w){this.TypedArrayConstructor=c;this.elementCount=2;c=this.TypedArrayConstructor;void 0===n&&(n=2*c.BYTES_PER_ELEMENT);const t=0===d.byteLength?0:g;this.typedBuffer=null==w?new c(d,t):new c(d,t,(w-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=n/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/
this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var h=q.prototype;h.sliceBuffer=function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,d){c*=this.typedBufferStride;return x.set(d,this.typedBuffer[c],this.typedBuffer[c+1])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c]=d[1]};h.get=function(c,d){return this.typedBuffer[c*
this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*this.typedBufferStride+d]=g};h.setValues=function(c,d,g){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c]=g};h.copyFrom=function(c,d,g){const n=this.typedBuffer,w=d.typedBuffer;c*=this.typedBufferStride;d=g*d.typedBufferStride;n[c++]=w[d++];n[c]=w[d]};k._createClass(q,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return q}();r.ElementCount=2;l.BufferViewVec2Impl=r;Object.defineProperty(l,Symbol.toStringTag,
{value:"Module"})})},"esri/chunks/vec2":function(){define(["exports","./common"],function(l,k){function x(m,e){m[0]=e[0];m[1]=e[1];return m}function r(m,e,b){m[0]=e;m[1]=b;return m}function q(m,e,b){m[0]=e[0]+b[0];m[1]=e[1]+b[1];return m}function h(m,e,b){m[0]=e[0]-b[0];m[1]=e[1]-b[1];return m}function c(m,e,b){m[0]=e[0]*b[0];m[1]=e[1]*b[1];return m}function d(m,e,b){m[0]=e[0]/b[0];m[1]=e[1]/b[1];return m}function g(m,e){m[0]=Math.ceil(e[0]);m[1]=Math.ceil(e[1]);return m}function n(m,e){m[0]=Math.floor(e[0]);
m[1]=Math.floor(e[1]);return m}function w(m,e,b){m[0]=Math.min(e[0],b[0]);m[1]=Math.min(e[1],b[1]);return m}function t(m,e,b){m[0]=Math.max(e[0],b[0]);m[1]=Math.max(e[1],b[1]);return m}function u(m,e){m[0]=Math.round(e[0]);m[1]=Math.round(e[1]);return m}function E(m,e,b){m[0]=e[0]*b;m[1]=e[1]*b;return m}function y(m,e,b,a){m[0]=e[0]+b[0]*a;m[1]=e[1]+b[1]*a;return m}function p(m,e){const b=e[0]-m[0];m=e[1]-m[1];return Math.sqrt(b*b+m*m)}function v(m,e){const b=e[0]-m[0];m=e[1]-m[1];return b*b+m*m}
function A(m){const e=m[0];m=m[1];return Math.sqrt(e*e+m*m)}function D(m){const e=m[0];m=m[1];return e*e+m*m}function F(m,e){m[0]=-e[0];m[1]=-e[1];return m}function B(m,e){m[0]=1/e[0];m[1]=1/e[1];return m}function G(m,e){var b=e[0];const a=e[1];b=b*b+a*a;0<b&&(b=1/Math.sqrt(b),m[0]=e[0]*b,m[1]=e[1]*b);return m}function H(m,e){return m[0]*e[0]+m[1]*e[1]}function I(m,e,b){e=e[0]*b[1]-e[1]*b[0];m[0]=m[1]=0;m[2]=e;return m}function J(m,e,b,a){const f=e[0];e=e[1];m[0]=f+a*(b[0]-f);m[1]=e+a*(b[1]-e);return m}
function K(m,e){e=e||1;const b=2*k.RANDOM()*Math.PI;m[0]=Math.cos(b)*e;m[1]=Math.sin(b)*e;return m}function L(m,e,b){const a=e[0];e=e[1];m[0]=b[0]*a+b[2]*e;m[1]=b[1]*a+b[3]*e;return m}function M(m,e,b){const a=e[0];e=e[1];m[0]=b[0]*a+b[2]*e+b[4];m[1]=b[1]*a+b[3]*e+b[5];return m}function P(m,e,b){const a=e[0];e=e[1];m[0]=b[0]*a+b[3]*e+b[6];m[1]=b[1]*a+b[4]*e+b[7];return m}function O(m,e,b){const a=e[0];e=e[1];m[0]=b[0]*a+b[4]*e+b[12];m[1]=b[1]*a+b[5]*e+b[13];return m}function R(m,e,b,a){const f=e[0]-
b[0];e=e[1]-b[1];const z=Math.sin(a);a=Math.cos(a);m[0]=f*a-e*z+b[0];m[1]=f*z+e*a+b[1];return m}function S(m,e){var b=m[0];m=m[1];const a=e[0];e=e[1];let f=b*b+m*m;0<f&&(f=1/Math.sqrt(f));let z=a*a+e*e;0<z&&(z=1/Math.sqrt(z));b=(b*a+m*e)*f*z;return 1<b?0:-1>b?Math.PI:Math.acos(b)}function T(m){return"vec2("+m[0]+", "+m[1]+")"}function Q(m,e){return m[0]===e[0]&&m[1]===e[1]}function U(m,e){const b=m[0];m=m[1];const a=e[0];e=e[1];const f=k.getEpsilon();return Math.abs(b-a)<=f*Math.max(1,Math.abs(b),
Math.abs(a))&&Math.abs(m-e)<=f*Math.max(1,Math.abs(m),Math.abs(e))}function V(m,e,b,a,f){let z=e[0]-b[0];b=e[1]-b[1];f=(a[0]*z+a[1]*b)*(f-1);z=a[0]*f;b=a[1]*f;m[0]=e[0]+z;m[1]=e[1]+b;return m}const N=Object.freeze(Object.defineProperty({__proto__:null,add:q,angle:S,ceil:g,copy:x,cross:I,dist:p,distance:p,div:d,divide:d,dot:H,equals:U,exactEquals:Q,floor:n,inverse:B,len:A,length:A,lerp:J,max:t,min:w,mul:c,multiply:c,negate:F,normalize:G,projectAndScale:V,random:K,rotate:R,round:u,scale:E,scaleAndAdd:y,
set:r,sqrDist:v,sqrLen:D,squaredDistance:v,squaredLength:D,str:T,sub:h,subtract:h,transformMat2:L,transformMat2d:M,transformMat3:P,transformMat4:O},Symbol.toStringTag,{value:"Module"}));l.add=q;l.angle=S;l.ceil=g;l.copy=x;l.cross=I;l.dist=p;l.distance=p;l.div=d;l.divide=d;l.dot=H;l.equals=U;l.exactEquals=Q;l.floor=n;l.inverse=B;l.len=A;l.length=A;l.lerp=J;l.max=t;l.min=w;l.mul=c;l.multiply=c;l.negate=F;l.normalize=G;l.projectAndScale=V;l.random=K;l.rotate=R;l.round=u;l.scale=E;l.scaleAndAdd=y;l.set=
r;l.sqrDist=v;l.sqrLen=D;l.squaredDistance=v;l.squaredLength=D;l.str=T;l.sub=h;l.subtract=h;l.transformMat2=L;l.transformMat2d=M;l.transformMat3=P;l.transformMat4=O;l.vec2=N})},"esri/geometry/support/buffer/internals/Vec3":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec3"],function(l,k,x){let r=function(){function q(c,d,g=0,n,w){this.TypedArrayConstructor=c;this.elementCount=3;c=this.TypedArrayConstructor;void 0===n&&(n=3*c.BYTES_PER_ELEMENT);const t=
0===d.byteLength?0:g;this.typedBuffer=null==w?new c(d,t):new c(d,t,(w-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=n/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var h=q.prototype;h.sliceBuffer=function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,d){c*=this.typedBufferStride;return x.set(d,
this.typedBuffer[c],this.typedBuffer[c+1],this.typedBuffer[c+2])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c++]=d[1];this.typedBuffer[c]=d[2]};h.get=function(c,d){return this.typedBuffer[c*this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*this.typedBufferStride+d]=g};h.setValues=function(c,d,g,n){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c++]=g;this.typedBuffer[c]=n};h.copyFrom=function(c,d,g){const n=this.typedBuffer,
w=d.typedBuffer;c*=this.typedBufferStride;d=g*d.typedBufferStride;n[c++]=w[d++];n[c++]=w[d++];n[c]=w[d]};k._createClass(q,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return q}();r.ElementCount=3;l.BufferViewVec3Impl=r;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/buffer/internals/Vec4":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec4"],function(l,k,x){let r=function(){function q(c,d,g=
0,n,w){this.TypedArrayConstructor=c;this.start=g;this.elementCount=4;c=this.TypedArrayConstructor;void 0===n&&(n=4*c.BYTES_PER_ELEMENT);const t=0===d.byteLength?0:g;this.typedBuffer=null==w?new c(d,t):new c(d,t,(w-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=n/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var h=q.prototype;h.sliceBuffer=function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+
d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,d){c*=this.typedBufferStride;return x.set(d,this.typedBuffer[c++],this.typedBuffer[c++],this.typedBuffer[c++],this.typedBuffer[c])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c++]=d[1];this.typedBuffer[c++]=d[2];this.typedBuffer[c]=d[3]};h.get=function(c,d){return this.typedBuffer[c*this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*this.typedBufferStride+
d]=g};h.setValues=function(c,d,g,n,w){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c++]=g;this.typedBuffer[c++]=n;this.typedBuffer[c]=w};h.copyFrom=function(c,d,g){const n=this.typedBuffer,w=d.typedBuffer;c*=this.typedBufferStride;d=g*d.typedBufferStride;n[c++]=w[d++];n[c++]=w[d++];n[c++]=w[d++];n[c]=w[d]};k._createClass(q,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return q}();r.ElementCount=4;l.BufferViewVec4Impl=r;Object.defineProperty(l,Symbol.toStringTag,
{value:"Module"})})},"esri/views/3d/support/buffer/InterleavedLayout":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../geometry/support/buffer/BufferView","../../../../geometry/support/buffer/types"],function(l,k,x,r){let q=function(){function c(g,n){this.layout=g;this.buffer="number"===typeof n?new ArrayBuffer(n*g.stride):n;for(const w of g.fieldNames)n=g.fields.get(w),this[w]=new n.constructor(this.buffer,n.offset,this.stride)}var d=c.prototype;d.getField=
function(g,n){return(g=this[g])&&g.elementCount===n.ElementCount&&g.elementType===n.ElementType?g:null};d.slice=function(g,n){return new c(this.layout,this.buffer.slice(g*this.stride,n*this.stride))};d.copyFrom=function(g,n,w,t){const u=this.stride;0===u%4?(g=new Uint32Array(g.buffer,n*u,t*u/4),(new Uint32Array(this.buffer,w*u,t*u/4)).set(g)):(g=new Uint8Array(g.buffer,n*u,t*u),(new Uint8Array(this.buffer,w*u,t*u)).set(g))};k._createClass(c,[{key:"stride",get:function(){return this.layout.stride}},
{key:"count",get:function(){return this.buffer.byteLength/this.stride}},{key:"byteLength",get:function(){return this.buffer.byteLength}}]);return c}(),h=function(){function c(){this.stride=0;this.fields=new Map;this.fieldNames=[]}var d=c.prototype;d.vec2f=function(g,n){this._appendField(g,x.BufferViewVec2f,n);return this};d.vec2f64=function(g,n){this._appendField(g,x.BufferViewVec2f64,n);return this};d.vec3f=function(g,n){this._appendField(g,x.BufferViewVec3f,n);return this};d.vec3f64=function(g,
n){this._appendField(g,x.BufferViewVec3f64,n);return this};d.vec4f=function(g,n){this._appendField(g,x.BufferViewVec4f,n);return this};d.vec4f64=function(g,n){this._appendField(g,x.BufferViewVec4f64,n);return this};d.mat3f=function(g,n){this._appendField(g,x.BufferViewMat3f,n);return this};d.mat3f64=function(g,n){this._appendField(g,x.BufferViewMat3f64,n);return this};d.mat4f=function(g,n){this._appendField(g,x.BufferViewMat4f,n);return this};d.mat4f64=function(g,n){this._appendField(g,x.BufferViewMat4f64,
n);return this};d.vec4u8=function(g,n){this._appendField(g,x.BufferViewVec4u8,n);return this};d.f32=function(g,n){this._appendField(g,x.BufferViewFloat,n);return this};d.f64=function(g,n){this._appendField(g,x.BufferViewFloat64,n);return this};d.u8=function(g,n){this._appendField(g,x.BufferViewUint8,n);return this};d.u16=function(g,n){this._appendField(g,x.BufferViewUint16,n);return this};d.i8=function(g,n){this._appendField(g,x.BufferViewInt8,n);return this};d.vec2i8=function(g,n){this._appendField(g,
x.BufferViewVec2i8,n);return this};d.vec2i16=function(g,n){this._appendField(g,x.BufferViewVec2i16,n);return this};d.vec2u8=function(g,n){this._appendField(g,x.BufferViewVec2u8,n);return this};d.vec4u16=function(g,n){this._appendField(g,x.BufferViewVec4u16,n);return this};d.u32=function(g,n){this._appendField(g,x.BufferViewUint32,n);return this};d._appendField=function(g,n,w){const t=n.ElementCount*r.elementTypeSize(n.ElementType);this.fields.set(g,{size:t,constructor:n,offset:this.stride,optional:w});
this.stride+=t;this.fieldNames.push(g)};d.alignTo=function(g){this.stride=Math.floor((this.stride+g-1)/g)*g;return this};d.hasField=function(g){return this.fieldNames.includes(g)};d.createBuffer=function(g){return new q(this,g)};d.createView=function(g){return new q(this,g)};d.clone=function(){const g=new c;g.stride=this.stride;g.fields=new Map;this.fields.forEach((n,w)=>g.fields.set(w,n));g.fieldNames=this.fieldNames.slice();g.BufferType=this.BufferType;return g};return c}();l.InterleavedBuffer=
q;l.InterleavedLayout=h;l.newLayout=function(){return new h};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/buffer/types":function(){define(["exports"],function(l){l.elementTypeSize=function(k){switch(k){case "u8":return 1;case "u16":return 2;case "u32":return 4;case "i8":return 1;case "i16":return 2;case "i32":return 4;case "f32":return 4;case "f64":return 8}};l.isInteger=function(k){switch(k){case "u8":case "u16":case "u32":case "i8":case "i16":case "i32":return!0;
case "f32":case "f64":return!1}};l.isSigned=function(k){switch(k){case "u8":case "u16":case "u32":return!1;case "i8":case "i16":case "i32":case "f32":case "f64":return!0}};l.maximumValue=function(k){switch(k){case "u8":return 255;case "u16":return 65535;case "u32":return 4294967295;case "i8":return 127;case "i16":return 32767;case "i32":return 2147483647;case "f32":return 3.402823E38;case "f64":return 1.79769E308}};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/edgeRendering/bufferLayouts":function(){define(["exports",
"../../../support/buffer/glUtil","../../../support/buffer/InterleavedLayout","../VertexAttribute"],function(l,k,x,r){const q=x.newLayout().vec3f(r.VertexAttribute.POSITION).u16(r.VertexAttribute.COMPONENTINDEX).u16(r.VertexAttribute.U16PADDING),h=x.newLayout().vec2u8(r.VertexAttribute.SIDENESS);k=k.glLayout(h);x=x.newLayout().vec3f(r.VertexAttribute.POSITION0).vec3f(r.VertexAttribute.POSITION1).u16(r.VertexAttribute.COMPONENTINDEX).u8(r.VertexAttribute.VARIANTOFFSET,{glNormalized:!0}).u8(r.VertexAttribute.VARIANTSTROKE).u8(r.VertexAttribute.VARIANTEXTENSION,
{glNormalized:!0}).u8(r.VertexAttribute.U8PADDING,{glPadding:!0}).u16(r.VertexAttribute.U16PADDING,{glPadding:!0});const c=x.clone().vec3f(r.VertexAttribute.NORMAL),d=x.clone().vec3f(r.VertexAttribute.NORMALA).vec3f(r.VertexAttribute.NORMALB);r=new Map([[r.VertexAttribute.POSITION0,0],[r.VertexAttribute.POSITION1,1],[r.VertexAttribute.COMPONENTINDEX,2],[r.VertexAttribute.VARIANTOFFSET,3],[r.VertexAttribute.VARIANTSTROKE,4],[r.VertexAttribute.VARIANTEXTENSION,5],[r.VertexAttribute.NORMAL,6],[r.VertexAttribute.NORMALA,
6],[r.VertexAttribute.NORMALB,7],[r.VertexAttribute.SIDENESS,8]]);l.CommonInstancesLayout=x;l.EdgeInputBufferLayout=q;l.EdgeShaderAttributeLocations=r;l.RegularEdgeInstancesLayout=c;l.SilhouetteEdgeInstancesLayout=d;l.VertexLayout=h;l.glVertexLayout=k;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/support/buffer/glUtil":function(){define(["exports","../../../webgl/enums","../../../webgl/VertexElementDescriptor"],function(l,k,x){const r={u8:k.DataType.UNSIGNED_BYTE,
u16:k.DataType.UNSIGNED_SHORT,u32:k.DataType.UNSIGNED_INT,i8:k.DataType.BYTE,i16:k.DataType.SHORT,i32:k.DataType.INT,f32:k.DataType.FLOAT};l.glLayout=function(q,h=0){const c=q.stride;return q.fieldNames.filter(d=>{d=q.fields.get(d).optional;return!(d&&d.glPadding)}).map(d=>{const g=q.fields.get(d),n=g.constructor.ElementCount;var w=r[g.constructor.ElementType];if(!w)throw Error("BufferType not supported in WebGL");return new x.VertexElementDescriptor(d,n,w,g.offset,c,!(!g.optional||!g.optional.glNormalized),
h)})};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/VertexAttribute":function(){define(["exports"],function(l){l.VertexAttribute=void 0;var k=l.VertexAttribute||(l.VertexAttribute={});k.POSITION="position";k.NORMAL="normal";k.UV0="uv0";k.AUXPOS1="auxpos1";k.AUXPOS2="auxpos2";k.COLOR="color";k.SYMBOLCOLOR="symbolColor";k.SIZE="size";k.TANGENT="tangent";k.OFFSET="offset";k.SUBDIVISIONFACTOR="subdivisionFactor";k.COLORFEATUREATTRIBUTE="colorFeatureAttribute";
k.SIZEFEATUREATTRIBUTE="sizeFeatureAttribute";k.OPACITYFEATUREATTRIBUTE="opacityFeatureAttribute";k.DISTANCETOSTART="distanceToStart";k.UVMAPSPACE="uvMapSpace";k.BOUNDINGRECT="boundingRect";k.UVREGION="uvRegion";k.NORMALCOMPRESSED="normalCompressed";k.PROFILERIGHT="profileRight";k.PROFILEUP="profileUp";k.PROFILEVERTEXANDNORMAL="profileVertexAndNormal";k.FEATUREVALUE="featureValue";k.MODELORIGINHI="modelOriginHi";k.MODELORIGINLO="modelOriginLo";k.MODEL="model";k.MODELNORMAL="modelNormal";k.INSTANCECOLOR=
"instanceColor";k.INSTANCEFEATUREATTRIBUTE="instanceFeatureAttribute";k.LOCALTRANSFORM="localTransform";k.GLOBALTRANSFORM="globalTransform";k.BOUNDINGSPHERE="boundingSphere";k.MODELORIGIN="modelOrigin";k.MODELSCALEFACTORS="modelScaleFactors";k.FEATUREATTRIBUTE="featureAttribute";k.STATE="state";k.LODLEVEL="lodLevel";k.POSITION0="position0";k.POSITION1="position1";k.NORMALA="normalA";k.NORMALB="normalB";k.COMPONENTINDEX="componentIndex";k.VARIANTOFFSET="variantOffset";k.VARIANTSTROKE="variantStroke";
k.VARIANTEXTENSION="variantExtension";k.U8PADDING="u8padding";k.U16PADDING="u16padding";k.SIDENESS="sideness";k.START="start";k.END="end";k.UP="up";k.EXTRUDE="extrude";k.OBJECTANDLAYERIDCOLOR="objectAndLayerIdColor";k.OBJECTANDLAYERIDCOLOR_INSTANCED="objectAndLayerIdColor_instanced";Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgePreprocessing":function(){define(["exports","../../../../../core/arrayUtils","../../../../../core/mathUtils",
"../../../../../chunks/vec3","../../../../../chunks/vec3f64"],function(l,k,x,r,q){function h(t,u){const E=x.acosClamped(t.cosAngle),y=g.fwd,p=g.ortho;r.direction(y,t.position1,t.position0);t=0<r.dot(r.cross(p,t.faceNormal0,t.faceNormal1),y)?-1:1;return E*t>u}function c(t){const u=t.faces.length/3,E=t.faces;t=t.neighbors;var y=0;for(var p=0;p<u;p++){var v=t[3*p+1],A=t[3*p+2],D=E[3*p],F=E[3*p+1],B=E[3*p+2];y+=-1===t[3*p]||D<F?1:0;y+=-1===v||F<B?1:0;y+=-1===A||B<D?1:0}y=new Int32Array(4*y);p=0;for(v=
0;v<u;v++){A=t[3*v];D=t[3*v+1];F=t[3*v+2];B=E[3*v];const G=E[3*v+1],H=E[3*v+2];if(-1===A||B<G)y[p++]=B,y[p++]=G,y[p++]=v,y[p++]=A;if(-1===D||G<H)y[p++]=G,y[p++]=H,y[p++]=v,y[p++]=D;if(-1===F||H<B)y[p++]=H,y[p++]=B,y[p++]=v,y[p++]=F}return y}function d(t){const u=t.faces.length/3,E=t.vertices.position;t=t.faces;const y=n.v0,p=n.v1,v=n.v2,A=new Float32Array(3*u);for(let D=0;D<u;D++){const F=t[3*D+1],B=t[3*D+2];E.getVec(t[3*D],y);E.getVec(F,p);E.getVec(B,v);r.subtract(p,p,y);r.subtract(v,v,y);r.cross(y,
p,v);r.normalize(y,y);A[3*D]=y[0];A[3*D+1]=y[1];A[3*D+2]=y[2]}return A}l.EdgeType=void 0;(function(t){t[t.SOLID=0]="SOLID";t[t.SKETCH=1]="SKETCH"})(l.EdgeType||(l.EdgeType={}));const g={edge:{position0:q.create(),position1:q.create(),faceNormal0:q.create(),faceNormal1:q.create(),componentIndex:0,cosAngle:0},ortho:q.create(),fwd:q.create()},n={v0:q.create(),v1:q.create(),v2:q.create()},w={anglePlanar:4,angleSignificantEdge:35};l.extractEdges=function(t,u,E,y=w){const p=t.vertices.position;var v=t.vertices.componentIndex,
A=x.deg2rad(y.anglePlanar);y=x.deg2rad(y.angleSignificantEdge);const D=Math.cos(y),F=Math.cos(A),B=g.edge,G=B.position0,H=B.position1,I=B.faceNormal0,J=B.faceNormal1,K=d(t),L=c(t),M=L.length/4;t=u.allocate(M);y=0;const P=E.allocate(M);let O=0,R=0,S=0;const T=k.range(0,M),Q=new Float32Array(M);Q.forEach((m,e,b)=>{p.getVec(L[4*e],G);p.getVec(L[4*e+1],H);b[e]=r.distance(G,H)});T.sort((m,e)=>Q[e]-Q[m]);const U=[],V=[];for(let m=0;m<M;m++){var N=T[m];const e=Q[N],b=L[4*N],a=L[4*N+1],f=L[4*N+2];N=L[4*N+
3];const z=-1===N;p.getVec(b,G);p.getVec(a,H);if(z)r.set(I,K[3*f],K[3*f+1],K[3*f+2]),r.copy(J,I),B.componentIndex=v.get(b),B.cosAngle=r.dot(I,J);else{r.set(I,K[3*f],K[3*f+1],K[3*f+2]);r.set(J,K[3*N],K[3*N+1],K[3*N+2]);B.componentIndex=v.get(b);B.cosAngle=r.dot(I,J);if(B.cosAngle>F)continue;-.9999>B.cosAngle&&r.copy(J,I)}R+=e;S++;z||B.cosAngle<D?(u.write(t,y++,B),U.push(e)):h(B,A)&&(E.write(P,O++,B),V.push(e))}v=new Float32Array(U.reverse());A=new Float32Array(V.reverse());return{regular:{instancesData:u.trim(t,
y),lodInfo:{lengths:v}},silhouette:{instancesData:E.trim(P,O),lodInfo:{lengths:A}},averageEdgeLength:R/S}};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgeProcessing":function(){define("exports ../../../../../geometry/support/meshUtils/deduplicate ../../../support/meshProcessing ../../../support/buffer/InterleavedLayout ../VertexAttribute ./bufferLayouts ./edgeBufferWriters ./edgePreprocessing".split(" "),function(l,k,x,r,q,h,c,d){function g(u,
E,y,p){if(E)return E=x.computeNeighbors(y,p,u.count),new n(y,p,E,u);u=k.deduplicate(u.buffer,u.stride/4,{originalIndices:y,originalIndicesLength:p});p=x.computeNeighbors(u.indices,p,u.uniqueCount);return{faces:u.indices,facesLength:u.indices.length,neighbors:p,vertices:h.EdgeInputBufferLayout.createView(u.buffer)}}let n=function(u,E,y,p){this.faces=u;this.facesLength=E;this.neighbors=y;this.vertices=p};const w=new c.RegularEdgeBufferWriter,t=new c.SilhouetteEdgeBufferWriter;c=r.newLayout().vec3f(q.VertexAttribute.POSITION0).vec3f(q.VertexAttribute.POSITION1);
r=r.newLayout().vec3f(q.VertexAttribute.POSITION0).vec3f(q.VertexAttribute.POSITION1).u16(q.VertexAttribute.COMPONENTINDEX).u16(q.VertexAttribute.U16PADDING,{glPadding:!0});l.extract=function(u){const E=g(u.data,u.skipDeduplicate,u.indices,u.indicesLength);w.updateSettings(u.writerSettings);t.updateSettings(u.writerSettings);return d.extractEdges(E,w,t)};l.extractComponentsEdgeLocationsLayout=r;l.extractEdgeInformation=g;l.extractEdgeLocationsLayout=c;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},
"esri/geometry/support/meshUtils/deduplicate":function(){define(["exports","../../../core/mathUtils","../../../views/3d/webgl-engine/lib/Indices"],function(l,k,x){let r=null;l.deduplicate=function(q,h,c){var d=Array.isArray(q),g=d?q.length/h:q.byteLength/(4*h),n=d?q:new Uint32Array(q,0,g*h),w=c?.minReduction??0;const t=(q=c?.originalIndices||null)?q.length:0;var u=c?.componentOffsets||null;c=0;if(u)for(var E=0;E<u.length-1;E++){var y=u[E+1]-u[E];y>c&&(c=y)}else c=g;var p=Math.floor(1.1*c)+1;if(null==
r||r.length<2*p)r=new Uint32Array(k.nextHighestPowerOfTwo(2*p));for(c=0;c<2*p;c++)r[c]=0;c=0;const v=(y=!!u&&!!q)?t:g;E=x.newIndexArray(g/3);var A=new Uint32Array(t),D=0!==w?Math.ceil(7.84*1.96/(w*w)*w*(1-w)):v,F=1,B=u?u[1]:v;for(let K=0;K<v;K++){if(K===D){var G=1-c/K;if(G+1.96*Math.sqrt(G*(1-G)/K)<w)return null;D*=2}if(K===B){for(B=0;B<2*p;B++)r[B]=0;if(q)for(B=u[F-1];B<u[F];B++)A[B]=E[q[B]];B=u[++F]}G=y?q[K]:K;const L=G*h;var H=0;for(var I=0;I<h;I++)H=n[L+I]+H|0,H=H+(H<<11)+(H>>>2)|0;H>>>=0;I=H%
p;let M=c;for(;0!==r[2*I+1];){if(r[2*I]===H){const P=r[2*I+1]-1;var J=P*h;a:{for(let O=0;O<h;O++)if(n[L+O]!==n[J+O]){J=!1;break a}J=!0}if(J){M=E[P];break}}I++;I>=p&&(I-=p)}M===c&&(r[2*I]=H,r[2*I+1]=G+1,c++);E[G]=M}if(0!==w&&1-c/g<w)return null;if(y){for(g=u[F-1];g<A.length;g++)A[g]=E[q[g]];E=x.compactIndices(A)}d=d?Array(c):new Uint32Array(c*h);c=0;for(D=0;D<v;D++)if(E[D]===c){g=n;w=(y?q[D]:D)*h;u=d;p=c*h;A=h;for(F=0;F<A;F++)u[p+F]=g[w+F];c++}if(q&&!y){h=new Uint32Array(t);for(n=0;n<h.length;n++)h[n]=
E[q[n]];E=x.compactIndices(h)}return{buffer:Array.isArray(d)?d:d.buffer,indices:E,uniqueCount:c}};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/Indices":function(){define(["exports","../../../../core/typedArrayUtil"],function(l,k){let x=(()=>{const h=new Uint32Array(131072);for(let c=0;c<h.length;++c)h[c]=c;return h})();const r=[0],q=(()=>{const h=new Uint16Array(65536);for(let c=0;c<h.length;++c)h[c]=c;return h})();l.compactIndices=function(h){if(Array.isArray(h)){if(h.length<
k.NATIVE_ARRAY_MAX_SIZE)return h;for(const c of h)if(65536<=c)return new Uint32Array(h);return new Uint16Array(h)}if(h.length<k.NATIVE_ARRAY_MAX_SIZE)return Array.from(h);if(h.BYTES_PER_ELEMENT===Uint16Array.BYTES_PER_ELEMENT)return h;for(const c of h)if(65536<=c)return h;return new Uint16Array(h)};l.generateDefaultIndexArray=function(h){if(1===h)return r;if(h<k.NATIVE_ARRAY_MAX_SIZE)return Array.from(new Uint16Array(q.buffer,0,h));if(h<q.length)return new Uint16Array(q.buffer,0,h);if(h>x.length){x=
new Uint32Array(Math.max(2*x.length,h));for(let c=0;c<x.length;c++)x[c]=c}return new Uint32Array(x.buffer,0,h)};l.generateIndexArray=function(h){if(1===h)return r;if(h<k.NATIVE_ARRAY_MAX_SIZE)return Array.from(new Uint16Array(q.buffer,0,h));if(h<q.length)return new Uint16Array(q.slice(0,h));if(h>x.length){h=new Uint32Array(h);for(let c=0;c<h.length;c++)h[c]=c;return h}return new Uint32Array(x.slice(0,h))};l.newIndexArray=function(h){h*=3;return h<=k.NATIVE_ARRAY_MAX_SIZE?Array(h):65536>=h?new Uint16Array(h):
new Uint32Array(h)};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/support/meshProcessing":function(){define(["exports"],function(l){l.computeNeighbors=function(k,x,r){x/=3;const q=new Uint32Array(r+1),h=new Uint32Array(r+1);var c=(p,v)=>{p<v?q[p+1]++:h[v+1]++};for(var d=0;d<x;d++){var g=k[3*d],n=k[3*d+1],w=k[3*d+2];c(g,n);c(n,w);c(w,g)}d=c=0;for(g=0;g<r;g++)n=q[g+1],w=h[g+1],q[g+1]=c,h[g+1]=d,c+=n,d+=w;const t=new Uint32Array(6*x),u=q[r];c=(p,v,A)=>{p<v?(p=q[p+1]++,
t[2*p]=v,t[2*p+1]=A):(v=h[v+1]++,t[2*u+2*v]=p,t[2*u+2*v+1]=A)};for(d=0;d<x;d++)g=k[3*d],n=k[3*d+1],w=k[3*d+2],c(g,n,d),c(n,w,d),c(w,g,d);c=(p,v)=>{const A=2*p;p=v-p;for(v=1;v<p;v++){const D=t[A+2*v],F=t[A+2*v+1];let B=v-1;for(B;0<=B&&t[A+2*B]>D;B--)t[A+2*B+2]=t[A+2*B],t[A+2*B+3]=t[A+2*B+1];t[A+2*B+2]=D;t[A+2*B+3]=F}};for(d=0;d<r;d++)c(q[d],q[d+1]),c(u+h[d],u+h[d+1]);const E=new Int32Array(3*x),y=(p,v)=>p===k[3*v]?0:p===k[3*v+1]?1:p===k[3*v+2]?2:-1;x=(p,v)=>{p=y(p,v);E[3*v+p]=-1};c=(p,v,A,D)=>{p=y(p,
v);E[3*v+p]=D;A=y(A,D);E[3*D+A]=v};for(d=0;d<r;d++){g=q[d];n=q[d+1];w=h[d];const p=h[d+1];for(;g<n&&w<p;){const v=t[2*g],A=t[2*u+2*w];v===A?(c(d,t[2*g+1],A,t[2*u+2*w+1]),g++,w++):v<A?(x(d,t[2*g+1]),g++):(x(A,t[2*u+2*w+1]),w++)}for(;g<n;)x(d,t[2*g+1]),g++;for(;w<p;)x(t[2*u+2*w],t[2*u+2*w+1]),w++}return E};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgeBufferWriters":function(){define("exports ../../../../../core/RandomLCG ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../support/buffer/glUtil ./bufferLayouts".split(" "),
function(l,k,x,r,q,h){function c(A){const D=w;D[0]=A.position0[0];D[1]=A.position0[1];D[2]=A.position0[2];D[3]=A.position1[0];D[4]=A.position1[1];D[5]=A.position1[2];u[0]=5381;for(A=0;A<t.length;A++)u[0]=31*u[0]+t[A];return u[0]}function d(A){const D=w;D[0]=g(A.position0[0]);D[1]=g(A.position0[1]);D[2]=g(A.position0[2]);D[3]=g(A.position1[0]);D[4]=g(A.position1[1]);D[5]=g(A.position1[2]);u[0]=5381;for(A=0;A<t.length;A++)u[0]=31*u[0]+t[A];return u[0]}function g(A){return Math.round(1E4*A)/1E4}let n=
function(){function A(){}var D=A.prototype;D.updateSettings=function(F){this.settings=F;this._edgeHashFunction=F.reducedPrecision?d:c};D.write=function(F,B,G){var H=this._edgeHashFunction(G);v.seed=H;H=v.getIntRange(0,255);const I=v.getIntRange(0,this.settings.variants-1);var J=v.getFloat();J=-(1-Math.min(J/.7,1))+Math.max(0,J-.7)/(1-.7);J=255*(Math.abs(J)**1.2*(0>J?-1:1)*.5+.5);F.position0.setVec(B,G.position0);F.position1.setVec(B,G.position1);F.componentIndex.set(B,G.componentIndex);F.variantOffset.set(B,
H);F.variantStroke.set(B,I);F.variantExtension.set(B,J)};D.trim=function(F,B){return F.slice(0,B)};return A}();const w=new Float32Array(6),t=new Uint32Array(w.buffer),u=new Uint32Array(1);let E=function(){function A(){this._commonWriter=new n}var D=A.prototype;D.updateSettings=function(F){this._commonWriter.updateSettings(F)};D.allocate=function(F){return h.RegularEdgeInstancesLayout.createBuffer(F)};D.write=function(F,B,G){this._commonWriter.write(F,B,G);x.add(p,G.faceNormal0,G.faceNormal1);x.normalize(p,
p);F.normal.setVec(B,p)};D.trim=function(F,B){return this._commonWriter.trim(F,B)};return A}();E.Layout=h.RegularEdgeInstancesLayout;E.glLayout=q.glLayout(h.RegularEdgeInstancesLayout,1);let y=function(){function A(){this._commonWriter=new n}var D=A.prototype;D.updateSettings=function(F){this._commonWriter.updateSettings(F)};D.allocate=function(F){return h.SilhouetteEdgeInstancesLayout.createBuffer(F)};D.write=function(F,B,G){this._commonWriter.write(F,B,G);F.normalA.setVec(B,G.faceNormal0);F.normalB.setVec(B,
G.faceNormal1)};D.trim=function(F,B){return this._commonWriter.trim(F,B)};return A}();y.Layout=h.SilhouetteEdgeInstancesLayout;y.glLayout=q.glLayout(h.SilhouetteEdgeInstancesLayout,1);const p=r.create(),v=new k;l.CommonBufferWriter=n;l.RegularEdgeBufferWriter=E;l.SilhouetteEdgeBufferWriter=y;Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})})},"*noref":1}});
define(["../../../../../chunks/_rollupPluginBabelHelpers","../../../support/buffer/workerHelper","./bufferLayouts","./edgePreprocessing","./edgeProcessing"],function(l,k,x,r,q){function h(u){return{data:x.EdgeInputBufferLayout.createView(u.dataBuffer),indices:"Uint32Array"===u.indicesType?new Uint32Array(u.indices):"Uint16Array"===u.indicesType?new Uint16Array(u.indices):u.indices,indicesLength:u.indicesLength,writerSettings:u.writerSettings,skipDeduplicate:u.skipDeduplicate}}let c=function(){function u(){}
var E=u.prototype;E.extract=function(){var y=l._asyncToGenerator(function*(p){var v=h(p);p=q.extract(v);v=[v.data.buffer];v.push(p.regular.lodInfo.lengths.buffer);v.push(p.silhouette.lodInfo.lengths.buffer);return{result:{regular:{instancesData:k.packInterleavedBuffer(p.regular.instancesData,v),lodInfo:{lengths:p.regular.lodInfo.lengths.buffer}},silhouette:{instancesData:k.packInterleavedBuffer(p.silhouette.instancesData,v),lodInfo:{lengths:p.silhouette.lodInfo.lengths.buffer}},averageEdgeLength:p.averageEdgeLength},
transferList:v}});return function(p){return y.apply(this,arguments)}}();E.extractComponentsEdgeLocations=function(){var y=l._asyncToGenerator(function*(p){p=h(p);p=q.extractEdgeInformation(p.data,p.skipDeduplicate,p.indices,p.indicesLength);p=r.extractEdges(p,w,t);const v=[];return{result:k.packInterleavedBuffer(p.regular.instancesData,v),transferList:v}});return function(p){return y.apply(this,arguments)}}();E.extractEdgeLocations=function(){var y=l._asyncToGenerator(function*(p){p=h(p);p=q.extractEdgeInformation(p.data,
p.skipDeduplicate,p.indices,p.indicesLength);p=r.extractEdges(p,n,t);const v=[];return{result:k.packInterleavedBuffer(p.regular.instancesData,v),transferList:v}});return function(p){return y.apply(this,arguments)}}();return u}(),d=function(){function u(){}var E=u.prototype;E.allocate=function(y){return q.extractEdgeLocationsLayout.createBuffer(y)};E.trim=function(y,p){return y.slice(0,p)};E.write=function(y,p,v){y.position0.setVec(p,v.position0);y.position1.setVec(p,v.position1)};return u}(),g=function(){function u(){}
var E=u.prototype;E.allocate=function(y){return q.extractComponentsEdgeLocationsLayout.createBuffer(y)};E.trim=function(y,p){return y.slice(0,p)};E.write=function(y,p,v){y.position0.setVec(p,v.position0);y.position1.setVec(p,v.position1);y.componentIndex.set(p,v.componentIndex)};return u}();const n=new d,w=new g,t={allocate:()=>null,write:()=>{},trim:()=>null};return c});