// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../config ../kernel ../request ../core/Error ../core/JSONSupport ../core/Loadable ../core/maybe ../core/promiseUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass ../geometry/Extent ../intl/locale ./PortalQueryParams ./PortalQueryResult ./PortalUser ../support/apiKeyUtils".split(" "),function(w,
A,c,y,z,H,B,b,I,F,u,d,J,Q,v,K,L,C,D,M,N,O){const x=q=>Object.freeze(Object.defineProperty({__proto__:null,default:q},Symbol.toStringTag,{value:"Module"}));var l;let E;const G={PortalGroup:()=>new Promise((q,m)=>w(["./PortalGroup"],h=>q(x(h)),m)),PortalItem:()=>new Promise((q,m)=>w(["./PortalItem"],h=>q(x(h)),m)),PortalUser:()=>new Promise((q,m)=>w(["./PortalUser"],h=>q(x(h)),m))};b=l=function(q){function m(a){a=q.call(this,a)||this;a._esriIdCredentialCreateHandle=null;a.access=null;a.allSSL=!1;a.authMode=
"auto";a.authorizedCrossOriginDomains=null;a.basemapGalleryGroupQuery=null;a.bingKey=null;a.canListApps=!1;a.canListData=!1;a.canListPreProvisionedItems=!1;a.canProvisionDirectPurchase=!1;a.canSearchPublic=!0;a.canShareBingPublic=!1;a.canSharePublic=!1;a.canSignInArcGIS=!1;a.canSignInIDP=!1;a.colorSetsGroupQuery=null;a.commentsEnabled=!1;a.created=null;a.culture=null;a.customBaseUrl=null;a.defaultBasemap=null;a.defaultDevBasemap=null;a.defaultExtent=null;a.defaultVectorBasemap=null;a.description=
null;a.devBasemapGalleryGroupQuery=null;a.eueiEnabled=null;a.featuredGroups=null;a.featuredItemsGroupQuery=null;a.galleryTemplatesGroupQuery=null;a.livingAtlasGroupQuery=null;a.hasCategorySchema=!1;a.helperServices=null;a.homePageFeaturedContent=null;a.homePageFeaturedContentCount=null;a.httpPort=null;a.httpsPort=null;a.id=null;a.ipCntryCode=null;a.isPortal=!1;a.isReadOnly=!1;a.layerTemplatesGroupQuery=null;a.maxTokenExpirationMinutes=null;a.modified=null;a.name=null;a.portalHostname=null;a.portalMode=
null;a.portalProperties=null;a.region=null;a.rotatorPanels=null;a.showHomePageDescription=!1;a.sourceJSON=null;a.supportsHostedServices=!1;a.symbolSetsGroupQuery=null;a.templatesGroupQuery=null;a.units=null;a.url=y.portalUrl;a.urlKey=null;a.user=null;a.useStandardizedQuery=!1;a.useVectorBasemaps=!1;a.vectorBasemapGalleryGroupQuery=null;return a}A._inheritsLoose(m,q);var h=m.prototype;h.normalizeCtorArgs=function(a){return"string"===typeof a?{url:a}:a};h.destroy=function(){this._esriIdCredentialCreateHandle=
F.removeMaybe(this._esriIdCredentialCreateHandle)};h.readAuthorizedCrossOriginDomains=function(a){if(a)for(const e of a)y.request.trustedServers.includes(e)||y.request.trustedServers.push(e);return a};h.readDefaultBasemap=function(a){return this._readBasemap(a)};h.readDefaultDevBasemap=function(a){return this._readBasemap(a)};h.readDefaultVectorBasemap=function(a){return this._readBasemap(a)};h.readUrlKey=function(a){return a?a.toLowerCase():a};h.readUser=function(a){let e=null;a&&(e=N.fromJSON(a),
e.portal=this);return e};h.load=function(a){const e=(new Promise((f,g)=>w(["../Basemap"],k=>f(x(k)),g))).then(({default:f})=>{u.throwIfAborted(a);E=f}).then(()=>this.sourceJSON?this.sourceJSON:this.fetchSelf(this.authMode,!1,a)).then(f=>{if(z.id){const g=z.id;this.credential=g.findCredential(this.restUrl);this.credential||this.authMode!==l.AUTH_MODE_AUTO||(this._esriIdCredentialCreateHandle=g.on("credential-create",()=>{g.findCredential(this.restUrl)&&this.signIn().catch(()=>{})}))}this.sourceJSON=
f;this.read(f)});this.addResolvingPromise(e);return Promise.resolve(this)};h.createElevationLayers=function(){var a=A._asyncToGenerator(function*(){yield this.load();const e=this._getHelperService("defaultElevationLayers"),f=(yield new Promise((g,k)=>w(["../layers/ElevationLayer"],p=>g(x(p)),k))).default;return e?e.map(g=>new f({id:g.id,url:g.url})):[]});return function(){return a.apply(this,arguments)}}();h.fetchBasemaps=function(a,e){const f=new D;f.query=a||(y.apiKey&&O.supportsApiKey(this.url)?
this.devBasemapGalleryGroupQuery:this.useVectorBasemaps?this.vectorBasemapGalleryGroupQuery:this.basemapGalleryGroupQuery);f.disableExtraQuery=!0;return this.queryGroups(f,e).then(g=>{f.num=100;f.query='type:"Web Map" -type:"Web Application"';return g.total?(g=g.results[0],f.sortField=g.sortField||"name",f.sortOrder=g.sortOrder||"desc",g.queryItems(f,e)):null}).then(g=>g&&g.total?g.results.filter(k=>"Web Map"===k.type).map(k=>new E({portalItem:k})):[])};h.fetchCategorySchema=function(a){return this.hasCategorySchema?
this.request(this.restUrl+"/portals/self/categorySchema",a).then(e=>e.categorySchema):u.isAborted(a)?Promise.reject(u.createAbortError()):Promise.resolve([])};h.fetchFeaturedGroups=function(a){const e=this.featuredGroups,f=new D;f.num=100;f.sortField="title";if(e&&e.length){const g=[];for(const k of e)g.push(`(title:"${k.title}" AND owner:${k.owner})`);f.query=g.join(" OR ");return this.queryGroups(f,a).then(k=>k.results)}return u.isAborted(a)?Promise.reject(u.createAbortError()):Promise.resolve([])};
h.fetchRegions=function(a){const e=this.user?.culture||this.culture||C.getLocale();return this.request(this.restUrl+"/portals/regions",{...a,query:{culture:e}})};h.fetchSettings=function(a){const e=this.user?.culture||this.culture||C.getLocale();return this.request(this.restUrl+"/portals/self/settings",{...a,query:{culture:e}})};m.getDefault=function(){if(!l._default||l._default.destroyed)l._default=new l;return l._default};h.queryGroups=function(a,e){return this.queryPortal("/community/groups",a,
"PortalGroup",e)};h.queryItems=function(a,e){return this.queryPortal("/search",a,"PortalItem",e)};h.queryUsers=function(a,e){a.sortField||(a.sortField="username");return this.queryPortal("/community/users",a,"PortalUser",e)};h.fetchSelf=function(a=this.authMode,e=!1,f){const g=this.restUrl+"/portals/self";a={authMode:a,query:{culture:C.getLocale().toLowerCase()},...f};"auto"===a.authMode&&(a.authMode="no-prompt");e&&(a.query.default=!0);return this.request(g,a)};h.queryPortal=function(a,e,f,g){const k=
J.ensureType(D,e),p=n=>this.request(this.restUrl+a,{...k.toRequestOptions(this),...g}).then(r=>{const t=k.clone();t.start=r.nextStart;return new M({nextQueryParams:t,queryParams:k,total:r.total,results:l._resultsToTypedArray(n,{portal:this},r,g)})}).then(r=>Promise.all(r.results.map(t=>"function"===typeof t.when?t.when():r)).then(()=>r,t=>{u.throwIfAbortError(t);return r}));return f&&G[f]?G[f]().then(({default:n})=>{u.throwIfAborted(g);return p(n)}):p()};h.signIn=function(){if(this.authMode===l.AUTH_MODE_ANONYMOUS)return Promise.reject(new B("portal:invalid-auth-mode",
`Current "authMode"' is "${this.authMode}"`));if("failed"===this.loadStatus)return Promise.reject(this.loadError);const a=e=>Promise.resolve().then(()=>{if("not-loaded"===this.loadStatus)return e||(this.authMode="immediate"),this.load().then(()=>null);if("loading"===this.loadStatus)return this.load().then(()=>{if(this.credential)return null;this.credential=e;return this.fetchSelf("immediate")});if(this.user&&this.credential===e)return null;this.credential=e;return this.fetchSelf("immediate")}).then(f=>
{f&&(this.sourceJSON=f,this.read(f))});return z.id?z.id.getCredential(this.restUrl).then(e=>a(e)):a(this.credential)};h.normalizeUrl=function(a){const e=this.credential&&this.credential.token;return this._normalizeSSL(e?a+(a.includes("?")?"\x26":"?")+"token\x3d"+e:a)};h.requestToTypedArray=function(a,e,f){return this.request(a,e).then(g=>{const k=l._resultsToTypedArray(f,{portal:this},g);return Promise.all(k.map(p=>"function"===typeof p.when?p.when():g)).then(()=>k,()=>k)})};h.request=function(a,
e={}){const f={f:"json",...e.query},{authMode:g=this.authMode===l.AUTH_MODE_ANONYMOUS?"anonymous":"auto",body:k=null,cacheBust:p=!1,method:n="auto",responseType:r="json",signal:t}=e;e={authMode:g,body:k,cacheBust:p,method:n,query:f,responseType:r,timeout:0,signal:t};return H(this._normalizeSSL(a),e).then(P=>P.data)};h.toJSON=function(){throw new B("internal:not-yet-implemented","Portal.toJSON is not yet implemented");};m.fromJSON=function(a){if(!a)return null;if(a.declaredClass)throw Error("JSON object is already hydrated");
return new l({sourceJSON:a})};h._getHelperService=function(a){const e=this.helperServices&&this.helperServices[a];if(!e)throw new B("portal:service-not-found",`The \`helperServices\` do not include an entry named "${a}"`);return e};h._normalizeSSL=function(a){return a.replace(/^http:/i,"https:").replace(":7080",":7443")};h._readBasemap=function(a){return a?(a=E.fromJSON(a),a.portalItem={portal:this},a):null};m._resultsToTypedArray=function(a,e,f,g){let k=[];if(f){const p=F.isSome(g)?g.signal:null;
k=f.listings||f.notifications||f.userInvitations||f.tags||f.items||f.groups||f.comments||f.provisions||f.results||f.relatedItems||f;if(a||e)k=k.map(n=>{n=Object.assign(a?a.fromJSON(n):n,e);"function"===typeof n.load&&n.load(p);return n})}else k=[];return k};A._createClass(m,[{key:"extraQuery",get:function(){const a=!(this.user&&this.user.orgId)||this.canSearchPublic;return this.id&&!a?` AND orgid:${this.id}`:null}},{key:"isOrganization",get:function(){return!!this.access}},{key:"itemPageUrl",get:function(){return this.url?
`${this.url}/home/item.html`:null}},{key:"restUrl",get:function(){let a=this.url;if(a){const e=a.indexOf("/sharing");a=0<e?a.substring(0,e):this.url.replace(/\/+$/,"");a+="/sharing/rest"}return a}},{key:"thumbnailUrl",get:function(){const a=this.restUrl,e=this.thumbnail;return a&&e?this._normalizeSSL(a+"/portals/self/resources/"+e):null}}]);return m}(b.JSONSupportMixin(I));b.AUTH_MODE_ANONYMOUS="anonymous";b.AUTH_MODE_AUTO="auto";b.AUTH_MODE_IMMEDIATE="immediate";c.__decorate([d.property()],b.prototype,
"access",void 0);c.__decorate([d.property()],b.prototype,"allSSL",void 0);c.__decorate([d.property()],b.prototype,"authMode",void 0);c.__decorate([d.property()],b.prototype,"authorizedCrossOriginDomains",void 0);c.__decorate([v.reader("authorizedCrossOriginDomains")],b.prototype,"readAuthorizedCrossOriginDomains",null);c.__decorate([d.property()],b.prototype,"basemapGalleryGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"bingKey",void 0);c.__decorate([d.property()],b.prototype,"canListApps",
void 0);c.__decorate([d.property()],b.prototype,"canListData",void 0);c.__decorate([d.property()],b.prototype,"canListPreProvisionedItems",void 0);c.__decorate([d.property()],b.prototype,"canProvisionDirectPurchase",void 0);c.__decorate([d.property()],b.prototype,"canSearchPublic",void 0);c.__decorate([d.property()],b.prototype,"canShareBingPublic",void 0);c.__decorate([d.property()],b.prototype,"canSharePublic",void 0);c.__decorate([d.property()],b.prototype,"canSignInArcGIS",void 0);c.__decorate([d.property()],
b.prototype,"canSignInIDP",void 0);c.__decorate([d.property()],b.prototype,"colorSetsGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"commentsEnabled",void 0);c.__decorate([d.property({type:Date})],b.prototype,"created",void 0);c.__decorate([d.property()],b.prototype,"credential",void 0);c.__decorate([d.property()],b.prototype,"culture",void 0);c.__decorate([d.property()],b.prototype,"currentVersion",void 0);c.__decorate([d.property()],b.prototype,"customBaseUrl",void 0);c.__decorate([d.property()],
b.prototype,"defaultBasemap",void 0);c.__decorate([v.reader("defaultBasemap")],b.prototype,"readDefaultBasemap",null);c.__decorate([d.property()],b.prototype,"defaultDevBasemap",void 0);c.__decorate([v.reader("defaultDevBasemap")],b.prototype,"readDefaultDevBasemap",null);c.__decorate([d.property({type:L})],b.prototype,"defaultExtent",void 0);c.__decorate([d.property()],b.prototype,"defaultVectorBasemap",void 0);c.__decorate([v.reader("defaultVectorBasemap")],b.prototype,"readDefaultVectorBasemap",
null);c.__decorate([d.property()],b.prototype,"description",void 0);c.__decorate([d.property()],b.prototype,"devBasemapGalleryGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"eueiEnabled",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,"extraQuery",null);c.__decorate([d.property()],b.prototype,"featuredGroups",void 0);c.__decorate([d.property()],b.prototype,"featuredItemsGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"galleryTemplatesGroupQuery",void 0);c.__decorate([d.property()],
b.prototype,"livingAtlasGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"hasCategorySchema",void 0);c.__decorate([d.property()],b.prototype,"helpBase",void 0);c.__decorate([d.property()],b.prototype,"helperServices",void 0);c.__decorate([d.property()],b.prototype,"helpMap",void 0);c.__decorate([d.property()],b.prototype,"homePageFeaturedContent",void 0);c.__decorate([d.property()],b.prototype,"homePageFeaturedContentCount",void 0);c.__decorate([d.property()],b.prototype,"httpPort",void 0);
c.__decorate([d.property()],b.prototype,"httpsPort",void 0);c.__decorate([d.property()],b.prototype,"id",void 0);c.__decorate([d.property()],b.prototype,"ipCntryCode",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,"isOrganization",null);c.__decorate([d.property()],b.prototype,"isPortal",void 0);c.__decorate([d.property()],b.prototype,"isReadOnly",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,"itemPageUrl",null);c.__decorate([d.property()],b.prototype,"layerTemplatesGroupQuery",
void 0);c.__decorate([d.property()],b.prototype,"maxTokenExpirationMinutes",void 0);c.__decorate([d.property({type:Date})],b.prototype,"modified",void 0);c.__decorate([d.property()],b.prototype,"name",void 0);c.__decorate([d.property()],b.prototype,"portalHostname",void 0);c.__decorate([d.property()],b.prototype,"portalMode",void 0);c.__decorate([d.property()],b.prototype,"portalProperties",void 0);c.__decorate([d.property()],b.prototype,"region",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,
"restUrl",null);c.__decorate([d.property()],b.prototype,"rotatorPanels",void 0);c.__decorate([d.property()],b.prototype,"showHomePageDescription",void 0);c.__decorate([d.property()],b.prototype,"sourceJSON",void 0);c.__decorate([d.property()],b.prototype,"staticImagesUrl",void 0);c.__decorate([d.property({json:{name:"2DStylesGroupQuery"}})],b.prototype,"stylesGroupQuery2d",void 0);c.__decorate([d.property({json:{name:"stylesGroupQuery"}})],b.prototype,"stylesGroupQuery3d",void 0);c.__decorate([d.property()],
b.prototype,"supportsHostedServices",void 0);c.__decorate([d.property()],b.prototype,"symbolSetsGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"templatesGroupQuery",void 0);c.__decorate([d.property()],b.prototype,"thumbnail",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,"thumbnailUrl",null);c.__decorate([d.property()],b.prototype,"units",void 0);c.__decorate([d.property()],b.prototype,"url",void 0);c.__decorate([d.property()],b.prototype,"urlKey",void 0);c.__decorate([v.reader("urlKey")],
b.prototype,"readUrlKey",null);c.__decorate([d.property()],b.prototype,"user",void 0);c.__decorate([v.reader("user")],b.prototype,"readUser",null);c.__decorate([d.property()],b.prototype,"useStandardizedQuery",void 0);c.__decorate([d.property()],b.prototype,"useVectorBasemaps",void 0);c.__decorate([d.property()],b.prototype,"vectorBasemapGalleryGroupQuery",void 0);return b=l=c.__decorate([K.subclass("esri.portal.Portal")],b)});