// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../geometry/support/aaBoundingRect ./interfaces ../webgl-engine/lib/basicInterfaces ../webgl-engine/lib/LocalOriginFactory".split(" "),function(f,m,g,b,l,n){f.OverlaySource=void 0;(function(c){c[c.None=0]="None";c[c.ColorAndWater=1]="ColorAndWater";c[c.Highlight=2]="Highlight";c[c.Occluded=3]="Occluded";c[c.ObjectAndLayerIdColor=4]="ObjectAndLayerIdColor"})(f.OverlaySource||(f.OverlaySource={}));let q=function(){function c(a,d){this.index=
a;this.renderTargets=d;this._extent=g.create();this.resolution=0;this.renderLocalOrigin=n.fromValues(0,0,0,"O");this.mapUnitsPerPixel=this.pixelRatio=1;this.canvasGeometries=new p;this.hasTargetWithoutRasterImage=this.hasDrapedRasterSource=this.hasDrapedFeatureSource=!1;this.index=a;this.validTargets=Array(d.renderTargets.length).fill(!1)}var e=c.prototype;e.getValidTexture=function(a){return this.validTargets[a]?this.renderTargets.getTarget(a).getTexture():null};e.getColorTexture=function(a){return(a=
a===f.OverlaySource.ColorAndWater?this.renderTargets.getTarget(b.RenderTargetType.Color):a===f.OverlaySource.Highlight?this.renderTargets.getTarget(b.RenderTargetType.Highlight):a===f.OverlaySource.ObjectAndLayerIdColor?this.renderTargets.getTarget(b.RenderTargetType.ObjectAndLayerIdColor):this.renderTargets.getTarget(b.RenderTargetType.Occluded))?a.getTexture():null};e.getColorTextureNoRasterImage=function(){return this._needsColorWithoutRasterImage?this.getValidTexture(b.RenderTargetType.ColorNoRasterImage):
this.hasDrapedFeatureSource?this.getValidTexture(b.RenderTargetType.Color):null};e.getNormalTexture=function(a){return(a=a===f.OverlaySource.ColorAndWater?this.renderTargets.getTarget(b.RenderTargetType.Water):null)?a.getTexture():null};e.draw=function(a,d){const h=this.computeRenderTargetValidityBitfield();for(const k of this.renderTargets.renderTargets)this.validTargets[k.type]=k.type!==b.RenderTargetType.ColorNoRasterImage||this._needsColorWithoutRasterImage?a.drawTarget(this,k,d):!1;a=this.computeRenderTargetValidityBitfield();
return h^a?l.ValidationState.CHANGED:l.ValidationState.UNCHANGED};e.computeRenderTargetValidityBitfield=function(){const a=this.validTargets;return+a[b.RenderTargetType.Color]|+a[b.RenderTargetType.ColorNoRasterImage]<<1|+a[b.RenderTargetType.Highlight]<<2|+a[b.RenderTargetType.Water]<<3|+a[b.RenderTargetType.Occluded]<<4};e.setupGeometryViewsCyclical=function(a){this.setupGeometryViewsDirect();var d=.001*a.range;if(this._extent[0]-d<=a.min){const h=this.canvasGeometries.extents[this.canvasGeometries.numViews++];
g.offset(this._extent,a.range,0,h)}this._extent[2]+d>=a.max&&(d=this.canvasGeometries.extents[this.canvasGeometries.numViews++],g.offset(this._extent,-a.range,0,d))};e.setupGeometryViewsDirect=function(){this.canvasGeometries.numViews=1;g.copy(this.canvasGeometries.extents[0],this._extent)};e.hasSomeSizedView=function(){for(let a=0;a<this.canvasGeometries.numViews;a++){const d=this.canvasGeometries.extents[a];if(d[0]!==d[2]&&d[1]!==d[3])return!0}return!1};e.applyViewport=function(a){a.setViewport(this.index===
b.OverlayIndex.INNER?0:this.resolution,0,this.resolution,this.resolution)};m._createClass(c,[{key:"extent",get:function(){return this._extent}},{key:"_needsColorWithoutRasterImage",get:function(){return this.hasDrapedRasterSource&&this.hasDrapedFeatureSource&&this.hasTargetWithoutRasterImage}}]);return c}(),p=function(){this.extents=[g.create(),g.create(),g.create()];this.numViews=0};f.Overlay=q;Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});