// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Color ../../../core/Accessor ../../../core/maybe ../../../core/ObjectPool ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../chunks/mat4f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/vec4f64 ../../../geometry/support/aaBoundingBox ../../../geometry/support/buffer/BufferView ../../ViewingMode ./interfaces ./LayerClass ./Overlay ./OverlayRenderer ./PatchGeometry ./PatchRenderData ./RenderOrder ./terrainUtils ./TileRenderer ./TileUpdate ./tileUtils ../webgl-engine/collections/Component/ComponentIntersectionData ../webgl-engine/core/shaderLibrary/ShaderOutput ../webgl-engine/core/shaderLibrary/terrain/Overlay.glsl ../../../chunks/Terrain.glsl ../webgl-engine/core/shaderLibrary/terrain/TileBlendInput ../webgl-engine/lib/Attribute ../webgl-engine/lib/basicInterfaces ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/Intersector ../webgl-engine/lib/IntersectorInterfaces ../webgl-engine/lib/Material ../webgl-engine/lib/RenderSlot ../webgl-engine/lib/screenSizePerspectiveUtils ../webgl-engine/lib/VertexAttribute ../webgl-engine/lib/verticalOffsetUtils ../webgl-engine/materials/DrawParameters ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/shaders/TerrainTechnique ../webgl-engine/shaders/TerrainTechniqueConfiguration ../../webgl/enums".split(" "),
function(f,Z,q,ka,la,h,ma,r,Ka,La,na,oa,M,z,pa,aa,qa,ra,R,sa,A,ba,ta,ua,ca,va,wa,N,S,da,k,T,xa,O,ya,U,za,Aa,P,ea,B,Ba,Ca,fa,ha,ia,Da,Ea,V){const W=aa.create();f.TransparencyMode=void 0;(function(t){t[t.Opaque=0]="Opaque";t[t.Semitransparent=1]="Semitransparent";t[t.TransparentWithDraped=2]="TransparentWithDraped";t[t.Empty=3]="Empty"})(f.TransparencyMode||(f.TransparencyMode={}));f.TerrainRenderer=function(t){function Q(a){a=t.call(this,a)||this;a.type=P.IntersectorType.TERRAIN;a.isGround=!0;a._tileSize=
256;a._techniqueConfiguration=new Ea.TerrainTechniqueConfiguration;a._passParameters=new xa.TerrainPassParameters;a._rctx=null;a._renderDataPool=new ma(ua.PatchRenderData);a._patchGroups=new Map;a._patchGroupsDirty=!0;a._patchSortingDirty=!0;a._tileIterator=new S.IteratorPreorder;a._highestVisibleLODTile=null;a._visible=!0;a._transparencyState=f.TransparencyMode.Opaque;a._velvetOverground=!0;a._castShadows=!0;a._emptyTex=null;a._tileRenderer=null;a._stencilEnabledLayerExtents=[];a._numTilesRendered=
0;a._numTilesCulled=0;a._numOriginsRendered=0;a.needsHighlight=!1;a.renderOccludedFlags=ea.RenderOccludedFlag.Occlude;return a}Z._inheritsLoose(Q,t);var d=Q.prototype;d.initialize=function(){this._stage.addRenderPlugin([B.RenderSlot.OPAQUE_TERRAIN,B.RenderSlot.TRANSPARENT_TERRAIN,B.RenderSlot.OCCLUDED_TERRAIN],this)};d.destroy=function(){this._stage.removeRenderPlugin(this);ta.clearCaches()};d.setDebugScreenSizePerspective=function(a){this._techniqueConfiguration.screenSizePerspective!==a&&(this._techniqueConfiguration.screenSizePerspective=
a,this.setNeedsRender())};d.setRootTiles=function(a){this._rootTiles=a;this.setDirty()};d.setNeedsHighlight=function(a){this.needsHighlight=a;this.setNeedsRender()};d.setRenderOccludedOverlay=function(a){this.renderOccludedFlags=a?ba.overlayRenderOccludedFlag:ea.RenderOccludedFlag.Occlude;this.setNeedsRender()};d.setStencilEnabledLayerExtents=function(a){this._stencilEnabledLayerExtents=a;this._setSortingDirty()};d.setTileSize=function(a){this._tileSize=a;h.isSome(this._tileRenderer)&&(this._tileRenderer.tileSize=
a);this.setDirty()};d._prepareTileForLoading=function(a){a.renderData||(a.renderData=this._renderDataPool.acquire(),a.renderData.init(a),a.renderData.localOrigin=this._getLocalOriginOfTile(a))};d.loadTile=function(a){this._prepareTileForLoading(a);this.updateTileGeometryState(a);this.updateTileTexture(a,N.TileUpdate.TEXTURE_FADING)};d.updateTileTexture=function(a,b){h.isSome(this._tileRenderer)&&(this._tileRenderer.updateTileTexture(a,b===N.TileUpdate.TEXTURE_FADING?R.TextureUpdate.FADING:R.TextureUpdate.UNFADED),
this.setNeedsRender(),a.resetPendingUpdate(b))};d.updateTileGeometryState=function(a){for(const b of a.layerInfo[sa.LayerClass.ELEVATION])b.pendingUpdates&=~N.TileUpdate.GEOMETRY;a.resetPendingUpdate(N.TileUpdate.GEOMETRY);(a=a.renderData.updateGeometryState())&&this.setDirty();return a};d.updateGeometryIfNeeded=function(a){a.isLoaded&&a.renderData.updateGeometryIfNeeded(this._rctx)};d.unloadTile=function(a){const b=a.renderData;b&&(b.releaseGeometry(),this._renderDataPool.release(b),b.clear(),a.renderData=
null,a.setMemoryDirty(),this.setDirty())};d._getLocalOriginOfTile=function(a){const b=Math.max(0,7*Math.floor((a.level-3)/7));if(this._isGlobal&&0===b)return z.ZEROS;for(;a.parent&&a.level>b;)a=a.parent;return a.centerAtSeaLevel};d.setVisibility=function(a){this._visible=a;this.setDirty()};d.getStats=function(){return{numTilesRendered:this._numTilesRendered,numTilesCulled:this._numTilesCulled,numOriginsRendered:this._numOriginsRendered}};d.setDirty=function(a=U.RenderRequestType.UPDATE){this._patchGroupsDirty=
!0;this._context.requestRender(a)};d._setSortingDirty=function(a=U.RenderRequestType.UPDATE){this._patchSortingDirty=!0;this._context.requestRender(a)};d.setNeedsRender=function(a=U.RenderRequestType.UPDATE){this._context.requestRender(a)};d.initializeRenderContext=function(a){this._context=a;this._rctx=a.renderContext.rctx;this._techniqueRepository=a.techniqueRepository;this._tileRenderer=new wa.TileRenderer(this._rctx,this._tileSize,this._techniqueRepository);this.updateTileBackground();this._emptyTex=
za.createEmptyTexture(this._rctx)};d.uninitializeRenderContext=function(){this._emptyTex=h.disposeMaybe(this._emptyTex);this._tileRenderer=h.disposeMaybe(this._tileRenderer)};d.intersect=function(a,b,c,e){if(!(!this._rootTiles||a.options.selectOpaqueTerrainOnly&&a.options.selectionMode&&this.transparency!==f.TransparencyMode.Opaque)){var g=Fa,u=Ga;M.subtract(g,e,c);M.set(u,1/g[0],1/g[1],1/g[2]);var l=a.results.min,n=a.results.max,w=a.results.ground,x=a.options.store===P.StoreResults.MIN,G=!!a.results.ground.target,
v=fa.getVerticalOffsetTerrain(a.verticalOffset),F=a.tolerance,H,X=x&&h.isSome(l.dist)?l.dist:Infinity,Ja=C=>{var D=C.renderData;if(D?.vao){var m=D.geometryInfo;aa.set(W,m.boundingBox);var E=D.localOrigin;h.isSome(v)&&(v.localOrigin=E,v.applyToAabb(W));I[0]=c[0]-E[0];I[1]=c[1]-E[1];I[2]=c[2]-E[2];if(ia.intersectAabbInvDirBefore(W,I,u,F,X)){var J=(p,y,Ha)=>{p.set(this.type,C,y,Ha,oa.IDENTITY);X=x&&h.isSome(l.dist)?l.dist:Infinity};D=(p,y)=>{h.isSome(y)&&0<=p&&(a.options.backfacesTerrain||0>M.dot(y,
g))&&(a.options.invisibleTerrain||!a.options.selectionMode||null==b||b(c,e,p))&&((null==w.dist||p<w.dist)&&J(w,p,y),a.options.isFiltered||(a.options.store===P.StoreResults.ALL&&(h.isNone(H)?(H=Aa.newIntersectorResult(a.ray),J(H,p,y),a.results.all.push(H)):p<H.dist&&J(H,p,y)),(null==l.dist||p<l.dist)&&J(l,p,y),a.options.store!==P.StoreResults.MIN&&(null==n.dist||p>n.dist)&&J(n,p,y)))};var Y=Ia;M.subtract(Y,e,E);E=m.indices;var K=m.vertexAttributes,L=K.getField(Ca.VertexAttribute.POSITION,qa.BufferViewVec3f);
K=new ya.Attribute(L.typedBuffer,3,!1,K.stride/4);m=m.indexCount/3;h.isNone(v)&&m>da.componentMinimalSizeForIntersectionData?(L=C.renderData,h.isNone(L.intersectionData)&&(L.intersectionData=new da.ComponentIntersectionData(E,0,m,K)),L.intersectionData.intersectRay({r0:I,r1:Y},D)):ia.intersectTriangles(I,Y,0,m,E,K,null,v,D)}}},ja=this._rootTiles;h.isSome(ja)&&(()=>{const C=this._tileIterator;C.reset(ja);const D=a.options.invisibleTerrain;for(let m=C.next();m;m=C.next())!(m.visible||D&&m.intersectsClippingArea)||
!h.isSome(v)&&!m.intersectsRay(c,g,F,X)||G&&this._useStencilForTile(m)?C.skipSubtree():Ja(m)})()}};d.processScaleRangeQueries=function(a,b){if(!b.done)for(this._updatePatchGroups();a.updating&&!b.done;){a.prepare();for(const c of this._patchGroups.values())for(const e of c)h.isSome(e.renderData?.textureReference)&&a.queriesForTile(e);a.process();b.madeProgress()}};d.prepareTechnique=function(a){if(a.bindParameters.slot===B.RenderSlot.OCCLUDED_TERRAIN){if(0===(a.renderOccludedMask&ba.overlayRenderOccludedFlag))return null}else if(a.bindParameters.slot!==
(this.transparency===f.TransparencyMode.Opaque?B.RenderSlot.OPAQUE_TERRAIN:B.RenderSlot.TRANSPARENT_TERRAIN))return null;switch(a.output){case k.ShaderOutput.Color:if(this.transparency===f.TransparencyMode.Empty)break;this._techniqueConfiguration.hasScreenSpaceReflections=a.bindParameters.ssr.enabled;this._techniqueConfiguration.hasCloudsReflections=h.isSome(a.bindParameters.cloudsFade.data);this._techniqueConfiguration.receiveShadows=a.bindParameters.shadowMap.ready;this._techniqueConfiguration.receiveAmbientOcclusion=
a.bindParameters.ssaoHelper.active;this._techniqueConfiguration.overlayMode=this._overlayRenderer.isEmpty?T.OverlayMode.Disabled:this._overlayRenderer.hasWater?T.OverlayMode.EnabledWithWater:T.OverlayMode.Enabled;return this._updateTechnique(k.ShaderOutput.Color,a.bindParameters.slot===B.RenderSlot.OCCLUDED_TERRAIN);case k.ShaderOutput.Shadow:case k.ShaderOutput.ShadowExcludeHighlight:if(this._castShadows&&1===a.bindParameters.lighting.globalFactor)return this._techniqueConfiguration.receiveShadows=
this._techniqueConfiguration.receiveAmbientOcclusion=!1,this._updateTechnique(k.ShaderOutput.Shadow,!1);break;case k.ShaderOutput.Depth:if(this.transparency===f.TransparencyMode.Empty)break;this._techniqueConfiguration.receiveShadows=this._techniqueConfiguration.receiveAmbientOcclusion=!1;return this._updateTechnique(k.ShaderOutput.Depth,!1);case k.ShaderOutput.Normal:if(this.transparency===f.TransparencyMode.Empty)break;this._techniqueConfiguration.receiveShadows=this._techniqueConfiguration.receiveAmbientOcclusion=
!1;return this._updateTechnique(k.ShaderOutput.Normal,!1);case k.ShaderOutput.ObjectAndLayerIdColor:return this.transparency===f.TransparencyMode.Empty?null:this._updateTechnique(k.ShaderOutput.ObjectAndLayerIdColor,!1);case k.ShaderOutput.Highlight:if(this.transparency!==f.TransparencyMode.Empty&&this.needsHighlight)return this._techniqueConfiguration.receiveShadows=this._techniqueConfiguration.receiveAmbientOcclusion=!1,this._updateTechnique(k.ShaderOutput.Highlight,!1)}return null};d.render=function(a,
b){const c=1===a.bindParameters.lighting.globalFactor;this._updatePatchGroups();b.useStencil=!1;switch(a.output){case k.ShaderOutput.Color:const e=a.bindParameters.slot===B.RenderSlot.OCCLUDED_TERRAIN?A.OverlaySource.Occluded:A.OverlaySource.ColorAndWater;this.transparency===f.TransparencyMode.Opaque?this._renderMaterialPass(a,b,e):a.offscreenRenderingHelper.renderToTargets(()=>this._renderMaterialPass(a,b,e),a.offscreenRenderingHelper.tmpColor,a.offscreenRenderingHelper.mainDepth,[0,0,0,0]);break;
case k.ShaderOutput.Depth:case k.ShaderOutput.Normal:this._renderAuxiliaryPass(a,b,A.OverlaySource.None);break;case k.ShaderOutput.Highlight:this.needsHighlight&&this._renderAuxiliaryPass(a,b,A.OverlaySource.Highlight);break;case k.ShaderOutput.Shadow:case k.ShaderOutput.ShadowExcludeHighlight:this._castShadows&&c&&this._renderAuxiliaryPass(a,b,A.OverlaySource.None);break;case k.ShaderOutput.ObjectAndLayerIdColor:this._renderAuxiliaryPass(a,b,A.OverlaySource.ObjectAndLayerIdColor)}};d._renderMaterialPass=
function(a,b,c){const {rctx:e}=a;this._passParameters.overlaySource=c;e.bindTechnique(b,this._passParameters,a.bindParameters);this._numOriginsRendered=this._numTilesCulled=this._numTilesRendered=0;this._renderPatchGroups(a,b,c)};d._renderAuxiliaryPass=function(a,b,c){const e=a.rctx;this._passParameters.overlaySource=c;e.bindTechnique(b,this._passParameters,a.bindParameters);this._renderPatchGroupsAuxiliary(a,b,c)};d.updateTileBackground=function(a=null){if(!h.isNone(this._tileRenderer)){var b=this._tileRenderer,
c=null;h.isSome(a)&&(a=ka.toUnitRGBA(a),c=z.fromValues(a[0]||0,a[1]||0,a[2]||0));b.setBackground(c);this._allTiles.forAll(e=>b.updateTileTexture(e,R.TextureUpdate.FADING));this._techniqueConfiguration.tileBlendInput=b.backgroundIsGrid?O.TileBlendInput.GridComposite:h.isSome(b.backgroundColor)?O.TileBlendInput.ColorComposite:O.TileBlendInput.LayerOnly;this.setNeedsRender()}};d._updatePatchGroups=function(){this._patchGroupsDirty&&(this._highestVisibleLODTile=null,this._rebuildPatchGroups(),this._patchGroupsDirty=
!1,this._patchSortingDirty=!0);if(this._patchSortingDirty&&this.renderOrder!==ca.RenderOrder.NONE){const a=Array.from(this._patchGroups.values()),b=this._stencilEnabledLayerExtents;for(const c of a)S.sortTiles(this.renderOrder,c,b);a.sort((c,e)=>S.compareTiles(c[0],e[0],this.renderOrder));this._patchGroups=new Map(a.map(c=>[c[0].renderData.localOrigin,c]));this._patchSortingDirty=!1}};d._rebuildPatchGroups=function(){const a=this._rootTiles;if(!h.isNone(a)){a[0]?.surface.checkAllTilesWaterproofness();
this._patchGroups.clear();for(const b of a)this._rebuildPatchGroupsForRootTile(b)}};d._rebuildPatchGroupsForRootTile=function(a){const b=this._tileIterator;for(b.resetOne(a);!b.done;){a=b.next();var c=a.renderData;if(!c){this._numTilesCulled++;continue}if(!a.visible){this._numTilesCulled++;b.skipSubtree();continue}c=c.localOrigin;let e=this._patchGroups.get(c);e||(e=[],this._patchGroups.set(c,e));e.push(a);if(!this._highestVisibleLODTile||a.vlevel>this._highestVisibleLODTile.vlevel)this._highestVisibleLODTile=
a;b.skipSubtree()}};d._useStencilForTile=function(a){for(const b of this._stencilEnabledLayerExtents)if(a.intersectsExtent(b))return!0;return!1};d._renderPatchGroupsAuxiliary=function(a,b,c){const e=0<this._stencilEnabledLayerExtents.length;this._patchGroups.forEach(g=>{b.program.bindDraw(new ha.DrawParameters(g[0].renderData.localOrigin),a.bindParameters,this._passParameters);for(let u=0;u<g.length;u++)this._renderPatch(a,b,g[u],V.PrimitiveType.TRIANGLES,e,c)});a.rctx.bindVAO(null)};d._renderPatchGroups=
function(a,b,c){var e=a.bindParameters.camera;const g=b.program;this._techniqueConfiguration.screenSizePerspective&&this.pointsOfInterest&&Ba.getSettings(this._stage.viewingMode,this._ellipsoidRadius).update({distance:this.pointsOfInterest.centerOnSurfaceFrequent.distance,fovY:e.fovY});e=0<this._stencilEnabledLayerExtents.length;const u=c===A.OverlaySource.Occluded;u&&(g.bindTexture("tex",this._emptyTex),g.setUniform3fv("textureOpacities",z.ZEROS),g.setUniform4fv("texOffsetAndScale",pa.ZEROS));var l=
h.isSome(this._tileRenderer)&&h.isSome(this._tileRenderer.backgroundColor)?this._tileRenderer.backgroundColor:z.ZEROS;this._techniqueConfiguration.tileBlendInput===O.TileBlendInput.ColorComposite&&g.setUniform3fv("backgroundColor",l);l=this.wireframe?V.PrimitiveType.LINES:V.PrimitiveType.TRIANGLES;this._techniqueConfiguration.textureFadingEnabled&&g.bindTexture("texNext",this._emptyTex);var n=this._patchGroups;for(const w of n.values()){b.program.bindDraw(new ha.DrawParameters(w[0].renderData.localOrigin),
a.bindParameters,this._passParameters);this._numOriginsRendered++;for(const x of w){n=x.renderData;const G=n.textureReference;if(!h.isNone(G)){if(!u){g.setUniform4fv("texOffsetAndScale",G.offsetAndScale);g.bindTexture("tex",G.texture.texture);const v=n.textureFadeFactor,F=1>v?n.nextTextureReference:null;this._techniqueConfiguration.textureFadingEnabled&&h.isSome(F)&&1>v?(g.setUniform1f("fadeFactor",v),g.setUniform4fv("nextTexOffsetAndScale",F.offsetAndScale),g.setUniform3fv("nextTexOpacities",F.opacities),
g.bindTexture("texNext",F.texture.texture)):g.setUniform1f("fadeFactor",1);n.textureIsFading&&this.setNeedsRender();g.setUniform3fv("textureOpacities",G.opacities)}this._renderPatch(a,b,x,l,e,c);x.renderOrder=this._numTilesRendered;this._numTilesRendered++}}}a.rctx.bindVAO(null)};d._renderPatch=function(a,b,c,e,g,u){const l=c.renderData,n=l.vao,w=n.indexBuffer;if(h.isNone(w))va.ENABLE_TERRAIN_INTERNAL_CHECKS&&console.error("Rendered tile with no indices: ",c.lij," : ",l);else{var x=b.program;u===
A.OverlaySource.None||this._overlayRenderer.isEmpty||this._bindOverlayPatchData(x,l.overlay);g&&(b.useStencil=this._useStencilForTile(c),b.bindPipelineState(a.rctx,a.bindParameters.slot));b=l.geometryInfo.indexCount;a.rctx.bindVAO(n);x.assertCompatibleVertexAttributeLocations(n);a.rctx.drawElements(e,b,w.indexType,0)}};d._bindOverlayPatchData=function(a,b){a.setUniform4fv("overlayTexOffset",b.offsets);a.setUniform4fv("overlayTexScale",b.scales)};d._updateTechnique=function(a,b){this._techniqueConfiguration.output=
a;a===k.ShaderOutput.Color&&(this._techniqueConfiguration.atmosphere=this._isGlobal&&this._velvetOverground);this._techniqueConfiguration.renderOccluded=b;this._techniqueConfiguration.stencilEnabled=!1;return this._shaderTechnique=this._techniqueRepository.releaseAndAcquire(Da.TerrainTechnique,this._techniqueConfiguration,this._shaderTechnique)};Z._createClass(Q,[{key:"_isGlobal",get:function(){return this._stage.viewingMode===ra.ViewingMode.Global}},{key:"shading",get:function(){return this._techniqueConfiguration.shading},
set:function(a){this._techniqueConfiguration.shading=a}},{key:"canRender",get:function(){return this._visible&&!!this._rootTiles&&!this.renderingDisabled}},{key:"renderingDisabled",set:function(a){this._set("renderingDisabled",!!a);this.setDirty()}},{key:"transparency",get:function(){return this._transparencyState},set:function(a){this._transparencyState!==a&&(this._techniqueConfiguration.invisible=a===f.TransparencyMode.TransparentWithDraped||a===f.TransparencyMode.Empty,this._transparencyState=
a,this.setNeedsRender())}},{key:"needsLinearDepth",get:function(){return this._overlayRenderer.hasWater}},{key:"renderPatchBorders",get:function(){return!!this._techniqueConfiguration.tileBorders},set:function(a){this._techniqueConfiguration.tileBorders!==a&&(this._techniqueConfiguration.tileBorders=a,this.setNeedsRender(),this.notifyChange("renderPatchBorders"))}},{key:"visualizeNormals",get:function(){return!!this._techniqueConfiguration.visualizeNormals},set:function(a){this._techniqueConfiguration.visualizeNormals!==
a&&(this._techniqueConfiguration.visualizeNormals=a,this.setNeedsRender(),this.notifyChange("visualizeNormals"))}},{key:"cullBackFaces",get:function(){return this._techniqueConfiguration.backfaceCullingEnabled},set:function(a){this._techniqueConfiguration.backfaceCullingEnabled!==a&&(this._techniqueConfiguration.backfaceCullingEnabled=a,this.notifyChange("cullBackFaces"),this.setNeedsRender())}},{key:"renderOrder",set:function(a){this._set("renderOrder",a);this._setSortingDirty()}},{key:"velvetOverground",
set:function(a){this._velvetOverground!==a&&(this._velvetOverground=a,this.setNeedsRender())}},{key:"layerUid",get:function(){return fa.TERRAIN_ID}},{key:"slicePlaneEnabled",get:function(){return this._techniqueConfiguration.hasSlicePlane},set:function(a){this._techniqueConfiguration.hasSlicePlane!==a&&(this._techniqueConfiguration.hasSlicePlane=a,this.setNeedsRender())}},{key:"textureFadingEnabled",set:function(a){this._techniqueConfiguration.textureFadingEnabled!==a&&(this._techniqueConfiguration.textureFadingEnabled=
a,this.setNeedsRender())}},{key:"pbrMode",set:function(a){this._techniqueConfiguration.pbrMode!==a&&(this._techniqueConfiguration.pbrMode=a,this.setNeedsRender())}},{key:"wireframe",set:function(a){this._get("wireframe")!==a&&(this._set("wireframe",a),this.setNeedsRender())}},{key:"test",get:function(){return{tileRenderer:this._tileRenderer}}}]);return Q}(la);q.__decorate([r.property({constructOnly:!0})],f.TerrainRenderer.prototype,"_overlayRenderer",void 0);q.__decorate([r.property({constructOnly:!0})],
f.TerrainRenderer.prototype,"_stage",void 0);q.__decorate([r.property({readOnly:!0})],f.TerrainRenderer.prototype,"_isGlobal",null);q.__decorate([r.property({constructOnly:!0})],f.TerrainRenderer.prototype,"_allTiles",void 0);q.__decorate([r.property({constructOnly:!0})],f.TerrainRenderer.prototype,"_ellipsoidRadius",void 0);q.__decorate([r.property({value:!1})],f.TerrainRenderer.prototype,"renderingDisabled",null);q.__decorate([r.property()],f.TerrainRenderer.prototype,"renderPatchBorders",null);
q.__decorate([r.property()],f.TerrainRenderer.prototype,"visualizeNormals",null);q.__decorate([r.property()],f.TerrainRenderer.prototype,"cullBackFaces",null);q.__decorate([r.property({value:ca.RenderOrder.FRONT_TO_BACK})],f.TerrainRenderer.prototype,"renderOrder",null);q.__decorate([r.property()],f.TerrainRenderer.prototype,"wireframe",null);f.TerrainRenderer=q.__decorate([na.subclass("esri.views.3d.terrain.TerrainRenderer")],f.TerrainRenderer);const Fa=z.create(),Ga=z.create(),I=z.create(),Ia=z.create();
Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});