// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/mathUtils ../../../core/maybe ../../../chunks/vec2 ../../../chunks/vec2f64 ../../../layers/support/layerUtils ../support/StreamDataLoader ./BlendLayersTechnique ./interfaces ./LayerClass ./terrainUtils ./TextureFader ./TextureReference ./TileCompositor ./TileTexture ./TileUpdate ../webgl-engine/core/shaderLibrary/output/BlendOptions ../webgl-engine/core/shaderLibrary/terrain/TileBackground.glsl ../webgl-engine/lib/glUtil3D ../../webgl/context-util ../../webgl/enums ../../webgl/Texture".split(" "),
function(L,fa,ha,m,R,S,D,ia,ja,T,H,B,M,N,ka,E,I,U,u,V,la,z,F){function O(e,d){p.layerIndex=d;const a=e.layerInfo[H.LayerClass.MAP][d];if(m.isSome(a.data))return R.set(p.offset,0,0),p.tile=e,p.scale=1,p.sourceLod=e.lij,p.sourceLayerInfo=a,p;e=a.upsampleInfo;return m.isSome(e)?(d=e.tile.layerInfo[H.LayerClass.MAP][d],p.tile=e.tile,R.copy(p.offset,e.offset),p.scale=e.scale,p.sourceLod=e.tile.lij,p.sourceLayerInfo=d,p):null}function W(e){let d="normal"!==e.blendMode;D.isGroupLayer(e.parent)&&(d=W(e.parent)||
d);return d}function X(e,d){D.isGroupLayer(e.parent)&&X(e.parent,d);const a=e.get("uid");if(m.isSome(a)&&""!==a){const b=J.get(a);b?b.start=d:J.set(a,new Y(d,d,e.blendMode,e.opacity))}}let Y=function(e,d,a,b){this.start=e;this.end=d;this.blendMode=a;this.opacity=b},ma=function(){function e(a,b,c){this._rctx=a;this.tileSize=b;this._techniqueRepository=c;this._passParameters=new ja.BlendLayersPassParameters;this._backgroundColor=this._backgroundTexture=null;this._backgroundDirty=!1;this._blackTex=null;
this._maxAnisotropy=this._rctx.parameters.maxMaxAnisotropy;this._composition=new ka.TileCompositor(this._rctx,this._techniqueRepository);this._blackTex=new E(V.createColorTexture(this._rctx,[0,0,0,1]));this._ensureBackgroundTexture(this.tileSize)}var d=e.prototype;d.dispose=function(){this._composition=m.disposeMaybe(this._composition);this._backgroundTexture=m.releaseMaybe(this._backgroundTexture);this._blackTex=m.releaseMaybe(this._blackTex)};d.updateTileTexture=function(a,b){if(a.renderData){var c=
a.surface,h=c.baseOpacity,n=0,K=0,f=this.tileSize,G=!1,q=c.view.state.contentPixelRatio,A=!1;J.clear();C.length=0;for(var v=a.layerInfo[H.LayerClass.MAP],w=v.length,g=0;g<v.length;g++){const k=c.layerViewByIndex(g,H.LayerClass.MAP);var x=k.layer.opacity;Z[g]=x;const l=k.fullOpacity;aa[g]=l;D.isBaseLayer(k.layer)&&w>=v.length&&(w=g);if(B.isBlendableLayerView(k)){ba[g]=k.layer.blendMode;var t="normal"!==k.layer.blendMode;if(D.isGroupLayer(k.layer.parent)){const y=k.layer.parent.get("uid");m.isSome(y)&&
""!==y&&(t=W(k.layer.parent)||t)}t&&(A=t,G=!1)}if(0!==x||A){if(++K,x=O(a,g))v[g].pendingUpdates&=~(I.TileUpdate.TEXTURE_NOFADING&I.TileUpdate.TEXTURE_FADING),D.isGroupLayer(k.layer.parent)&&(t=k.layer.parent.get("uid"),m.isSome(t)&&""!==t&&X(k.layer.parent,g)),B.isVectorTileLayerView(k)?f=Math.max(f,this.tileSize*q):1===h&&1===l&&(k.isOpaque||this._dataToTexture(x)&&x.sourceLayerInfo.data.descriptor.isOpaque)&&(G=!0),++n}else v[g].pendingUpdates&=~(I.TileUpdate.TEXTURE_NOFADING&I.TileUpdate.TEXTURE_FADING)}this._rctx.type===
la.ContextType.WEBGL1&&(q=f,f=ha.nextHighestPowerOfTwo(q),c=f*f,h=q*q,c===h?f=q:(q=f/2,f=c-h<h-q*q?f:q));c=f/this.tileSize;--g;this._ensureBackgroundTexture(this.tileSize);0===n?this._useBackgroundTexture(a,K):(1!==n||A||!this._useLayerTexture(a,g,w,aa[g]))&&this._composeMapLayers(a,b,g,w,Z,ba,f,c,!G||A,J,A)}};d._ensureBackgroundTexture=function(a){m.isNone(this._backgroundTexture)&&(this._backgroundTexture=this._buildTexture(a),this._backgroundDirty=!0);this._backgroundDirty&&(this._composition.bind(a),
this._passParameters.offset=S.ZEROS,this._passParameters.scale=1,this._passParameters.opacity=1,m.isSome(this.backgroundColor)&&(this._passParameters.backgroundColor=this.backgroundColor),this._composition.drawBackground(this._passParameters,m.isSome(this.backgroundColor)),this._composition.copyFBOToTexture(this._backgroundTexture),this._composition.unbind(),this._backgroundDirty=!1)};d._useBackgroundTexture=function(a,b){let c=M.ActivationTime.Immediate;if(a.surface.view.layerViewManager.updating||
0<b)c=M.ActivationTime.Delayed;b=a.renderData;this._backgroundTexture&&m.isNone(b.textureReference)&&(c=M.ActivationTime.Immediate);b.setTextureReference(m.isSome(this._backgroundTexture)?new N.TextureReference(this._backgroundTexture,T.TextureUpdate.FADING,ca,a.surface.baseOpacity,0,1):null,c)};d._useLayerTexture=function(a,b,c,h){var n=b<c;c=n?1:a.surface.baseOpacity;n=n?a.surface.baseOpacity:1;b=O(a,b);return this._dataToTexture(b)?(a.renderData.setTextureReference(new N.TextureReference(b.sourceLayerInfo.data,
T.TextureUpdate.FADING,b,c,n,h)),!0):!1};d._composeMapLayers=function(a,b,c,h,n,K,f,G,q,A,v){this._composition.ensureBuffer(f);const w=a.surface.baseOpacity;let g=!1,x=z.TextureSamplingMode.LINEAR_MIPMAP_LINEAR,t=!1,k=0;for(let r=c;0<=r;r--){var l=O(a,r);if(!l)continue;if(0===n[r]&&!v)continue;var y=r<h&&1>w&&!g;this._passParameters.baseOpacity=y?w:1;c=1>this._passParameters.baseOpacity?u.BaseOpacityMode.Required:u.BaseOpacityMode.NotRequired;y&&(g=!0);let da=!1;A.forEach(ea=>{ea.start===r&&(C.push(ea),
this._composition.openGroup(f),da=!0)});y=0===k;const P=da?u.BlendLayersOutput.GroupBackgroundComposite:q&&y?this.backgroundIsGrid?u.BlendLayersOutput.GridComposite:u.BlendLayersOutput.ColorComposite:u.BlendLayersOutput.Composite,Q=U.blendModeFromString[K[r]];B.isVectorTileRenderInfo(l)?(this._passParameters.opacity=n[r],t=this._composition.drawVectorData(this._passParameters,P,f,Q,c,l,G,this.tileSize,t)):B.isImageryTileRenderInfo(l)?(this._passParameters.opacity=n[r],this._composition.drawImageryTileData(this._passParameters,
P,f,Q,c,l),this._hasNearestInterpolation(l)&&(x=z.TextureSamplingMode.NEAREST)):this._dataToTexture(l)&&(this._passParameters.texture=l.sourceLayerInfo.data.texture,this._passParameters.offset=l.offset,this._passParameters.scale=l.scale,this._passParameters.opacity=n[r],this._composition.drawRasterData(this._passParameters,P,f,Q,c));for(;0<C.length&&C[C.length-1].end===r;)l=C.pop(),this._passParameters.opacity=l.opacity,this._passParameters.offset=S.ZEROS,this._passParameters.scale=1,this._composition.drawGroup(this._passParameters,
q&&y?this.backgroundIsGrid?u.BlendLayersOutput.GridComposite:u.BlendLayersOutput.ColorComposite:u.BlendLayersOutput.Composite,f,U.blendModeFromString[l.blendMode],c);k++}a=a.renderData;h=a.ensureTexture(f,()=>this._buildTexture(f,x));this._composition.copyFBOToTexture(h);this._composition.unbind();a.setTextureReference(new N.TextureReference(h,b,ca,g?1:w,0,1))};d._hasNearestInterpolation=function(a){a=a.sourceLayerInfo.data;return a.source?"nearest"===a.interpolation:!1};d._dataToTexture=function(a){if(B.isRasterTileRenderInfo(a)){const b=
a.sourceLayerInfo;b.data=this._buildTexture(b.data);a.tile.setMemoryDirty()}return B.isTextureTileRenderInfo(a)};d.setBackground=function(a){this._backgroundColor!==a&&(this._backgroundColor=a,this._backgroundDirty=!0)};d._buildTexture=function(a,b=z.TextureSamplingMode.LINEAR_MIPMAP_LINEAR){if(m.isNone(a))return null;const c={target:z.TextureType.TEXTURE_2D,pixelFormat:z.PixelFormat.RGBA,dataType:z.PixelType.UNSIGNED_BYTE,wrapMode:z.TextureWrapMode.CLAMP_TO_EDGE,samplingMode:b,maxAnisotropy:this._maxAnisotropy,
preMultiplyAlpha:!0,flipped:!0,hasMipmap:!0};b=this._rctx;let h;if("number"===typeof a)c.width=c.height=a,h=new E(new F.Texture(b,c));else if(a instanceof ia.ImageWithType)c.isOpaque=a.isOpaque,h=new E(new F.Texture(b,c,a.image)),a.release();else try{c.width=a.width,c.height=a.height,h=new E(new F.Texture(b,c,a))}catch(n){h=new E(V.createEmptyTexture(b)),console.warn("TileRenderer: failed to execute 'texImage2D', cross-origin image may not be loaded.")}a=b.bindTexture(h.texture,F.Texture.TEXTURE_UNIT_FOR_UPDATES);
h.generateMipmap();b.bindTexture(a,F.Texture.TEXTURE_UNIT_FOR_UPDATES);return h};fa._createClass(e,[{key:"backgroundIsGrid",get:function(){return m.isNone(this._backgroundColor)}},{key:"backgroundColor",get:function(){return this._backgroundColor}},{key:"test",get:function(){return{backgroundTexture:this._backgroundTexture}}}]);return e}();const Z=[],aa=[],ba=[],J=new Map,C=[],p={tile:null,sourceLayerInfo:null,sourceLod:null,offset:[0,0],scale:1,layerIndex:0},ca={offset:[0,0],scale:1};L.GroupInfo=
Y;L.TileRenderer=ma;Object.defineProperty(L,Symbol.toStringTag,{value:"Module"})});