// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define(["exports","../../../chunks/_rollupPluginBabelHelpers","../../../core/maybe","../../../core/PooledArray","./RenderOrder"],function(f,l,h,m,t){function k(a,b){b(a);if(!a.isLeaf)for(const c of a.children)k(c,b)}function n(a,b){a=a.lij;b=b.lij;return a[0]-b[0]||a[1]-b[1]||a[2]-b[2]}function u(a,b){const c=b.screenDepth-a.screenDepth;if(0!==c)return c;a=a.lij;b=b.lij;return a[0]-b[0]||a[1]-b[1]||a[2]-b[2]}function v(a,b){const c=a.screenDepth-b.screenDepth;if(0!==c)return c;a=a.lij;b=b.lij;return a[0]-
b[0]||a[1]-b[1]||a[2]-b[2]}function p(a,b,c){const d=a.screenDepth,e=b.screenDepth;return d<e?-c:d>e?c:n(a,b)}function q(a,b,c,d){const e=r(a,d);d=r(b,d);return e===d?p(a,b,c):a?c:-c}function r(a,b){for(const c of b)if(a.intersectsExtent(c))return!0;return!1}function w(a,b){const c=a.distanceToPOI-b.distanceToPOI;if(0!==c)return c;a=a.lij;b=b.lij;return a[0]-b[0]||a[1]-b[1]||a[2]-b[2]}let x=function(){function a(){this._queue=new m;this.remove=()=>{}}var b=a.prototype;b.resetOne=function(c){this._queue.clear();
this._queue.push(c);this._last=void 0};b.reset=function(c=null){this._queue.clear();h.isSome(c)&&this._queue.pushArray(c);this._last=void 0};b.skipSubtree=function(){this._last=void 0};b.next=function(){const c=this._last?.children;c&&c[0]&&this._queue.pushArray(c);return this._last=this._queue.pop()};l._createClass(a,[{key:"done",get:function(){return 0===this._queue.length&&(!this._last||this._last.isLeaf)}}]);return a}(),y=function(){function a(){this._q=new m}var b=a.prototype;b.reset=function(c){this._q.clear();
if(!h.isNone(c))for(this._q.pushArray(c),c=0;c<this._q.length;++c){const d=this._q.data[c];d.isLeaf||this._q.pushArray(d.children)}};b.next=function(){return this._q.pop()};l._createClass(a,[{key:"done",get:function(){return 0===this._q.length}}]);return a}();f.IteratorPostorder=y;f.IteratorPreorder=x;f.compareTiles=p;f.compareTilesByLij=n;f.compareTilesWithStencil=q;f.computeUpsampleInfo=function(a,b,c){let d=1,e=0,g=0;for(;a!==b;)if(d*=.5,e*=.5,g*=.5,a.lij[2]&1&&(e+=.5),0===(a.lij[1]&1)&&(g+=.5),
a=a.parent,null==a)throw Error("tile was not a descendant of upsampleTile");c.init(b,e,g,d)};f.fallsWithinLayer=function(a,b,c){if(h.isNone(b)||h.isNone(b.fullExtent))return!1;const d=b.fullExtent,e=a.extent;if(c){if(e[0]<d.xmin||e[1]<d.ymin||e[2]>d.xmax||e[3]>d.ymax)return!1}else if(d.xmin>e[2]||d.ymin>e[3]||d.xmax<e[0]||d.ymax<e[1])return!1;a=a.surface.tilingScheme.levels[a.level].scale;c=b.minScale;if(0<c&&a>1.00000001*c)return!1;b=b.maxScale;return 0<b&&a<.99999999*b?!1:!0};f.hasLoadableSiblings=
function(a){for(let b=0;b<a.length;b++){const c=a[b],d=c.parent;if(d)for(let e=0;4>e;e++){const g=d.children[e];if(g&&g!==c)return!0}}return!1};f.sortTiles=function(a,b,c=null){h.isNone(c)||0===c.length?a===t.RenderOrder.BACK_TO_FRONT?b.sort(u):b.sort(v):b.sort((d,e)=>q(d,e,a,c))};f.sortTilesByPOI=function(a,b){const c=a.length;for(let d=0;d<c;++d)a.getItemAt(d).updateDistanceToPOI(b);a.sort(w)};f.tilesAreRelated=function(a,b){if(!a||!b||a[0]===b[0])return!1;const c=a[0]<b[0],d=c?a:b;a=c?b:a;b=1<<
a[0]-d[0];return Math.floor(a[1]/b)===d[1]&&Math.floor(a[2]/b)===d[2]};f.traverseTilesPreorder=function(a,b){if(Array.isArray(a))for(let c=0;c<a.length;c++)k(a[c],b);else k(a,b)};Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});