// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Error ../../../../core/has ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/urlUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../support/source/DataLayerSource ../../../../rest/utils ../../../../rest/query/executeForCount ../../../../rest/query/executeForExtent ../../../../rest/query/executeForIds ../../../../rest/query/executeQueryJSON ../../../../rest/query/executeQueryPBF ../../../../rest/support/FeatureSet ../../../../rest/support/Query".split(" "),
function(m,l,n,k,z,A,r,q,B,p,R,S,C,x,D,E,F,G,H,I,J,K){const y=u=>Object.freeze(Object.defineProperty({__proto__:null,default:u},Symbol.toStringTag,{value:"Module"}));k=function(u){function v(b){b=u.call(this,b)||this;b.dynamicDataSource=null;b.fieldsIndex=null;b.gdbVersion=null;b.infoFor3D=null;b.pbfSupported=!1;b.queryAttachmentsSupported=!1;b.sourceSpatialReference=null;b.url=null;return b}l._inheritsLoose(v,u);var g=v.prototype;g.execute=function(){var b=l._asyncToGenerator(function*(a,c){const e=
yield this.executeJSON(a,c);return this.featureSetFromJSON(a,e,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeJSON=function(){var b=l._asyncToGenerator(function*(a,c){const e=this._normalizeQuery(a);a=null!=a.outStatistics?.[0];const f=A("featurelayer-pbf-statistics");a=!a||f;let d;if(this.pbfSupported&&a)try{d=yield I.executeRawQueryPBF(this.url,e,c)}catch(h){if("query:parsing-pbf"===h.name)this.pbfSupported=!1;else throw h;}this.pbfSupported&&a||(d=yield H.executeRawQueryJSON(this.url,
e,c));this._normalizeFields(d.fields);return d});return function(a,c){return b.apply(this,arguments)}}();g.featureSetFromJSON=function(){var b=l._asyncToGenerator(function*(a,c,e){if(!this._queryIs3DObjectFormat(a)||r.isNone(this.infoFor3D)||!c.assetMaps||!c.features||!c.features.length)return J.fromJSON(c);({meshFeatureSetFromJSON:e}=yield q.whenOrAbort(new Promise((f,d)=>m(["../../../../rest/support/meshFeatureSet"],f,d)),e));return e(a,this.infoFor3D,c)});return function(a,c,e){return b.apply(this,
arguments)}}();g.executeForCount=function(b,a){return E.executeForCount(this.url,this._normalizeQuery(b),a)};g.executeForExtent=function(b,a){return F.executeForExtent(this.url,this._normalizeQuery(b),a)};g.executeForIds=function(b,a){return G.executeForIds(this.url,this._normalizeQuery(b),a)};g.executeRelationshipQuery=function(){var b=l._asyncToGenerator(function*(a,c){const [{default:e},{executeRelationshipQuery:f}]=yield q.whenOrAbort(Promise.all([new Promise((d,h)=>m(["../../../../rest/support/RelationshipQuery"],
t=>d(y(t)),h)),new Promise((d,h)=>m(["../../../../rest/query/executeRelationshipQuery"],d,h))]),c);a=e.from(a);if(this.gdbVersion||this.dynamicDataSource)a=a.clone(),a.gdbVersion=a.gdbVersion||this.gdbVersion,a.dynamicDataSource=a.dynamicDataSource||this.dynamicDataSource;return f(this.url,a,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeRelationshipQueryForCount=function(){var b=l._asyncToGenerator(function*(a,c){const [{default:e},{executeRelationshipQueryForCount:f}]=yield q.whenOrAbort(Promise.all([new Promise((d,
h)=>m(["../../../../rest/support/RelationshipQuery"],t=>d(y(t)),h)),new Promise((d,h)=>m(["../../../../rest/query/executeRelationshipQuery"],d,h))]),c);a=e.from(a);if(this.gdbVersion||this.dynamicDataSource)a=a.clone(),a.gdbVersion=a.gdbVersion||this.gdbVersion,a.dynamicDataSource=a.dynamicDataSource||this.dynamicDataSource;return f(this.url,a,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeAttachmentQuery=function(){var b=l._asyncToGenerator(function*(a,c){const {executeAttachmentQuery:e,
fetchAttachments:f,processAttachmentQueryResult:d}=yield q.whenOrAbort(new Promise((t,w)=>m(["../../../../rest/query/operations/queryAttachments"],t,w)),c),h=D.parseUrl(this.url);a=yield this.queryAttachmentsSupported?e(h,a,c):f(h,a,c);return d(h,a)});return function(a,c){return b.apply(this,arguments)}}();g.executeTopFeaturesQuery=function(){var b=l._asyncToGenerator(function*(a,c){const {executeTopFeaturesQuery:e}=yield q.whenOrAbort(new Promise((f,d)=>m(["../../../../rest/query/executeTopFeaturesQuery"],
f,d)),c);return e(this.parsedUrl,a,this.sourceSpatialReference,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeForTopIds=function(){var b=l._asyncToGenerator(function*(a,c){const {executeForTopIds:e}=yield q.whenOrAbort(new Promise((f,d)=>m(["../../../../rest/query/executeForTopIds"],f,d)),c);return e(this.parsedUrl,a,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeForTopExtents=function(){var b=l._asyncToGenerator(function*(a,c){const {executeForTopExtents:e}=
yield q.whenOrAbort(new Promise((f,d)=>m(["../../../../rest/query/executeForTopExtents"],f,d)),c);return e(this.parsedUrl,a,c)});return function(a,c){return b.apply(this,arguments)}}();g.executeForTopCount=function(){var b=l._asyncToGenerator(function*(a,c){const {executeForTopCount:e}=yield q.whenOrAbort(new Promise((f,d)=>m(["../../../../rest/query/executeForTopCount"],f,d)),c);return e(this.parsedUrl,a,c)});return function(a,c){return b.apply(this,arguments)}}();g._normalizeQuery=function(b){let a=
K.from(b);a.sourceSpatialReference=a.sourceSpatialReference||this.sourceSpatialReference;if(this.gdbVersion||this.dynamicDataSource)a=a===b?a.clone():a,a.gdbVersion=b.gdbVersion||this.gdbVersion,a.dynamicDataSource=b.dynamicDataSource?x.DataLayerSource.from(b.dynamicDataSource):this.dynamicDataSource;if(r.isSome(this.infoFor3D)&&this._queryIs3DObjectFormat(b)){a=a===b?a.clone():a;a.formatOf3DObjects=null;for(const c of this.infoFor3D.queryFormats){if("3D_glb"===c){a.formatOf3DObjects=c;break}"3D_gltf"!==
c||a.formatOf3DObjects||(a.formatOf3DObjects=c)}if(!a.formatOf3DObjects)throw new z("query:unsupported-3d-query-formats","Could not find any supported 3D object query format. Only supported formats are 3D_glb and 3D_gltf");if(r.isNone(a.outFields)||!a.outFields.includes("*")){a=a===b?a.clone():a;r.isNone(a.outFields)&&(a.outFields=[]);const {originX:c,originY:e,originZ:f,translationX:d,translationY:h,translationZ:t,scaleX:w,scaleY:L,scaleZ:M,rotationX:N,rotationY:O,rotationZ:P,rotationDeg:Q}=this.infoFor3D.transformFieldRoles;
a.outFields.push(c,e,f,d,h,t,w,L,M,N,O,P,Q)}}return a};g._normalizeFields=function(b){if(r.isSome(this.fieldsIndex)&&r.isSome(b))for(const a of b)(b=this.fieldsIndex.get(a.name))&&Object.assign(a,b.toJSON())};g._queryIs3DObjectFormat=function(b){return r.isSome(this.infoFor3D)&&!0===b.returnGeometry&&"xyFootprint"!==b.multipatchOption&&!b.outStatistics};l._createClass(v,[{key:"parsedUrl",get:function(){return B.urlToObject(this.url)}}]);return v}(k);n.__decorate([p.property({type:x.DataLayerSource})],
k.prototype,"dynamicDataSource",void 0);n.__decorate([p.property()],k.prototype,"fieldsIndex",void 0);n.__decorate([p.property()],k.prototype,"gdbVersion",void 0);n.__decorate([p.property()],k.prototype,"infoFor3D",void 0);n.__decorate([p.property({readOnly:!0})],k.prototype,"parsedUrl",null);n.__decorate([p.property()],k.prototype,"pbfSupported",void 0);n.__decorate([p.property()],k.prototype,"queryAttachmentsSupported",void 0);n.__decorate([p.property()],k.prototype,"sourceSpatialReference",void 0);
n.__decorate([p.property({type:String})],k.prototype,"url",void 0);return k=n.__decorate([C.subclass("esri.tasks.QueryTask")],k)});