// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/handleUtils ../../../../../core/maybe ../../../../../core/reactiveUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../support/elevationInfoUtils ../../../../../symbols/support/ElevationInfo ../../SegmentLabels3D ../../SnappingVisualizer3D ../settings ../../visualElements/ExtendedLineVisualElement ../../visualElements/OutlineVisualElement ../../visualElements/VerticesVisualElement ../../../layers/graphics/elevationAlignmentUtils ../../../layers/graphics/ElevationContext ../../../layers/graphics/GraphicState ../../../webgl-engine/lib/Material ../../../../draw/DrawGraphicTool ../../../../draw/DrawOperation ../../../../draw/drawSurfaces".split(" "),
function(d,y,h,k,c,r,l,N,O,z,A,B,n,C,D,E,e,F,G,t,H,I,J,K,u,L,v){d.DrawGraphicTool3D=function(w){function p(a){a=w.call(this,a)||this;a._activeVertexVisualElement=null;a._createGraphicState=null;a._outlineVisualElement=null;a._verticesVisualElement=null;a._verticalLineVisualElement=null;a.geometryType=null;a.type="draw-3d";return a}y._inheritsLoose(p,w);var f=p.prototype;f.initialize=function(){const {mode:a,offset:b}=this.elevationInfo;this.internalGraphicsLayer.elevationInfo=new C({mode:a,offset:b})};
f.normalizeCtorArgs=function(a){return a.elevationInfo?a:{...a,elevationInfo:n.getEffectiveElevationInfo(a.hasZ??!0)}};f.initializeGraphic=function(a){const b=this._createGraphicState=new J.GraphicState({graphic:a});return k.handlesGroup([this.view.maskOccludee(a),this.view.trackGraphicState(b),r.watch(()=>({element:this._outlineVisualElement,isDraped:b.isDraped}),({element:m,isDraped:q})=>{c.applySome(m,M=>M.isDraped=q)},r.initial)])};f.makeDrawOperation=function(){const {geometryType:a}=this,b=
"circle"!==a&&"rectangle"!==a;return new L.DrawOperation({view:this.view,manipulators:this.manipulators,geometryType:u.geometryTypeToDrawOperationGeometryType(a),drawingMode:this.mode,hasZ:this.hasZ,defaultZ:this.defaultZ,snapToSceneEnabled:this.snapToScene,drawSurface:new v.SceneDrawSurface(this.view,this.elevationInfo,[this.internalGraphicsLayer]),elevationDrawSurface:new v.ElevationDrawSurface(this.elevationInfo,this.defaultZ,this.view,this.internalGraphicsLayer),hasM:!1,elevationInfo:this.elevationInfo,
snappingManager:this.snappingManager,snappingVisualizer:new E.SnappingVisualizer3D,segmentLabels:b?new D.SegmentLabels3D:null,labelOptions:this.labelOptions,tooltipOptions:this.tooltipOptions,isDraped:c.isSome(this._createGraphicState)?this._createGraphicState.isDraped:"on-the-ground"===n.getEffectiveElevationMode(this.hasZ,this.elevationInfo)})};f.onActiveVertexChanged=function(a){const {view:b}=this;if(c.isSome(this._activeVertexVisualElement))return this._activeVertexVisualElement.vertices=[a],
this._updateVerticalLineVisualElement(a),null;this._activeVertexVisualElement=new t.VerticesVisualElement({view:b,spatialReference:b.spatialReference,vertices:[a],elevationInfo:this.internalGraphicsLayer.elevationInfo,renderOccluded:e.settings.reshapeManipulators.vertex.renderOccluded,attached:!1});this._activeVertexVisualElement.color=e.settings.colorToVec4(e.settings.reshapeManipulators.selected.color);this._activeVertexVisualElement.attached=!0;this._verticalLineVisualElement=new F.ExtendedLineVisualElement({view:b,
extensionType:e.settings.visualElements.zVerticalLine.extensionType,innerWidth:1,attached:!1,writeDepthEnabled:!1,renderOccluded:K.RenderOccludedFlag.OccludeAndTransparent});e.settings.visualElements.zVerticalLine.apply(this._verticalLineVisualElement);return k.makeHandle(()=>{this._activeVertexVisualElement=c.destroyMaybe(this._activeVertexVisualElement);this._verticalLineVisualElement=c.destroyMaybe(this._verticalLineVisualElement)})};f._updateVerticalLineVisualElement=function(a){const b=this._verticalLineVisualElement;
if(!c.isNone(b)){var {renderCoordsHelper:m,elevationProvider:q}=this.view;A.set(g,a[0],a[1],a[2]);x.setFromElevationInfo(this.elevationInfo);g[2]=H.evaluateElevationAlignmentAtPoint(g,q,x,m);m.toRenderCoords(g,this.view.spatialReference,g)?(b.setStartEndFromWorldDownAtLocation(g),b.attached=!0):b.attached=!1}};f.onOutlineChanged=function(a){if(c.isSome(this._outlineVisualElement))return this._outlineVisualElement.geometry=a,null;const b=this.internalGraphicsLayer.elevationInfo;this._outlineVisualElement=
new G.OutlineVisualElement({view:this.view,geometry:a,elevationInfo:b,isDraped:c.isSome(this._createGraphicState)?this._createGraphicState.isDraped:"on-the-ground"===n.getEffectiveElevationMode(this.hasZ,b),attached:!1});e.settings.visualElements.lineGraphics.outline.apply(this._outlineVisualElement);e.settings.visualElements.lineGraphics.shadowStyle.apply(this._outlineVisualElement);this._outlineVisualElement.attached=!0;this._outlineVisualElement.laserlineEnabled=!0;return k.makeHandle(()=>{this._outlineVisualElement=
c.destroyMaybe(this._outlineVisualElement)})};f.onRegularVerticesChanged=function(a){if(c.isSome(this._verticesVisualElement))return this._verticesVisualElement.vertices=a,null;this._verticesVisualElement=new t.VerticesVisualElement({view:this.view,spatialReference:this.view.spatialReference,vertices:a,elevationInfo:this.internalGraphicsLayer.elevationInfo,renderOccluded:e.settings.reshapeManipulators.vertex.renderOccluded,attached:!1});this._verticesVisualElement.attached=!0;return k.makeHandle(()=>
{this._verticesVisualElement=c.destroyMaybe(this._verticesVisualElement)})};return p}(u.DrawGraphicTool);h.__decorate([l.property({constructOnly:!0})],d.DrawGraphicTool3D.prototype,"elevationInfo",void 0);h.__decorate([l.property({constructOnly:!0})],d.DrawGraphicTool3D.prototype,"geometryType",void 0);h.__decorate([l.property()],d.DrawGraphicTool3D.prototype,"type",void 0);h.__decorate([l.property({constructOnly:!0})],d.DrawGraphicTool3D.prototype,"view",void 0);d.DrawGraphicTool3D=h.__decorate([z.subclass("esri.views.3d.interactive.editingTools.draw.DrawGraphicTool3D")],
d.DrawGraphicTool3D);const x=new I.ElevationContext,g=B.create();Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});