// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../intl ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/decorators/cast ../../core/arrayUtils ../../core/accessorSupport/decorators/subclass ../Widget ./FeatureRelationship/FeatureRelationshipViewModel ./support/FeatureElementInfo ../support/widgetUtils ../support/decorators/messageBundle ../support/jsxFactory ../../intl/substitute".split(" "),
function(m,p,g,e,v,w,k,h,x,H,y,z,q,A,B,r,f,C){const t={title:!0,description:!0};e=function(u){function n(a,b){var c=u.call(this,a,b)||this;c._featureElementInfo=null;c._relatedFeatureIntersectionObserverNode=null;c._relatedFeatureIntersectionObserver=new IntersectionObserver(([l])=>{l?.isIntersecting&&c._increaseFeaturePage()},{root:window.document});c.headingLevel=2;c.viewModel=new q;c.messages=null;c.messagesCommon=null;c.visibleElements={...t};c._increaseFeaturePage=()=>{const {state:l,showAllEnabled:D,
relatedFeatures:E,featuresPerPage:F,featurePage:G}=c.viewModel;"ready"===l&&D&&E.length>=F*G&&c.viewModel.featurePage++};return c}p._inheritsLoose(n,u);var d=n.prototype;d.initialize=function(){this._featureElementInfo=new A;this.addHandles([k.watch(()=>[this.viewModel.description,this.viewModel.title,this.headingLevel],()=>this._setupFeatureElementInfo(),k.initial),k.watch(()=>[this.viewModel.state,this.viewModel.showAllEnabled,this._relatedFeatureIntersectionObserverNode],()=>this._handleRelatedFeatureObserverChange()),
k.on(()=>this.viewModel.relatedFeatureViewModels,"change",()=>this._setupRelatedFeatureViewModels())])};d.loadDependencies=function(){return Promise.all([new Promise((a,b)=>m(["../../chunks/calcite-list"],a,b)),new Promise((a,b)=>m(["../../chunks/calcite-list-item"],a,b)),new Promise((a,b)=>m(["../../chunks/calcite-icon"],a,b)),new Promise((a,b)=>m(["../../chunks/calcite-notice"],a,b))])};d.destroy=function(){this._unobserveRelatedFeatureObserver();this._featureElementInfo=v.destroyMaybe(this._featureElementInfo)};
d.castVisibleElements=function(a){return{...t,...a}};d.renderStickyLoading=function(){return"querying"===this.viewModel.state?f.tsx("div",{key:"sticky-loader",class:"esri-feature__sticky-loading-container"},this.renderLoadingIcon()):null};d.renderLoadingIcon=function(){return f.tsx("span",{class:this.classes("esri-icon-loading-indicator esri-rotating","esri-feature__loading-spinner")})};d.renderLoading=function(){return f.tsx("div",{key:"loading-container",class:"esri-feature__loading-container"},
this.renderLoadingIcon())};d.renderShowAllIconNode=function(){return f.tsx("calcite-icon",{scale:"s",icon:"list",slot:"content-end"})};d.renderChevronIconNode=function(){const a=B.isRTL(this.container)?"chevron-left":"chevron-right";return f.tsx("calcite-icon",{scale:"s",icon:a,slot:"content-end"})};d.renderRelatedFeature=function(a){var {itemDescriptionFieldName:b}=this.viewModel;const c=a.title;a.description=b&&a.formattedAttributes?.global[b];b="loading"===a.state;return f.tsx("calcite-list-item",
{key:a.uid,label:b?`${this.messagesCommon?.loading}\u2026`:c,description:b?"\u2026":a.description??"",onCalciteListItemSelect:()=>this.emit("select-record",{featureViewModel:a})},this.renderChevronIconNode())};d.renderShowAllListItem=function(){return this.displayShowAllButton?f.tsx("calcite-list-item",{key:"show-all-item",label:this.messages?.showAll,description:this.featureCountDescription,onCalciteListItemSelect:()=>this.emit("show-all-records")},this.renderShowAllIconNode()):null};d.renderNoRelatedFeaturesMessage=
function(){return f.tsx("calcite-notice",{key:"no-related-features-message",icon:"information",open:!0,kind:"brand",scale:"s",width:"full"},f.tsx("div",{slot:"message"},this.messages?.noRelatedFeatures))};d.renderFeatureObserver=function(){return f.tsx("div",{key:"feature-observer",class:"esri-feature__feature-observer",bind:this,afterCreate:this._relatedFeatureIntersectionObserverCreated})};d.renderList=function(){const {relatedFeatureViewModels:a}=this.viewModel;return f.tsx("calcite-list",null,
a.toArray().map(b=>this.renderRelatedFeature(b)),this.renderShowAllListItem())};d.renderRelatedFeatures=function(){const {displayListItems:a}=this,{state:b}=this.viewModel;return f.tsx("div",{key:"list-container",class:this.classes("esri-feature-relationship__list",{["esri-feature-relationship__list--querying"]:"querying"===b})},a?this.renderList():"ready"===b?this.renderNoRelatedFeaturesMessage():null,this.renderStickyLoading(),this.renderFeatureObserver())};d.renderRelationshipNotFound=function(){return f.tsx("calcite-notice",
{key:"relationship-not-found",icon:"exclamation-mark-triangle",open:!0,kind:"danger",scale:"s",width:"full"},f.tsx("div",{slot:"message"},this.messages?.relationshipNotFound))};d.render=function(){const {state:a}=this.viewModel;return f.tsx("div",{class:this.classes("esri-feature-relationship","esri-widget")},this._featureElementInfo?.render(),"loading"===a?this.renderLoading():"disabled"===a?this.renderRelationshipNotFound():this.renderRelatedFeatures())};d._setupRelatedFeatureViewModels=function(){const {relatedFeatureViewModels:a}=
this.viewModel;this.removeHandles("related-feature-viewmodels");a?.forEach(b=>{this.addHandles(k.watch(()=>[b.title,b.state],()=>this.scheduleRender(),k.initial),"related-feature-viewmodels")});this.scheduleRender()};d._setupFeatureElementInfo=function(){const {headingLevel:a,visibleElements:b}=this,c=b.description&&this.description,l=b.title&&this.title;this._featureElementInfo?.set({description:c,title:l,headingLevel:a})};d._handleRelatedFeatureObserverChange=function(){var a=p._asyncToGenerator(function*(){this._unobserveRelatedFeatureObserver();
const {state:b,showAllEnabled:c}=this.viewModel;yield w.after(0);this._relatedFeatureIntersectionObserverNode&&"ready"===b&&c&&this._relatedFeatureIntersectionObserver.observe(this._relatedFeatureIntersectionObserverNode)});return function(){return a.apply(this,arguments)}}();d._relatedFeatureIntersectionObserverCreated=function(a){this._relatedFeatureIntersectionObserverNode=a};d._unobserveRelatedFeatureObserver=function(){this._relatedFeatureIntersectionObserverNode&&this._relatedFeatureIntersectionObserver.unobserve(this._relatedFeatureIntersectionObserverNode)};
p._createClass(n,[{key:"displayShowAllButton",get:function(){const {showAllEnabled:a,featureCount:b,displayCount:c}=this.viewModel;return!a&&!!b&&(b>c||0===c)}},{key:"displayListItems",get:function(){return this.displayShowAllButton||0<this.viewModel.relatedFeatureViewModels.length}},{key:"description",get:function(){return this.viewModel.description},set:function(a){this.viewModel.description=a}},{key:"featureCountDescription",get:function(){const {messages:a}=this,{featureCount:b}=this.viewModel;
return C.substitute(1===b?a?.numberRecord:a?.numberRecords,{number:b})}},{key:"title",get:function(){return this.viewModel.title},set:function(a){this.viewModel.title=a}}]);return n}(z);g.__decorate([h.property()],e.prototype,"_relatedFeatureIntersectionObserverNode",void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"displayShowAllButton",null);g.__decorate([h.property({readOnly:!0})],e.prototype,"displayListItems",null);g.__decorate([h.property()],e.prototype,"description",null);g.__decorate([h.property({readOnly:!0})],
e.prototype,"featureCountDescription",null);g.__decorate([h.property()],e.prototype,"headingLevel",void 0);g.__decorate([h.property()],e.prototype,"title",null);g.__decorate([h.property({type:q})],e.prototype,"viewModel",void 0);g.__decorate([h.property(),r.messageBundle("esri/widgets/Feature/t9n/Feature")],e.prototype,"messages",void 0);g.__decorate([h.property(),r.messageBundle("esri/t9n/common")],e.prototype,"messagesCommon",void 0);g.__decorate([h.property()],e.prototype,"visibleElements",void 0);
g.__decorate([x.cast("visibleElements")],e.prototype,"castVisibleElements",null);return e=g.__decorate([y.subclass("esri.widgets.Feature.FeatureRelationship")],e)});