// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../geometry ../../../core/Error ../../../core/maybe ../../../core/urlUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../RasterInfo ../RasterStorageInfo ../serviceTileInfoProperty ../TileInfo ../TilemapCache ./BaseRaster ../rasterFunctions/pixelUtils ../rasterTransforms/GCSShiftTransform ../../../rest/imageService/fetchRasterInfo ../../../geometry/SpatialReference ../../../geometry/Point ../../../geometry/Extent".split(" "),
function(v,B,w,C,u,G,E,X,Y,H,I,J,K,L,M,N,O,P,Q,R,S,T){w=function(F){function D(){var e=F.apply(this,arguments)||this;e._levelOffset=0;e._tilemapCache=null;e._slices=null;e.datasetFormat="RasterTileServer";e.tileType=null;return e}v._inheritsLoose(D,F);var p=D.prototype;p.open=function(){var e=v._asyncToGenerator(function*(a){yield this.init();var b=a&&a.signal;a=this.sourceJSON?{data:this.sourceJSON}:yield this.request(this.url,{query:{f:"json"},signal:b});a.ssl&&(this.url=this.url.replace(/^http:/i,
"https:"));this.sourceJSON=a=a.data;if(!a)throw new C("imageserverraster:open","cannot initialize tiled image service, missing service info");if(!a.tileInfo)throw new C("imageserverraster:open","use ImageryLayer to open non-tiled image services");this._fixScaleInServiceInfo();var d="jpg jpeg png png8 png24 png32 mixed".split(" ");this.tileType=a.cacheType;null==this.tileType&&(d.includes(a.tileInfo.format.toLowerCase())?this.tileType="Map":"lerc"===a.tileInfo.format.toLowerCase()?this.tileType="Elevation":
this.tileType="Raster");this.datasetName=a.name?.slice(a.name.indexOf("/")+1)??"";b=yield this._fetchRasterInfo({signal:b});if(u.isNone(b))throw new C("image-server-raster:open","cannot initialize image service");d="Map"===this.tileType?K.readServiceTileInfo(a.tileInfo,a):L.fromJSON(a.tileInfo);u.assertIsSome(d);const [c,h]=this._computeMinMaxLOD(b,d),{extent:k,pixelSize:f}=b,g=.5/b.width*f.x,r=Math.max(f.x,f.y),{lods:q}=d;if("Map"!==this.tileType&&0!==a.maxScale||Math.abs(f.x-f.y)>g||!q.some(m=>
Math.abs(m.resolution-r)<g))f.x=f.y=c.resolution,b.width=Math.ceil((k.xmax-k.xmin)/f.x-.1),b.height=Math.ceil((k.ymax-k.ymin)/f.y-.1);const t=c.level-h.level,[x,y]=d.size,n=[],l=[];q.forEach((m,z)=>{m.level>=h.level&&m.level<=c.level&&n.push({x:m.resolution,y:m.resolution});z<q.length-1&&l.push(Math.round(10*m.resolution/q[z+1].resolution)/10)});n.sort((m,z)=>m.x-z.x);const U=this.computeBlockBoundary(k,x,y,d.origin,n,t),V=1<n.length?n.slice(1):null;var A;a.transposeInfo&&(A={tileSize:[a.transposeInfo.rows,
a.transposeInfo.cols],packetSize:b.keyProperties?._yxs.PacketSize??0});const W=1>=l.length||3<=l.length&&l.slice(0,l.length-1).every(m=>m===l[0])?l[0]??2:Math.round(10/(h.resolution/c.resolution)**(-1/t))/10;b.storageInfo=new J({blockWidth:d.size[0],blockHeight:d.size[1],pyramidBlockWidth:d.size[0],pyramidBlockHeight:d.size[1],pyramidResolutions:V,pyramidScalingFactor:W,compression:d.format,origin:d.origin,firstPyramidLevel:1,maximumPyramidLevel:t,tileInfo:d,transposeInfo:A,blockBoundary:U});this._fixGCSShift(b);
this._set("rasterInfo",b);a.capabilities.toLowerCase().includes("tilemap")&&(A={tileInfo:b.storageInfo.tileInfo,parsedUrl:G.urlToObject(this.url),url:this.url,tileServers:[],type:"tile"},this._tilemapCache=new M.TilemapCache({layer:A}))});return function(a){return e.apply(this,arguments)}}();p.fetchRawTile=function(){var e=v._asyncToGenerator(function*(a,b,d,c={}){const {storageInfo:h,extent:k}=this.rasterInfo;var {transposeInfo:f}=h,g=u.isSome(f)&&!!c.transposedVariableName;if(this._slices&&!g&&
null==c.sliceId)return null;({data:c}=yield this.request(`${this.url}/tile/${g?0:h.maximumPyramidLevel-a+this._levelOffset}/${b}/${d}`,{query:this._slices?g?{variable:c.transposedVariableName}:{sliceId:c.sliceId||0}:null,responseType:"array-buffer",signal:c.signal}));if(!c)return null;f=g?f.tileSize:h.tileInfo.size;g=yield this.decodePixelBlock(c,{width:f[0],height:f[1],planes:null,pixelType:null,isPoint:"Elevation"===this.tileType,returnInterleaved:g,noDataValue:u.unwrap(this.rasterInfo.noDataValue)});
if(null==g)return null;f=h.blockBoundary[a];if("jpg"!==h.compression||d>f.minCol&&d<f.maxCol&&b>f.minRow&&b<f.maxRow)return g;const {origin:r,blockWidth:q,blockHeight:t}=h,{x,y}=this.getPyramidPixelSize(a);var n=Math.round((k.xmin-r.x)/x)%q;a=Math.round((k.xmax-r.x)/x)%q||q;var l=Math.round((r.y-k.ymax)/y)%t;c=Math.round((r.y-k.ymin)/y)%t||t;n=d===f.minCol?n:0;l=b===f.minRow?l:0;O.setValidBoundary(g,{x:n,y:l},{width:(d===f.maxCol?a:q)-n,height:(b===f.maxRow?c:t)-l});return g});return function(a,b,
d){return e.apply(this,arguments)}}();p.getSliceIndex=function(e){if(!this._slices||u.isNone(e)||0===e.length)return null;for(let a=0;a<this._slices.length;a++){const b=this._slices[a].multidimensionalDefinition;if(b.length===e.length&&!b.some(d=>{var c=e.find(k=>d.variableName===k.variableName&&k.dimensionName===d.dimensionName);if(!c)return!0;const h=Array.isArray(d.values[0])?`${d.values[0][0]}-${d.values[0][1]}`:d.values[0];c=Array.isArray(c.values[0])?`${c.values[0][0]}-${c.values[0][1]}`:c.values[0];
return h!==c}))return a}return null};p.fetchVariableStatisticsHistograms=function(){var e=v._asyncToGenerator(function*(a,b){var d=this.request(this.url+"/statistics",{query:{variable:a,f:"json"},signal:b}).then(c=>c.data?.statistics);a=this.request(this.url+"/histograms",{query:{variable:a,f:"json"},signal:b}).then(c=>c.data?.histograms);d=yield Promise.all([d,a]);d[0]&&d[0].forEach(c=>{c.avg=c.mean;c.stddev=c.standardDeviation});return{statistics:d[0]||null,histograms:d[1]||null}});return function(a,
b){return e.apply(this,arguments)}}();p.computeBestPyramidLevelForLocation=function(){var e=v._asyncToGenerator(function*(a,b={}){if(!this._tilemapCache)return 0;a=this.identifyPixelLocation(a,0,u.unwrap(b.datumTransformation));if(null===a)return null;let d=0;var {maximumPyramidLevel:c}=this.rasterInfo.storageInfo;c=c-d+this._levelOffset;const h=a.srcLocation;for(;0<=c;){try{if("available"===(yield this._tilemapCache.fetchAvailability(c,a.row,a.col,b)))break}catch{}c--;d++;a=this.identifyPixelLocation(h,
d,u.unwrap(b.datumTransformation));if(null===a)return null}return-1===c||null==a?null:d});return function(a){return e.apply(this,arguments)}}();p._fetchRasterInfo=function(){var e=v._asyncToGenerator(function*(a){var b=this.sourceJSON;if("Map"===this.tileType){a=b.fullExtent||b.extent;var d=Math.ceil((a.xmax-a.xmin)/b.pixelSizeX-.1);const c=Math.ceil((a.ymax-a.ymin)/b.pixelSizeY-.1),h=R.fromJSON(b.spatialReference||a.spatialReference);b=new S({x:b.pixelSizeX,y:b.pixelSizeY,spatialReference:h});return new I({width:d,
height:c,bandCount:3,extent:T.fromJSON(a),spatialReference:h,pixelSize:b,pixelType:"u8",statistics:null,keyProperties:{DataType:"processed"}})}({signal:d}=a);a=Q.fetchServiceRasterInfo(this.url,this.sourceJSON,{signal:d,query:this.ioConfig.customFetchParameters});b=b.hasMultidimensions?this.request(`${this.url}/slices`,{query:{f:"json"},signal:d}).then(c=>c.data&&c.data.slices).catch(()=>null):null;b=yield Promise.all([a,b]);this._slices=b[1];return b[0]});return function(a){return e.apply(this,arguments)}}();
p._fixScaleInServiceInfo=function(){const {sourceJSON:e}=this;e.minScale&&0>e.minScale&&(e.minScale=0);e.maxScale&&0>e.maxScale&&(e.maxScale=0)};p._fixGCSShift=function(e){const {extent:a,spatialReference:b}=e;-1<a.xmin&&181<a.xmax&&b?.wkid&&b.isGeographic&&(e.nativeExtent=e.extent,e.transform=new P,e.extent=e.transform.forwardTransform(a))};p._computeMinMaxLOD=function(e,a){const {pixelSize:b}=e,d=.5/e.width*b.x;({lods:e}=a);var c=a.lodAt(Math.max.apply(null,e.map(g=>g.level)));a=a.lodAt(Math.min.apply(null,
e.map(g=>g.level)));var {tileType:h}=this;if("Map"===h)return this._levelOffset=e[0].level,[c,a];if("Raster"===h)return[e.find(g=>g.resolution===b.x)??c,a];const {minScale:k,maxScale:f}=this.sourceJSON;h=c;0<f&&((h=e.find(g=>Math.abs(g.scale-f)<d))||(h=e.filter(g=>g.scale>f).sort((g,r)=>g.scale>r.scale?1:-1)[0]??c));c=a;0<k&&(c=e.find(g=>Math.abs(g.scale-k)<d)??a,this._levelOffset=c.level-a.level);return[h,c]};return D}(N);B.__decorate([E.property({type:String,json:{write:!0}})],w.prototype,"datasetFormat",
void 0);B.__decorate([E.property()],w.prototype,"tileType",void 0);return w=B.__decorate([H.subclass("esri.layers.support.rasterDatasets.ImageServerRaster")],w)});