// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../geometry ../core/Collection ../core/Error ../core/Logger ../core/promiseUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ../geohash/geohashUtils ./Layer ./graphics/featureConversionUtils ./graphics/OptimizedGeometry ./knowledgeGraph/KnowledgeGraphLayerDataManager ./knowledgeGraph/KnowledgeGraphSubLayer ./mixins/BlendLayer ./mixins/ScaleRangeLayer ../libs/linkchartlayout/LinkChartLayout ../rest/knowledgeGraphService ../rest/knowledgeGraph/EntityType ../rest/knowledgeGraph/RelationshipType ../geometry/Extent ../geometry/Point ../geometry/Polyline".split(" "),
function(w,x,t,M,H,I,U,y,ea,fa,V,F,W,E,N,e,O,X,Y,u,Z,aa,ba,P,J,Q){t=function(R){function K(c){var b=R.call(this,c)||this;b.dataPreloadedInLocalCache=!1;b.layers=new M;b.linkChartDiagramLookup=new Map;b.linkChartExtent=new P({xmin:-1E-7,ymin:-1E-7,xmax:1E-7,ymax:1E-7});b.linkChartGeohashLookup=new Map;b.sublayerIdsCache=new Map;b.tables=new M;b.type="link-chart";b._originalInclusionList=c.inclusionModeDefinition;if(c.dataPreloadedInLocalCache&&!c.inclusionModeDefinition)throw new H("knowledge-graph:linkchart-layer-constructor",
"If creating a link chart composite layer and configured that data is already loaded in the cache, you must specify an inclusion list so the Composite Layer knows what records belong to it");return b}w._inheritsLoose(K,R);var C=K.prototype;C.normalizeCtorArgs=function(c){return{url:c.url,title:c.title,dataPreloadedInLocalCache:c.dataPreloadedInLocalCache,defaultLinkChartConfig:c.defaultLinkChartConfig}};C._initializeLayerProperties=function(c){if(!this.title&&this.url){var b=this.url.split("/");this.title=
b[b.length-2]}const a=new Set,d=new Map;let f=[],l=[];if(c.inclusionModeDefinition&&(!c.inclusionModeDefinition.namedTypeDefinitions||1>c.inclusionModeDefinition.namedTypeDefinitions.size))throw new H("knowledge-graph:composite-layer-constructor","If an explicit inclusion definition is defined, at least one namedTypeDefinition must also be defined");c.inclusionModeDefinition?.generateAllSublayers?(f=c.knowledgeGraph.dataModel.entityTypes?c.knowledgeGraph.dataModel.entityTypes:[],l=c.knowledgeGraph.dataModel.relationshipTypes?
c.knowledgeGraph.dataModel.relationshipTypes:[]):c.inclusionModeDefinition?.namedTypeDefinitions&&0<c.inclusionModeDefinition?.namedTypeDefinitions.size?(c.knowledgeGraph.dataModel.entityTypes?.forEach(h=>{h.name&&d.set(h.name,h)}),c.knowledgeGraph.dataModel.relationshipTypes?.forEach(h=>{h.name&&d.set(h.name,h)}),c.inclusionModeDefinition?.namedTypeDefinitions.forEach((h,q)=>{d.get(q)?d.get(q)instanceof ba||"strictOrigin"in d.get(q)?a.has(q)||(a.add(q),l.push(d.get(q))):d.get(q)instanceof aa||"properties"in
d.get(q)?a.has(q)||(a.add(q),f.push(d.get(q))):(I.getLogger(this.declaredClass).warn(`A named type, ${q}, was in the inclusion list that wasn't properly modeled and will be removed`),c.inclusionModeDefinition?.namedTypeDefinitions.delete(q)):(I.getLogger(this.declaredClass).warn(`A named type, ${q}, was in the inclusion list that wasn't in the data model and will be removed`),c.inclusionModeDefinition?.namedTypeDefinitions.delete(q))})):(f=c.knowledgeGraph.dataModel.entityTypes?c.knowledgeGraph.dataModel.entityTypes:
[],l=c.knowledgeGraph.dataModel.relationshipTypes?c.knowledgeGraph.dataModel.relationshipTypes:[]);b=new e.KnowledgeGraphLayerDataManager({knowledgeGraph:c.knowledgeGraph,inclusionModeDefinition:c.inclusionModeDefinition});this.knowledgeGraph=c.knowledgeGraph;this.memberEntityTypes=f;this.memberRelationshipTypes=l;this.dataManager=b};C.load=function(c){var b=this;this.addResolvingPromise(new Promise(a=>{Z.fetchKnowledgeGraph(this.url).then(d=>{this._initializeLayerProperties({knowledgeGraph:d,inclusionModeDefinition:this._originalInclusionList});
this.dataManager.inclusionModeDefinition?.namedTypeDefinitions?.size||(this.dataManager.inclusionModeDefinition={generateAllSublayers:!1,namedTypeDefinitions:new Map},this.dataManager.knowledgeGraph.dataModel.entityTypes?.forEach(f=>{f.name&&this.dataManager.inclusionModeDefinition?.namedTypeDefinitions.set(f.name,{useAllData:!0})}),this.dataManager.knowledgeGraph.dataModel.relationshipTypes?.forEach(f=>{f.name&&this.dataManager.inclusionModeDefinition?.namedTypeDefinitions.set(f.name,{useAllData:!0})}));
this.dataPreloadedInLocalCache?(this.loadLayerAssumingLocalCache(),this.dataManager.inclusionModeDefinition&&(this.dataManager.inclusionModeDefinition.generateAllSublayers=!1),this.dataManager.inclusionModeDefinition?.namedTypeDefinitions.forEach(f=>{f.useAllData=!1;f.members?.forEach(l=>{let h;h=l.linkChartLocation instanceof N?l.linkChartLocation:l.linkChartLocation?E.convertFromGeometry(l.linkChartLocation):null;this.linkChartDiagramLookup.set(l.id,h);h&&2===h.coords.length&&0===h.lengths.length?
this.linkChartGeohashLookup.set(l.id,F.encodeGeohash(h.coords[1],h.coords[0],e.GEOHASH_ENCODING_PRECISION)):this.linkChartGeohashLookup.set(l.id,"")});this.addResolvingPromise(this._initializeDiagram().then(w._asyncToGenerator(function*(){b.layers.forEach(function(){var l=w._asyncToGenerator(function*(h){yield h.refreshCachedQueryEngine()});return function(h){return l.apply(this,arguments)}}());b.tables.forEach(function(){var l=w._asyncToGenerator(function*(h){yield h.refreshCachedQueryEngine()});
return function(h){return l.apply(this,arguments)}}())})))})):this.addResolvingPromise(this.dataManager.refreshCacheContent(void 0,!0,"GEOGRAPHIC"===this.defaultLinkChartConfig?.layoutMode).then(w._asyncToGenerator(function*(){U.throwIfAborted(c);const f=[],l=[];b.loadLayerAssumingLocalCache();b.dataManager.inclusionModeDefinition&&(b.dataManager.inclusionModeDefinition.generateAllSublayers=!1,b.dataManager.inclusionModeDefinition.namedTypeDefinitions.forEach(h=>{h.useAllData=!1}));yield b._initializeDiagram();
b.layers.forEach(function(){var h=w._asyncToGenerator(function*(q){l.push(q.refreshCachedQueryEngine());f.push(new Promise(D=>{q.on("layerview-create",w._asyncToGenerator(function*(){D(null)}))}))});return function(q){return h.apply(this,arguments)}}());b.tables.forEach(function(){var h=w._asyncToGenerator(function*(q){l.push(q.refreshCachedQueryEngine())});return function(q){return h.apply(this,arguments)}}());yield Promise.all(l);Promise.all(f).then(w._asyncToGenerator(function*(){b.dataManager.refreshCacheContent().then(w._asyncToGenerator(function*(){b.layers.forEach(h=>
{h.refreshCachedQueryEngine()});b.tables.forEach(h=>{h.refreshCachedQueryEngine()})}))}))})));a(null)})}));return Promise.resolve(this)};C.loadLayerAssumingLocalCache=function(){this.memberEntityTypes.forEach(c=>{const b=new O({objectType:c,parentCompositeLayer:this,graphType:"entity",title:c.name});b.geometryType?this.layers.push(b):this.tables.push(b);this.dataManager.sublayerCaches.has(c.name)||this.dataManager.sublayerCaches.set(c.name,new Map)});this.memberRelationshipTypes.forEach(c=>{const b=
new O({objectType:c,parentCompositeLayer:this,graphType:"relationship",title:c.name});b.geometryType?this.layers.push(b):this.tables.push(b);this.dataManager.sublayerCaches.has(c.name)||this.dataManager.sublayerCaches.set(c.name,new Map)});this.dataManager.inclusionModeDefinition?.namedTypeDefinitions&&this.dataManager.inclusionModeDefinition?.namedTypeDefinitions.forEach((c,b)=>{c.members?.forEach(a=>{this.sublayerIdsCache.has(b)?this.sublayerIdsCache.get(b)?.push(a.id):this.sublayerIdsCache.set(b,
[a.id]);if(a.linkChartLocation)if(a.linkChartLocation instanceof N)this.linkChartDiagramLookup.set(a.id,a.linkChartLocation),2===a.linkChartLocation.coords.length&&0===a.linkChartLocation.lengths.length?this.linkChartGeohashLookup.set(a.id,F.encodeGeohash(a.linkChartLocation.coords[1],a.linkChartLocation.coords[0],e.GEOHASH_ENCODING_PRECISION)):this.linkChartGeohashLookup.set(a.id,"");else{const d=E.convertFromGeometry(a.linkChartLocation);this.linkChartDiagramLookup.set(a.id,a.linkChartLocation?
d:null);"x"in a.linkChartLocation&&"y"in a.linkChartLocation?this.linkChartGeohashLookup.set(a.id,F.encodeGeohash(a.linkChartLocation.x,a.linkChartLocation.y,e.GEOHASH_ENCODING_PRECISION)):this.linkChartGeohashLookup.set(a.id,"")}})});Array.from(this.sublayerIdsCache.values()).forEach(c=>c.sort())};C.calculateLinkChartLayout=function(){var c=w._asyncToGenerator(function*(b="RADIAL_TREE",a){const d=[],f=[];this.dataManager.sublayerCaches.forEach((m,r)=>{this.dataManager.entityTypeNames.has(r)?m.forEach(k=>
{d.push({typeName:r,feature:k})}):this.dataManager.relationshipTypeNames.has(r)&&m.forEach(k=>{f.push({typeName:r,feature:k})})});this.linkChartDiagramLookup=new Map;const l=new Map,h=new Map,q=new Map,D=new Map,B=new Uint8Array(d.length),A=new Float64Array(d.length),v=new Float64Array(d.length),S=new Uint32Array(f.length),T=new Uint32Array(f.length),n=[];var g=a?.geographicStrategy?a.geographicStrategy:"FORCE_DIRECTED";const ca=a?.xScaleFactor?a.xScaleFactor:1,da=a?.yScaleFactor?a.yScaleFactor:1,
z=new P({xmin:-1E-7,ymin:-1E-7,xmax:1E-7,ymax:1E-7});let p=0,L=0;switch("GEOGRAPHIC"===b?g:b){case "FORCE_DIRECTED":g=u.LCForceDirectedLayout.apply;break;case "COMMUNITY":g=u.LCCommunityLayout.apply;break;case "HIERARCHICAL":g=u.LCHierarchicalLayout.apply;break;case "RADIAL_TREE":g=u.LCRadialTreeLayout.apply;break;case "SMART_TREE":g=u.LCSmartTreeLayout.apply;break;default:g=u.LCSimpleLayout.apply}d.forEach(({typeName:m,feature:r})=>{if(a?.lockedNodeLocations?.has(r.attributes[e.MOCK_OID_FIELD_NAME])){"GEOGRAPHIC"===
b&&this.dataManager.geographicLookup.has(m)?B[p]=u.NodeFlag.IsGeographic:B[p]=u.NodeFlag.None;var k=a.lockedNodeLocations.get(r.attributes[e.MOCK_OID_FIELD_NAME]);A[p]=k.x;v[p]=k.y}else if("GEOGRAPHIC"===b&&this.dataManager.geographicLookup.has(m)){B[p]=u.NodeFlag.IsGeographic;k=null;k=r.attributes[this.dataManager.geographicLookup.get(m).name];switch(this.dataManager.geographicLookup.get(m)?.geometryType){case "esriGeometryPoint":A[p]=k?.x;v[p]=k?.y;break;case "esriGeometryPolygon":k=k?.centroid;
k?.x&&k?.y?(A[p]=k?.x,v[p]=k?.y):B[p]=u.NodeFlag.IsMovable;break;case "esriGeometryPolyline":k=k?.extent?.center;k?.x&&k?.y?(A[p]=k?.x,v[p]=k?.y):B[p]=u.NodeFlag.IsMovable;break;case "esriGeometryMultipoint":k=k?.extent?.center;k?.x&&k?.y?(A[p]=k?.x,v[p]=k?.y):B[p]=u.NodeFlag.IsMovable;break;default:B[p]=u.NodeFlag.IsMovable}A[p]||(A[p]=0);v[p]||(v[p]=0)}else B[p]=u.NodeFlag.IsMovable,A[p]=0,v[p]=0;D.set(r.attributes[e.MOCK_OID_FIELD_NAME],p);n[p]={feature:r,typeName:m};p++});f.forEach(m=>{const r=
D.get(m.feature.attributes[e.MOCK_ORIGIN_ID_FIELD_NAME]),k=D.get(m.feature.attributes[e.MOCK_DESTINATION_ID_FIELD_NAME]);void 0!==r&&void 0!==k?(S[L]=r,T[L]=k,L++):(I.getLogger(this.declaredClass).warn("A relationship is a member of this layer that has either origin or destination entity nodes that are not members.  The diagram geometry will be set to null"),this.linkChartDiagramLookup.set(m.feature.attributes[e.MOCK_ORIGIN_ID_FIELD_NAME],null),this.linkChartGeohashLookup.set(m.feature.attributes[e.MOCK_ORIGIN_ID_FIELD_NAME],
null))});yield u.load();if(!g(B,A,v,S,T))throw new H("knowledge-graph:layout-failed","Attempting to arrange the records in the specified layout failed");for(g=0;g<n.length;g++){80<v[g]&&(v[g]=80);-80>v[g]&&(v[g]=-80);n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]=B[g]===u.NodeFlag.IsMovable?new J(A[g]*ca,v[g]*da):new J(A[g],v[g]);if(l.has(n[g].typeName))l.get(n[g].typeName)?.set(n[g].feature.attributes[e.MOCK_OID_FIELD_NAME],n[g].feature);else{var G=new Map;G.set(n[g].feature.attributes[e.MOCK_OID_FIELD_NAME],
n[g].feature);l.set(n[g].typeName,G)}q.set(n[g].feature.attributes[e.MOCK_OID_FIELD_NAME],n[g].feature);G=E.convertFromGeometry(n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]);this.linkChartDiagramLookup.set(n[g].feature.attributes[e.MOCK_OID_FIELD_NAME],n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]?G:null);this.linkChartGeohashLookup.set(n[g].feature.attributes[e.MOCK_OID_FIELD_NAME],F.encodeGeohash(n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].y,n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].x,
e.GEOHASH_ENCODING_PRECISION));n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].x<z.xmin&&(z.xmin=n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].x);n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].x>z.xmax&&(z.xmax=n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].x);n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].y<z.ymin&&(z.ymin=n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].y);n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].y>
z.ymax&&(z.ymax=n[g].feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME].y)}this.linkChartExtent.xmin=z.xmin;this.linkChartExtent.xmax=z.xmax;this.linkChartExtent.ymin=z.ymin;this.linkChartExtent.ymax=z.ymax;f.forEach(m=>{var r=n[D.get(m.feature.attributes[e.MOCK_ORIGIN_ID_FIELD_NAME])]?.feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME];const k=n[D.get(m.feature.attributes[e.MOCK_DESTINATION_ID_FIELD_NAME])]?.feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME];r&&k&&(r=new Q({paths:[[r.x,
r.y],[k.x,k.y]]}),m.feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]=r,h.has(m.typeName)?h.get(m.typeName)?.set(m.feature.attributes[e.MOCK_OID_FIELD_NAME],m.feature):(r=new Map,r.set(m.feature.attributes[e.MOCK_OID_FIELD_NAME],m.feature),h.set(m.typeName,r)),q.set(m.feature.attributes[e.MOCK_OID_FIELD_NAME],m.feature),r=E.convertFromGeometry(m.feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]),this.linkChartDiagramLookup.set(m.feature.attributes[e.MOCK_OID_FIELD_NAME],m.feature.attributes[e.MOCK_LAYOUT_GEOMETRY_FIELD_NAME]?
r:null),this.linkChartGeohashLookup.set(m.feature.attributes[e.MOCK_OID_FIELD_NAME],""))});return{nodes:l,links:h,idMap:q}});return function(){return c.apply(this,arguments)}}();C.applyNewLinkChartLayout=function(){var c=w._asyncToGenerator(function*(b="RADIAL_TREE",a){const d=[];yield this.calculateLinkChartLayout(b,a);this.layers.forEach(f=>{d.push(f.refreshCachedQueryEngine())});yield Promise.all(d);this.layers.forEach(f=>{f.emit("refresh",{dataChanged:!0})})});return function(){return c.apply(this,
arguments)}}();C.synchronizeInclusionListWithCache=function(){var c=w._asyncToGenerator(function*(){return new Promise(b=>{this.dataManager.inclusionModeDefinition?.namedTypeDefinitions.forEach((a,d)=>{a.useAllData=!1;if(a.members&&0<a.members.size&&this.dataManager.sublayerCaches.get(d)){var f=Array.from(this.dataManager.sublayerCaches.get(d).keys());Array.from(a.members.keys()).filter(l=>!f.includes(l)).forEach(l=>{a.members?.delete(l)})}});b()})});return function(){return c.apply(this,arguments)}}();
C._initializeDiagram=function(){var c=w._asyncToGenerator(function*(){if(this.defaultLinkChartConfig)if(this.defaultLinkChartConfig.doNotRecalculateLayout)this.dataManager.inclusionModeDefinition?.namedTypeDefinitions?.forEach(b=>{b?.members?.forEach(a=>{var d=a.linkChartLocation;a=a.id;if(d){d="x"in d?{x:d.x,y:d.y}:{x:d.coords[0],y:d.coords[1]};var f=E.convertFromGeometry(d);this.linkChartDiagramLookup.set(a,f);this.linkChartGeohashLookup.set(a,F.encodeGeohash(d.x,d.y,e.GEOHASH_ENCODING_PRECISION));
this.linkChartExtent.xmin>d.x&&(this.linkChartExtent.xmin=d.x);this.linkChartExtent.xmax<d.x&&(this.linkChartExtent.xmax=d.x);this.linkChartExtent.ymin>d.y&&(this.linkChartExtent.ymin=d.y);this.linkChartExtent.ymax<d.y&&(this.linkChartExtent.ymax=d.y)}})}),this.memberRelationshipTypes.forEach(b=>{b.name&&this.dataManager.sublayerCaches.get(b.name)?.forEach(a=>{var d=this.linkChartDiagramLookup.get(a.attributes[e.MOCK_ORIGIN_ID_FIELD_NAME]);const f=this.linkChartDiagramLookup.get(a.attributes[e.MOCK_DESTINATION_ID_FIELD_NAME]);
d&&f?(d=E.convertFromGeometry(new Q({paths:[[d.coords[0],d.coords[1]],[f.coords[0],f.coords[1]]]})),this.linkChartDiagramLookup.set(a.attributes[e.MOCK_OID_FIELD_NAME],d)):this.linkChartDiagramLookup.set(a.attributes[e.MOCK_OID_FIELD_NAME],null);this.linkChartGeohashLookup.set(a.attributes[e.MOCK_OID_FIELD_NAME],"")})});else{const b=new Map;this.dataManager.inclusionModeDefinition?.namedTypeDefinitions?.forEach(a=>{a?.members?.forEach(d=>{var f=d.linkChartLocation;const l=d.id;f&&("x"in f?(d=f.x,
f=f.y):(d=f.coords[0],f=f.coords[1]),b.set(l,new J({x:d,y:f})))})});yield this.calculateLinkChartLayout(this.defaultLinkChartConfig.layoutMode,{xScaleFactor:this.defaultLinkChartConfig.xScaleFactor,yScaleFactor:this.defaultLinkChartConfig.yScaleFactor,lockedNodeLocations:b})}else yield this.calculateLinkChartLayout()});return function(){return c.apply(this,arguments)}}();return K}(X.BlendLayer(Y.ScaleRangeLayer(W)));x.__decorate([y.property()],t.prototype,"dataPreloadedInLocalCache",void 0);x.__decorate([y.property()],
t.prototype,"defaultLinkChartConfig",void 0);x.__decorate([y.property()],t.prototype,"dataManager",void 0);x.__decorate([y.property()],t.prototype,"knowledgeGraph",void 0);x.__decorate([y.property()],t.prototype,"layers",void 0);x.__decorate([y.property()],t.prototype,"linkChartDiagramLookup",void 0);x.__decorate([y.property()],t.prototype,"linkChartExtent",void 0);x.__decorate([y.property()],t.prototype,"linkChartGeohashLookup",void 0);x.__decorate([y.property()],t.prototype,"memberEntityTypes",
void 0);x.__decorate([y.property()],t.prototype,"memberRelationshipTypes",void 0);x.__decorate([y.property()],t.prototype,"sublayerIdsCache",void 0);x.__decorate([y.property()],t.prototype,"tables",void 0);x.__decorate([y.property({json:{read:!1}})],t.prototype,"type",void 0);return t=x.__decorate([V.subclass("esri.layers.LinkChartLayer")],t)});