// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../geometry ../PopupTemplate ../renderers/ClassBreaksRenderer ../renderers/DictionaryRenderer ../renderers/DotDensityRenderer ../renderers/HeatmapRenderer ../renderers/PieChartRenderer ../renderers/Renderer ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/support/jsonUtils ../renderers/support/types ../request ../symbols ../core/Error ../core/handleUtils ../core/Logger ../core/maybe ../core/MultiOriginJSONSupport ../core/promiseUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass ../core/accessorSupport/extensions/serializableProperty/reader ../geometry/support/typeUtils ./Layer ./mixins/ArcGISService ./mixins/BlendLayer ./mixins/CustomParametersMixin ./mixins/FeatureEffectLayer ./mixins/FeatureReductionLayer ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/RefreshableLayer ./mixins/ScaleRangeLayer ./mixins/TemporalLayer ./support/commonProperties ./support/Field ./support/fieldProperties ./support/fieldUtils ./support/LabelClass ./support/labelingInfo ./support/PurgeOptions ../renderers/support/styleUtils ../rest/support/Query ../support/popupUtils ../symbols/support/ElevationInfo ../geometry/SpatialReference ../geometry/Extent".split(" "),
function(D,q,d,t,E,sa,ta,ua,va,wa,xa,F,G,H,x,I,J,m,K,L,M,c,N,e,y,ya,z,O,P,u,Q,R,S,T,U,V,W,X,Y,Z,aa,l,ba,ca,v,da,ea,A,fa,ha,ia,ja,B,ka){function C(h,n){return new m("layer:unsupported",`Layer (${h.title}, ${h.id}) of type '${h.declaredClass}' ${n}`,{layer:h})}t=ca.defineFieldProperties();c=function(h){function n(...a){a=h.call(this,...a)||this;a.copyright=null;a.definitionExpression=null;a.displayField=null;a.elevationInfo=null;a.fields=null;a.fieldsIndex=null;a.geometryDefinition=null;a.geometryType=
null;a.labelsVisible=!0;a.labelingInfo=null;a.legendEnabled=!0;a.maxReconnectionAttempts=0;a.maxReconnectionInterval=20;a.maxScale=0;a.minScale=0;a.objectIdField=null;a.operationalLayerType="ArcGISStreamLayer";a.popupEnabled=!0;a.popupTemplate=null;a.purgeOptions=new A;a.screenSizePerspectiveEnabled=!0;a.sourceJSON=null;a.spatialReference=B.WGS84;a.type="stream";a.url=null;a.updateInterval=300;a.webSocketUrl=null;return a}q._inheritsLoose(n,h);var g=n.prototype;g.normalizeCtorArgs=function(a,b){return"string"===
typeof a?{url:a,...b}:a};g.load=function(a){if(!("WebSocket"in globalThis))return this.addResolvingPromise(Promise.reject(new m("stream-layer:websocket-unsupported","WebSocket is not supported in this browser. StreamLayer will not have real-time connection with the stream service."))),Promise.resolve(this);const b=M.isSome(a)?a.signal:null;this.addResolvingPromise(this.loadFromPortal({supportedTypes:["Stream Service","Feed"]},a).catch(N.throwIfAbortError).then(()=>this._fetchService(b)));return Promise.resolve(this)};
g.readRenderer=function(a,b,f){b=b.layerDefinition||b;if(a=b.drawingInfo&&b.drawingInfo.renderer||void 0)return(a=H.read(a,b,f)||void 0)||L.getLogger(this.declaredClass).error("Failed to create renderer",{rendererDefinition:b.drawingInfo.renderer,layer:this,context:f}),a;if(b.defaultSymbol)return b.types&&b.types.length?new G({defaultSymbol:w(b.defaultSymbol,b,f),field:b.typeIdField,uniqueValueInfos:b.types.map(k=>({id:k.id,symbol:w(k.symbol,k,f)}))}):new F({symbol:w(b.defaultSymbol,b,f)})};g.connect=
function(){var a=q._asyncToGenerator(function*(b){const [{createConnection:f}]=yield Promise.all([new Promise((p,la)=>D(["./graphics/sources/connections/createConnection"],p,la)),this.load()]),k=this.geometryType?u.featureGeometryTypeKebabDictionary.toJSON(this.geometryType):null,{customParameters:ma=null,definitionExpression:na=null,geometryDefinition:oa=null,maxReconnectionAttempts:pa=0,maxReconnectionInterval:qa=20,spatialReference:ra=this.spatialReference}=b||this.createConnectionParameters(),
r=f(this.parsedUrl,this.spatialReference,ra,k,{geometry:oa,where:na},pa,qa,ma??void 0);b=K.handlesGroup([this.on("send-message-to-socket",p=>r.sendMessageToSocket(p)),this.on("send-message-to-client",p=>r.sendMessageToClient(p))]);r.once("destroy",b.remove);return r});return function(b){return a.apply(this,arguments)}}();g.createConnectionParameters=function(){return{spatialReference:this.spatialReference,customParameters:this.customParameters,definitionExpression:this.definitionExpression,geometryDefinition:this.geometryDefinition,
maxReconnectionAttempts:this.maxReconnectionAttempts,maxReconnectionInterval:this.maxReconnectionInterval}};g.createPopupTemplate=function(a){return ia.createPopupTemplate(this,a)};g.createQuery=function(){const a=new ha;a.returnGeometry=!0;a.outFields=["*"];a.where=this.definitionExpression||"1\x3d1";return a};g.getFieldDomain=function(a,b){if(!this.fields)return null;let f=null;this.fields.some(k=>{k.name===a&&(f=k.domain);return!!f});return f};g.getField=function(a){return this.fieldsIndex.get(a)};
g.serviceSupportsSpatialReference=function(a){return!0};g.sendMessageToSocket=function(a){this.emit("send-message-to-socket",a)};g.sendMessageToClient=function(a){this.emit("send-message-to-client",a)};g.write=function(a,b){const f=b?.messages;return this.webSocketUrl?(f?.push(C(this,"using a custom websocket connection cannot be written to web scenes and web maps")),null):this.parsedUrl?h.prototype.write.call(this,a,b):(f?.push(C(this,"using a client-side only connection without a url cannot be written to web scenes and web maps")),
null)};g._fetchService=function(){var a=q._asyncToGenerator(function*(b){if(!this.webSocketUrl&&this.parsedUrl)this.sourceJSON||({data:b}=yield I(this.parsedUrl.path,{query:{f:"json",...this.customParameters,...this.parsedUrl.query},responseType:"json",signal:b}),this.sourceJSON=b);else{if(!this.timeInfo?.trackIdField)throw new m("stream-layer:missing-metadata","The stream layer trackIdField must be specified.");if(!this.objectIdField){b=this.fields.find(f=>"oid"===f.type)?.name;if(!b)throw new m("stream-layer:missing-metadata",
"The stream layer objectIdField must be specified.");this.objectIdField=b}if(!this.fields)throw new m("stream-layer:missing-metadata","The stream layer fields must be specified.");this.fields.some(f=>f.name===this.objectIdField)||this.fields.push(new ba({name:this.objectIdField,alias:this.objectIdField,type:"oid"}));if(!this.geometryType)throw new m("stream-layer:missing-metadata","The stream layer geometryType must be specified.");this.webSocketUrl&&(this.url=this.webSocketUrl)}this.read(this.sourceJSON,
{origin:"service",portalItem:this.portalItem,portal:this.portalItem?.portal,url:this.parsedUrl});v.fixRendererFields(this.renderer,this.fieldsIndex);v.fixTimeInfoFields(this.timeInfo,this.fieldsIndex);this.objectIdField||(this.objectIdField="__esri_stream_id__");return fa.loadStyleRenderer(this,{origin:"service"})});return function(b){return a.apply(this,arguments)}}();q._createClass(n,[{key:"defaultPopupTemplate",get:function(){return this.createPopupTemplate()}},{key:"renderer",set:function(a){v.fixRendererFields(a,
this.fieldsIndex);this._set("renderer",a)}}]);return n}(V.FeatureReductionLayer(U.FeatureEffectLayer(S.BlendLayer(aa.TemporalLayer(Z.ScaleRangeLayer(Y.RefreshableLayer(R.ArcGISService(W.OperationalLayer(X.PortalLayer(c.MultiOriginJSONMixin(T.CustomParametersMixin(Q))))))))))));d.__decorate([e.property({type:String})],c.prototype,"copyright",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"defaultPopupTemplate",null);d.__decorate([e.property({type:String,json:{name:"layerDefinition.definitionExpression",
write:{enabled:!0,allowNull:!0}}})],c.prototype,"definitionExpression",void 0);d.__decorate([e.property({type:String})],c.prototype,"displayField",void 0);d.__decorate([e.property({type:ja})],c.prototype,"elevationInfo",void 0);d.__decorate([e.property(t.fields)],c.prototype,"fields",void 0);d.__decorate([e.property(t.fieldsIndex)],c.prototype,"fieldsIndex",void 0);d.__decorate([e.property({type:ka})],c.prototype,"geometryDefinition",void 0);d.__decorate([e.property({type:u.featureGeometryTypeKebabDictionary.apiValues,
json:{read:{reader:u.featureGeometryTypeKebabDictionary.read}}})],c.prototype,"geometryType",void 0);d.__decorate([e.property(l.labelsVisible)],c.prototype,"labelsVisible",void 0);d.__decorate([e.property({type:[da],json:{read:{source:"layerDefinition.drawingInfo.labelingInfo",reader:ea.reader},write:{target:"layerDefinition.drawingInfo.labelingInfo"}}})],c.prototype,"labelingInfo",void 0);d.__decorate([e.property(l.legendEnabled)],c.prototype,"legendEnabled",void 0);d.__decorate([e.property({type:["show",
"hide"]})],c.prototype,"listMode",void 0);d.__decorate([e.property({type:y.Integer})],c.prototype,"maxReconnectionAttempts",void 0);d.__decorate([e.property({type:y.Integer})],c.prototype,"maxReconnectionInterval",void 0);d.__decorate([e.property(l.maxScale)],c.prototype,"maxScale",void 0);d.__decorate([e.property(l.minScale)],c.prototype,"minScale",void 0);d.__decorate([e.property({type:String})],c.prototype,"objectIdField",void 0);d.__decorate([e.property({value:"ArcGISStreamLayer",type:["ArcGISStreamLayer"]})],
c.prototype,"operationalLayerType",void 0);d.__decorate([e.property(l.popupEnabled)],c.prototype,"popupEnabled",void 0);d.__decorate([e.property({type:E,json:{read:{source:"popupInfo"},write:{target:"popupInfo"}}})],c.prototype,"popupTemplate",void 0);d.__decorate([e.property({type:A})],c.prototype,"purgeOptions",void 0);d.__decorate([e.property({types:x.rendererTypes,json:{origins:{service:{write:{target:"drawingInfo.renderer",enabled:!1}},"web-scene":{name:"layerDefinition.drawingInfo.renderer",
types:x.webSceneRendererTypes,write:!0}},write:{target:"layerDefinition.drawingInfo.renderer"}}})],c.prototype,"renderer",null);d.__decorate([z.reader("service","renderer",["drawingInfo.renderer","defaultSymbol"]),z.reader("renderer",["layerDefinition.drawingInfo.renderer","layerDefinition.defaultSymbol"])],c.prototype,"readRenderer",null);d.__decorate([e.property(l.screenSizePerspectiveEnabled)],c.prototype,"screenSizePerspectiveEnabled",void 0);d.__decorate([e.property()],c.prototype,"sourceJSON",
void 0);d.__decorate([e.property({type:B,json:{origins:{service:{read:{source:"spatialReference"}}}}})],c.prototype,"spatialReference",void 0);d.__decorate([e.property({json:{read:!1}})],c.prototype,"type",void 0);d.__decorate([e.property(l.url)],c.prototype,"url",void 0);d.__decorate([e.property({type:Number})],c.prototype,"updateInterval",void 0);d.__decorate([e.property({type:String})],c.prototype,"webSocketUrl",void 0);c=d.__decorate([O.subclass("esri.layers.StreamLayer")],c);const w=P.createTypeReader({types:J.symbolTypesRenderer});
return c});