// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/mat3 ../../../chunks/mat3f64 ../../../chunks/quat ../../../chunks/quatf32 ../../../chunks/quatf64 ../../../chunks/vec3 ../../../chunks/vec3f32 ../../../chunks/vec3f64 ../../../chunks/vec4 ../../../chunks/vec4f64 ../../../geometry/support/aaBoundingBox ../../../geometry/support/plane ../../ViewingMode ./dito".split(" "),function(k,C,I,q,F,D,d,G,r,J,K,L,w,M,N){function E(a=[0,0,0],b=[-1,-1,-1],c=D.create()){return{center:r.clone(a),halfSize:G.clone(b),quaternion:F.clone(c)}}
function t(a,b){const c=w.signedDistance(b,a.center);a=A(a,w.normal(b));return c>a?1:c<-a?-1:0}function A(a,b){q.conjugate(u,a.quaternion);d.transformQuat(h,b,u);a=a.halfSize;return Math.abs(h[0]*a[0])+Math.abs(h[1]*a[1])+Math.abs(h[2]*a[2])}const u=D.create(),h=r.create(),O=r.create(),v=K.create(),z=I.create(),m=[.1,.2,.3,.4,.5,.6,.7,.8,.9,1,1.1,1.2],P=(()=>{const a=new Int8Array(162);let b=0;const c=e=>{for(let f=0;f<e.length;f++)a[b+f]=e[f];b+=6};c([6,2,3,1,5,4]);c([0,2,3,1,5,4]);c([0,2,3,7,5,
4]);c([0,1,3,2,6,4]);c([0,1,3,2,0,0]);c([0,1,5,7,3,2]);c([0,1,3,7,6,4]);c([0,1,3,7,6,2]);c([0,1,5,7,6,2]);c([0,1,5,4,6,2]);c([0,1,5,4,0,0]);c([0,1,3,7,5,4]);c([0,2,6,4,0,0]);c([0,0,0,0,0,0]);c([1,3,7,5,0,0]);c([2,3,7,6,4,0]);c([2,3,7,6,0,0]);c([2,3,1,5,7,6]);c([0,1,5,7,6,2]);c([0,1,5,7,6,4]);c([0,1,3,7,6,4]);c([4,5,7,6,2,0]);c([4,5,7,6,0,0]);c([4,5,1,3,7,6]);c([0,2,3,7,5,4]);c([6,2,3,7,5,4]);c([6,2,3,1,5,4]);return a})(),p=r.create(),x=r.create(),y=r.create(),B=D.create();k.ObbArray=function(a){this.buffer=
new ArrayBuffer(56*a);this.obbs=Array(a);for(let b=0;b<a;b++)this.obbs[b]={center:r.createView(this.buffer,56*b),halfSize:G.createView(this.buffer,56*b+24),quaternion:F.createView(this.buffer,56*b+36)}};k.clone=function(a){return E(a.center,a.halfSize,a.quaternion)};k.compute=function(a,b){b=b||E();N.computeOBB(a,b);return b};k.computeOffsetObb=function(a,b,c,e,f){q.copy(f.quaternion,a.quaternion);if(e===M.ViewingMode.Global){q.conjugate(B,a.quaternion);d.transformQuat(p,a.center,B);d.abs(x,p);d.min(y,
x,a.halfSize);d.sub(y,x,y);e=d.length(y);d.add(y,x,a.halfSize);const n=d.length(y);e<c?(d.copy(f.center,a.center),d.set(p,c,c,c),d.add(f.halfSize,a.halfSize,p)):(b=0<n?1+b/n:1,e=0<e?1+c/e:1,c=(e+b)/2,b=(e-b)/2,d.scale(f.halfSize,x,b),d.scaleAndAdd(f.halfSize,f.halfSize,a.halfSize,c),d.scale(f.center,x,c),d.scaleAndAdd(f.center,f.center,a.halfSize,b),d.sign(p,p),d.multiply(f.center,f.center,p),d.transformQuat(f.center,f.center,f.quaternion))}else e=d.set(p,0,0,1),d.scaleAndAdd(f.center,a.center,e,
(c+b)/2),q.conjugate(B,a.quaternion),d.transformQuat(e,e,B),d.abs(e,e),d.scaleAndAdd(f.halfSize,a.halfSize,e,(c-b)/2);return f};k.corners=function(a,b){for(let c=0;8>c;++c){const e=b[c];e[0]=c&1?-a.halfSize[0]:a.halfSize[0];e[1]=c&2?-a.halfSize[1]:a.halfSize[1];e[2]=c&4?-a.halfSize[2]:a.halfSize[2];d.transformQuat(e,e,a.quaternion);d.add(e,e,a.center)}};k.create=E;k.intersectLine=function(a,b,c,e=0){q.conjugate(u,a.quaternion);d.subtract(h,b,a.center);b=d.transformQuat(h,h,u);c=d.transformQuat(O,
c,u);let f=-Infinity,n=Infinity;for(let g=0;3>g;g++)if(1E-6<Math.abs(c[g])){const l=(e+a.halfSize[g]-b[g])/c[g],H=(-e-a.halfSize[g]-b[g])/c[g];f=Math.max(f,Math.min(l,H));n=Math.min(n,Math.max(l,H))}else if(b[g]>a.halfSize[g]+e||b[g]<-a.halfSize[g]-e)return!1;return f<=n};k.intersectPlane=t;k.isVisible=function(a,b){return 0>=t(a,b[0])&&0>=t(a,b[1])&&0>=t(a,b[2])&&0>=t(a,b[3])&&0>=t(a,b[4])&&0>=t(a,b[5])};k.maximumDistancePlane=function(a,b){const c=w.signedDistance(b,a.center);a=A(a,w.normal(b));
return c+a};k.minimumDistancePlane=function(a,b){const c=w.signedDistance(b,a.center);a=A(a,w.normal(b));return c-a};k.projectedArea=function(a,b,c,e,f){q.conjugate(u,a.quaternion);d.sub(h,b,a.center);d.transformQuat(h,h,u);var n=h[0]<-a.halfSize[0]?-1:h[0]>a.halfSize[0]?1:0,g=h[1]<-a.halfSize[1]?-1:h[1]>a.halfSize[1]?1:0,l=h[2]<-a.halfSize[2]?-1:h[2]>a.halfSize[2]?1:0;b=Math.abs(n)+Math.abs(g)+Math.abs(l);if(0===b)return Infinity;b=1===b?4:6;n=6*(n+3*g+9*l+13);C.fromQuat(z,a.quaternion);C.scale(z,
z,a.halfSize);for(g=0;g<b;g++)l=P[n+g],d.set(h,((l&1)<<1)-1,(l&2)-1,((l&4)>>1)-1),d.transformMat3(h,h,z),d.add(v,a.center,h),v[3]=1,J.transformMat4(v,v,c),l=1/Math.max(1E-6,v[3]),m[2*g]=v[0]*l,m[2*g+1]=v[1]*l;a=2*b-2;c=m[0]*(m[3]-m[a+1])+m[a]*(m[1]-m[a-1]);for(b=2;b<a;b+=2)c+=m[b]*(m[b+3]-m[b-1]);return Math.abs(c)*e*f*.125};k.projectedRadius=A;k.radius=function(a){return d.len(a.halfSize)};k.set=function(a,b){d.copy(b.center,a.center);d.copy(b.halfSize,a.halfSize);q.copy(b.quaternion,a.quaternion)};
k.toAaBoundingBox=function(a,b){b||(b=L.create());var c=C.fromQuat(z,a.quaternion);const e=a.halfSize[0]*Math.abs(c[0])+a.halfSize[1]*Math.abs(c[3])+a.halfSize[2]*Math.abs(c[6]),f=a.halfSize[0]*Math.abs(c[1])+a.halfSize[1]*Math.abs(c[4])+a.halfSize[2]*Math.abs(c[7]);c=a.halfSize[0]*Math.abs(c[2])+a.halfSize[1]*Math.abs(c[5])+a.halfSize[2]*Math.abs(c[8]);b[0]=a.center[0]-e;b[1]=a.center[1]-f;b[2]=a.center[2]-c;b[3]=a.center[0]+e;b[4]=a.center[1]+f;b[5]=a.center[2]+c;return b};Object.defineProperty(k,
Symbol.toStringTag,{value:"Module"})});