// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/maybe ../../../core/reactiveUtils ../../../core/scheduling ../../../core/time ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ./index ./MemoryController ./StreamDataLoader ../../support/Scheduler".split(" "),function(p,m,b,h,l,n,u,v,d,B,C,q,r,w,x,k){h=function(f){function g(){var e=
f.apply(this,arguments)||this;e.updating=!1;return e}m._inheritsLoose(g,f);return g}(h);b.__decorate([d.property({readOnly:!0})],h.prototype,"updating",void 0);h=b.__decorate([q.subclass("esri.views.3d.support.ResourceControllerMain")],h);let c=function(f){function g(){var a=f.apply(this,arguments)||this;a._immediateTask=k.ImmediateTask;a._normalTask=k.ImmediateTask;a._frameTask=null;return a}m._inheritsLoose(g,f);var e=g.prototype;e.initialize=function(){this._scheduler=k.newScheduler();this._memoryController=
w.newMemoryController(this.view);this._streamDataLoader=new x.StreamDataLoader;this._streamDataLoader.setup(r.maxDownloadSlots,r.downloadSlotsPerClient,this._scheduler);this.addHandles([n.watch(()=>this.view.state?.mode,a=>{null!=a&&(this._scheduler.state=a)},n.sync),n.watch(()=>this.view.stationary,()=>this._stationaryChangedHandler())]);this._frameTask=u.addFrameTask({update:a=>this._frame(a)});this._immediateTask=this._scheduler.registerTask(k.TaskPriority.RESOURCE_CONTROLLER_IMMEDIATE);this._normalTask=
this._scheduler.registerTask(k.TaskPriority.RESOURCE_CONTROLLER)};e.destroy=function(){this._immediateTask.remove();this._normalTask.remove();this._frameTask=l.removeMaybe(this._frameTask);this._streamDataLoader=l.destroyMaybe(this._streamDataLoader);this._memoryController=l.destroyMaybe(this._memoryController);this._scheduler=l.destroyMaybe(this._scheduler)};e.createStreamDataRequester=function(a){const t=this._streamDataLoader;return{request(y,z,A){return t.request(y,z,a,A)},get busy(){return!t.hasDownloadSlots(a)}}};
e._frame=function(a){if(!this.view.suspended){if(this.view.stateManager&&(this.view.stateManager.step(v.secondsFromMilliseconds(a.deltaTime)),!this._scheduler))return;this._scheduler.updateBudget(a)?(this._memoryController.update(),this._scheduler.frame()):this._memoryController.updating&&this._memoryController.update()}};e._stationaryChangedHandler=function(){this.memoryController.resetStableQuality()};m._createClass(g,[{key:"immediate",get:function(){return this._immediateTask}},{key:"normal",get:function(){return this._normalTask}},
{key:"updating",get:function(){return!!(this._memoryController?.updating||this._streamDataLoader?.updating||this._immediateTask?.updating)}},{key:"scheduler",get:function(){return this._scheduler}},{key:"memoryController",get:function(){return this._memoryController}},{key:"test",get:function(){return{getQueueStats:a=>this._streamDataLoader.test.loadQueue.getStatsForType(a)}}}]);return g}(h);b.__decorate([d.property({constructOnly:!0})],c.prototype,"view",void 0);b.__decorate([d.property()],c.prototype,
"_scheduler",void 0);b.__decorate([d.property()],c.prototype,"_memoryController",void 0);b.__decorate([d.property()],c.prototype,"_streamDataLoader",void 0);b.__decorate([d.property()],c.prototype,"_immediateTask",void 0);b.__decorate([d.property()],c.prototype,"_normalTask",void 0);b.__decorate([d.property({readOnly:!0})],c.prototype,"updating",null);c=b.__decorate([q.subclass("esri.views.3d.support.ResourceControllerImpl")],c);p.newResourceController=function(f){return new c({view:f})};Object.defineProperty(p,
Symbol.toStringTag,{value:"Module"})});