// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/Accessor ../../../../../core/byteSizeEstimations ../../../../../core/maybe ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/data/BoundsStore ../../../../../layers/support/TileInfo ../../../../../layers/support/TileKey ../../../../../rest/query/operations/query ./FeatureServiceTileCache".split(" "),
function(n,u,v,C,w,l,x,M,N,D,t,E,F,y,G,H,I){function J(h){return h.reduce((f,e)=>{var a=e.geometry;if(l.isNone(a))a=0;else{var b=w.estimateFixedArraySize(a.lengths,4);a=32+w.estimateFixedArraySize(a.coords,8)+b}e=32+a+w.estimateAttributesObjectSize(e.attributes);return f+e},0)}n.FeatureServiceTileStore=function(h){function f(a){a=h.call(this,a)||this;a.tileInfo=null;a.extent=null;a.maximumByteSize=10*w.ByteSizeUnit.MEGABYTES;a._tileBounds=new F.BoundsStore;a._tiles=new I.FeatureServiceTileCache;a._refCounts=
new Map;a._tileFeatureCounts=new Map;a._tmpBoundingRect=t.create();return a}u._inheritsLoose(f,h);var e=f.prototype;e.add=function(a,b){const c=[];for(const d of b)this._referenceFeature(d.objectId)===p.ADDED&&c.push(d);this._addTileStorage(a,new Set(b.map(d=>d.objectId)),J(b));this.featureStore.addMany(c);this._tiles.applyByteSizeLimit(this.maximumByteSize,d=>this._removeTileStorage(d))};e.destroy=function(){this.clear();this._tileFeatureCounts.clear()};e.clear=function(){this.featureStore.clear();
this._tileBounds.clear();this._tiles.clear();this._refCounts.clear()};e.refresh=function(){this.clear();this._tileFeatureCounts.clear()};e.processEdits=function(a,b,c){this._processEditsDelete(a.deletedFeatures.concat(a.updatedFeatures));return this._processEditsRefetch(a.addedFeatures.concat(a.updatedFeatures),b,c)};e._addTileStorage=function(a,b,c){const d=a.id;this._tiles.set(d,new K(a,b,c));this._tileBounds.set(d,a.extent);this._tileFeatureCounts.set(d,b.size)};e._remove=function({id:a}){(a=this._tiles.get(a))&&
this._removeTileStorage(a)};e._removeTileStorage=function(a){const b=[];for(const c of a.objectIds)this._unreferenceFeature(c)===p.REMOVED&&b.push(c);this.featureStore.removeManyById(b);a=a.data.id;this._tiles.delete(a);this._tileBounds.delete(a)};e._processEditsDelete=function(a){this.featureStore.removeManyById(a);for(const [,b]of this._tiles){for(const c of a)b.objectIds.delete(c);this._tileFeatureCounts.set(b.data.id,b.objectIds.size)}for(const b of a)this._refCounts.delete(b)};e._processEditsRefetch=
function(){var a=u._asyncToGenerator(function*(b,c,d){b=(yield c(b,d)).features;const {hasZ:g,hasM:k}=this.featureStore;for(const q of b)b=E.getBoundsOptimizedGeometry(this._tmpBoundingRect,q.geometry,g,k),l.isNone(b)||this._tileBounds.forEachInBounds(b,m=>{m=this._tiles.get(m);this.featureStore.add(q);const r=q.objectId;m.objectIds.has(r)||(m.objectIds.add(r),this._referenceFeature(r),this._tileFeatureCounts.set(m.data.id,m.objectIds.size))})});return function(b,c,d){return a.apply(this,arguments)}}();
e.process=function(a,b=()=>!0){if(l.isNone(this.tileInfo)||!a.extent||l.isSome(this.extent)&&!t.intersects(t.fromExtent(this.extent,this._tmpBoundingRect),a.extent)||this._tiles.has(a.id))return new z(a);const c=this._createTileTree(a,this.tileInfo);this._simplify(c,b,null,0,1);return this._collectMissingTiles(a,c,this.tileInfo)};e.getFeatureCount=function(a){return this._tileFeatureCounts.get(a.id)??0};e.fetchCount=function(){var a=u._asyncToGenerator(function*(b,c,d,g){const k=this._tileFeatureCounts.get(b.id);
if(null!=k)return k;c=yield H.executeQueryForCount(c,d,g);this._tileFeatureCounts.set(b.id,c.data.count);return c.data.count});return function(b,c,d,g){return a.apply(this,arguments)}}();e._createTileTree=function(a,b){const c=new A(a.level,a.row,a.col);b.updateTileInfo(c,y.ExtrapolateOptions.POWER_OF_TWO);this._tileBounds.forEachInBounds(a.extent,d=>{(d=this._tiles.get(d)?.data)&&this._tilesAreRelated(a,d)&&this._populateChildren(c,d,b,this._tileFeatureCounts.get(d.id)||0)});return c};e._tilesAreRelated=
function(a,b){if(!a||!b)return!1;if(a.level===b.level)return a.row===b.row&&a.col===b.col;const c=a.level<b.level,d=c?a:b;a=c?b:a;b=1<<a.level-d.level;return Math.floor(a.row/b)===d.row&&Math.floor(a.col/b)===d.col};e._populateChildren=function(a,b,c,d){var g=b.level-a.level-1;if(0>g)a.isLeaf=!0;else{var k=b.row>>g,q=b.col>>g;g=(k-(a.row<<1)<<1)+(q-(a.col<<1));var m=a.children[g];l.isSome(m)?this._populateChildren(m,b,c,d):(k=new A(a.level+1,k,q),c.updateTileInfo(k,y.ExtrapolateOptions.POWER_OF_TWO),
a.children[g]=k,this._populateChildren(k,b,c,d))}};e._simplify=function(a,b,c,d,g){const k=g*g;if(a.isLeaf)return b(this.getFeatureCount(a),g)?0:(this._remove(a),l.isSome(c)&&(c.children[d]=null),k);g/=2;const q=g*g;let m=0;for(let r=0;r<a.children.length;r++){const B=a.children[r];m+=l.isSome(B)?this._simplify(B,b,a,r,g):q}0===m?this._mergeChildren(a):.18751>1-m/k&&(this._purge(a),l.isSome(c)&&(c.children[d]=null),m=k);return m};e._mergeChildren=function(a){const b=new Set;let c=0;this._forEachLeaf(a,
d=>{const g=this._tiles.get(d.id);if(g){c+=g.byteSize;for(const k of g.objectIds)b.has(k)||(b.add(k),this._referenceFeature(k));this._remove(d)}});this._addTileStorage(a,b,c);a.isLeaf=!0;a.children[0]=a.children[1]=a.children[2]=a.children[3]=null;this._tileFeatureCounts.set(a.id,b.size)};e._forEachLeaf=function(a,b){for(const c of a.children)l.isNone(c)||(c.isLeaf?b(c):this._forEachLeaf(c,b))};e._purge=function(a){if(!l.isNone(a))if(a.isLeaf)this._remove(a);else for(let b=0;b<a.children.length;b++)this._purge(a.children[b]),
a.children[b]=null};e._collectMissingTiles=function(a,b,c){a=new L(c,a,this.extent);this._collectMissingTilesRecurse(b,a,1);return a.info};e._collectMissingTilesRecurse=function(a,b,c){if(!a.isLeaf)if(a.hasChildren){c/=2;for(let d=0;d<a.children.length;d++){const g=a.children[d];l.isNone(g)?b.addMissing(a.level+1,(a.row<<1)+((d&2)>>1),(a.col<<1)+(d&1),c):this._collectMissingTilesRecurse(g,b,c)}}else b.addMissing(a.level,a.row,a.col,c)};e._referenceFeature=function(a){const b=(this._refCounts.get(a)||
0)+1;this._refCounts.set(a,b);return 1===b?p.ADDED:p.UNCHANGED};e._unreferenceFeature=function(a){const b=(this._refCounts.get(a)||0)-1;if(0===b)return this._refCounts.delete(a),p.REMOVED;0<b&&this._refCounts.set(a,b);return p.UNCHANGED};u._createClass(f,[{key:"debugInfo",get:function(){return Array.from(this._tiles.values()).map(({data:a})=>({data:a,featureCount:this._tileFeatureCounts.get(a.id)||0}))}},{key:"test",get:function(){return{tiles:Array.from(this._tiles.values()).map(a=>`${a.data.id}:[${Array.from(a.objectIds)}]`),
featureReferences:Array.from(this._refCounts.keys()).map(a=>`${a}:${this._refCounts.get(a)}`)}}}]);return f}(C);v.__decorate([x.property({constructOnly:!0})],n.FeatureServiceTileStore.prototype,"featureStore",void 0);v.__decorate([x.property()],n.FeatureServiceTileStore.prototype,"tileInfo",void 0);v.__decorate([x.property()],n.FeatureServiceTileStore.prototype,"extent",void 0);v.__decorate([x.property()],n.FeatureServiceTileStore.prototype,"maximumByteSize",void 0);n.FeatureServiceTileStore=v.__decorate([D.subclass("esri.views.interactive.snapping.featureSources.featureServiceSource.FeatureServiceTileStore")],
n.FeatureServiceTileStore);let K=function(h,f,e){this.data=h;this.objectIds=f;this.byteSize=e},A=function(){function h(f,e,a){this.level=f;this.row=e;this.col=a;this.isLeaf=!1;this.extent=null;this.children=[null,null,null,null]}u._createClass(h,[{key:"hasChildren",get:function(){return!this.isLeaf&&(l.isSome(this.children[0])||l.isSome(this.children[1])||l.isSome(this.children[2])||l.isSome(this.children[3]))}}]);return h}(),z=function(){function h(f,e=[]){this.missingTiles=e;this.coveredArea=this.fullArea=
0;this.coveredArea=this.fullArea=t.area(f.extent)}h.prototype.prepend=function(f){this.missingTiles=f.missingTiles.concat(this.missingTiles);this.coveredArea+=f.coveredArea;this.fullArea+=f.fullArea};return h}(),L=function(){function h(f,e,a){this._tileInfo=f;this._extent=null;this.info=new z(e);l.isSome(a)&&(this._extent=t.fromExtent(a))}h.prototype.addMissing=function(f,e,a,b){f=new G.TileKey(null,f,e,a);this._tileInfo.updateTileInfo(f,y.ExtrapolateOptions.POWER_OF_TWO);l.isNone(f.extent)||l.isSome(this._extent)&&
!t.intersects(this._extent,f.extent)||(this.info.missingTiles.push({data:f,resolution:b}),this.info.coveredArea-=t.area(f.extent))};return h}();var p;(function(h){h[h.ADDED=0]="ADDED";h[h.REMOVED=1]="REMOVED";h[h.UNCHANGED=2]="UNCHANGED"})(p||(p={}));n.ProcessResult=z;Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});