// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Error ../../../core/handleUtils ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../rest/support/FeatureSet ./FeatureLayerView2D ./support/util".split(" "),function(n,l,t,v,m,p,q,g,C,w,x,y,z){function u(e,f){if(m.isNone(e)&&m.isNone(f))return null;
const c={};m.isSome(f)&&(c.geometry=f.toJSON());m.isSome(e)&&(c.where=e);return c}g=function(e){function f(){var a=e.apply(this,arguments)||this;a._enabledEventTypes=new Set;a._isUserPaused=!1;a.errorString=null;a.connectionStatus="disconnected";return a}n._inheritsLoose(f,e);var c=f.prototype;c.initialize=function(){this.addHandles([p.watch(()=>this.layer.customParameters,a=>this._proxy.updateCustomParameters(a)),this.layer.on("send-message-to-socket",a=>this._proxy.sendMessageToSocket(a)),this.layer.on("send-message-to-client",
a=>this._proxy.sendMessageToClient(a)),p.watch(()=>this.layer.purgeOptions,()=>this._update()),p.watch(()=>this.suspended,a=>{a?this._proxy.pauseStream():this._isUserPaused||this._proxy.resumeStream()})],"constructor")};c.pause=function(){this._isUserPaused=!0;this._proxy.pauseStream()};c.resume=function(){this._isUserPaused=!1;this._proxy.resumeStream()};c.on=function(a,b){if(Array.isArray(a))return v.handlesGroup(a.map(r=>this.on(r,b)));const d=["data-received","message-received"].includes(a);d&&
(this._enabledEventTypes.add(a),this._proxy.enableEvent(a,!0));const h=e.prototype.on.call(this,a,b),k=this;return{remove(){h.remove();d&&(k._proxy.closed||k.hasEventListener(a)||k._proxy.enableEvent(a,!1))}}};c.queryLatestObservations=function(a,b){if(!(this.layer.timeInfo?.endField||this.layer.timeInfo?.startField||this.layer.timeInfo?.trackIdField))throw new t("streamlayer-no-timeField","queryLatestObservation can only be used with services that define a TrackIdField");return this._proxy.queryLatestObservations(this._cleanUpQuery(a),
b).then(d=>{d=x.fromJSON(d);d.features.forEach(h=>{h.layer=this.layer;h.sourceLayer=this.layer});return d})};c.detach=function(){e.prototype.detach.call(this);this.connectionStatus="disconnected"};c._createClientOptions=function(){return{...e.prototype._createClientOptions.call(this),setProperty:a=>{this.set(a.propertyName,a.value)}}};c._createTileRendererHash=function(a){var b=JSON.stringify(this.layer.purgeOptions);const d=JSON.stringify(u(this.layer.definitionExpression,this.layer.geometryDefinition));
b=`${b}.${d})`;return e.prototype._createTileRendererHash.call(this,a)+b};c._createServiceOptions=function(){var a=n._asyncToGenerator(function*(){const b=this.layer,{objectIdField:d}=b,h=b.fields.map(A=>A.toJSON()),k=z.toJSONGeometryType(b.geometryType),r=b.timeInfo&&b.timeInfo.toJSON()||null,B=b.spatialReference?b.spatialReference.toJSON():null;return{type:"stream",fields:h,geometryType:k,objectIdField:d,timeInfo:r,source:this.layer.parsedUrl,serviceFilter:u(this.layer.definitionExpression,this.layer.geometryDefinition),
purgeOptions:this.layer.purgeOptions.toJSON(),enabledEventTypes:Array.from(this._enabledEventTypes.values()),spatialReference:B,maxReconnectionAttempts:this.layer.maxReconnectionAttempts,maxReconnectionInterval:this.layer.maxReconnectionInterval,updateInterval:this.layer.updateInterval,customParameters:b.customParameters}});return function(){return a.apply(this,arguments)}}();n._createClass(f,[{key:"connectionError",get:function(){if(this.errorString)return new t("stream-controller",this.errorString)}}]);
return f}(y);l.__decorate([q.property()],g.prototype,"errorString",void 0);l.__decorate([q.property({readOnly:!0})],g.prototype,"connectionError",null);l.__decorate([q.property()],g.prototype,"connectionStatus",void 0);return g=l.__decorate([w.subclass("esri.views.2d.layers.StreamLayerView2D")],g)});