// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/events ../core/Handles ../core/maybe ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/accessorSupport/decorators/subclass ../intl/date ../webdoc/support/SlideThumbnail ./Widget ./Bookmarks/BookmarksUserState ./Bookmarks/BookmarksViewModel ./Bookmarks/css ./FeatureTable/Grid/support/ButtonMenu ./FeatureTable/Grid/support/ButtonMenuItem ./support/Heading ./support/widgetUtils ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ../chunks/sortable.esm".split(" "),
function(B,r,l,F,G,w,p,m,H,k,I,t,J,K,x,C,c,L,y,M,N,z,O,f,P){const D={addBookmark:!0,thumbnail:!0,time:!0},A=/^https:\/\/.*/i;k=function(E){function u(a,b){a=E.call(this,a,b)||this;a._handles=new G;a._addInputNode=null;a._editInputNode=null;a._urlEditInputNode=null;a._addBookmarkButtonNode=null;a._focusAddBookmarkButton=!1;a._focusEditInputBox=!1;a._focusAddInputBox=!1;a._focusUrlEditInputBox=!1;a._sortable=null;a._sortableNode=null;a._focusSortUid=null;a._selectedSortUid=null;a._sortableSavedItems=
null;a._editIncludeTimeExtent=null;a._userState=null;a.disabled=!1;a.editingEnabled=!1;a.headingLevel=2;a.iconClass=c.CSS.widgetIcon;a.messages=null;a.messagesCommon=null;a.messagesUnits=null;a.viewModel=new C;a.visibleElements={...D};return a}r._inheritsLoose(u,E);var e=u.prototype;e.initialize=function(){this.addHandles([p.watch(()=>this.viewModel?.bookmarks,()=>this._bookmarksInitialized(),p.initial),p.watch(()=>this.editingEnabled,()=>this._toggleSorting(),p.initial)])};e.destroy=function(){this._destroySortable();
this._handles.destroy();this._handles=null;this._editMenu.destroy()};e.loadDependencies=function(){return Promise.all([new Promise((a,b)=>B(["../chunks/calcite-label"],a,b)),new Promise((a,b)=>B(["../chunks/calcite-switch"],a,b))])};e.castVisibleElements=function(a){return{...D,...a}};e.endAddBookmark=function(){this._userState=null};e.goTo=function(a){return this.viewModel.goTo(a)};e.render=function(){var {state:a}=this.viewModel;a="loading"===a?this.renderLoading():this.renderBookmarks();return f.tsx("div",
{class:this.classes(c.CSS.base,c.CSS.esriWidget,{[c.CSS.esriWidgetDisabled]:this.disabled})},a)};e.startAddBookmark=function(){this._userState=new x({state:"add"});this._focusAddInputBox=!0;this.scheduleRender()};e.renderLoading=function(){return f.tsx("div",{class:c.CSS.loaderContainer,key:"loader",tabIndex:this.disabled?-1:null},f.tsx("div",{class:c.CSS.loader}))};e.renderNoBookmarksContainer=function(){const {messages:a,disabled:b}=this;return f.tsx("div",{class:c.CSS.noBookmarksContainer,key:"no-bookmarks",
tabIndex:b?-1:null},f.tsx("span",{"aria-hidden":"true",class:this.classes(c.CSS.noBookmarksIcon,c.CSS.widgetIcon)}),f.tsx(M.Heading,{level:this.headingLevel,class:this.classes(c.CSS.header,c.CSS.noBookmarksHeader)},a?.noBookmarksHeading),f.tsx("p",{class:c.CSS.noBookmarksDescription},a?.noBookmarksDescription))};e.renderAddBookmarkLoading=function(){return f.tsx("div",{key:"adding-bookmark",class:c.CSS.addingBookmark},f.tsx("span",{"aria-hidden":"true",class:this.classes(c.CSS.loading,c.CSS.rotating)}),
this.messages?.addingBookmark)};e.renderBookmarkItems=function(a){if(!a)return null;const {_userState:b,editingEnabled:d}=this;return a.map(g=>d&&g&&b&&("edit"===b.state||"edit-thumbnail"===b.state)&&b.bookmark===g?"edit-thumbnail"===b.state?this.renderEditingBookmarkUrl(b.editedBookmark):this.renderEditingBookmark(b.editedBookmark):this.renderBookmark(g)).toArray()};e.renderBookmarksContainer=function(a){const {_userState:b,editingEnabled:d,disabled:g}=this;var h="add"===b?.state;const n=d&&!h?this.renderAddBookmarkButton():
null;h=d?h&&b.loading?this.renderAddBookmarkLoading():"add"===b?.state?this.renderAddingBookmark():null:null;return[f.tsx("ul",{key:"bookmark-list","aria-label":this.messages?.widgetLabel,class:this.classes(c.CSS.bookmarkList,{[c.CSS.bookmarkListSortable]:this.editingEnabled}),afterCreate:this._sortNodeCreated,afterRemoved:this._destroySortable,"data-node-ref":"_sortableNode",bind:this,tabIndex:g?-1:null},this.renderBookmarkItems(a)),n,h]};e.renderAddBookmarkButton=function(){return this.visibleElements.addBookmark?
f.tsx("div",{key:"add-bookmark-item",class:c.CSS.addBookmark},f.tsx("button",{class:this.classes(c.CSS.esriButton,c.CSS.esriButtonTertiary,c.CSS.addBookmarkButton),disabled:this.disabled,onclick:this.startAddBookmark,afterCreate:this._storeAddBookmarkButton,afterUpdate:this._storeAddBookmarkButton,"data-node-ref":"_addBookmarkButtonNode",bind:this,type:"button"},f.tsx("span",{"aria-hidden":"true",class:this.classes(c.CSS.addBookmarkIcon,c.CSS.iconPlus)}),this.messages?.addBookmark)):null};e.renderBookmarks=
function(){var {bookmarks:a}=this.viewModel,b=a&&a.filter(Boolean);b=(a=b&&b.length)||this.editingEnabled?this.renderBookmarksContainer(b):null;return[a?null:this.renderNoBookmarksContainer(),b]};e.renderEditContainer=function(a){const {messagesCommon:b,disabled:d}=this,g=this._getBookmarkTitle(a);return f.tsx("div",{class:c.CSS.bookmarkEditButtonContainer,key:"edit-container"},f.tsx("button",{disabled:d,title:`${b?.edit} ${g}`,"aria-label":`${b?.edit} ${g}`,"data-bookmark":a,onclick:this._showEditBookmarkForm,
bind:this,class:c.CSS.bookmarkEditButton,type:"button"},f.tsx("span",{"aria-hidden":"true",class:c.CSS.iconEdit})))};e.renderDragHandle=function(a){const {messagesCommon:b,disabled:d}=this,g=this._getBookmarkTitle(a);return f.tsx("div",{role:"button",tabIndex:d?-1:0,key:"drag-handle",bind:this,class:c.CSS.bookmarkDragHandle,onkeydown:this._dragHandleKeydown,afterCreate:this._focusDragHandle,afterUpdate:this._focusDragHandle,onblur:this._dragHandleBlur,"aria-pressed":this._selectedSortUid===a.uid?
"true":"false","aria-label":`${b?.dragHandleTitle} ${g}`,title:`${b?.dragHandleTitle} ${g}`,["data-bookmark-uid"]:a.uid},f.tsx("span",{"aria-hidden":"true",class:this.classes(c.CSS.bookmarkDragHandleIcon,c.CSS.iconHandle)}))};e.renderBookmarkImageIcon=function(){return f.tsx("span",{"aria-hidden":"true",class:this.classes(c.CSS.bookmarkIcon,c.CSS.widgetIcon)})};e.renderBookmarkImage=function(a){const {visibleElements:b}=this;({thumbnail:a}=a);a=a&&a.url||"";return b.thumbnail&&a?f.tsx("img",{src:a,
alt:"",class:c.CSS.bookmarkImage}):null};e.renderBookmarkTimeSwitch=function(a){const {messages:b,disabled:d}=this;({timeExtent:a}=a);const {view:g}=this.viewModel;return g.timeExtent||a?f.tsx("calcite-label",{layout:"inline-space-between"},b.includeTimeExtent,f.tsx("calcite-switch",{scale:"s",disabled:d,checked:!!a,onCalciteSwitchChange:h=>{this._editIncludeTimeExtent=!!h.currentTarget.checked}})):null};e.renderBookmarkTimeExtent=function(a){const {visibleElements:b}=this;({timeExtent:a}=a);return a?
f.tsx("span",{class:c.CSS.timeExtent},[w.isSome(a.start)&&f.tsx("span",{key:"start-date-group",class:c.CSS.timeExtentGroup},f.tsx("span",{key:"start-date",class:c.CSS.timeExtentDate},this._formatDate(a.start)),b.time&&f.tsx("span",{key:"start-time",class:c.CSS.timeExtentTime},this._formatTime(a.start))),w.isSome(a.end)&&(w.isNone(a.start)||a.start.getTime()!==a.end.getTime())&&f.tsx("span",{key:"end-date-group",class:c.CSS.timeExtentGroup},f.tsx("span",{key:"end-date",class:c.CSS.timeExtentDate},
this._formatDate(a.end)),b.time&&f.tsx("span",{key:"end-time",class:c.CSS.timeExtentTime},this._formatTime(a.end)))]):null};e.renderBookmarkButton=function(a){const {disabled:b}=this;var {timeExtent:d}=a;const {abilities:g}=this.viewModel,h=this._getBookmarkTitle(a);var {thumbnail:n}=a;n=f.tsx("div",{class:this.classes(c.CSS.bookmarkImageContainer,n&&n.url?c.CSS.bookmarkImageContainerHasImage:null)},this.renderBookmarkImage(a)||this.renderBookmarkImageIcon());d=g.time&&d?f.tsx("span",{key:"time-extent",
class:c.CSS.bookmarkTimeExtent},this.renderBookmarkTimeExtent(a)):null;return f.tsx("button",{disabled:b,key:"bookmark-button",class:c.CSS.bookmarkButton,bind:this,"data-bookmark":a,onclick:this._goToBookmark,type:"button"},n,f.tsx("div",{class:c.CSS.bookmarkLabel},f.tsx("span",{key:"bookmark-title",class:c.CSS.bookmarkName},h),d))};e.renderBookmark=function(a){var {activeBookmark:b}=this.viewModel;b={[c.CSS.bookmarkActive]:b===a};const d=this.editingEnabled?this.renderEditContainer(a):null,g={["data-bookmark-uid"]:a.uid},
h=this.editingEnabled?this.renderDragHandle(a):null;return f.tsx("li",{key:a,class:this.classes(c.CSS.bookmark,b),...g},h,this.renderBookmarkButton(a),d)};e.renderEditingBookmarkName=function(a){const {messages:b,_userState:d,disabled:g}=this,h="name-required"===d.validationState;return f.tsx("label",{class:c.CSS.authoringLabel},b?.title,h?f.tsx("strong",null,b?.invalidTitle):null,f.tsx("input",{required:!0,disabled:g,bind:this,class:this.classes(c.CSS.esriInput,h?c.CSS.authoringInputInvalid:null),
type:"text",value:a.name,afterCreate:this._storeEditInput,afterUpdate:this._focusEditInput,"data-bookmark":a,"data-node-ref":"_editInputNode",placeholder:b?.titlePlaceholder}))};e.renderEditingBookmarkUrlActions=function(){const {messagesCommon:a,disabled:b}=this;return f.tsx("div",{class:c.CSS.authoringActions},f.tsx("input",{type:"button",disabled:b,value:a?.back,class:this.classes(c.CSS.esriButton,c.CSS.esriButtonTertiary),onclick:this._closeUrlEditBookmarkForm,bind:this}),f.tsx("input",{class:c.CSS.esriButton,
disabled:b,type:"submit",value:a?.add}))};e.renderEditingBookmarkActions=function(){const {messagesCommon:a,disabled:b}=this,{bookmark:d}=this._userState;return f.tsx("div",{class:c.CSS.authoringActions},f.tsx("input",{type:"button",disabled:b,value:a?.delete,class:this.classes(c.CSS.esriButton,c.CSS.esriButtonTertiary,c.CSS.authoringDeleteButton),"data-bookmark":d,onclick:this._deleteBookmark,bind:this}),f.tsx("input",{disabled:b,type:"button",value:a?.cancel,class:this.classes(c.CSS.esriButton,
c.CSS.esriButtonTertiary),onclick:this._closeEditBookmarkForm,bind:this}),f.tsx("input",{class:c.CSS.esriButton,disabled:b,type:"submit",value:a?.save}))};e.renderEditingBookmarkUrlInput=function(a){const {messages:b,_userState:d,disabled:g}=this;var h=a.thumbnail?.url;h=A.test(h)?h:null;const n="absolute-url-required"===d.validationState;return f.tsx("label",{class:c.CSS.authoringLabel},n?f.tsx("strong",null,b?.invalidImageUrl):null,f.tsx("input",{required:!0,disabled:g,bind:this,class:this.classes(c.CSS.esriInput,
n?c.CSS.authoringInputInvalid:null),type:"text",value:h,afterCreate:this._storeUrlEditInput,afterUpdate:this._focusUrlEditInput,"data-bookmark":a,"data-node-ref":"_urlEditInputNode",title:b?.imageUrlTooltip,placeholder:b&&`https://<${b.imageUrlPlaceholder}>`}))};e.renderEditingBookmarkUrl=function(a){return f.tsx("li",{key:"edit-bookmark-url-form",class:c.CSS.authoringCard,["data-bookmark-uid"]:a.uid},f.tsx("form",{class:c.CSS.authoringForm,disabled:this.disabled,onsubmit:this._editBookmarkUrlSubmit,
bind:this},this.renderEditingBookmarkUrlInput(a),this.renderEditingBookmarkUrlActions()))};e.renderEditingBookmark=function(a){const b={["data-bookmark-uid"]:a.uid};var {abilities:d}=this.viewModel;d=d.time?f.tsx("div",{key:"edit-bookmark-time-container",class:c.CSS.timeExtentContainer},this.renderBookmarkTimeSwitch(a),this._editIncludeTimeExtent&&this.renderBookmarkTimeExtent(a)):null;return f.tsx("li",{key:"edit-bookmark-form",class:c.CSS.authoringCard,...b},f.tsx("form",{class:c.CSS.authoringForm,
disabled:this.disabled,onsubmit:this._editBookmarkSubmit,bind:this},f.tsx("div",{class:c.CSS.authoringContainer},f.tsx("div",{class:c.CSS.bookmarkImageContainer},this.renderBookmarkImage(a),this._editMenu.render()),this.renderEditingBookmarkName(a)),d,this.renderEditingBookmarkActions()))};e.renderAddingBookmarkName=function(){const {_userState:a,messages:b,disabled:d}=this,g="name-required"===a.validationState;return f.tsx("label",{class:c.CSS.authoringLabel},b?.title,g?f.tsx("strong",null,b?.invalidTitle):
null,f.tsx("input",{required:!0,disabled:d,bind:this,class:this.classes(c.CSS.esriInput,g?c.CSS.authoringInputInvalid:null),type:"text",afterCreate:this._storeAddInput,afterUpdate:this._focusAddInput,"data-node-ref":"_addInputNode",value:"",placeholder:b?.titlePlaceholder}))};e.renderAddingBookmarkActions=function(){const {messagesCommon:a,disabled:b}=this;return f.tsx("div",{class:this.classes(c.CSS.authoringActions)},f.tsx("input",{type:"button",disabled:b,value:a?.cancel,class:this.classes(c.CSS.esriButton,
c.CSS.esriButtonTertiary,c.CSS.authoringCancelButton),onclick:this._endAddBookmark.bind(this),bind:this}),f.tsx("input",{class:c.CSS.esriButton,disabled:b,type:"submit",value:a?.add}))};e.renderAddingBookmark=function(){return f.tsx("div",{key:"add-bookmark-form",class:c.CSS.authoringCard},f.tsx("form",{class:c.CSS.authoringForm,onsubmit:this._addBookmarkSubmit,bind:this},this.renderAddingBookmarkName(),this.renderAddingBookmarkActions()))};e._getBookmarkTitle=function(a){return a.name||this.messagesCommon?.untitled};
e._formatDate=function(a){return a?t.formatDate(a,t.convertDateFormatToIntlOptions("short-date")):null};e._formatTime=function(a){return a?t.formatDate(a,t.convertDateFormatToIntlOptions("long-time")):null};e._dragHandleBlur=function(){this._selectedSortUid=null;this.scheduleRender()};e._dragHandleKeydown=function(a){const {_sortableSavedItems:b}=this,d=F.eventKey(a);if("ArrowDown;ArrowUp;Escape;Tab; ;Enter".split(";").includes(d)){var {_sortable:g,_selectedSortUid:h}=this,n=g.toArray(),q=a.target.getAttribute("data-bookmark-uid"),
v=n.indexOf(q);N.isActivationKey(d)?(this._selectedSortUid=(n=h&&h===q)?null:q,this._sortableSavedItems=n?null:this._sortable.toArray(),this.scheduleRender()):"Tab"===d?(this._selectedSortUid=null,this.scheduleRender()):"Escape"===d&&b?(a.stopPropagation(),this._selectedSortUid=null,this._updateSortItems(b,g,q),this.scheduleRender()):-1!==v&&h&&(a="ArrowUp"===d?v-1:v+1,a>=n.length||-1>=a||(n.splice(a,0,n.splice(v,1)[0]),this._updateSortItems(n,g,q)))}};e._updateSortItems=function(a,b,d){b.sort(a);
this._sortBookmarks(b);this._selectedSortUid=this._focusSortUid=d};e._focusDragHandle=function(a){const {_focusSortUid:b}=this;a&&b&&a.getAttribute("data-bookmark-uid")===b&&(a.focus(),this._focusSortUid=null)};e._toggleSorting=function(){const {_sortable:a,_sortableNode:b,editingEnabled:d,disabled:g}=this;if(b)if(a)a.option("disabled",g||!d);else{const h=P.Sortable.create(b,{dataIdAttr:"data-bookmark-uid",handle:`.${c.CSS.bookmarkDragHandle}`,group:"bookmarks",disabled:g||!d,onSort:()=>this._sortBookmarks(h)});
this._sortable=h}};e._sortNodeCreated=function(a){this._sortableNode=a;this._toggleSorting()};e._sortBookmarks=function(a){const {bookmarks:b}=this.viewModel;if(b){var d=a.toArray();b.sort((g,h)=>{g=d.indexOf(g.uid);h=d.indexOf(h.uid);return g>h?1:g<h?-1:0})}};e._destroySortable=function(){const {_sortable:a}=this;a&&a.destroy();this._sortable=null};e._endAddBookmark=function(){this._focusAddBookmarkButton=!0;this.endAddBookmark()};e._bookmarksInitialized=function(){const {_handles:a}=this;a.remove("bookmarks-init");
a.add(p.on(()=>this.viewModel?.bookmarks,"change",()=>this._bookmarksChanged()),"bookmarks-init")};e._bookmarksChanged=function(){var {bookmarks:a}=this.viewModel;const {_handles:b}=this;b.remove("bookmarks-change");a=a.map(d=>p.watch(()=>[d?.name,d?.thumbnail?.url],()=>this.scheduleRender()));b.add(a,"bookmarks-change");this.scheduleRender()};e._showEditBookmarkForm=function(a){a=a.currentTarget["data-bookmark"];this._editIncludeTimeExtent=!!a.timeExtent;this._focusEditInputBox=!0;this._userState=
new x({bookmark:a,state:"edit"});this.viewModel.goTo(a);this.scheduleRender()};e._closeUrlEditBookmarkForm=function(){this._focusEditInputBox=!0;this._userState.state="edit"};e._closeEditBookmarkForm=function(){this._userState=null};e._addBookmarkSubmit=function(a){a.preventDefault();const {_addInputNode:b,_userState:d}=this,g=b&&b.value.trim();g?(d.loading=!0,this.viewModel.createBookmark().then(h=>{h.name=g;this.viewModel.bookmarks.add(h);this._endAddBookmark()})):d.validationState="name-required"};
e._editBookmarkAndClose=function(){var a=r._asyncToGenerator(function*(b,d){const {viewModel:g}=this;yield g.editBookmark(b,{...g.defaultEditOptions,...d});this._closeEditBookmarkForm()});return function(b,d){return a.apply(this,arguments)}}();e._editBookmarkSubmit=function(a){a.preventDefault();const {_editInputNode:b,_userState:d,_editIncludeTimeExtent:g}=this;(a=b&&b.value.trim())?(d.bookmark.name=a,d.bookmark.thumbnail=d.editedBookmark.thumbnail,g||(d.bookmark.timeExtent=null),this._editBookmarkAndClose(d.bookmark,
{takeScreenshot:!1,captureTimeExtent:g})):d.validationState="name-required"};e._storeAddBookmarkButton=function(a){this._addBookmarkButtonNode=a;this._focusAddBookmark()};e._storeEditInput=function(a){this._editInputNode=a;this._focusEditInput()};e._storeAddInput=function(a){this._addInputNode=a;this._focusAddInput()};e._storeUrlEditInput=function(a){this._urlEditInputNode=a;this._focusUrlEditInput()};e._focusUrlEditInput=function(){this._urlEditInputNode&&this._focusUrlEditInputBox&&(this._focusUrlEditInputBox=
!1,this._urlEditInputNode.focus())};e._focusAddInput=function(){this._addInputNode&&this._focusAddInputBox&&(this._focusAddInputBox=!1,this._addInputNode.focus())};e._focusAddBookmark=function(){this._addBookmarkButtonNode&&this._focusAddBookmarkButton&&(this._focusAddBookmarkButton=!1,this._addBookmarkButtonNode.focus())};e._focusEditInput=function(){this._editInputNode&&this._focusEditInputBox&&(this._focusEditInputBox=!1,this._editInputNode.focus())};e._deleteBookmark=function(a){this.viewModel.bookmarks.remove(a.currentTarget["data-bookmark"])};
e._goToBookmark=function(a){a=a.currentTarget["data-bookmark"];this.endAddBookmark();this._closeEditBookmarkForm();this.viewModel.goTo(a)};e._refreshThumbnail=function(){var a=r._asyncToGenerator(function*(){const {_userState:b,_editMenu:d,viewModel:g}=this;b.validationState=void 0;yield g.editBookmark(this._userState.editedBookmark,{takeScreenshot:!0,captureViewpoint:!1,captureRotation:!1,captureScale:!1,captureTimeExtent:!1});d.open=!1;this._focusEditInputBox=!0;this.scheduleRender()});return function(){return a.apply(this,
arguments)}}();e._removeThumbnail=function(){const {_userState:a,_editMenu:b}=this;a.editedBookmark.thumbnail=null;a.validationState=void 0;b.open=!1;this._focusEditInputBox=!0;this.scheduleRender()};e._startUseImageUrl=function(){this._userState.state="edit-thumbnail";this._editMenu.open=!1;this._focusUrlEditInputBox=!0;this.scheduleRender()};e._editBookmarkUrlSubmit=function(a){a.preventDefault();const {_urlEditInputNode:b,_userState:d}=this;a=b.value;A.test(a)?(a&&(d.editedBookmark.thumbnail=new J.SlideThumbnail({url:a})),
this._closeUrlEditBookmarkForm()):d.validationState="absolute-url-required"};r._createClass(u,[{key:"_editMenuItems",get:function(){const {messages:a,_userState:b}=this;var d=b?.editedBookmark?.thumbnail?.url;const g=new y({label:a?.menu.refreshThumbnail,iconClass:c.CSS.iconRefresh,clickFunction:()=>this._refreshThumbnail()}),h=new y({label:A.test(d)?a?.menu.editImageUrl:a?.menu.useImageUrl,iconClass:c.CSS.iconLink,clickFunction:()=>this._startUseImageUrl()});d=d?new y({label:a?.menu.removeThumbnail,
iconClass:c.CSS.iconRemove,clickFunction:()=>this._removeThumbnail()}):null;return[g,h,d].filter(Boolean)}},{key:"_editMenu",get:function(){const {_editMenuItems:a,messages:b,disabled:d}=this;var g=this._get("_editMenu");g&&g.destroy();g=new L({disabled:d,iconClass:c.CSS.iconHandleHorizontal,label:b?.menu.label});g.items=a;return g}},{key:"defaultCreateOptions",get:function(){return this.viewModel.defaultCreateOptions},set:function(a){this.viewModel.defaultCreateOptions=a}},{key:"defaultEditOptions",
get:function(){return this.viewModel.defaultEditOptions},set:function(a){this.viewModel.defaultEditOptions=a}},{key:"bookmarks",get:function(){return this.viewModel.bookmarks},set:function(a){this.viewModel.bookmarks=a}},{key:"goToOverride",get:function(){return this.viewModel.goToOverride},set:function(a){this.viewModel.goToOverride=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"view",get:function(){return this.viewModel.view},
set:function(a){this.viewModel.view=a}}]);return u}(K);l.__decorate([m.property()],k.prototype,"_editIncludeTimeExtent",void 0);l.__decorate([m.property({type:x})],k.prototype,"_userState",void 0);l.__decorate([m.property({readOnly:!0})],k.prototype,"_editMenuItems",null);l.__decorate([m.property({readOnly:!0})],k.prototype,"_editMenu",null);l.__decorate([m.property()],k.prototype,"defaultCreateOptions",null);l.__decorate([m.property()],k.prototype,"defaultEditOptions",null);l.__decorate([m.property()],
k.prototype,"bookmarks",null);l.__decorate([m.property()],k.prototype,"disabled",void 0);l.__decorate([m.property()],k.prototype,"editingEnabled",void 0);l.__decorate([m.property()],k.prototype,"headingLevel",void 0);l.__decorate([m.property()],k.prototype,"goToOverride",null);l.__decorate([m.property()],k.prototype,"iconClass",void 0);l.__decorate([m.property()],k.prototype,"label",null);l.__decorate([m.property(),z.messageBundle("esri/widgets/Bookmarks/t9n/Bookmarks")],k.prototype,"messages",void 0);
l.__decorate([m.property(),z.messageBundle("esri/t9n/common")],k.prototype,"messagesCommon",void 0);l.__decorate([m.property(),z.messageBundle("esri/core/t9n/Units")],k.prototype,"messagesUnits",void 0);l.__decorate([m.property()],k.prototype,"uiStrings",void 0);l.__decorate([m.property()],k.prototype,"view",null);l.__decorate([m.property({type:C}),O.vmEvent(["select-bookmark","bookmark-edit","bookmark-select"])],k.prototype,"viewModel",void 0);l.__decorate([m.property()],k.prototype,"visibleElements",
void 0);l.__decorate([H.cast("visibleElements")],k.prototype,"castVisibleElements",null);l.__decorate([m.property()],k.prototype,"endAddBookmark",null);l.__decorate([m.property()],k.prototype,"startAddBookmark",null);return k=l.__decorate([I.subclass("esri.widgets.Bookmarks")],k)});