// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/accessorSupport/decorators/subclass ./Widget ./BuildingExplorer/BuildingExplorerViewModel ./BuildingExplorer/css ./BuildingExplorer/BuildingDisciplinesTree/BuildingDisciplinesTree ./BuildingExplorer/BuildingLevelPicker/BuildingLevelPicker ./BuildingExplorer/BuildingPhasePicker/BuildingPhasePicker ./support/Heading ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory".split(" "),
function(p,f,g,v,e,w,x,q,c,y,z,A,n,k,r,d){const t={levels:!0,phases:!0,disciplines:!0};e=function(u){function m(a,b){a=u.call(this,a,b)||this;a._defaultViewModel=new q;a.viewModel=a._defaultViewModel;a.visibleElements={...t};a.headingLevel=3;a.iconClass=c.CSS.widgetIcon;a.messages=null;a.messagesCommon=null;a.toggleSiblingsVisibility=!1;return a}p._inheritsLoose(m,u);var h=m.prototype;h.destroy=function(){this.viewModel!==this._defaultViewModel&&this._defaultViewModel.destroy()};h._castVisibleElements=
function(a){return{...t,...a}};h.render=function(){const a=this.viewModel;return d.tsx("div",{key:this,class:k.classes(c.CSS.esriWidget,c.CSS.base,{[c.CSS.esriWidgetDisabled]:"disabled"===a.state||!a.isSupported}),"aria-label":this.messages.widgetLabel},this._renderContent())};h._renderContent=function(){const a=this.viewModel,b=this.messages;if(!a.isSupported)return d.tsx("p",{class:c.CSS.panelError},b.unsupported);if(!a.layers.length)return d.tsx("p",{class:c.CSS.panelError},b.noData);switch(a.state){case "loading":return this._renderLoadingIndicator();
case "ready":return d.tsx("div",{key:"content",class:c.CSS.content},this._renderLevelPickerSection(),this._renderPhasePickerSection(),this._renderDisciplinesSection());case "failed":return d.tsx("p",{class:c.CSS.panelError},b.failed);default:return null}};h._renderLoadingIndicator=function(){const a=this.messagesCommon.loading;return d.tsx("div",{key:"loading-container",role:"presentation",class:c.CSS.loadingContainer,"aria-label":a,title:a},d.tsx("span",{"aria-hidden":"true",class:k.classes(c.CSS.esriIconLoadingIndicator,
c.CSS.esriRotating)}))};h._renderLevelPickerSection=function(){const a=this.viewModel.level;var b="ready"===a.state;const l=1<a.allowedValues.length;if(!this.visibleElements.levels||!b||!l)return null;b=this.messages?.level;return d.tsx("div",{key:"levels",class:k.classes(c.CSS.section,c.CSS.levels)},d.tsx(n.Heading,{level:this.headingLevel},b?.title),d.tsx(z,{vm:a,messages:b}))};h._renderPhasePickerSection=function(){const a=this.viewModel.phase;var b="ready"===a.state;const l=1<a.allowedValues.length;
if(!this.visibleElements.phases||!b||!l)return null;b=this.messages.phase;return d.tsx("div",{key:"phases",class:k.classes(c.CSS.section,c.CSS.phases)},d.tsx(n.Heading,{level:this.headingLevel},b.title),d.tsx(A,{vm:a,messages:b}))};h._renderDisciplinesSection=function(){const a=this.viewModel.disciplines;var b="ready"===a.state;const l=a.root.hasChildren;if(!this.visibleElements.disciplines||!b||!l)return null;b=this.messages?.disciplines;return d.tsx("div",{key:"disciplines",class:k.classes(c.CSS.section,
c.CSS.disciplines)},d.tsx(n.Heading,{level:this.headingLevel},b.title),d.tsx(y,{vm:a,messages:b,toggleSiblingsVisibility:this.toggleSiblingsVisibility}))};p._createClass(m,[{key:"view",get:function(){return this.viewModel.view},set:function(a){this.viewModel.view=a}},{key:"layers",get:function(){return this.viewModel.layers},set:function(a){this.viewModel.layers=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}}]);return m}(x);
f.__decorate([g.property({type:q})],e.prototype,"viewModel",void 0);f.__decorate([g.property()],e.prototype,"view",null);f.__decorate([g.property()],e.prototype,"layers",null);f.__decorate([g.property()],e.prototype,"visibleElements",void 0);f.__decorate([v.cast("visibleElements")],e.prototype,"_castVisibleElements",null);f.__decorate([g.property()],e.prototype,"headingLevel",void 0);f.__decorate([g.property()],e.prototype,"iconClass",void 0);f.__decorate([g.property()],e.prototype,"label",null);
f.__decorate([g.property(),r.messageBundle("esri/widgets/BuildingExplorer/t9n/BuildingExplorer")],e.prototype,"messages",void 0);f.__decorate([g.property(),r.messageBundle("esri/t9n/common")],e.prototype,"messagesCommon",void 0);f.__decorate([g.property({nonNullable:!0})],e.prototype,"toggleSiblingsVisibility",void 0);f.__decorate([g.property()],e.prototype,"uiStrings",void 0);return e=f.__decorate([w.subclass("esri.widgets.BuildingExplorer")],e)});