// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Logger ../core/maybe ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ./Widget ./Daylight/css ./Daylight/DaylightViewModel ./Daylight/VisibleElements ./Daylight/support/daylightUtils ./Daylight/support/SliderWithDropdown ./support/DatePicker ./support/Heading ./support/timeWidgetUtils ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory".split(" "),
function(t,p,f,B,v,g,h,e,J,C,D,d,w,x,E,F,G,H,I,K,y,k){const z=/(.*)\s(.*)/;e=function(n){function q(a,c){var b=n.call(this,a,c)||this;b.headingLevel=3;b.iconClass=d.CSS.widgetIcon;b.viewModel=new w;b.visibleElements=new x;b.dateOrSeason="date";b._timeSlider=new F({viewModel:b.viewModel.timeSliderViewModel,steps:b.timeSliderSteps,labelInputsEnabled:!1,visibleElements:{labels:!0},tickConfigs:[{mode:"position",values:[0,360,720,1080,1439],labelsVisible:!0,tickCreatedFunction:b._onPrimaryTickCreated.bind(p._assertThisInitialized(b))},
{mode:"position",values:[120,240,480,600,840,960,1200,1320],tickCreatedFunction:b._onSecondaryTickCreated.bind(p._assertThisInitialized(b))}],items:[]});b._datePicker=new G({viewModel:b.viewModel.datePickerViewModel,commitOnMonthChange:!0});b._onPlayDayClick=()=>{b.viewModel.toggleDayPlaying()};b._onYearPlayClick=()=>{b.viewModel.toggleYearPlaying()};b._onSeasonChange=l=>{b.viewModel.currentSeason=l.target.value};b._onSunLightingCheckboxChange=()=>{b.viewModel.toggleSunLightingEnabled()};b._onShadowCheckboxChange=
()=>{b.viewModel.toggleDirectShadowsEnabled()};return b}p._inheritsLoose(q,n);var m=q.prototype;m.postInitialize=function(){this.viewModel.isSupported&&this.addHandles([g.watch(()=>this.viewModel.datePickerViewModel,a=>this._datePicker.viewModel=a,g.syncAndInitial),g.watch(()=>this.viewModel.timeSliderViewModel,a=>this._timeSlider.viewModel=a,g.syncAndInitial),g.watch(()=>this.timezoneMessages.chooseTimezone,a=>this._timeSlider.buttonTooltip=a,g.syncAndInitial),g.watch(()=>this.visibleElements?.timezone,
a=>this._timeSlider.showDropDown=a,g.syncAndInitial),g.watch(()=>!this.viewModel.sunLightingEnabled,a=>{this._datePicker.disabled=a;this._timeSlider.disabled=a},g.syncAndInitial),g.when(()=>this.gmtOffsets,a=>{this._timeSlider.items=a.map(c=>({utcOffset:c.utcOffset,name:c.short,label:[c.shortWithUTC,c.long]}))},g.syncAndInitial),g.watch(()=>[this.viewModel.utcOffset,this.gmtOffsets],()=>this._onUTCOffsetChange(),g.syncAndInitial),g.when(()=>!this.visible,()=>this._datePicker?.close(!1),g.sync)])};
m.destroy=function(){this._datePicker.destroy();this._timeSlider.destroy()};m.render=function(){const {messages:a,viewModel:c,visibleElements:b}=this,l=c.isSupported;return k.tsx("div",{class:this.classes(d.CSS.base,d.CSS.widget)},l?k.tsx(k.tsxFragment,null,b.header&&k.tsx(H.Heading,{level:this.headingLevel},a.title),this._renderTimeOptions(),b.datePicker&&this._renderDateOrSeason(),b.sunLightingToggle&&this._renderSunLightingToggle(),b.shadowsToggle&&this._renderShadowsToggle()):k.tsx("div",{key:"unsupported",
class:d.CSS.panelError},k.tsx("p",null,a.unsupported)))};m.loadDependencies=function(){return Promise.all([new Promise((a,c)=>t(["../chunks/calcite-button"],a,c)),new Promise((a,c)=>t(["../chunks/calcite-checkbox"],a,c)),new Promise((a,c)=>t(["../chunks/calcite-label"],a,c))])};m._renderTimeOptions=function(){const {viewModel:a,visibleElements:c,messages:b}=this,{directShadowsEnabled:l,dayPlaying:r}=a,A=!a.sunLightingEnabled;return k.tsx("div",{class:this.classes(d.CSS.dayContainer,this._labelAlignmentClass,
{[d.CSS.shadowOn]:l,[d.CSS.shadowOff]:!l,[d.CSS.sliderDateOn]:c.datePicker,[d.CSS.sliderDateOff]:!c.datePicker,[d.CSS.sliderAmPmOn]:this._useAmPm,[d.CSS.containerDisabled]:A}),key:"daylight-time-options"},this._timeSlider.render(),c.playButtons&&this._renderPlayPauseButton({playing:r,disabled:A,label:b.playDay,onClick:this._onPlayDayClick}))};m._renderDateOptions=function(){const {viewModel:a,visibleElements:c,messages:b}=this,{yearPlaying:l}=a,r=!a.sunLightingEnabled;return k.tsx("div",{key:"daylight-date-options",
class:this.classes(d.CSS.dateContainer,r&&d.CSS.containerDisabled)},this._datePicker.render(),c.playButtons&&this._renderPlayPauseButton({playing:l,disabled:r,label:b.playYear,onClick:this._onYearPlayClick}))};m._renderPlayPauseButton=function({playing:a,disabled:c,label:b,onClick:l}){return k.tsx("calcite-button",{appearance:"solid",class:d.CSS.playPauseButton,disabled:c,iconStart:a?"pause-f":"play-f",label:b,round:!0,title:b,type:"button",onclick:l})};m._renderSeasonOptions=function(){const {messages:a,
viewModel:c}=this,b=!c.sunLightingEnabled;return k.tsx("select",{class:this.classes(d.CSS.select,d.CSS.seasonPicker,b&&d.CSS.seasonPickerDisabled),disabled:b,value:c.currentSeason,"aria-label":a.season,onchange:this._onSeasonChange},E.ORDERED_SEASONS.map(l=>k.tsx("option",{value:l},a[l])))};m._renderDateOrSeason=function(){return"date"===this.dateOrSeason?this._renderDateOptions():this._renderSeasonOptions()};m._renderSunLightingToggle=function(){const a=this.messages?.sunLightingToggle;return k.tsx("calcite-label",
{key:"date-time-toggle",layout:"inline",title:a?.tooltip,scale:"s"},k.tsx("calcite-checkbox",{class:d.CSS.sunLightingCheckbox,checked:this.viewModel.sunLightingEnabled,onCalciteCheckboxChange:this._onSunLightingCheckboxChange}),a?.label)};m._renderShadowsToggle=function(){const a=this.messages.shadowsToggle;return k.tsx("calcite-label",{key:"shadow-toggle",layout:"inline",title:a?.tooltip,scale:"s"},k.tsx("calcite-checkbox",{class:d.CSS.shadowsCheckbox,checked:this.viewModel.directShadowsEnabled,
onCalciteCheckboxChange:this._onShadowCheckboxChange}),a.label)};m._onUTCOffsetChange=function(){const a=this.viewModel.utcOffset;var c=this._timeSlider.currentItem?.utcOffset;const b=this.gmtOffsets;v.isNone(b)||c===a||(c=b.findIndex(({utcOffset:l})=>l===a),-1<c&&(this._timeSlider.currentIndex=c))};m._onPrimaryTickCreated=function(a,c,b){c.classList.add(...u,d.CSS.primaryTick);b.classList.add(...u,d.CSS.primaryTickLabel);b.onclick=c.onclick=this._makeGoToTime(a);a=b.textContent;if(a=null!=a&&z.exec(a))b.innerHTML=
`${a[1]}<br><div class=${d.CSS.primaryTickAmPm}>${a[2]}</div>`};m._onSecondaryTickCreated=function(a,c){c.classList.add(...u,d.CSS.secondaryTick);c.onclick=this._makeGoToTime(a)};m._makeGoToTime=function(a){return()=>{this.viewModel.timeSliderPosition=a}};p._createClass(q,[{key:"gmtOffsets",get:function(){return v.applySome(this.timezoneMessages,I.getTimezoneInfos)}},{key:"label",get:function(){return this.messages?.title??""},set:function(a){this._overrideIfSome("label",a)}},{key:"playSpeedMultiplier",
get:function(){return this.viewModel.playSpeedMultiplier},set:function(a){this.viewModel.playSpeedMultiplier=a}},{key:"timeSliderSteps",get:function(){return this._timeSlider?.steps??5},set:function(a){this._timeSlider.steps=a}},{key:"view",get:function(){return this.viewModel.view},set:function(a){this.viewModel.view=a}},{key:"test",get:function(){return{datePicker:this._datePicker}}},{key:"_useAmPm",get:function(){const a=this._timeSlider.viewModel.getLabelForValue(0,"tick");return null!=a&&z.test(a)}},
{key:"_labelAlignmentClass",get:function(){const a=this.viewModel.timeSliderViewModel.values?.[0]??0,c=60*(this._useAmPm?21:21.5);return a<60*(this._useAmPm?4:3)?d.CSS.sliderAlignLeft:a>c?d.CSS.sliderAlignRight:null}}]);return q}(D);f.__decorate([h.property({readOnly:!0})],e.prototype,"gmtOffsets",null);f.__decorate([h.property(),y.messageBundle("esri/widgets/Daylight/t9n/Daylight")],e.prototype,"messages",void 0);f.__decorate([h.property(),y.messageBundle("esri/widgets/support/t9n/timezone")],e.prototype,
"timezoneMessages",void 0);f.__decorate([h.property()],e.prototype,"headingLevel",void 0);f.__decorate([h.property()],e.prototype,"iconClass",void 0);f.__decorate([h.property()],e.prototype,"label",null);f.__decorate([h.property()],e.prototype,"playSpeedMultiplier",null);f.__decorate([h.property()],e.prototype,"timeSliderSteps",null);f.__decorate([h.property()],e.prototype,"view",null);f.__decorate([h.property({type:w})],e.prototype,"viewModel",void 0);f.__decorate([h.property({type:x,nonNullable:!0})],
e.prototype,"visibleElements",void 0);f.__decorate([h.property({cast:n=>{if("season"===n||"date"===n)return n;B.getLogger("esri.widgets.Daylight").warn(`"${n}" is not a valid option. Acceptable values are only "date" or "season". Defaulting to "${"date"}".`);return"date"}})],e.prototype,"dateOrSeason",void 0);f.__decorate([h.property()],e.prototype,"_timeSlider",void 0);f.__decorate([h.property()],e.prototype,"_useAmPm",null);f.__decorate([h.property()],e.prototype,"_labelAlignmentClass",null);f.__decorate([h.property()],
e.prototype,"_datePicker",void 0);e=f.__decorate([C.subclass("esri.widgets.Daylight")],e);const u=["esri-interactive","esri-widget__anchor"];return e});