// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../intl ../core/maybe ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ./Widget ./Histogram/HistogramViewModel ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory ../intl/substitute".split(" "),function(x,k,f,r,m,K,L,A,B,C,D,E,l,F){var w;f=w=function(y){function t(a,b){a=y.call(this,a,b)||this;a._bgFillId=`${a.id}-bg-fill`;
a._containerNode=null;a._containerDimensions={width:0,height:0};a._defaultBarColor="#d8d8d8";a.barCreatedFunction=null;a.dataLines=null;a.dataLineCreatedFunction=null;a.dataLineUpdatedFunction=null;a.messages=null;a.viewModel=new C;return a}x._inheritsLoose(t,y);t.fromHistogramResult=function(a){const {bins:b,maxValue:c,minValue:e}=a;return new w({bins:b,max:c,min:e})};var g=t.prototype;g.render=function(){const {label:a,layout:b,state:c}=this,e=this.classes("esri-histogram","esri-widget","horizontal"===
b?"esri-histogram--horizontal":"esri-histogram--vertical","disabled"===c?"esri-disabled":null);return l.tsx("div",{"aria-label":a,class:e,bind:this,afterCreate:this._afterContainerNodeCreate},"ready"===c?this.renderContent():null)};g.renderContent=function(){if(this._containerNode){var a=this._bgFillId,b=`clip-path: url(#${a})`;return l.tsx("div",{class:"esri-histogram__content"},l.tsx("svg",{class:"esri-histogram__svg",xmlns:"http://www.w3.org/2000/svg"},l.tsx("defs",null,this.renderFillDefinition(a)),
l.tsx("g",{style:b},this.renderBarsGroup()),this.renderLinesGroup()))}};g.renderBarsGroup=function(){return l.tsx("g",{class:this.classes("esri-histogram__bars")},this.renderBars())};g.renderBars=function(){const {layout:a,viewModel:{binRange:b,range:c}}=this;if(b&&c){var e=b/c,{width:h,height:d}=this._containerDimensions;if(0!==d||0!==h)if(0===d&&0!==h)this.scheduleRender();else{var [n,q]="vertical"===a?[d*e,h]:[d,h*e];return this._getBarDimensions(n,q).map(([u,v],p)=>this.renderBar(p,u,v))}}};g.renderBar=
function(a,b,c){const {bins:e,layout:h,max:d,messages:n,viewModel:{range:q}}=this;if(e&&!r.isNone(d)){var {width:u,height:v}=this._containerDimensions,p=e.slice()[a],{count:G,maxValue:z,minValue:H}=p;p=d-z;var [I,J]="vertical"===h?[0,v/q*p]:[u-c-u/q*p,v-b];p=F.substitute(n.barLabel,{count:G,maxValue:z,minValue:H});return l.tsx("rect",{"aria-label":p,afterCreate:this._afterBarCreate,bind:this,class:"esri-histogram__bar","data-index":a,fill:this._defaultBarColor,height:b,role:"img","shape-rendering":"crispEdges",
"stroke-width":"0",width:c,x:I,y:J})}};g.renderLinesGroup=function(){return l.tsx("g",{class:this.classes("esri-histogram__data-lines")},this.renderAverageLine(),this.renderCustomLines())};g.renderAverageLine=function(){const {average:a}=this;if(!r.isNone(a)){var b=[l.tsx("tspan",{class:this.classes("esri-histogram__average-symbol")},"x\u0304 "),l.tsx("tspan",{class:this.classes("esri-histogram__average-label")},this.labelFormatFunction?this.labelFormatFunction(a,"average"):a)];return l.tsx("g",{afterCreate:this._afterLinesSubgroupCreate,
afterUpdate:this._afterLinesSubgroupUpdate,bind:this,class:this.classes("esri-histogram__data-lines-subgroup")},l.tsx("title",{key:"title"},a),this.renderLine(a,this.classes("esri-histogram__average-data-line")),this.renderLabel({label:b,value:a}))}};g.renderCustomLines=function(){if(this.dataLines&&this.dataLines.length)return this.dataLines.map((a,b)=>this.renderLineSubgroup(a,b))};g.renderLineSubgroup=function(a,b){const {value:c}=a;return l.tsx("g",{afterCreate:this._afterLinesSubgroupCreate,
afterUpdate:this._afterLinesSubgroupUpdate,bind:this,class:this.classes("esri-histogram__data-lines-subgroup"),"data-index":b},l.tsx("title",{key:"title"},c),this.renderLine(c),this.renderLabel(a))};g.renderLine=function(a,b){const [c,e,h,d]=this._getLinePosition(a);return l.tsx("line",{class:this.classes("esri-histogram__data-line",b),x1:c,x2:e,y1:h,y2:d,"shape-rendering":"crispEdges"})};g.renderLabel=function(a,b){const {label:c,value:e}=a,[h,d]=this._getLabelPosition(e);return l.tsx("text",{class:this.classes("esri-histogram__label",
b),"text-anchor":"end",transform:"horizontal"===this.layout?"rotate(270)":null,x:h,y:d-2},c??"")};g.renderFillDefinition=function(a){const {width:b,height:c}=this._containerDimensions;return l.tsx("clipPath",{id:a},l.tsx("rect",{x:"0",y:"0",width:b,height:c}))};g._afterContainerNodeCreate=function(a){this._containerNode=a;this.addHandles(D.onResize(a,b=>{const {width:c,height:e}=b.contentRect;this._containerDimensions={width:c,height:e}}))};g._getIndexFromElement=function(a){const b=a.dataset?.index;
a=a.getAttribute("data-index");return r.isSome(b)?parseInt(b,10):r.isSome(a)?parseInt(a,10):null};g._afterBarCreate=function(a){if(this.barCreatedFunction){const b=this._getIndexFromElement(a);this.barCreatedFunction(b,a)}};g._afterLinesSubgroupCreate=function(a){if(this.dataLineCreatedFunction){const b=this._getIndexFromElement(a);this.dataLineCreatedFunction(a.childNodes[0],a.childNodes[1]?a.childNodes[1]:null,b)}};g._afterLinesSubgroupUpdate=function(a){if(this.dataLineUpdatedFunction){const b=
this._getIndexFromElement(a);this.dataLineUpdatedFunction(a.childNodes[0],a.childNodes[1]?a.childNodes[1]:null,b)}};g._getBarDimensions=function(a,b){const {bins:c,layout:e}=this,h=c?c.map(n=>n.count):[],d=Math.max.apply(Math,h);return h.map(n=>"vertical"===e?[a/h.length,0!==d?n/d*b:0]:[0!==d?n/d*a:0,b/h.length])};g._getLinePosition=function(a){const {layout:b,min:c,viewModel:{range:e}}=this;if(r.isNone(c))return[0,0,0,0];a=Math.round((a-c)/e*100)/100;const {width:h,height:d}=this._containerDimensions,
[n,q]=[a*h||1,d-a*d||1];return"vertical"===b?[0,"100%",q,q]:[n,n,"100%",0]};g._getLabelPosition=function(a){const {layout:b,min:c,viewModel:{range:e}}=this;if(r.isNone(c))return[0,0];a=Math.round((a-c)/e*100)/100;const {width:h,height:d}=this._containerDimensions;return"vertical"===b?[h,d-a*d]:[0,a*h]};x._createClass(t,[{key:"average",get:function(){return this.viewModel.average},set:function(a){this.viewModel.average=a}},{key:"bins",get:function(){return this.viewModel.bins},set:function(a){this.viewModel.bins=
a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"labelFormatFunction",get:function(){return this.viewModel.labelFormatFunction},set:function(a){this.viewModel.labelFormatFunction=a}},{key:"layout",set:function(a){"vertical"!==a&&(a="horizontal");this._set("layout",a)}},{key:"max",get:function(){return this.viewModel.max},set:function(a){this.viewModel.max=a}},{key:"min",get:function(){return this.viewModel.min},set:function(a){this.viewModel.min=
a}},{key:"state",get:function(){return this.viewModel.state}}]);return t}(B);k.__decorate([m.property()],f.prototype,"_bgFillId",void 0);k.__decorate([m.property()],f.prototype,"_containerNode",void 0);k.__decorate([m.property()],f.prototype,"_containerDimensions",void 0);k.__decorate([m.property()],f.prototype,"_defaultBarColor",void 0);k.__decorate([m.property()],f.prototype,"average",null);k.__decorate([m.property()],f.prototype,"barCreatedFunction",void 0);k.__decorate([m.property()],f.prototype,
"dataLines",void 0);k.__decorate([m.property()],f.prototype,"dataLineCreatedFunction",void 0);k.__decorate([m.property()],f.prototype,"dataLineUpdatedFunction",void 0);k.__decorate([m.property()],f.prototype,"label",null);k.__decorate([m.property()],f.prototype,"labelFormatFunction",null);k.__decorate([m.property({value:"horizontal"})],f.prototype,"layout",null);k.__decorate([m.property()],f.prototype,"max",null);k.__decorate([m.property(),E.messageBundle("esri/widgets/Histogram/t9n/Histogram")],
f.prototype,"messages",void 0);k.__decorate([m.property()],f.prototype,"min",null);k.__decorate([m.property({readOnly:!0})],f.prototype,"state",null);k.__decorate([m.property()],f.prototype,"viewModel",void 0);return f=w=k.__decorate([A.subclass("esri.widgets.Histogram")],f)});