// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../TimeInterval ../core/arrayUtils ../core/Collection ../core/compilerUtils ../core/maybe ../core/reactiveUtils ../core/timeUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/subclass ../intl/date ./Slider ./Widget ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ./support/widgetUtils ../support/themeUtils ./TimeSlider/css ./TimeSlider/TimeSliderViewModel".split(" "),
function(P,H,f,b,Z,aa,ba,e,I,Q,h,la,ca,z,da,ea,J,R,fa,d,ha,ia,c,K){const ja=new aa([{minor:new b({value:100,unit:"milliseconds"}),major:new b({value:1,unit:"seconds"}),format:{second:"numeric"}},{minor:new b({value:500,unit:"milliseconds"}),major:new b({value:5,unit:"seconds"}),format:{second:"numeric"}},{minor:new b({value:1,unit:"seconds"}),major:new b({value:20,unit:"seconds"}),format:{minute:"numeric",second:"numeric"}},{minor:new b({value:2,unit:"seconds"}),major:new b({value:30,unit:"seconds"}),
format:{minute:"numeric",second:"numeric"}},{minor:new b({value:10,unit:"seconds"}),major:new b({value:1,unit:"minutes"}),format:{minute:"numeric"}},{minor:new b({value:15,unit:"seconds"}),major:new b({value:5,unit:"minutes"}),format:{hour:"numeric",minute:"numeric"}},{minor:new b({value:1,unit:"minutes"}),major:new b({value:20,unit:"minutes"}),format:{hour:"numeric",minute:"numeric"}},{minor:new b({value:5,unit:"minutes"}),major:new b({value:2,unit:"hours"}),format:{hour:"numeric",minute:"numeric"}},
{minor:new b({value:15,unit:"minutes"}),major:new b({value:6,unit:"hours"}),format:{hour:"numeric",minute:"numeric"}},{minor:new b({value:1,unit:"hours"}),major:new b({value:1,unit:"days"}),format:{day:"numeric",month:"short"}},{minor:new b({value:6,unit:"hours"}),major:new b({value:1,unit:"weeks"}),format:{day:"numeric",month:"short"}},{minor:new b({value:1,unit:"days"}),major:new b({value:1,unit:"months"}),format:{month:"long"}},{minor:new b({value:2,unit:"days"}),major:new b({value:1,unit:"months"}),
format:{month:"short"}},{minor:new b({value:3,unit:"days"}),major:new b({value:1,unit:"months"}),format:{month:"short"}},{minor:new b({value:4,unit:"days"}),major:new b({value:3,unit:"months"}),format:{month:"short",year:"numeric"}},{minor:new b({value:1,unit:"weeks"}),major:new b({value:1,unit:"years"}),format:{year:"numeric"}},{minor:new b({value:1,unit:"months"}),major:new b({value:1,unit:"years"}),format:{year:"numeric"}},{minor:new b({value:2,unit:"months"}),major:new b({value:2,unit:"years"}),
format:{year:"numeric"}},{minor:new b({value:1,unit:"years"}),major:new b({value:1,unit:"decades"}),format:{year:"numeric"}},{minor:new b({value:2,unit:"years"}),major:new b({value:5,unit:"decades"}),format:{year:"numeric"}},{minor:new b({value:5,unit:"decades"}),major:new b({value:10,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:1,unit:"centuries"}),major:new b({value:10,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:2,unit:"centuries"}),
major:new b({value:20,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:5,unit:"centuries"}),major:new b({value:50,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:10,unit:"centuries"}),major:new b({value:100,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:20,unit:"centuries"}),major:new b({value:200,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:50,unit:"centuries"}),major:new b({value:500,
unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:100,unit:"centuries"}),major:new b({value:1E3,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:200,unit:"centuries"}),major:new b({value:1E3,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:500,unit:"centuries"}),major:new b({value:5E3,unit:"centuries"}),format:{era:"short",year:"numeric"}},{minor:new b({value:1E3,unit:"centuries"}),major:new b({value:1E4,unit:"centuries"}),
format:{era:"short",year:"numeric"}}]);b=function(S){function A(a,g){a=S.call(this,a,g)||this;a._ignoreNextSliderUpdate=!1;a._slider=new da({precision:0,visibleElements:{rangeLabels:!1},rangeLabelInputsEnabled:!1,thumbsConstrained:!1});a._tickFormat=null;a.disabled=!1;a.iconClass=c.CSS.widgetIcon;a.labelFormatFunction=null;a.messages=null;a.messagesCommon=null;a.tickConfigs=null;a.timeVisible=!1;a.viewModel=new K;return a}H._inheritsLoose(A,S);var l=A.prototype;l.initialize=function(){this.addHandles([I.watch(()=>
this._slider.values,a=>{this._ignoreNextSliderUpdate?this._ignoreNextSliderUpdate=!1:(a=this.viewModel.valuesToTimeExtent(a),e.isSome(this.timeExtent)?e.isSome(a)?this.timeExtent.equals(a)||(this.timeExtent=a):this.timeExtent=null:e.isSome(a)&&(this.timeExtent=a))}),I.watch(()=>this.effectiveStops,()=>this._updateSliderSteps(),I.initial)])};l.loadDependencies=function(){return Promise.all([new Promise((a,g)=>P(["../chunks/calcite-action"],a,g)),new Promise((a,g)=>P(["../chunks/calcite-action-menu"],
a,g))])};l.destroy=function(){this._slider.destroy();this._tickFormat=null};A.getPropertiesFromWebMap=function(){var a=H._asyncToGenerator(function*(g,t){return K.getPropertiesFromWebMap(g,t)});return function(g,t){return a.apply(this,arguments)}}();l.next=function(){return this.viewModel.next()};l.play=function(){return this.viewModel.play()};l.previous=function(){return this.viewModel.previous()};l.stop=function(){return this.viewModel.stop()};l.render=function(){const {_slider:a,actions:g,domNode:t,
effectiveStops:C,fullTimeExtent:n,interactive:u,messages:L,messagesCommon:r,mode:T,tickConfigs:M,timeExtent:k,timeVisible:D,viewModel:{state:U,timeExtentValues:N}}=this;if(e.isSome(n)){const {start:m,end:V}=n;if(e.isSome(m)&&e.isSome(V)){var p=m.getTime(),v=V.getTime(),x=a.min!==p||a.max!==v;x&&(a.min=p,a.max=v);if(e.isSome(M))a.tickConfigs!==M&&(a.tickConfigs=M);else{const ka=(v-p)/(a.trackElement?.offsetWidth||400),y=ja.find(B=>B.minor.toMilliseconds()>3*ka);if(p=this._tickFormat!==y&&null!=y)this._tickFormat=
y;if(x||p)x={mode:"position",values:this._getTickPositions(y.minor),labelsVisible:!1,tickCreatedFunction:(B,O)=>{O.classList.add(c.CSS.sliderMinorTick)}},p={mode:"position",values:this._getTickPositions(y.major),labelsVisible:!0,tickCreatedFunction:(B,O)=>{O.classList.add(c.CSS.sliderMajorTick)},labelFormatFunction:B=>z.formatDate(B,y.format)},a.tickConfigs=[x,p]}}}if(x=e.isNone(this.fullTimeExtent)||e.isNone(this.timeExtent)||this.timeExtent.isAllTime||this.timeExtent.isEmpty||e.isSome(this.timeExtent.start)&&
(this.timeExtent.start<this.fullTimeExtent.start||this.timeExtent.start>this.fullTimeExtent.end)||e.isSome(this.timeExtent.end)&&(this.timeExtent.end>this.fullTimeExtent.end||this.timeExtent.end<this.fullTimeExtent.start))switch(this._ignoreNextSliderUpdate=!0,T){case "time-window":a.values=[a.min,a.max];break;case "instant":case "cumulative-from-end":a.values=[a.min];break;case "cumulative-from-start":a.values=[a.max]}else e.isSome(N)?Z.equals(a.values,N)||(a.values=N):a.values=null;a.disabled=!u;
v="ready"===U;var w="playing"===U,q=x||!u||e.isNone(C)||0===C.length;p="auto"===this.layout?858>t.clientWidth?"compact":"wide":this.layout;v=d.tsx("div",{class:c.CSS.animation},d.tsx("button",{"aria-disabled":q?"true":"false","aria-label":w?r.control.stop:r.control.play,bind:this,class:this.classes(c.CSS.esriWidgetButton,c.CSS.animationButton,q&&c.CSS.esriButtonDisabled),disabled:q,title:w?r.control.stop:r.control.play,onclick:this._playOrStopClick,type:"button"},d.tsx("div",{class:this.classes((v||
q)&&c.CSS.animationPlay,w&&c.CSS.animationPause)})));var E=e.isSome(this.labelFormatFunction)?d.tsx("div",{key:"extent",bind:this,class:c.CSS.timeExtentDate,"data-type":"extent","data-layout":p,"data-date":e.applySome(k,m=>[m.start,m.end]),afterCreate:this._createLabel,afterUpdate:this._createLabel}):e.isNone(k)||e.isSome(k)&&k.isAllTime?[d.tsx("div",{class:this.classes(c.CSS.warning,c.CSS.warningIcon)}),d.tsx("div",{key:"warning-text",class:c.CSS.warningText},L.noTimeExtent)]:k.isEmpty?[d.tsx("div",
{class:this.classes(c.CSS.warning,c.CSS.warningIcon)}),d.tsx("div",{key:"warning-text",class:c.CSS.warningText},L.emptyTimeExtent)]:[e.isSome(k.start)&&d.tsx("div",{key:"start-date-group",class:c.CSS.timeExtentGroup},d.tsx("div",{key:"start-date",class:c.CSS.timeExtentDate},this._formatDate(k.start)),D&&d.tsx("div",{key:"start-time",class:c.CSS.timeExtentTime},this._formatTime(k.start))),e.isSome(k.start)&&e.isSome(k.end)&&k.start.getTime()!==k.end.getTime()&&d.tsx("div",{key:"separator",class:c.CSS.timeExtentSeparator},
"\u2013"),e.isSome(k.end)&&(e.isNone(k.start)||k.start.getTime()!==k.end.getTime())&&d.tsx("div",{key:"end-date-group",class:c.CSS.timeExtentGroup},d.tsx("div",{key:"end-date",class:c.CSS.timeExtentDate},this._formatDate(k.end)),D&&d.tsx("div",{key:"end-time",class:c.CSS.timeExtentTime},this._formatTime(k.end)))];E=d.tsx("div",{class:this.classes(c.CSS.timeExtent,!u&&c.CSS.esriButtonDisabled)},[E]);var F=e.isSome(this.labelFormatFunction)?d.tsx("div",{key:"min-date",bind:this,class:c.CSS.minDate,
"data-date":e.applySome(n,m=>m.start),"data-type":"min","data-layout":p,afterCreate:this._createLabel,afterUpdate:this._createLabel}):e.isSome(n)&&e.isSome(n.start)&&[d.tsx("div",{key:"min-date",class:c.CSS.minDate},this._formatDate(n.start)),D&&d.tsx("div",{key:"min-time",class:c.CSS.minTime},this._formatTime(n.start))];F=d.tsx("div",{class:this.classes(c.CSS.min,!u&&c.CSS.esriButtonDisabled)},[F]);const W=d.tsx("div",{class:c.CSS.slider},a.render());var G=e.isSome(this.labelFormatFunction)?d.tsx("div",
{key:"max-date",bind:this,class:c.CSS.maxDate,"data-date":e.applySome(n,m=>m.end),"data-type":"max","data-layout":p,afterCreate:this._createLabel,afterUpdate:this._createLabel}):e.isSome(n)&&e.isSome(n.end)&&[d.tsx("div",{key:"max-date",class:c.CSS.maxDate},this._formatDate(n.end)),D&&d.tsx("div",{key:"max-time",class:c.CSS.maxTime},this._formatTime(n.end))];G=d.tsx("div",{class:this.classes(c.CSS.max,!u&&c.CSS.esriButtonDisabled)},[G]);const X=d.tsx("div",{class:c.CSS.previous},d.tsx("button",{"aria-disabled":q?
"true":"false","aria-label":r.pagination.previous,bind:this,class:this.classes(c.CSS.esriWidgetButton,c.CSS.previousButton,(w||q)&&c.CSS.esriButtonDisabled),disabled:q,title:r.pagination.previous,onclick:this._previousClick,type:"button"},d.tsx("div",{class:c.CSS.previousIcon})));w=d.tsx("div",{class:c.CSS.next},d.tsx("button",{"aria-disabled":q?"true":"false","aria-label":r.pagination.next,bind:this,class:this.classes(c.CSS.esriWidgetButton,c.CSS.nextButton,(w||q)&&c.CSS.esriButtonDisabled),disabled:q,
title:r.pagination.next,onclick:this._nextClick,type:"button"},d.tsx("div",{class:c.CSS.nextIcon})));const Y=(q=0<g?.length)&&d.tsx("div",{class:c.CSS.actions,title:r.options},d.tsx("calcite-action-menu",{label:r.options,class:c.CSS.actionsButton},g.toArray().map(m=>d.tsx("calcite-action",{bind:this,icon:m.icon,id:m.id,onclick:()=>this.viewModel.triggerAction(m),text:m.title,textEnabled:!0}))));return d.tsx("div",{class:this.classes(c.CSS.timeSlider,c.CSS.esriWidget,`${c.CSS.timeSliderMode}${T}`,
`${c.CSS.timeSliderLayout}${p}`,!u&&c.CSS.esriDisabled,x&&c.CSS.timeSliderOutOfBounds,q&&c.CSS.hasActions,ia.getCalciteThemeClass()),afterCreate:m=>{this.addHandles(ha.onResize(m,()=>this.scheduleRender()))},"aria-label":L.widgetLabel},"wide"===p&&d.tsx("div",{class:c.CSS.timeSliderRow},d.tsx("div",{class:c.CSS.playbackControls},[v,E,F,W,G,X,w]),Y),"compact"===p&&[d.tsx("div",{key:"time-slider-row-1",class:c.CSS.timeSliderRow},[E,Y]),d.tsx("div",{key:"time-slider-row-2",class:c.CSS.timeSliderRow},
[W]),d.tsx("div",{key:"time-slider-row-3",class:c.CSS.timeSliderRow},[F,X,v,w,G])])};l.updateWebDocument=function(a){this.viewModel?.updateWebDocument(a)};l._createLabel=function(a){if(!e.isNone(this.labelFormatFunction)){var g=a.getAttribute("data-type"),t=a.getAttribute("data-layout");this.labelFormatFunction(a["data-date"],g,a,t)}};l._getTickPositions=function(a){var {fullTimeExtent:g}=this;if(e.isNone(g)||e.isNone(g.start)||e.isNone(g.end))return[];const {start:t,end:C}=g;g=[];const {value:n,
unit:u}=a;for(a=Q.truncateDate(t,u);a.getTime()<=C.getTime();)a.getTime()>=t.getTime()&&g.push(a.getTime()),a=Q.offsetDate(a,n,u);return g};l._formatDate=function(a){return a?z.formatDate(a,z.convertDateFormatToIntlOptions("short-date")):null};l._formatTime=function(a){return a?z.formatDate(a,z.convertDateFormatToIntlOptions("long-time")):null};l._updateSliderSteps=function(){this._slider.steps=e.isSome(this.effectiveStops)&&0<this.effectiveStops.length?this.effectiveStops.map(a=>a.getTime()):null};
l._playOrStopClick=function(){switch(this.viewModel.state){case "ready":this.viewModel.play();break;case "playing":this.viewModel.stop();break;case "disabled":break;default:ba.neverReached(this.viewModel.state)}};l._previousClick=function(){this.viewModel.previous()};l._nextClick=function(){this.viewModel.next()};H._createClass(A,[{key:"actions",get:function(){return this.viewModel.actions},set:function(a){this.viewModel.actions=a}},{key:"effectiveStops",get:function(){return this.viewModel.effectiveStops}},
{key:"fullTimeExtent",get:function(){return this.viewModel.fullTimeExtent},set:function(a){this.viewModel.fullTimeExtent=a}},{key:"interactive",get:function(){return!this.disabled&&"disabled"!==this.viewModel?.state}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"layout",set:function(a){["auto","compact","wide"].includes(a)||(a="auto");this._set("layout",a)}},{key:"loop",get:function(){return this.viewModel.loop},set:function(a){this.viewModel.loop=
a}},{key:"mode",get:function(){return this.viewModel.mode},set:function(a){this.viewModel.mode=a}},{key:"playRate",get:function(){return this.viewModel.playRate},set:function(a){this.viewModel.playRate=a}},{key:"stops",get:function(){return this.viewModel.stops},set:function(a){this.viewModel.stops=a}},{key:"timeExtent",get:function(){return this.viewModel.timeExtent},set:function(a){this.viewModel.timeExtent=a}},{key:"view",get:function(){return this.viewModel.view},set:function(a){this.viewModel.view=
a}}]);return A}(ea);f.__decorate([h.property()],b.prototype,"actions",null);f.__decorate([h.property()],b.prototype,"disabled",void 0);f.__decorate([h.property()],b.prototype,"effectiveStops",null);f.__decorate([h.property()],b.prototype,"fullTimeExtent",null);f.__decorate([h.property()],b.prototype,"iconClass",void 0);f.__decorate([h.property({readOnly:!0})],b.prototype,"interactive",null);f.__decorate([h.property()],b.prototype,"label",null);f.__decorate([h.property()],b.prototype,"labelFormatFunction",
void 0);f.__decorate([h.property({value:"auto"})],b.prototype,"layout",null);f.__decorate([h.property()],b.prototype,"loop",null);f.__decorate([h.property(),R.messageBundle("esri/widgets/TimeSlider/t9n/TimeSlider")],b.prototype,"messages",void 0);f.__decorate([h.property(),R.messageBundle("esri/t9n/common")],b.prototype,"messagesCommon",void 0);f.__decorate([h.property()],b.prototype,"mode",null);f.__decorate([h.property()],b.prototype,"playRate",null);f.__decorate([h.property()],b.prototype,"stops",
null);f.__decorate([h.property()],b.prototype,"tickConfigs",void 0);f.__decorate([h.property()],b.prototype,"timeExtent",null);f.__decorate([h.property({nonNullable:!0})],b.prototype,"timeVisible",void 0);f.__decorate([h.property()],b.prototype,"view",null);f.__decorate([h.property({type:K}),fa.vmEvent("trigger-action")],b.prototype,"viewModel",void 0);f.__decorate([J.accessibleHandler()],b.prototype,"_playOrStopClick",null);f.__decorate([J.accessibleHandler()],b.prototype,"_previousClick",null);
f.__decorate([J.accessibleHandler()],b.prototype,"_nextClick",null);return b=f.__decorate([ca.subclass("esri.widgets.TimeSlider")],b)});