// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Handles ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/accessorSupport/decorators/subclass ./Widget ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory ./UtilityNetworkAssociations/UtilityNetworkAssociationsViewModel".split(" "),function(h,m,d,r,t,e,u,b,v,w,B,x,c,n){const p={maxAllowableAssociationsSlider:!1};
b=function(q){function k(a,g){a=q.call(this,a,g)||this;a._autoRefreshAssociations=!0;a._associationsOptionsEnabled=!1;a._handles=new r;a._maxAllowableAssociationsSliderMax=1E3;a._maxAllowableAssociationsSliderMin=250;a._maxAllowableAssociationsSliderStep=250;a._warningMessage="";a.messages=null;a.showAssociationsEnabled=!1;a.viewModel=new n;a.visibleElements={...p};return a}m._inheritsLoose(k,q);var f=k.prototype;f.initialize=function(){this._handles.add([t.watch(()=>[this.view?.stationary,this.showAssociationsEnabled,
this.includeConnectivityAssociations,this.includeStructuralAttachmentAssociations,this.maxAllowableAssociations],()=>{!0===this.autoRefreshAssociations&&(!0===this.showAssociationsEnabled?this.viewModel.showAssociations():this.viewModel.removeAssociations())})])};f.castVisibleElements=function(a){return{...p,...a}};f.render=function(){const {messages:a}=this;return c.tsx("div",null,c.tsx("calcite-block",{heading:a.widgetLabel,class:"esri-un-associations__widget-block-content",collapsible:!0,open:!0},
this.autoRefreshAssociations?this.renderShowAssociationsSwitch():this.renderRefreshAssociationsAction(),this.renderShowStatusIcon(),this.renderSettings()),this.autoRefreshAssociations?this.renderShowAssociationsSwitchTooltip():this.renderRefreshAssociationsActionTooltip(),this.renderShowStatusIconTooltip())};f.loadDependencies=function(){return Promise.all([new Promise((a,g)=>h(["../chunks/calcite-action"],a,g)),new Promise((a,g)=>h(["../chunks/calcite-block"],a,g)),new Promise((a,g)=>h(["../chunks/calcite-label"],
a,g)),new Promise((a,g)=>h(["../chunks/calcite-slider"],a,g)),new Promise((a,g)=>h(["../chunks/calcite-switch"],a,g)),new Promise((a,g)=>h(["../chunks/calcite-tooltip"],a,g))])};f.renderConnectivityAssociationsToggle=function(){const {messages:{enableConnectivity:a}}=this;return c.tsx("div",{class:"esri-un-associations__controls-label-and-toggle"},c.tsx("calcite-label",{class:"esri-un-associations__controls-label"},a),c.tsx("calcite-switch",{bind:this,disabled:!this._associationsOptionsEnabled&&this.autoRefreshAssociations,
checked:this.includeConnectivityAssociations,onCalciteSwitchChange:this._connectivityAssociationsSwitchChange}))};f.renderMaxAllowableAssociationsSlider=function(){const {messages:{maxAllowableAssociations:a},visibleElements:{maxAllowableAssociationsSlider:g}}=this;return g?c.tsx("div",{class:"esri-un-associations__controls-label-and-slider"},c.tsx("calcite-label",{class:"esri-un-associations__controls-label"},a),c.tsx("calcite-slider",{bind:this,class:"esri-un-associations__controls-slider",disabled:!this._associationsOptionsEnabled&&
this.autoRefreshAssociations,min:this.maxAllowableAssociationsSliderMin,max:this.maxAllowableAssociationsSliderMax,step:this.maxAllowableAssociationsSliderStep,ticks:this.maxAllowableAssociationsSliderStep,value:this.maxAllowableAssociations,labelTicks:!0,snap:!0,scale:"s",onCalciteSliderChange:this._maxAllowableAssociationsSliderChange})):null};f.renderRefreshAssociationsAction=function(){return c.tsx("div",{slot:"control",style:"--calcite-ui-icon-color: #077ac2"},c.tsx("calcite-action",{id:"refreshAssociations-action",
bind:this,class:"esri-un-associations__widget-block-actions",icon:"refresh-",text:"",onclick:this._refreshAssociations}))};f.renderRefreshAssociationsActionTooltip=function(){const {messages:{enableAssociations:a}}=this;return c.tsx("calcite-tooltip",{label:"refreshAssociations-action-tooltip-label",referenceElement:"refreshAssociations-action"},c.tsx("span",null,a))};f.renderSettings=function(){return c.tsx("div",{class:"esri-un-associations__widget-settings-container"},this.renderConnectivityAssociationsToggle(),
this.renderStructuralAttachmentAssociationsToggle(),this.renderMaxAllowableAssociationsSlider())};f.renderShowAssociationsSwitch=function(){return c.tsx("calcite-switch",{id:"showAssociations-switch",bind:this,class:"esri-un-associations__widget-block-actions",checked:this.showAssociationsEnabled,onCalciteSwitchChange:this._showAssociationsSwitchChange,slot:"control"})};f.renderShowAssociationsSwitchTooltip=function(){const {messages:{enableAssociations:a}}=this;return c.tsx("calcite-tooltip",{label:"showAssociations-switch-tooltip-label",
referenceElement:"showAssociations-switch"},c.tsx("span",null,a))};f.renderShowStatusIcon=function(){const {messages:{maxAllowableAssociationsExceededWarning:a,noAssociationsFoundWarning:g}}=this;var l=()=>this.maxAllowableAssociationsExceeded?(this._warningMessage=a,"exclamation-mark-triangle"):this.noAssociationsFound?(this._warningMessage=g,"exclamation-mark-triangle"):"blank",y=c.tsx,z=c.tsx,A=l();l="blank"===l()?!0:!1;return y.call(c,"div",{slot:"control",style:"--calcite-ui-icon-color: #edd317"},
z.call(c,"calcite-action",{id:"statusIcon-action",class:"esri-un-associations__widget-block-actions",icon:A,disabled:l,text:"",slot:"control"}))};f.renderShowStatusIconTooltip=function(){return c.tsx("calcite-tooltip",{label:"statusIcon-action-tooltip-label",referenceElement:"statusIcon-action"},c.tsx("span",null,this._warningMessage))};f.renderStructuralAttachmentAssociationsToggle=function(){const {messages:{enableStructuralAttachment:a}}=this;return c.tsx("div",{class:"esri-un-associations__controls-label-and-toggle"},
c.tsx("calcite-label",{class:"esri-un-associations__controls-label"},a),c.tsx("calcite-switch",{bind:this,disabled:!this._associationsOptionsEnabled&&this.autoRefreshAssociations,checked:this.includeStructuralAttachmentAssociations,onCalciteSwitchChange:this._structuralAttAssociationsSwitchChange}))};f._connectivityAssociationsSwitchChange=function(a){this.includeConnectivityAssociations=a.target.checked};f._maxAllowableAssociationsSliderChange=function(a){this.maxAllowableAssociations=Number(a.target.value)};
f._refreshAssociations=function(){this.viewModel.showAssociations()};f._showAssociationsSwitchChange=function(a){this._associationsOptionsEnabled=this.showAssociationsEnabled=a.target.checked};f._structuralAttAssociationsSwitchChange=function(a){this.includeStructuralAttachmentAssociations=a.target.checked};m._createClass(k,[{key:"autoRefreshAssociations",get:function(){return this._autoRefreshAssociations},set:function(a){this._autoRefreshAssociations=a}},{key:"connectivityAssociationsLineSymbol",
get:function(){return this.viewModel.connectivityAssociationsLineSymbol},set:function(a){this.viewModel.connectivityAssociationsLineSymbol=a}},{key:"gdbVersion",get:function(){return this.viewModel.gdbVersion},set:function(a){this.viewModel.gdbVersion=a}},{key:"includeConnectivityAssociations",get:function(){return this.viewModel.includeConnectivityAssociations},set:function(a){this.viewModel.includeConnectivityAssociations=a}},{key:"includeStructuralAttachmentAssociations",get:function(){return this.viewModel.includeStructuralAttachmentAssociations},
set:function(a){this.viewModel.includeStructuralAttachmentAssociations=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"maxAllowableAssociations",get:function(){return this.viewModel.maxAllowableAssociations},set:function(a){this.viewModel.maxAllowableAssociations=a}},{key:"maxAllowableAssociationsExceeded",get:function(){return this.viewModel.maxAllowableAssociationsExceeded},set:function(a){this.viewModel.maxAllowableAssociationsExceeded=
a}},{key:"maxAllowableAssociationsSliderMax",get:function(){return this._maxAllowableAssociationsSliderMax},set:function(a){a<=this.maxAllowableAssociationsSliderMin||(this._maxAllowableAssociationsSliderMax=a)}},{key:"maxAllowableAssociationsSliderMin",get:function(){return this._maxAllowableAssociationsSliderMin},set:function(a){0>a||a>=this.maxAllowableAssociationsSliderMax||(this._maxAllowableAssociationsSliderMin=a)}},{key:"maxAllowableAssociationsSliderStep",get:function(){return this._maxAllowableAssociationsSliderStep},
set:function(a){this._maxAllowableAssociationsSliderStep=a}},{key:"moment",get:function(){return this.viewModel.moment},set:function(a){this.viewModel.moment=a}},{key:"noAssociationsFound",get:function(){return this.viewModel.noAssociationsFound},set:function(a){this.viewModel.noAssociationsFound=a}},{key:"showArrowsConnectivity",get:function(){return this.viewModel.showArrowsConnectivity},set:function(a){this.viewModel.showArrowsConnectivity=a}},{key:"showArrowsStructuralAttachment",get:function(){return this.viewModel.showArrowsStructuralAttachment},
set:function(a){this.viewModel.showArrowsStructuralAttachment=a}},{key:"structuralAttachmentAssociationsLineSymbol",get:function(){return this.viewModel.structuralAttachmentAssociationsLineSymbol},set:function(a){this.viewModel.structuralAttachmentAssociationsLineSymbol=a}},{key:"utilityNetwork",get:function(){return this.viewModel.utilityNetwork},set:function(a){this.viewModel.utilityNetwork=a}},{key:"view",get:function(){return this.viewModel.view},set:function(a){this.viewModel.view=a}}]);return k}(w);
d.__decorate([e.property()],b.prototype,"connectivityAssociationsLineSymbol",null);d.__decorate([e.property()],b.prototype,"gdbVersion",null);d.__decorate([e.property()],b.prototype,"includeConnectivityAssociations",null);d.__decorate([e.property()],b.prototype,"includeStructuralAttachmentAssociations",null);d.__decorate([e.property()],b.prototype,"label",null);d.__decorate([e.property()],b.prototype,"maxAllowableAssociations",null);d.__decorate([e.property()],b.prototype,"maxAllowableAssociationsExceeded",
null);d.__decorate([e.property()],b.prototype,"maxAllowableAssociationsSliderMax",null);d.__decorate([e.property()],b.prototype,"maxAllowableAssociationsSliderMin",null);d.__decorate([e.property()],b.prototype,"maxAllowableAssociationsSliderStep",null);d.__decorate([e.property(),x.messageBundle("esri/widgets/UtilityNetworkAssociations/t9n/UtilityNetworkAssociations")],b.prototype,"messages",void 0);d.__decorate([e.property()],b.prototype,"moment",null);d.__decorate([e.property()],b.prototype,"noAssociationsFound",
null);d.__decorate([e.property()],b.prototype,"showArrowsConnectivity",null);d.__decorate([e.property()],b.prototype,"showArrowsStructuralAttachment",null);d.__decorate([e.property()],b.prototype,"showAssociationsEnabled",void 0);d.__decorate([e.property()],b.prototype,"structuralAttachmentAssociationsLineSymbol",null);d.__decorate([e.property()],b.prototype,"utilityNetwork",null);d.__decorate([e.property()],b.prototype,"view",null);d.__decorate([e.property({type:n})],b.prototype,"viewModel",void 0);
d.__decorate([e.property()],b.prototype,"visibleElements",void 0);d.__decorate([u.cast("visibleElements")],b.prototype,"castVisibleElements",null);return b=d.__decorate([v.subclass("esri.widgets.UtilityNetworkAssociations")],b)});