// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/accessorSupport/decorators/subclass ./Widget ./support/widgetUtils ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ./ValuePicker/ValuePickerCollection ./ValuePicker/ValuePickerCombobox ./ValuePicker/ValuePickerSlider ./ValuePicker/ValuePickerViewModel ./ValuePicker/ValuePickerVisibleElements".split(" "),
function(n,p,c,d,q,K,v,b,L,r,w,k,x,y,z,A,t){q={base:null,key:"type",typeMap:{collection:x,combobox:y,slider:z}};b=function(u){function l(a,f){a=u.call(this,a,f)||this;a.component=null;a.messages=null;a.messagesCommon=null;a.viewModel=new A;a.visibleElements=new t;return a}p._inheritsLoose(l,u);var g=l.prototype;g.loadDependencies=function(){return Promise.all([new Promise((a,f)=>n(["../chunks/calcite-action"],a,f)),new Promise((a,f)=>n(["../chunks/calcite-action-bar"],a,f))])};g.next=function(){this.viewModel.next()};
g.pause=function(){this.viewModel.pause()};g.play=function(){this.viewModel.play()};g.previous=function(){this.viewModel.previous()};g.render=function(){const {disabled:a,state:f}=this.viewModel;var e="playing"===f,h="horizontal"===this.layout;const {control:B,pagination:C}=this.messagesCommon,{pause:D,play:E}=B,{previous:F,up:G,next:H,down:I}=C;if(this.component){var m;(m=this.component).viewModel??(m.viewModel=this.viewModel)}m=this.visibleElements.playButton&&k.tsx("calcite-action",{active:e,alignment:"center",
bind:this,disabled:a||!this.canPlay,icon:e?"pause":"play",key:"play",onclick:e?this.pause:this.play,text:e?D:E});const J=this.visibleElements.previousButton&&k.tsx("calcite-action",{alignment:"center",bind:this,disabled:a||e||!this.canPrevious,icon:h?"chevron-left":"chevron-up",key:"previous",onclick:this.previous,text:h?F:G});e=this.visibleElements.nextButton&&k.tsx("calcite-action",{alignment:"center",bind:this,disabled:a||e||!this.canNext,icon:h?"chevron-right":"chevron-down",key:"next",onclick:this.next,
text:h?H:I});h=this.component?.render();return k.tsx("div",{"aria-label":this.label,class:this.classes("esri-value-picker","esri-widget",`${"esri-value-picker"}__layout--${this.layout}`,`${"esri-value-picker"}__type--${this.component?.type}`)},k.tsx("calcite-action-bar",{expandDisabled:!0,layout:this.layout,class:"esri-value-picker__action-bar"},[m,J,e,h]))};p._createClass(l,[{key:"canNext",get:function(){return this.component?.canNext??!0}},{key:"canPlay",get:function(){return this.component?.canPlay??
!0}},{key:"canPrevious",get:function(){return this.component?.canPrevious??!0}},{key:"disabled",get:function(){return this.viewModel.disabled},set:function(a){this.viewModel.disabled=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"layout",get:function(){return this.viewModel.layout},set:function(a){this.viewModel.layout=a}},{key:"loop",get:function(){return this.viewModel.loop},set:function(a){this.viewModel.loop=a}},{key:"playRate",
get:function(){return this.viewModel.playRate},set:function(a){this.viewModel.playRate=a}},{key:"values",get:function(){return this.viewModel.values},set:function(a){this.viewModel.values=a}}]);return l}(b);c.__decorate([d.property()],b.prototype,"canNext",null);c.__decorate([d.property()],b.prototype,"canPlay",null);c.__decorate([d.property()],b.prototype,"canPrevious",null);c.__decorate([d.property({types:q})],b.prototype,"component",void 0);c.__decorate([d.property()],b.prototype,"disabled",null);
c.__decorate([d.property()],b.prototype,"label",null);c.__decorate([d.property()],b.prototype,"layout",null);c.__decorate([d.property()],b.prototype,"loop",null);c.__decorate([d.property(),r.messageBundle("esri/widgets/ValuePicker/t9n/ValuePicker")],b.prototype,"messages",void 0);c.__decorate([d.property(),r.messageBundle("esri/t9n/common")],b.prototype,"messagesCommon",void 0);c.__decorate([d.property()],b.prototype,"playRate",null);c.__decorate([d.property()],b.prototype,"values",null);c.__decorate([d.property(),
w.vmEvent(["animate","next","pause","play","previous"])],b.prototype,"viewModel",void 0);c.__decorate([d.property({type:t,nonNullable:!0})],b.prototype,"visibleElements",void 0);return b=c.__decorate([v.subclass("esri.widgets.ValuePicker")],b)});