// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("require exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/HandleOwner ../../../core/Handles ../../../core/MapUtils ../../../core/maybe ../../../core/promiseUtils ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../chunks/vec2 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/common ../../../layers/graphics/data/QueryEngineResult ../../../support/elevationInfoUtils ./SnappingConstraint ./SnappingDomain ./SnappingPoint ./snappingUtils ./candidates/DrapedEdgeSnappingCandidate ./candidates/EdgeSnappingCandidate ./candidates/FeatureSnappingCandidate ./candidates/RightAngleSnappingCandidate ../support/viewUtils".split(" "),
function(t,q,x,r,K,L,M,f,A,u,v,Y,Z,N,y,B,C,O,D,E,P,Q,F,G,R,S,T,H,I){function U({constraint:{start:m,end:g}}){const e=B.squaredDistance(m,g);m=y.squaredDistance(m,g);return e<O.getEpsilon()||1E-4>m/e}function z(m,g,e,a,b,c,{spatialReference:d}){g=B.copy(V,g);g[0]+=e;g[1]+=a;g[2]+=b;return(e=I.vectorToScreenPoint(g,d,E.absoluteHeightElevationInfo,c))?G.screenDistance(e,m):Infinity}q.FeatureSnappingEngine=function(m){function g(a){a=m.call(this,a)||this;a.options=null;a._domain=Q.SnappingDomain.FEATURE;
a._sourceModules={featureService:{module:null,loader:null},featureCollection:{module:null,loader:null},graphics:{module:null,loader:null},notes:{module:null,loader:null},scene:{module:null,loader:null}};return a}x._inheritsLoose(g,m);var e=g.prototype;e.initialize=function(){this.updatingHandles.add(()=>this.snappingSources,()=>this.notifyChange("updating"),u.sync);f.isSome(this.view)&&this.handles.add([this.view.on("layerview-create",a=>this._updateLayerView(a.layer,a.layerView)),this.view.on("layerview-destroy",
a=>this._updateLayerView(a.layer,null))])};e._updateLayerView=function(a,b){for(const [,c]of this.snappingSources)c.snappingSource.layerSource.layer===a&&(c.layerView=b)};e.destroy=function(){this._set("options",null);for(const [,a]of this.snappingSources)a.destroy()};e.fetchCandidates=function(){var a=x._asyncToGenerator(function*(b,c,d,k){if(!(c&this._domain)||f.isNone(this.options)||!this.options.effectiveFeatureEnabled)return[];var h=[];c=this._computeScreenSizeDistanceParameters(b,d);const l=
{distance:c,mode:f.unwrap(this.view)?.type??"2d",point:b,coordinateHelper:d.coordinateHelper,types:this._types};for(const [,{snappingSource:p,layerView:n}]of this.snappingSources)!p.layerSource.enabled||f.isSome(n)&&n.suspended||h.push(p.fetchCandidates(l,k).then(w=>w.filter(W=>!this._candidateIsExcluded(p,W,d.excludeFeature))));h=(yield A.eachAlwaysValues(h)).flat();this._addRightAngleCandidates(h,b,c,d);A.throwIfAborted(k);G.sortCandidatesInPlace(b,h);return h});return function(b,c,d,k){return a.apply(this,
arguments)}}();e._addRightAngleCandidates=function(a,b,c,d){var k=f.isSome(d.vertexHandle)?d.vertexHandle.rightEdge?.rightVertex?.pos:f.isSome(d.editGeometryOperations)&&"polygon"===d.editGeometryOperations.data.type?f.unwrap(d.editGeometryOperations.data.components[0]?.getFirstVertex())?.pos:null,h=f.isSome(d.vertexHandle)?d.vertexHandle.leftEdge?.leftVertex?.pos:f.isSome(d.editGeometryOperations)?f.unwrap(d.editGeometryOperations.data.components[0]?.getLastVertex())?.pos:null,{view:l}=this;k=F.anyMapPointToSnappingPoint(k,
l,d);d=F.anyMapPointToSnappingPoint(h,l,d);h=a.length;for(l=0;l<h;l++)this._addRightAngleCandidate(a[l],d,b,c,a),this._addRightAngleCandidate(a[l],k,b,c,a)};e._addRightAngleCandidate=function(a,b,c,d,k){var h;(h=f.isNone(b))||(h=!((a instanceof S.EdgeSnappingCandidate||a instanceof R.DrapedEdgeSnappingCandidate)&&!U(a)));if(!h){h=a.constraint.closestTo(b);var l=(h[0]-c[0])/d.x;c=(h[1]-c[1])/d.y;var {start:p,end:n}=a.constraint;1>=l*l+c*c&&(a=new H.RightAngleSnappingCandidate({targetPoint:h,otherVertex:b,
otherVertexType:H.OtherVertexType.NEXT,previousVertex:y.squaredDistance(h,p)>y.squaredDistance(h,n)?p:n,constraint:new P.VerticalHalfPlaneConstraint(b,h),objectId:a.objectId,isDraped:a.isDraped}),k.push(a))}};e._computeScreenSizeDistanceParameters=function(a,b){let c=f.isSome(this.options)?this.options.distance*("touch"===b.pointer?this.options.touchSensitivityMultiplier:1):0;return f.isNone(this.view)?{x:c,y:c,z:c,distance:c}:"2d"===this.view.type?(c*=this.view.resolution,{x:c,y:c,z:c,distance:c}):
this._computeScreenSizeDistanceParameters3D(a,c,this.view,b)};e._computeScreenSizeDistanceParameters3D=function(a,b,c,d){var {spatialReference:k}=d;c.renderCoordsHelper.toRenderCoords(a,k,J);const h=c.state.camera.computeScreenPixelSizeAt(J),l=h*c.renderCoordsHelper.unitInMeters/c.mapCoordsHelper.unitInMeters,p=b*l,n=I.vectorToScreenPoint(a,k,E.absoluteHeightElevationInfo,c);k=n?z(n,a,l,0,0,c,d):0;const w=n?z(n,a,0,l,0,c,d):0;a=n?z(n,a,0,0,l,c,d):0;return{x:0===k?0:p/k,y:0===w?0:p/w,z:0===a?0:p/a,
distance:h*b}};e._candidateIsExcluded=function(a,b,c){if(f.isNone(c))return!1;b=this._getCandidateObjectId(b);if(f.isNone(b))return!1;a=a.layerSource.layer;return"graphics"===a.type?c.uid===b:c.sourceLayer===a&&c.attributes&&"objectIdField"in a?c.attributes[a.objectIdField]===b:!1};e._getCandidateObjectId=function(a){return a instanceof T.FeatureSnappingCandidate?a.objectId:null};e._createSourceInfo=function(a){const b=this._createFeatureSnappingSourceType(a);if(f.isNone(b))return null;if("loading"in
b)return this.updatingHandles.addPromise(b.loading.then(()=>{this.destroyed||this.notifyChange("snappingSources")})),null;const c=f.isSome(this.view)?this.view.allLayerViews.find(d=>d.layer===a.layer):null;return new X(b.source,c)};e._createFeatureSnappingSourceType=function(a){switch(a.layer.type){case "feature":case "geojson":case "csv":case "oriented-imagery":case "subtype-group":case "wfs":return this._createFeatureSnappingSourceFeatureLayer(a);case "graphics":return this._createFeatureSnappingSourceGraphicsLayer(a);
case "map-notes":return this._createFeatureSnappingSourceMapNotesLayer(a);case "scene":case "building-scene":return this._createFeatureSnappingSourceSceneLayer(a)}return null};e._createFeatureSnappingSourceSceneLayer=function(a){const {view:b}=this;if(f.isNone(b)||"3d"!==b.type)return null;const c=this._getSourceModule("scene");return f.isSome(c.module)?{source:new c.module.SceneLayerSnappingSource({layerSource:a,view:b})}:{loading:c.loader}};e._createFeatureSnappingSourceFeatureLayer=function(a){switch(a.layer.source?.type){case "feature-layer":case "oriented-imagery":var b=
this._getSourceModule("featureService");return f.isSome(b.module)?{source:new b.module.FeatureServiceSnappingSource({spatialReference:this.spatialReference,view:this.view,layerSource:a})}:{loading:b.loader};case "memory":case "csv":case "geojson":case "wfs":if("mesh"!==a.layer.geometryType)return b=this._getSourceModule("featureCollection"),f.isSome(b.module)?{source:new b.module.FeatureCollectionSnappingSource({layerSource:a,view:this.view})}:{loading:b.loader}}return null};e._createFeatureSnappingSourceGraphicsLayer=
function(a){const b=this._getSourceModule("graphics");return f.isSome(b.module)?{source:new b.module.GraphicsSnappingSource({getGraphicsLayers:()=>[a.layer],spatialReference:this.spatialReference,view:this.view,layerSource:a})}:{loading:b.loader}};e._createFeatureSnappingSourceMapNotesLayer=function(a){const b=this._getSourceModule("notes");return f.isSome(b.module)?{source:new b.module.GraphicsSnappingSource({getGraphicsLayers:()=>f.isSome(a.layer.sublayers)?a.layer.sublayers.toArray():[],spatialReference:this.spatialReference,
view:this.view,layerSource:a})}:{loading:b.loader}};e._getSourceModule=function(a){const b=this._sourceModules[a];return f.isNone(b.loader)?(a=this._loadSourceModule(a).then(c=>{b.module=c}),b.loader=a,{module:b.module,loader:a}):{module:b.module,loader:b.loader}};e._loadSourceModule=function(a){const b=this.updatingHandles;switch(a){case "featureService":return b.addPromise(new Promise((c,d)=>t(["./featureSources/FeatureServiceSnappingSource"],c,d)));case "featureCollection":return b.addPromise(new Promise((c,
d)=>t(["./featureSources/FeatureCollectionSnappingSource"],c,d)));case "graphics":return b.addPromise(new Promise((c,d)=>t(["./featureSources/GraphicsSnappingSource"],c,d)));case "notes":return b.addPromise(new Promise((c,d)=>t(["./featureSources/GraphicsSnappingSource"],c,d)));case "scene":return b.addPromise(new Promise((c,d)=>t(["./featureSources/SceneLayerSnappingSource"],c,d)))}};x._createClass(g,[{key:"updating",get:function(){return M.someMap(this.snappingSources,({snappingSource:a})=>a.updating)||
this.updatingHandles.updating}},{key:"snappingSources",get:function(){const a=this._get("snappingSources")||new Map,b=new Map;if(f.isSome(this.options)&&f.isSome(this.options.featureSources))for(const d of this.options.featureSources.items){const k=d.layer.uid;var c=a.get(k);c?(a.delete(k),b.set(k,c)):d.layer.loaded?(c=this._createSourceInfo(d),f.isSome(c)&&b.set(k,c)):this.updatingHandles.addPromise(d.layer.load())}for(const [,d]of a)d.destroy();return b}},{key:"_types",get:function(){return D.SnappingTypes.EDGE|
D.SnappingTypes.VERTEX}}]);return g}(K.HandleOwner);r.__decorate([v.property({constructOnly:!0})],q.FeatureSnappingEngine.prototype,"spatialReference",void 0);r.__decorate([v.property({constructOnly:!0})],q.FeatureSnappingEngine.prototype,"view",void 0);r.__decorate([v.property()],q.FeatureSnappingEngine.prototype,"options",void 0);r.__decorate([v.property({readOnly:!0})],q.FeatureSnappingEngine.prototype,"updating",null);r.__decorate([v.property({readOnly:!0})],q.FeatureSnappingEngine.prototype,
"snappingSources",null);q.FeatureSnappingEngine=r.__decorate([N.subclass("esri.views.interactive.snapping.FeatureSnappingEngine")],q.FeatureSnappingEngine);let X=function(){function m(g,e){this.snappingSource=g;this.layerView=e;this.handles=new L;e=this.snappingSource.layerSource.layer;"refresh"in e&&this.handles.add(e.on("refresh",()=>g.refresh()));this.handles.add([u.watch(()=>g.updating,a=>g.layerSource.updating=a,u.syncAndInitial),u.watch(()=>g.availability,a=>g.layerSource.availability=a,u.syncAndInitial)])}
m.prototype.destroy=function(){this.snappingSource.destroy();this.handles.destroy()};return m}();const J=C.create(),V=C.create();Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});