// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Evented ../../../core/HandleOwner ../../../core/maybe ../../../core/promiseUtils ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/accessorSupport/decorators/subclass ../../../geometry/projection ../../../support/elevationInfoUtils ./Settings ./SnappingDomain ./snappingFactory ./SnappingOptions ./SnappingPoint ./snappingUtils ./candidates/IntersectionSnappingCandidate ../support/viewUtils".split(" "),
function(n,v,p,H,I,u,J,w,t,P,Q,K,C,D,E,z,L,M,x,F,A,N){function O({coordinateHelper:q,elevationInfo:y}){return q.hasZ()?D.absoluteHeightElevationInfo:y}n.SnappingManager=function(q){function y(b){b=q.call(this,b)||this;b.options=new M;b.snappingEnginesFactory=L.defaultSnappingEnginesFactory;b._engines=[];b._currentMainCandidate=null;b._currentOtherActiveCandidates=[];b._currentSnappedType=r.MAIN;return b}v._inheritsLoose(y,q);var g=y.prototype;g.initialize=function(){this.handles.add([w.watch(()=>
{const {effectiveFeatureEnabled:b,effectiveSelfEnabled:a,touchSensitivityMultiplier:c,distance:d}=this.options;return{effectiveFeatureEnabled:b,effectiveSelfEnabled:a,touchSensitivityMultiplier:c,distance:d}},()=>{this.doneSnapping();this.emit("changed")},w.sync),w.watch(()=>this.options,b=>{for(const a of this._engines)a.options=b},w.sync),w.watch(()=>({viewReady:this.view.ready,viewSpatialReference:this.view.spatialReference,snappingEnginesFactory:this.snappingEnginesFactory}),({viewReady:b,snappingEnginesFactory:a})=>
this._recreateEngines(b,a),w.syncAndInitial)])};g.destroy=function(){this._destroyEngines()};g._recreateEngines=function(b,a){this._destroyEngines();if(b){var {view:c,options:d}=this;this._engines=a(c,d)}};g._destroyEngines=function(){for(const b of this._engines)b.destroy();this._engines=[]};g.snap=function(){var b=v._asyncToGenerator(function*(a){return u.isSome(a.scenePoint)?this._snapMultiPoint(a):this._snapSinglePoint(a)});return function(a){return b.apply(this,arguments)}}();g.update=function(b){const {point:a,
context:c}=b;this._removeVisualization();const d=this._currentMainCandidate;if(u.isNone(d))return a;var e=this._selectUpdateInput(b);if(u.isNone(e))return a;({spatialReference:b}=c);var f=C.project(e,b);if(u.isNone(f))return a;({view:e}=this);const {elevationInfo:l,visualizer:m}=c,h=[];f=x.pointToSnappingPoint(f,e,c);const k=d.constraint.closestTo(f);if(!this._arePointsWithinScreenThreshold(f,k,c))return this._resetSnappingState(),a;d.targetPoint=k;h.push(...d.hints);for(const B of this._currentOtherActiveCandidates)B.targetPoint=
k,h.push(...B.hints);u.isSome(m)&&this.handles.add(m.draw(h,{spatialReference:b,elevationInfo:O(c),view:e,selfSnappingZ:c.selfSnappingZ}),"visualization-handle");return x.snappingPointToSnappingOutput(k,e,{z:a.z,m:a.m,spatialReference:a.spatialReference,elevationInfo:l})};g.doneSnapping=function(){this._removeVisualization();this._resetSnappingState()};g._selectUpdateInput=function({point:b,scenePoint:a}){switch(this._currentSnappedType){case r.MAIN:return b;case r.SCENE:return a}};g._resetSnappingState=
function(){this._currentMainCandidate=null;this._currentOtherActiveCandidates=[];this._currentSnappedType=r.MAIN};g._removeVisualization=function(){this.handles.remove("visualization-handle")};g._snapSinglePoint=function(){var b=v._asyncToGenerator(function*({point:a,context:c,signal:d}){const {view:e}=this,f=x.pointToSnappingPoint(a,e,c),l=yield this._fetchCandidates(f,z.SnappingDomain.ALL,c,d);return this._createSnapResult(f,r.MAIN,l,e,c,{z:a.z,m:a.m,spatialReference:a.spatialReference,elevationInfo:c.elevationInfo},
d)});return function(a){return b.apply(this,arguments)}}();g._snapMultiPoint=function(){var b=v._asyncToGenerator(function*({point:a,scenePoint:c,context:d,signal:e}){const {view:f}=this,{coordinateHelper:l,spatialReference:m}=d;yield C.initializeProjection(c.spatialReference,m);c=C.project(c,m);var h=x.pointToSnappingPoint(c,f,d);const k=yield this._fetchCandidates(h,z.SnappingDomain.FEATURE,d,e);if(0<k.length)return a=yield this._fetchCandidates(h,z.SnappingDomain.SELF,d,e),this._createSnapResult(h,
r.SCENE,[...k,...a],f,d,{z:c.z,m:c.m,spatialReference:c.spatialReference,elevationInfo:d.elevationInfo},e);c=x.pointToSnappingPoint(a,f,d);h=yield this._fetchCandidates(c,z.SnappingDomain.SELF,d,e);return this._createSnapResult(c,r.MAIN,h,f,d,{z:l.hasZ()&&a.hasZ?a.z??0:void 0,m:l.hasM()&&a.hasM?a.m??0:void 0,spatialReference:a.spatialReference,elevationInfo:d.elevationInfo},e)});return function(a){return b.apply(this,arguments)}}();g._fetchCandidates=function(){var b=v._asyncToGenerator(function*(a,
c,d,e){return(yield Promise.all(this._engines.map(f=>f.fetchCandidates(a,c,d,e)))).flat()});return function(a,c,d,e){return b.apply(this,arguments)}}();g._createSnapResult=function(b,a,c,d,e,f,l){return{get valid(){return!J.isAborted(l)},apply:()=>{const {spatialReference:m}=e,{snappedPoint:h,hints:k}=this._processCandidates(b,a,c,e);this._removeVisualization();u.isSome(e.visualizer)&&this.handles.add(e.visualizer.draw(k,{spatialReference:m,elevationInfo:D.absoluteHeightElevationInfo,view:d,selfSnappingZ:e.selfSnappingZ}),
"visualization-handle");return x.snappingPointToSnappingOutput(h,d,f)}}};g._processCandidates=function(b,a,c,d){if(1>c.length)return this.doneSnapping(),{snappedPoint:b,hints:[]};this._currentSnappedType!==a&&this._resetSnappingState();F.sortCandidatesInPlace(b,c);const e=this._currentMainCandidate;if(u.isSome(e)){const f=this._findOldConstraintInNewCandidates(e,c);if(0<=f)if(c[f]instanceof A.IntersectionSnappingCandidate){if(this._arePointsWithinScreenThreshold(b,e.targetPoint,d))return this._updateSnappingCandidate(e,
a,c,d)}else return this._intersectWithOtherCandidates(f,c,b,a,d)}return this._intersectWithOtherCandidates(0,c,b,a,d)};g._findOldConstraintInNewCandidates=function(b,a){return b instanceof A.IntersectionSnappingCandidate?0<=this._findOldCandidateIndex(a,b.first)&&0<=this._findOldCandidateIndex(a,b.second)?0:-1:this._findOldCandidateIndex(a,b)};g._intersectWithOtherCandidates=function(b,a,c,d,e){const {coordinateHelper:f}=e,l=a[b],m=[];for(let h=0;h<a.length;++h){if(h===b)continue;const k=a[h];for(const B of l.constraint.intersect(k.constraint)){const G=
B.closestTo(l.targetPoint);m.push([new A.IntersectionSnappingCandidate(G,l,k,k.isDraped),this._squaredScreenDistance(c,G,f)])}}return 0<m.length&&(m.sort((h,k)=>h[1]-k[1]),m[0][1]<this._squaredPointProximityThreshold(e.pointer))?this._updateSnappingCandidate(m[0][0],d,a,e):this._updateSnappingCandidate(l,d,a,e)};g._updateSnappingCandidate=function(b,a,c,d){this.doneSnapping();this._currentMainCandidate=b;this._currentSnappedType=a;a=this._currentMainCandidate.targetPoint;const e=[];e.push(...b.hints);
for(const f of c){if(b instanceof A.IntersectionSnappingCandidate){if(f.constraint.equals(b.first.constraint)||f.constraint.equals(b.second.constraint))continue}else if(f.constraint.equals(b.constraint))continue;c=f.constraint.closestTo(a);this._squaredScreenDistance(c,a,d.coordinateHelper)<this._squaredSatisfiesConstraintThreshold&&(f.targetPoint=a,this._currentOtherActiveCandidates.push(f),e.push(...f.hints))}return{snappedPoint:a,hints:e}};g._squaredPointProximityThreshold=function(b){return"touch"===
b?this._squaredTouchProximityThreshold:this._squaredMouseProximityTreshold};g._arePointsWithinScreenThreshold=function(b,a,c){return this._squaredScreenDistance(b,a,c.coordinateHelper)<this._squaredPointProximityThreshold(c.pointer)};g._squaredScreenDistance=function(b,a,c){return F.squaredScreenDistance(this._toScreen(b,c),this._toScreen(a,c))};g._toScreen=function(b,a){return N.vectorToScreenPoint(b,a.spatialReference,D.absoluteHeightElevationInfo,this.view)};g._findOldCandidateIndex=function(b,
a){let c=-1;for(let d=0;d<b.length;++d)if(a.constraint.equals(b[d].constraint)){c=d;break}return c};v._createClass(y,[{key:"updating",get:function(){return this._engines.some(b=>b.updating)}},{key:"_squaredMouseProximityTreshold",get:function(){return this.options.distance*this.options.distance}},{key:"_squaredTouchProximityThreshold",get:function(){const {distance:b,touchSensitivityMultiplier:a}=this.options,c=b*a;return c*c}},{key:"_squaredSatisfiesConstraintThreshold",get:function(){return E.defaults.satisfiesConstraintScreenThreshold*
E.defaults.satisfiesConstraintScreenThreshold}},{key:"test",get:function(){return{visualizationsActive:this.handles.has("visualization-handle"),engines:this._engines}}}]);return y}(H.EventedMixin(I.HandleOwner));p.__decorate([t.property({constructOnly:!0})],n.SnappingManager.prototype,"view",void 0);p.__decorate([t.property()],n.SnappingManager.prototype,"options",void 0);p.__decorate([t.property({readOnly:!0})],n.SnappingManager.prototype,"updating",null);p.__decorate([t.property()],n.SnappingManager.prototype,
"snappingEnginesFactory",void 0);p.__decorate([t.property()],n.SnappingManager.prototype,"_engines",void 0);p.__decorate([t.property()],n.SnappingManager.prototype,"_squaredMouseProximityTreshold",null);p.__decorate([t.property()],n.SnappingManager.prototype,"_squaredTouchProximityThreshold",null);p.__decorate([t.property()],n.SnappingManager.prototype,"_squaredSatisfiesConstraintThreshold",null);n.SnappingManager=p.__decorate([K.subclass("esri.views.interactive.snapping.SnappingManager")],n.SnappingManager);
var r;(function(q){q[q.MAIN=0]="MAIN";q[q.SCENE=1]="SCENE"})(r||(r={}));Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});