// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Handles ../../../../core/Logger ../../../../core/maybe ../../../../core/quantityUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/geometryEngine ../../../../geometry/Polyline ../../../../geometry/projection ../../../../geometry/spatialReferenceEllipsoidUtils ../../../../geometry/support/geodesicUtils ../interfaces ../support/projectionUtils ../support/UnitNormalizer".split(" "),
function(f,x,p,F,G,H,k,r,l,t,O,P,I,y,q,J,K,g,w,u,z,A,L){const M=H.getLogger("esri.views.3d.analysis.DirectLineMeasurement.DirectLineMeasurementController");f.DirectLineMeasurementController=function(B){function v(a){a=B.call(this,a)||this;a._unitNormalizer=new L.UnitNormalizer;a._handles=new G;a._tempStartPosition=q.create();a._tempEndPosition=q.create();a._tempCornerPosition=q.create();return a}x._inheritsLoose(v,B);var m=v.prototype;m.initialize=function(){const a=this.view.spatialReference;var c=
w.getSphericalPCPF(a);this._sphericalPCPF=c=c===w.SphericalECEFSpatialReference?w.WGS84ECEFSpatialReference:c;const e=g.canProjectWithoutEngine(a,c);this._unitNormalizer.spatialReference=e?c:a;this._handles.add([l.watch(()=>({viewData:this.viewData,startPoint:this.analysis.startPoint}),({viewData:b,startPoint:d})=>{b.elevationAlignedStartPoint=this._applyProjectionAndElevationAlignment(d)},l.syncAndInitial),l.watch(()=>({viewData:this.viewData,endPoint:this.analysis.endPoint}),({viewData:b,endPoint:d})=>
{b.elevationAlignedEndPoint=this._applyProjectionAndElevationAlignment(d)},l.syncAndInitial),l.watch(()=>({result:this._computedResult,viewData:this.viewData}),({result:b,viewData:d})=>{d.result=b},l.syncAndInitial)])};m.destroy=function(){this._handles=k.destroyMaybe(this._handles)};m._applyProjectionAndElevationAlignment=function(a){if(k.isNone(a))return a;const {spatialReference:c,elevationProvider:e}=this.view,b=A.applyProjectionAndElevationAlignment(a,c,e);return k.isNone(b)?(A.logFailedGeometryProjectionError(this.analysis,
a.spatialReference,M),null):b};m._euclideanDistances=function(a,c){var e=a.clone();e.z=c.z;const b=this._tempStartPosition;var d=this._tempEndPosition,h=this._tempCornerPosition,n=this.view.spatialReference;const C=this._sphericalPCPF;n=g.canProjectWithoutEngine(n,C)?C:n;g.projectPointToVector(a,b,n);g.projectPointToVector(c,d,n);g.projectPointToVector(e,h,n);e=y.distance(b,d);d=y.distance(h,d);a=Math.abs(c.z-a.z);c=N=>this._unitNormalizer.normalizeDistance(N);h=c(e);d=c(d);a=c(a);return{direct:r.createQuantity(h,
"meters"),horizontal:r.createQuantity(d,"meters"),vertical:r.createQuantity(a,"meters")}};m._geodesicDistance=function(a,c,e){var b=a.spatialReference;const d=new K({spatialReference:b});d.addPath([a,c]);b=b.isGeographic&&u.isSupported(b)?u.geodesicLengths([d],"meters")[0]:b.isWebMercator?J.geodesicLength(d,"meters"):null;a=k.isSome(b)?b:this._fallbackGeodesicDistance(a,c,e);return r.createQuantity(a,"meters")};m._fallbackGeodesicDistance=function(a,c,e){return g.projectPointToWGS84ComparableLonLat(a,
D)&&g.projectPointToWGS84ComparableLonLat(c,E)?(a=new u.InverseGeodeticSolverResult,u.inverseGeodeticSolver(a,D,E),a.distance):e};x._createClass(v,[{key:"_computedResult",get:function(){const {elevationAlignedStartPoint:a,elevationAlignedEndPoint:c,measurementMode:e}=this.viewData;if(k.isNone(a)||k.isNone(c))return null;const b=this._euclideanDistances(a,c),d=this._geodesicDistance(a,c,b.horizontal.value),h=e===z.MeasurementMode.Geodesic||e===z.MeasurementMode.Auto&&1E5<b.horizontal.value?"geodesic":
"euclidean";return{mode:h,distance:"euclidean"===h?b.direct:d,directDistance:b.direct,horizontalDistance:b.horizontal,verticalDistance:b.vertical,geodesicDistance:d}}}]);return v}(F);p.__decorate([t.property()],f.DirectLineMeasurementController.prototype,"view",void 0);p.__decorate([t.property()],f.DirectLineMeasurementController.prototype,"analysis",void 0);p.__decorate([t.property()],f.DirectLineMeasurementController.prototype,"viewData",void 0);p.__decorate([t.property()],f.DirectLineMeasurementController.prototype,
"_computedResult",null);f.DirectLineMeasurementController=p.__decorate([I.subclass("esri.views.3d.analysis.DirectLineMeasurement.DirectLineMeasurementController")],f.DirectLineMeasurementController);const D=q.create(),E=q.create();Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});