// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4f64 ./Object3DVisualElement ../../support/engineContent/line ../../webgl-engine/lib/Material ../../webgl-engine/materials/RibbonLineMaterial".split(" "),function(t,u,g,v,z,k,h,p,r,w,A,B){r=function(x){function q(a,c){var b=x.call(this,a)||this;b._hasExternalMaterial=!1;b._hasExternalMaterial=
g.isSome(c);b._material=g.isSome(c)?c:new B.RibbonLineMaterial({width:1,color:p.fromValues(1,0,1,1),stippleOffColor:null,stipplePattern:null,stipplePreferContinuous:!0,isClosed:!1,falloff:0,innerColor:null,innerWidth:1,hasPolygonOffset:!1,renderOccluded:A.RenderOccludedFlag.OccludeAndTransparent,writeDepth:!0});b.applyProps(a);return b}u._inheritsLoose(q,x);var f=q.prototype;f.setGeometryFromRenderSpacePoint=function(a,c=1E3){this.geometry=[[[a[0]-c,a[1]+0,a[2]+0],[a[0]+c,a[1]+0,a[2]+0]],[[a[0]-0,
a[1]-c,a[2]+0],[a[0]+0,a[1]+c,a[2]+0]],[[a[0]-0,a[1]+0,a[2]-c],[a[0]+0,a[1]+0,a[2]+c]]]};f.setGeometryFromExtent=function(a){const c=this.view.spatialReference,b=h.create(),d=h.create(),e=[];k.set(b,a[0],a[1],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);k.set(b,a[2],a[1],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);k.set(b,a[2],a[3],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);k.set(b,a[0],
a[3],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);k.set(b,a[0],a[1],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);k.set(b,a[0],a[1],100);this.view.renderCoordsHelper.toRenderCoords(b,c,d);e.push([d[0],d[1],d[2]]);this.geometry=[e]};f.setGeometryFromFrustum=function(a){const c=[];a.lines.forEach(b=>{c.push([b.origin[0],b.origin[1],b.origin[2]]);c.push([b.endpoint[0],b.endpoint[1],b.endpoint[2]])});this.geometry=[c]};f.setGeometryFromBoundedPlane=
function(a){const c=[],b=a.origin,d=a.basis1;a=a.basis2;const e=h.create(),l=h.create(),m=h.create(),n=h.create();e[0]=b[0]-.5*d[0]-.5*a[0];e[1]=b[1]-.5*d[1]-.5*a[1];e[2]=b[2]-.5*d[2]-.5*a[2];l[0]=b[0]-.5*d[0]+.5*a[0];l[1]=b[1]-.5*d[1]+.5*a[1];l[2]=b[2]-.5*d[2]+.5*a[2];m[0]=b[0]+.5*d[0]+.5*a[0];m[1]=b[1]+.5*d[1]+.5*a[1];m[2]=b[2]+.5*d[2]+.5*a[2];n[0]=b[0]+.5*d[0]-.5*a[0];n[1]=b[1]+.5*d[1]-.5*a[1];n[2]=b[2]+.5*d[2]-.5*a[2];c.push([e[0],e[1],e[2]]);c.push([l[0],l[1],l[2]]);c.push([m[0],m[1],m[2]]);
c.push([n[0],n[1],n[2]]);c.push([e[0],e[1],e[2]]);this.geometry=[c]};f.setGeometryFromSegment=function(a){const c=a.endRenderSpace;this.transform=v.fromTranslation(y,c);({points:a}=a.createRenderGeometry(c,this.view.renderCoordsHelper));this.geometry=[a]};f.setGeometryFromSegments=function(a,c=h.ZEROS){this.transform=v.fromTranslation(y,c);this.geometry=a.map(b=>b.createRenderGeometry(c,this.view.renderCoordsHelper).points)};f.getTransformedGeometry=function(){return g.isNone(this._geometry)?null:
this._geometry.map(a=>a.map(c=>k.transformMat4(h.create(),c,this.transform)))};f.createExternalResources=function(){};f.destroyExternalResources=function(){};f.createGeometries=function(a){for(const c of w.lineStripsToParameters(this.geometry)){const b=w.createGeometry(g.unwrap(this._material),c);a.addGeometry(b)}};f.forEachExternalMaterial=function(a){this._hasExternalMaterial||a(g.unwrap(this._material))};u._createClass(q,[{key:"renderOccluded",get:function(){return this._material.parameters.renderOccluded},
set:function(a){this._material.setParameters({renderOccluded:a})}},{key:"geometry",get:function(){return this._geometry},set:function(a){this._geometry=a;this.recreateGeometry()}},{key:"width",get:function(){return this._material.parameters.width},set:function(a){this._material.setParameters({width:a})}},{key:"color",get:function(){return this._material.parameters.color},set:function(a){this._material.setParameters({color:p.clone(a)})}},{key:"innerWidth",get:function(){return this._material.parameters.innerWidth},
set:function(a){this._material.setParameters({innerWidth:a})}},{key:"innerColor",get:function(){return this._material.parameters.innerColor},set:function(a){this._material.setParameters({innerColor:g.isSome(a)?p.clone(a):null})}},{key:"stipplePattern",get:function(){return this._material.parameters.stipplePattern},set:function(a){g.isSome(this._material)&&this._material.setParameters({stipplePattern:a})}},{key:"stippleOffColor",get:function(){return this._material.parameters.stippleOffColor},set:function(a){this._material.setParameters({stippleOffColor:g.isSome(a)?
p.clone(a):null})}},{key:"stipplePreferContinuous",get:function(){return this._material.parameters.stipplePreferContinuous},set:function(a){this._material.setParameters({stipplePreferContinuous:a})}},{key:"writeDepthEnabled",get:function(){return this._material.parameters.writeDepth},set:function(a){this._material.setParameters({writeDepth:a})}},{key:"falloff",get:function(){return this._material.parameters.falloff},set:function(a){this._material.setParameters({falloff:a})}},{key:"polygonOffset",
get:function(){return this._material.parameters.hasPolygonOffset},set:function(a){this._material.setParameters({hasPolygonOffset:a})}}]);return q}(r.Object3DVisualElement);const y=z.create();t.LineVisualElement=r;Object.defineProperty(t,Symbol.toStringTag,{value:"Module"})});