// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../core/analysisThemeUtils ../../../../core/Handles ../../../../core/mathUtils ../../../../core/maybe ../../../../core/reactiveUtils ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4f64 ../../../../geometry/support/vectorStacks ./Object3DVisualElement ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/Material ../../webgl-engine/materials/MeasurementArrowMaterial".split(" "),
function(x,y,q,r,D,k,f,E,F,G,z,t,l,u,H,I,J){u=function(A){function m(a){var b=A.call(this,a)||this;b._parameters={arrowWidth:16,arrowOutlineColor:q.toUnitRGBA(r.getAccentColor()),arrowStripeEvenColor:q.toUnitRGBA(r.getContrastColor()),arrowStripeOddColor:q.toUnitRGBA(r.getAccentColor()),arrowSubdivisions:128};b._origin=z.create();b._originTransform=F.create();b._arrowCenter=z.create();b._renderOccluded=I.RenderOccludedFlag.OccludeAndTransparent;b._geometry=null;b._stripeLength=1;b._stripesEnabled=
!0;b._opacity=1;b.applyProps(a);return b}y._inheritsLoose(m,A);var d=m.prototype;d.createExternalResources=function(){const {arrowStripeEvenColor:a,arrowStripeOddColor:b,arrowOutlineColor:e}=this._parameters;this._arrowMaterial=new J.MeasurementArrowMaterial({outlineColor:e,stripeEvenColor:this._stripesEnabled?a:b,stripeOddColor:b,renderOccluded:this.renderOccluded,polygonOffset:!0});this._handles=new D;this._handles.add(E.watch(()=>this.view.state.camera,()=>{this._viewChanged()}))};d.destroyExternalResources=
function(){this._arrowMaterial=null;this._handles=f.destroyMaybe(this._handles)};d.forEachExternalMaterial=function(a){a(this._arrowMaterial)};d.createGeometries=function(a){if(!(f.isNone(this._geometry)||f.isNone(this._geometry.startRenderSpace)||f.isNone(this._geometry.endRenderSpace))){var b=this._createArrowGeometry(this._geometry.startRenderSpace,this._geometry.endRenderSpace,this._origin,this._geometry);b.transformation=this._originTransform;a.addGeometry(b);this._viewChanged()}};d._createArrowGeometry=
function(a,b,e,c){const n=this.view.renderCoordsHelper,p=[],B=[],w=(v,g)=>{const h=l.sv3d.get();G.subtract(h,v,e);p.push(h);B.push(g)};if("euclidean"===c.type)c.eval(.5,this._arrowCenter),c=l.sv3d.get(),n.worldUpAtPosition(this._arrowCenter,c),w(a,c),w(b,c);else for(c.eval(.5,this._arrowCenter),a=this._parameters.arrowSubdivisions+1&-2,b=0;b<a;++b){const v=b/(a-1),g=l.sv3d.get(),h=l.sv3d.get();c.eval(v,g);n.worldUpAtPosition(g,h);w(g,h)}return H.createPolylineGeometry(this._arrowMaterial,p,B)};d._geometryChanged=
function(){this.recreateGeometry()};d._viewChanged=function(){if(this.view.ready&&this.attached&&f.isSome(this._geometry)){const a=this.view.state.camera.computeScreenPixelSizeAt(this._arrowCenter);this._arrowMaterial.setParameters({width:this._parameters.arrowWidth*a})}};d._updateArrowOpacity=function(){var a=this.opacity;const {arrowStripeEvenColor:b,arrowStripeOddColor:e,arrowOutlineColor:c}=this._parameters,n=k.applyOpacity(C,this._stripesEnabled?b:e,a),p=k.applyOpacity(K,c,a);a=k.applyOpacity(L,
e,a);this._arrowMaterial.setParameters({stripeEvenColor:n,outlineColor:p,stripeOddColor:a})};y._createClass(m,[{key:"renderOccluded",get:function(){return this._renderOccluded},set:function(a){a!==this._renderOccluded&&(this._renderOccluded=a,this._arrowMaterial&&this._arrowMaterial.setParameters({renderOccluded:a}))}},{key:"geometry",get:function(){return this._geometry},set:function(a){this._geometry=a;this._geometryChanged()}},{key:"stripeLength",get:function(){return this._stripeLength},set:function(a){this._stripeLength=
a;this.attached&&this._arrowMaterial.setParameters({stripeLength:this._stripeLength})}},{key:"stripesEnabled",get:function(){return this._stripesEnabled},set:function(a){this._stripesEnabled=a;if(this.attached){a=this.opacity;const {arrowStripeEvenColor:b,arrowStripeOddColor:e}=this._parameters;a=k.applyOpacity(C,this._stripesEnabled?b:e,a);this._arrowMaterial.setParameters({stripeEvenColor:a})}}},{key:"opacity",get:function(){return this._opacity},set:function(a){a!==this._opacity&&(this._opacity=
a,this._updateArrowOpacity())}}]);return m}(u.Object3DVisualElement);const C=t.create(),K=t.create(),L=t.create();x.MeasurementArrowVisualElement=u;Object.defineProperty(x,Symbol.toStringTag,{value:"Module"})});