// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/Error ../../../core/events ../../../core/has ../../../core/maybe ../../../core/scheduling ../../../chunks/mat3f32 ../../../symbols/cim/CIMResourceManager ./Container ./webgl/BufferPool ./webgl/enums ./webgl/Painter ./webgl/Profiler ../support/Timeline ../../support/screenshotUtils ../../webgl/context-util ../../webgl/enums ../../webgl/FramebufferObject ../../webgl/RenderingContext ../../../core/imageUtils".split(" "),function(r,
l,x,y,v,t,z,A,B,w,C,m,D,E,F,G,H,n,I,J,K){let L=function(u){function p(c,b){var a=u.call(this)||this;a._trash=new Set;a._renderRemainingTime=0;a._lastFrameRenderTime=0;a.renderRequested=!1;a.stage=l._assertThisInitialized(a);a._stationary=!0;const {canvas:d=document.createElement("canvas"),alpha:k=!0,stencil:e=!0,contextOptions:f={}}=b;a._canvas=d;const h=H.createContextOrErrorHTML("2d",d,{alpha:k,antialias:!1,depth:!0,stencil:e});a.context=new J.RenderingContext(t.unwrap(h)??null,f);a.resourceManager=
new B;a.painter=new D(a.context,l._assertThisInitialized(a),a.resourceManager);v("esri-2d-profiler")&&(a._debugOutput=document.createElement("div"),a._debugOutput.setAttribute("style","margin: 24px 64px; position: absolute; color: red;"),c.appendChild(a._debugOutput));a._renderParameters={drawPhase:0,state:a.state,pixelRatio:window.devicePixelRatio,stationary:!1,globalOpacity:1,blendMode:null,deltaTime:-1,time:0,inFadeTransition:!1,effects:null,context:a.context,painter:a.painter,timeline:b.timeline||
new F.Timeline,renderingOptions:b.renderingOptions,requestRender:()=>a.requestRender(),allowDelayedRender:!1,requireFBO:!1,profiler:new E.Profiler(a.context,a._debugOutput),dataUploadCounter:0,get highlightGradient(){return a._highlightGradient}};a._taskHandle=z.addFrameTask({render:q=>a.renderFrame(q)});a._taskHandle.pause();a._lostWebGLContextHandle=y.on(d,"webglcontextlost",()=>{a.emit("webgl-error",{error:new x("webgl-context-lost")})});a._bufferPool=new C.BufferPool;d.setAttribute("style","width: 100%; height:100%; display:block;");
c.appendChild(d);return a}l._inheritsLoose(p,u);var g=p.prototype;g.destroy=function(){this.removeAllChildren();this._emptyTrash();this._taskHandle=t.removeMaybe(this._taskHandle);this._lostWebGLContextHandle=t.removeMaybe(this._lostWebGLContextHandle);this._canvas.parentNode?.removeChild(this._canvas);this._debugOutput?.parentNode?.removeChild(this._debugOutput);this._bufferPool.destroy();this.resourceManager.destroy();this.painter.dispose();this.context.dispose();this._canvas=null};g.trashDisplayObject=
function(c){this._trash.add(c);this.requestRender()};g.untrashDisplayObject=function(c){return this._trash.delete(c)};g.requestRender=function(){this._renderRemainingTime=2E3;this.renderRequested||(this.renderRequested=!0,this.emit("will-render"),this._taskHandle.resume())};g.renderFrame=function(c){this._renderRemainingTime-=this._lastFrameRenderTime?c.time-this._lastFrameRenderTime:0;0>=this._renderRemainingTime&&this._taskHandle.pause();this._lastFrameRenderTime=c.time;this.renderRequested=!1;
this._renderParameters.state=this._state;this._renderParameters.stationary=this.stationary;this._renderParameters.pixelRatio=window.devicePixelRatio;this._renderParameters.globalOpacity=1;this._renderParameters.time=c.time;this._renderParameters.deltaTime=c.deltaTime;this._renderParameters.effects=null;this.processRender(this._renderParameters);this._emptyTrash();this.emit("post-render")};g._createTransforms=function(){return{dvs:A.create()}};g.renderChildren=function(c){for(const b of this.children)b.beforeRender(c);
this._renderChildren(this.children,c);for(const b of this.children)b.afterRender(c)};g._renderChildren=function(c,b){const a=this.context;this.painter.textureUploadManager.upload();a.resetInfo();b.profiler.recordStart("drawLayers");b.dataUploadCounter=0;b.drawPhase=m.WGLDrawPhase.MAP;this.painter.beforeRenderLayers(a,this.background);for(const d of c)d.processRender(b);this.painter.prepareDisplay(b,this.background,this.state.padding);this.painter.renderLayers(a);b.drawPhase=m.WGLDrawPhase.HIGHLIGHT;
this.painter.beforeRenderLayers(a);for(const d of c)d.processRender(b);this.painter.renderLayers(a);if(this._isLabelDrawPhaseRequired(c)){b.drawPhase=m.WGLDrawPhase.LABEL;this.painter.beforeRenderLayers(a);for(const d of c)d.processRender(b);this.painter.renderLayers(a)}if(v("esri-tiles-debug")){b.drawPhase=m.WGLDrawPhase.DEBUG;this.painter.beforeRenderLayers(a);for(const d of c)d.processRender(b);this.painter.renderLayers(a)}b.profiler.recordEnd("drawLayers");a.logInfo()};g.doRender=function(c){const b=
this.context,{state:a,pixelRatio:d}=c;this._resizeCanvas(c);b.setViewport(0,0,d*a.size[0],d*a.size[1]);b.setDepthWriteEnabled(!0);b.setStencilWriteMask(255);u.prototype.doRender.call(this,c)};g.takeScreenshot=function(){var c=l._asyncToGenerator(function*(b){const {framebufferWidth:a,framebufferHeight:d}={framebufferWidth:Math.round(this.state.size[0]*b.resolutionScale),framebufferHeight:Math.round(this.state.size[1]*b.resolutionScale)};var k=b.resolutionScale,e=this.context,f=this._state.clone();
if(null!=b.rotation){var h=f.viewpoint;f.viewpoint.rotation=b.rotation;f.viewpoint=h}h={...this._renderParameters,drawPhase:null,globalOpacity:1,stationary:!0,state:f,pixelRatio:k,time:performance.now(),deltaTime:0,blendMode:null,effects:null,inFadeTransition:!1};const q=new I.FramebufferObject(e,{colorTarget:n.TargetType.TEXTURE,depthStencilTarget:n.DepthStencilTargetType.DEPTH_STENCIL_RENDER_BUFFER,width:a,height:d});k=e.getBoundFramebufferObject();f=e.getViewport();e.bindFramebuffer(q);e.setViewport(0,
0,a,d);this._renderChildren(b.children,h);h=this._readbackScreenshot(q,{...b.cropArea,y:d-(b.cropArea.y+b.cropArea.height)});e.bindFramebuffer(k);e.setViewport(f.x,f.y,f.width,f.height);this.requestRender();e=yield h;1===b.outputScale?b=e:(b=new ImageData(Math.round(e.width*b.outputScale),Math.round(e.height*b.outputScale)),G.resampleHermite(e,b,!0));return b});return function(b){return c.apply(this,arguments)}}();g._readbackScreenshot=function(){var c=l._asyncToGenerator(function*(b,a){const d=K.createEmptyImageData(a.width,
a.height,document.createElement("canvas"));yield b.readPixelsAsync(a.x,a.y,a.width,a.height,n.PixelFormat.RGBA,n.PixelType.UNSIGNED_BYTE,new Uint8Array(d.data.buffer));return d});return function(b,a){return c.apply(this,arguments)}}();g._resizeCanvas=function(c){const b=this._canvas,a=b.style,{state:{size:d},pixelRatio:k}=c;c=d[0];const e=d[1],f=Math.round(c*k),h=Math.round(e*k);if(b.width!==f||b.height!==h)b.width=f,b.height=h;a.width=c+"px";a.height=e+"px"};g._emptyTrash=function(){for(;0<this._trash.size;){const c=
Array.from(this._trash);this._trash.clear();for(const b of c)b.processDetach()}};g._isLabelDrawPhaseRequired=function(c){let b=!1;for(const a of c){if(!(a instanceof w.Container)){b=b||!1;break}if(a.hasLabels)return!0;b=b||this._isLabelDrawPhaseRequired(a.children)}return b};l._createClass(p,[{key:"background",get:function(){return this._background},set:function(c){this._background=c;this.requestRender()}},{key:"bufferPool",get:function(){return this._bufferPool}},{key:"renderingOptions",get:function(){return this._renderingOptions},
set:function(c){this._renderingOptions=c;this.requestRender()}},{key:"state",get:function(){return this._state},set:function(c){this._state=c;this.requestRender()}},{key:"stationary",get:function(){return this._stationary},set:function(c){this._stationary!==c&&(this._stationary=c,this.requestRender())}}]);return p}(w.Container);r.EXTRA_RENDER_TIME=2E3;r.Stage=L;Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});