// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ./chunks/_rollupPluginBabelHelpers ./Graphic ./arcade/ArcadeDate ./arcade/ImmutableArray ./core/Error ./core/lang ./layers/FeatureLayer ./portal/Portal ./rest/support/FeatureSet ./support/arcadeOnDemand".split(" "),function(t,A,K,u,L,v,M,N,O,P,Q){function R(b,a,c,e={}){a=a.elementType;const d="array"===a.type?[{name:"value",type:a.type,elementType:a.elementType}]:"dictionary"===a.type?[{name:"value",type:a.type,properties:a.properties}]:[{name:"value",type:a.type}];return new L(b.map(f=>
{const h={};w(h,d,{value:f},c,e);return h.value}))}function S(b,a,c={}){b=b instanceof P?new N({source:b.features,geometryType:b.geometryType,fields:b.fields,spatialReference:b.spatialReference}):b;return a.constructFeatureSet(b,c.spatialReference,null,!0,c.lruCache,c.interceptor)}function T(b,a,c={}){const {spatialReference:e,interceptor:d,lruCache:f}=c;return"string"===typeof b?a.createFeatureSetCollectionFromService(b,e,f,d):a.createFeatureSetCollectionFromMap(b,e,f,d)}function U(b,a,c,e={}){const d=
{};w(d,a.properties,b,c,e);return new q.Dictionary(d)}function w(b,a,c,e,d={}){const f={};for(const h of Object.keys(c))f[h.toLowerCase()]=c[h];for(const h of a)if(a=h.name.toLowerCase(),d.variablesPreProcessed)b[a]=f[a];else switch(h.type){case "array":b[a]=R(f[a],h,e,d);break;case "feature":c=f[a];b[a]=null==c?null:q.Feature.createFromGraphic(c,d?.timeReference);break;case "featureSet":c=f[a];b[a]=e?S(c,e,d):null;break;case "featureSetCollection":c=f[a];b[a]=e?T(c,e,d):null;break;case "dictionary":b[a]=
U(f[a],h,e,d);break;case "date":c=f[a];b[a]=c?c instanceof u.ArcadeDate?c:d?.timeReference?.timeZone?u.ArcadeDate.dateJSAndZoneToArcadeDate(c,d?.timeReference?.timeZone):u.ArcadeDate.dateJSToArcadeDate(c):null;break;case "geometry":case "boolean":case "text":case "number":b[a]=f[a]}}function B(b,a){for(const c of b)a.push(c),"dictionary"===c.type&&B(c.properties,a);return a}function C(b,a,c,e,d){const {spatialReference:f,interceptor:h,lruCache:x,console:n,abortSignal:l,timeReference:k,services:y=
{portal:O.getDefault()}}=c;d={vars:{},spatialReference:f,interceptor:h,timeReference:k,lrucache:x,useAsync:d,services:y,console:n,abortSignal:l};if(!a)return d;w(d.vars,b.variables,a,e,c);return d}function r(b,a){switch(a.getArcadeType(b)){case "date":return b.toJSDate();case "feature":var c="geometry"in b?b.geometry():null;b="readAttributes"in b?b.readAttributes():b.attributes;return new K({geometry:c,attributes:b});case "dictionary":c=b.attributes;const e={};for(const d of Object.keys(c))e[d]=r(b.field(d),
a);return e;case "array":return("toArray"in b?b.toArray():b).map(d=>r(d,a))}return b}function z(){z=A._asyncToGenerator(function*(b,a,c={}){q||(q=yield Q.loadArcade());const {arcade:e,arcadeUtils:d}=q,{loadScriptDependencies:f,referencesMember:h,scriptIsAsync:x}=e;var n=B(a.variables,[]),l=n.filter(g=>"featureSet"===g.type||"featureSetCollection"===g.type).map(g=>g.name.toLowerCase());const k=e.parseScript(b,l);if(!k)throw new v("arcade:invalid-script","Unable to create SyntaxTree");b=d.extractFieldNames(k);
const y=e.scriptTouchesGeometry(k);n=n.map(g=>g.name.toLowerCase()).filter(g=>h(k,g));const p=x(k,l);yield f(k,p,l);l={vars:{},spatialReference:null,useAsync:p};for(const g of n)l.vars[g]="any";const {lruCache:D}=c,E=e.compileScript(k,l),F=e.featureSetUtils();return{execute:(g,m={})=>{if(p)throw new v("arcade:invalid-execution-mode","Cannot execute the script in synchronous mode");g=E(C(a,g,{lruCache:D,...m},F,p));return m.rawOutput?g:r(g,d)},executeAsync:function(){var g=A._asyncToGenerator(function*(m,
G={}){m=yield E(C(a,m,{lruCache:D,...G},F,p));return G.rawOutput?m:r(m,d)});return function(m){return g.apply(this,arguments)}}(),isAsync:p,variablesUsed:n,fieldsUsed:b,geometryUsed:y,syntaxTree:k}});return z.apply(this,arguments)}let q=null;const H={variables:[{name:"$feature",type:"feature"},{name:"$layer",type:"featureSet"},{name:"$datastore",type:"featureSetCollection"},{name:"$map",type:"featureSetCollection"}]},I={variables:[{name:"$feature",type:"feature"},{name:"$aggregatedFeatures",type:"featureSet"}]},
J=new Map([["form-constraint",{variables:[{name:"$feature",type:"feature"}]}],["feature-z",{variables:[{name:"$feature",type:"feature"}]}],["field-calculation",{variables:[{name:"$feature",type:"feature"},{name:"$datastore",type:"featureSetCollection"}]}],["form-calculation",{variables:[{name:"$feature",type:"feature"},{name:"$originalFeature",type:"feature"},{name:"$layer",type:"featureSet"},{name:"$featureSet",type:"featureSet"},{name:"$datastore",type:"featureSetCollection"},{name:"$map",type:"featureSetCollection"},
{name:"$editContext",type:"dictionary",properties:[{name:"editType",type:"text"}]}]}],["labeling",{variables:[{name:"$feature",type:"feature"}]}],["popup",H],["popup-element",H],["feature-reduction-popup",I],["feature-reduction-popup-element",I],["visualization",{variables:[{name:"$feature",type:"feature"},{name:"$view",type:"dictionary",properties:[{name:"scale",type:"number"}]}]}]]);t.createArcadeExecutor=function(b,a){return z.apply(this,arguments)};t.createArcadeProfile=function(b){var a=J.get(b);
if(!a)throw a=Array.from(J.keys()).map(c=>`'${c}'`).join(", "),new v("createArcadeProfile:invalid-profile-name",`Invalid profile name '${b}'. You must specify one of the following values: ${a}`);return M.clone(a)};Object.defineProperty(t,Symbol.toStringTag,{value:"Module"})});