// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/accessorSupport/decorators/subclass ../../../../support/elevationInfoUtils ../snappingUtils ./queryEngineUtils ./snappingCandidateElevationAlignment ./snappingCandidateElevationFilter ./symbologySnappingCandidates".split(" "),
function(f,m,g,z,h,n,p,k,D,E,A,B,u,v,w,C,x){f.FeatureCollectionSnappingSource=function(y){function r(a){a=y.call(this,a)||this;a.view=null;a._layerView3D=null;return a}m._inheritsLoose(r,y);var t=r.prototype;t.initialize=function(){const {view:a}=this,{layer:c}=this.layerSource;h.isSome(a)&&"3d"===a.type&&"subtype-group"!==c.type&&(a.whenLayerView(c).then(b=>this._layerView3D=b),this.addHandles([a.elevationProvider.on("elevation-change",({context:b})=>{const {elevationInfo:d}=c;B.elevationContextAffectsAlignment(b,
d)&&this._snappingElevationAligner.notifyElevationSourceChange()}),p.watch(()=>c.elevationInfo,()=>this._snappingElevationAligner.notifyElevationSourceChange(),p.initial),p.watch(()=>h.isSome(this._layerView3D)?this._layerView3D.processor?.renderer:null,()=>this._symbologySnappingFetcher.notifySymbologyChange(),p.initial),p.on(()=>h.toNullable(this._layerView3D)?.layer,["edits","apply-edits","graphic-update"],()=>this._symbologySnappingFetcher.notifySymbologyChange())]))};t.refresh=function(){};t.fetchCandidates=
function(){var a=m._asyncToGenerator(function*(c,b){var {layer:d}=this.layerSource,e=d.source;if(!e?.querySnapping)return[];d=u.makeFilter(d);c=u.makeSnappingQuery(c,h.unwrap(this.view)?.type??"2d",d);e=yield e.querySnapping(c,{signal:b});n.throwIfAborted(b);e=yield this._snappingElevationAligner.alignCandidates(e.candidates,b);n.throwIfAborted(b);d=yield this._symbologySnappingFetcher.fetch(e,b);n.throwIfAborted(b);b=0===d.length?e:[...e,...d];b=this._snappingElevationFilter.filter(c,b);const l=
this._getGroundElevation;return b.map(q=>v.convertSnappingCandidate(q,l))});return function(c,b){return a.apply(this,arguments)}}();m._createClass(r,[{key:"availability",get:function(){return 1}},{key:"updating",get:function(){return this.layerSource.updating}},{key:"_snappingElevationAligner",get:function(){const {view:a}=this,{layer:c}=this.layerSource,b=h.isSome(a)&&"3d"===a.type;if(!b||"subtype-group"===c.type)return w.getSnappingCandidateElevationAligner();const d=function(){var e=m._asyncToGenerator(function*(l,
q){return(yield n.whenOrAbort(a.whenLayerView(c),q)).elevationAlignPointsInFeatures(l,q)});return function(l,q){return e.apply(this,arguments)}}();return w.getSnappingCandidateElevationAligner(b,{elevationInfo:c.elevationInfo,alignPointsInFeatures:d,spatialReference:a.spatialReference})}},{key:"_snappingElevationFilter",get:function(){var {view:a}=this;a=h.isSome(a)&&"3d"===a.type&&"subtype-group"!==this.layerSource.layer.type;return C.getSnappingCandidateElevationFilter(a)}},{key:"_symbologySnappingFetcher",
get:function(){const {view:a}=this,{layer:c}=this.layerSource;return h.isSome(a)&&"3d"===a.type&&"subtype-group"!==c.type?x.getSymbologySnappingCandidatesFetcher(this._symbologySnappingSupported,function(){var b=m._asyncToGenerator(function*(d,e){const l=yield a.whenLayerView(c);n.throwIfAborted(e);return l.queryForSymbologySnapping({candidates:d,spatialReference:a.spatialReference},e)});return function(d,e){return b.apply(this,arguments)}}()):x.getSymbologySnappingCandidatesFetcher()}},{key:"_symbologySnappingSupported",
get:function(){return h.isSome(this._layerView3D)&&this._layerView3D.symbologySnappingSupported}},{key:"_getGroundElevation",get:function(){return v.makeGetGroundElevation(this.view)}}]);return r}(z);g.__decorate([k.property({constructOnly:!0})],f.FeatureCollectionSnappingSource.prototype,"layerSource",void 0);g.__decorate([k.property({constructOnly:!0})],f.FeatureCollectionSnappingSource.prototype,"view",void 0);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_snappingElevationAligner",
null);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_snappingElevationFilter",null);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_symbologySnappingFetcher",null);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_layerView3D",void 0);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_symbologySnappingSupported",null);g.__decorate([k.property()],f.FeatureCollectionSnappingSource.prototype,"_getGroundElevation",
null);f.FeatureCollectionSnappingSource=g.__decorate([A.subclass("esri.views.interactive.snapping.featureSources.FeatureCollectionSnappingSource")],f.FeatureCollectionSnappingSource);Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});