// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/time ../../../../../core/Logger ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/Error ../../../../../core/has ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../camera/constraintUtils ../../../camera/constraintUtils/ConstraintTypes ../../../camera/constraintUtils/InteractionType ../../../camera/constraintUtils/TiltMode ../PointToPointAnimationController ../../utils/navigationUtils ../../../webgl-engine/lib/Camera ../../../webgl-engine/lib/Intersector ../../../../animation/easing".split(" "),
function(h,u,v,w,x,y,I,J,K,L,M,z,d,f,A,B,C,D,E,k,p,F,G){h.ZoomStepController=function(q){function m(){var b=q.apply(this,arguments)||this;b._zoomLocation=f.create();b._tmpCamera=new p.Camera;b._tmpRayDir=f.create();b._tmpCenter=f.create();b._constraintOptions={selection:B.ConstraintTypes.ALL,interactionType:C.InteractionType.ZOOM,interactionFactor:null,interactionStartCamera:new p.Camera,interactionDirection:null,tiltMode:D.TiltMode.TUMBLE};return b}u._inheritsLoose(m,q);var n=m.prototype;n.zoomStep=
function(b,c){if(this.active){var e=this.view.state,{interactionStartCamera:a}=this._constraintOptions;a&&(this.animation.finished?a.copyFrom(e.camera):this.animation.cameraAt(1,a));this._tmpCamera.copyFrom(e.camera);a=F.newIntersector(this.view.state.viewingMode);e=!1;0<b?(e=this.intersectionHelper.intersectScreenFreePointFallback(c,this._zoomLocation,0===this.view.map.ground.opacity?k.contentIntersectorOptions:{}),this.intersectionHelper.intersectRay(this._tmpCamera.ray,a,this._tmpCenter)&&(this._tmpCamera.center=
this._tmpCenter)):this.intersectionHelper.intersectRay(this._tmpCamera.ray,a,this._zoomLocation)?this._tmpCamera.center=this._zoomLocation:d.copy(this._zoomLocation,this._tmpCamera.center);b=.6**b;c=this.view._stage.renderView.getMinimalDepthForArea(this.view.voxelWasm,c[0],c[1],this.view.state.camera,60);d.subtract(l,this._tmpCamera.eye,this._zoomLocation);d.normalize(l,l);a=w.clamp(Math.min(k.ZOOM_DISTANCE_MODIFIER,1/Math.abs(d.dot(H,l)))*Math.abs(this.view.camera.position.z),k.ZOOM_MIN_DISTANCE_MODIFIER,
k.ZOOM_MAX_DISTANCE_MODIFIER);if(c=x.isSome(c)?c:a)if(a=f.create(),d.subtract(a,this._zoomLocation,this._tmpCamera.eye),c<d.length(a)||!e)d.normalize(a,a),d.add(this._zoomLocation,this._tmpCamera.eye,d.scale(a,a,c));this._updateCamera(this._tmpCamera,b,this._zoomLocation);this.begin(this._tmpCamera)}};n.animationSettings=function(){return{duration:y.Milliseconds(600),easing:G.outExpo}};n._updateCamera=function(b,c,e){d.subtract(this._tmpRayDir,e,b.eye);const a=d.length(this._tmpRayDir);let g=a*c;
const r=Math.max(4,1.01*b.nearFar[0]);0!==g&&(1>=c&&g<r&&(g=r,c=g/a),1E-6>Math.abs(a-g)||(d.scale(this._tmpRayDir,this._tmpRayDir,c),b.eye=d.subtract(t,e,this._tmpRayDir),b.center=d.lerp(t,b.center,e,1-c),A.applyAll(this.view,b,this._constraintOptions)))};return m}(E.PointToPointAnimationController);h.ZoomStepController=v.__decorate([z.subclass("esri.views.3d.state.controllers.local.ZoomStepController")],h.ZoomStepController);const t=f.create(),H=f.fromValues(0,0,1),l=f.create();Object.defineProperty(h,
Symbol.toStringTag,{value:"Module"})});